export interface CatalogTeam {
  name: string;
  conference: string;
}

export const CATALOG_TEAMS: CatalogTeam[] = [
  // SEC (16)
  { name: "LSU",                    conference: "SEC" },
  { name: "Florida",                conference: "SEC" },
  { name: "Vanderbilt",             conference: "SEC" },
  { name: "Texas A&M",              conference: "SEC" },
  { name: "Tennessee",              conference: "SEC" },
  { name: "Ole Miss",               conference: "SEC" },
  { name: "Arkansas",               conference: "SEC" },
  { name: "Alabama",                conference: "SEC" },
  { name: "Auburn",                 conference: "SEC" },
  { name: "Georgia",                conference: "SEC" },
  { name: "Mississippi State",      conference: "SEC" },
  { name: "South Carolina",         conference: "SEC" },
  { name: "Kentucky",               conference: "SEC" },
  { name: "Missouri",               conference: "SEC" },
  { name: "Oklahoma",               conference: "SEC" },
  { name: "Texas",                  conference: "SEC" },
  // ACC (16)
  { name: "Clemson",                conference: "ACC" },
  { name: "Duke",                   conference: "ACC" },
  { name: "Florida State",          conference: "ACC" },
  { name: "Georgia Tech",           conference: "ACC" },
  { name: "Louisville",             conference: "ACC" },
  { name: "Miami",                  conference: "ACC" },
  { name: "NC State",               conference: "ACC" },
  { name: "North Carolina",         conference: "ACC" },
  { name: "Notre Dame",             conference: "ACC" },
  { name: "Pittsburgh",             conference: "ACC" },
  { name: "California",             conference: "ACC" },
  { name: "Stanford",               conference: "ACC" },
  { name: "Virginia",               conference: "ACC" },
  { name: "Virginia Tech",          conference: "ACC" },
  { name: "Wake Forest",            conference: "ACC" },
  { name: "Boston College",         conference: "ACC" },
  // Big Ten (17)
  { name: "Illinois",               conference: "Big Ten" },
  { name: "Indiana",                conference: "Big Ten" },
  { name: "Iowa",                   conference: "Big Ten" },
  { name: "Maryland",               conference: "Big Ten" },
  { name: "Michigan",               conference: "Big Ten" },
  { name: "Michigan State",         conference: "Big Ten" },
  { name: "Minnesota",              conference: "Big Ten" },
  { name: "Nebraska",               conference: "Big Ten" },
  { name: "Northwestern",           conference: "Big Ten" },
  { name: "Ohio State",             conference: "Big Ten" },
  { name: "Oregon",                 conference: "Big Ten" },
  { name: "Penn State",             conference: "Big Ten" },
  { name: "Purdue",                 conference: "Big Ten" },
  { name: "Rutgers",                conference: "Big Ten" },
  { name: "USC",                    conference: "Big Ten" },
  { name: "UCLA",                   conference: "Big Ten" },
  { name: "Washington",             conference: "Big Ten" },
  // Big 12 (14)
  { name: "Kansas",                 conference: "Big 12" },
  { name: "West Virginia",          conference: "Big 12" },
  { name: "Arizona State",          conference: "Big 12" },
  { name: "Arizona",                conference: "Big 12" },
  { name: "Baylor",                 conference: "Big 12" },
  { name: "BYU",                    conference: "Big 12" },
  { name: "Cincinnati",             conference: "Big 12" },
  { name: "Houston",                conference: "Big 12" },
  { name: "Kansas State",           conference: "Big 12" },
  { name: "Oklahoma State",         conference: "Big 12" },
  { name: "TCU",                    conference: "Big 12" },
  { name: "Texas Tech",             conference: "Big 12" },
  { name: "UCF",                    conference: "Big 12" },
  { name: "Utah",                   conference: "Big 12" },
  // Pac-12 (8: includes former Mountain West teams)
  { name: "Oregon State",           conference: "Pac-12" },
  { name: "Washington State",       conference: "Pac-12" },
  { name: "Fresno State",           conference: "Pac-12" },
  { name: "San Diego State",        conference: "Pac-12" },
  { name: "UNLV",                   conference: "Pac-12" },
  { name: "Nevada",                 conference: "Pac-12" },
  { name: "New Mexico",             conference: "Pac-12" },
  { name: "Air Force",              conference: "Pac-12" },
  // AAC (11)
  { name: "East Carolina",          conference: "AAC" },
  { name: "Wichita State",          conference: "AAC" },
  { name: "Tulane",                 conference: "AAC" },
  { name: "Memphis",                conference: "AAC" },
  { name: "South Florida",          conference: "AAC" },
  { name: "Charlotte",              conference: "AAC" },
  { name: "UAB",                    conference: "AAC" },
  { name: "Rice",                   conference: "AAC" },
  { name: "Florida Atlantic",       conference: "AAC" },
  { name: "North Texas",            conference: "AAC" },
  { name: "Dallas Baptist",         conference: "AAC" },
  // Sun Belt (12)
  { name: "Coastal Carolina",       conference: "Sun Belt" },
  { name: "Southern Miss",          conference: "Sun Belt" },
  { name: "Troy",                   conference: "Sun Belt" },
  { name: "Marshall",               conference: "Sun Belt" },
  { name: "Louisiana",              conference: "Sun Belt" },
  { name: "Old Dominion",           conference: "Sun Belt" },
  { name: "Arkansas State",         conference: "Sun Belt" },
  { name: "Georgia Southern",       conference: "Sun Belt" },
  { name: "App State",              conference: "Sun Belt" },
  { name: "Georgia State",          conference: "Sun Belt" },
  { name: "South Alabama",          conference: "Sun Belt" },
  { name: "James Madison",          conference: "Sun Belt" },
  // WCC (8)
  { name: "Pepperdine",             conference: "WCC" },
  { name: "Loyola Marymount",       conference: "WCC" },
  { name: "San Diego",              conference: "WCC" },
  { name: "Saint Mary's",           conference: "WCC" },
  { name: "Gonzaga",                conference: "WCC" },
  { name: "Santa Clara",            conference: "WCC" },
  { name: "Portland",               conference: "WCC" },
  { name: "San Francisco",          conference: "WCC" },
  // Big West (10)
  { name: "Cal State Fullerton",    conference: "Big West" },
  { name: "Long Beach State",       conference: "Big West" },
  { name: "UC Irvine",              conference: "Big West" },
  { name: "UC Santa Barbara",       conference: "Big West" },
  { name: "UC San Diego",           conference: "Big West" },
  { name: "Hawaii",                 conference: "Big West" },
  { name: "Cal Poly",               conference: "Big West" },
  { name: "UC Davis",               conference: "Big West" },
  { name: "Cal State Northridge",   conference: "Big West" },
  { name: "Cal State Bakersfield",  conference: "Big West" },
  // Missouri Valley (13)
  { name: "Missouri State",         conference: "Missouri Valley" },
  { name: "Indiana State",          conference: "Missouri Valley" },
  { name: "Illinois State",         conference: "Missouri Valley" },
  { name: "Southern Illinois",      conference: "Missouri Valley" },
  { name: "Bradley",                conference: "Missouri Valley" },
  { name: "Evansville",             conference: "Missouri Valley" },
  { name: "Valparaiso",             conference: "Missouri Valley" },
  { name: "UIC",                    conference: "Missouri Valley" },
  { name: "Belmont",                conference: "Missouri Valley" },
  { name: "Murray State",           conference: "Missouri Valley" },
  { name: "Western Illinois",       conference: "Missouri Valley" },
  { name: "Northern Iowa",          conference: "Missouri Valley" },
  { name: "Creighton",              conference: "Missouri Valley" },
  // Ivy League (8)
  { name: "Columbia",               conference: "Ivy League" },
  { name: "Cornell",                conference: "Ivy League" },
  { name: "Dartmouth",              conference: "Ivy League" },
  { name: "Harvard",                conference: "Ivy League" },
  { name: "Penn",                   conference: "Ivy League" },
  { name: "Princeton",              conference: "Ivy League" },
  { name: "Yale",                   conference: "Ivy League" },
  { name: "Brown",                  conference: "Ivy League" },
  // HBCU (16)
  { name: "Grambling State",        conference: "HBCU" },
  { name: "Southern University",    conference: "HBCU" },
  { name: "Florida A&M",            conference: "HBCU" },
  { name: "Bethune-Cookman",        conference: "HBCU" },
  { name: "Jackson State",          conference: "HBCU" },
  { name: "North Carolina A&T",     conference: "HBCU" },
  { name: "Alabama State",          conference: "HBCU" },
  { name: "Norfolk State",          conference: "HBCU" },
  { name: "Alcorn State",           conference: "HBCU" },
  { name: "Prairie View A&M",       conference: "HBCU" },
  { name: "Texas Southern",         conference: "HBCU" },
  { name: "Howard",                 conference: "HBCU" },
  { name: "Delaware State",         conference: "HBCU" },
  { name: "Coppin State",           conference: "HBCU" },
  { name: "North Carolina Central", conference: "HBCU" },
  { name: "Maryland Eastern Shore", conference: "HBCU" },
];

export const TEAM_CONFERENCE_MAP: ReadonlyMap<string, string> = new Map(
  CATALOG_TEAMS.map(t => [t.name, t.conference]),
);

export const CATALOG_TEAM_NAMES: readonly string[] = CATALOG_TEAMS.map(t => t.name);
