import { RealPlayer } from "./realRosters";

function pitchMix(primary: number, secondary: number[]): { pitchFB: number; pitch2S: number; pitchSL: number; pitchCB: number; pitchCH: number; pitchCT: number; pitchSNK: number; pitchSPL: number } {
  return { pitchFB: primary, pitch2S: secondary[0] || 0, pitchSL: secondary[1] || 0, pitchCB: secondary[2] || 0, pitchCH: secondary[3] || 0, pitchCT: secondary[4] || 0, pitchSNK: secondary[5] || 0, pitchSPL: secondary[6] || 0 };
}
const noPitches = { pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0 };

export const ACC_BATCH2_ROSTERS: Record<string, RealPlayer[]> = {
  "Miami": [
    // PITCHERS (8)
    { firstName: "Ryan", lastName: "Bilka", position: "P", eligibility: "JR", homeState: "VA", hometown: "Richmond", jerseyNumber: 34,
      hitForAvg: 20, power: 16, speed: 40, arm: 80, fielding: 50, errorResistance: 52, velocity: 82, control: 78, stamina: 78, stuff: 80,
      clutch: 74, vsLHP: 70, grit: 76, stealing: 12, running: 36, throwing: 78, recovery: 70, wRISP: 72, vsLefty: 72, poise: 76, heater: 80, agile: 44,
      abilities: ["Ace", "Strong Starter"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [1, 6, 4, 5, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Dorn", position: "P", eligibility: "JR", homeState: "FL", hometown: "Fort Lauderdale", jerseyNumber: 29,
      hitForAvg: 18, power: 14, speed: 42, arm: 78, fielding: 48, errorResistance: 50, velocity: 80, control: 76, stamina: 76, stuff: 78,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 14, running: 38, throwing: 76, recovery: 68, wRISP: 70, vsLefty: 70, poise: 74, heater: 78, agile: 46,
      abilities: ["Strong Starter", "Workhorse"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "AJ", lastName: "Ciscar", position: "P", eligibility: "SO", homeState: "FL", hometown: "Orlando", jerseyNumber: 41,
      hitForAvg: 18, power: 14, speed: 44, arm: 74, fielding: 46, errorResistance: 48, velocity: 78, control: 70, stamina: 70, stuff: 74,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 14, running: 40, throwing: 72, recovery: 64, wRISP: 64, vsLefty: 66, poise: 68, heater: 76, agile: 48,
      abilities: ["Guts"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 4, 5, 0, 0, 0]) },
    { firstName: "TJ", lastName: "Coats", position: "P", eligibility: "JR", homeState: "FL", hometown: "Tampa", jerseyNumber: 27,
      hitForAvg: 16, power: 14, speed: 40, arm: 74, fielding: 44, errorResistance: 48, velocity: 76, control: 72, stamina: 72, stuff: 74,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 12, running: 36, throwing: 72, recovery: 64, wRISP: 64, vsLefty: 64, poise: 68, heater: 74, agile: 44,
      abilities: ["Workhorse"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Tate", lastName: "DeRias", position: "P", eligibility: "SO", homeState: "FL", hometown: "Jacksonville", jerseyNumber: 38,
      hitForAvg: 16, power: 14, speed: 42, arm: 72, fielding: 44, errorResistance: 46, velocity: 76, control: 68, stamina: 68, stuff: 72,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 14, running: 38, throwing: 70, recovery: 60, wRISP: 60, vsLefty: 62, poise: 64, heater: 74, agile: 46,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Frank", lastName: "Menendez", position: "P", eligibility: "JR", homeState: "FL", hometown: "Hialeah", jerseyNumber: 36,
      hitForAvg: 16, power: 14, speed: 38, arm: 72, fielding: 44, errorResistance: 46, velocity: 74, control: 68, stamina: 62, stuff: 72,
      clutch: 60, vsLHP: 58, grit: 64, stealing: 12, running: 34, throwing: 70, recovery: 56, wRISP: 58, vsLefty: 60, poise: 62, heater: 72, agile: 42,
      abilities: ["Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 4, 0, 0, 0]) },
    { firstName: "Lyndon", lastName: "Glidewell", position: "P", eligibility: "JR", homeState: "FL", hometown: "Pembroke Pines", jerseyNumber: 44,
      hitForAvg: 16, power: 14, speed: 40, arm: 70, fielding: 44, errorResistance: 46, velocity: 74, control: 66, stamina: 64, stuff: 70,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 12, running: 36, throwing: 68, recovery: 58, wRISP: 58, vsLefty: 60, poise: 62, heater: 72, agile: 44,
      abilities: ["Fireman"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 5, 3, 0, 0]) },
    { firstName: "Marco", lastName: "Reyes", position: "P", eligibility: "FR", homeState: "FL", hometown: "Coral Gables", jerseyNumber: 48,
      hitForAvg: 14, power: 12, speed: 42, arm: 68, fielding: 40, errorResistance: 42, velocity: 74, control: 58, stamina: 54, stuff: 66,
      clutch: 46, vsLHP: 44, grit: 48, stealing: 14, running: 40, throwing: 66, recovery: 46, wRISP: 44, vsLefty: 48, poise: 46, heater: 72, agile: 46,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 3, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Alex", lastName: "Sosa", position: "C", eligibility: "JR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 12,
      hitForAvg: 62, power: 58, speed: 40, arm: 68, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 18, running: 38, throwing: 70, recovery: 54, wRISP: 66, vsLefty: 60, poise: 64, heater: 0, agile: 44,
      abilities: ["Clutch Hitter"], potential: "A-", catcherAbility: 66,
      ...noPitches },
    { firstName: "Alonzo", lastName: "Alvarez", position: "C", eligibility: "FR", homeState: "FL", hometown: "Miami", jerseyNumber: 25,
      hitForAvg: 46, power: 42, speed: 42, arm: 62, fielding: 56, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 18, running: 40, throwing: 64, recovery: 42, wRISP: 46, vsLefty: 44, poise: 46, heater: 0, agile: 44,
      abilities: ["Switch Hitter"], potential: "A-", catcherAbility: 60,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Daniel", lastName: "Cuvet", position: "3B", eligibility: "JR", homeState: "FL", hometown: "Miami", jerseyNumber: 5,
      hitForAvg: 82, power: 78, speed: 54, arm: 68, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 84, vsLHP: 78, grit: 82, stealing: 24, running: 52, throwing: 70, recovery: 62, wRISP: 84, vsLefty: 76, poise: 80, heater: 0, agile: 56,
      abilities: ["Power Surge", "Clutch Hitter"], potential: "A+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jake", lastName: "Ogden", position: "2B", eligibility: "JR", homeState: "FL", hometown: "Boca Raton", jerseyNumber: 3,
      hitForAvg: 72, power: 56, speed: 64, arm: 62, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 44, running: 62, throwing: 64, recovery: 56, wRISP: 70, vsLefty: 64, poise: 68, heater: 0, agile: 66,
      abilities: ["Contact Machine", "Table Setter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Brylan", lastName: "West", position: "1B", eligibility: "JR", homeState: "FL", hometown: "Homestead", jerseyNumber: 24,
      hitForAvg: 70, power: 64, speed: 44, arm: 58, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 16, running: 42, throwing: 60, recovery: 54, wRISP: 68, vsLefty: 62, poise: 66, heater: 0, agile: 46,
      abilities: ["Power Surge"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Vance", lastName: "Sheahan", position: "SS", eligibility: "JR", homeState: "SC", hometown: "Spartanburg", jerseyNumber: 6,
      hitForAvg: 70, power: 62, speed: 68, arm: 70, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 52, running: 66, throwing: 72, recovery: 58, wRISP: 72, vsLefty: 66, poise: 70, heater: 0, agile: 70,
      abilities: ["Speed Demon", "Clutch Hitter"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Cian", lastName: "Copeland", position: "3B", eligibility: "JR", homeState: "FL", hometown: "Miami", jerseyNumber: 18,
      hitForAvg: 74, power: 66, speed: 54, arm: 64, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 22, running: 52, throwing: 66, recovery: 56, wRISP: 72, vsLefty: 66, poise: 70, heater: 0, agile: 56,
      abilities: ["Power Surge"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Carlos", lastName: "Rivera", position: "SS", eligibility: "FR", homeState: "FL", hometown: "Kendall", jerseyNumber: 9,
      hitForAvg: 44, power: 36, speed: 60, arm: 60, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 40, grit: 46, stealing: 34, running: 58, throwing: 62, recovery: 40, wRISP: 42, vsLefty: 38, poise: 42, heater: 0, agile: 62,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (9)
    { firstName: "Derek", lastName: "Williams", position: "OF", eligibility: "SR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 1,
      hitForAvg: 68, power: 56, speed: 62, arm: 68, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 36, running: 60, throwing: 70, recovery: 56, wRISP: 66, vsLefty: 62, poise: 66, heater: 0, agile: 64,
      abilities: ["Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Max", lastName: "Galvin", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Naples", jerseyNumber: 10,
      hitForAvg: 66, power: 54, speed: 58, arm: 66, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 30, running: 56, throwing: 68, recovery: 52, wRISP: 64, vsLefty: 58, poise: 62, heater: 0, agile: 60,
      abilities: ["Clutch Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Fabio", lastName: "Peralta", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Hialeah", jerseyNumber: 21,
      hitForAvg: 56, power: 48, speed: 60, arm: 64, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 34, running: 58, throwing: 66, recovery: 50, wRISP: 56, vsLefty: 52, poise: 56, heater: 0, agile: 62,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jailen", lastName: "Watkins", position: "OF", eligibility: "FR", homeState: "FL", hometown: "Fort Lauderdale", jerseyNumber: 30,
      hitForAvg: 48, power: 42, speed: 68, arm: 62, fielding: 56, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 46, vsLHP: 42, grit: 48, stealing: 42, running: 66, throwing: 64, recovery: 42, wRISP: 44, vsLefty: 40, poise: 44, heater: 0, agile: 70,
      abilities: ["Speed Demon"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Dario", lastName: "Gonzalez", position: "OF", eligibility: "FR", homeState: "FL", hometown: "Doral", jerseyNumber: 32,
      hitForAvg: 42, power: 38, speed: 58, arm: 60, fielding: 52, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 38, grit: 44, stealing: 32, running: 56, throwing: 62, recovery: 40, wRISP: 40, vsLefty: 36, poise: 40, heater: 0, agile: 60,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Brandon", lastName: "Cruz", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Plantation", jerseyNumber: 16,
      hitForAvg: 54, power: 48, speed: 58, arm: 64, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 30, running: 56, throwing: 66, recovery: 48, wRISP: 54, vsLefty: 50, poise: 54, heater: 0, agile: 60,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Luis", lastName: "Medina", position: "OF", eligibility: "SO", homeState: "FL", hometown: "Coral Springs", jerseyNumber: 20,
      hitForAvg: 50, power: 44, speed: 56, arm: 62, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 28, running: 54, throwing: 64, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 58,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Tommy", lastName: "Santiago", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Coconut Grove", jerseyNumber: 7,
      hitForAvg: 52, power: 46, speed: 54, arm: 62, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 28, running: 52, throwing: 64, recovery: 46, wRISP: 52, vsLefty: 48, poise: 52, heater: 0, agile: 56,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Anthony", lastName: "Perez", position: "OF", eligibility: "SO", homeState: "FL", hometown: "Weston", jerseyNumber: 8,
      hitForAvg: 48, power: 42, speed: 56, arm: 60, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 30, running: 54, throwing: 62, recovery: 44, wRISP: 48, vsLefty: 44, poise: 48, heater: 0, agile: 58,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "NC State": [
    // PITCHERS (8)
    { firstName: "Ryan", lastName: "Marohn", position: "P", eligibility: "JR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 34,
      hitForAvg: 20, power: 16, speed: 40, arm: 82, fielding: 50, errorResistance: 52, velocity: 84, control: 78, stamina: 80, stuff: 82,
      clutch: 76, vsLHP: 72, grit: 78, stealing: 14, running: 36, throwing: 80, recovery: 72, wRISP: 74, vsLefty: 74, poise: 78, heater: 82, agile: 44,
      abilities: ["Ace", "Strong Starter"], potential: "A+", catcherAbility: null,
      ...pitchMix(1, [1, 6, 4, 5, 0, 0, 0]) },
    { firstName: "Jacob", lastName: "Dudan", position: "P", eligibility: "JR", homeState: "NC", hometown: "Cary", jerseyNumber: 38,
      hitForAvg: 18, power: 14, speed: 42, arm: 76, fielding: 48, errorResistance: 50, velocity: 78, control: 72, stamina: 74, stuff: 76,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 14, running: 38, throwing: 74, recovery: 66, wRISP: 66, vsLefty: 66, poise: 70, heater: 76, agile: 46,
      abilities: ["Strong Starter"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Cam", lastName: "Andrews", position: "P", eligibility: "JR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 29,
      hitForAvg: 18, power: 14, speed: 40, arm: 74, fielding: 46, errorResistance: 48, velocity: 76, control: 70, stamina: 72, stuff: 74,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 12, running: 36, throwing: 72, recovery: 64, wRISP: 64, vsLefty: 64, poise: 68, heater: 74, agile: 44,
      abilities: ["Workhorse"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 4, 0, 0, 0]) },
    { firstName: "Anderson", lastName: "Nance", position: "P", eligibility: "JR", homeState: "GA", hometown: "Alpharetta", jerseyNumber: 27,
      hitForAvg: 16, power: 14, speed: 44, arm: 78, fielding: 44, errorResistance: 48, velocity: 80, control: 72, stamina: 62, stuff: 78,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 16, running: 40, throwing: 76, recovery: 60, wRISP: 70, vsLefty: 70, poise: 74, heater: 78, agile: 48,
      abilities: ["Fireman", "Explosive Fastball"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 7, 0, 5, 3, 0, 0]) },
    { firstName: "Collins", lastName: "Black", position: "P", eligibility: "JR", homeState: "NC", hometown: "Greensboro", jerseyNumber: 41,
      hitForAvg: 16, power: 14, speed: 38, arm: 70, fielding: 44, errorResistance: 48, velocity: 74, control: 68, stamina: 64, stuff: 70,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 12, running: 34, throwing: 68, recovery: 60, wRISP: 60, vsLefty: 62, poise: 64, heater: 72, agile: 42,
      abilities: ["Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Vincent", lastName: "Decarlo", position: "P", eligibility: "FR", homeState: "NJ", hometown: "Toms River", jerseyNumber: 45,
      hitForAvg: 14, power: 12, speed: 42, arm: 68, fielding: 40, errorResistance: 42, velocity: 74, control: 58, stamina: 54, stuff: 66,
      clutch: 46, vsLHP: 44, grit: 48, stealing: 14, running: 40, throwing: 66, recovery: 46, wRISP: 44, vsLefty: 48, poise: 46, heater: 72, agile: 46,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 3, 0, 0, 0]) },
    { firstName: "Sam", lastName: "Harris", position: "P", eligibility: "FR", homeState: "NC", hometown: "Durham", jerseyNumber: 47,
      hitForAvg: 14, power: 12, speed: 40, arm: 66, fielding: 38, errorResistance: 40, velocity: 72, control: 56, stamina: 52, stuff: 64,
      clutch: 44, vsLHP: 42, grit: 46, stealing: 12, running: 38, throwing: 64, recovery: 44, wRISP: 42, vsLefty: 46, poise: 44, heater: 70, agile: 44,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 3, 0, 0, 0]) },
    { firstName: "Aiden", lastName: "Kitchings", position: "P", eligibility: "FR", homeState: "NC", hometown: "Apex", jerseyNumber: 48,
      hitForAvg: 14, power: 12, speed: 44, arm: 66, fielding: 38, errorResistance: 40, velocity: 72, control: 56, stamina: 52, stuff: 64,
      clutch: 44, vsLHP: 42, grit: 46, stealing: 16, running: 42, throwing: 64, recovery: 44, wRISP: 42, vsLefty: 46, poise: 44, heater: 70, agile: 48,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 3, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Brandon", lastName: "Crabtree", position: "C", eligibility: "JR", homeState: "NC", hometown: "Wake Forest", jerseyNumber: 12,
      hitForAvg: 54, power: 46, speed: 38, arm: 66, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 64, stealing: 16, running: 36, throwing: 68, recovery: 52, wRISP: 58, vsLefty: 54, poise: 60, heater: 0, agile: 42,
      abilities: ["Cannon Arm"], potential: "B+", catcherAbility: 64,
      ...noPitches },
    { firstName: "Garrett", lastName: "Payne", position: "C", eligibility: "SO", homeState: "NC", hometown: "Wilmington", jerseyNumber: 25,
      hitForAvg: 42, power: 38, speed: 36, arm: 60, fielding: 56, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 40, grit: 46, stealing: 14, running: 34, throwing: 58, recovery: 42, wRISP: 42, vsLefty: 38, poise: 42, heater: 0, agile: 38,
      abilities: [], potential: "B", catcherAbility: 58,
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Chris", lastName: "McHugh", position: "1B", eligibility: "JR", homeState: "PA", hometown: "Philadelphia", jerseyNumber: 18,
      hitForAvg: 68, power: 70, speed: 42, arm: 58, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 16, running: 40, throwing: 60, recovery: 56, wRISP: 70, vsLefty: 64, poise: 68, heater: 0, agile: 44,
      abilities: ["Power Surge"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Mikey", lastName: "Ryan", position: "SS", eligibility: "JR", homeState: "CA", hometown: "San Clemente", jerseyNumber: 6,
      hitForAvg: 64, power: 52, speed: 64, arm: 70, fielding: 70, errorResistance: 68, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 42, running: 62, throwing: 72, recovery: 54, wRISP: 64, vsLefty: 60, poise: 66, heater: 0, agile: 66,
      abilities: ["Iron Glove"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Luke", lastName: "Nixon", position: "2B", eligibility: "JR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 3,
      hitForAvg: 58, power: 44, speed: 56, arm: 60, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 32, running: 54, throwing: 62, recovery: 50, wRISP: 58, vsLefty: 54, poise: 58, heater: 0, agile: 58,
      abilities: ["Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Sherman", lastName: "Johnson", position: "3B", eligibility: "SO", homeState: "TX", hometown: "Houston", jerseyNumber: 15,
      hitForAvg: 54, power: 50, speed: 50, arm: 62, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 24, running: 48, throwing: 64, recovery: 48, wRISP: 54, vsLefty: 50, poise: 54, heater: 0, agile: 52,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Dalton", lastName: "Bargo", position: "1B", eligibility: "JR", homeState: "TN", hometown: "Knoxville", jerseyNumber: 24,
      hitForAvg: 60, power: 64, speed: 40, arm: 56, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 14, running: 38, throwing: 58, recovery: 52, wRISP: 64, vsLefty: 58, poise: 62, heater: 0, agile: 42,
      abilities: ["Clutch Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Wyatt", lastName: "Peifer", position: "3B", eligibility: "SR", homeState: "VA", hometown: "Harrisonburg", jerseyNumber: 11,
      hitForAvg: 56, power: 52, speed: 46, arm: 62, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 20, running: 44, throwing: 64, recovery: 50, wRISP: 56, vsLefty: 52, poise: 56, heater: 0, agile: 48,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Mikey", lastName: "Ragusa", position: "SS", eligibility: "FR", homeState: "NJ", hometown: "Middletown", jerseyNumber: 9,
      hitForAvg: 42, power: 36, speed: 56, arm: 58, fielding: 52, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 40, grit: 46, stealing: 30, running: 54, throwing: 60, recovery: 40, wRISP: 42, vsLefty: 38, poise: 42, heater: 0, agile: 58,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (8)
    { firstName: "Ty", lastName: "Head", position: "OF", eligibility: "SO", homeState: "TX", hometown: "Grapevine", jerseyNumber: 4,
      hitForAvg: 62, power: 48, speed: 72, arm: 70, fielding: 72, errorResistance: 70, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 68, stealing: 50, running: 70, throwing: 72, recovery: 56, wRISP: 62, vsLefty: 58, poise: 64, heater: 0, agile: 74,
      abilities: ["Table Setter", "Iron Glove"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Brayden", lastName: "Fraasman", position: "OF", eligibility: "JR", homeState: "NC", hometown: "Fuquay-Varina", jerseyNumber: 21,
      hitForAvg: 56, power: 48, speed: 60, arm: 64, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 34, running: 58, throwing: 66, recovery: 50, wRISP: 56, vsLefty: 52, poise: 56, heater: 0, agile: 62,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Andrew", lastName: "Wiggins", position: "OF", eligibility: "JR", homeState: "GA", hometown: "Marietta", jerseyNumber: 10,
      hitForAvg: 54, power: 50, speed: 58, arm: 66, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 32, running: 56, throwing: 68, recovery: 48, wRISP: 54, vsLefty: 50, poise: 54, heater: 0, agile: 60,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Rett", lastName: "Johnson", position: "OF", eligibility: "FR", homeState: "NC", hometown: "Huntersville", jerseyNumber: 1,
      hitForAvg: 52, power: 48, speed: 66, arm: 64, fielding: 58, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 40, running: 64, throwing: 66, recovery: 46, wRISP: 48, vsLefty: 44, poise: 48, heater: 0, agile: 68,
      abilities: ["Speed Demon"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Marcus", lastName: "Greer", position: "OF", eligibility: "JR", homeState: "NC", hometown: "Garner", jerseyNumber: 8,
      hitForAvg: 52, power: 44, speed: 56, arm: 62, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 30, running: 54, throwing: 64, recovery: 46, wRISP: 52, vsLefty: 48, poise: 52, heater: 0, agile: 58,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Kyle", lastName: "Fitzgerald", position: "OF", eligibility: "JR", homeState: "VA", hometown: "Richmond", jerseyNumber: 20,
      hitForAvg: 48, power: 42, speed: 54, arm: 60, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 28, running: 52, throwing: 62, recovery: 44, wRISP: 48, vsLefty: 44, poise: 48, heater: 0, agile: 56,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Tyler", lastName: "Barnes", position: "OF", eligibility: "SO", homeState: "NC", hometown: "Concord", jerseyNumber: 32,
      hitForAvg: 46, power: 40, speed: 58, arm: 58, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 44, grit: 50, stealing: 32, running: 56, throwing: 60, recovery: 44, wRISP: 46, vsLefty: 42, poise: 46, heater: 0, agile: 60,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Josh", lastName: "Hogue", position: "OF", eligibility: "JR", homeState: "NC", hometown: "Wake Forest", jerseyNumber: 7,
      hitForAvg: 50, power: 44, speed: 56, arm: 62, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 30, running: 54, throwing: 64, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 58,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "North Carolina": [
    // PITCHERS (7)
    { firstName: "Jason", lastName: "DeCaro", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Wayne", jerseyNumber: 34,
      hitForAvg: 20, power: 16, speed: 42, arm: 82, fielding: 50, errorResistance: 52, velocity: 84, control: 78, stamina: 80, stuff: 82,
      clutch: 76, vsLHP: 72, grit: 78, stealing: 14, running: 38, throwing: 80, recovery: 72, wRISP: 74, vsLefty: 74, poise: 78, heater: 82, agile: 46,
      abilities: ["Ace", "Explosive Fastball"], potential: "A+", catcherAbility: null,
      ...pitchMix(1, [1, 6, 4, 5, 0, 0, 0]) },
    { firstName: "Folger", lastName: "Boaz", position: "P", eligibility: "JR", homeState: "NC", hometown: "Greensboro", jerseyNumber: 29,
      hitForAvg: 18, power: 14, speed: 40, arm: 78, fielding: 48, errorResistance: 50, velocity: 80, control: 74, stamina: 76, stuff: 78,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 12, running: 36, throwing: 76, recovery: 68, wRISP: 68, vsLefty: 68, poise: 72, heater: 78, agile: 44,
      abilities: ["Strong Starter"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 5, 6, 4, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Lynch", position: "P", eligibility: "SO", homeState: "NC", hometown: "Durham", jerseyNumber: 41,
      hitForAvg: 18, power: 14, speed: 44, arm: 76, fielding: 46, errorResistance: 48, velocity: 78, control: 72, stamina: 72, stuff: 76,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 14, running: 40, throwing: 74, recovery: 64, wRISP: 64, vsLefty: 66, poise: 68, heater: 76, agile: 48,
      abilities: ["Workhorse"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 6, 4, 5, 0, 0, 0]) },
    { firstName: "Walker", lastName: "McDuffie", position: "P", eligibility: "SO", homeState: "NC", hometown: "Charlotte", jerseyNumber: 27,
      hitForAvg: 16, power: 14, speed: 42, arm: 74, fielding: 44, errorResistance: 48, velocity: 76, control: 70, stamina: 68, stuff: 74,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 14, running: 38, throwing: 72, recovery: 62, wRISP: 62, vsLefty: 64, poise: 66, heater: 74, agile: 46,
      abilities: ["Guts"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Cam", lastName: "Seagraves", position: "P", eligibility: "JR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 44,
      hitForAvg: 16, power: 14, speed: 38, arm: 70, fielding: 44, errorResistance: 46, velocity: 74, control: 66, stamina: 64, stuff: 70,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 12, running: 34, throwing: 68, recovery: 58, wRISP: 58, vsLefty: 60, poise: 62, heater: 72, agile: 42,
      abilities: ["Fireman"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 5, 3, 0, 0]) },
    { firstName: "Ethan", lastName: "Brewer", position: "P", eligibility: "FR", homeState: "SC", hometown: "Greenville", jerseyNumber: 36,
      hitForAvg: 14, power: 12, speed: 42, arm: 68, fielding: 40, errorResistance: 42, velocity: 74, control: 58, stamina: 54, stuff: 66,
      clutch: 46, vsLHP: 44, grit: 48, stealing: 14, running: 40, throwing: 66, recovery: 46, wRISP: 44, vsLefty: 48, poise: 46, heater: 72, agile: 46,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 3, 0, 0, 0]) },
    { firstName: "Camden", lastName: "Foster", position: "P", eligibility: "FR", homeState: "MD", hometown: "Bethesda", jerseyNumber: 38,
      hitForAvg: 14, power: 12, speed: 40, arm: 66, fielding: 38, errorResistance: 40, velocity: 72, control: 56, stamina: 52, stuff: 64,
      clutch: 44, vsLHP: 42, grit: 46, stealing: 12, running: 38, throwing: 64, recovery: 44, wRISP: 42, vsLefty: 46, poise: 44, heater: 70, agile: 44,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 3, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Macon", lastName: "Winslow", position: "C", eligibility: "JR", homeState: "NC", hometown: "Durham", jerseyNumber: 8,
      hitForAvg: 62, power: 58, speed: 38, arm: 68, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 16, running: 36, throwing: 70, recovery: 54, wRISP: 66, vsLefty: 60, poise: 64, heater: 0, agile: 42,
      abilities: ["Clutch Hitter"], potential: "A-", catcherAbility: 66,
      ...noPitches },
    { firstName: "Colin", lastName: "Hynek", position: "C", eligibility: "JR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 19,
      hitForAvg: 48, power: 42, speed: 36, arm: 64, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 14, running: 34, throwing: 62, recovery: 44, wRISP: 48, vsLefty: 44, poise: 48, heater: 0, agile: 38,
      abilities: [], potential: "B", catcherAbility: 60,
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Gavin", lastName: "Gallaher", position: "2B", eligibility: "JR", homeState: "NC", hometown: "Chapel Hill", jerseyNumber: 5,
      hitForAvg: 80, power: 68, speed: 62, arm: 68, fielding: 72, errorResistance: 70, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 82, vsLHP: 76, grit: 80, stealing: 38, running: 60, throwing: 70, recovery: 62, wRISP: 82, vsLefty: 74, poise: 78, heater: 0, agile: 64,
      abilities: ["Contact Machine", "Clutch Hitter"], potential: "A+", catcherAbility: null,
      ...noPitches },
    { firstName: "Erik", lastName: "Paulsen", position: "1B", eligibility: "JR", homeState: "NY", hometown: "Stony Brook", jerseyNumber: 24,
      hitForAvg: 60, power: 62, speed: 40, arm: 56, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 14, running: 38, throwing: 58, recovery: 52, wRISP: 62, vsLefty: 56, poise: 60, heater: 0, agile: 42,
      abilities: ["Power Surge"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jake", lastName: "Schaffner", position: "SS", eligibility: "JR", homeState: "ND", hometown: "Fargo", jerseyNumber: 2,
      hitForAvg: 56, power: 44, speed: 58, arm: 64, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 34, running: 56, throwing: 66, recovery: 50, wRISP: 56, vsLefty: 52, poise: 56, heater: 0, agile: 60,
      abilities: ["Iron Glove"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Lee", lastName: "Sowers", position: "3B", eligibility: "SO", homeState: "NC", hometown: "Cary", jerseyNumber: 14,
      hitForAvg: 50, power: 44, speed: 50, arm: 60, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 24, running: 48, throwing: 62, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 52,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Cooper", lastName: "Nicholson", position: "2B", eligibility: "FR", homeState: "NC", hometown: "Pinehurst", jerseyNumber: 11,
      hitForAvg: 44, power: 38, speed: 54, arm: 58, fielding: 52, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 40, grit: 46, stealing: 30, running: 52, throwing: 60, recovery: 40, wRISP: 42, vsLefty: 38, poise: 42, heater: 0, agile: 56,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Bryce", lastName: "Landers", position: "SS", eligibility: "FR", homeState: "VA", hometown: "Virginia Beach", jerseyNumber: 9,
      hitForAvg: 42, power: 36, speed: 56, arm: 56, fielding: 50, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 38, grit: 44, stealing: 32, running: 54, throwing: 58, recovery: 38, wRISP: 40, vsLefty: 36, poise: 40, heater: 0, agile: 58,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "James", lastName: "Whitfield", position: "3B", eligibility: "JR", homeState: "NC", hometown: "Fayetteville", jerseyNumber: 18,
      hitForAvg: 52, power: 48, speed: 48, arm: 62, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 22, running: 46, throwing: 64, recovery: 48, wRISP: 52, vsLefty: 48, poise: 52, heater: 0, agile: 50,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (9)
    { firstName: "Carter", lastName: "French", position: "OF", eligibility: "SR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 1,
      hitForAvg: 64, power: 54, speed: 64, arm: 68, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 40, running: 62, throwing: 70, recovery: 56, wRISP: 64, vsLefty: 60, poise: 66, heater: 0, agile: 66,
      abilities: ["Table Setter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Owen", lastName: "Hull", position: "OF", eligibility: "JR", homeState: "VA", hometown: "Fairfax", jerseyNumber: 10,
      hitForAvg: 58, power: 66, speed: 54, arm: 66, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 26, running: 52, throwing: 68, recovery: 52, wRISP: 62, vsLefty: 56, poise: 60, heater: 0, agile: 56,
      abilities: ["Power Surge"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Michael", lastName: "Maginnis", position: "OF", eligibility: "JR", homeState: "GA", hometown: "Kennesaw", jerseyNumber: 21,
      hitForAvg: 66, power: 72, speed: 70, arm: 68, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 56, running: 68, throwing: 70, recovery: 56, wRISP: 66, vsLefty: 62, poise: 66, heater: 0, agile: 72,
      abilities: ["Power Surge", "Speed Demon"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Sawyer", lastName: "Black", position: "OF", eligibility: "SO", homeState: "NC", hometown: "Winston-Salem", jerseyNumber: 16,
      hitForAvg: 50, power: 44, speed: 58, arm: 62, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 34, running: 56, throwing: 64, recovery: 48, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 60,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Perry", lastName: "Hargett", position: "OF", eligibility: "SO", homeState: "NC", hometown: "Raleigh", jerseyNumber: 26,
      hitForAvg: 48, power: 42, speed: 60, arm: 60, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 36, running: 58, throwing: 62, recovery: 46, wRISP: 48, vsLefty: 44, poise: 48, heater: 0, agile: 62,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Tyler", lastName: "Howe", position: "OF", eligibility: "FR", homeState: "NC", hometown: "Greensboro", jerseyNumber: 30,
      hitForAvg: 44, power: 40, speed: 60, arm: 60, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 40, grit: 46, stealing: 36, running: 58, throwing: 62, recovery: 42, wRISP: 42, vsLefty: 38, poise: 42, heater: 0, agile: 62,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Logan", lastName: "Dorsey", position: "OF", eligibility: "SO", homeState: "VA", hometown: "Roanoke", jerseyNumber: 23,
      hitForAvg: 48, power: 46, speed: 54, arm: 58, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 28, running: 52, throwing: 60, recovery: 44, wRISP: 48, vsLefty: 44, poise: 48, heater: 0, agile: 56,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "Metcalf", position: "OF", eligibility: "JR", homeState: "NC", hometown: "Asheville", jerseyNumber: 32,
      hitForAvg: 50, power: 44, speed: 56, arm: 62, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 30, running: 54, throwing: 64, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 58,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Will", lastName: "Pearson", position: "OF", eligibility: "JR", homeState: "NC", hometown: "Wilmington", jerseyNumber: 22,
      hitForAvg: 46, power: 42, speed: 54, arm: 60, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 44, grit: 50, stealing: 26, running: 52, throwing: 62, recovery: 44, wRISP: 46, vsLefty: 42, poise: 46, heater: 0, agile: 56,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "Notre Dame": [
    // PITCHERS (8)
    { firstName: "Jack", lastName: "Radel", position: "P", eligibility: "JR", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 34,
      hitForAvg: 22, power: 18, speed: 42, arm: 84, fielding: 50, errorResistance: 52, velocity: 88, control: 78, stamina: 80, stuff: 84,
      clutch: 78, vsLHP: 74, grit: 80, stealing: 14, running: 38, throwing: 82, recovery: 72, wRISP: 76, vsLefty: 76, poise: 80, heater: 86, agile: 46,
      abilities: ["Ace", "Explosive Fastball"], potential: "A+", catcherAbility: null,
      ...pitchMix(1, [1, 7, 4, 5, 0, 0, 0]) },
    { firstName: "Ty", lastName: "Uber", position: "P", eligibility: "SR", homeState: "CA", hometown: "Palo Alto", jerseyNumber: 29,
      hitForAvg: 18, power: 14, speed: 40, arm: 78, fielding: 48, errorResistance: 50, velocity: 80, control: 74, stamina: 74, stuff: 76,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 12, running: 36, throwing: 76, recovery: 66, wRISP: 68, vsLefty: 68, poise: 72, heater: 78, agile: 44,
      abilities: ["Strong Starter"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Noah", lastName: "Rooney", position: "P", eligibility: "SR", homeState: "MN", hometown: "Minneapolis", jerseyNumber: 41,
      hitForAvg: 18, power: 14, speed: 38, arm: 76, fielding: 46, errorResistance: 48, velocity: 78, control: 72, stamina: 72, stuff: 74,
      clutch: 66, vsLHP: 64, grit: 70, stealing: 12, running: 34, throwing: 74, recovery: 64, wRISP: 64, vsLefty: 66, poise: 70, heater: 76, agile: 42,
      abilities: ["Workhorse"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 5, 0, 0, 0]) },
    { firstName: "Eli", lastName: "Thurmond", position: "P", eligibility: "SR", homeState: "GA", hometown: "Savannah", jerseyNumber: 27,
      hitForAvg: 16, power: 14, speed: 40, arm: 74, fielding: 46, errorResistance: 48, velocity: 76, control: 70, stamina: 70, stuff: 72,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 12, running: 36, throwing: 72, recovery: 62, wRISP: 64, vsLefty: 64, poise: 68, heater: 74, agile: 44,
      abilities: ["Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Chase", lastName: "Van Ameyde", position: "P", eligibility: "SO", homeState: "IN", hometown: "South Bend", jerseyNumber: 38,
      hitForAvg: 16, power: 14, speed: 42, arm: 72, fielding: 44, errorResistance: 48, velocity: 76, control: 68, stamina: 64, stuff: 72,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 14, running: 38, throwing: 70, recovery: 60, wRISP: 60, vsLefty: 62, poise: 64, heater: 74, agile: 46,
      abilities: ["Filthy Breaking Ball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 7, 3, 4, 0, 0, 0]) },
    { firstName: "Oisin", lastName: "Lee", position: "P", eligibility: "SO", homeState: "IL", hometown: "Chicago", jerseyNumber: 36,
      hitForAvg: 16, power: 14, speed: 44, arm: 74, fielding: 44, errorResistance: 46, velocity: 78, control: 66, stamina: 60, stuff: 74,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 14, running: 40, throwing: 72, recovery: 58, wRISP: 62, vsLefty: 64, poise: 66, heater: 76, agile: 48,
      abilities: ["Fireman"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 5, 3, 0, 0]) },
    { firstName: "Caden", lastName: "Crowell", position: "P", eligibility: "FR", homeState: "IN", hometown: "Valparaiso", jerseyNumber: 45,
      hitForAvg: 14, power: 12, speed: 42, arm: 72, fielding: 40, errorResistance: 42, velocity: 76, control: 60, stamina: 56, stuff: 70,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 14, running: 40, throwing: 70, recovery: 48, wRISP: 46, vsLefty: 50, poise: 48, heater: 74, agile: 46,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Dylan", lastName: "Singleton", position: "P", eligibility: "FR", homeState: "OH", hometown: "Columbus", jerseyNumber: 48,
      hitForAvg: 14, power: 12, speed: 40, arm: 68, fielding: 38, errorResistance: 40, velocity: 72, control: 56, stamina: 52, stuff: 64,
      clutch: 44, vsLHP: 42, grit: 46, stealing: 12, running: 38, throwing: 66, recovery: 44, wRISP: 42, vsLefty: 46, poise: 44, heater: 70, agile: 44,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 3, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Ryan", lastName: "Grogan", position: "C", eligibility: "JR", homeState: "IN", hometown: "Indianapolis", jerseyNumber: 8,
      hitForAvg: 54, power: 48, speed: 38, arm: 66, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 62, stealing: 16, running: 36, throwing: 68, recovery: 52, wRISP: 56, vsLefty: 52, poise: 58, heater: 0, agile: 40,
      abilities: ["Cannon Arm"], potential: "B+", catcherAbility: 64,
      ...noPitches },
    { firstName: "Sean", lastName: "Murray", position: "C", eligibility: "SO", homeState: "IL", hometown: "Naperville", jerseyNumber: 19,
      hitForAvg: 44, power: 40, speed: 36, arm: 62, fielding: 58, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 46, vsLHP: 42, grit: 48, stealing: 14, running: 34, throwing: 60, recovery: 42, wRISP: 44, vsLefty: 40, poise: 44, heater: 0, agile: 38,
      abilities: [], potential: "B", catcherAbility: 58,
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Noah", lastName: "Coy", position: "SS", eligibility: "SO", homeState: "OH", hometown: "Dayton", jerseyNumber: 6,
      hitForAvg: 58, power: 46, speed: 62, arm: 68, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 38, running: 60, throwing: 70, recovery: 52, wRISP: 58, vsLefty: 54, poise: 58, heater: 0, agile: 64,
      abilities: ["Iron Glove"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Parker", lastName: "Brzustewicz", position: "3B", eligibility: "SO", homeState: "MI", hometown: "Ann Arbor", jerseyNumber: 5,
      hitForAvg: 56, power: 50, speed: 50, arm: 64, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 24, running: 48, throwing: 66, recovery: 50, wRISP: 56, vsLefty: 52, poise: 56, heater: 0, agile: 52,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Davis", lastName: "Johnson", position: "1B", eligibility: "JR", homeState: "IN", hometown: "Fort Wayne", jerseyNumber: 18,
      hitForAvg: 54, power: 52, speed: 44, arm: 58, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 62, stealing: 18, running: 42, throwing: 60, recovery: 50, wRISP: 58, vsLefty: 52, poise: 58, heater: 0, agile: 46,
      abilities: ["Clutch Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jamie", lastName: "Zee", position: "2B", eligibility: "FR", homeState: "NJ", hometown: "Oradell", jerseyNumber: 3,
      hitForAvg: 46, power: 38, speed: 58, arm: 58, fielding: 56, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 46, vsLHP: 42, grit: 48, stealing: 34, running: 56, throwing: 60, recovery: 42, wRISP: 44, vsLefty: 40, poise: 44, heater: 0, agile: 60,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Matt", lastName: "Sloan", position: "2B", eligibility: "JR", homeState: "OH", hometown: "Cleveland", jerseyNumber: 14,
      hitForAvg: 50, power: 40, speed: 52, arm: 58, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 28, running: 50, throwing: 60, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 54,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Jack", lastName: "Penney", position: "3B", eligibility: "JR", homeState: "PA", hometown: "Pittsburgh", jerseyNumber: 15,
      hitForAvg: 48, power: 46, speed: 46, arm: 60, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 20, running: 44, throwing: 62, recovery: 44, wRISP: 48, vsLefty: 44, poise: 48, heater: 0, agile: 48,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Tommy", lastName: "O'Brien", position: "SS", eligibility: "JR", homeState: "CT", hometown: "Greenwich", jerseyNumber: 9,
      hitForAvg: 50, power: 42, speed: 56, arm: 62, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 30, running: 54, throwing: 64, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 58,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (8)
    { firstName: "Jared", lastName: "Zimbardo", position: "OF", eligibility: "SR", homeState: "FL", hometown: "Tampa", jerseyNumber: 1,
      hitForAvg: 60, power: 54, speed: 60, arm: 66, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 36, running: 58, throwing: 68, recovery: 54, wRISP: 60, vsLefty: 56, poise: 62, heater: 0, agile: 62,
      abilities: ["Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Bino", lastName: "Watters", position: "OF", eligibility: "FR", homeState: "FL", hometown: "Orlando", jerseyNumber: 24,
      hitForAvg: 48, power: 56, speed: 50, arm: 62, fielding: 52, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 44, grit: 50, stealing: 22, running: 48, throwing: 64, recovery: 42, wRISP: 46, vsLefty: 42, poise: 46, heater: 0, agile: 52,
      abilities: ["Power Surge"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Jayce", lastName: "Lee", position: "OF", eligibility: "FR", homeState: "CA", hometown: "San Diego", jerseyNumber: 21,
      hitForAvg: 42, power: 38, speed: 62, arm: 60, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 38, grit: 44, stealing: 36, running: 60, throwing: 62, recovery: 40, wRISP: 40, vsLefty: 36, poise: 40, heater: 0, agile: 64,
      abilities: ["Speed Demon"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Michael", lastName: "Hogan", position: "OF", eligibility: "JR", homeState: "IN", hometown: "Carmel", jerseyNumber: 10,
      hitForAvg: 54, power: 48, speed: 56, arm: 64, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 30, running: 54, throwing: 66, recovery: 48, wRISP: 54, vsLefty: 50, poise: 54, heater: 0, agile: 58,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Patrick", lastName: "Kelly", position: "OF", eligibility: "JR", homeState: "IL", hometown: "Evanston", jerseyNumber: 16,
      hitForAvg: 52, power: 46, speed: 58, arm: 62, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 32, running: 56, throwing: 64, recovery: 48, wRISP: 52, vsLefty: 48, poise: 52, heater: 0, agile: 60,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Drew", lastName: "Casper", position: "OF", eligibility: "JR", homeState: "MI", hometown: "Grand Rapids", jerseyNumber: 20,
      hitForAvg: 50, power: 44, speed: 54, arm: 62, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 28, running: 52, throwing: 64, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 56,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Brady", lastName: "Walsh", position: "OF", eligibility: "SO", homeState: "OH", hometown: "Toledo", jerseyNumber: 32,
      hitForAvg: 48, power: 42, speed: 56, arm: 60, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 30, running: 54, throwing: 62, recovery: 44, wRISP: 48, vsLefty: 44, poise: 48, heater: 0, agile: 58,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Kevin", lastName: "Burke", position: "OF", eligibility: "JR", homeState: "MA", hometown: "Boston", jerseyNumber: 7,
      hitForAvg: 46, power: 40, speed: 52, arm: 60, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 44, grit: 50, stealing: 26, running: 50, throwing: 62, recovery: 42, wRISP: 46, vsLefty: 42, poise: 46, heater: 0, agile: 54,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "Pittsburgh": [
    // PITCHERS (7)
    { firstName: "David", lastName: "Leslie", position: "P", eligibility: "JR", homeState: "PA", hometown: "Pittsburgh", jerseyNumber: 34,
      hitForAvg: 18, power: 14, speed: 40, arm: 76, fielding: 48, errorResistance: 50, velocity: 78, control: 72, stamina: 74, stuff: 76,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 12, running: 36, throwing: 74, recovery: 66, wRISP: 66, vsLefty: 66, poise: 70, heater: 76, agile: 44,
      abilities: ["Strong Starter"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [1, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Vincent", lastName: "Spizzoucco", position: "P", eligibility: "JR", homeState: "PA", hometown: "Philadelphia", jerseyNumber: 29,
      hitForAvg: 18, power: 14, speed: 38, arm: 74, fielding: 46, errorResistance: 48, velocity: 76, control: 72, stamina: 72, stuff: 74,
      clutch: 66, vsLHP: 64, grit: 68, stealing: 12, running: 34, throwing: 72, recovery: 64, wRISP: 64, vsLefty: 66, poise: 68, heater: 74, agile: 42,
      abilities: ["Workhorse"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 5, 0, 0, 0]) },
    { firstName: "Drew", lastName: "Lafferty", position: "P", eligibility: "JR", homeState: "PA", hometown: "Allentown", jerseyNumber: 41,
      hitForAvg: 16, power: 14, speed: 40, arm: 72, fielding: 46, errorResistance: 48, velocity: 74, control: 70, stamina: 70, stuff: 72,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 12, running: 36, throwing: 70, recovery: 62, wRISP: 62, vsLefty: 64, poise: 66, heater: 72, agile: 44,
      abilities: ["Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Mikey", lastName: "Gray", position: "P", eligibility: "JR", homeState: "PA", hometown: "Erie", jerseyNumber: 27,
      hitForAvg: 16, power: 14, speed: 42, arm: 76, fielding: 44, errorResistance: 48, velocity: 78, control: 70, stamina: 62, stuff: 76,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 14, running: 38, throwing: 74, recovery: 58, wRISP: 68, vsLefty: 68, poise: 72, heater: 76, agile: 46,
      abilities: ["Fireman", "Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 7, 0, 5, 3, 0, 0]) },
    { firstName: "Daniel", lastName: "McAuliff", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Cherry Hill", jerseyNumber: 38,
      hitForAvg: 16, power: 14, speed: 42, arm: 74, fielding: 44, errorResistance: 46, velocity: 76, control: 68, stamina: 60, stuff: 74,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 14, running: 38, throwing: 72, recovery: 56, wRISP: 66, vsLefty: 66, poise: 70, heater: 74, agile: 46,
      abilities: ["Fireman"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 5, 3, 0, 0]) },
    { firstName: "Jake", lastName: "Nesmith", position: "P", eligibility: "JR", homeState: "PA", hometown: "Harrisburg", jerseyNumber: 36,
      hitForAvg: 16, power: 14, speed: 38, arm: 70, fielding: 44, errorResistance: 46, velocity: 72, control: 68, stamina: 66, stuff: 68,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 12, running: 34, throwing: 68, recovery: 58, wRISP: 58, vsLefty: 60, poise: 62, heater: 70, agile: 42,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Kowalski", position: "P", eligibility: "SO", homeState: "PA", hometown: "Scranton", jerseyNumber: 44,
      hitForAvg: 16, power: 14, speed: 40, arm: 68, fielding: 42, errorResistance: 44, velocity: 72, control: 64, stamina: 62, stuff: 66,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 12, running: 36, throwing: 66, recovery: 54, wRISP: 54, vsLefty: 56, poise: 56, heater: 70, agile: 42,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 3, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Grant", lastName: "Talbot", position: "C", eligibility: "JR", homeState: "PA", hometown: "State College", jerseyNumber: 12,
      hitForAvg: 52, power: 46, speed: 38, arm: 66, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 62, stealing: 16, running: 36, throwing: 68, recovery: 52, wRISP: 56, vsLefty: 52, poise: 58, heater: 0, agile: 42,
      abilities: ["Cannon Arm"], potential: "B+", catcherAbility: 64,
      ...noPitches },
    { firstName: "Nick", lastName: "Barber", position: "C", eligibility: "SO", homeState: "OH", hometown: "Akron", jerseyNumber: 25,
      hitForAvg: 42, power: 38, speed: 36, arm: 60, fielding: 56, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 40, grit: 46, stealing: 14, running: 34, throwing: 58, recovery: 42, wRISP: 42, vsLefty: 38, poise: 42, heater: 0, agile: 38,
      abilities: [], potential: "B", catcherAbility: 56,
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Caden", lastName: "Dulin", position: "2B", eligibility: "JR", homeState: "PA", hometown: "Bethel Park", jerseyNumber: 5,
      hitForAvg: 72, power: 52, speed: 58, arm: 62, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 34, running: 56, throwing: 64, recovery: 56, wRISP: 70, vsLefty: 64, poise: 68, heater: 0, agile: 60,
      abilities: ["Contact Machine", "Clutch Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Luke", lastName: "Cantwell", position: "1B", eligibility: "JR", homeState: "PA", hometown: "Lancaster", jerseyNumber: 24,
      hitForAvg: 58, power: 60, speed: 40, arm: 56, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 14, running: 38, throwing: 58, recovery: 52, wRISP: 62, vsLefty: 56, poise: 60, heater: 0, agile: 42,
      abilities: ["Power Surge"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Marco", lastName: "Pellegrini", position: "SS", eligibility: "JR", homeState: "PA", hometown: "Moon Township", jerseyNumber: 2,
      hitForAvg: 54, power: 44, speed: 60, arm: 66, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 36, running: 58, throwing: 68, recovery: 50, wRISP: 54, vsLefty: 50, poise: 54, heater: 0, agile: 62,
      abilities: ["Iron Glove"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Evan", lastName: "DeLuca", position: "3B", eligibility: "JR", homeState: "PA", hometown: "Cranberry Township", jerseyNumber: 15,
      hitForAvg: 52, power: 48, speed: 48, arm: 62, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 22, running: 46, throwing: 64, recovery: 48, wRISP: 52, vsLefty: 48, poise: 52, heater: 0, agile: 50,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Tyler", lastName: "Kozak", position: "2B", eligibility: "SO", homeState: "PA", hometown: "Greensburg", jerseyNumber: 9,
      hitForAvg: 48, power: 40, speed: 54, arm: 58, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 30, running: 52, throwing: 60, recovery: 46, wRISP: 48, vsLefty: 44, poise: 48, heater: 0, agile: 56,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Brandon", lastName: "Russo", position: "1B", eligibility: "FR", homeState: "NJ", hometown: "Morristown", jerseyNumber: 23,
      hitForAvg: 44, power: 48, speed: 38, arm: 54, fielding: 50, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 40, grit: 46, stealing: 14, running: 36, throwing: 56, recovery: 40, wRISP: 42, vsLefty: 38, poise: 42, heater: 0, agile: 40,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Gavin", lastName: "Torres", position: "SS", eligibility: "FR", homeState: "PA", hometown: "Reading", jerseyNumber: 11,
      hitForAvg: 40, power: 34, speed: 56, arm: 58, fielding: 52, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 38, grit: 44, stealing: 32, running: 54, throwing: 60, recovery: 38, wRISP: 40, vsLefty: 36, poise: 40, heater: 0, agile: 58,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (9)
    { firstName: "AJ", lastName: "Nessler", position: "OF", eligibility: "JR", homeState: "PA", hometown: "Monroeville", jerseyNumber: 1,
      hitForAvg: 66, power: 52, speed: 62, arm: 66, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 38, running: 60, throwing: 68, recovery: 54, wRISP: 64, vsLefty: 60, poise: 64, heater: 0, agile: 64,
      abilities: ["Contact Machine"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Jayden", lastName: "Melendez", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Miami", jerseyNumber: 10,
      hitForAvg: 56, power: 50, speed: 60, arm: 64, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 34, running: 58, throwing: 66, recovery: 50, wRISP: 56, vsLefty: 52, poise: 56, heater: 0, agile: 62,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Mason", lastName: "Ligenza", position: "OF", eligibility: "FR", homeState: "IL", hometown: "Naperville", jerseyNumber: 21,
      hitForAvg: 54, power: 52, speed: 66, arm: 66, fielding: 58, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 42, running: 64, throwing: 68, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 68,
      abilities: ["Speed Demon"], potential: "A+", catcherAbility: null,
      ...noPitches },
    { firstName: "Dom", lastName: "Marrazzo", position: "OF", eligibility: "JR", homeState: "PA", hometown: "Canonsburg", jerseyNumber: 16,
      hitForAvg: 52, power: 46, speed: 56, arm: 62, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 30, running: 54, throwing: 64, recovery: 48, wRISP: 52, vsLefty: 48, poise: 52, heater: 0, agile: 58,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Cole", lastName: "Peterson", position: "OF", eligibility: "SO", homeState: "PA", hometown: "Williamsport", jerseyNumber: 20,
      hitForAvg: 48, power: 42, speed: 58, arm: 60, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 32, running: 56, throwing: 62, recovery: 46, wRISP: 48, vsLefty: 44, poise: 48, heater: 0, agile: 60,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Jason", lastName: "Mitchell", position: "OF", eligibility: "FR", homeState: "PA", hometown: "West Chester", jerseyNumber: 32,
      hitForAvg: 42, power: 38, speed: 56, arm: 58, fielding: 52, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 38, grit: 44, stealing: 30, running: 54, throwing: 60, recovery: 40, wRISP: 40, vsLefty: 36, poise: 40, heater: 0, agile: 58,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Anthony", lastName: "Ricci", position: "OF", eligibility: "FR", homeState: "NY", hometown: "Staten Island", jerseyNumber: 30,
      hitForAvg: 40, power: 36, speed: 54, arm: 56, fielding: 50, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 36, grit: 42, stealing: 28, running: 52, throwing: 58, recovery: 38, wRISP: 38, vsLefty: 34, poise: 38, heater: 0, agile: 56,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Chris", lastName: "Varga", position: "OF", eligibility: "JR", homeState: "PA", hometown: "Bethlehem", jerseyNumber: 7,
      hitForAvg: 50, power: 44, speed: 56, arm: 62, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 30, running: 54, throwing: 64, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 58,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Mike", lastName: "Brennan", position: "OF", eligibility: "SO", homeState: "PA", hometown: "Norristown", jerseyNumber: 8,
      hitForAvg: 46, power: 40, speed: 54, arm: 60, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 44, grit: 50, stealing: 28, running: 52, throwing: 62, recovery: 44, wRISP: 46, vsLefty: 42, poise: 46, heater: 0, agile: 56,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
  ],
};
