import { RealPlayer } from "./realRosters";

function pitchMix(primary: number, secondary: number[]): { pitchFB: number; pitch2S: number; pitchSL: number; pitchCB: number; pitchCH: number; pitchCT: number; pitchSNK: number; pitchSPL: number } {
  return { pitchFB: primary, pitch2S: secondary[0] || 0, pitchSL: secondary[1] || 0, pitchCB: secondary[2] || 0, pitchCH: secondary[3] || 0, pitchCT: secondary[4] || 0, pitchSNK: secondary[5] || 0, pitchSPL: secondary[6] || 0 };
}

const noPitches = { pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0 };

export const ACC_BATCH1_ROSTERS: Record<string, RealPlayer[]> = {
  "Clemson": [
    { firstName: "Aidan", lastName: "Knaak", position: "P", eligibility: "JR", homeState: "FL", hometown: "Fort Myers", jerseyNumber: 34,
      hitForAvg: 19, power: 16, speed: 48, arm: 90, fielding: 54, errorResistance: 56, velocity: 92, control: 86, stamina: 88, stuff: 90,
      clutch: 82, vsLHP: 77, grit: 84, stealing: 15, running: 43, throwing: 88, recovery: 77, wRISP: 80, vsLefty: 82, poise: 84, heater: 92, agile: 52,
      abilities: ["Ace", "Explosive Fastball"], potential: "A+", catcherAbility: null,
      ...pitchMix(1, [1, 6, 4, 5, 0, 0, 0]) },
    { firstName: "Michael", lastName: "Sharman", position: "P", eligibility: "JR", homeState: "TN", hometown: "Knoxville", jerseyNumber: 29,
      hitForAvg: 12, power: 10, speed: 31, arm: 60, fielding: 37, errorResistance: 38, velocity: 62, control: 59, stamina: 57, stuff: 60,
      clutch: 54, vsLHP: 51, grit: 56, stealing: 9, running: 28, throwing: 59, recovery: 53, wRISP: 53, vsLefty: 54, poise: 56, heater: 62, agile: 34,
      abilities: ["Strong Starter"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 5, 6, 4, 0, 0, 0]) },
    { firstName: "Cole", lastName: "Stokes", position: "P", eligibility: "JR", homeState: "OR", hometown: "Portland", jerseyNumber: 36,
      hitForAvg: 14, power: 13, speed: 38, arm: 74, fielding: 40, errorResistance: 42, velocity: 82, control: 63, stamina: 62, stuff: 76,
      clutch: 62, vsLHP: 58, grit: 63, stealing: 13, running: 34, throwing: 72, recovery: 54, wRISP: 60, vsLefty: 62, poise: 62, heater: 82, agile: 42,
      abilities: ["Explosive Fastball"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 6, 3, 5, 0, 0, 0]) },
    { firstName: "Talan", lastName: "Bell", position: "P", eligibility: "SO", homeState: "SC", hometown: "Simpsonville", jerseyNumber: 44,
      hitForAvg: 13, power: 11, speed: 35, arm: 61, fielding: 38, errorResistance: 39, velocity: 63, control: 60, stamina: 58, stuff: 61,
      clutch: 53, vsLHP: 52, grit: 55, stealing: 11, running: 31, throwing: 60, recovery: 53, wRISP: 52, vsLefty: 55, poise: 55, heater: 63, agile: 38,
      abilities: ["Guts"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 5, 0, 0, 0]) },
    { firstName: "Drew", lastName: "Titsworth", position: "P", eligibility: "JR", homeState: "MI", hometown: "Frankenmuth", jerseyNumber: 27,
      hitForAvg: 15, power: 14, speed: 34, arm: 61, fielding: 39, errorResistance: 41, velocity: 64, control: 59, stamina: 61, stuff: 61,
      clutch: 54, vsLHP: 51, grit: 56, stealing: 10, running: 31, throwing: 59, recovery: 53, wRISP: 53, vsLefty: 54, poise: 56, heater: 64, agile: 37,
      abilities: ["Workhorse"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Jacob", lastName: "McGovern", position: "P", eligibility: "JR", homeState: "GA", hometown: "Roswell", jerseyNumber: 38,
      hitForAvg: 10, power: 9, speed: 26, arm: 44, fielding: 27, errorResistance: 30, velocity: 46, control: 42, stamina: 41, stuff: 44,
      clutch: 39, vsLHP: 36, grit: 40, stealing: 9, running: 24, throwing: 42, recovery: 37, wRISP: 37, vsLefty: 39, poise: 40, heater: 46, agile: 27,
      abilities: ["Fireman"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Braeden", lastName: "Moehler", position: "P", eligibility: "JR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 41,
      hitForAvg: 12, power: 9, speed: 27, arm: 48, fielding: 32, errorResistance: 33, velocity: 52, control: 48, stamina: 45, stuff: 48,
      clutch: 43, vsLHP: 40, grit: 44, stealing: 8, running: 24, throwing: 47, recovery: 41, wRISP: 41, vsLefty: 43, poise: 44, heater: 52, agile: 29,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 0, 3, 0, 0]) },
    { firstName: "Zach", lastName: "Allen", position: "P", eligibility: "JR", homeState: "SC", hometown: "Spartanburg", jerseyNumber: 33,
      hitForAvg: 10, power: 9, speed: 26, arm: 43, fielding: 29, errorResistance: 30, velocity: 47, control: 43, stamina: 41, stuff: 43,
      clutch: 38, vsLHP: 37, grit: 39, stealing: 8, running: 23, throwing: 41, recovery: 37, wRISP: 37, vsLefty: 38, poise: 39, heater: 47, agile: 27,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 0, 4, 3, 0, 0]) },
    { firstName: "Trey", lastName: "Harwick", position: "P", eligibility: "FR", homeState: "SC", hometown: "Greenville", jerseyNumber: 48,
      hitForAvg: 9, power: 9, speed: 31, arm: 49, fielding: 28, errorResistance: 29, velocity: 53, control: 39, stamina: 37, stuff: 47,
      clutch: 34, vsLHP: 33, grit: 35, stealing: 12, running: 29, throwing: 47, recovery: 34, wRISP: 33, vsLefty: 35, poise: 34, heater: 53, agile: 34,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 6, 3, 4, 0, 0, 0]) },
    { firstName: "Camden", lastName: "Cross", position: "P", eligibility: "FR", homeState: "GA", hometown: "Alpharetta", jerseyNumber: 46,
      hitForAvg: 10, power: 10, speed: 31, arm: 49, fielding: 27, errorResistance: 28, velocity: 53, control: 39, stamina: 36, stuff: 48,
      clutch: 33, vsLHP: 31, grit: 35, stealing: 10, running: 27, throwing: 48, recovery: 32, wRISP: 32, vsLefty: 33, poise: 32, heater: 53, agile: 32,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 3, 0, 0, 0]) },
    { firstName: "Cooper", lastName: "Crighton", position: "C", eligibility: "SR", homeState: "MI", hometown: "Rochester Hills", jerseyNumber: 8,
      hitForAvg: 47, power: 41, speed: 34, arm: 55, fielding: 54, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 47, grit: 54, stealing: 16, running: 33, throwing: 57, recovery: 44, wRISP: 48, vsLefty: 45, poise: 51, heater: 0, agile: 37,
      abilities: ["Iron Glove"], potential: "B+", catcherAbility: 51,
      ...noPitches },
    { firstName: "Tyler", lastName: "Lichtenberger", position: "SS", eligibility: "SO", homeState: "NC", hometown: "Boone", jerseyNumber: 6,
      hitForAvg: 46, power: 33, speed: 43, arm: 46, fielding: 47, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 41, grit: 46, stealing: 31, running: 41, throwing: 47, recovery: 36, wRISP: 43, vsLefty: 41, poise: 43, heater: 0, agile: 44,
      abilities: ["Iron Glove", "Contact Machine"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Jarren", lastName: "Purify", position: "3B", eligibility: "JR", homeState: "MI", hometown: "Detroit", jerseyNumber: 5,
      hitForAvg: 53, power: 55, speed: 42, arm: 55, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 50, grit: 55, stealing: 21, running: 40, throwing: 57, recovery: 45, wRISP: 53, vsLefty: 48, poise: 51, heater: 0, agile: 43,
      abilities: ["Power Surge"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Blake", lastName: "Jarrell", position: "2B", eligibility: "SR", homeState: "SC", hometown: "Greer", jerseyNumber: 3,
      hitForAvg: 52, power: 37, speed: 47, arm: 51, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 51, grit: 58, stealing: 32, running: 45, throwing: 52, recovery: 45, wRISP: 52, vsLefty: 49, poise: 56, heater: 0, agile: 49,
      abilities: ["Table Setter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Collin", lastName: "Priest", position: "1B", eligibility: "JR", homeState: "GA", hometown: "Marietta", jerseyNumber: 18,
      hitForAvg: 52, power: 58, speed: 41, arm: 56, fielding: 52, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 52, grit: 56, stealing: 18, running: 40, throwing: 58, recovery: 45, wRISP: 54, vsLefty: 51, poise: 54, heater: 0, agile: 44,
      abilities: ["Power Surge"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Josh", lastName: "Castellani", position: "3B", eligibility: "JR", homeState: "FL", hometown: "Orlando", jerseyNumber: 22,
      hitForAvg: 35, power: 37, speed: 25, arm: 33, fielding: 35, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 37, vsLHP: 34, grit: 38, stealing: 9, running: 24, throwing: 34, recovery: 31, wRISP: 37, vsLefty: 33, poise: 35, heater: 0, agile: 26,
      abilities: ["Clutch Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Bryce", lastName: "Clavon", position: "OF", eligibility: "SO", homeState: "GA", hometown: "Athens", jerseyNumber: 1,
      hitForAvg: 47, power: 41, speed: 51, arm: 49, fielding: 47, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 44, grit: 49, stealing: 39, running: 50, throwing: 50, recovery: 40, wRISP: 46, vsLefty: 43, poise: 46, heater: 0, agile: 51,
      abilities: ["Speed Demon"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Austin", lastName: "Gaffney", position: "OF", eligibility: "JR", homeState: "IN", hometown: "West Lafayette", jerseyNumber: 10,
      hitForAvg: 56, power: 43, speed: 46, arm: 51, fielding: 48, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 51, grit: 55, stealing: 29, running: 44, throwing: 52, recovery: 44, wRISP: 55, vsLefty: 48, poise: 52, heater: 0, agile: 47,
      abilities: ["Contact Machine"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "TP", lastName: "Wentworth", position: "OF", eligibility: "SO", homeState: "SC", hometown: "Charleston", jerseyNumber: 7,
      hitForAvg: 53, power: 44, speed: 57, arm: 58, fielding: 55, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 49, grit: 53, stealing: 36, running: 55, throwing: 60, recovery: 46, wRISP: 49, vsLefty: 47, poise: 52, heater: 0, agile: 58,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Peyton", lastName: "Caldwell", position: "OF", eligibility: "JR", homeState: "SC", hometown: "Anderson", jerseyNumber: 20,
      hitForAvg: 52, power: 45, speed: 54, arm: 58, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 33, running: 52, throwing: 59, recovery: 47, wRISP: 51, vsLefty: 47, poise: 52, heater: 0, agile: 56,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Marcus", lastName: "Whitfield", position: "OF", eligibility: "SO", homeState: "GA", hometown: "Lawrenceville", jerseyNumber: 14,
      hitForAvg: 53, power: 45, speed: 60, arm: 59, fielding: 57, errorResistance: 55, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 49, grit: 55, stealing: 40, running: 59, throwing: 60, recovery: 48, wRISP: 51, vsLefty: 48, poise: 53, heater: 0, agile: 60,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Carter", lastName: "Tompkins", position: "2B", eligibility: "FR", homeState: "SC", hometown: "Columbia", jerseyNumber: 12,
      hitForAvg: 29, power: 23, speed: 36, arm: 35, fielding: 33, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 28, vsLHP: 25, grit: 29, stealing: 22, running: 35, throwing: 36, recovery: 26, wRISP: 26, vsLefty: 24, poise: 26, heater: 0, agile: 36,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Weston", lastName: "Brock", position: "SS", eligibility: "FR", homeState: "GA", hometown: "Augusta", jerseyNumber: 15,
      hitForAvg: 35, power: 26, speed: 47, arm: 46, fielding: 39, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 33, vsLHP: 30, grit: 35, stealing: 29, running: 46, throwing: 47, recovery: 31, wRISP: 31, vsLefty: 29, poise: 31, heater: 0, agile: 47,
      abilities: ["Speed Demon"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Camden", lastName: "Duffie", position: "OF", eligibility: "FR", homeState: "SC", hometown: "Rock Hill", jerseyNumber: 32,
      hitForAvg: 33, power: 30, speed: 47, arm: 43, fielding: 38, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 33, vsLHP: 30, grit: 34, stealing: 29, running: 45, throwing: 45, recovery: 31, wRISP: 31, vsLefty: 29, poise: 31, heater: 0, agile: 47,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Hayden", lastName: "Foster", position: "OF", eligibility: "JR", homeState: "SC", hometown: "Clemson", jerseyNumber: 17,
      hitForAvg: 31, power: 26, speed: 32, arm: 36, fielding: 33, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 31, vsLHP: 29, grit: 32, stealing: 19, running: 31, throwing: 37, recovery: 27, wRISP: 30, vsLefty: 27, poise: 31, heater: 0, agile: 33,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "Duke": [
    { firstName: "Aidan", lastName: "Weaver", position: "P", eligibility: "JR", homeState: "PA", hometown: "Pittsburgh", jerseyNumber: 22,
      hitForAvg: 22, power: 20, speed: 52, arm: 90, fielding: 59, errorResistance: 61, velocity: 96, control: 90, stamina: 90, stuff: 93,
      clutch: 83, vsLHP: 78, grit: 85, stealing: 17, running: 46, throwing: 88, recovery: 81, wRISP: 81, vsLefty: 83, poise: 85, heater: 96, agile: 56,
      abilities: ["Strong Starter", "Guts"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 6, 4, 0, 0, 0]) },
    { firstName: "Ben", lastName: "Dean", position: "P", eligibility: "JR", homeState: "OH", hometown: "Dayton", jerseyNumber: 33,
      hitForAvg: 13, power: 11, speed: 31, arm: 59, fielding: 36, errorResistance: 37, velocity: 62, control: 56, stamina: 54, stuff: 60,
      clutch: 51, vsLHP: 48, grit: 53, stealing: 9, running: 28, throwing: 57, recovery: 49, wRISP: 49, vsLefty: 51, poise: 53, heater: 62, agile: 34,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 4, 5, 0, 0, 0]) },
    { firstName: "Matt", lastName: "Nochowitz", position: "P", eligibility: "JR", homeState: "NY", hometown: "Cortland", jerseyNumber: 37,
      hitForAvg: 14, power: 12, speed: 34, arm: 63, fielding: 41, errorResistance: 43, velocity: 67, control: 65, stamina: 63, stuff: 63,
      clutch: 58, vsLHP: 55, grit: 60, stealing: 9, running: 30, throwing: 62, recovery: 56, wRISP: 56, vsLefty: 58, poise: 62, heater: 67, agile: 37,
      abilities: ["Workhorse"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [1, 5, 4, 4, 0, 0, 0]) },
    { firstName: "Aiden", lastName: "O'Connell", position: "P", eligibility: "JR", homeState: "TN", hometown: "Nashville", jerseyNumber: 19,
      hitForAvg: 14, power: 12, speed: 39, arm: 65, fielding: 39, errorResistance: 40, velocity: 72, control: 59, stamina: 56, stuff: 67,
      clutch: 56, vsLHP: 53, grit: 58, stealing: 12, running: 36, throwing: 64, recovery: 53, wRISP: 54, vsLefty: 56, poise: 58, heater: 72, agile: 40,
      abilities: ["Fireman"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 5, 0, 3, 0]) },
    { firstName: "Jack", lastName: "Hedrick", position: "P", eligibility: "JR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 28,
      hitForAvg: 14, power: 12, speed: 35, arm: 60, fielding: 39, errorResistance: 40, velocity: 64, control: 60, stamina: 56, stuff: 60,
      clutch: 53, vsLHP: 49, grit: 54, stealing: 11, running: 32, throwing: 57, recovery: 50, wRISP: 50, vsLefty: 53, poise: 54, heater: 64, agile: 36,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Leverett", position: "P", eligibility: "JR", homeState: "VA", hometown: "Richmond", jerseyNumber: 31,
      hitForAvg: 11, power: 10, speed: 26, arm: 45, fielding: 30, errorResistance: 32, velocity: 49, control: 46, stamina: 45, stuff: 45,
      clutch: 39, vsLHP: 38, grit: 41, stealing: 7, running: 23, throwing: 43, recovery: 39, wRISP: 38, vsLefty: 41, poise: 41, heater: 49, agile: 27,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 0, 4, 3, 0, 0]) },
    { firstName: "Drew", lastName: "Hartigan", position: "P", eligibility: "SO", homeState: "MD", hometown: "Bethesda", jerseyNumber: 45,
      hitForAvg: 9, power: 9, speed: 28, arm: 45, fielding: 26, errorResistance: 27, velocity: 48, control: 36, stamina: 33, stuff: 43,
      clutch: 29, vsLHP: 28, grit: 31, stealing: 9, running: 26, throwing: 43, recovery: 29, wRISP: 28, vsLefty: 31, poise: 29, heater: 48, agile: 29,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 5, 0, 0, 0]) },
    { firstName: "Nick", lastName: "Thornton", position: "P", eligibility: "FR", homeState: "VA", hometown: "Charlottesville", jerseyNumber: 42,
      hitForAvg: 10, power: 10, speed: 29, arm: 47, fielding: 27, errorResistance: 29, velocity: 51, control: 39, stamina: 36, stuff: 47,
      clutch: 31, vsLHP: 30, grit: 34, stealing: 9, running: 26, throwing: 45, recovery: 31, wRISP: 30, vsLefty: 31, poise: 31, heater: 51, agile: 30,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 0, 4, 3, 0, 0]) },
    { firstName: "Marcus", lastName: "Holloway", position: "P", eligibility: "JR", homeState: "NC", hometown: "Durham", jerseyNumber: 35,
      hitForAvg: 11, power: 9, speed: 25, arm: 44, fielding: 30, errorResistance: 31, velocity: 49, control: 44, stamina: 44, stuff: 44,
      clutch: 38, vsLHP: 36, grit: 39, stealing: 6, running: 23, throwing: 44, recovery: 38, wRISP: 36, vsLefty: 39, poise: 39, heater: 49, agile: 27,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 0, 3, 0, 0]) },
    { firstName: "Cider", lastName: "Canon", position: "C", eligibility: "JR", homeState: "NC", hometown: "Davidson", jerseyNumber: 14,
      hitForAvg: 60, power: 56, speed: 33, arm: 56, fielding: 55, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 55, grit: 58, stealing: 14, running: 31, throwing: 58, recovery: 45, wRISP: 58, vsLefty: 53, poise: 56, heater: 0, agile: 36,
      abilities: ["Clutch Hitter", "Power Surge"], potential: "A", catcherAbility: 53,
      ...noPitches },
    { firstName: "Gavin", lastName: "Morelli", position: "C", eligibility: "FR", homeState: "NJ", hometown: "Montclair", jerseyNumber: 24,
      hitForAvg: 30, power: 26, speed: 25, arm: 42, fielding: 36, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 31, vsLHP: 28, grit: 32, stealing: 8, running: 24, throwing: 41, recovery: 30, wRISP: 30, vsLefty: 26, poise: 30, heater: 0, agile: 26,
      abilities: [], potential: "B+", catcherAbility: 40,
      ...noPitches },
    { firstName: "Jake", lastName: "Lambdin", position: "SS", eligibility: "JR", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 2,
      hitForAvg: 56, power: 42, speed: 53, arm: 61, fielding: 62, errorResistance: 61, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 57, vsLHP: 53, grit: 58, stealing: 40, running: 52, throwing: 62, recovery: 48, wRISP: 56, vsLefty: 52, poise: 57, heater: 0, agile: 56,
      abilities: ["Iron Glove"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Coltin", lastName: "Quagliano", position: "2B", eligibility: "JR", homeState: "IL", hometown: "Champaign", jerseyNumber: 7,
      hitForAvg: 48, power: 35, speed: 45, arm: 48, fielding: 53, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 45, grit: 49, stealing: 28, running: 44, throwing: 49, recovery: 42, wRISP: 46, vsLefty: 44, poise: 48, heater: 0, agile: 46,
      abilities: ["Table Setter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "RJ", lastName: "Hamilton", position: "3B", eligibility: "JR", homeState: "TN", hometown: "Nashville", jerseyNumber: 11,
      hitForAvg: 49, power: 45, speed: 44, arm: 56, fielding: 53, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 47, grit: 53, stealing: 23, running: 42, throwing: 58, recovery: 44, wRISP: 49, vsLefty: 45, poise: 49, heater: 0, agile: 45,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jeff", lastName: "Lougee", position: "1B", eligibility: "SO", homeState: "MA", hometown: "Andover", jerseyNumber: 16,
      hitForAvg: 32, power: 28, speed: 27, arm: 35, fielding: 35, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 33, vsLHP: 31, grit: 33, stealing: 11, running: 26, throwing: 37, recovery: 30, wRISP: 32, vsLefty: 30, poise: 32, heater: 0, agile: 28,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Kaden", lastName: "Smith", position: "1B", eligibility: "JR", homeState: "SC", hometown: "Charleston", jerseyNumber: 21,
      hitForAvg: 49, power: 43, speed: 44, arm: 57, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 21, running: 43, throwing: 59, recovery: 46, wRISP: 49, vsLefty: 46, poise: 52, heater: 0, agile: 46,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Brooks", lastName: "Perez", position: "3B", eligibility: "FR", homeState: "FL", hometown: "Tampa", jerseyNumber: 9,
      hitForAvg: 30, power: 32, speed: 25, arm: 35, fielding: 32, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 29, grit: 32, stealing: 9, running: 24, throwing: 37, recovery: 28, wRISP: 30, vsLefty: 28, poise: 30, heater: 0, agile: 27,
      abilities: ["Power Surge"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Cameron", lastName: "Wiley", position: "SS", eligibility: "FR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 3,
      hitForAvg: 34, power: 28, speed: 47, arm: 46, fielding: 40, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 34, vsLHP: 31, grit: 35, stealing: 31, running: 46, throwing: 47, recovery: 32, wRISP: 32, vsLefty: 29, poise: 32, heater: 0, agile: 47,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Tyler", lastName: "Albright", position: "OF", eligibility: "JR", homeState: "VA", hometown: "Fairfax", jerseyNumber: 1,
      hitForAvg: 53, power: 49, speed: 49, arm: 53, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 52, grit: 54, stealing: 32, running: 47, throwing: 54, recovery: 43, wRISP: 53, vsLefty: 50, poise: 53, heater: 0, agile: 50,
      abilities: ["Clutch Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Michael", lastName: "DiMartini", position: "OF", eligibility: "JR", homeState: "OH", hometown: "Dayton", jerseyNumber: 5,
      hitForAvg: 63, power: 53, speed: 52, arm: 53, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 57, grit: 60, stealing: 36, running: 50, throwing: 56, recovery: 47, wRISP: 62, vsLefty: 56, poise: 59, heater: 0, agile: 53,
      abilities: ["Contact Machine", "Power Surge"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Adin", lastName: "Zorn", position: "OF", eligibility: "JR", homeState: "OH", hometown: "Dayton", jerseyNumber: 8,
      hitForAvg: 49, power: 41, speed: 49, arm: 52, fielding: 51, errorResistance: 49, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 45, grit: 49, stealing: 33, running: 48, throwing: 54, recovery: 43, wRISP: 46, vsLefty: 43, poise: 48, heater: 0, agile: 51,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Bobby", lastName: "Marsh", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Miami", jerseyNumber: 17,
      hitForAvg: 49, power: 41, speed: 50, arm: 54, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 45, grit: 50, stealing: 31, running: 49, throwing: 55, recovery: 44, wRISP: 47, vsLefty: 44, poise: 49, heater: 0, agile: 52,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Nolan", lastName: "Johnson", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Coral Gables", jerseyNumber: 13,
      hitForAvg: 52, power: 45, speed: 52, arm: 57, fielding: 53, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 53, stealing: 31, running: 49, throwing: 59, recovery: 46, wRISP: 49, vsLefty: 46, poise: 52, heater: 0, agile: 53,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Nate", lastName: "Rodriguez", position: "OF", eligibility: "FR", homeState: "NC", hometown: "Chapel Hill", jerseyNumber: 10,
      hitForAvg: 34, power: 29, speed: 46, arm: 44, fielding: 40, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 34, vsLHP: 30, grit: 36, stealing: 29, running: 44, throwing: 46, recovery: 33, wRISP: 33, vsLefty: 29, poise: 33, heater: 0, agile: 46,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Ethan", lastName: "Brooks", position: "OF", eligibility: "JR", homeState: "VA", hometown: "Virginia Beach", jerseyNumber: 6,
      hitForAvg: 45, power: 37, speed: 50, arm: 52, fielding: 49, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 45, vsLHP: 42, grit: 47, stealing: 31, running: 49, throwing: 54, recovery: 40, wRISP: 44, vsLefty: 40, poise: 45, heater: 0, agile: 52,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "Florida State": [
    { firstName: "Wes", lastName: "Mendes", position: "P", eligibility: "JR", homeState: "FL", hometown: "Coral Springs", jerseyNumber: 34,
      hitForAvg: 20, power: 18, speed: 46, arm: 89, fielding: 56, errorResistance: 58, velocity: 91, control: 87, stamina: 87, stuff: 89,
      clutch: 82, vsLHP: 78, grit: 84, stealing: 15, running: 42, throwing: 87, recovery: 78, wRISP: 80, vsLefty: 82, poise: 84, heater: 91, agile: 51,
      abilities: ["Ace", "Guts"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [1, 6, 4, 5, 0, 0, 0]) },
    { firstName: "Trey", lastName: "Beard", position: "P", eligibility: "JR", homeState: "FL", hometown: "Boca Raton", jerseyNumber: 27,
      hitForAvg: 12, power: 11, speed: 32, arm: 61, fielding: 37, errorResistance: 39, velocity: 62, control: 59, stamina: 59, stuff: 62,
      clutch: 57, vsLHP: 53, grit: 57, stealing: 10, running: 28, throwing: 59, recovery: 53, wRISP: 55, vsLefty: 57, poise: 57, heater: 62, agile: 34,
      abilities: ["Filthy Breaking Ball", "Strong Starter"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 4, 0, 0, 0]) },
    { firstName: "Brodie", lastName: "Purcell", position: "P", eligibility: "JR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 38,
      hitForAvg: 13, power: 11, speed: 37, arm: 63, fielding: 37, errorResistance: 38, velocity: 69, control: 58, stamina: 53, stuff: 64,
      clutch: 56, vsLHP: 53, grit: 58, stealing: 11, running: 33, throwing: 61, recovery: 50, wRISP: 55, vsLefty: 56, poise: 58, heater: 69, agile: 40,
      abilities: ["Fireman", "Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 5, 0, 3, 0]) },
    { firstName: "John", lastName: "Abraham", position: "P", eligibility: "JR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 44,
      hitForAvg: 16, power: 13, speed: 40, arm: 71, fielding: 45, errorResistance: 46, velocity: 75, control: 69, stamina: 69, stuff: 71,
      clutch: 64, vsLHP: 59, grit: 66, stealing: 13, running: 37, throwing: 69, recovery: 61, wRISP: 61, vsLefty: 64, poise: 66, heater: 75, agile: 45,
      abilities: ["Workhorse"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Cooper", lastName: "Whited", position: "P", eligibility: "SO", homeState: "FL", hometown: "Tallahassee", jerseyNumber: 41,
      hitForAvg: 16, power: 14, speed: 40, arm: 71, fielding: 44, errorResistance: 46, velocity: 76, control: 70, stamina: 67, stuff: 71,
      clutch: 61, vsLHP: 57, grit: 63, stealing: 12, running: 36, throwing: 70, recovery: 60, wRISP: 60, vsLefty: 61, poise: 63, heater: 76, agile: 44,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 4, 0, 0, 0]) },
    { firstName: "Dalton", lastName: "Reeves", position: "P", eligibility: "JR", homeState: "FL", hometown: "Pensacola", jerseyNumber: 36,
      hitForAvg: 9, power: 8, speed: 22, arm: 40, fielding: 25, errorResistance: 27, velocity: 43, control: 40, stamina: 39, stuff: 40,
      clutch: 36, vsLHP: 34, grit: 37, stealing: 6, running: 20, throwing: 39, recovery: 35, wRISP: 35, vsLefty: 36, poise: 37, heater: 43, agile: 24,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 0, 4, 3, 0, 0]) },
    { firstName: "Braden", lastName: "Sikes", position: "P", eligibility: "SO", homeState: "FL", hometown: "Naples", jerseyNumber: 31,
      hitForAvg: 10, power: 9, speed: 25, arm: 44, fielding: 28, errorResistance: 30, velocity: 48, control: 44, stamina: 43, stuff: 44,
      clutch: 37, vsLHP: 36, grit: 39, stealing: 8, running: 24, throwing: 43, recovery: 37, wRISP: 36, vsLefty: 39, poise: 39, heater: 48, agile: 27,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Marcus", lastName: "Harrell", position: "P", eligibility: "FR", homeState: "FL", hometown: "Jacksonville", jerseyNumber: 48,
      hitForAvg: 10, power: 10, speed: 31, arm: 49, fielding: 28, errorResistance: 30, velocity: 53, control: 39, stamina: 37, stuff: 48,
      clutch: 34, vsLHP: 31, grit: 35, stealing: 11, running: 30, throwing: 48, recovery: 34, wRISP: 32, vsLefty: 34, poise: 34, heater: 53, agile: 34,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 3, 0, 0, 0]) },
    { firstName: "Jaylen", lastName: "Cartwright", position: "P", eligibility: "FR", homeState: "GA", hometown: "Valdosta", jerseyNumber: 46,
      hitForAvg: 9, power: 9, speed: 27, arm: 44, fielding: 25, errorResistance: 26, velocity: 48, control: 35, stamina: 33, stuff: 43,
      clutch: 30, vsLHP: 27, grit: 32, stealing: 9, running: 25, throwing: 43, recovery: 29, wRISP: 29, vsLefty: 30, poise: 29, heater: 48, agile: 29,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 3, 0, 0, 0]) },
    { firstName: "Hunter", lastName: "Carns", position: "C", eligibility: "SO", homeState: "GA", hometown: "Buford", jerseyNumber: 12,
      hitForAvg: 49, power: 45, speed: 32, arm: 50, fielding: 50, errorResistance: 49, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 47, grit: 51, stealing: 14, running: 30, throwing: 51, recovery: 41, wRISP: 49, vsLefty: 46, poise: 50, heater: 0, agile: 34,
      abilities: ["Cannon Arm", "Clutch Hitter"], potential: "A+", catcherAbility: 46,
      ...noPitches },
    { firstName: "Nate", lastName: "Cmeyla", position: "C", eligibility: "SR", homeState: "FL", hometown: "Tampa", jerseyNumber: 24,
      hitForAvg: 32, power: 27, speed: 22, arm: 37, fielding: 36, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 33, vsLHP: 32, grit: 36, stealing: 8, running: 21, throwing: 38, recovery: 29, wRISP: 32, vsLefty: 30, poise: 35, heater: 0, agile: 23,
      abilities: [], potential: "B+", catcherAbility: 35,
      ...noPitches },
    { firstName: "Alex", lastName: "Lodise", position: "SS", eligibility: "JR", homeState: "FL", hometown: "Fort Lauderdale", jerseyNumber: 2,
      hitForAvg: 47, power: 37, speed: 44, arm: 48, fielding: 49, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 45, grit: 48, stealing: 32, running: 43, throwing: 49, recovery: 39, wRISP: 47, vsLefty: 44, poise: 47, heater: 0, agile: 45,
      abilities: ["Iron Glove", "Contact Machine"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Myles", lastName: "Bailey", position: "1B", eligibility: "JR", homeState: "FL", hometown: "Miami", jerseyNumber: 16,
      hitForAvg: 55, power: 62, speed: 36, arm: 51, fielding: 52, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 59, vsLHP: 55, grit: 59, stealing: 14, running: 35, throwing: 52, recovery: 47, wRISP: 60, vsLefty: 54, poise: 57, heater: 0, agile: 38,
      abilities: ["Power Surge", "Clutch Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Gabe", lastName: "Nard", position: "2B", eligibility: "SR", homeState: "GA", hometown: "Savannah", jerseyNumber: 7,
      hitForAvg: 56, power: 42, speed: 54, arm: 60, fielding: 63, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 33, running: 52, throwing: 63, recovery: 50, wRISP: 56, vsLefty: 52, poise: 58, heater: 0, agile: 56,
      abilities: ["Table Setter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Cal", lastName: "Fisher", position: "3B", eligibility: "JR", homeState: "VA", hometown: "Richmond", jerseyNumber: 18,
      hitForAvg: 62, power: 56, speed: 43, arm: 60, fielding: 56, errorResistance: 55, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 65, vsLHP: 60, grit: 65, stealing: 17, running: 42, throwing: 62, recovery: 51, wRISP: 66, vsLefty: 59, poise: 62, heater: 0, agile: 45,
      abilities: ["Clutch Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Ethan", lastName: "Rigsby", position: "2B", eligibility: "FR", homeState: "FL", hometown: "Gainesville", jerseyNumber: 9,
      hitForAvg: 30, power: 23, speed: 38, arm: 37, fielding: 34, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 28, vsLHP: 26, grit: 30, stealing: 23, running: 37, throwing: 38, recovery: 27, wRISP: 27, vsLefty: 24, poise: 27, heater: 0, agile: 38,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Mason", lastName: "Prescott", position: "3B", eligibility: "FR", homeState: "GA", hometown: "Alpharetta", jerseyNumber: 11,
      hitForAvg: 33, power: 32, speed: 34, arm: 43, fielding: 37, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 33, vsLHP: 29, grit: 34, stealing: 15, running: 33, throwing: 44, recovery: 32, wRISP: 32, vsLefty: 28, poise: 32, heater: 0, agile: 35,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Tristan", lastName: "Weeks", position: "SS", eligibility: "FR", homeState: "FL", hometown: "St. Augustine", jerseyNumber: 3,
      hitForAvg: 31, power: 26, speed: 43, arm: 43, fielding: 37, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 31, vsLHP: 28, grit: 32, stealing: 27, running: 42, throwing: 44, recovery: 30, wRISP: 30, vsLefty: 27, poise: 30, heater: 0, agile: 44,
      abilities: ["Speed Demon"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Brayden", lastName: "Dowd", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 1,
      hitForAvg: 48, power: 49, speed: 42, arm: 46, fielding: 44, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 49, stealing: 28, running: 41, throwing: 48, recovery: 38, wRISP: 50, vsLefty: 45, poise: 48, heater: 0, agile: 44,
      abilities: ["Power Surge", "Clutch Hitter"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Noah", lastName: "Sheffield", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Orlando", jerseyNumber: 5,
      hitForAvg: 50, power: 41, speed: 49, arm: 49, fielding: 48, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 49, grit: 52, stealing: 34, running: 48, throwing: 50, recovery: 41, wRISP: 52, vsLefty: 48, poise: 50, heater: 0, agile: 49,
      abilities: ["Clutch Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Brody", lastName: "DeLamielleure", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Ponte Vedra", jerseyNumber: 8,
      hitForAvg: 48, power: 46, speed: 50, arm: 51, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 47, grit: 51, stealing: 33, running: 48, throwing: 53, recovery: 42, wRISP: 48, vsLefty: 46, poise: 48, heater: 0, agile: 51,
      abilities: ["Power Surge"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Chase", lastName: "Mitchell", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Sarasota", jerseyNumber: 20,
      hitForAvg: 44, power: 37, speed: 46, arm: 48, fielding: 46, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 41, grit: 45, stealing: 30, running: 45, throwing: 50, recovery: 39, wRISP: 42, vsLefty: 39, poise: 44, heater: 0, agile: 48,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jaxon", lastName: "Byrd", position: "OF", eligibility: "SO", homeState: "FL", hometown: "Pensacola", jerseyNumber: 21,
      hitForAvg: 53, power: 45, speed: 63, arm: 60, fielding: 57, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 49, grit: 54, stealing: 39, running: 60, throwing: 63, recovery: 46, wRISP: 50, vsLefty: 46, poise: 53, heater: 0, agile: 63,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Colby", lastName: "Hawkins", position: "OF", eligibility: "JR", homeState: "GA", hometown: "Macon", jerseyNumber: 22,
      hitForAvg: 37, power: 32, speed: 40, arm: 43, fielding: 40, errorResistance: 39, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 37, vsLHP: 34, grit: 39, stealing: 23, running: 39, throwing: 44, recovery: 33, wRISP: 36, vsLefty: 33, poise: 37, heater: 0, agile: 42,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Landon", lastName: "Pierce", position: "OF", eligibility: "SO", homeState: "FL", hometown: "Tallahassee", jerseyNumber: 14,
      hitForAvg: 42, power: 34, speed: 45, arm: 47, fielding: 45, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 39, grit: 44, stealing: 29, running: 44, throwing: 48, recovery: 37, wRISP: 41, vsLefty: 37, poise: 42, heater: 0, agile: 47,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Georgia Tech": [
    { firstName: "Tate", lastName: "McKee", position: "P", eligibility: "JR", homeState: "GA", hometown: "Alpharetta", jerseyNumber: 34,
      hitForAvg: 20, power: 18, speed: 49, arm: 94, fielding: 57, errorResistance: 59, velocity: 96, control: 91, stamina: 91, stuff: 94,
      clutch: 87, vsLHP: 83, grit: 89, stealing: 17, running: 44, throwing: 91, recovery: 83, wRISP: 84, vsLefty: 87, poise: 89, heater: 96, agile: 52,
      abilities: ["Ace", "Strong Starter"], potential: "A+", catcherAbility: null,
      ...pitchMix(1, [1, 6, 4, 5, 0, 0, 0]) },
    { firstName: "Mason", lastName: "Patel", position: "P", eligibility: "JR", homeState: "GA", hometown: "Johns Creek", jerseyNumber: 19,
      hitForAvg: 12, power: 10, speed: 33, arm: 62, fielding: 34, errorResistance: 36, velocity: 65, control: 56, stamina: 50, stuff: 64,
      clutch: 59, vsLHP: 55, grit: 59, stealing: 10, running: 29, throwing: 60, recovery: 47, wRISP: 57, vsLefty: 57, poise: 59, heater: 65, agile: 36,
      abilities: ["Fireman", "Explosive Fastball"], potential: "A+", catcherAbility: null,
      ...pitchMix(1, [0, 7, 0, 5, 0, 3, 0]) },
    { firstName: "Justin", lastName: "Shadek", position: "P", eligibility: "JR", homeState: "PA", hometown: "Philadelphia", jerseyNumber: 27,
      hitForAvg: 13, power: 12, speed: 33, arm: 63, fielding: 41, errorResistance: 42, velocity: 67, control: 63, stamina: 62, stuff: 66,
      clutch: 59, vsLHP: 55, grit: 61, stealing: 10, running: 30, throwing: 62, recovery: 55, wRISP: 57, vsLefty: 59, poise: 61, heater: 67, agile: 37,
      abilities: ["Strong Starter", "Workhorse"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 5, 6, 4, 0, 0, 0]) },
    { firstName: "Dylan", lastName: "Loy", position: "P", eligibility: "JR", homeState: "FL", hometown: "Tampa", jerseyNumber: 28,
      hitForAvg: 13, power: 11, speed: 31, arm: 60, fielding: 37, errorResistance: 38, velocity: 63, control: 59, stamina: 59, stuff: 61,
      clutch: 56, vsLHP: 53, grit: 57, stealing: 9, running: 27, throwing: 59, recovery: 53, wRISP: 54, vsLefty: 56, poise: 57, heater: 63, agile: 34,
      abilities: ["Guts"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [1, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Carson", lastName: "Ballard", position: "P", eligibility: "JR", homeState: "GA", hometown: "Marietta", jerseyNumber: 41,
      hitForAvg: 9, power: 8, speed: 24, arm: 40, fielding: 25, errorResistance: 26, velocity: 43, control: 40, stamina: 38, stuff: 41,
      clutch: 36, vsLHP: 34, grit: 38, stealing: 8, running: 22, throwing: 39, recovery: 34, wRISP: 35, vsLefty: 36, poise: 38, heater: 43, agile: 25,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 4, 0, 0, 0]) },
    { firstName: "Alex", lastName: "Hernandez", position: "P", eligibility: "SO", homeState: "FL", hometown: "Miami", jerseyNumber: 44,
      hitForAvg: 19, power: 17, speed: 45, arm: 66, fielding: 45, errorResistance: 43, velocity: 70, control: 63, stamina: 59, stuff: 66,
      clutch: 61, vsLHP: 57, grit: 63, stealing: 21, running: 43, throwing: 64, recovery: 54, wRISP: 59, vsLefty: 61, poise: 61, heater: 70, agile: 47,
      abilities: ["Explosive Fastball"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 6, 4, 5, 0, 0, 0]) },
    { firstName: "Cooper", lastName: "Underwood", position: "P", eligibility: "FR", homeState: "GA", hometown: "Woodstock", jerseyNumber: 46,
      hitForAvg: 10, power: 9, speed: 28, arm: 48, fielding: 27, errorResistance: 28, velocity: 52, control: 40, stamina: 36, stuff: 48,
      clutch: 35, vsLHP: 32, grit: 36, stealing: 10, running: 27, throwing: 47, recovery: 32, wRISP: 33, vsLefty: 35, poise: 35, heater: 52, agile: 30,
      abilities: ["Explosive Fastball"], potential: "A+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 4, 0, 0, 0]) },
    { firstName: "Charlie", lastName: "Willcox", position: "P", eligibility: "FR", homeState: "GA", hometown: "Cumming", jerseyNumber: 48,
      hitForAvg: 10, power: 10, speed: 29, arm: 50, fielding: 28, errorResistance: 29, velocity: 55, control: 42, stamina: 38, stuff: 50,
      clutch: 35, vsLHP: 32, grit: 36, stealing: 10, running: 28, throwing: 49, recovery: 34, wRISP: 34, vsLefty: 35, poise: 35, heater: 55, agile: 31,
      abilities: [], potential: "A+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Vahn", lastName: "Lackey", position: "C", eligibility: "JR", homeState: "GA", hometown: "Peachtree City", jerseyNumber: 12,
      hitForAvg: 60, power: 55, speed: 36, arm: 62, fielding: 60, errorResistance: 59, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 63, vsLHP: 59, grit: 63, stealing: 16, running: 35, throwing: 63, recovery: 50, wRISP: 62, vsLefty: 58, poise: 62, heater: 0, agile: 40,
      abilities: ["Cannon Arm", "Clutch Hitter"], potential: "A+", catcherAbility: 55,
      ...noPitches },
    { firstName: "Dominic", lastName: "Stephenson", position: "C", eligibility: "FR", homeState: "GA", hometown: "Roswell", jerseyNumber: 25,
      hitForAvg: 30, power: 28, speed: 27, arm: 44, fielding: 38, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 29, grit: 34, stealing: 10, running: 25, throwing: 41, recovery: 29, wRISP: 30, vsLefty: 28, poise: 30, heater: 0, agile: 28,
      abilities: [], potential: "A", catcherAbility: 40,
      ...noPitches },
    { firstName: "Jarren", lastName: "Advincula", position: "2B", eligibility: "JR", homeState: "CA", hometown: "San Jose", jerseyNumber: 2,
      hitForAvg: 54, power: 40, speed: 47, arm: 47, fielding: 53, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 53, grit: 56, stealing: 37, running: 46, throwing: 49, recovery: 41, wRISP: 54, vsLefty: 52, poise: 54, heater: 0, agile: 49,
      abilities: ["Contact Machine", "Iron Glove"], potential: "A+", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "Zuckerman", position: "1B", eligibility: "JR", homeState: "PA", hometown: "Pittsburgh", jerseyNumber: 16,
      hitForAvg: 59, power: 65, speed: 41, arm: 55, fielding: 57, errorResistance: 55, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 59, grit: 64, stealing: 15, running: 38, throwing: 57, recovery: 51, wRISP: 65, vsLefty: 57, poise: 61, heater: 0, agile: 42,
      abilities: ["Power Surge"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Carson", lastName: "Kerce", position: "3B", eligibility: "JR", homeState: "GA", hometown: "Kennesaw", jerseyNumber: 7,
      hitForAvg: 49, power: 44, speed: 42, arm: 54, fielding: 53, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 51, vsLHP: 48, grit: 53, stealing: 22, running: 41, throwing: 57, recovery: 44, wRISP: 49, vsLefty: 46, poise: 51, heater: 0, agile: 44,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Michael", lastName: "Dee", position: "SS", eligibility: "FR", homeState: "GA", hometown: "Lawrenceville", jerseyNumber: 9,
      hitForAvg: 35, power: 28, speed: 44, arm: 43, fielding: 39, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 33, vsLHP: 31, grit: 35, stealing: 28, running: 43, throwing: 44, recovery: 31, wRISP: 32, vsLefty: 30, poise: 32, heater: 0, agile: 44,
      abilities: ["Speed Demon"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Ethan", lastName: "Dolan", position: "SS", eligibility: "JR", homeState: "GA", hometown: "Savannah", jerseyNumber: 3,
      hitForAvg: 49, power: 38, speed: 53, arm: 56, fielding: 56, errorResistance: 55, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 46, grit: 52, stealing: 36, running: 52, throwing: 59, recovery: 45, wRISP: 48, vsLefty: 45, poise: 49, heater: 0, agile: 55,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jake", lastName: "Whitfield", position: "2B", eligibility: "SO", homeState: "GA", hometown: "Decatur", jerseyNumber: 11,
      hitForAvg: 48, power: 35, speed: 48, arm: 51, fielding: 53, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 44, grit: 49, stealing: 28, running: 46, throwing: 53, recovery: 41, wRISP: 46, vsLefty: 43, poise: 48, heater: 0, agile: 49,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Drew", lastName: "Burress", position: "OF", eligibility: "SR", homeState: "GA", hometown: "Buford", jerseyNumber: 1,
      hitForAvg: 51, power: 51, speed: 42, arm: 45, fielding: 46, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 49, grit: 52, stealing: 31, running: 42, throwing: 46, recovery: 39, wRISP: 52, vsLefty: 48, poise: 51, heater: 0, agile: 43,
      abilities: ["Power Surge", "Clutch Hitter", "Contact Machine"], potential: "A+", catcherAbility: null,
      ...noPitches },
    { firstName: "Parker", lastName: "Brosius", position: "OF", eligibility: "SR", homeState: "GA", hometown: "Suwanee", jerseyNumber: 5,
      hitForAvg: 51, power: 44, speed: 50, arm: 55, fielding: 53, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 50, grit: 55, stealing: 33, running: 47, throwing: 56, recovery: 44, wRISP: 51, vsLefty: 47, poise: 53, heater: 0, agile: 51,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Caleb", lastName: "Daniel", position: "OF", eligibility: "JR", homeState: "GA", hometown: "Duluth", jerseyNumber: 8,
      hitForAvg: 48, power: 45, speed: 43, arm: 50, fielding: 48, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 47, grit: 51, stealing: 24, running: 42, throwing: 51, recovery: 42, wRISP: 50, vsLefty: 45, poise: 48, heater: 0, agile: 45,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Coleman", lastName: "Lewis", position: "OF", eligibility: "FR", homeState: "GA", hometown: "Canton", jerseyNumber: 21,
      hitForAvg: 36, power: 32, speed: 48, arm: 44, fielding: 39, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 36, vsLHP: 32, grit: 37, stealing: 31, running: 46, throwing: 46, recovery: 32, wRISP: 34, vsLefty: 31, poise: 34, heater: 0, agile: 48,
      abilities: ["Speed Demon"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Nathan", lastName: "Pruitt", position: "OF", eligibility: "JR", homeState: "GA", hometown: "Athens", jerseyNumber: 14,
      hitForAvg: 52, power: 44, speed: 52, arm: 57, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 33, running: 50, throwing: 59, recovery: 44, wRISP: 50, vsLefty: 46, poise: 52, heater: 0, agile: 54,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Will", lastName: "Harmon", position: "OF", eligibility: "SO", homeState: "GA", hometown: "Macon", jerseyNumber: 20,
      hitForAvg: 47, power: 39, speed: 49, arm: 51, fielding: 49, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 44, grit: 49, stealing: 32, running: 49, throwing: 53, recovery: 40, wRISP: 45, vsLefty: 42, poise: 47, heater: 0, agile: 51,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Marcus", lastName: "Terrell", position: "3B", eligibility: "JR", homeState: "SC", hometown: "Greenville", jerseyNumber: 18,
      hitForAvg: 44, power: 40, speed: 39, arm: 50, fielding: 47, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 45, vsLHP: 41, grit: 47, stealing: 18, running: 37, throwing: 52, recovery: 39, wRISP: 44, vsLefty: 40, poise: 44, heater: 0, agile: 40,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Bryce", lastName: "Patterson", position: "OF", eligibility: "JR", homeState: "TN", hometown: "Chattanooga", jerseyNumber: 17,
      hitForAvg: 38, power: 32, speed: 39, arm: 44, fielding: 41, errorResistance: 39, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 35, grit: 39, stealing: 24, running: 38, throwing: 45, recovery: 34, wRISP: 36, vsLefty: 34, poise: 38, heater: 0, agile: 41,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Jayden", lastName: "Carter", position: "OF", eligibility: "SO", homeState: "GA", hometown: "Augusta", jerseyNumber: 22,
      hitForAvg: 30, power: 26, speed: 34, arm: 35, fielding: 33, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 30, vsLHP: 28, grit: 31, stealing: 21, running: 33, throwing: 36, recovery: 27, wRISP: 29, vsLefty: 27, poise: 30, heater: 0, agile: 35,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Louisville": [
    { firstName: "Ethan", lastName: "Eberle", position: "P", eligibility: "SO", homeState: "KY", hometown: "Louisville", jerseyNumber: 34,
      hitForAvg: 19, power: 17, speed: 45, arm: 85, fielding: 54, errorResistance: 56, velocity: 88, control: 83, stamina: 83, stuff: 85,
      clutch: 79, vsLHP: 75, grit: 81, stealing: 15, running: 41, throwing: 83, recovery: 75, wRISP: 77, vsLefty: 79, poise: 81, heater: 88, agile: 49,
      abilities: ["Ace", "Strong Starter"], potential: "A+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 6, 4, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Bean", position: "P", eligibility: "JR", homeState: "OH", hometown: "Kent", jerseyNumber: 27,
      hitForAvg: 14, power: 13, speed: 37, arm: 70, fielding: 44, errorResistance: 46, velocity: 74, control: 70, stamina: 70, stuff: 72,
      clutch: 65, vsLHP: 61, grit: 66, stealing: 11, running: 33, throwing: 68, recovery: 63, wRISP: 63, vsLefty: 65, poise: 66, heater: 74, agile: 40,
      abilities: ["Workhorse", "Guts"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [1, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Wyatt", lastName: "Danilowicz", position: "P", eligibility: "SO", homeState: "IN", hometown: "Indianapolis", jerseyNumber: 44,
      hitForAvg: 15, power: 13, speed: 37, arm: 66, fielding: 41, errorResistance: 43, velocity: 69, control: 66, stamina: 64, stuff: 68,
      clutch: 58, vsLHP: 55, grit: 60, stealing: 13, running: 34, throwing: 64, recovery: 57, wRISP: 57, vsLefty: 58, poise: 60, heater: 69, agile: 41,
      abilities: ["Filthy Breaking Ball"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 5, 0, 0, 0]) },
    { firstName: "Dominic", lastName: "Jacoby", position: "P", eligibility: "JR", homeState: "FL", hometown: "Jacksonville", jerseyNumber: 38,
      hitForAvg: 15, power: 14, speed: 39, arm: 71, fielding: 44, errorResistance: 45, velocity: 76, control: 68, stamina: 68, stuff: 72,
      clutch: 62, vsLHP: 59, grit: 65, stealing: 12, running: 35, throwing: 68, recovery: 61, wRISP: 61, vsLefty: 62, poise: 65, heater: 76, agile: 44,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Schweitzer", position: "P", eligibility: "SO", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 36,
      hitForAvg: 9, power: 8, speed: 23, arm: 41, fielding: 27, errorResistance: 28, velocity: 45, control: 41, stamina: 40, stuff: 43,
      clutch: 37, vsLHP: 34, grit: 37, stealing: 7, running: 21, throwing: 40, recovery: 36, wRISP: 36, vsLefty: 37, poise: 37, heater: 45, agile: 25,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 0, 4, 3, 0, 0]) },
    { firstName: "Eli", lastName: "Hoyt", position: "P", eligibility: "SR", homeState: "KY", hometown: "Bowling Green", jerseyNumber: 29,
      hitForAvg: 16, power: 14, speed: 34, arm: 62, fielding: 41, errorResistance: 42, velocity: 67, control: 64, stamina: 59, stuff: 64,
      clutch: 59, vsLHP: 55, grit: 60, stealing: 8, running: 31, throwing: 60, recovery: 57, wRISP: 57, vsLefty: 59, poise: 60, heater: 67, agile: 37,
      abilities: ["Fireman"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 5, 0, 3, 0]) },
    { firstName: "Peter", lastName: "Michael", position: "P", eligibility: "SR", homeState: "OH", hometown: "Columbus", jerseyNumber: 22,
      hitForAvg: 10, power: 9, speed: 24, arm: 42, fielding: 27, errorResistance: 28, velocity: 46, control: 44, stamina: 41, stuff: 44,
      clutch: 38, vsLHP: 36, grit: 39, stealing: 6, running: 21, throwing: 41, recovery: 38, wRISP: 38, vsLefty: 38, poise: 39, heater: 46, agile: 27,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 0, 3, 0, 0]) },
    { firstName: "Tanner", lastName: "Thomas", position: "P", eligibility: "FR", homeState: "KY", hometown: "Covington", jerseyNumber: 48,
      hitForAvg: 10, power: 10, speed: 33, arm: 54, fielding: 31, errorResistance: 32, velocity: 58, control: 42, stamina: 40, stuff: 52,
      clutch: 37, vsLHP: 33, grit: 38, stealing: 13, running: 32, throwing: 52, recovery: 37, wRISP: 36, vsLefty: 37, poise: 37, heater: 58, agile: 37,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 3, 0, 0, 0]) },
    { firstName: "Kade", lastName: "Elam", position: "P", eligibility: "FR", homeState: "KY", hometown: "Lexington", jerseyNumber: 46,
      hitForAvg: 10, power: 10, speed: 30, arm: 47, fielding: 27, errorResistance: 28, velocity: 53, control: 38, stamina: 35, stuff: 47,
      clutch: 33, vsLHP: 30, grit: 34, stealing: 10, running: 27, throwing: 45, recovery: 31, wRISP: 31, vsLefty: 33, poise: 31, heater: 53, agile: 31,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 3, 0, 0, 0]) },
    { firstName: "Kyle", lastName: "Haynes", position: "C", eligibility: "JR", homeState: "KY", hometown: "Louisville", jerseyNumber: 12,
      hitForAvg: 30, power: 26, speed: 22, arm: 37, fielding: 35, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 30, grit: 34, stealing: 8, running: 20, throwing: 38, recovery: 27, wRISP: 31, vsLefty: 29, poise: 32, heater: 0, agile: 23,
      abilities: [], potential: "B+", catcherAbility: 34,
      ...noPitches },
    { firstName: "Collin", lastName: "Osenbaugh", position: "C", eligibility: "FR", homeState: "IN", hometown: "Carmel", jerseyNumber: 25,
      hitForAvg: 38, power: 34, speed: 33, arm: 53, fielding: 46, errorResistance: 43, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 39, vsLHP: 35, grit: 41, stealing: 12, running: 30, throwing: 52, recovery: 38, wRISP: 38, vsLefty: 34, poise: 38, heater: 0, agile: 34,
      abilities: [], potential: "B+", catcherAbility: 50,
      ...noPitches },
    { firstName: "AJ", lastName: "Martin", position: "2B", eligibility: "JR", homeState: "SC", hometown: "Charleston", jerseyNumber: 2,
      hitForAvg: 54, power: 48, speed: 46, arm: 51, fielding: 54, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 51, grit: 56, stealing: 32, running: 45, throwing: 53, recovery: 45, wRISP: 54, vsLefty: 49, poise: 53, heater: 0, agile: 48,
      abilities: ["Contact Machine", "Clutch Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Alex", lastName: "Alicea", position: "SS", eligibility: "JR", homeState: "FL", hometown: "Orlando", jerseyNumber: 7,
      hitForAvg: 44, power: 34, speed: 45, arm: 49, fielding: 50, errorResistance: 49, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 45, vsLHP: 43, grit: 46, stealing: 32, running: 44, throwing: 50, recovery: 40, wRISP: 44, vsLefty: 41, poise: 45, heater: 0, agile: 46,
      abilities: ["Iron Glove"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Bayram", lastName: "Hot", position: "3B", eligibility: "SR", homeState: "CA", hometown: "San Diego", jerseyNumber: 18,
      hitForAvg: 52, power: 49, speed: 40, arm: 54, fielding: 52, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 51, grit: 56, stealing: 18, running: 39, throwing: 56, recovery: 45, wRISP: 54, vsLefty: 49, poise: 54, heater: 0, agile: 42,
      abilities: ["Clutch Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Tague", lastName: "Davis", position: "1B", eligibility: "SO", homeState: "KY", hometown: "Frankfort", jerseyNumber: 11,
      hitForAvg: 47, power: 42, speed: 43, arm: 51, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 45, grit: 50, stealing: 23, running: 42, throwing: 53, recovery: 42, wRISP: 47, vsLefty: 43, poise: 47, heater: 0, agile: 45,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Brandon", lastName: "Shannon", position: "3B", eligibility: "FR", homeState: "KY", hometown: "Owensboro", jerseyNumber: 15,
      hitForAvg: 36, power: 34, speed: 41, arm: 46, fielding: 41, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 36, vsLHP: 33, grit: 37, stealing: 20, running: 38, throwing: 49, recovery: 34, wRISP: 34, vsLefty: 30, poise: 34, heater: 0, agile: 42,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Lucas", lastName: "Moore", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Tampa", jerseyNumber: 1,
      hitForAvg: 47, power: 36, speed: 52, arm: 43, fielding: 46, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 45, grit: 48, stealing: 49, running: 51, throwing: 45, recovery: 39, wRISP: 46, vsLefty: 43, poise: 46, heater: 0, agile: 51,
      abilities: ["Speed Demon", "Contact Machine"], potential: "A+", catcherAbility: null,
      ...noPitches },
    { firstName: "Zion", lastName: "Rose", position: "OF", eligibility: "JR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 5,
      hitForAvg: 49, power: 46, speed: 44, arm: 49, fielding: 48, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 52, stealing: 30, running: 43, throwing: 51, recovery: 41, wRISP: 52, vsLefty: 46, poise: 51, heater: 0, agile: 45,
      abilities: ["Power Surge", "Clutch Hitter"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Ben", lastName: "Slanker", position: "OF", eligibility: "JR", homeState: "OH", hometown: "Toledo", jerseyNumber: 8,
      hitForAvg: 56, power: 62, speed: 47, arm: 56, fielding: 53, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 59, vsLHP: 54, grit: 59, stealing: 24, running: 44, throwing: 59, recovery: 48, wRISP: 60, vsLefty: 53, poise: 56, heater: 0, agile: 48,
      abilities: ["Power Surge"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Griffin", lastName: "Crain", position: "OF", eligibility: "SO", homeState: "KY", hometown: "Louisville", jerseyNumber: 17,
      hitForAvg: 42, power: 37, speed: 44, arm: 47, fielding: 45, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 40, grit: 45, stealing: 27, running: 42, throwing: 49, recovery: 37, wRISP: 42, vsLefty: 39, poise: 44, heater: 0, agile: 45,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Kyle", lastName: "Campbell", position: "OF", eligibility: "SO", homeState: "KY", hometown: "Lexington", jerseyNumber: 20,
      hitForAvg: 49, power: 42, speed: 54, arm: 57, fielding: 52, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 51, vsLHP: 48, grit: 52, stealing: 34, running: 52, throwing: 58, recovery: 46, wRISP: 49, vsLefty: 46, poise: 51, heater: 0, agile: 57,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Zane", lastName: "Stahl", position: "OF", eligibility: "FR", homeState: "IN", hometown: "Bloomington", jerseyNumber: 21,
      hitForAvg: 36, power: 33, speed: 48, arm: 45, fielding: 40, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 36, vsLHP: 33, grit: 37, stealing: 30, running: 46, throwing: 46, recovery: 34, wRISP: 34, vsLefty: 30, poise: 34, heater: 0, agile: 48,
      abilities: ["Speed Demon"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "Mercer", position: "1B", eligibility: "JR", homeState: "OH", hometown: "Dayton", jerseyNumber: 33,
      hitForAvg: 31, power: 30, speed: 24, arm: 33, fielding: 33, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 31, vsLHP: 30, grit: 33, stealing: 9, running: 22, throwing: 34, recovery: 27, wRISP: 31, vsLefty: 28, poise: 31, heater: 0, agile: 25,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Tyler", lastName: "Jennings", position: "OF", eligibility: "SO", homeState: "IN", hometown: "Terre Haute", jerseyNumber: 14,
      hitForAvg: 44, power: 37, speed: 49, arm: 51, fielding: 47, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 40, grit: 45, stealing: 30, running: 47, throwing: 52, recovery: 39, wRISP: 42, vsLefty: 39, poise: 44, heater: 0, agile: 51,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Derek", lastName: "Collins", position: "OF", eligibility: "JR", homeState: "KY", hometown: "Paducah", jerseyNumber: 9,
      hitForAvg: 49, power: 41, speed: 50, arm: 55, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 44, grit: 50, stealing: 30, running: 49, throwing: 57, recovery: 43, wRISP: 47, vsLefty: 43, poise: 49, heater: 0, agile: 52,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],
};
