import { RealPlayer } from "./realRosters";
import { pitchMix, noPitches } from "./pitchMixHelpers";

export const ACC_BATCH3_ROSTERS: Record<string, RealPlayer[]> = {
  "California": [
    // PITCHERS (10)
    { firstName: "Oliver", lastName: "de la Torre", position: "P", eligibility: "JR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 22,
      hitForAvg: 33, power: 26, speed: 42, arm: 87, fielding: 57, errorResistance: 71, velocity: 85, control: 79, stamina: 85, stuff: 82,
      clutch: 90, vsLHP: 85, grit: 95, stealing: 21, running: 55, throwing: 96, recovery: 76, wRISP: 70, vsLefty: 75, poise: 76, heater: 85, agile: 66,
      abilities: ["Strong Starter", "Wild Fastball", "Delayed Arm", "Intimidator", "Heavy Ball"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Ethan", lastName: "Foley", position: "P", eligibility: "JR", homeState: "CA", hometown: "San Diego", jerseyNumber: 33,
      hitForAvg: 20, power: 17, speed: 36, arm: 61, fielding: 36, errorResistance: 49, velocity: 61, control: 55, stamina: 59, stuff: 56,
      clutch: 62, vsLHP: 60, grit: 67, stealing: 16, running: 41, throwing: 76, recovery: 50, wRISP: 47, vsLefty: 49, poise: 50, heater: 60, agile: 45,
      abilities: ["Guts", "Lefty Killer", "Heavy Ball", "Intimidator", "Escape Pitch"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [1, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Gavin", lastName: "Eddy", position: "P", eligibility: "JR", homeState: "CA", hometown: "Claremont", jerseyNumber: 40,
      hitForAvg: 24, power: 18, speed: 38, arm: 68, fielding: 40, errorResistance: 55, velocity: 68, control: 61, stamina: 65, stuff: 61,
      clutch: 70, vsLHP: 67, grit: 75, stealing: 14, running: 43, throwing: 84, recovery: 55, wRISP: 51, vsLefty: 54, poise: 55, heater: 67, agile: 50,
      abilities: ["Guts", "Natural Shuuto", "Monster Stuff"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Cole", lastName: "Clark", position: "P", eligibility: "JR", homeState: "CA", hometown: "Bakersfield", jerseyNumber: 37,
      hitForAvg: 11, power: 9, speed: 24, arm: 28, fielding: 18, errorResistance: 28, velocity: 35, control: 26, stamina: 24, stuff: 24,
      clutch: 32, vsLHP: 32, grit: 36, stealing: 9, running: 22, throwing: 40, recovery: 24, wRISP: 21, vsLefty: 22, poise: 24, heater: 28, agile: 25,
      abilities: ["Fireman"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    { firstName: "Jordy", lastName: "Lopez", position: "P", eligibility: "JR", homeState: "CA", hometown: "Riverside", jerseyNumber: 45,
      hitForAvg: 11, power: 9, speed: 27, arm: 26, fielding: 18, errorResistance: 29, velocity: 40, control: 26, stamina: 24, stuff: 26,
      clutch: 34, vsLHP: 33, grit: 38, stealing: 8, running: 22, throwing: 42, recovery: 24, wRISP: 22, vsLefty: 23, poise: 25, heater: 26, agile: 26,
      abilities: ["Groundball Pitcher"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 0, 1, 3, 0, 0]) },
    { firstName: "Ryan", lastName: "Takahashi", position: "P", eligibility: "JR", homeState: "CA", hometown: "Torrance", jerseyNumber: 28,
      hitForAvg: 12, power: 10, speed: 28, arm: 31, fielding: 20, errorResistance: 30, velocity: 34, control: 36, stamina: 29, stuff: 27,
      clutch: 38, vsLHP: 37, grit: 40, stealing: 8, running: 24, throwing: 44, recovery: 27, wRISP: 26, vsLefty: 26, poise: 28, heater: 31, agile: 27,
      abilities: ["Star of Victory"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 5, 1, 0, 3, 0]) },
    { firstName: "Derek", lastName: "Ng", position: "P", eligibility: "SR", homeState: "CA", hometown: "San Francisco", jerseyNumber: 31,
      hitForAvg: 26, power: 19, speed: 40, arm: 62, fielding: 43, errorResistance: 62, velocity: 65, control: 63, stamina: 57, stuff: 54,
      clutch: 77, vsLHP: 75, grit: 81, stealing: 15, running: 38, throwing: 80, recovery: 57, wRISP: 56, vsLefty: 57, poise: 63, heater: 61, agile: 48,
      abilities: ["Guts", "Good Pickoff", "Strikeout", "Strong Starter"], potential: "B-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 0, 1, 3, 0, 0]) },
    { firstName: "Sean", lastName: "Watanabe", position: "P", eligibility: "JR", homeState: "CA", hometown: "Cupertino", jerseyNumber: 47,
      hitForAvg: 21, power: 17, speed: 36, arm: 54, fielding: 34, errorResistance: 51, velocity: 58, control: 52, stamina: 47, stuff: 47,
      clutch: 59, vsLHP: 58, grit: 63, stealing: 16, running: 39, throwing: 68, recovery: 46, wRISP: 45, vsLefty: 46, poise: 49, heater: 54, agile: 45,
      abilities: ["Perfect Combustion", "Heavy Ball", "Gyroball", "Intimidator"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    { firstName: "Marcus", lastName: "Chen", position: "P", eligibility: "FR", homeState: "CA", hometown: "Fremont", jerseyNumber: 48,
      hitForAvg: 11, power: 8, speed: 27, arm: 29, fielding: 16, errorResistance: 26, velocity: 38, control: 22, stamina: 21, stuff: 26,
      clutch: 28, vsLHP: 26, grit: 29, stealing: 11, running: 25, throwing: 43, recovery: 18, wRISP: 18, vsLefty: 19, poise: 18, heater: 29, agile: 29,
      abilities: ["Poker Face", "Natural Shuuto"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Cole", lastName: "Posey", position: "P", eligibility: "FR", homeState: "CA", hometown: "Pleasanton", jerseyNumber: 49,
      hitForAvg: 12, power: 10, speed: 28, arm: 34, fielding: 19, errorResistance: 29, velocity: 41, control: 24, stamina: 24, stuff: 28,
      clutch: 30, vsLHP: 29, grit: 33, stealing: 11, running: 27, throwing: 46, recovery: 20, wRISP: 19, vsLefty: 22, poise: 20, heater: 34, agile: 33,
      abilities: ["Wizard Mode"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 6, 3, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Carl", lastName: "Schmidt", position: "C", eligibility: "SR", homeState: "CA", hometown: "San Mateo", jerseyNumber: 10,
      hitForAvg: 48, power: 45, speed: 36, arm: 52, fielding: 48, errorResistance: 47, velocity: 0, control: 0, stamina: 29, stuff: 0,
      clutch: 45, vsLHP: 43, grit: 48, stealing: 15, running: 28, throwing: 53, recovery: 39, wRISP: 44, vsLefty: 42, poise: 47, heater: 0, agile: 33,
      abilities: ["Ace Killer", "Multi-Hit"], potential: "B", catcherAbility: 48,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Nate", lastName: "Arakawa", position: "C", eligibility: "SO", homeState: "CA", hometown: "Sacramento", jerseyNumber: 24,
      hitForAvg: 34, power: 29, speed: 31, arm: 38, fielding: 34, errorResistance: 31, velocity: 0, control: 0, stamina: 21, stuff: 0,
      clutch: 29, vsLHP: 25, grit: 29, stealing: 8, running: 21, throwing: 35, recovery: 25, wRISP: 28, vsLefty: 24, poise: 29, heater: 0, agile: 23,
      abilities: ["Double Play"], potential: "B", catcherAbility: 34,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Cade", lastName: "Campbell", position: "3B", eligibility: "JR", homeState: "CA", hometown: "San Jose", jerseyNumber: 2,
      hitForAvg: 56, power: 48, speed: 53, arm: 50, fielding: 50, errorResistance: 49, velocity: 0, control: 0, stamina: 27, stuff: 0,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 27, running: 41, throwing: 52, recovery: 41, wRISP: 49, vsLefty: 47, poise: 49, heater: 0, agile: 45,
      abilities: ["Defensive Artisan", "Consigliere"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Jacob", lastName: "French", position: "2B", eligibility: "JR", homeState: "CA", hometown: "Long Beach", jerseyNumber: 4,
      hitForAvg: 41, power: 28, speed: 42, arm: 31, fielding: 33, errorResistance: 32, velocity: 0, control: 0, stamina: 19, stuff: 0,
      clutch: 33, vsLHP: 31, grit: 34, stealing: 20, running: 28, throwing: 32, recovery: 26, wRISP: 34, vsLefty: 30, poise: 32, heater: 0, agile: 31,
      abilities: ["Contact Hitter", "Chance Maker"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Joshua", lastName: "Hanson", position: "1B", eligibility: "JR", homeState: "CA", hometown: "Pasadena", jerseyNumber: 15,
      hitForAvg: 54, power: 57, speed: 48, arm: 50, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 30, stuff: 0,
      clutch: 50, vsLHP: 48, grit: 51, stealing: 15, running: 36, throwing: 51, recovery: 41, wRISP: 50, vsLefty: 45, poise: 50, heater: 0, agile: 37,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Devin", lastName: "Ramirez", position: "SS", eligibility: "SO", homeState: "CA", hometown: "Stockton", jerseyNumber: 8,
      hitForAvg: 38, power: 32, speed: 54, arm: 39, fielding: 39, errorResistance: 37, velocity: 0, control: 0, stamina: 21, stuff: 0,
      clutch: 33, vsLHP: 30, grit: 35, stealing: 24, running: 35, throwing: 40, recovery: 29, wRISP: 33, vsLefty: 29, poise: 33, heater: 0, agile: 37,
      abilities: ["God of Pinch Hitting", "Consigliere", "Contact Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Ian", lastName: "Fujimoto", position: "1B", eligibility: "SO", homeState: "CA", hometown: "Irvine", jerseyNumber: 23,
      hitForAvg: 35, power: 37, speed: 45, arm: 34, fielding: 34, errorResistance: 32, velocity: 0, control: 0, stamina: 22, stuff: 0,
      clutch: 30, vsLHP: 28, grit: 31, stealing: 11, running: 22, throwing: 35, recovery: 25, wRISP: 29, vsLefty: 25, poise: 30, heater: 0, agile: 24,
      abilities: ["Bad Mood"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Ethan", lastName: "Kwan", position: "2B", eligibility: "FR", homeState: "CA", hometown: "Oakland", jerseyNumber: 18,
      hitForAvg: 33, power: 24, speed: 54, arm: 33, fielding: 27, errorResistance: 24, velocity: 0, control: 0, stamina: 17, stuff: 0,
      clutch: 22, vsLHP: 19, grit: 22, stealing: 18, running: 27, throwing: 28, recovery: 19, wRISP: 22, vsLefty: 18, poise: 22, heater: 0, agile: 29,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Jamal", lastName: "Patterson", position: "3B", eligibility: "FR", homeState: "CA", hometown: "Compton", jerseyNumber: 16,
      hitForAvg: 36, power: 31, speed: 50, arm: 36, fielding: 28, errorResistance: 28, velocity: 0, control: 0, stamina: 19, stuff: 0,
      clutch: 24, vsLHP: 24, grit: 26, stealing: 16, running: 28, throwing: 33, recovery: 24, wRISP: 24, vsLefty: 20, poise: 24, heater: 0, agile: 31,
      abilities: ["Walkoff Hitter", "First Pitch Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Seth", lastName: "Gwynn", position: "OF", eligibility: "SR", homeState: "CA", hometown: "Concord", jerseyNumber: 7,
      hitForAvg: 53, power: 49, speed: 62, arm: 49, fielding: 49, errorResistance: 46, velocity: 0, control: 0, stamina: 30, stuff: 0,
      clutch: 49, vsLHP: 45, grit: 50, stealing: 29, running: 44, throwing: 50, recovery: 42, wRISP: 46, vsLefty: 44, poise: 49, heater: 0, agile: 45,
      abilities: ["Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Alex", lastName: "Birge", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Danville", jerseyNumber: 9,
      hitForAvg: 55, power: 48, speed: 66, arm: 54, fielding: 54, errorResistance: 51, velocity: 0, control: 0, stamina: 31, stuff: 0,
      clutch: 50, vsLHP: 45, grit: 51, stealing: 34, running: 51, throwing: 56, recovery: 42, wRISP: 48, vsLefty: 44, poise: 50, heater: 0, agile: 54,
      abilities: ["Express Baserunning"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Ricky", lastName: "Navarro", position: "OF", eligibility: "SO", homeState: "CA", hometown: "San Diego", jerseyNumber: 11,
      hitForAvg: 35, power: 32, speed: 46, arm: 35, fielding: 34, errorResistance: 33, velocity: 0, control: 0, stamina: 22, stuff: 0,
      clutch: 30, vsLHP: 27, grit: 32, stealing: 20, running: 33, throwing: 36, recovery: 26, wRISP: 29, vsLefty: 26, poise: 30, heater: 0, agile: 34,
      abilities: ["Contact Hitter"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...noPitches },
    { firstName: "Grant", lastName: "Larson", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Santa Cruz", jerseyNumber: 20,
      hitForAvg: 39, power: 34, speed: 49, arm: 37, fielding: 37, errorResistance: 34, velocity: 0, control: 0, stamina: 23, stuff: 0,
      clutch: 34, vsLHP: 32, grit: 34, stealing: 20, running: 34, throwing: 38, recovery: 30, wRISP: 33, vsLefty: 30, poise: 34, heater: 0, agile: 34,
      abilities: ["Head-first Slide", "Storming Home", "Pinch Hitter"], potential: "B-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Kyle", lastName: "Watkins", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Walnut Creek", jerseyNumber: 13,
      hitForAvg: 34, power: 30, speed: 43, arm: 34, fielding: 34, errorResistance: 32, velocity: 0, control: 0, stamina: 21, stuff: 0,
      clutch: 31, vsLHP: 29, grit: 32, stealing: 19, running: 31, throwing: 34, recovery: 25, wRISP: 30, vsLefty: 26, poise: 31, heater: 0, agile: 32,
      abilities: ["Trickster", "Contact Hitter", "Consigliere"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Tyler", lastName: "Maki", position: "OF", eligibility: "FR", homeState: "CA", hometown: "Fresno", jerseyNumber: 19,
      hitForAvg: 31, power: 25, speed: 44, arm: 31, fielding: 26, errorResistance: 26, velocity: 0, control: 0, stamina: 19, stuff: 0,
      clutch: 22, vsLHP: 20, grit: 23, stealing: 19, running: 30, throwing: 31, recovery: 20, wRISP: 20, vsLefty: 19, poise: 22, heater: 0, agile: 31,
      abilities: ["Inside Hitter", "Contact Hitter", "Batter Intimidator"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
  ],

  "Stanford": [
    // PITCHERS (10)
    { firstName: "Christian", lastName: "Lim", position: "P", eligibility: "JR", homeState: "CA", hometown: "Irvine", jerseyNumber: 35,
      hitForAvg: 29, power: 24, speed: 38, arm: 79, fielding: 49, errorResistance: 63, velocity: 74, control: 75, stamina: 78, stuff: 75,
      clutch: 84, vsLHP: 80, grit: 87, stealing: 18, running: 47, throwing: 89, recovery: 67, wRISP: 67, vsLefty: 69, poise: 72, heater: 78, agile: 56,
      abilities: ["Strong Starter", "Miracle Sharpness", "Intimidator", "Good Pickoff", "Heavy Ball", "Wild Fastball"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Parker", lastName: "Warner", position: "P", eligibility: "SO", homeState: "CA", hometown: "San Jose", jerseyNumber: 29,
      hitForAvg: 20, power: 17, speed: 36, arm: 56, fielding: 34, errorResistance: 49, velocity: 61, control: 52, stamina: 54, stuff: 50,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 15, running: 38, throwing: 72, recovery: 46, wRISP: 43, vsLefty: 46, poise: 47, heater: 55, agile: 45,
      abilities: ["Guts", "High Spin Gyroball", "Natural Shuuto", "Groundball Pitcher"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...pitchMix(1, [1, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Aidan", lastName: "Keenan", position: "P", eligibility: "JR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 41,
      hitForAvg: 15, power: 12, speed: 27, arm: 41, fielding: 25, errorResistance: 36, velocity: 43, control: 37, stamina: 40, stuff: 37,
      clutch: 47, vsLHP: 45, grit: 48, stealing: 10, running: 27, throwing: 53, recovery: 34, wRISP: 34, vsLefty: 35, poise: 37, heater: 41, agile: 33,
      abilities: ["Guts", "Painter", "Strong Finisher"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 6, 4, 1, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Bruno", position: "P", eligibility: "JR", homeState: "CA", hometown: "Redwood City", jerseyNumber: 38,
      hitForAvg: 23, power: 17, speed: 39, arm: 58, fielding: 39, errorResistance: 55, velocity: 64, control: 57, stamina: 55, stuff: 55,
      clutch: 67, vsLHP: 66, grit: 69, stealing: 16, running: 39, throwing: 77, recovery: 51, wRISP: 50, vsLefty: 51, poise: 55, heater: 58, agile: 47,
      abilities: ["True Slider", "Guts", "Doctor K"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 6, 1, 0, 0, 0]) },
    { firstName: "Justin", lastName: "Campbell", position: "P", eligibility: "SR", homeState: "CA", hometown: "Palo Alto", jerseyNumber: 44,
      hitForAvg: 22, power: 18, speed: 34, arm: 52, fielding: 34, errorResistance: 50, velocity: 56, control: 52, stamina: 48, stuff: 47,
      clutch: 62, vsLHP: 60, grit: 66, stealing: 14, running: 34, throwing: 66, recovery: 45, wRISP: 45, vsLefty: 47, poise: 50, heater: 52, agile: 40,
      abilities: ["Fireman", "Guts"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 0, 1, 3, 0, 0]) },
    { firstName: "Ty", lastName: "Uber", position: "P", eligibility: "SR", homeState: "CA", hometown: "Menlo Park", jerseyNumber: 32,
      hitForAvg: 9, power: 8, speed: 23, arm: 23, fielding: 14, errorResistance: 25, velocity: 23, control: 22, stamina: 20, stuff: 23,
      clutch: 30, vsLHP: 29, grit: 32, stealing: 6, running: 16, throwing: 34, recovery: 19, wRISP: 19, vsLefty: 19, poise: 21, heater: 23, agile: 21,
      abilities: ["Top Gear", "Intimidator"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 6, 4, 0, 3, 0, 0]) },
    { firstName: "Carson", lastName: "Peer", position: "P", eligibility: "SO", homeState: "CA", hometown: "Santa Monica", jerseyNumber: 46,
      hitForAvg: 10, power: 7, speed: 25, arm: 23, fielding: 15, errorResistance: 25, velocity: 34, control: 19, stamina: 18, stuff: 25,
      clutch: 28, vsLHP: 27, grit: 29, stealing: 7, running: 20, throwing: 35, recovery: 17, wRISP: 16, vsLefty: 18, poise: 17, heater: 23, agile: 24,
      abilities: ["Cross Cannon"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Drew", lastName: "Dowd", position: "P", eligibility: "JR", homeState: "CA", hometown: "Sacramento", jerseyNumber: 47,
      hitForAvg: 10, power: 6, speed: 26, arm: 24, fielding: 16, errorResistance: 25, velocity: 34, control: 22, stamina: 22, stuff: 26,
      clutch: 30, vsLHP: 29, grit: 31, stealing: 6, running: 19, throwing: 35, recovery: 20, wRISP: 19, vsLefty: 20, poise: 21, heater: 24, agile: 22,
      abilities: ["Release"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "David", lastName: "Wiser", position: "P", eligibility: "FR", homeState: "CA", hometown: "San Diego", jerseyNumber: 48,
      hitForAvg: 11, power: 9, speed: 27, arm: 31, fielding: 16, errorResistance: 26, velocity: 38, control: 22, stamina: 21, stuff: 27,
      clutch: 28, vsLHP: 27, grit: 29, stealing: 12, running: 27, throwing: 46, recovery: 19, wRISP: 17, vsLefty: 19, poise: 19, heater: 31, agile: 31,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 6, 4, 1, 0, 0, 0]) },
    { firstName: "Colt", lastName: "Peterson", position: "P", eligibility: "FR", homeState: "CA", hometown: "Fresno", jerseyNumber: 49,
      hitForAvg: 12, power: 9, speed: 30, arm: 34, fielding: 19, errorResistance: 29, velocity: 43, control: 24, stamina: 22, stuff: 29,
      clutch: 31, vsLHP: 29, grit: 31, stealing: 12, running: 29, throwing: 49, recovery: 20, wRISP: 19, vsLefty: 20, poise: 20, heater: 34, agile: 34,
      abilities: ["Grit"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 3, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Charlie", lastName: "Bates", position: "C", eligibility: "JR", homeState: "CA", hometown: "Stockton", jerseyNumber: 10,
      hitForAvg: 37, power: 33, speed: 26, arm: 37, fielding: 34, errorResistance: 33, velocity: 0, control: 0, stamina: 21, stuff: 0,
      clutch: 33, vsLHP: 32, grit: 34, stealing: 11, running: 21, throwing: 39, recovery: 29, wRISP: 33, vsLefty: 30, poise: 33, heater: 0, agile: 25,
      abilities: ["High-Speed Laser"], potential: "B+", catcherAbility: 36,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "JJ", lastName: "Moran", position: "C", eligibility: "SO", homeState: "CA", hometown: "Newport Beach", jerseyNumber: 24,
      hitForAvg: 35, power: 31, speed: 29, arm: 38, fielding: 34, errorResistance: 33, velocity: 0, control: 0, stamina: 21, stuff: 0,
      clutch: 30, vsLHP: 29, grit: 33, stealing: 10, running: 21, throwing: 37, recovery: 28, wRISP: 29, vsLefty: 28, poise: 30, heater: 0, agile: 24,
      abilities: ["Double Play"], potential: "B+", catcherAbility: 35,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // INFIELDERS (8)
    { firstName: "Rintaro", lastName: "Sasaki", position: "1B", eligibility: "SO", homeState: "CA", hometown: "Stanford", jerseyNumber: 21,
      hitForAvg: 91, power: 99, speed: 63, arm: 51, fielding: 58, errorResistance: 54, velocity: 0, control: 0, stamina: 31, stuff: 0,
      clutch: 78, vsLHP: 71, grit: 75, stealing: 15, running: 35, throwing: 51, recovery: 49, wRISP: 76, vsLefty: 69, poise: 71, heater: 0, agile: 38,
      abilities: ["Power Hitter", "Consigliere", "vs. Fastballs"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Jimmy", lastName: "Nati", position: "3B", eligibility: "SR", homeState: "NJ", hometown: "Toms River", jerseyNumber: 6,
      hitForAvg: 40, power: 41, speed: 37, arm: 35, fielding: 33, errorResistance: 32, velocity: 0, control: 0, stamina: 21, stuff: 0,
      clutch: 37, vsLHP: 35, grit: 37, stealing: 12, running: 24, throwing: 37, recovery: 30, wRISP: 37, vsLefty: 34, poise: 37, heater: 0, agile: 25,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Ethan", lastName: "Hott", position: "2B", eligibility: "JR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 3,
      hitForAvg: 37, power: 28, speed: 46, arm: 30, fielding: 31, errorResistance: 31, velocity: 0, control: 0, stamina: 17, stuff: 0,
      clutch: 31, vsLHP: 30, grit: 32, stealing: 18, running: 27, throwing: 31, recovery: 25, wRISP: 31, vsLefty: 28, poise: 31, heater: 0, agile: 28,
      abilities: ["Contact Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Brady", lastName: "Reynolds", position: "SS", eligibility: "JR", homeState: "CA", hometown: "Carlsbad", jerseyNumber: 1,
      hitForAvg: 33, power: 27, speed: 48, arm: 33, fielding: 33, errorResistance: 33, velocity: 0, control: 0, stamina: 17, stuff: 0,
      clutch: 30, vsLHP: 28, grit: 31, stealing: 20, running: 29, throwing: 34, recovery: 25, wRISP: 29, vsLefty: 27, poise: 30, heater: 0, agile: 31,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Eric", lastName: "Jeon", position: "2B", eligibility: "JR", homeState: "NY", hometown: "New York", jerseyNumber: 14,
      hitForAvg: 61, power: 42, speed: 65, arm: 49, fielding: 51, errorResistance: 49, velocity: 0, control: 0, stamina: 30, stuff: 0,
      clutch: 51, vsLHP: 47, grit: 52, stealing: 30, running: 44, throwing: 51, recovery: 41, wRISP: 51, vsLefty: 45, poise: 51, heater: 0, agile: 47,
      abilities: ["Chance Maker"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Brock", lastName: "Sell", position: "3B", eligibility: "FR", homeState: "CA", hometown: "San Clemente", jerseyNumber: 12,
      hitForAvg: 64, power: 57, speed: 55, arm: 58, fielding: 54, errorResistance: 49, velocity: 0, control: 0, stamina: 31, stuff: 0,
      clutch: 54, vsLHP: 49, grit: 54, stealing: 27, running: 47, throwing: 61, recovery: 42, wRISP: 50, vsLefty: 47, poise: 49, heater: 0, agile: 50,
      abilities: ["Consigliere"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Brock", lastName: "Ketelsen", position: "SS", eligibility: "FR", homeState: "CA", hometown: "Encinitas", jerseyNumber: 8,
      hitForAvg: 37, power: 28, speed: 61, arm: 37, fielding: 28, errorResistance: 26, velocity: 0, control: 0, stamina: 17, stuff: 0,
      clutch: 26, vsLHP: 24, grit: 27, stealing: 18, running: 28, throwing: 31, recovery: 20, wRISP: 25, vsLefty: 23, poise: 25, heater: 0, agile: 30,
      abilities: ["Pull Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Teddy", lastName: "Tokheim", position: "OF", eligibility: "FR", homeState: "MN", hometown: "Edina", jerseyNumber: 18,
      hitForAvg: 37, power: 82, speed: 53, arm: 37, fielding: 30, errorResistance: 28, velocity: 0, control: 0, stamina: 20, stuff: 0,
      clutch: 28, vsLHP: 25, grit: 28, stealing: 16, running: 28, throwing: 35, recovery: 23, wRISP: 27, vsLefty: 23, poise: 28, heater: 0, agile: 30,
      abilities: ["Shock Commander"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...noPitches },
    // OUTFIELDERS (5)
    { firstName: "Tatum", lastName: "Marsh", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Atherton", jerseyNumber: 7,
      hitForAvg: 39, power: 31, speed: 40, arm: 32, fielding: 32, errorResistance: 31, velocity: 0, control: 0, stamina: 18, stuff: 0,
      clutch: 33, vsLHP: 32, grit: 33, stealing: 20, running: 30, throwing: 32, recovery: 26, wRISP: 33, vsLefty: 31, poise: 32, heater: 0, agile: 31,
      abilities: ["Contact Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Luke", lastName: "Lavin", position: "OF", eligibility: "JR", homeState: "CA", hometown: "San Francisco", jerseyNumber: 20,
      hitForAvg: 55, power: 48, speed: 61, arm: 52, fielding: 51, errorResistance: 48, velocity: 0, control: 0, stamina: 31, stuff: 0,
      clutch: 48, vsLHP: 44, grit: 51, stealing: 31, running: 47, throwing: 53, recovery: 42, wRISP: 47, vsLefty: 43, poise: 48, heater: 0, agile: 48,
      abilities: ["Home Defense"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "R",
      ...noPitches },
    { firstName: "Cort", lastName: "MacDonald", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Walnut Creek", jerseyNumber: 27,
      hitForAvg: 53, power: 45, speed: 57, arm: 49, fielding: 49, errorResistance: 47, velocity: 0, control: 0, stamina: 31, stuff: 0,
      clutch: 46, vsLHP: 43, grit: 47, stealing: 32, running: 47, throwing: 51, recovery: 40, wRISP: 44, vsLefty: 41, poise: 46, heater: 0, agile: 49,
      abilities: ["Express Baserunning"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...noPitches },
    { firstName: "Jack", lastName: "O'Brien", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Atherton", jerseyNumber: 22,
      hitForAvg: 30, power: 26, speed: 43, arm: 30, fielding: 26, errorResistance: 25, velocity: 0, control: 0, stamina: 16, stuff: 0,
      clutch: 24, vsLHP: 23, grit: 25, stealing: 16, running: 25, throwing: 28, recovery: 22, wRISP: 23, vsLefty: 22, poise: 24, heater: 0, agile: 26,
      abilities: ["Artist", "Walkoff Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Drew", lastName: "Bowser", position: "OF", eligibility: "SO", homeState: "CA", hometown: "Sacramento", jerseyNumber: 9,
      hitForAvg: 33, power: 30, speed: 49, arm: 33, fielding: 31, errorResistance: 30, velocity: 0, control: 0, stamina: 19, stuff: 0,
      clutch: 28, vsLHP: 25, grit: 29, stealing: 19, running: 31, throwing: 33, recovery: 24, wRISP: 27, vsLefty: 24, poise: 28, heater: 0, agile: 32,
      abilities: ["Predicament"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
  ],

  "Virginia": [
      // 32-16/12-12 ACC, RPI #18, D1B #20s, peak #10. Chris Pollard Yr 1 (from Duke). HR 5th nation, Runs 9th nation.
      // PITCHERS (10) — 1-8 pitch scale
      // Henry Zatkowski — Friday JR RHP, 7IP/2ER/10K vs Clemson, established Friday ace
      { firstName: "Henry", lastName: "Zatkowski", position: "P", eligibility: "JR", homeState: "NC", hometown: "Durham", jerseyNumber: 34,
        hitForAvg: 15, power: 12, speed: 34, arm: 67, fielding: 43, errorResistance: 58, velocity: 67, control: 68, stamina: 68, stuff: 65,
        clutch: 82, vsLHP: 74, grit: 82, stealing: 10, running: 34, throwing: 82, recovery: 56, wRISP: 60, vsLefty: 65, poise: 65, heater: 67, agile: 45,
        abilities: ["Strong Starter", "Sharpness", "Doctor K", "Strong Finisher"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 6, 1, 0, 0, 0]) },
      // Kyle Johnson — Saturday LHP JR, 6-0/4.06 ERA, team-high 73 K, 1.20 ERA at home
      { firstName: "Kyle", lastName: "Johnson", position: "P", eligibility: "JR", homeState: "VA", hometown: "Richmond", jerseyNumber: 21,
        hitForAvg: 14, power: 13, speed: 31, arm: 62, fielding: 39, errorResistance: 50, velocity: 62, control: 59, stamina: 62, stuff: 62,
        clutch: 75, vsLHP: 79, grit: 71, stealing: 10, running: 32, throwing: 73, recovery: 53, wRISP: 59, vsLefty: 65, poise: 62, heater: 65, agile: 41,
        abilities: ["Strong Starter", "Fireman", "Doctor K", "Intimidator"], potential: "A", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [6, 0, 5, 1, 0, 0, 0]) },
      // Tyler Kapa — Sunday/Stopper JR RHP, "unicorn" outlier metrics, Stopper of Year semi, 90K/66IP last yr
      { firstName: "Tyler", lastName: "Kapa", position: "P", eligibility: "JR", homeState: "VA", hometown: "Richmond", jerseyNumber: 26,
        hitForAvg: 12, power: 10, speed: 28, arm: 59, fielding: 34, errorResistance: 47, velocity: 58, control: 49, stamina: 49, stuff: 59,
        clutch: 66, vsLHP: 60, grit: 66, stealing: 9, running: 28, throwing: 69, recovery: 44, wRISP: 49, vsLefty: 49, poise: 52, heater: 59, agile: 36,
        abilities: ["Doctor K", "Intimidator", "Sharpness", "Heavy Ball"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 7, 6, 1, 0, 0, 0]) },
      // Lucas Hartman — closer JR, 12 G (T-3rd nation), NPOY + SOY semi, Midseason 2nd Team All-Am — TEAM ELITE STUFF
      { firstName: "Lucas", lastName: "Hartman", position: "P", eligibility: "JR", homeState: "KY", hometown: "Bowling Green", jerseyNumber: 40,
        hitForAvg: 13, power: 10, speed: 32, arm: 65, fielding: 40, errorResistance: 55, velocity: 65, control: 63, stamina: 40, stuff: 70,
        clutch: 81, vsLHP: 77, grit: 81, stealing: 9, running: 31, throwing: 79, recovery: 45, wRISP: 65, vsLefty: 62, poise: 65, heater: 68, agile: 42,
        abilities: ["Fireman", "Doctor K", "Inside Pitch"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 7, 0, 1, 0, 5, 0]) },
      // Joe Colucci — JR RHP RP
      { firstName: "Joe", lastName: "Colucci", position: "P", eligibility: "JR", homeState: "VA", hometown: "Virginia Beach", jerseyNumber: 27,
        hitForAvg: 8, power: 6, speed: 20, arm: 31, fielding: 19, errorResistance: 28, velocity: 33, control: 31, stamina: 25, stuff: 28,
        clutch: 39, vsLHP: 37, grit: 39, stealing: 6, running: 20, throwing: 40, recovery: 26, wRISP: 28, vsLefty: 28, poise: 28, heater: 32, agile: 25,
        abilities: ["Fireman", "Winner's Luck", "Poker Face"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
      // Max Stammel — JR RHP rotation depth
      { firstName: "Max", lastName: "Stammel", position: "P", eligibility: "JR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 37,
        hitForAvg: 13, power: 10, speed: 28, arm: 46, fielding: 28, errorResistance: 39, velocity: 49, control: 43, stamina: 43, stuff: 42,
        clutch: 53, vsLHP: 49, grit: 53, stealing: 8, running: 28, throwing: 56, recovery: 39, wRISP: 39, vsLefty: 40, poise: 40, heater: 47, agile: 36,
        abilities: ["Guts", "Low Ball", "Showtime", "Strong Finisher"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
      // Matt Buchanan — SR RHP
      { firstName: "Matt", lastName: "Buchanan", position: "P", eligibility: "SR", homeState: "VA", hometown: "Fairfax", jerseyNumber: 44,
        hitForAvg: 9, power: 8, speed: 24, arm: 27, fielding: 17, errorResistance: 27, velocity: 27, control: 32, stamina: 24, stuff: 24,
        clutch: 34, vsLHP: 34, grit: 37, stealing: 6, running: 19, throwing: 37, recovery: 23, wRISP: 23, vsLefty: 23, poise: 26, heater: 27, agile: 22,
        abilities: ["Guts"], potential: "B", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 0, 1, 3, 0, 0]) },
      // Noah Yoder — FR RHP — PG Frosh 2nd Team / Top-200 national
      { firstName: "Noah", lastName: "Yoder", position: "P", eligibility: "FR", homeState: "VA", hometown: "Harrisonburg", jerseyNumber: 49,
        hitForAvg: 8, power: 7, speed: 22, arm: 35, fielding: 14, errorResistance: 22, velocity: 40, control: 28, stamina: 26, stuff: 32,
        clutch: 26, vsLHP: 24, grit: 26, stealing: 9, running: 21, throwing: 37, recovery: 16, wRISP: 16, vsLefty: 17, poise: 17, heater: 28, agile: 26,
        abilities: ["Explosive Fastball"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 4, 1, 0, 0, 0]) },
      // Jayden Stroman — FR midweek SP — PG HM / Top-500 national (2.70 ERA / 16 K in 13.1 IP)
      { firstName: "Jayden", lastName: "Stroman", position: "P", eligibility: "FR", homeState: "VA", hometown: "Chesapeake", jerseyNumber: 48,
        hitForAvg: 10, power: 8, speed: 25, arm: 36, fielding: 16, errorResistance: 26, velocity: 42, control: 32, stamina: 31, stuff: 33,
        clutch: 31, vsLHP: 29, grit: 31, stealing: 11, running: 27, throwing: 41, recovery: 20, wRISP: 21, vsLefty: 22, poise: 22, heater: 30, agile: 30,
        abilities: ["Strong Starter", "Doctor K"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
      // Kevin Jaxel — JR RHP
      { firstName: "Kevin", lastName: "Jaxel", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Ridgewood", jerseyNumber: 31,
        hitForAvg: 10, power: 9, speed: 27, arm: 29, fielding: 20, errorResistance: 29, velocity: 31, control: 35, stamina: 26, stuff: 26,
        clutch: 35, vsLHP: 34, grit: 36, stealing: 9, running: 23, throwing: 39, recovery: 23, wRISP: 23, vsLefty: 23, poise: 24, heater: 29, agile: 26,
        abilities: ["Gyroball"], potential: "B", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 4, 1, 0, 3, 0]) },
      // CATCHERS (2)
      // Ethan Anderson — JR C
      { firstName: "Ethan", lastName: "Anderson", position: "C", eligibility: "JR", homeState: "VA", hometown: "Charlottesville", jerseyNumber: 12,
        hitForAvg: 44, power: 40, speed: 27, arm: 43, fielding: 39, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 39, vsLHP: 35, grit: 39, stealing: 11, running: 23, throwing: 43, recovery: 32, wRISP: 39, vsLefty: 35, poise: 39, heater: 0, agile: 27,
        abilities: ["High-Speed Laser", "Defensive Artisan"], potential: "A-", catcherAbility: 41,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Thomas O'Connell — FR C
      { firstName: "Thomas", lastName: "O'Connell", position: "C", eligibility: "FR", homeState: "MD", hometown: "Bethesda", jerseyNumber: 25,
        hitForAvg: 32, power: 28, speed: 28, arm: 34, fielding: 32, errorResistance: 27, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 25, vsLHP: 22, grit: 25, stealing: 8, running: 19, throwing: 33, recovery: 22, wRISP: 23, vsLefty: 22, poise: 25, heater: 0, agile: 22,
        abilities: ["Artist"], potential: "A-", catcherAbility: 32,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // INFIELDERS (7)
      // Eric Becker — SS SR, Brooks Wallace Award (top SS), offensive anchor — TEAM ELITE HIT
      { firstName: "Eric", lastName: "Becker", position: "SS", eligibility: "SR", homeState: "VA", hometown: "Fredericksburg", jerseyNumber: 2,
        hitForAvg: 91, power: 88, speed: 91, arm: 87, fielding: 91, errorResistance: 91, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 91, vsLHP: 91, grit: 91, stealing: 62, running: 80, throwing: 91, recovery: 70, wRISP: 91, vsLefty: 91, poise: 91, heater: 0, agile: 87,
        abilities: ["Magician", "Contact Hitter", "Defensive Artisan", "Consigliere"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Harrison Didawick — 1B SR, power bat
      { firstName: "Harrison", lastName: "Didawick", position: "1B", eligibility: "SR", homeState: "VA", hometown: "Fredericksburg", jerseyNumber: 24,
        hitForAvg: 67, power: 77, speed: 56, arm: 50, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 71, vsLHP: 65, grit: 71, stealing: 13, running: 31, throwing: 50, recovery: 43, wRISP: 71, vsLefty: 65, poise: 71, heater: 0, agile: 37,
        abilities: ["Artist", "Power Hitter", "Consigliere"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Sam Harris — 2B JR, multi-HR vs Monmouth
      { firstName: "Sam", lastName: "Harris", position: "2B", eligibility: "JR", homeState: "VA", hometown: "McLean", jerseyNumber: 8,
        hitForAvg: 61, power: 78, speed: 62, arm: 46, fielding: 47, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 55, vsLHP: 50, grit: 55, stealing: 24, running: 38, throwing: 46, recovery: 38, wRISP: 55, vsLefty: 50, poise: 55, heater: 0, agile: 44,
        abilities: ["Power Hitter", "Contact Hitter"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Noah Murray — INF, broke program record for runs in game (3-run blast), Crozet native
      { firstName: "Noah", lastName: "Murray", position: "2B", eligibility: "JR", homeState: "VA", hometown: "Crozet", jerseyNumber: 9,
        hitForAvg: 59, power: 59, speed: 59, arm: 44, fielding: 46, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 62, vsLHP: 49, grit: 53, stealing: 19, running: 37, throwing: 44, recovery: 37, wRISP: 62, vsLefty: 49, poise: 53, heater: 0, agile: 40,
        abilities: ["Power Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "S",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Aiden Harris — 3B FR
      { firstName: "Aiden", lastName: "Harris", position: "3B", eligibility: "FR", homeState: "VA", hometown: "Alexandria", jerseyNumber: 3,
        hitForAvg: 39, power: 35, speed: 35, arm: 37, fielding: 33, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 35, vsLHP: 30, grit: 34, stealing: 17, running: 32, throwing: 38, recovery: 26, wRISP: 35, vsLefty: 30, poise: 32, heater: 0, agile: 33,
        abilities: ["Consigliere"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Zach Jackson — 3B JR, homered in VCU sweep
      { firstName: "Zach", lastName: "Jackson", position: "3B", eligibility: "JR", homeState: "VA", hometown: "Norfolk", jerseyNumber: 14,
        hitForAvg: 49, power: 49, speed: 46, arm: 38, fielding: 37, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 42, vsLHP: 38, grit: 42, stealing: 12, running: 24, throwing: 38, recovery: 30, wRISP: 42, vsLefty: 38, poise: 42, heater: 0, agile: 27,
        abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // RJ Holmes — SS FR
      { firstName: "RJ", lastName: "Holmes", position: "SS", eligibility: "FR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 18,
        hitForAvg: 33, power: 26, speed: 56, arm: 33, fielding: 28, errorResistance: 27, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 22, vsLHP: 20, grit: 24, stealing: 19, running: 28, throwing: 32, recovery: 22, wRISP: 22, vsLefty: 19, poise: 22, heater: 0, agile: 30,
        abilities: ["Artist", "Multi-Hit", "Contact Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "fade",
        ...noPitches },
      // OUTFIELDERS (6)
      // AJ Gracia — OF JR, Perfect Game 1st Team All-American, Golden Spikes Watch List, multi-HR
      { firstName: "AJ", lastName: "Gracia", position: "OF", eligibility: "JR", homeState: "NC", hometown: "Durham", jerseyNumber: 6,
        hitForAvg: 55, power: 63, speed: 45, arm: 40, fielding: 39, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 57, vsLHP: 50, grit: 57, stealing: 26, running: 38, throwing: 40, recovery: 31, wRISP: 57, vsLefty: 50, poise: 57, heater: 0, agile: 40,
        abilities: ["Artist", "Power Hitter", "Contact Hitter"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Antonio Perrotta — OF JR
      { firstName: "Antonio", lastName: "Perrotta", position: "OF", eligibility: "JR", homeState: "VA", hometown: "Leesburg", jerseyNumber: 10,
        hitForAvg: 38, power: 35, speed: 41, arm: 35, fielding: 33, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 33, vsLHP: 31, grit: 33, stealing: 16, running: 28, throwing: 36, recovery: 28, wRISP: 33, vsLefty: 31, poise: 33, heater: 0, agile: 31,
        abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Jack Brendle — OF SO
      { firstName: "Jack", lastName: "Brendle", position: "OF", eligibility: "SO", homeState: "NC", hometown: "Charlotte", jerseyNumber: 16,
        hitForAvg: 32, power: 29, speed: 40, arm: 31, fielding: 30, errorResistance: 28, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 28, vsLHP: 25, grit: 28, stealing: 19, running: 28, throwing: 31, recovery: 23, wRISP: 26, vsLefty: 23, poise: 28, heater: 0, agile: 30,
        abilities: ["Express Baserunning"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Colin Tuft — OF JR
      { firstName: "Colin", lastName: "Tuft", position: "OF", eligibility: "JR", homeState: "VA", hometown: "McLean", jerseyNumber: 7,
        hitForAvg: 39, power: 34, speed: 43, arm: 37, fielding: 37, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 35, vsLHP: 32, grit: 35, stealing: 22, running: 35, throwing: 39, recovery: 29, wRISP: 33, vsLefty: 32, poise: 35, heater: 0, agile: 36,
        abilities: ["High-Speed Laser", "Multi-Hit"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Anthony Stephan — OF SR
      { firstName: "Anthony", lastName: "Stephan", position: "OF", eligibility: "SR", homeState: "VA", hometown: "Leesburg", jerseyNumber: 22,
        hitForAvg: 45, power: 38, speed: 44, arm: 40, fielding: 40, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 40, vsLHP: 35, grit: 42, stealing: 23, running: 35, throwing: 43, recovery: 32, wRISP: 37, vsLefty: 33, poise: 40, heater: 0, agile: 37,
        abilities: ["High-Speed Laser"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Spencer Metz — OF SO
      { firstName: "Spencer", lastName: "Metz", position: "OF", eligibility: "SO", homeState: "VA", hometown: "Manassas", jerseyNumber: 19,
        hitForAvg: 33, power: 28, speed: 47, arm: 32, fielding: 30, errorResistance: 29, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 26, vsLHP: 24, grit: 27, stealing: 19, running: 29, throwing: 30, recovery: 24, wRISP: 24, vsLefty: 23, poise: 26, heater: 0, agile: 30,
        abilities: ["Final Hit", "Error Prone"], potential: "B", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
    ],
  
  "Virginia Tech": [
    // PITCHERS (10)
    { firstName: "Brett", lastName: "Renfrow", position: "P", eligibility: "SR", homeState: "VA", hometown: "Richmond", jerseyNumber: 34,
      hitForAvg: 28, power: 23, speed: 38, arm: 79, fielding: 48, errorResistance: 62, velocity: 78, control: 73, stamina: 74, stuff: 74,
      clutch: 89, vsLHP: 86, grit: 91, stealing: 19, running: 47, throwing: 92, recovery: 70, wRISP: 72, vsLefty: 72, poise: 74, heater: 79, agile: 60,
      abilities: ["Star of Victory", "Intimidator", "Escape Pitch", "Heavy Ball", "Release"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [1, 7, 4, 1, 0, 0, 0]) },
    { firstName: "Logan", lastName: "Eisenreich", position: "P", eligibility: "SO", homeState: "VA", hometown: "Blacksburg", jerseyNumber: 29,
      hitForAvg: 17, power: 13, speed: 32, arm: 44, fielding: 27, errorResistance: 39, velocity: 48, control: 40, stamina: 41, stuff: 39,
      clutch: 49, vsLHP: 47, grit: 51, stealing: 10, running: 32, throwing: 57, recovery: 34, wRISP: 34, vsLefty: 36, poise: 38, heater: 44, agile: 36,
      abilities: ["Strong Starter", "vs. Strong Batters", "Bad Ball Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Aiden", lastName: "Robertson", position: "P", eligibility: "JR", homeState: "GA", hometown: "Augusta", jerseyNumber: 41,
      hitForAvg: 19, power: 15, speed: 35, arm: 54, fielding: 33, errorResistance: 46, velocity: 59, control: 49, stamina: 52, stuff: 49,
      clutch: 63, vsLHP: 60, grit: 63, stealing: 14, running: 34, throwing: 70, recovery: 46, wRISP: 46, vsLefty: 46, poise: 48, heater: 54, agile: 41,
      abilities: ["Guts", "Wild Fastball", "Winner's Luck", "Crossfire"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 6, 4, 1, 0, 0, 0]) },
    { firstName: "Griffin", lastName: "Green", position: "P", eligibility: "JR", homeState: "VA", hometown: "Roanoke", jerseyNumber: 38,
      hitForAvg: 20, power: 17, speed: 33, arm: 54, fielding: 35, errorResistance: 48, velocity: 59, control: 52, stamina: 52, stuff: 50,
      clutch: 60, vsLHP: 59, grit: 64, stealing: 14, running: 37, throwing: 69, recovery: 44, wRISP: 44, vsLefty: 47, poise: 48, heater: 54, agile: 43,
      abilities: ["Guts", "Showtime", "vs. Strong Batters"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Drue", lastName: "Hackenberg", position: "P", eligibility: "SO", homeState: "PA", hometown: "Mechanicsburg", jerseyNumber: 37,
      hitForAvg: 8, power: 7, speed: 23, arm: 22, fielding: 14, errorResistance: 23, velocity: 31, control: 21, stamina: 21, stuff: 23,
      clutch: 28, vsLHP: 28, grit: 30, stealing: 7, running: 18, throwing: 33, recovery: 18, wRISP: 18, vsLefty: 18, poise: 19, heater: 22, agile: 21,
      abilities: ["Delayed Arm"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...pitchMix(1, [0, 4, 6, 1, 0, 0, 0]) },
    { firstName: "Noah", lastName: "Sorrells", position: "P", eligibility: "JR", homeState: "VA", hometown: "Harrisonburg", jerseyNumber: 45,
      hitForAvg: 12, power: 9, speed: 27, arm: 30, fielding: 20, errorResistance: 31, velocity: 33, control: 36, stamina: 28, stuff: 27,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 9, running: 24, throwing: 43, recovery: 26, wRISP: 26, vsLefty: 26, poise: 28, heater: 30, agile: 27,
      abilities: ["Fireman"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 5, 1, 0, 3, 0]) },
    { firstName: "Luke", lastName: "Vickers", position: "P", eligibility: "SR", homeState: "VA", hometown: "Herndon", jerseyNumber: 44,
      hitForAvg: 15, power: 13, speed: 28, arm: 38, fielding: 27, errorResistance: 38, velocity: 44, control: 39, stamina: 36, stuff: 33,
      clutch: 46, vsLHP: 46, grit: 49, stealing: 9, running: 25, throwing: 49, recovery: 34, wRISP: 33, vsLefty: 34, poise: 38, heater: 38, agile: 29,
      abilities: ["Guts", "Gyroball"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 0, 1, 3, 0, 0]) },
    { firstName: "Ethan", lastName: "Douglas", position: "P", eligibility: "SO", homeState: "VA", hometown: "Norfolk", jerseyNumber: 32,
      hitForAvg: 12, power: 9, speed: 29, arm: 31, fielding: 20, errorResistance: 33, velocity: 29, control: 38, stamina: 28, stuff: 28,
      clutch: 38, vsLHP: 37, grit: 40, stealing: 9, running: 26, throwing: 45, recovery: 26, wRISP: 24, vsLefty: 26, poise: 27, heater: 31, agile: 30,
      abilities: ["Explosive Fastball", "Heavy Ball"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Ethan", lastName: "Grim", position: "P", eligibility: "FR", homeState: "VA", hometown: "Lynchburg", jerseyNumber: 47,
      hitForAvg: 9, power: 8, speed: 26, arm: 29, fielding: 17, errorResistance: 26, velocity: 37, control: 22, stamina: 22, stuff: 26,
      clutch: 29, vsLHP: 26, grit: 29, stealing: 9, running: 26, throwing: 43, recovery: 19, wRISP: 19, vsLefty: 20, poise: 20, heater: 29, agile: 29,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 6, 4, 1, 0, 0, 0]) },
    { firstName: "Austin", lastName: "Dean", position: "P", eligibility: "FR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 46,
      hitForAvg: 10, power: 9, speed: 30, arm: 36, fielding: 19, errorResistance: 30, velocity: 43, control: 26, stamina: 24, stuff: 30,
      clutch: 33, vsLHP: 30, grit: 34, stealing: 9, running: 29, throwing: 51, recovery: 20, wRISP: 20, vsLefty: 23, poise: 22, heater: 36, agile: 33,
      abilities: ["Gyroball", "Wizard Mode", "Intimidator"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Henry", lastName: "Cooke", position: "C", eligibility: "JR", homeState: "VA", hometown: "Chesapeake", jerseyNumber: 10,
      hitForAvg: 59, power: 56, speed: 41, arm: 61, fielding: 57, errorResistance: 56, velocity: 0, control: 0, stamina: 33, stuff: 0,
      clutch: 56, vsLHP: 51, grit: 59, stealing: 16, running: 32, throwing: 63, recovery: 48, wRISP: 56, vsLefty: 51, poise: 57, heater: 0, agile: 37,
      abilities: ["High-Speed Laser", "Consigliere"], potential: "A-", catcherAbility: 57,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "CJ", lastName: "Oxendine", position: "C", eligibility: "FR", homeState: "NC", hometown: "Fayetteville", jerseyNumber: 25,
      hitForAvg: 37, power: 31, speed: 33, arm: 39, fielding: 37, errorResistance: 32, velocity: 0, control: 0, stamina: 22, stuff: 0,
      clutch: 29, vsLHP: 27, grit: 30, stealing: 10, running: 22, throwing: 39, recovery: 26, wRISP: 28, vsLefty: 26, poise: 29, heater: 0, agile: 24,
      abilities: ["Double Play"], potential: "A-", catcherAbility: 37,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Sam", lastName: "Grube", position: "2B", eligibility: "SO", homeState: "MD", hometown: "Emmitsburg", jerseyNumber: 4,
      hitForAvg: 36, power: 29, speed: 52, arm: 31, fielding: 33, errorResistance: 31, velocity: 0, control: 0, stamina: 19, stuff: 0,
      clutch: 31, vsLHP: 30, grit: 33, stealing: 28, running: 35, throwing: 33, recovery: 25, wRISP: 31, vsLefty: 29, poise: 31, heater: 0, agile: 36,
      abilities: ["Express Baserunning", "Chance Maker"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Pete", lastName: "Daniel", position: "1B", eligibility: "JR", homeState: "TN", hometown: "Nashville", jerseyNumber: 18,
      hitForAvg: 41, power: 42, speed: 56, arm: 41, fielding: 34, errorResistance: 34, velocity: 0, control: 0, stamina: 20, stuff: 0,
      clutch: 34, vsLHP: 33, grit: 35, stealing: 10, running: 24, throwing: 35, recovery: 28, wRISP: 34, vsLefty: 31, poise: 34, heater: 0, agile: 26,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Ethan", lastName: "Ball", position: "SS", eligibility: "FR", homeState: "VA", hometown: "Virginia Beach", jerseyNumber: 1,
      hitForAvg: 64, power: 96, speed: 79, arm: 66, fielding: 60, errorResistance: 54, velocity: 0, control: 0, stamina: 33, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 40, running: 60, throwing: 68, recovery: 42, wRISP: 50, vsLefty: 47, poise: 50, heater: 0, agile: 64,
      abilities: ["Defensive Artisan"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Willie", lastName: "Hurt", position: "3B", eligibility: "FR", homeState: "VA", hometown: "Woodbridge", jerseyNumber: 16,
      hitForAvg: 33, power: 26, speed: 46, arm: 33, fielding: 25, errorResistance: 24, velocity: 0, control: 0, stamina: 17, stuff: 0,
      clutch: 22, vsLHP: 19, grit: 23, stealing: 14, running: 25, throwing: 30, recovery: 18, wRISP: 20, vsLefty: 18, poise: 22, heater: 0, agile: 27,
      abilities: ["Opposite Field Hitter", "Home Defense"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Eduardo", lastName: "Malinowski", position: "3B", eligibility: "SO", homeState: "VA", hometown: "Virginia Beach", jerseyNumber: 6,
      hitForAvg: 51, power: 50, speed: 48, arm: 49, fielding: 45, errorResistance: 45, velocity: 0, control: 0, stamina: 30, stuff: 0,
      clutch: 45, vsLHP: 45, grit: 48, stealing: 21, running: 37, throwing: 51, recovery: 39, wRISP: 45, vsLefty: 42, poise: 45, heater: 0, agile: 41,
      abilities: ["Pinch Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Cole", lastName: "Cardwell", position: "2B", eligibility: "SR", homeState: "VA", hometown: "Charlottesville", jerseyNumber: 14,
      hitForAvg: 38, power: 32, speed: 53, arm: 33, fielding: 38, errorResistance: 36, velocity: 0, control: 0, stamina: 21, stuff: 0,
      clutch: 33, vsLHP: 32, grit: 34, stealing: 23, running: 33, throwing: 34, recovery: 29, wRISP: 33, vsLefty: 31, poise: 33, heater: 0, agile: 34,
      abilities: ["Chance Maker"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Nick", lastName: "Rivero", position: "1B", eligibility: "JR", homeState: "VA", hometown: "Fairfax", jerseyNumber: 15,
      hitForAvg: 33, power: 33, speed: 47, arm: 33, fielding: 25, errorResistance: 24, velocity: 0, control: 0, stamina: 17, stuff: 0,
      clutch: 25, vsLHP: 23, grit: 27, stealing: 7, running: 18, throwing: 27, recovery: 21, wRISP: 25, vsLefty: 23, poise: 25, heater: 0, agile: 20,
      abilities: ["Ace Killer"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Carson", lastName: "DeMartini", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Danville", jerseyNumber: 7,
      hitForAvg: 37, power: 34, speed: 44, arm: 34, fielding: 34, errorResistance: 33, velocity: 0, control: 0, stamina: 19, stuff: 0,
      clutch: 33, vsLHP: 32, grit: 34, stealing: 23, running: 33, throwing: 36, recovery: 28, wRISP: 33, vsLefty: 31, poise: 33, heater: 0, agile: 33,
      abilities: ["High-Speed Laser"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Gavin", lastName: "Cross", position: "OF", eligibility: "SR", homeState: "VA", hometown: "Bristol", jerseyNumber: 9,
      hitForAvg: 35, power: 34, speed: 42, arm: 32, fielding: 32, errorResistance: 31, velocity: 0, control: 0, stamina: 19, stuff: 0,
      clutch: 31, vsLHP: 30, grit: 32, stealing: 20, running: 29, throwing: 33, recovery: 26, wRISP: 31, vsLefty: 29, poise: 31, heater: 0, agile: 30,
      abilities: ["Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Ben", lastName: "Watson", position: "OF", eligibility: "SO", homeState: "VA", hometown: "Fredericksburg", jerseyNumber: 22,
      hitForAvg: 46, power: 42, speed: 52, arm: 45, fielding: 44, errorResistance: 43, velocity: 0, control: 0, stamina: 26, stuff: 0,
      clutch: 41, vsLHP: 39, grit: 43, stealing: 30, running: 44, throwing: 48, recovery: 37, wRISP: 40, vsLefty: 38, poise: 41, heater: 0, agile: 45,
      abilities: ["Express Baserunning"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Tyler", lastName: "Johnson", position: "OF", eligibility: "JR", homeState: "VA", hometown: "Danville", jerseyNumber: 20,
      hitForAvg: 32, power: 32, speed: 47, arm: 26, fielding: 25, errorResistance: 24, velocity: 0, control: 0, stamina: 16, stuff: 0,
      clutch: 23, vsLHP: 21, grit: 24, stealing: 16, running: 24, throwing: 27, recovery: 20, wRISP: 22, vsLefty: 21, poise: 23, heater: 0, agile: 25,
      abilities: ["Defensive Artisan"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Drew", lastName: "Shelton", position: "OF", eligibility: "SR", homeState: "VA", hometown: "Manassas", jerseyNumber: 11,
      hitForAvg: 74, power: 65, speed: 77, arm: 71, fielding: 71, errorResistance: 67, velocity: 0, control: 0, stamina: 42, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 67, stealing: 38, running: 62, throwing: 73, recovery: 56, wRISP: 65, vsLefty: 61, poise: 66, heater: 0, agile: 65,
      abilities: ["Emergency Strength", "Contact Hitter", "Double Play"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Jack", lastName: "Hurley", position: "OF", eligibility: "JR", homeState: "VA", hometown: "Herndon", jerseyNumber: 8,
      hitForAvg: 39, power: 38, speed: 48, arm: 38, fielding: 38, errorResistance: 34, velocity: 0, control: 0, stamina: 23, stuff: 0,
      clutch: 34, vsLHP: 33, grit: 38, stealing: 20, running: 33, throwing: 42, recovery: 31, wRISP: 33, vsLefty: 31, poise: 34, heater: 0, agile: 34,
      abilities: ["Insurer"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
  ],

  "Wake Forest": [
    // PITCHERS (10)
    { firstName: "Blake", lastName: "Morningstar", position: "P", eligibility: "JR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 35,
      hitForAvg: 22, power: 18, speed: 44, arm: 89, fielding: 54, errorResistance: 72, velocity: 87, control: 81, stamina: 85, stuff: 84,
      clutch: 98, vsLHP: 92, grit: 99, stealing: 22, running: 52, throwing: 99, recovery: 76, wRISP: 78, vsLefty: 78, poise: 81, heater: 89, agile: 65,
      abilities: ["Star of Victory", "Strong Starter", "Intimidator", "Heavy Ball", "Winner's Luck", "Gyroball", "Quick Hands"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...pitchMix(1, [1, 6, 4, 1, 0, 0, 0]) },
    { firstName: "Chris", lastName: "Levonas", position: "P", eligibility: "SO", homeState: "NC", hometown: "Charlotte", jerseyNumber: 29,
      hitForAvg: 20, power: 15, speed: 38, arm: 58, fielding: 35, errorResistance: 47, velocity: 63, control: 53, stamina: 54, stuff: 53,
      clutch: 63, vsLHP: 61, grit: 64, stealing: 14, running: 39, throwing: 72, recovery: 47, wRISP: 47, vsLefty: 48, poise: 49, heater: 58, agile: 47,
      abilities: ["Strong Starter", "Sharpness", "Full Throttle"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Matthew", lastName: "Dallas", position: "P", eligibility: "JR", homeState: "NC", hometown: "Greensboro", jerseyNumber: 37,
      hitForAvg: 16, power: 13, speed: 29, arm: 44, fielding: 27, errorResistance: 39, velocity: 46, control: 43, stamina: 43, stuff: 42,
      clutch: 51, vsLHP: 50, grit: 53, stealing: 11, running: 29, throwing: 58, recovery: 38, wRISP: 38, vsLefty: 39, poise: 41, heater: 44, agile: 35,
      abilities: ["Sharpness", "Wild Fastball"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Cameron", lastName: "Bagwell", position: "P", eligibility: "SO", homeState: "NC", hometown: "Wilmington", jerseyNumber: 40,
      hitForAvg: 21, power: 17, speed: 37, arm: 56, fielding: 34, errorResistance: 48, velocity: 61, control: 56, stamina: 54, stuff: 53,
      clutch: 65, vsLHP: 63, grit: 68, stealing: 15, running: 38, throwing: 73, recovery: 47, wRISP: 49, vsLefty: 49, poise: 51, heater: 56, agile: 45,
      abilities: ["Guts", "Showtime"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [1, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Troy", lastName: "Dressler", position: "P", eligibility: "JR", homeState: "NC", hometown: "Durham", jerseyNumber: 41,
      hitForAvg: 11, power: 9, speed: 26, arm: 28, fielding: 18, errorResistance: 29, velocity: 28, control: 34, stamina: 26, stuff: 26,
      clutch: 36, vsLHP: 35, grit: 38, stealing: 9, running: 22, throwing: 42, recovery: 24, wRISP: 24, vsLefty: 24, poise: 26, heater: 28, agile: 26,
      abilities: ["Fireman"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Will", lastName: "Ray", position: "P", eligibility: "SR", homeState: "NC", hometown: "Winston-Salem", jerseyNumber: 44,
      hitForAvg: 15, power: 12, speed: 27, arm: 38, fielding: 24, errorResistance: 35, velocity: 43, control: 37, stamina: 37, stuff: 36,
      clutch: 46, vsLHP: 44, grit: 48, stealing: 9, running: 25, throwing: 49, recovery: 33, wRISP: 33, vsLefty: 33, poise: 36, heater: 38, agile: 30,
      abilities: ["Guts", "Tunneling"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 5, 1, 0, 3, 0]) },
    { firstName: "Josh", lastName: "Hartle", position: "P", eligibility: "JR", homeState: "NC", hometown: "High Point", jerseyNumber: 31,
      hitForAvg: 9, power: 7, speed: 24, arm: 21, fielding: 15, errorResistance: 24, velocity: 32, control: 21, stamina: 19, stuff: 24,
      clutch: 28, vsLHP: 28, grit: 30, stealing: 7, running: 17, throwing: 33, recovery: 17, wRISP: 17, vsLefty: 17, poise: 19, heater: 21, agile: 21,
      abilities: ["High Spin Gyroball"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 4, 0, 3, 0, 0]) },
    { firstName: "Teddy", lastName: "McGraw", position: "P", eligibility: "SO", homeState: "NC", hometown: "Asheville", jerseyNumber: 46,
      hitForAvg: 12, power: 10, speed: 32, arm: 30, fielding: 19, errorResistance: 32, velocity: 42, control: 28, stamina: 25, stuff: 31,
      clutch: 36, vsLHP: 35, grit: 39, stealing: 10, running: 27, throwing: 43, recovery: 23, wRISP: 23, vsLefty: 23, poise: 24, heater: 30, agile: 31,
      abilities: ["Halting Quickness", "Cowardly"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Brennecke", position: "P", eligibility: "FR", homeState: "NC", hometown: "Cary", jerseyNumber: 48,
      hitForAvg: 8, power: 6, speed: 24, arm: 25, fielding: 13, errorResistance: 22, velocity: 33, control: 19, stamina: 19, stuff: 23,
      clutch: 24, vsLHP: 23, grit: 26, stealing: 8, running: 22, throwing: 37, recovery: 15, wRISP: 14, vsLefty: 16, poise: 15, heater: 25, agile: 26,
      abilities: ["Release"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 6, 3, 1, 0, 0, 0]) },
    { firstName: "Brandon", lastName: "Reitz", position: "P", eligibility: "FR", homeState: "NC", hometown: "Apex", jerseyNumber: 49,
      hitForAvg: 9, power: 7, speed: 26, arm: 24, fielding: 13, errorResistance: 24, velocity: 35, control: 17, stamina: 15, stuff: 25,
      clutch: 24, vsLHP: 24, grit: 26, stealing: 9, running: 22, throwing: 38, recovery: 14, wRISP: 14, vsLefty: 15, poise: 14, heater: 24, agile: 26,
      abilities: ["Poker Face", "Explosive Fastball"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Jimmy", lastName: "Keenan", position: "C", eligibility: "SR", homeState: "NJ", hometown: "Toms River", jerseyNumber: 12,
      hitForAvg: 37, power: 35, speed: 26, arm: 36, fielding: 34, errorResistance: 34, velocity: 0, control: 0, stamina: 22, stuff: 0,
      clutch: 34, vsLHP: 32, grit: 36, stealing: 10, running: 19, throwing: 38, recovery: 28, wRISP: 34, vsLefty: 31, poise: 35, heater: 0, agile: 23,
      abilities: ["Consigliere"], potential: "B+", catcherAbility: 35,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Davis", lastName: "Sharpe", position: "C", eligibility: "FR", homeState: "NC", hometown: "Pinehurst", jerseyNumber: 24,
      hitForAvg: 37, power: 32, speed: 32, arm: 43, fielding: 38, errorResistance: 33, velocity: 0, control: 0, stamina: 23, stuff: 0,
      clutch: 30, vsLHP: 27, grit: 31, stealing: 9, running: 23, throwing: 41, recovery: 27, wRISP: 29, vsLefty: 26, poise: 30, heater: 0, agile: 26,
      abilities: ["Multi-Hit", "Slap Happy", "Contact Hitter"], potential: "B+", catcherAbility: 40,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Kade", lastName: "Lewis", position: "1B", eligibility: "JR", homeState: "NC", hometown: "Davidson", jerseyNumber: 23,
      hitForAvg: 43, power: 48, speed: 42, arm: 35, fielding: 36, errorResistance: 35, velocity: 0, control: 0, stamina: 22, stuff: 0,
      clutch: 41, vsLHP: 38, grit: 42, stealing: 10, running: 24, throwing: 36, recovery: 32, wRISP: 42, vsLefty: 36, poise: 39, heater: 0, agile: 28,
      abilities: ["Power Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...noPitches },
    { firstName: "Austin", lastName: "Hawke", position: "2B", eligibility: "SR", homeState: "NC", hometown: "Concord", jerseyNumber: 8,
      hitForAvg: 57, power: 45, speed: 67, arm: 50, fielding: 55, errorResistance: 53, velocity: 0, control: 0, stamina: 31, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 53, stealing: 33, running: 47, throwing: 52, recovery: 43, wRISP: 50, vsLefty: 47, poise: 52, heater: 0, agile: 50,
      abilities: ["Chance Maker"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Dalton", lastName: "Wentz", position: "SS", eligibility: "JR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 3,
      hitForAvg: 67, power: 99, speed: 84, arm: 68, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 37, stuff: 0,
      clutch: 63, vsLHP: 58, grit: 64, stealing: 41, running: 59, throwing: 70, recovery: 51, wRISP: 59, vsLefty: 57, poise: 63, heater: 0, agile: 64,
      abilities: ["Late Night Hero", "Contact Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Blake", lastName: "Schaaf", position: "3B", eligibility: "JR", homeState: "DC", hometown: "Washington", jerseyNumber: 14,
      hitForAvg: 56, power: 44, speed: 50, arm: 47, fielding: 45, errorResistance: 44, velocity: 0, control: 0, stamina: 27, stuff: 0,
      clutch: 47, vsLHP: 44, grit: 48, stealing: 19, running: 35, throwing: 48, recovery: 38, wRISP: 48, vsLefty: 42, poise: 47, heater: 0, agile: 38,
      abilities: ["Contact Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Tyler", lastName: "Figueroa", position: "2B", eligibility: "JR", homeState: "FL", hometown: "Orlando", jerseyNumber: 6,
      hitForAvg: 35, power: 26, speed: 56, arm: 27, fielding: 35, errorResistance: 27, velocity: 0, control: 0, stamina: 16, stuff: 0,
      clutch: 26, vsLHP: 24, grit: 27, stealing: 16, running: 26, throwing: 28, recovery: 22, wRISP: 26, vsLefty: 23, poise: 26, heater: 0, agile: 27,
      abilities: ["Consigliere", "Magician"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "JD", lastName: "Stein", position: "SS", eligibility: "FR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 2,
      hitForAvg: 40, power: 33, speed: 51, arm: 41, fielding: 37, errorResistance: 35, velocity: 0, control: 0, stamina: 22, stuff: 0,
      clutch: 32, vsLHP: 31, grit: 35, stealing: 25, running: 39, throwing: 41, recovery: 28, wRISP: 32, vsLefty: 29, poise: 32, heater: 0, agile: 41,
      abilities: ["Defensive Artisan"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Ryan", lastName: "Caveness", position: "1B", eligibility: "FR", homeState: "NC", hometown: "Mooresville", jerseyNumber: 18,
      hitForAvg: 34, power: 34, speed: 47, arm: 34, fielding: 28, errorResistance: 26, velocity: 0, control: 0, stamina: 19, stuff: 0,
      clutch: 24, vsLHP: 21, grit: 25, stealing: 8, running: 21, throwing: 31, recovery: 20, wRISP: 24, vsLefty: 20, poise: 24, heater: 0, agile: 22,
      abilities: ["vs. Fastballs", "Final Hit"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Javar", lastName: "Williams", position: "OF", eligibility: "JR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 7,
      hitForAvg: 46, power: 41, speed: 77, arm: 43, fielding: 43, errorResistance: 41, velocity: 0, control: 0, stamina: 25, stuff: 0,
      clutch: 41, vsLHP: 39, grit: 43, stealing: 31, running: 41, throwing: 44, recovery: 36, wRISP: 40, vsLefty: 38, poise: 41, heater: 0, agile: 43,
      abilities: ["Express Baserunning"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Luke", lastName: "Costello", position: "OF", eligibility: "JR", homeState: "NC", hometown: "Matthews", jerseyNumber: 11,
      hitForAvg: 64, power: 88, speed: 69, arm: 60, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 88, vsLHP: 54, grit: 60, stealing: 37, running: 56, throwing: 62, recovery: 47, wRISP: 56, vsLefty: 51, poise: 58, heater: 0, agile: 58,
      abilities: ["Error Prone"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Boston", lastName: "Torres", position: "OF", eligibility: "JR", homeState: "VA", hometown: "Lexington", jerseyNumber: 9,
      hitForAvg: 41, power: 37, speed: 45, arm: 34, fielding: 34, errorResistance: 32, velocity: 0, control: 0, stamina: 20, stuff: 0,
      clutch: 35, vsLHP: 34, grit: 36, stealing: 18, running: 29, throwing: 35, recovery: 29, wRISP: 36, vsLefty: 32, poise: 34, heater: 0, agile: 31,
      abilities: ["Power Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Jay", lastName: "Miller", position: "OF", eligibility: "JR", homeState: "SC", hometown: "Greenville", jerseyNumber: 20,
      hitForAvg: 38, power: 35, speed: 48, arm: 36, fielding: 36, errorResistance: 36, velocity: 0, control: 0, stamina: 22, stuff: 0,
      clutch: 35, vsLHP: 32, grit: 36, stealing: 22, running: 35, throwing: 37, recovery: 29, wRISP: 34, vsLefty: 31, poise: 35, heater: 0, agile: 36,
      abilities: ["High Ball Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Travis", lastName: "Driscoll", position: "OF", eligibility: "SO", homeState: "NC", hometown: "Chapel Hill", jerseyNumber: 16,
      hitForAvg: 40, power: 34, speed: 58, arm: 40, fielding: 34, errorResistance: 33, velocity: 0, control: 0, stamina: 21, stuff: 0,
      clutch: 32, vsLHP: 29, grit: 33, stealing: 21, running: 33, throwing: 36, recovery: 27, wRISP: 30, vsLefty: 28, poise: 32, heater: 0, agile: 34,
      abilities: ["Slap Happy", "Timely Whiff"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Parker", lastName: "Thomas", position: "OF", eligibility: "SO", homeState: "SC", hometown: "Greenville", jerseyNumber: 19,
      hitForAvg: 34, power: 30, speed: 48, arm: 32, fielding: 30, errorResistance: 30, velocity: 0, control: 0, stamina: 20, stuff: 0,
      clutch: 28, vsLHP: 25, grit: 29, stealing: 19, running: 30, throwing: 31, recovery: 24, wRISP: 27, vsLefty: 24, poise: 28, heater: 0, agile: 30,
      abilities: ["Shock Commander"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
  ],

  "Boston College": [
      // 35-16/17-10 ACC, D1B #20, Todd Interdonato Yr 3, program-record 17 ACC W. NCAA record 8 SB in inning vs Duke.
      // PITCHERS (10) — 1-8 pitch scale
      // AJ Colarusso — Friday SR RHP, "heart and soul", 5W (6IP/7K vs Clemson), 3.40 over last 42.1 IP — TEAM ELITE STUFF
      { firstName: "AJ", lastName: "Colarusso", position: "P", eligibility: "SR", homeState: "MA", hometown: "Braintree", jerseyNumber: 34,
        hitForAvg: 20, power: 15, speed: 43, arm: 84, fielding: 53, errorResistance: 69, velocity: 89, control: 84, stamina: 89, stuff: 91,
        clutch: 99, vsLHP: 98, grit: 99, stealing: 15, running: 47, throwing: 99, recovery: 73, wRISP: 81, vsLefty: 84, poise: 84, heater: 89, agile: 56,
        abilities: ["Star of Victory", "Strong Starter", "Intimidator", "Heavy Ball", "Winner's Luck", "Pace", "Straddle"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 7, 5, 1, 0, 0, 0]) },
      // Brady Miller — Saturday LHP SO, 47 K in 45.1 IP, 2.03 ERA over last 40 IP, 6'5"
      { firstName: "Brady", lastName: "Miller", position: "P", eligibility: "SO", homeState: "MA", hometown: "Harwich", jerseyNumber: 27,
        hitForAvg: 13, power: 10, speed: 29, arm: 56, fielding: 32, errorResistance: 43, velocity: 56, control: 56, stamina: 56, stuff: 54,
        clutch: 71, vsLHP: 73, grit: 64, stealing: 7, running: 29, throwing: 68, recovery: 47, wRISP: 52, vsLefty: 59, poise: 56, heater: 56, agile: 38,
        abilities: ["Strong Starter", "Fireman", "Doctor K"], potential: "A", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [6, 0, 5, 1, 0, 0, 0]) },
      // Drew Grumbles — Sunday RHP JR (Johns Hopkins transfer), 2.66 ERA / 103 K in 91.1 IP, D3 COY 2025
      { firstName: "Drew", lastName: "Grumbles", position: "P", eligibility: "JR", homeState: "AR", hometown: "Little Rock", jerseyNumber: 24,
        hitForAvg: 10, power: 8, speed: 25, arm: 45, fielding: 27, errorResistance: 36, velocity: 46, control: 49, stamina: 45, stuff: 43,
        clutch: 53, vsLHP: 49, grit: 53, stealing: 6, running: 24, throwing: 55, recovery: 38, wRISP: 38, vsLefty: 38, poise: 42, heater: 45, agile: 33,
        abilities: ["Strong Starter", "Inside Pitch", "Staredown", "Slugger Killer"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
      // Tyler Mudd — RHP, 11 GS, 3-3, 74 K in 47 IP
      { firstName: "Tyler", lastName: "Mudd", position: "P", eligibility: "JR", homeState: "MA", hometown: "Boston", jerseyNumber: 36,
        hitForAvg: 11, power: 9, speed: 28, arm: 47, fielding: 28, errorResistance: 37, velocity: 50, control: 46, stamina: 47, stuff: 47,
        clutch: 55, vsLHP: 51, grit: 55, stealing: 6, running: 26, throwing: 59, recovery: 38, wRISP: 40, vsLefty: 40, poise: 42, heater: 48, agile: 34,
        abilities: ["Strong Starter", "Doctor K"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 6, 1, 0, 0, 0]) },
      // Sean Hard — RHP NJ (NY Yankees draft pick from HS, command issues but throws hard)
      { firstName: "Sean", lastName: "Hard", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Toms River", jerseyNumber: 31,
        hitForAvg: 9, power: 8, speed: 25, arm: 45, fielding: 25, errorResistance: 35, velocity: 49, control: 34, stamina: 29, stuff: 43,
        clutch: 47, vsLHP: 44, grit: 47, stealing: 7, running: 24, throwing: 56, recovery: 33, wRISP: 34, vsLefty: 35, poise: 36, heater: 48, agile: 32,
        abilities: ["Explosive Fastball", "Intimidator", "Strikeout", "Gyroball"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 7, 0, 1, 0, 4, 0]) },
      // Gavin Soares — top RP RHP, #6 ACC RP / #34 nation
      { firstName: "Gavin", lastName: "Soares", position: "P", eligibility: "JR", homeState: "MA", hometown: "Fall River", jerseyNumber: 28,
        hitForAvg: 10, power: 9, speed: 29, arm: 50, fielding: 29, errorResistance: 39, velocity: 53, control: 49, stamina: 34, stuff: 49,
        clutch: 66, vsLHP: 62, grit: 62, stealing: 7, running: 27, throwing: 62, recovery: 39, wRISP: 48, vsLefty: 43, poise: 51, heater: 51, agile: 35,
        abilities: ["Fireman", "Doctor K"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...pitchMix(1, [0, 6, 0, 1, 0, 4, 0]) },
      // Cesar Gonzalez — closer (15 saves)
      { firstName: "Cesar", lastName: "Gonzalez", position: "P", eligibility: "SR", homeState: "PR", hometown: "San Juan", jerseyNumber: 39,
        hitForAvg: 14, power: 12, speed: 38, arm: 68, fielding: 39, errorResistance: 52, velocity: 70, control: 65, stamina: 46, stuff: 67,
        clutch: 95, vsLHP: 84, grit: 91, stealing: 10, running: 36, throwing: 86, recovery: 52, wRISP: 69, vsLefty: 65, poise: 74, heater: 69, agile: 47,
        abilities: ["Fireman", "Decisive", "Inside Pitch", "Low Ball"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...pitchMix(1, [0, 7, 0, 1, 0, 4, 0]) },
      // Mason Pelio — JR RHP rotation depth
      { firstName: "Mason", lastName: "Pelio", position: "P", eligibility: "JR", homeState: "MA", hometown: "Needham", jerseyNumber: 29,
        hitForAvg: 10, power: 7, speed: 22, arm: 34, fielding: 20, errorResistance: 29, velocity: 34, control: 31, stamina: 31, stuff: 31,
        clutch: 38, vsLHP: 37, grit: 41, stealing: 7, running: 22, throwing: 43, recovery: 26, wRISP: 26, vsLefty: 29, poise: 29, heater: 34, agile: 26,
        abilities: ["Guts", "Staredown", "Intimidator"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 4, 1, 0, 0, 0]) },
      // Henry Leake — JR RHP RP
      { firstName: "Henry", lastName: "Leake", position: "P", eligibility: "JR", homeState: "NH", hometown: "Concord", jerseyNumber: 44,
        hitForAvg: 9, power: 8, speed: 21, arm: 32, fielding: 21, errorResistance: 31, velocity: 35, control: 31, stamina: 30, stuff: 31,
        clutch: 39, vsLHP: 37, grit: 39, stealing: 7, running: 21, throwing: 42, recovery: 28, wRISP: 28, vsLefty: 30, poise: 31, heater: 34, agile: 26,
        abilities: ["Fireman", "Fighting Spirit", "Sharpness"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
      // Trevor Shea — FR RHP
      { firstName: "Trevor", lastName: "Shea", position: "P", eligibility: "FR", homeState: "MA", hometown: "Scituate", jerseyNumber: 48,
        hitForAvg: 9, power: 7, speed: 25, arm: 27, fielding: 16, errorResistance: 25, velocity: 34, control: 23, stamina: 21, stuff: 25,
        clutch: 27, vsLHP: 25, grit: 28, stealing: 9, running: 25, throwing: 39, recovery: 18, wRISP: 17, vsLefty: 18, poise: 18, heater: 28, agile: 27,
        abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
      // CATCHERS (2)
      // Peter Burns — JR C
      { firstName: "Peter", lastName: "Burns", position: "C", eligibility: "JR", homeState: "MA", hometown: "Marshfield", jerseyNumber: 12,
        hitForAvg: 41, power: 37, speed: 27, arm: 45, fielding: 41, errorResistance: 39, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 38, vsLHP: 35, grit: 41, stealing: 12, running: 24, throwing: 45, recovery: 33, wRISP: 36, vsLefty: 33, poise: 39, heater: 0, agile: 27,
        abilities: ["High-Speed Laser", "Defensive Artisan"], potential: "B+", catcherAbility: 42,
        throwHand: "R", batHand: "S",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Dylan Kearns — FR C
      { firstName: "Dylan", lastName: "Kearns", position: "C", eligibility: "FR", homeState: "MA", hometown: "Hingham", jerseyNumber: 25,
        hitForAvg: 34, power: 30, speed: 31, arm: 40, fielding: 36, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 28, vsLHP: 24, grit: 30, stealing: 9, running: 23, throwing: 38, recovery: 28, wRISP: 26, vsLefty: 24, poise: 28, heater: 0, agile: 24,
        abilities: ["Final Hit", "Flying Start", "Contact Hitter"], potential: "B+", catcherAbility: 36,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // INFIELDERS (7)
      // Ty Mainolfi — 2B JR (Dayton transfer), 6th ACC 2B, 4-5 vs UMass Lowell
      { firstName: "Ty", lastName: "Mainolfi", position: "2B", eligibility: "JR", homeState: "OH", hometown: "Dayton", jerseyNumber: 1,
        hitForAvg: 88, power: 67, speed: 74, arm: 59, fielding: 64, errorResistance: 59, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 80, vsLHP: 74, grit: 80, stealing: 41, running: 55, throwing: 59, recovery: 49, wRISP: 80, vsLefty: 74, poise: 80, heater: 0, agile: 59,
        abilities: ["Contact Hitter", "Express Baserunning", "Chance Maker"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Nick Wang — 1B JR, 15 HRs, 7th ACC 1B
      { firstName: "Nick", lastName: "Wang", position: "1B", eligibility: "JR", homeState: "MA", hometown: "Brookline", jerseyNumber: 2,
        hitForAvg: 69, power: 79, speed: 49, arm: 50, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 62, vsLHP: 57, grit: 62, stealing: 15, running: 32, throwing: 50, recovery: 40, wRISP: 62, vsLefty: 57, poise: 62, heater: 0, agile: 37,
        abilities: ["Artist", "Power Hitter", "Consigliere"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Patrick Roche — 3B SR
      { firstName: "Patrick", lastName: "Roche", position: "3B", eligibility: "SR", homeState: "MA", hometown: "Milton", jerseyNumber: 6,
        hitForAvg: 47, power: 40, speed: 38, arm: 42, fielding: 39, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 42, vsLHP: 39, grit: 42, stealing: 16, running: 29, throwing: 42, recovery: 33, wRISP: 42, vsLefty: 37, poise: 42, heater: 0, agile: 33,
        abilities: ["Contact Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Gunnar Johnson — INF, clutch 2-out RBI single vs Clemson
      { firstName: "Gunnar", lastName: "Johnson", position: "3B", eligibility: "JR", homeState: "MA", hometown: "Boston", jerseyNumber: 8,
        hitForAvg: 46, power: 41, speed: 40, arm: 39, fielding: 37, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 51, vsLHP: 39, grit: 44, stealing: 18, running: 29, throwing: 39, recovery: 30, wRISP: 51, vsLefty: 39, poise: 44, heater: 0, agile: 32,
        abilities: ["Consigliere"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Eddie Park — SS SO (moved from 2B due to Mainolfi)
      { firstName: "Eddie", lastName: "Park", position: "SS", eligibility: "FR", homeState: "MA", hometown: "Cambridge", jerseyNumber: 14,
        hitForAvg: 41, power: 33, speed: 53, arm: 39, fielding: 40, errorResistance: 39, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 36, vsLHP: 33, grit: 37, stealing: 24, running: 36, throwing: 40, recovery: 31, wRISP: 34, vsLefty: 31, poise: 36, heater: 0, agile: 39,
        abilities: ["Express Baserunning"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Matt Kemp — 3B FR
      { firstName: "Matt", lastName: "Kemp", position: "3B", eligibility: "FR", homeState: "NY", hometown: "White Plains", jerseyNumber: 4,
        hitForAvg: 37, power: 31, speed: 50, arm: 37, fielding: 28, errorResistance: 27, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 24, vsLHP: 21, grit: 27, stealing: 16, running: 28, throwing: 34, recovery: 23, wRISP: 23, vsLefty: 21, poise: 24, heater: 0, agile: 33,
        abilities: ["Consigliere"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Chris Donovan — SS FR
      { firstName: "Chris", lastName: "Donovan", position: "SS", eligibility: "FR", homeState: "MA", hometown: "Quincy", jerseyNumber: 18,
        hitForAvg: 30, power: 27, speed: 57, arm: 35, fielding: 35, errorResistance: 28, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 23, vsLHP: 21, grit: 24, stealing: 18, running: 31, throwing: 34, recovery: 23, wRISP: 23, vsLefty: 18, poise: 23, heater: 0, agile: 34,
        abilities: ["Express Baserunning", "Contact Hitter", "Push"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // OUTFIELDERS (6)
      // Kyle Wolff — OF, 4 HR in 4 consecutive games (400-foot blast vs Clemson) — TEAM ELITE POWER
      { firstName: "Kyle", lastName: "Wolff", position: "OF", eligibility: "JR", homeState: "MA", hometown: "Newton", jerseyNumber: 5,
        hitForAvg: 80, power: 83, speed: 61, arm: 55, fielding: 52, errorResistance: 49, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 78, vsLHP: 74, grit: 78, stealing: 23, running: 44, throwing: 55, recovery: 43, wRISP: 78, vsLefty: 74, poise: 78, heater: 0, agile: 49,
        abilities: ["Artist", "Power Hitter", "Consigliere"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Julio Solier — OF, multi-hit vs Clemson
      { firstName: "Julio", lastName: "Solier", position: "OF", eligibility: "JR", homeState: "MA", hometown: "Lawrence", jerseyNumber: 10,
        hitForAvg: 44, power: 37, speed: 57, arm: 36, fielding: 35, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 36, vsLHP: 35, grit: 38, stealing: 26, running: 34, throwing: 36, recovery: 28, wRISP: 36, vsLefty: 34, poise: 36, heater: 0, agile: 36,
        abilities: ["Express Baserunning", "Contact Hitter"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Jack Cunningham — OF JR
      { firstName: "Jack", lastName: "Cunningham", position: "OF", eligibility: "JR", homeState: "MA", hometown: "Wellesley", jerseyNumber: 7,
        hitForAvg: 36, power: 32, speed: 41, arm: 33, fielding: 33, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 31, vsLHP: 29, grit: 33, stealing: 20, running: 29, throwing: 33, recovery: 26, wRISP: 30, vsLefty: 29, poise: 31, heater: 0, agile: 30,
        abilities: ["Consigliere"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Drew Bowser — OF SO
      { firstName: "Drew", lastName: "Bowser", position: "OF", eligibility: "SO", homeState: "MA", hometown: "Plymouth", jerseyNumber: 9,
        hitForAvg: 38, power: 34, speed: 41, arm: 37, fielding: 35, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 34, vsLHP: 31, grit: 34, stealing: 21, running: 34, throwing: 38, recovery: 28, wRISP: 32, vsLefty: 31, poise: 34, heater: 0, agile: 34,
        abilities: ["Express Baserunning"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Kody Huff — OF SR
      { firstName: "Kody", lastName: "Huff", position: "OF", eligibility: "SR", homeState: "CT", hometown: "Stamford", jerseyNumber: 11,
        hitForAvg: 41, power: 38, speed: 46, arm: 37, fielding: 37, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 35, vsLHP: 32, grit: 37, stealing: 20, running: 32, throwing: 38, recovery: 31, wRISP: 34, vsLefty: 32, poise: 35, heater: 0, agile: 34,
        abilities: ["Pull Hit"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Brett Barrera — OF SR
      { firstName: "Brett", lastName: "Barrera", position: "OF", eligibility: "SR", homeState: "MA", hometown: "Andover", jerseyNumber: 20,
        hitForAvg: 39, power: 36, speed: 46, arm: 36, fielding: 36, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 33, vsLHP: 32, grit: 33, stealing: 17, running: 30, throwing: 36, recovery: 29, wRISP: 32, vsLefty: 29, poise: 33, heater: 0, agile: 32,
        abilities: ["Trickster", "Opposite Field Hitter", "Contact Hitter"], potential: "B", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
    ],
};
