import { RealPlayer } from "./realRosters";

function pitchMix(primary: number, secondary: number[]): { pitchFB: number; pitch2S: number; pitchSL: number; pitchCB: number; pitchCH: number; pitchCT: number; pitchSNK: number; pitchSPL: number } {
  return {
    pitchFB: primary,
    pitch2S: secondary[0] || 0,
    pitchSL: secondary[1] || 0,
    pitchCB: secondary[2] || 0,
    pitchCH: secondary[3] || 0,
    pitchCT: secondary[4] || 0,
    pitchSNK: secondary[5] || 0,
    pitchSPL: secondary[6] || 0,
  };
}

const noPitches = { pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0 };

export const ACC_BATCH1_ROSTERS: Record<string, RealPlayer[]> = {
  "Clemson": [
    // PITCHERS (8)
    { firstName: "Aidan", lastName: "Knaak", position: "P", eligibility: "SO", homeState: "FL", hometown: "Fort Myers", jerseyNumber: 34,
      hitForAvg: 25, power: 20, speed: 45, arm: 82, fielding: 48, errorResistance: 50, velocity: 84, control: 76, stamina: 78, stuff: 82,
      clutch: 72, vsLHP: 68, grit: 75, stealing: 18, running: 40, throwing: 80, recovery: 68, wRISP: 70, vsLefty: 72, poise: 74, heater: 82, agile: 50,
      abilities: ["Explosive Fastball", "Strong Starter"], potential: "A+", catcherAbility: null,
      ...pitchMix(1, [1, 6, 4, 5, 0, 0, 0]) },
    { firstName: "Drew", lastName: "Titsworth", position: "P", eligibility: "SO", homeState: "MI", hometown: "Frankenmuth", jerseyNumber: 29,
      hitForAvg: 22, power: 18, speed: 42, arm: 76, fielding: 46, errorResistance: 48, velocity: 78, control: 70, stamina: 72, stuff: 74,
      clutch: 64, vsLHP: 62, grit: 68, stealing: 15, running: 38, throwing: 74, recovery: 64, wRISP: 62, vsLefty: 66, poise: 66, heater: 76, agile: 46,
      abilities: ["Heavy Ball"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Ethan", lastName: "Darden", position: "P", eligibility: "JR", homeState: "SC", hometown: "Rock Hill", jerseyNumber: 44,
      hitForAvg: 20, power: 16, speed: 40, arm: 74, fielding: 50, errorResistance: 52, velocity: 74, control: 72, stamina: 70, stuff: 72,
      clutch: 66, vsLHP: 64, grit: 70, stealing: 14, running: 36, throwing: 72, recovery: 66, wRISP: 64, vsLefty: 68, poise: 70, heater: 70, agile: 44,
      abilities: ["Crossfire"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 5, 0, 0, 0]) },
    { firstName: "Lucas", lastName: "Mahlstedt", position: "P", eligibility: "SR", homeState: "FL", hometown: "Ormond Beach", jerseyNumber: 38,
      hitForAvg: 22, power: 18, speed: 38, arm: 72, fielding: 48, errorResistance: 52, velocity: 76, control: 74, stamina: 68, stuff: 70,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 12, running: 34, throwing: 70, recovery: 70, wRISP: 68, vsLefty: 70, poise: 74, heater: 72, agile: 42,
      abilities: ["Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 5, 3, 0, 0]) },
    { firstName: "Reed", lastName: "Garris", position: "P", eligibility: "SR", homeState: "SC", hometown: "Mount Pleasant", jerseyNumber: 41,
      hitForAvg: 20, power: 16, speed: 40, arm: 70, fielding: 46, errorResistance: 50, velocity: 74, control: 70, stamina: 65, stuff: 68,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 14, running: 36, throwing: 68, recovery: 66, wRISP: 66, vsLefty: 66, poise: 72, heater: 70, agile: 44,
      abilities: ["Fireman"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 0, 3, 0, 0]) },
    { firstName: "Joe", lastName: "Allen", position: "P", eligibility: "JR", homeState: "NH", hometown: "Hampton Falls", jerseyNumber: 27,
      hitForAvg: 18, power: 15, speed: 38, arm: 68, fielding: 44, errorResistance: 48, velocity: 72, control: 68, stamina: 64, stuff: 66,
      clutch: 60, vsLHP: 58, grit: 64, stealing: 12, running: 34, throwing: 66, recovery: 62, wRISP: 58, vsLefty: 62, poise: 64, heater: 68, agile: 42,
      abilities: ["Low Ball"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Casey", lastName: "Tallent", position: "P", eligibility: "JR", homeState: "GA", hometown: "Hartwell", jerseyNumber: 36,
      hitForAvg: 20, power: 16, speed: 42, arm: 66, fielding: 46, errorResistance: 50, velocity: 70, control: 66, stamina: 62, stuff: 64,
      clutch: 58, vsLHP: 56, grit: 62, stealing: 14, running: 38, throwing: 64, recovery: 60, wRISP: 56, vsLefty: 60, poise: 62, heater: 66, agile: 44,
      abilities: [], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 0, 4, 3, 0, 0]) },
    { firstName: "Austin", lastName: "Gordon", position: "P", eligibility: "FR", homeState: "SC", hometown: "Greenville", jerseyNumber: 48,
      hitForAvg: 18, power: 14, speed: 44, arm: 72, fielding: 40, errorResistance: 42, velocity: 76, control: 56, stamina: 52, stuff: 68,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 18, running: 42, throwing: 70, recovery: 48, wRISP: 46, vsLefty: 50, poise: 48, heater: 74, agile: 48,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 6, 3, 4, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Hideki", lastName: "Prather", position: "C", eligibility: "SO", homeState: "CA", hometown: "Oakland", jerseyNumber: 12,
      hitForAvg: 62, power: 55, speed: 42, arm: 70, fielding: 68, errorResistance: 65, velocity: 38, control: 35, stamina: 40, stuff: 32,
      clutch: 65, vsLHP: 60, grit: 68, stealing: 22, running: 40, throwing: 72, recovery: 55, wRISP: 62, vsLefty: 58, poise: 64, heater: 35, agile: 48,
      abilities: ["Iron Wall"], potential: "A-", catcherAbility: 68,
      ...noPitches },
    { firstName: "Steele", lastName: "Burd", position: "C", eligibility: "FR", homeState: "SC", hometown: "Hilton Head Island", jerseyNumber: 25,
      hitForAvg: 45, power: 40, speed: 38, arm: 62, fielding: 55, errorResistance: 50, velocity: 34, control: 32, stamina: 36, stuff: 30,
      clutch: 48, vsLHP: 44, grit: 50, stealing: 16, running: 35, throwing: 60, recovery: 45, wRISP: 46, vsLefty: 42, poise: 46, heater: 32, agile: 40,
      abilities: [], potential: "B+", catcherAbility: 58,
      ...noPitches },
    // INFIELDERS (5)
    { firstName: "Andrew", lastName: "Ciufo", position: "SS", eligibility: "SR", homeState: "NY", hometown: "Medford", jerseyNumber: 6,
      hitForAvg: 68, power: 52, speed: 62, arm: 72, fielding: 74, errorResistance: 72, velocity: 40, control: 36, stamina: 38, stuff: 34,
      clutch: 70, vsLHP: 65, grit: 72, stealing: 48, running: 60, throwing: 74, recovery: 58, wRISP: 68, vsLefty: 64, poise: 68, heater: 36, agile: 68,
      abilities: ["Iron Glove", "Clutch Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Josh", lastName: "Paino", position: "2B", eligibility: "SR", homeState: "CA", hometown: "Temecula", jerseyNumber: 3,
      hitForAvg: 72, power: 48, speed: 58, arm: 60, fielding: 70, errorResistance: 68, velocity: 36, control: 34, stamina: 36, stuff: 32,
      clutch: 68, vsLHP: 66, grit: 70, stealing: 42, running: 56, throwing: 62, recovery: 56, wRISP: 70, vsLefty: 68, poise: 70, heater: 34, agile: 62,
      abilities: ["Contact Master"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jarren", lastName: "Purify", position: "3B", eligibility: "SO", homeState: "MI", hometown: "Detroit", jerseyNumber: 5,
      hitForAvg: 60, power: 65, speed: 50, arm: 66, fielding: 58, errorResistance: 56, velocity: 38, control: 34, stamina: 38, stuff: 32,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 28, running: 48, throwing: 68, recovery: 52, wRISP: 60, vsLefty: 56, poise: 58, heater: 34, agile: 52,
      abilities: ["Gap Power"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Nolan", lastName: "Nawrocki", position: "1B", eligibility: "JR", homeState: "NY", hometown: "Rockville Centre", jerseyNumber: 18,
      hitForAvg: 64, power: 68, speed: 42, arm: 58, fielding: 62, errorResistance: 60, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 66, vsLHP: 62, grit: 66, stealing: 18, running: 40, throwing: 60, recovery: 54, wRISP: 66, vsLefty: 60, poise: 64, heater: 32, agile: 44,
      abilities: ["Power Slugger"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Gavin", lastName: "Abrams", position: "2B", eligibility: "SR", homeState: "FL", hometown: "St Johns", jerseyNumber: 2,
      hitForAvg: 58, power: 44, speed: 60, arm: 58, fielding: 64, errorResistance: 62, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 60, vsLHP: 56, grit: 64, stealing: 44, running: 58, throwing: 60, recovery: 52, wRISP: 58, vsLefty: 54, poise: 62, heater: 32, agile: 60,
      abilities: ["Table Setter"], potential: "B", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (8)
    { firstName: "Cam", lastName: "Cannarella", position: "OF", eligibility: "SR", homeState: "SC", hometown: "Hartsville", jerseyNumber: 1,
      hitForAvg: 74, power: 62, speed: 68, arm: 72, fielding: 70, errorResistance: 68, velocity: 40, control: 36, stamina: 38, stuff: 34,
      clutch: 75, vsLHP: 70, grit: 74, stealing: 52, running: 66, throwing: 74, recovery: 60, wRISP: 72, vsLefty: 68, poise: 72, heater: 36, agile: 70,
      abilities: ["Clutch Hitter", "Spray Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Kier", lastName: "Meredith", position: "OF", eligibility: "SR", homeState: "NC", hometown: "Winston-Salem", jerseyNumber: 4,
      hitForAvg: 66, power: 42, speed: 80, arm: 62, fielding: 68, errorResistance: 66, velocity: 38, control: 34, stamina: 36, stuff: 32,
      clutch: 62, vsLHP: 60, grit: 66, stealing: 72, running: 78, throwing: 64, recovery: 56, wRISP: 60, vsLefty: 58, poise: 64, heater: 34, agile: 76,
      abilities: ["Speed Demon", "Base Burglar"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Dylan", lastName: "Brewer", position: "OF", eligibility: "SR", homeState: "SC", hometown: "Latta", jerseyNumber: 7,
      hitForAvg: 62, power: 55, speed: 72, arm: 66, fielding: 66, errorResistance: 64, velocity: 38, control: 34, stamina: 36, stuff: 32,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 56, running: 70, throwing: 68, recovery: 56, wRISP: 62, vsLefty: 58, poise: 64, heater: 34, agile: 72,
      abilities: ["Speed Demon"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Lleyton", lastName: "Lackey", position: "OF", eligibility: "JR", homeState: "GA", hometown: "Evans", jerseyNumber: 10,
      hitForAvg: 58, power: 50, speed: 60, arm: 64, fielding: 62, errorResistance: 60, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 40, running: 58, throwing: 66, recovery: 52, wRISP: 58, vsLefty: 54, poise: 60, heater: 32, agile: 62,
      abilities: ["Laser Beam"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Dominic", lastName: "Listi", position: "OF", eligibility: "SR", homeState: "IL", hometown: "Crystal Lake", jerseyNumber: 15,
      hitForAvg: 60, power: 56, speed: 52, arm: 62, fielding: 60, errorResistance: 58, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 30, running: 50, throwing: 64, recovery: 52, wRISP: 62, vsLefty: 56, poise: 62, heater: 32, agile: 54,
      abilities: ["Tough Out"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Jack", lastName: "Crighton", position: "OF", eligibility: "JR", homeState: "MI", hometown: "Rochester Hills", jerseyNumber: 8,
      hitForAvg: 56, power: 48, speed: 56, arm: 64, fielding: 60, errorResistance: 58, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 56, vsLHP: 54, grit: 58, stealing: 34, running: 54, throwing: 66, recovery: 50, wRISP: 54, vsLefty: 52, poise: 56, heater: 32, agile: 58,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Tryston", lastName: "McCladdie", position: "OF", eligibility: "SO", homeState: "GA", hometown: "Harlem", jerseyNumber: 22,
      hitForAvg: 52, power: 46, speed: 64, arm: 60, fielding: 56, errorResistance: 54, velocity: 36, control: 32, stamina: 36, stuff: 30,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 42, running: 62, throwing: 62, recovery: 48, wRISP: 52, vsLefty: 48, poise: 52, heater: 32, agile: 64,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Duke": [
    // PITCHERS (9)
    { firstName: "Henry", lastName: "Zatkowski", position: "P", eligibility: "SO", homeState: "MD", hometown: "Bethesda", jerseyNumber: 22,
      hitForAvg: 24, power: 18, speed: 42, arm: 78, fielding: 48, errorResistance: 50, velocity: 78, control: 74, stamina: 72, stuff: 76,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 16, running: 38, throwing: 76, recovery: 66, wRISP: 66, vsLefty: 68, poise: 70, heater: 74, agile: 46,
      abilities: ["Strikeout", "Crossfire"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 5, 6, 4, 0, 0, 0]) },
    { firstName: "Max", lastName: "Stammel", position: "P", eligibility: "SO", homeState: "TX", hometown: "Houston", jerseyNumber: 33,
      hitForAvg: 22, power: 16, speed: 40, arm: 74, fielding: 46, errorResistance: 48, velocity: 76, control: 70, stamina: 70, stuff: 72,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 14, running: 36, throwing: 72, recovery: 62, wRISP: 62, vsLefty: 66, poise: 66, heater: 72, agile: 44,
      abilities: ["Crossfire"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 5, 0, 0, 0]) },
    { firstName: "Cooper", lastName: "Deans", position: "P", eligibility: "JR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 37,
      hitForAvg: 20, power: 16, speed: 38, arm: 72, fielding: 48, errorResistance: 50, velocity: 74, control: 72, stamina: 68, stuff: 70,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 12, running: 34, throwing: 70, recovery: 64, wRISP: 64, vsLefty: 66, poise: 68, heater: 70, agile: 42,
      abilities: ["Strong Starter"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [1, 5, 4, 4, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Leverett", position: "P", eligibility: "SR", homeState: "VA", hometown: "Richmond", jerseyNumber: 19,
      hitForAvg: 22, power: 18, speed: 36, arm: 70, fielding: 46, errorResistance: 50, velocity: 72, control: 74, stamina: 66, stuff: 68,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 10, running: 32, throwing: 68, recovery: 68, wRISP: 68, vsLefty: 70, poise: 72, heater: 68, agile: 40,
      abilities: ["Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 5, 3, 0, 0]) },
    { firstName: "James", lastName: "Talbot", position: "P", eligibility: "JR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 28,
      hitForAvg: 20, power: 15, speed: 40, arm: 68, fielding: 44, errorResistance: 48, velocity: 70, control: 68, stamina: 64, stuff: 66,
      clutch: 60, vsLHP: 58, grit: 62, stealing: 14, running: 36, throwing: 66, recovery: 60, wRISP: 58, vsLefty: 62, poise: 62, heater: 66, agile: 42,
      abilities: ["Low Ball"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 5, 0, 0, 0]) },
    { firstName: "Marcus", lastName: "Chen", position: "P", eligibility: "SO", homeState: "NJ", hometown: "Princeton", jerseyNumber: 45,
      hitForAvg: 18, power: 14, speed: 42, arm: 66, fielding: 42, errorResistance: 46, velocity: 72, control: 62, stamina: 58, stuff: 66,
      clutch: 54, vsLHP: 52, grit: 56, stealing: 16, running: 38, throwing: 64, recovery: 56, wRISP: 52, vsLefty: 56, poise: 56, heater: 68, agile: 44,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 3, 4, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Reeves", position: "P", eligibility: "SR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 31,
      hitForAvg: 20, power: 16, speed: 38, arm: 68, fielding: 46, errorResistance: 50, velocity: 70, control: 70, stamina: 60, stuff: 64,
      clutch: 62, vsLHP: 58, grit: 66, stealing: 12, running: 34, throwing: 66, recovery: 62, wRISP: 60, vsLefty: 62, poise: 66, heater: 66, agile: 40,
      abilities: ["Fireman"], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 0, 5, 0, 3, 0]) },
    { firstName: "Will", lastName: "Patterson", position: "P", eligibility: "FR", homeState: "NC", hometown: "Durham", jerseyNumber: 42,
      hitForAvg: 16, power: 14, speed: 44, arm: 70, fielding: 38, errorResistance: 40, velocity: 74, control: 54, stamina: 50, stuff: 68,
      clutch: 46, vsLHP: 44, grit: 48, stealing: 18, running: 42, throwing: 68, recovery: 46, wRISP: 44, vsLefty: 48, poise: 46, heater: 72, agile: 46,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 3, 0, 0, 0]) },
    { firstName: "Drew", lastName: "Hartman", position: "P", eligibility: "JR", homeState: "PA", hometown: "Philadelphia", jerseyNumber: 35,
      hitForAvg: 18, power: 15, speed: 36, arm: 66, fielding: 44, errorResistance: 48, velocity: 68, control: 66, stamina: 62, stuff: 64,
      clutch: 58, vsLHP: 56, grit: 60, stealing: 10, running: 32, throwing: 64, recovery: 58, wRISP: 56, vsLefty: 60, poise: 60, heater: 64, agile: 40,
      abilities: [], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 0, 3, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Andrew", lastName: "Yu", position: "C", eligibility: "SR", homeState: "TN", hometown: "Nashville", jerseyNumber: 14,
      hitForAvg: 60, power: 52, speed: 40, arm: 72, fielding: 70, errorResistance: 68, velocity: 38, control: 36, stamina: 40, stuff: 32,
      clutch: 66, vsLHP: 62, grit: 70, stealing: 18, running: 38, throwing: 74, recovery: 56, wRISP: 64, vsLefty: 60, poise: 68, heater: 34, agile: 44,
      abilities: ["Bazooka Arm", "The Almanac"], potential: "B+", catcherAbility: 72,
      ...noPitches },
    { firstName: "Jack", lastName: "Brinkley", position: "C", eligibility: "SO", homeState: "NC", hometown: "Cary", jerseyNumber: 24,
      hitForAvg: 44, power: 40, speed: 36, arm: 60, fielding: 56, errorResistance: 52, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 48, vsLHP: 44, grit: 50, stealing: 14, running: 34, throwing: 62, recovery: 44, wRISP: 46, vsLefty: 42, poise: 46, heater: 30, agile: 38,
      abilities: [], potential: "B", catcherAbility: 56,
      ...noPitches },
    // INFIELDERS (5)
    { firstName: "Mike", lastName: "Miller", position: "SS", eligibility: "JR", homeState: "NJ", hometown: "Morristown", jerseyNumber: 2,
      hitForAvg: 64, power: 48, speed: 62, arm: 68, fielding: 72, errorResistance: 70, velocity: 38, control: 34, stamina: 36, stuff: 32,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 46, running: 60, throwing: 70, recovery: 56, wRISP: 64, vsLefty: 60, poise: 66, heater: 34, agile: 64,
      abilities: ["Iron Glove"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Bryce", lastName: "Eldridge", position: "1B", eligibility: "JR", homeState: "VA", hometown: "Arlington", jerseyNumber: 16,
      hitForAvg: 58, power: 62, speed: 44, arm: 56, fielding: 58, errorResistance: 56, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 18, running: 42, throwing: 58, recovery: 50, wRISP: 60, vsLefty: 54, poise: 58, heater: 32, agile: 44,
      abilities: ["Power Slugger"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Kevin", lastName: "Martinez", position: "2B", eligibility: "SR", homeState: "FL", hometown: "Miami", jerseyNumber: 7,
      hitForAvg: 56, power: 42, speed: 56, arm: 58, fielding: 64, errorResistance: 62, velocity: 34, control: 32, stamina: 34, stuff: 28,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 40, running: 54, throwing: 60, recovery: 50, wRISP: 56, vsLefty: 52, poise: 58, heater: 30, agile: 58,
      abilities: ["Table Setter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "David", lastName: "Walsh", position: "3B", eligibility: "JR", homeState: "CT", hometown: "Greenwich", jerseyNumber: 11,
      hitForAvg: 54, power: 52, speed: 48, arm: 62, fielding: 58, errorResistance: 56, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 24, running: 46, throwing: 64, recovery: 48, wRISP: 54, vsLefty: 50, poise: 54, heater: 32, agile: 50,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Chris", lastName: "Fontenot", position: "SS", eligibility: "SO", homeState: "NC", hometown: "Greensboro", jerseyNumber: 9,
      hitForAvg: 50, power: 38, speed: 60, arm: 60, fielding: 62, errorResistance: 58, velocity: 34, control: 32, stamina: 34, stuff: 28,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 42, running: 58, throwing: 62, recovery: 46, wRISP: 48, vsLefty: 46, poise: 50, heater: 30, agile: 62,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "AJ", lastName: "Gracia", position: "OF", eligibility: "JR", homeState: "NJ", hometown: "Woodbridge", jerseyNumber: 1,
      hitForAvg: 76, power: 68, speed: 66, arm: 70, fielding: 72, errorResistance: 70, velocity: 40, control: 36, stamina: 38, stuff: 34,
      clutch: 78, vsLHP: 72, grit: 76, stealing: 48, running: 64, throwing: 72, recovery: 60, wRISP: 76, vsLefty: 70, poise: 74, heater: 36, agile: 68,
      abilities: ["Clutch Hitter", "Power Slugger"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Nate", lastName: "Rodriguez", position: "OF", eligibility: "SR", homeState: "NC", hometown: "Chapel Hill", jerseyNumber: 5,
      hitForAvg: 58, power: 50, speed: 58, arm: 64, fielding: 62, errorResistance: 60, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 38, running: 56, throwing: 66, recovery: 52, wRISP: 58, vsLefty: 54, poise: 60, heater: 32, agile: 60,
      abilities: ["Spray Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Ethan", lastName: "Brooks", position: "OF", eligibility: "JR", homeState: "VA", hometown: "Virginia Beach", jerseyNumber: 8,
      hitForAvg: 54, power: 46, speed: 62, arm: 62, fielding: 60, errorResistance: 58, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 44, running: 60, throwing: 64, recovery: 50, wRISP: 54, vsLefty: 50, poise: 56, heater: 32, agile: 64,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Sam", lastName: "Hwang", position: "OF", eligibility: "SO", homeState: "MD", hometown: "Rockville", jerseyNumber: 17,
      hitForAvg: 50, power: 42, speed: 56, arm: 58, fielding: 56, errorResistance: 54, velocity: 34, control: 32, stamina: 34, stuff: 28,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 36, running: 54, throwing: 60, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 30, agile: 58,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Luke", lastName: "Hammond", position: "OF", eligibility: "FR", homeState: "SC", hometown: "Charleston", jerseyNumber: 21,
      hitForAvg: 44, power: 38, speed: 58, arm: 56, fielding: 50, errorResistance: 48, velocity: 32, control: 30, stamina: 34, stuff: 28,
      clutch: 44, vsLHP: 40, grit: 46, stealing: 36, running: 56, throwing: 58, recovery: 42, wRISP: 42, vsLefty: 38, poise: 42, heater: 28, agile: 58,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Daniel", lastName: "Perkins", position: "OF", eligibility: "JR", homeState: "GA", hometown: "Savannah", jerseyNumber: 13,
      hitForAvg: 52, power: 44, speed: 54, arm: 60, fielding: 58, errorResistance: 56, velocity: 34, control: 32, stamina: 34, stuff: 28,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 32, running: 52, throwing: 62, recovery: 48, wRISP: 52, vsLefty: 48, poise: 54, heater: 30, agile: 56,
      abilities: [], potential: "B-", catcherAbility: null,
      ...noPitches },
  ],

  "Florida State": [
    // PITCHERS (9)
    { firstName: "Wes", lastName: "Mendes", position: "P", eligibility: "SR", homeState: "FL", hometown: "Coral Springs", jerseyNumber: 34,
      hitForAvg: 24, power: 20, speed: 40, arm: 78, fielding: 50, errorResistance: 52, velocity: 80, control: 76, stamina: 76, stuff: 78,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 14, running: 36, throwing: 76, recovery: 70, wRISP: 70, vsLefty: 72, poise: 76, heater: 78, agile: 44,
      abilities: ["Strong Starter", "Guts"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [1, 6, 4, 5, 0, 0, 0]) },
    { firstName: "Connor", lastName: "Hults", position: "P", eligibility: "JR", homeState: "FL", hometown: "Jacksonville", jerseyNumber: 27,
      hitForAvg: 22, power: 18, speed: 42, arm: 76, fielding: 48, errorResistance: 50, velocity: 76, control: 74, stamina: 72, stuff: 74,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 16, running: 38, throwing: 74, recovery: 66, wRISP: 66, vsLefty: 68, poise: 70, heater: 72, agile: 46,
      abilities: ["Crossfire", "Sharpness"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 5, 0, 0, 0]) },
    { firstName: "Joe", lastName: "Charles", position: "P", eligibility: "SO", homeState: "FL", hometown: "Tampa", jerseyNumber: 44,
      hitForAvg: 20, power: 16, speed: 44, arm: 76, fielding: 44, errorResistance: 46, velocity: 80, control: 66, stamina: 64, stuff: 76,
      clutch: 60, vsLHP: 58, grit: 64, stealing: 18, running: 42, throwing: 74, recovery: 58, wRISP: 58, vsLefty: 62, poise: 60, heater: 78, agile: 48,
      abilities: ["Explosive Fastball"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 6, 3, 5, 0, 0, 0]) },
    { firstName: "David", lastName: "Barrett", position: "P", eligibility: "JR", homeState: "FL", hometown: "Orlando", jerseyNumber: 38,
      hitForAvg: 20, power: 16, speed: 40, arm: 72, fielding: 48, errorResistance: 50, velocity: 74, control: 72, stamina: 70, stuff: 70,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 14, running: 36, throwing: 70, recovery: 64, wRISP: 64, vsLefty: 66, poise: 68, heater: 70, agile: 44,
      abilities: ["Heavy Ball"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Keating", position: "P", eligibility: "SR", homeState: "GA", hometown: "Marietta", jerseyNumber: 19,
      hitForAvg: 22, power: 18, speed: 38, arm: 70, fielding: 46, errorResistance: 50, velocity: 72, control: 74, stamina: 66, stuff: 68,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 10, running: 34, throwing: 68, recovery: 68, wRISP: 68, vsLefty: 70, poise: 72, heater: 68, agile: 40,
      abilities: ["Fireman"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 0, 5, 3, 0, 0]) },
    { firstName: "Brandon", lastName: "Neely", position: "P", eligibility: "JR", homeState: "FL", hometown: "Fort Lauderdale", jerseyNumber: 41,
      hitForAvg: 18, power: 15, speed: 40, arm: 68, fielding: 44, errorResistance: 48, velocity: 70, control: 68, stamina: 64, stuff: 66,
      clutch: 60, vsLHP: 58, grit: 62, stealing: 14, running: 36, throwing: 66, recovery: 60, wRISP: 58, vsLefty: 62, poise: 62, heater: 66, agile: 42,
      abilities: ["Groundball Pitcher"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 5, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Pfennigs", position: "P", eligibility: "SO", homeState: "FL", hometown: "Tallahassee", jerseyNumber: 29,
      hitForAvg: 18, power: 14, speed: 42, arm: 66, fielding: 42, errorResistance: 46, velocity: 72, control: 62, stamina: 58, stuff: 66,
      clutch: 54, vsLHP: 52, grit: 56, stealing: 16, running: 40, throwing: 64, recovery: 56, wRISP: 52, vsLefty: 56, poise: 56, heater: 68, agile: 44,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 3, 0, 0, 0]) },
    { firstName: "Cam", lastName: "Leiter", position: "P", eligibility: "FR", homeState: "NJ", hometown: "Toms River", jerseyNumber: 47,
      hitForAvg: 16, power: 14, speed: 44, arm: 70, fielding: 38, errorResistance: 40, velocity: 76, control: 54, stamina: 50, stuff: 68,
      clutch: 46, vsLHP: 44, grit: 48, stealing: 18, running: 42, throwing: 68, recovery: 46, wRISP: 44, vsLefty: 48, poise: 46, heater: 74, agile: 46,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 5, 3, 4, 0, 0, 0]) },
    { firstName: "Colton", lastName: "Vincent", position: "P", eligibility: "SR", homeState: "GA", hometown: "Savannah", jerseyNumber: 36,
      hitForAvg: 20, power: 16, speed: 36, arm: 66, fielding: 46, errorResistance: 50, velocity: 68, control: 68, stamina: 62, stuff: 64,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 10, running: 32, throwing: 64, recovery: 62, wRISP: 60, vsLefty: 62, poise: 64, heater: 64, agile: 38,
      abilities: [], potential: "C+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 0, 3, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Colton", lastName: "Gordon", position: "C", eligibility: "JR", homeState: "FL", hometown: "Pensacola", jerseyNumber: 12,
      hitForAvg: 58, power: 54, speed: 40, arm: 70, fielding: 68, errorResistance: 66, velocity: 38, control: 36, stamina: 40, stuff: 32,
      clutch: 64, vsLHP: 60, grit: 68, stealing: 18, running: 38, throwing: 72, recovery: 54, wRISP: 62, vsLefty: 58, poise: 66, heater: 34, agile: 44,
      abilities: ["Iron Wall"], potential: "B+", catcherAbility: 70,
      ...noPitches },
    { firstName: "Danny", lastName: "Neri", position: "C", eligibility: "SO", homeState: "FL", hometown: "Miami", jerseyNumber: 25,
      hitForAvg: 46, power: 42, speed: 36, arm: 62, fielding: 58, errorResistance: 54, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 14, running: 34, throwing: 64, recovery: 46, wRISP: 48, vsLefty: 44, poise: 48, heater: 30, agile: 38,
      abilities: [], potential: "B", catcherAbility: 60,
      ...noPitches },
    // INFIELDERS (5)
    { firstName: "Alex", lastName: "Lodise", position: "SS", eligibility: "JR", homeState: "FL", hometown: "Fort Myers", jerseyNumber: 1,
      hitForAvg: 80, power: 65, speed: 70, arm: 74, fielding: 78, errorResistance: 76, velocity: 42, control: 38, stamina: 40, stuff: 36,
      clutch: 82, vsLHP: 76, grit: 80, stealing: 56, running: 68, throwing: 76, recovery: 62, wRISP: 80, vsLefty: 74, poise: 78, heater: 38, agile: 72,
      abilities: ["Clutch Hitter", "Contact Master"], potential: "A+", catcherAbility: null,
      ...noPitches },
    { firstName: "Marcus", lastName: "Rivera", position: "2B", eligibility: "SR", homeState: "FL", hometown: "Gainesville", jerseyNumber: 7,
      hitForAvg: 60, power: 44, speed: 58, arm: 58, fielding: 66, errorResistance: 64, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 42, running: 56, throwing: 60, recovery: 52, wRISP: 60, vsLefty: 56, poise: 62, heater: 32, agile: 60,
      abilities: ["Table Setter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Jordan", lastName: "Carrion", position: "3B", eligibility: "JR", homeState: "FL", hometown: "Lakeland", jerseyNumber: 5,
      hitForAvg: 58, power: 56, speed: 50, arm: 64, fielding: 60, errorResistance: 58, velocity: 38, control: 34, stamina: 36, stuff: 32,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 26, running: 48, throwing: 66, recovery: 50, wRISP: 58, vsLefty: 54, poise: 58, heater: 34, agile: 52,
      abilities: ["Gap Power"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Tyler", lastName: "Martin", position: "1B", eligibility: "SR", homeState: "GA", hometown: "Augusta", jerseyNumber: 22,
      hitForAvg: 56, power: 64, speed: 42, arm: 56, fielding: 60, errorResistance: 58, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 16, running: 40, throwing: 58, recovery: 50, wRISP: 60, vsLefty: 54, poise: 58, heater: 32, agile: 42,
      abilities: ["Power Slugger"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Max", lastName: "Williams", position: "SS", eligibility: "FR", homeState: "FL", hometown: "Naples", jerseyNumber: 3,
      hitForAvg: 48, power: 36, speed: 62, arm: 60, fielding: 58, errorResistance: 52, velocity: 34, control: 30, stamina: 34, stuff: 28,
      clutch: 46, vsLHP: 42, grit: 48, stealing: 44, running: 60, throwing: 62, recovery: 42, wRISP: 44, vsLefty: 40, poise: 44, heater: 30, agile: 62,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Nathan", lastName: "Cmeyla", position: "OF", eligibility: "JR", homeState: "FL", hometown: "St. Petersburg", jerseyNumber: 8,
      hitForAvg: 68, power: 58, speed: 64, arm: 68, fielding: 66, errorResistance: 64, velocity: 38, control: 36, stamina: 38, stuff: 32,
      clutch: 70, vsLHP: 66, grit: 70, stealing: 46, running: 62, throwing: 70, recovery: 56, wRISP: 68, vsLefty: 64, poise: 68, heater: 34, agile: 66,
      abilities: ["Clutch Hitter", "Laser Beam"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "James", lastName: "Tibbs", position: "OF", eligibility: "SO", homeState: "GA", hometown: "Alpharetta", jerseyNumber: 10,
      hitForAvg: 62, power: 54, speed: 60, arm: 64, fielding: 62, errorResistance: 60, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 40, running: 58, throwing: 66, recovery: 52, wRISP: 60, vsLefty: 56, poise: 60, heater: 32, agile: 62,
      abilities: ["Spray Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Jaime", lastName: "Ferrer", position: "OF", eligibility: "SR", homeState: "FL", hometown: "Kissimmee", jerseyNumber: 11,
      hitForAvg: 64, power: 60, speed: 56, arm: 66, fielding: 64, errorResistance: 62, velocity: 38, control: 34, stamina: 36, stuff: 32,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 34, running: 54, throwing: 68, recovery: 54, wRISP: 66, vsLefty: 60, poise: 66, heater: 34, agile: 58,
      abilities: ["Power Slugger"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Cam", lastName: "Smith", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Ocala", jerseyNumber: 15,
      hitForAvg: 56, power: 48, speed: 62, arm: 62, fielding: 60, errorResistance: 58, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 44, running: 60, throwing: 64, recovery: 50, wRISP: 54, vsLefty: 50, poise: 56, heater: 32, agile: 64,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Reese", lastName: "Albert", position: "OF", eligibility: "SO", homeState: "FL", hometown: "Daytona Beach", jerseyNumber: 18,
      hitForAvg: 52, power: 44, speed: 58, arm: 60, fielding: 56, errorResistance: 54, velocity: 34, control: 32, stamina: 34, stuff: 28,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 38, running: 56, throwing: 62, recovery: 48, wRISP: 50, vsLefty: 46, poise: 50, heater: 30, agile: 60,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Daniel", lastName: "Cantu", position: "OF", eligibility: "FR", homeState: "FL", hometown: "Hialeah", jerseyNumber: 21,
      hitForAvg: 44, power: 40, speed: 60, arm: 58, fielding: 50, errorResistance: 48, velocity: 32, control: 30, stamina: 34, stuff: 28,
      clutch: 44, vsLHP: 40, grit: 46, stealing: 40, running: 58, throwing: 60, recovery: 42, wRISP: 42, vsLefty: 38, poise: 42, heater: 28, agile: 60,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Georgia Tech": [
    // PITCHERS (9)
    { firstName: "Tate", lastName: "McKee", position: "P", eligibility: "JR", homeState: "GA", hometown: "Roswell", jerseyNumber: 34,
      hitForAvg: 24, power: 20, speed: 42, arm: 78, fielding: 48, errorResistance: 50, velocity: 80, control: 74, stamina: 76, stuff: 78,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 16, running: 38, throwing: 76, recovery: 68, wRISP: 68, vsLefty: 70, poise: 72, heater: 78, agile: 46,
      abilities: ["Strong Starter", "Strikeout"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [1, 6, 4, 5, 0, 0, 0]) },
    { firstName: "Mason", lastName: "Patel", position: "P", eligibility: "JR", homeState: "GA", hometown: "Johns Creek", jerseyNumber: 28,
      hitForAvg: 22, power: 18, speed: 40, arm: 74, fielding: 46, errorResistance: 48, velocity: 78, control: 70, stamina: 70, stuff: 74,
      clutch: 64, vsLHP: 62, grit: 68, stealing: 14, running: 36, throwing: 72, recovery: 64, wRISP: 62, vsLefty: 66, poise: 68, heater: 74, agile: 44,
      abilities: ["Pace"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Dylan", lastName: "Loy", position: "P", eligibility: "JR", homeState: "TN", hometown: "Knoxville", jerseyNumber: 33,
      hitForAvg: 22, power: 16, speed: 42, arm: 76, fielding: 48, errorResistance: 50, velocity: 78, control: 72, stamina: 72, stuff: 76,
      clutch: 66, vsLHP: 64, grit: 70, stealing: 16, running: 38, throwing: 74, recovery: 66, wRISP: 64, vsLefty: 68, poise: 68, heater: 76, agile: 46,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 4, 5, 0, 0, 0]) },
    { firstName: "Carson", lastName: "Ballard", position: "P", eligibility: "JR", homeState: "GA", hometown: "Cumming", jerseyNumber: 37,
      hitForAvg: 20, power: 16, speed: 38, arm: 70, fielding: 46, errorResistance: 50, velocity: 74, control: 70, stamina: 68, stuff: 70,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 12, running: 34, throwing: 68, recovery: 62, wRISP: 62, vsLefty: 64, poise: 66, heater: 70, agile: 42,
      abilities: ["Tunneling"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Cooper", lastName: "Underwood", position: "P", eligibility: "FR", homeState: "GA", hometown: "Marietta", jerseyNumber: 42,
      hitForAvg: 18, power: 14, speed: 44, arm: 72, fielding: 40, errorResistance: 42, velocity: 76, control: 56, stamina: 52, stuff: 70,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 18, running: 42, throwing: 70, recovery: 48, wRISP: 46, vsLefty: 50, poise: 48, heater: 74, agile: 48,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 3, 0, 0, 0]) },
    { firstName: "Chandler", lastName: "Day", position: "P", eligibility: "SR", homeState: "GA", hometown: "Woodstock", jerseyNumber: 19,
      hitForAvg: 20, power: 16, speed: 36, arm: 68, fielding: 46, errorResistance: 50, velocity: 72, control: 72, stamina: 64, stuff: 66,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 10, running: 32, throwing: 66, recovery: 64, wRISP: 64, vsLefty: 66, poise: 68, heater: 68, agile: 40,
      abilities: ["Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 0, 4, 3, 0, 0]) },
    { firstName: "Luke", lastName: "Bartnicki", position: "P", eligibility: "SO", homeState: "GA", hometown: "Lawrenceville", jerseyNumber: 45,
      hitForAvg: 18, power: 14, speed: 40, arm: 66, fielding: 42, errorResistance: 46, velocity: 70, control: 64, stamina: 60, stuff: 64,
      clutch: 56, vsLHP: 54, grit: 58, stealing: 14, running: 36, throwing: 64, recovery: 56, wRISP: 54, vsLefty: 58, poise: 58, heater: 66, agile: 42,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 5, 0, 0, 0]) },
    { firstName: "Josh", lastName: "Stinson", position: "P", eligibility: "JR", homeState: "GA", hometown: "Alpharetta", jerseyNumber: 31,
      hitForAvg: 18, power: 15, speed: 38, arm: 66, fielding: 44, errorResistance: 48, velocity: 70, control: 66, stamina: 62, stuff: 64,
      clutch: 58, vsLHP: 56, grit: 60, stealing: 12, running: 34, throwing: 64, recovery: 58, wRISP: 56, vsLefty: 60, poise: 60, heater: 66, agile: 40,
      abilities: ["Fireman"], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 0, 5, 3, 0, 0]) },
    { firstName: "Weston", lastName: "Gales", position: "P", eligibility: "FR", homeState: "GA", hometown: "Peachtree City", jerseyNumber: 48,
      hitForAvg: 16, power: 14, speed: 42, arm: 68, fielding: 38, errorResistance: 40, velocity: 74, control: 52, stamina: 48, stuff: 66,
      clutch: 44, vsLHP: 42, grit: 46, stealing: 16, running: 40, throwing: 66, recovery: 44, wRISP: 42, vsLefty: 46, poise: 44, heater: 70, agile: 44,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 3, 4, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Vahn", lastName: "Lackey", position: "C", eligibility: "JR", homeState: "GA", hometown: "Suwanee", jerseyNumber: 8,
      hitForAvg: 72, power: 58, speed: 62, arm: 72, fielding: 70, errorResistance: 68, velocity: 40, control: 36, stamina: 40, stuff: 34,
      clutch: 74, vsLHP: 68, grit: 74, stealing: 54, running: 60, throwing: 74, recovery: 58, wRISP: 72, vsLefty: 66, poise: 72, heater: 36, agile: 64,
      abilities: ["Bazooka Arm", "Iron Wall"], potential: "A", catcherAbility: 76,
      ...noPitches },
    { firstName: "Riley", lastName: "Stanford", position: "C", eligibility: "SO", homeState: "GA", hometown: "Kennesaw", jerseyNumber: 24,
      hitForAvg: 44, power: 40, speed: 38, arm: 62, fielding: 56, errorResistance: 52, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 48, vsLHP: 44, grit: 50, stealing: 16, running: 36, throwing: 64, recovery: 44, wRISP: 46, vsLefty: 42, poise: 46, heater: 30, agile: 40,
      abilities: [], potential: "B", catcherAbility: 58,
      ...noPitches },
    // INFIELDERS (5)
    { firstName: "Carson", lastName: "Kerce", position: "SS", eligibility: "JR", homeState: "GA", hometown: "Buford", jerseyNumber: 2,
      hitForAvg: 64, power: 50, speed: 64, arm: 70, fielding: 72, errorResistance: 70, velocity: 38, control: 34, stamina: 36, stuff: 32,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 48, running: 62, throwing: 72, recovery: 56, wRISP: 64, vsLefty: 60, poise: 66, heater: 34, agile: 66,
      abilities: ["Iron Glove", "Table Setter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Kent", lastName: "Schmidt", position: "1B", eligibility: "JR", homeState: "GA", hometown: "Duluth", jerseyNumber: 22,
      hitForAvg: 62, power: 68, speed: 42, arm: 58, fielding: 62, errorResistance: 60, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 66, vsLHP: 62, grit: 66, stealing: 16, running: 40, throwing: 60, recovery: 54, wRISP: 66, vsLefty: 60, poise: 64, heater: 32, agile: 44,
      abilities: ["Power Slugger"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Michael", lastName: "Dee", position: "2B", eligibility: "FR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 14,
      hitForAvg: 46, power: 36, speed: 58, arm: 56, fielding: 54, errorResistance: 50, velocity: 32, control: 30, stamina: 34, stuff: 28,
      clutch: 46, vsLHP: 42, grit: 48, stealing: 40, running: 56, throwing: 58, recovery: 42, wRISP: 44, vsLefty: 40, poise: 44, heater: 28, agile: 58,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Logan", lastName: "Morris", position: "3B", eligibility: "JR", homeState: "GA", hometown: "Decatur", jerseyNumber: 11,
      hitForAvg: 56, power: 54, speed: 48, arm: 64, fielding: 60, errorResistance: 58, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 24, running: 46, throwing: 66, recovery: 50, wRISP: 56, vsLefty: 52, poise: 56, heater: 32, agile: 50,
      abilities: ["Gap Power"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Jake", lastName: "DeBrusk", position: "SS", eligibility: "SO", homeState: "GA", hometown: "Canton", jerseyNumber: 6,
      hitForAvg: 50, power: 40, speed: 60, arm: 62, fielding: 60, errorResistance: 56, velocity: 34, control: 32, stamina: 34, stuff: 28,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 42, running: 58, throwing: 64, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 30, agile: 62,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Drew", lastName: "Burress", position: "OF", eligibility: "JR", homeState: "GA", hometown: "Stockbridge", jerseyNumber: 1,
      hitForAvg: 78, power: 82, speed: 66, arm: 72, fielding: 70, errorResistance: 68, velocity: 42, control: 38, stamina: 40, stuff: 36,
      clutch: 80, vsLHP: 74, grit: 78, stealing: 48, running: 64, throwing: 74, recovery: 60, wRISP: 78, vsLefty: 72, poise: 76, heater: 38, agile: 68,
      abilities: ["Power Slugger", "Clutch Hitter"], potential: "A+", catcherAbility: null,
      ...noPitches },
    { firstName: "Parker", lastName: "Brosius", position: "OF", eligibility: "SR", homeState: "GA", hometown: "Roswell", jerseyNumber: 3,
      hitForAvg: 64, power: 56, speed: 60, arm: 66, fielding: 66, errorResistance: 64, velocity: 38, control: 34, stamina: 36, stuff: 32,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 40, running: 58, throwing: 68, recovery: 54, wRISP: 64, vsLefty: 60, poise: 66, heater: 34, agile: 62,
      abilities: ["Spray Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Caleb", lastName: "Daniel", position: "OF", eligibility: "SO", homeState: "GA", hometown: "Cartersville", jerseyNumber: 10,
      hitForAvg: 58, power: 50, speed: 62, arm: 64, fielding: 60, errorResistance: 58, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 44, running: 60, throwing: 66, recovery: 50, wRISP: 56, vsLefty: 52, poise: 56, heater: 32, agile: 64,
      abilities: ["Speed Demon"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Colin", lastName: "Reese", position: "OF", eligibility: "JR", homeState: "GA", hometown: "Smyrna", jerseyNumber: 15,
      hitForAvg: 54, power: 46, speed: 56, arm: 62, fielding: 58, errorResistance: 56, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 36, running: 54, throwing: 64, recovery: 48, wRISP: 54, vsLefty: 50, poise: 54, heater: 32, agile: 58,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Stephen", lastName: "Reid", position: "OF", eligibility: "SR", homeState: "SC", hometown: "Greenville", jerseyNumber: 17,
      hitForAvg: 56, power: 48, speed: 54, arm: 64, fielding: 60, errorResistance: 58, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 32, running: 52, throwing: 66, recovery: 50, wRISP: 56, vsLefty: 52, poise: 58, heater: 32, agile: 56,
      abilities: ["Tough Out"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Bryce", lastName: "Habetz", position: "OF", eligibility: "FR", homeState: "GA", hometown: "Athens", jerseyNumber: 21,
      hitForAvg: 42, power: 38, speed: 60, arm: 58, fielding: 50, errorResistance: 46, velocity: 32, control: 30, stamina: 34, stuff: 28,
      clutch: 42, vsLHP: 38, grit: 44, stealing: 38, running: 58, throwing: 60, recovery: 40, wRISP: 40, vsLefty: 36, poise: 40, heater: 28, agile: 60,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Louisville": [
    // PITCHERS (9)
    { firstName: "Brennyn", lastName: "Cutts", position: "P", eligibility: "SR", homeState: "KY", hometown: "Louisville", jerseyNumber: 34,
      hitForAvg: 24, power: 20, speed: 42, arm: 78, fielding: 50, errorResistance: 52, velocity: 80, control: 76, stamina: 76, stuff: 78,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 14, running: 38, throwing: 76, recovery: 70, wRISP: 70, vsLefty: 72, poise: 74, heater: 78, agile: 46,
      abilities: ["Strong Starter", "Intimidator"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [1, 6, 4, 5, 0, 0, 0]) },
    { firstName: "Eli", lastName: "Hoyt", position: "P", eligibility: "SR", homeState: "IN", hometown: "Indianapolis", jerseyNumber: 37,
      hitForAvg: 22, power: 18, speed: 40, arm: 76, fielding: 48, errorResistance: 50, velocity: 78, control: 74, stamina: 68, stuff: 76,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 12, running: 36, throwing: 74, recovery: 70, wRISP: 70, vsLefty: 72, poise: 76, heater: 76, agile: 44,
      abilities: ["Fireman", "Escape Pitch"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 7, 0, 5, 0, 3, 0]) },
    { firstName: "Peter", lastName: "Michael", position: "P", eligibility: "JR", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 28,
      hitForAvg: 20, power: 16, speed: 42, arm: 74, fielding: 46, errorResistance: 48, velocity: 76, control: 72, stamina: 72, stuff: 74,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 16, running: 38, throwing: 72, recovery: 64, wRISP: 64, vsLefty: 66, poise: 68, heater: 74, agile: 46,
      abilities: ["Heavy Ball"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Parker", lastName: "Detmers", position: "P", eligibility: "SO", homeState: "KY", hometown: "Lexington", jerseyNumber: 44,
      hitForAvg: 20, power: 16, speed: 44, arm: 74, fielding: 42, errorResistance: 44, velocity: 78, control: 66, stamina: 64, stuff: 74,
      clutch: 58, vsLHP: 56, grit: 60, stealing: 18, running: 42, throwing: 72, recovery: 56, wRISP: 56, vsLefty: 60, poise: 58, heater: 76, agile: 48,
      abilities: ["Pace"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 6, 3, 5, 0, 0, 0]) },
    { firstName: "Kade", lastName: "Grundy", position: "P", eligibility: "JR", homeState: "KY", hometown: "Bowling Green", jerseyNumber: 19,
      hitForAvg: 18, power: 15, speed: 38, arm: 70, fielding: 46, errorResistance: 50, velocity: 72, control: 72, stamina: 68, stuff: 68,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 12, running: 34, throwing: 68, recovery: 64, wRISP: 62, vsLefty: 64, poise: 66, heater: 68, agile: 40,
      abilities: ["Low Ball"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Jack", lastName: "Perkins", position: "P", eligibility: "SR", homeState: "OH", hometown: "Columbus", jerseyNumber: 41,
      hitForAvg: 20, power: 16, speed: 36, arm: 68, fielding: 46, errorResistance: 50, velocity: 72, control: 70, stamina: 62, stuff: 66,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 10, running: 32, throwing: 66, recovery: 64, wRISP: 64, vsLefty: 66, poise: 68, heater: 68, agile: 40,
      abilities: ["Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 0, 4, 3, 0, 0]) },
    { firstName: "Riley", lastName: "Bliss", position: "P", eligibility: "SO", homeState: "KY", hometown: "Owensboro", jerseyNumber: 29,
      hitForAvg: 18, power: 14, speed: 42, arm: 66, fielding: 42, errorResistance: 46, velocity: 72, control: 62, stamina: 58, stuff: 66,
      clutch: 54, vsLHP: 52, grit: 56, stealing: 16, running: 38, throwing: 64, recovery: 56, wRISP: 52, vsLefty: 56, poise: 56, heater: 68, agile: 44,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 3, 0, 0, 0]) },
    { firstName: "Chase", lastName: "Burns", position: "P", eligibility: "JR", homeState: "TN", hometown: "Murfreesboro", jerseyNumber: 31,
      hitForAvg: 18, power: 15, speed: 40, arm: 68, fielding: 44, errorResistance: 48, velocity: 70, control: 66, stamina: 64, stuff: 66,
      clutch: 58, vsLHP: 56, grit: 60, stealing: 12, running: 36, throwing: 66, recovery: 58, wRISP: 56, vsLefty: 60, poise: 60, heater: 66, agile: 42,
      abilities: ["Sharpness"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 0, 3, 0, 0]) },
    { firstName: "Austin", lastName: "Clay", position: "P", eligibility: "FR", homeState: "KY", hometown: "Paducah", jerseyNumber: 47,
      hitForAvg: 16, power: 14, speed: 44, arm: 70, fielding: 38, errorResistance: 40, velocity: 74, control: 54, stamina: 50, stuff: 68,
      clutch: 46, vsLHP: 44, grit: 48, stealing: 18, running: 42, throwing: 68, recovery: 46, wRISP: 44, vsLefty: 48, poise: 46, heater: 72, agile: 46,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 3, 4, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Matt", lastName: "Klein", position: "C", eligibility: "SO", homeState: "KY", hometown: "Prospect", jerseyNumber: 12,
      hitForAvg: 56, power: 52, speed: 40, arm: 70, fielding: 66, errorResistance: 64, velocity: 38, control: 36, stamina: 40, stuff: 32,
      clutch: 62, vsLHP: 58, grit: 66, stealing: 18, running: 38, throwing: 72, recovery: 54, wRISP: 60, vsLefty: 56, poise: 62, heater: 34, agile: 44,
      abilities: ["Iron Wall"], potential: "A-", catcherAbility: 68,
      ...noPitches },
    { firstName: "Ben", lastName: "Metzinger", position: "C", eligibility: "JR", homeState: "IN", hometown: "Evansville", jerseyNumber: 25,
      hitForAvg: 48, power: 44, speed: 36, arm: 64, fielding: 58, errorResistance: 54, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 14, running: 34, throwing: 66, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 30, agile: 38,
      abilities: [], potential: "B", catcherAbility: 60,
      ...noPitches },
    // INFIELDERS (5)
    { firstName: "Kamau", lastName: "Neighbors", position: "SS", eligibility: "SR", homeState: "GA", hometown: "Powder Springs", jerseyNumber: 2,
      hitForAvg: 70, power: 56, speed: 68, arm: 72, fielding: 74, errorResistance: 72, velocity: 40, control: 36, stamina: 38, stuff: 34,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 54, running: 66, throwing: 74, recovery: 58, wRISP: 70, vsLefty: 66, poise: 72, heater: 36, agile: 70,
      abilities: ["Clutch Hitter", "Iron Glove"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Caden", lastName: "Dulin", position: "2B", eligibility: "JR", homeState: "KY", hometown: "Elizabethtown", jerseyNumber: 7,
      hitForAvg: 58, power: 44, speed: 58, arm: 58, fielding: 64, errorResistance: 62, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 42, running: 56, throwing: 60, recovery: 52, wRISP: 58, vsLefty: 54, poise: 60, heater: 32, agile: 60,
      abilities: ["Table Setter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jake", lastName: "Snider", position: "3B", eligibility: "JR", homeState: "OH", hometown: "Dayton", jerseyNumber: 11,
      hitForAvg: 56, power: 54, speed: 48, arm: 64, fielding: 58, errorResistance: 56, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 24, running: 46, throwing: 66, recovery: 50, wRISP: 56, vsLefty: 52, poise: 56, heater: 32, agile: 50,
      abilities: ["Gap Power"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Tyler", lastName: "Fitzgerald", position: "1B", eligibility: "SR", homeState: "KY", hometown: "Florence", jerseyNumber: 22,
      hitForAvg: 60, power: 66, speed: 42, arm: 56, fielding: 62, errorResistance: 60, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 16, running: 40, throwing: 58, recovery: 52, wRISP: 64, vsLefty: 58, poise: 62, heater: 32, agile: 42,
      abilities: ["Power Slugger"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Drew", lastName: "Campbell", position: "SS", eligibility: "FR", homeState: "IN", hometown: "Fort Wayne", jerseyNumber: 9,
      hitForAvg: 46, power: 36, speed: 60, arm: 58, fielding: 56, errorResistance: 50, velocity: 32, control: 30, stamina: 34, stuff: 28,
      clutch: 46, vsLHP: 42, grit: 48, stealing: 42, running: 58, throwing: 60, recovery: 42, wRISP: 44, vsLefty: 40, poise: 44, heater: 28, agile: 60,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Eddie", lastName: "King Jr", position: "OF", eligibility: "SR", homeState: "TN", hometown: "Memphis", jerseyNumber: 1,
      hitForAvg: 78, power: 72, speed: 70, arm: 72, fielding: 72, errorResistance: 70, velocity: 42, control: 38, stamina: 40, stuff: 36,
      clutch: 80, vsLHP: 74, grit: 78, stealing: 54, running: 68, throwing: 74, recovery: 60, wRISP: 78, vsLefty: 72, poise: 76, heater: 38, agile: 72,
      abilities: ["Power Slugger", "Clutch Hitter"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Garret", lastName: "Pike", position: "OF", eligibility: "SR", homeState: "KY", hometown: "Covington", jerseyNumber: 3,
      hitForAvg: 62, power: 54, speed: 60, arm: 66, fielding: 64, errorResistance: 62, velocity: 38, control: 34, stamina: 36, stuff: 32,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 42, running: 58, throwing: 68, recovery: 54, wRISP: 62, vsLefty: 58, poise: 64, heater: 34, agile: 62,
      abilities: ["Spray Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Michael", lastName: "Lippe", position: "OF", eligibility: "JR", homeState: "OH", hometown: "Cleveland", jerseyNumber: 5,
      hitForAvg: 60, power: 52, speed: 58, arm: 64, fielding: 62, errorResistance: 60, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 38, running: 56, throwing: 66, recovery: 52, wRISP: 60, vsLefty: 56, poise: 62, heater: 32, agile: 60,
      abilities: ["Laser Beam"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Zion", lastName: "Rose", position: "OF", eligibility: "SO", homeState: "GA", hometown: "Macon", jerseyNumber: 10,
      hitForAvg: 56, power: 50, speed: 66, arm: 62, fielding: 58, errorResistance: 56, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 50, running: 64, throwing: 64, recovery: 48, wRISP: 54, vsLefty: 50, poise: 54, heater: 32, agile: 66,
      abilities: ["Speed Demon"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "McCoy", position: "OF", eligibility: "JR", homeState: "KY", hometown: "Frankfort", jerseyNumber: 15,
      hitForAvg: 54, power: 46, speed: 56, arm: 62, fielding: 58, errorResistance: 56, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 34, running: 54, throwing: 64, recovery: 48, wRISP: 54, vsLefty: 50, poise: 54, heater: 32, agile: 58,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Marcus", lastName: "Graves", position: "OF", eligibility: "FR", homeState: "KY", hometown: "Henderson", jerseyNumber: 21,
      hitForAvg: 44, power: 38, speed: 62, arm: 58, fielding: 50, errorResistance: 46, velocity: 32, control: 30, stamina: 34, stuff: 28,
      clutch: 44, vsLHP: 40, grit: 46, stealing: 40, running: 60, throwing: 60, recovery: 40, wRISP: 42, vsLefty: 38, poise: 42, heater: 28, agile: 62,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],
};
