import { RealPlayer } from "./realRosters";
import { pitchMix, noPitches } from "./pitchMixHelpers";

export const ACC_BATCH3_ROSTERS: Record<string, RealPlayer[]> = {
  "California": [
    // PITCHERS (10)
    { firstName: "Oliver", lastName: "de la Torre", position: "P", eligibility: "JR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 22,
      hitForAvg: 28, power: 22, speed: 35, arm: 73, fielding: 48, errorResistance: 60, velocity: 72, control: 67, stamina: 72, stuff: 69,
      clutch: 76, vsLHP: 72, grit: 80, stealing: 18, running: 46, throwing: 90, recovery: 64, wRISP: 59, vsLefty: 63, poise: 64, heater: 72, agile: 56,
      abilities: ["Strong Starter", "Wild Fastball", "Delayed Arm", "Intimidator", "Heavy Ball"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Ethan", lastName: "Foley", position: "P", eligibility: "JR", homeState: "CA", hometown: "San Diego", jerseyNumber: 33,
      hitForAvg: 20, power: 16, speed: 34, arm: 59, fielding: 35, errorResistance: 47, velocity: 59, control: 52, stamina: 56, stuff: 53,
      clutch: 60, vsLHP: 58, grit: 64, stealing: 15, running: 39, throwing: 73, recovery: 48, wRISP: 45, vsLefty: 47, poise: 48, heater: 57, agile: 43,
      abilities: ["Guts", "Lefty Killer", "Heavy Ball", "Intimidator", "Escape Pitch"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [1, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Gavin", lastName: "Eddy", position: "P", eligibility: "JR", homeState: "CA", hometown: "Claremont", jerseyNumber: 40,
      hitForAvg: 20, power: 16, speed: 33, arm: 58, fielding: 35, errorResistance: 48, velocity: 58, control: 53, stamina: 56, stuff: 53,
      clutch: 60, vsLHP: 57, grit: 65, stealing: 13, running: 37, throwing: 73, recovery: 48, wRISP: 45, vsLefty: 47, poise: 48, heater: 57, agile: 43,
      abilities: ["Guts", "Natural Shuuto", "Monster Stuff"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Cole", lastName: "Clark", position: "P", eligibility: "JR", homeState: "CA", hometown: "Bakersfield", jerseyNumber: 37,
      hitForAvg: 11, power: 9, speed: 25, arm: 29, fielding: 19, errorResistance: 28, velocity: 36, control: 27, stamina: 25, stuff: 25,
      clutch: 33, vsLHP: 33, grit: 37, stealing: 9, running: 23, throwing: 41, recovery: 24, wRISP: 22, vsLefty: 23, poise: 24, heater: 29, agile: 26,
      abilities: ["Fireman"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Jordy", lastName: "Lopez", position: "P", eligibility: "JR", homeState: "CA", hometown: "Riverside", jerseyNumber: 45,
      hitForAvg: 13, power: 9, speed: 31, arm: 30, fielding: 20, errorResistance: 33, velocity: 43, control: 29, stamina: 26, stuff: 30,
      clutch: 38, vsLHP: 37, grit: 41, stealing: 8, running: 24, throwing: 45, recovery: 26, wRISP: 24, vsLefty: 25, poise: 27, heater: 30, agile: 28,
      abilities: ["Groundball Pitcher"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 3, 4, 0]) },
    { firstName: "Ryan", lastName: "Takahashi", position: "P", eligibility: "JR", homeState: "CA", hometown: "Torrance", jerseyNumber: 28,
      hitForAvg: 11, power: 9, speed: 24, arm: 27, fielding: 17, errorResistance: 26, velocity: 30, control: 31, stamina: 25, stuff: 23,
      clutch: 33, vsLHP: 32, grit: 34, stealing: 7, running: 20, throwing: 37, recovery: 23, wRISP: 22, vsLefty: 23, poise: 24, heater: 27, agile: 23,
      abilities: ["Star of Victory"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Derek", lastName: "Ng", position: "P", eligibility: "SR", homeState: "CA", hometown: "San Francisco", jerseyNumber: 31,
      hitForAvg: 20, power: 15, speed: 32, arm: 48, fielding: 34, errorResistance: 48, velocity: 51, control: 49, stamina: 45, stuff: 42,
      clutch: 60, vsLHP: 58, grit: 63, stealing: 12, running: 30, throwing: 62, recovery: 45, wRISP: 44, vsLefty: 45, poise: 49, heater: 47, agile: 37,
      abilities: ["Guts", "Good Pickoff", "Strikeout", "Strong Starter"], potential: "B-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 3, 4, 0]) },
    { firstName: "Sean", lastName: "Watanabe", position: "P", eligibility: "JR", homeState: "CA", hometown: "Cupertino", jerseyNumber: 47,
      hitForAvg: 20, power: 16, speed: 34, arm: 51, fielding: 33, errorResistance: 48, velocity: 55, control: 49, stamina: 45, stuff: 45,
      clutch: 56, vsLHP: 55, grit: 60, stealing: 14, running: 37, throwing: 65, recovery: 43, wRISP: 42, vsLefty: 43, poise: 46, heater: 51, agile: 42,
      abilities: ["Perfect Combustion", "Heavy Ball", "Gyroball", "Intimidator"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Marcus", lastName: "Chen", position: "P", eligibility: "FR", homeState: "CA", hometown: "Fremont", jerseyNumber: 48,
      hitForAvg: 12, power: 10, speed: 31, arm: 34, fielding: 19, errorResistance: 30, velocity: 44, control: 26, stamina: 24, stuff: 30,
      clutch: 33, vsLHP: 30, grit: 34, stealing: 12, running: 29, throwing: 51, recovery: 21, wRISP: 20, vsLefty: 22, poise: 21, heater: 34, agile: 34,
      abilities: ["Poker Face", "Natural Shuuto"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Cole", lastName: "Posey", position: "P", eligibility: "FR", homeState: "CA", hometown: "Pleasanton", jerseyNumber: 49,
      hitForAvg: 12, power: 10, speed: 28, arm: 33, fielding: 18, errorResistance: 29, velocity: 40, control: 25, stamina: 24, stuff: 28,
      clutch: 30, vsLHP: 29, grit: 32, stealing: 11, running: 27, throwing: 47, recovery: 20, wRISP: 19, vsLefty: 22, poise: 20, heater: 33, agile: 32,
      abilities: ["Wizard Mode"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 3]) },
    // CATCHERS (2)
    { firstName: "Carl", lastName: "Schmidt", position: "C", eligibility: "SR", homeState: "CA", hometown: "San Mateo", jerseyNumber: 10,
      hitForAvg: 40, power: 37, speed: 30, arm: 43, fielding: 39, errorResistance: 39, velocity: 0, control: 0, stamina: 24, stuff: 0,
      clutch: 37, vsLHP: 35, grit: 39, stealing: 12, running: 23, throwing: 53, recovery: 32, wRISP: 36, vsLefty: 34, poise: 39, heater: 0, agile: 26,
      abilities: ["Ace Killer", "Multi-Hit"], potential: "B", catcherAbility: 39,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Nate", lastName: "Arakawa", position: "C", eligibility: "SO", homeState: "CA", hometown: "Sacramento", jerseyNumber: 24,
      hitForAvg: 40, power: 34, speed: 36, arm: 44, fielding: 40, errorResistance: 37, velocity: 0, control: 0, stamina: 24, stuff: 0,
      clutch: 33, vsLHP: 29, grit: 34, stealing: 9, running: 24, throwing: 52, recovery: 29, wRISP: 32, vsLefty: 28, poise: 33, heater: 0, agile: 27,
      abilities: ["Double Play"], potential: "B", catcherAbility: 41,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Cade", lastName: "Campbell", position: "3B", eligibility: "JR", homeState: "CA", hometown: "San Jose", jerseyNumber: 2,
      hitForAvg: 58, power: 50, speed: 55, arm: 52, fielding: 52, errorResistance: 51, velocity: 0, control: 0, stamina: 28, stuff: 0,
      clutch: 52, vsLHP: 49, grit: 54, stealing: 28, running: 43, throwing: 64, recovery: 42, wRISP: 51, vsLefty: 48, poise: 51, heater: 0, agile: 46,
      abilities: ["Defensive Artisan", "Consigliere"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Jacob", lastName: "French", position: "2B", eligibility: "JR", homeState: "CA", hometown: "Long Beach", jerseyNumber: 4,
      hitForAvg: 65, power: 46, speed: 68, arm: 50, fielding: 53, errorResistance: 52, velocity: 0, control: 0, stamina: 29, stuff: 0,
      clutch: 53, vsLHP: 50, grit: 55, stealing: 32, running: 46, throwing: 62, recovery: 42, wRISP: 55, vsLefty: 48, poise: 52, heater: 0, agile: 50,
      abilities: ["Contact Hitter", "Chance Maker"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Joshua", lastName: "Hanson", position: "1B", eligibility: "JR", homeState: "CA", hometown: "Pasadena", jerseyNumber: 15,
      hitForAvg: 61, power: 64, speed: 55, arm: 57, fielding: 57, errorResistance: 54, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 57, vsLHP: 53, grit: 58, stealing: 17, running: 41, throwing: 68, recovery: 46, wRISP: 57, vsLefty: 50, poise: 57, heater: 0, agile: 42,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Devin", lastName: "Ramirez", position: "SS", eligibility: "SO", homeState: "CA", hometown: "Stockton", jerseyNumber: 8,
      hitForAvg: 48, power: 40, speed: 68, arm: 49, fielding: 49, errorResistance: 47, velocity: 0, control: 0, stamina: 27, stuff: 0,
      clutch: 42, vsLHP: 38, grit: 44, stealing: 30, running: 44, throwing: 61, recovery: 37, wRISP: 41, vsLefty: 37, poise: 42, heater: 0, agile: 47,
      abilities: ["God of Pinch Hitting", "Consigliere", "Contact Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Ian", lastName: "Fujimoto", position: "1B", eligibility: "SO", homeState: "CA", hometown: "Irvine", jerseyNumber: 23,
      hitForAvg: 35, power: 38, speed: 46, arm: 34, fielding: 34, errorResistance: 33, velocity: 0, control: 0, stamina: 22, stuff: 0,
      clutch: 30, vsLHP: 29, grit: 32, stealing: 10, running: 23, throwing: 45, recovery: 26, wRISP: 29, vsLefty: 26, poise: 30, heater: 0, agile: 25,
      abilities: ["Bad Mood"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Ethan", lastName: "Kwan", position: "2B", eligibility: "FR", homeState: "CA", hometown: "Oakland", jerseyNumber: 18,
      hitForAvg: 40, power: 29, speed: 66, arm: 40, fielding: 33, errorResistance: 29, velocity: 0, control: 0, stamina: 21, stuff: 0,
      clutch: 26, vsLHP: 23, grit: 27, stealing: 22, running: 33, throwing: 44, recovery: 23, wRISP: 25, vsLefty: 22, poise: 26, heater: 0, agile: 35,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Jamal", lastName: "Patterson", position: "3B", eligibility: "FR", homeState: "CA", hometown: "Compton", jerseyNumber: 16,
      hitForAvg: 40, power: 34, speed: 55, arm: 40, fielding: 32, errorResistance: 31, velocity: 0, control: 0, stamina: 22, stuff: 0,
      clutch: 27, vsLHP: 26, grit: 29, stealing: 18, running: 32, throwing: 47, recovery: 26, wRISP: 26, vsLefty: 23, poise: 27, heater: 0, agile: 34,
      abilities: ["Walkoff Hitter", "First Pitch Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Seth", lastName: "Gwynn", position: "OF", eligibility: "SR", homeState: "CA", hometown: "Concord", jerseyNumber: 7,
      hitForAvg: 52, power: 47, speed: 60, arm: 47, fielding: 47, errorResistance: 45, velocity: 0, control: 0, stamina: 29, stuff: 0,
      clutch: 47, vsLHP: 44, grit: 49, stealing: 28, running: 42, throwing: 59, recovery: 40, wRISP: 45, vsLefty: 42, poise: 47, heater: 0, agile: 44,
      abilities: ["Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Alex", lastName: "Birge", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Danville", jerseyNumber: 9,
      hitForAvg: 52, power: 45, speed: 62, arm: 50, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 30, stuff: 0,
      clutch: 47, vsLHP: 43, grit: 48, stealing: 32, running: 48, throwing: 63, recovery: 40, wRISP: 45, vsLefty: 42, poise: 47, heater: 0, agile: 50,
      abilities: ["Express Baserunning"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Ricky", lastName: "Navarro", position: "OF", eligibility: "SO", homeState: "CA", hometown: "San Diego", jerseyNumber: 11,
      hitForAvg: 37, power: 33, speed: 47, arm: 37, fielding: 35, errorResistance: 34, velocity: 0, control: 0, stamina: 23, stuff: 0,
      clutch: 31, vsLHP: 28, grit: 33, stealing: 21, running: 34, throwing: 47, recovery: 27, wRISP: 30, vsLefty: 27, poise: 31, heater: 0, agile: 35,
      abilities: ["Contact Hitter"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...noPitches },
    { firstName: "Grant", lastName: "Larson", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Santa Cruz", jerseyNumber: 20,
      hitForAvg: 39, power: 35, speed: 49, arm: 37, fielding: 37, errorResistance: 35, velocity: 0, control: 0, stamina: 23, stuff: 0,
      clutch: 34, vsLHP: 32, grit: 35, stealing: 21, running: 34, throwing: 48, recovery: 30, wRISP: 33, vsLefty: 30, poise: 34, heater: 0, agile: 35,
      abilities: ["Head-first Slide", "Storming Home", "Pinch Hitter"], potential: "B-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Kyle", lastName: "Watkins", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Walnut Creek", jerseyNumber: 13,
      hitForAvg: 50, power: 43, speed: 61, arm: 48, fielding: 48, errorResistance: 46, velocity: 0, control: 0, stamina: 30, stuff: 0,
      clutch: 45, vsLHP: 42, grit: 46, stealing: 28, running: 45, throwing: 59, recovery: 38, wRISP: 43, vsLefty: 39, poise: 45, heater: 0, agile: 46,
      abilities: ["Trickster", "Contact Hitter", "Consigliere"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Tyler", lastName: "Maki", position: "OF", eligibility: "FR", homeState: "CA", hometown: "Fresno", jerseyNumber: 19,
      hitForAvg: 40, power: 32, speed: 59, arm: 40, fielding: 35, errorResistance: 33, velocity: 0, control: 0, stamina: 24, stuff: 0,
      clutch: 29, vsLHP: 25, grit: 30, stealing: 24, running: 39, throwing: 50, recovery: 25, wRISP: 26, vsLefty: 24, poise: 29, heater: 0, agile: 40,
      abilities: ["Inside Hitter", "Contact Hitter", "Batter Intimidator"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
  ],

  "Stanford": [
    // PITCHERS (10)
    { firstName: "Christian", lastName: "Lim", position: "P", eligibility: "JR", homeState: "CA", hometown: "Irvine", jerseyNumber: 35,
      hitForAvg: 27, power: 23, speed: 35, arm: 75, fielding: 47, errorResistance: 59, velocity: 70, control: 71, stamina: 74, stuff: 71,
      clutch: 79, vsLHP: 76, grit: 82, stealing: 17, running: 44, throwing: 90, recovery: 63, wRISP: 63, vsLefty: 65, poise: 68, heater: 74, agile: 54,
      abilities: ["Strong Starter", "Miracle Sharpness", "Intimidator", "Good Pickoff", "Heavy Ball", "Wild Fastball"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Parker", lastName: "Warner", position: "P", eligibility: "SO", homeState: "CA", hometown: "San Jose", jerseyNumber: 29,
      hitForAvg: 19, power: 15, speed: 33, arm: 52, fielding: 31, errorResistance: 44, velocity: 56, control: 47, stamina: 49, stuff: 46,
      clutch: 55, vsLHP: 52, grit: 57, stealing: 13, running: 35, throwing: 66, recovery: 42, wRISP: 40, vsLefty: 42, poise: 43, heater: 50, agile: 41,
      abilities: ["Guts", "High Spin Gyroball", "Natural Shuuto", "Groundball Pitcher"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...pitchMix(1, [1, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Aidan", lastName: "Keenan", position: "P", eligibility: "JR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 41,
      hitForAvg: 18, power: 14, speed: 32, arm: 48, fielding: 30, errorResistance: 42, velocity: 51, control: 45, stamina: 47, stuff: 44,
      clutch: 55, vsLHP: 53, grit: 57, stealing: 12, running: 32, throwing: 62, recovery: 40, wRISP: 40, vsLefty: 41, poise: 43, heater: 48, agile: 39,
      abilities: ["Guts", "Painter", "Strong Finisher"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Ryan", lastName: "Bruno", position: "P", eligibility: "JR", homeState: "CA", hometown: "Redwood City", jerseyNumber: 38,
      hitForAvg: 19, power: 14, speed: 32, arm: 49, fielding: 33, errorResistance: 46, velocity: 53, control: 48, stamina: 46, stuff: 45,
      clutch: 55, vsLHP: 54, grit: 57, stealing: 13, running: 33, throwing: 63, recovery: 42, wRISP: 41, vsLefty: 42, poise: 45, heater: 49, agile: 39,
      abilities: ["True Slider", "Guts", "Doctor K"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Justin", lastName: "Campbell", position: "P", eligibility: "SR", homeState: "CA", hometown: "Palo Alto", jerseyNumber: 44,
      hitForAvg: 20, power: 17, speed: 33, arm: 49, fielding: 33, errorResistance: 48, velocity: 53, control: 49, stamina: 46, stuff: 45,
      clutch: 59, vsLHP: 57, grit: 63, stealing: 13, running: 33, throwing: 63, recovery: 43, wRISP: 43, vsLefty: 45, poise: 48, heater: 49, agile: 39,
      abilities: ["Fireman", "Guts"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 3, 4, 0]) },
    { firstName: "Ty", lastName: "Uber", position: "P", eligibility: "SR", homeState: "CA", hometown: "Menlo Park", jerseyNumber: 32,
      hitForAvg: 12, power: 10, speed: 30, arm: 30, fielding: 19, errorResistance: 32, velocity: 30, control: 29, stamina: 26, stuff: 30,
      clutch: 39, vsLHP: 37, grit: 41, stealing: 8, running: 22, throwing: 44, recovery: 25, wRISP: 24, vsLefty: 25, poise: 27, heater: 30, agile: 27,
      abilities: ["Top Gear", "Intimidator"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 0, 0, 4, 4]) },
    { firstName: "Carson", lastName: "Peer", position: "P", eligibility: "SO", homeState: "CA", hometown: "Santa Monica", jerseyNumber: 46,
      hitForAvg: 11, power: 9, speed: 30, arm: 26, fielding: 17, errorResistance: 29, velocity: 40, control: 23, stamina: 22, stuff: 30,
      clutch: 33, vsLHP: 31, grit: 34, stealing: 9, running: 24, throwing: 41, recovery: 20, wRISP: 19, vsLefty: 21, poise: 20, heater: 27, agile: 28,
      abilities: ["Cross Cannon"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Drew", lastName: "Dowd", position: "P", eligibility: "JR", homeState: "CA", hometown: "Sacramento", jerseyNumber: 47,
      hitForAvg: 11, power: 8, speed: 30, arm: 28, fielding: 18, errorResistance: 29, velocity: 40, control: 26, stamina: 26, stuff: 30,
      clutch: 35, vsLHP: 33, grit: 36, stealing: 8, running: 22, throwing: 41, recovery: 23, wRISP: 22, vsLefty: 23, poise: 24, heater: 28, agile: 26,
      abilities: ["Release"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "David", lastName: "Wiser", position: "P", eligibility: "FR", homeState: "CA", hometown: "San Diego", jerseyNumber: 48,
      hitForAvg: 11, power: 10, speed: 28, arm: 32, fielding: 16, errorResistance: 27, velocity: 40, control: 24, stamina: 22, stuff: 28,
      clutch: 29, vsLHP: 28, grit: 30, stealing: 12, running: 28, throwing: 48, recovery: 20, wRISP: 18, vsLefty: 20, poise: 20, heater: 32, agile: 32,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Colt", lastName: "Peterson", position: "P", eligibility: "FR", homeState: "CA", hometown: "Fresno", jerseyNumber: 49,
      hitForAvg: 12, power: 9, speed: 32, arm: 36, fielding: 20, errorResistance: 31, velocity: 45, control: 26, stamina: 24, stuff: 31,
      clutch: 33, vsLHP: 31, grit: 34, stealing: 12, running: 31, throwing: 53, recovery: 22, wRISP: 20, vsLefty: 22, poise: 22, heater: 36, agile: 36,
      abilities: ["Grit"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 3]) },
    // CATCHERS (2)
    { firstName: "Charlie", lastName: "Bates", position: "C", eligibility: "JR", homeState: "CA", hometown: "Stockton", jerseyNumber: 10,
      hitForAvg: 55, power: 50, speed: 38, arm: 55, fielding: 52, errorResistance: 51, velocity: 0, control: 0, stamina: 32, stuff: 0,
      clutch: 51, vsLHP: 48, grit: 52, stealing: 17, running: 32, throwing: 68, recovery: 43, wRISP: 50, vsLefty: 46, poise: 51, heater: 0, agile: 36,
      abilities: ["High-Speed Laser"], potential: "B+", catcherAbility: 54,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "JJ", lastName: "Moran", position: "C", eligibility: "SO", homeState: "CA", hometown: "Newport Beach", jerseyNumber: 24,
      hitForAvg: 38, power: 34, speed: 32, arm: 42, fielding: 37, errorResistance: 36, velocity: 0, control: 0, stamina: 23, stuff: 0,
      clutch: 33, vsLHP: 31, grit: 36, stealing: 11, running: 23, throwing: 50, recovery: 30, wRISP: 32, vsLefty: 30, poise: 33, heater: 0, agile: 26,
      abilities: ["Double Play"], potential: "B+", catcherAbility: 38,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // INFIELDERS (8)
    { firstName: "Rintaro", lastName: "Sasaki", position: "1B", eligibility: "SO", homeState: "CA", hometown: "Stanford", jerseyNumber: 21,
      hitForAvg: 79, power: 87, speed: 55, arm: 44, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 27, stuff: 0,
      clutch: 68, vsLHP: 62, grit: 65, stealing: 13, running: 31, throwing: 55, recovery: 42, wRISP: 66, vsLefty: 60, poise: 62, heater: 0, agile: 34,
      abilities: ["Power Hitter", "Consigliere", "vs. Fastballs"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Jimmy", lastName: "Nati", position: "3B", eligibility: "SR", homeState: "NJ", hometown: "Toms River", jerseyNumber: 6,
      hitForAvg: 59, power: 61, speed: 55, arm: 52, fielding: 49, errorResistance: 47, velocity: 0, control: 0, stamina: 30, stuff: 0,
      clutch: 55, vsLHP: 52, grit: 55, stealing: 17, running: 36, throwing: 64, recovery: 44, wRISP: 55, vsLefty: 50, poise: 54, heater: 0, agile: 39,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Ethan", lastName: "Hott", position: "2B", eligibility: "JR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 3,
      hitForAvg: 55, power: 41, speed: 67, arm: 43, fielding: 46, errorResistance: 44, velocity: 0, control: 0, stamina: 25, stuff: 0,
      clutch: 46, vsLHP: 43, grit: 47, stealing: 26, running: 39, throwing: 54, recovery: 36, wRISP: 46, vsLefty: 41, poise: 44, heater: 0, agile: 41,
      abilities: ["Contact Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Brady", lastName: "Reynolds", position: "SS", eligibility: "JR", homeState: "CA", hometown: "Carlsbad", jerseyNumber: 1,
      hitForAvg: 38, power: 31, speed: 55, arm: 38, fielding: 38, errorResistance: 37, velocity: 0, control: 0, stamina: 20, stuff: 0,
      clutch: 34, vsLHP: 32, grit: 35, stealing: 23, running: 33, throwing: 49, recovery: 29, wRISP: 33, vsLefty: 31, poise: 34, heater: 0, agile: 35,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Eric", lastName: "Jeon", position: "2B", eligibility: "JR", homeState: "NY", hometown: "New York", jerseyNumber: 14,
      hitForAvg: 64, power: 44, speed: 68, arm: 51, fielding: 54, errorResistance: 51, velocity: 0, control: 0, stamina: 31, stuff: 0,
      clutch: 54, vsLHP: 49, grit: 55, stealing: 31, running: 46, throwing: 64, recovery: 43, wRISP: 54, vsLefty: 48, poise: 54, heater: 0, agile: 49,
      abilities: ["Chance Maker"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Brock", lastName: "Sell", position: "3B", eligibility: "FR", homeState: "CA", hometown: "San Clemente", jerseyNumber: 12,
      hitForAvg: 65, power: 58, speed: 55, arm: 59, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 31, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 54, stealing: 28, running: 48, throwing: 71, recovery: 43, wRISP: 51, vsLefty: 48, poise: 50, heater: 0, agile: 51,
      abilities: ["Consigliere"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Brock", lastName: "Ketelsen", position: "SS", eligibility: "FR", homeState: "CA", hometown: "Encinitas", jerseyNumber: 8,
      hitForAvg: 40, power: 30, speed: 66, arm: 40, fielding: 30, errorResistance: 28, velocity: 0, control: 0, stamina: 18, stuff: 0,
      clutch: 28, vsLHP: 26, grit: 29, stealing: 20, running: 30, throwing: 44, recovery: 22, wRISP: 27, vsLefty: 25, poise: 27, heater: 0, agile: 32,
      abilities: ["Pull Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Teddy", lastName: "Tokheim", position: "OF", eligibility: "FR", homeState: "MN", hometown: "Edina", jerseyNumber: 18,
      hitForAvg: 34, power: 73, speed: 48, arm: 34, fielding: 28, errorResistance: 25, velocity: 0, control: 0, stamina: 18, stuff: 0,
      clutch: 24, vsLHP: 22, grit: 25, stealing: 14, running: 24, throwing: 42, recovery: 20, wRISP: 24, vsLefty: 21, poise: 24, heater: 0, agile: 27,
      abilities: ["Shock Commander"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...noPitches },
    // OUTFIELDERS (5)
    { firstName: "Tatum", lastName: "Marsh", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Atherton", jerseyNumber: 7,
      hitForAvg: 58, power: 45, speed: 61, arm: 47, fielding: 47, errorResistance: 45, velocity: 0, control: 0, stamina: 27, stuff: 0,
      clutch: 50, vsLHP: 47, grit: 50, stealing: 30, running: 44, throwing: 58, recovery: 39, wRISP: 50, vsLefty: 45, poise: 48, heater: 0, agile: 45,
      abilities: ["Contact Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Luke", lastName: "Lavin", position: "OF", eligibility: "JR", homeState: "CA", hometown: "San Francisco", jerseyNumber: 20,
      hitForAvg: 57, power: 50, speed: 62, arm: 53, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 32, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 32, running: 49, throwing: 65, recovery: 43, wRISP: 49, vsLefty: 45, poise: 50, heater: 0, agile: 50,
      abilities: ["Home Defense"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "R",
      ...noPitches },
    { firstName: "Cort", lastName: "MacDonald", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Walnut Creek", jerseyNumber: 27,
      hitForAvg: 59, power: 51, speed: 63, arm: 55, fielding: 55, errorResistance: 53, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 53, stealing: 35, running: 53, throwing: 66, recovery: 44, wRISP: 49, vsLefty: 46, poise: 52, heater: 0, agile: 55,
      abilities: ["Express Baserunning"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...noPitches },
    { firstName: "Jack", lastName: "O'Brien", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Atherton", jerseyNumber: 22,
      hitForAvg: 40, power: 35, speed: 58, arm: 40, fielding: 35, errorResistance: 34, velocity: 0, control: 0, stamina: 22, stuff: 0,
      clutch: 33, vsLHP: 31, grit: 34, stealing: 21, running: 34, throwing: 48, recovery: 30, wRISP: 31, vsLefty: 30, poise: 33, heater: 0, agile: 35,
      abilities: ["Artist", "Walkoff Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Drew", lastName: "Bowser", position: "OF", eligibility: "SO", homeState: "CA", hometown: "Sacramento", jerseyNumber: 9,
      hitForAvg: 37, power: 32, speed: 54, arm: 37, fielding: 33, errorResistance: 32, velocity: 0, control: 0, stamina: 21, stuff: 0,
      clutch: 30, vsLHP: 27, grit: 31, stealing: 22, running: 33, throwing: 46, recovery: 27, wRISP: 29, vsLefty: 27, poise: 30, heater: 0, agile: 35,
      abilities: ["Predicament"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
  ],

  "Virginia": [
      // 32-16/12-12 ACC, RPI #18, D1B #20s, peak #10. Chris Pollard Yr 1 (from Duke). HR 5th nation, Runs 9th nation.
      // PITCHERS (10) — 1-8 pitch scale
      // Henry Zatkowski — Friday JR RHP, 7IP/2ER/10K vs Clemson, established Friday ace
      { firstName: "Henry", lastName: "Zatkowski", position: "P", eligibility: "JR", homeState: "NC", hometown: "Durham", jerseyNumber: 34,
        hitForAvg: 14, power: 11, speed: 32, arm: 63, fielding: 40, errorResistance: 54, velocity: 63, control: 64, stamina: 64, stuff: 61,
        clutch: 76, vsLHP: 70, grit: 76, stealing: 10, running: 32, throwing: 76, recovery: 52, wRISP: 56, vsLefty: 61, poise: 61, heater: 63, agile: 42,
        abilities: ["Strong Starter", "Sharpness", "Doctor K", "Strong Finisher"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
      // Kyle Johnson — Saturday LHP JR, 6-0/4.06 ERA, team-high 73 K, 1.20 ERA at home
      { firstName: "Kyle", lastName: "Johnson", position: "P", eligibility: "JR", homeState: "VA", hometown: "Richmond", jerseyNumber: 21,
        hitForAvg: 16, power: 13, speed: 33, arm: 65, fielding: 41, errorResistance: 54, velocity: 65, control: 62, stamina: 65, stuff: 65,
        clutch: 80, vsLHP: 84, grit: 76, stealing: 10, running: 34, throwing: 78, recovery: 57, wRISP: 62, vsLefty: 68, poise: 65, heater: 68, agile: 44,
        abilities: ["Strong Starter", "Fireman", "Doctor K", "Intimidator"], potential: "A", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [1, 0, 0, 1, 0, 0, 4]) },
      // Tyler Kapa — Sunday/Stopper JR RHP, "unicorn" outlier metrics, Stopper of Year semi, 90K/66IP last yr
      { firstName: "Tyler", lastName: "Kapa", position: "P", eligibility: "JR", homeState: "VA", hometown: "Richmond", jerseyNumber: 26,
        hitForAvg: 14, power: 11, speed: 32, arm: 68, fielding: 40, errorResistance: 54, velocity: 67, control: 56, stamina: 56, stuff: 68,
        clutch: 76, vsLHP: 70, grit: 76, stealing: 10, running: 32, throwing: 80, recovery: 51, wRISP: 56, vsLefty: 56, poise: 61, heater: 68, agile: 42,
        abilities: ["Doctor K", "Intimidator", "Sharpness", "Heavy Ball"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
      // Lucas Hartman — closer JR, 12 G (T-3rd nation), NPOY + SOY semi, Midseason 2nd Team All-Am — TEAM ELITE STUFF
      { firstName: "Lucas", lastName: "Hartman", position: "P", eligibility: "JR", homeState: "KY", hometown: "Bowling Green", jerseyNumber: 40,
        hitForAvg: 13, power: 10, speed: 32, arm: 64, fielding: 40, errorResistance: 54, velocity: 64, control: 62, stamina: 40, stuff: 69,
        clutch: 80, vsLHP: 76, grit: 80, stealing: 9, running: 30, throwing: 78, recovery: 45, wRISP: 64, vsLefty: 61, poise: 64, heater: 67, agile: 42,
        abilities: ["Fireman", "Doctor K", "Inside Pitch"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 0]) },
      // Joe Colucci — JR RHP RP
      { firstName: "Joe", lastName: "Colucci", position: "P", eligibility: "JR", homeState: "VA", hometown: "Virginia Beach", jerseyNumber: 27,
        hitForAvg: 13, power: 10, speed: 32, arm: 48, fielding: 30, errorResistance: 42, velocity: 52, control: 48, stamina: 38, stuff: 45,
        clutch: 60, vsLHP: 56, grit: 60, stealing: 9, running: 32, throwing: 62, recovery: 39, wRISP: 42, vsLefty: 44, poise: 45, heater: 50, agile: 38,
        abilities: ["Fireman", "Winner's Luck", "Poker Face"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
      // Max Stammel — JR RHP rotation depth
      { firstName: "Max", lastName: "Stammel", position: "P", eligibility: "JR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 37,
        hitForAvg: 14, power: 12, speed: 32, arm: 52, fielding: 32, errorResistance: 44, velocity: 56, control: 49, stamina: 49, stuff: 48,
        clutch: 60, vsLHP: 56, grit: 60, stealing: 10, running: 32, throwing: 64, recovery: 43, wRISP: 43, vsLefty: 46, poise: 46, heater: 54, agile: 40,
        abilities: ["Guts", "Low Ball", "Showtime", "Strong Finisher"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
      // Matt Buchanan — SR RHP
      { firstName: "Matt", lastName: "Buchanan", position: "P", eligibility: "SR", homeState: "VA", hometown: "Fairfax", jerseyNumber: 44,
        hitForAvg: 11, power: 9, speed: 29, arm: 32, fielding: 21, errorResistance: 32, velocity: 33, control: 37, stamina: 29, stuff: 28,
        clutch: 39, vsLHP: 39, grit: 43, stealing: 7, running: 22, throwing: 43, recovery: 27, wRISP: 27, vsLefty: 27, poise: 31, heater: 32, agile: 26,
        abilities: ["Guts"], potential: "B", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 3, 4, 0]) },
      // Noah Yoder — FR RHP — PG Frosh 2nd Team / Top-200 national
      { firstName: "Noah", lastName: "Yoder", position: "P", eligibility: "FR", homeState: "VA", hometown: "Harrisonburg", jerseyNumber: 49,
        hitForAvg: 8, power: 7, speed: 24, arm: 36, fielding: 16, errorResistance: 24, velocity: 42, control: 30, stamina: 27, stuff: 34,
        clutch: 27, vsLHP: 25, grit: 27, stealing: 9, running: 22, throwing: 40, recovery: 17, wRISP: 17, vsLefty: 19, poise: 19, heater: 30, agile: 27,
        abilities: ["Explosive Fastball"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
      // Jayden Stroman — FR midweek SP — PG HM / Top-500 national (2.70 ERA / 16 K in 13.1 IP)
      { firstName: "Jayden", lastName: "Stroman", position: "P", eligibility: "FR", homeState: "VA", hometown: "Chesapeake", jerseyNumber: 48,
        hitForAvg: 14, power: 11, speed: 33, arm: 48, fielding: 22, errorResistance: 34, velocity: 55, control: 43, stamina: 41, stuff: 44,
        clutch: 42, vsLHP: 38, grit: 42, stealing: 16, running: 36, throwing: 54, recovery: 25, wRISP: 27, vsLefty: 28, poise: 29, heater: 40, agile: 40,
        abilities: ["Strong Starter", "Doctor K"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
      // Kevin Jaxel — JR RHP
      { firstName: "Kevin", lastName: "Jaxel", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Ridgewood", jerseyNumber: 31,
        hitForAvg: 11, power: 9, speed: 28, arm: 31, fielding: 20, errorResistance: 31, velocity: 33, control: 36, stamina: 27, stuff: 27,
        clutch: 36, vsLHP: 35, grit: 38, stealing: 9, running: 24, throwing: 42, recovery: 25, wRISP: 24, vsLefty: 25, poise: 25, heater: 31, agile: 27,
        abilities: ["Gyroball"], potential: "B", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
      // CATCHERS (2)
      // Ethan Anderson — JR C
      { firstName: "Ethan", lastName: "Anderson", position: "C", eligibility: "JR", homeState: "VA", hometown: "Charlottesville", jerseyNumber: 12,
        hitForAvg: 63, power: 57, speed: 38, arm: 60, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 56, vsLHP: 50, grit: 56, stealing: 16, running: 32, throwing: 70, recovery: 46, wRISP: 56, vsLefty: 50, poise: 56, heater: 0, agile: 38,
        abilities: ["High-Speed Laser", "Defensive Artisan"], potential: "A-", catcherAbility: 58,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Thomas O'Connell — FR C
      { firstName: "Thomas", lastName: "O'Connell", position: "C", eligibility: "FR", homeState: "MD", hometown: "Bethesda", jerseyNumber: 25,
        hitForAvg: 40, power: 35, speed: 36, arm: 44, fielding: 40, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 32, vsLHP: 28, grit: 32, stealing: 10, running: 24, throwing: 52, recovery: 28, wRISP: 30, vsLefty: 28, poise: 32, heater: 0, agile: 28,
        abilities: ["Artist"], potential: "A-", catcherAbility: 40,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // INFIELDERS (7)
      // Eric Becker — SS SR, Brooks Wallace Award (top SS), offensive anchor — TEAM ELITE HIT
      { firstName: "Eric", lastName: "Becker", position: "SS", eligibility: "SR", homeState: "VA", hometown: "Fredericksburg", jerseyNumber: 2,
        hitForAvg: 95, power: 71, speed: 73, arm: 70, fielding: 80, errorResistance: 76, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 80, vsLHP: 76, grit: 80, stealing: 50, running: 64, throwing: 86, recovery: 56, wRISP: 80, vsLefty: 76, poise: 80, heater: 0, agile: 70,
        abilities: ["Contact Hitter", "Defensive Artisan", "Consigliere", "Hit Machine"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Harrison Didawick — 1B SR, power bat
      { firstName: "Harrison", lastName: "Didawick", position: "1B", eligibility: "SR", homeState: "VA", hometown: "Fredericksburg", jerseyNumber: 24,
        hitForAvg: 67, power: 77, speed: 55, arm: 50, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 70, vsLHP: 64, grit: 70, stealing: 14, running: 32, throwing: 60, recovery: 42, wRISP: 70, vsLefty: 64, poise: 70, heater: 0, agile: 36,
        abilities: ["Artist", "Power Hitter", "Consigliere"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Sam Harris — 2B JR, multi-HR vs Monmouth
      { firstName: "Sam", lastName: "Harris", position: "2B", eligibility: "JR", homeState: "VA", hometown: "McLean", jerseyNumber: 8,
        hitForAvg: 67, power: 85, speed: 68, arm: 50, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 60, vsLHP: 54, grit: 60, stealing: 26, running: 42, throwing: 60, recovery: 42, wRISP: 60, vsLefty: 54, poise: 60, heater: 0, agile: 48,
        abilities: ["Power Hitter", "Contact Hitter"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Noah Murray — INF, broke program record for runs in game (3-run blast), Crozet native
      { firstName: "Noah", lastName: "Murray", position: "2B", eligibility: "JR", homeState: "VA", hometown: "Crozet", jerseyNumber: 9,
        hitForAvg: 67, power: 67, speed: 67, arm: 50, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 70, vsLHP: 56, grit: 60, stealing: 22, running: 42, throwing: 60, recovery: 42, wRISP: 70, vsLefty: 56, poise: 60, heater: 0, agile: 46,
        abilities: ["Power Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "S",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Aiden Harris — 3B FR
      { firstName: "Aiden", lastName: "Harris", position: "3B", eligibility: "FR", homeState: "VA", hometown: "Alexandria", jerseyNumber: 3,
        hitForAvg: 63, power: 57, speed: 55, arm: 60, fielding: 52, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 56, vsLHP: 48, grit: 54, stealing: 28, running: 50, throwing: 72, recovery: 42, wRISP: 56, vsLefty: 46, poise: 50, heater: 0, agile: 52,
        abilities: ["Consigliere"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Zach Jackson — 3B JR, homered in VCU sweep
      { firstName: "Zach", lastName: "Jackson", position: "3B", eligibility: "JR", homeState: "VA", hometown: "Norfolk", jerseyNumber: 14,
        hitForAvg: 45, power: 45, speed: 43, arm: 36, fielding: 34, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 39, vsLHP: 36, grit: 39, stealing: 11, running: 23, throwing: 46, recovery: 28, wRISP: 39, vsLefty: 36, poise: 39, heater: 0, agile: 25,
        abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // RJ Holmes — SS FR
      { firstName: "RJ", lastName: "Holmes", position: "SS", eligibility: "FR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 18,
        hitForAvg: 40, power: 31, speed: 66, arm: 40, fielding: 34, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 26, vsLHP: 24, grit: 28, stealing: 22, running: 34, throwing: 48, recovery: 26, wRISP: 26, vsLefty: 22, poise: 26, heater: 0, agile: 36,
        abilities: ["Artist", "Multi-Hit", "Contact Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "fade",
        ...noPitches },
      // OUTFIELDERS (6)
      // AJ Gracia — OF JR, Perfect Game 1st Team All-American, Golden Spikes Watch List, multi-HR
      { firstName: "AJ", lastName: "Gracia", position: "OF", eligibility: "JR", homeState: "NC", hometown: "Durham", jerseyNumber: 6,
        hitForAvg: 77, power: 88, speed: 63, arm: 56, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 80, vsLHP: 70, grit: 80, stealing: 36, running: 52, throwing: 66, recovery: 44, wRISP: 80, vsLefty: 70, poise: 80, heater: 0, agile: 56,
        abilities: ["Artist", "Power Hitter", "Contact Hitter"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Antonio Perrotta — OF JR
      { firstName: "Antonio", lastName: "Perrotta", position: "OF", eligibility: "JR", homeState: "VA", hometown: "Leesburg", jerseyNumber: 10,
        hitForAvg: 57, power: 53, speed: 61, arm: 52, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 50, vsLHP: 46, grit: 50, stealing: 24, running: 42, throwing: 64, recovery: 42, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 46,
        abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Jack Brendle — OF SO
      { firstName: "Jack", lastName: "Brendle", position: "OF", eligibility: "SO", homeState: "NC", hometown: "Charlotte", jerseyNumber: 16,
        hitForAvg: 40, power: 35, speed: 50, arm: 38, fielding: 36, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 35, vsLHP: 31, grit: 35, stealing: 23, running: 35, throwing: 48, recovery: 30, wRISP: 33, vsLefty: 30, poise: 35, heater: 0, agile: 36,
        abilities: ["Express Baserunning"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Colin Tuft — OF JR
      { firstName: "Colin", lastName: "Tuft", position: "OF", eligibility: "JR", homeState: "VA", hometown: "McLean", jerseyNumber: 7,
        hitForAvg: 57, power: 49, speed: 62, arm: 54, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 50, vsLHP: 46, grit: 50, stealing: 32, running: 50, throwing: 66, recovery: 42, wRISP: 48, vsLefty: 46, poise: 50, heater: 0, agile: 52,
        abilities: ["High-Speed Laser", "Multi-Hit"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Anthony Stephan — OF SR
      { firstName: "Anthony", lastName: "Stephan", position: "OF", eligibility: "SR", homeState: "VA", hometown: "Leesburg", jerseyNumber: 22,
        hitForAvg: 63, power: 53, speed: 62, arm: 56, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 56, vsLHP: 50, grit: 58, stealing: 32, running: 50, throwing: 70, recovery: 44, wRISP: 52, vsLefty: 48, poise: 56, heater: 0, agile: 52,
        abilities: ["High-Speed Laser"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Spencer Metz — OF SO
      { firstName: "Spencer", lastName: "Metz", position: "OF", eligibility: "SO", homeState: "VA", hometown: "Manassas", jerseyNumber: 19,
        hitForAvg: 41, power: 35, speed: 59, arm: 40, fielding: 38, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 32, vsLHP: 30, grit: 34, stealing: 24, running: 36, throwing: 48, recovery: 30, wRISP: 30, vsLefty: 28, poise: 32, heater: 0, agile: 38,
        abilities: ["Final Hit", "Error Prone"], potential: "B", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
    ],
  
  "Virginia Tech": [
    // PITCHERS (10)
    { firstName: "Brett", lastName: "Renfrow", position: "P", eligibility: "SR", homeState: "VA", hometown: "Richmond", jerseyNumber: 34,
      hitForAvg: 25, power: 21, speed: 35, arm: 71, fielding: 44, errorResistance: 56, velocity: 70, control: 67, stamina: 68, stuff: 68,
      clutch: 81, vsLHP: 77, grit: 83, stealing: 17, running: 43, throwing: 90, recovery: 63, wRISP: 65, vsLefty: 65, poise: 68, heater: 71, agile: 54,
      abilities: ["Star of Victory", "Intimidator", "Escape Pitch", "Heavy Ball", "Release"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [1, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Logan", lastName: "Eisenreich", position: "P", eligibility: "SO", homeState: "VA", hometown: "Blacksburg", jerseyNumber: 29,
      hitForAvg: 17, power: 13, speed: 32, arm: 44, fielding: 27, errorResistance: 39, velocity: 49, control: 40, stamina: 41, stuff: 39,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 11, running: 32, throwing: 58, recovery: 35, wRISP: 35, vsLefty: 37, poise: 38, heater: 44, agile: 37,
      abilities: ["Strong Starter", "vs. Strong Batters", "Bad Ball Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Aiden", lastName: "Robertson", position: "P", eligibility: "JR", homeState: "GA", hometown: "Augusta", jerseyNumber: 41,
      hitForAvg: 17, power: 14, speed: 32, arm: 49, fielding: 30, errorResistance: 42, velocity: 54, control: 45, stamina: 47, stuff: 45,
      clutch: 57, vsLHP: 55, grit: 58, stealing: 12, running: 31, throwing: 64, recovery: 42, wRISP: 42, vsLefty: 43, poise: 44, heater: 49, agile: 38,
      abilities: ["Guts", "Wild Fastball", "Winner's Luck", "Crossfire"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Griffin", lastName: "Green", position: "P", eligibility: "JR", homeState: "VA", hometown: "Roanoke", jerseyNumber: 38,
      hitForAvg: 19, power: 16, speed: 33, arm: 53, fielding: 35, errorResistance: 47, velocity: 57, control: 51, stamina: 51, stuff: 49,
      clutch: 59, vsLHP: 57, grit: 62, stealing: 14, running: 36, throwing: 67, recovery: 44, wRISP: 44, vsLefty: 46, poise: 48, heater: 53, agile: 42,
      abilities: ["Guts", "Showtime", "vs. Strong Batters"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Drue", lastName: "Hackenberg", position: "P", eligibility: "SO", homeState: "PA", hometown: "Mechanicsburg", jerseyNumber: 37,
      hitForAvg: 11, power: 8, speed: 30, arm: 28, fielding: 18, errorResistance: 29, velocity: 41, control: 26, stamina: 26, stuff: 30,
      clutch: 36, vsLHP: 36, grit: 38, stealing: 8, running: 23, throwing: 43, recovery: 23, wRISP: 23, vsLefty: 23, poise: 24, heater: 28, agile: 26,
      abilities: ["Delayed Arm"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Noah", lastName: "Sorrells", position: "P", eligibility: "JR", homeState: "VA", hometown: "Harrisonburg", jerseyNumber: 45,
      hitForAvg: 12, power: 9, speed: 27, arm: 30, fielding: 20, errorResistance: 31, velocity: 33, control: 35, stamina: 28, stuff: 27,
      clutch: 39, vsLHP: 37, grit: 40, stealing: 9, running: 23, throwing: 43, recovery: 26, wRISP: 25, vsLefty: 26, poise: 28, heater: 30, agile: 27,
      abilities: ["Fireman"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Luke", lastName: "Vickers", position: "P", eligibility: "SR", homeState: "VA", hometown: "Herndon", jerseyNumber: 44,
      hitForAvg: 17, power: 14, speed: 32, arm: 42, fielding: 29, errorResistance: 42, velocity: 49, control: 44, stamina: 40, stuff: 37,
      clutch: 52, vsLHP: 51, grit: 55, stealing: 10, running: 28, throwing: 55, recovery: 38, wRISP: 37, vsLefty: 38, poise: 42, heater: 42, agile: 33,
      abilities: ["Guts", "Gyroball"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 3, 4, 0]) },
    { firstName: "Ethan", lastName: "Douglas", position: "P", eligibility: "SO", homeState: "VA", hometown: "Norfolk", jerseyNumber: 32,
      hitForAvg: 12, power: 9, speed: 29, arm: 31, fielding: 20, errorResistance: 33, velocity: 29, control: 37, stamina: 28, stuff: 28,
      clutch: 37, vsLHP: 36, grit: 40, stealing: 9, running: 26, throwing: 45, recovery: 25, wRISP: 24, vsLefty: 25, poise: 27, heater: 31, agile: 30,
      abilities: ["Explosive Fastball", "Heavy Ball"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Ethan", lastName: "Grim", position: "P", eligibility: "FR", homeState: "VA", hometown: "Lynchburg", jerseyNumber: 47,
      hitForAvg: 11, power: 9, speed: 28, arm: 33, fielding: 18, errorResistance: 28, velocity: 41, control: 25, stamina: 24, stuff: 30,
      clutch: 33, vsLHP: 30, grit: 33, stealing: 11, running: 28, throwing: 48, recovery: 21, wRISP: 21, vsLefty: 22, poise: 22, heater: 33, agile: 33,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Austin", lastName: "Dean", position: "P", eligibility: "FR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 46,
      hitForAvg: 10, power: 9, speed: 26, arm: 32, fielding: 17, errorResistance: 26, velocity: 39, control: 23, stamina: 22, stuff: 28,
      clutch: 29, vsLHP: 27, grit: 30, stealing: 9, running: 25, throwing: 46, recovery: 18, wRISP: 18, vsLefty: 20, poise: 20, heater: 32, agile: 29,
      abilities: ["Gyroball", "Wizard Mode", "Intimidator"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    // CATCHERS (2)
    { firstName: "Henry", lastName: "Cooke", position: "C", eligibility: "JR", homeState: "VA", hometown: "Chesapeake", jerseyNumber: 10,
      hitForAvg: 54, power: 51, speed: 37, arm: 55, fielding: 52, errorResistance: 51, velocity: 0, control: 0, stamina: 30, stuff: 0,
      clutch: 51, vsLHP: 47, grit: 54, stealing: 15, running: 29, throwing: 67, recovery: 43, wRISP: 51, vsLefty: 46, poise: 52, heater: 0, agile: 33,
      abilities: ["High-Speed Laser", "Consigliere"], potential: "A-", catcherAbility: 52,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "CJ", lastName: "Oxendine", position: "C", eligibility: "FR", homeState: "NC", hometown: "Fayetteville", jerseyNumber: 25,
      hitForAvg: 40, power: 34, speed: 36, arm: 43, fielding: 40, errorResistance: 35, velocity: 0, control: 0, stamina: 24, stuff: 0,
      clutch: 31, vsLHP: 29, grit: 33, stealing: 10, running: 24, throwing: 52, recovery: 27, wRISP: 30, vsLefty: 27, poise: 31, heater: 0, agile: 26,
      abilities: ["Double Play"], potential: "A-", catcherAbility: 40,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Sam", lastName: "Grube", position: "2B", eligibility: "SO", homeState: "MD", hometown: "Emmitsburg", jerseyNumber: 4,
      hitForAvg: 38, power: 29, speed: 53, arm: 32, fielding: 34, errorResistance: 32, velocity: 0, control: 0, stamina: 20, stuff: 0,
      clutch: 32, vsLHP: 30, grit: 34, stealing: 28, running: 35, throwing: 44, recovery: 27, wRISP: 31, vsLefty: 29, poise: 31, heater: 0, agile: 38,
      abilities: ["Express Baserunning", "Chance Maker"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Pete", lastName: "Daniel", position: "1B", eligibility: "JR", homeState: "TN", hometown: "Nashville", jerseyNumber: 18,
      hitForAvg: 40, power: 41, speed: 55, arm: 40, fielding: 34, errorResistance: 33, velocity: 0, control: 0, stamina: 21, stuff: 0,
      clutch: 34, vsLHP: 32, grit: 35, stealing: 10, running: 24, throwing: 45, recovery: 28, wRISP: 34, vsLefty: 30, poise: 34, heater: 0, agile: 26,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Ethan", lastName: "Ball", position: "SS", eligibility: "FR", homeState: "VA", hometown: "Virginia Beach", jerseyNumber: 1,
      hitForAvg: 57, power: 86, speed: 70, arm: 59, fielding: 54, errorResistance: 49, velocity: 0, control: 0, stamina: 30, stuff: 0,
      clutch: 47, vsLHP: 43, grit: 49, stealing: 37, running: 54, throwing: 71, recovery: 38, wRISP: 45, vsLefty: 42, poise: 45, heater: 0, agile: 57,
      abilities: ["Defensive Artisan"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Willie", lastName: "Hurt", position: "3B", eligibility: "FR", homeState: "VA", hometown: "Woodbridge", jerseyNumber: 16,
      hitForAvg: 40, power: 31, speed: 55, arm: 40, fielding: 30, errorResistance: 28, velocity: 0, control: 0, stamina: 20, stuff: 0,
      clutch: 26, vsLHP: 23, grit: 27, stealing: 17, running: 29, throwing: 46, recovery: 22, wRISP: 24, vsLefty: 22, poise: 26, heater: 0, agile: 32,
      abilities: ["Opposite Field Hitter", "Home Defense"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Eduardo", lastName: "Malinowski", position: "3B", eligibility: "SO", homeState: "VA", hometown: "Virginia Beach", jerseyNumber: 6,
      hitForAvg: 58, power: 57, speed: 55, arm: 56, fielding: 51, errorResistance: 50, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 52, vsLHP: 50, grit: 55, stealing: 24, running: 42, throwing: 68, recovery: 44, wRISP: 51, vsLefty: 47, poise: 52, heater: 0, agile: 46,
      abilities: ["Pinch Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Cole", lastName: "Cardwell", position: "2B", eligibility: "SR", homeState: "VA", hometown: "Charlottesville", jerseyNumber: 14,
      hitForAvg: 48, power: 40, speed: 67, arm: 43, fielding: 48, errorResistance: 46, velocity: 0, control: 0, stamina: 27, stuff: 0,
      clutch: 43, vsLHP: 40, grit: 44, stealing: 29, running: 41, throwing: 54, recovery: 37, wRISP: 41, vsLefty: 39, poise: 43, heater: 0, agile: 44,
      abilities: ["Chance Maker"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Nick", lastName: "Rivero", position: "1B", eligibility: "JR", homeState: "VA", hometown: "Fairfax", jerseyNumber: 15,
      hitForAvg: 40, power: 40, speed: 55, arm: 40, fielding: 30, errorResistance: 29, velocity: 0, control: 0, stamina: 19, stuff: 0,
      clutch: 30, vsLHP: 28, grit: 32, stealing: 9, running: 21, throwing: 42, recovery: 25, wRISP: 30, vsLefty: 27, poise: 30, heater: 0, agile: 23,
      abilities: ["Ace Killer"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Carson", lastName: "DeMartini", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Danville", jerseyNumber: 7,
      hitForAvg: 51, power: 47, speed: 61, arm: 47, fielding: 47, errorResistance: 46, velocity: 0, control: 0, stamina: 26, stuff: 0,
      clutch: 46, vsLHP: 43, grit: 47, stealing: 31, running: 44, throwing: 59, recovery: 39, wRISP: 44, vsLefty: 42, poise: 44, heater: 0, agile: 46,
      abilities: ["High-Speed Laser"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Gavin", lastName: "Cross", position: "OF", eligibility: "SR", homeState: "VA", hometown: "Bristol", jerseyNumber: 9,
      hitForAvg: 39, power: 37, speed: 47, arm: 35, fielding: 35, errorResistance: 34, velocity: 0, control: 0, stamina: 20, stuff: 0,
      clutch: 34, vsLHP: 32, grit: 35, stealing: 21, running: 31, throwing: 46, recovery: 29, wRISP: 34, vsLefty: 31, poise: 34, heater: 0, agile: 32,
      abilities: ["Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Ben", lastName: "Watson", position: "OF", eligibility: "SO", homeState: "VA", hometown: "Fredericksburg", jerseyNumber: 22,
      hitForAvg: 56, power: 51, speed: 63, arm: 55, fielding: 54, errorResistance: 53, velocity: 0, control: 0, stamina: 32, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 53, stealing: 36, running: 54, throwing: 68, recovery: 44, wRISP: 49, vsLefty: 45, poise: 50, heater: 0, agile: 55,
      abilities: ["Express Baserunning"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Tyler", lastName: "Johnson", position: "OF", eligibility: "JR", homeState: "VA", hometown: "Danville", jerseyNumber: 20,
      hitForAvg: 40, power: 40, speed: 58, arm: 31, fielding: 30, errorResistance: 29, velocity: 0, control: 0, stamina: 19, stuff: 0,
      clutch: 28, vsLHP: 25, grit: 29, stealing: 19, running: 29, throwing: 42, recovery: 24, wRISP: 27, vsLefty: 25, poise: 28, heater: 0, agile: 30,
      abilities: ["Defensive Artisan"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Drew", lastName: "Shelton", position: "OF", eligibility: "SR", homeState: "VA", hometown: "Manassas", jerseyNumber: 11,
      hitForAvg: 59, power: 52, speed: 62, arm: 57, fielding: 57, errorResistance: 54, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 53, vsLHP: 49, grit: 54, stealing: 30, running: 49, throwing: 68, recovery: 45, wRISP: 52, vsLefty: 48, poise: 53, heater: 0, agile: 52,
      abilities: ["Emergency Strength", "Contact Hitter", "Double Play"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Jack", lastName: "Hurley", position: "OF", eligibility: "JR", homeState: "VA", hometown: "Herndon", jerseyNumber: 8,
      hitForAvg: 51, power: 50, speed: 61, arm: 50, fielding: 48, errorResistance: 45, velocity: 0, control: 0, stamina: 29, stuff: 0,
      clutch: 45, vsLHP: 43, grit: 48, stealing: 26, running: 44, throwing: 63, recovery: 39, wRISP: 44, vsLefty: 40, poise: 45, heater: 0, agile: 45,
      abilities: ["Insurer"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
  ],

  "Wake Forest": [
    // PITCHERS (10)
    { firstName: "Blake", lastName: "Morningstar", position: "P", eligibility: "JR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 35,
      hitForAvg: 26, power: 21, speed: 35, arm: 70, fielding: 43, errorResistance: 57, velocity: 69, control: 65, stamina: 68, stuff: 67,
      clutch: 78, vsLHP: 74, grit: 80, stealing: 18, running: 41, throwing: 90, recovery: 61, wRISP: 62, vsLefty: 62, poise: 65, heater: 70, agile: 52,
      abilities: ["Star of Victory", "Strong Starter", "Intimidator", "Heavy Ball", "Winner's Luck", "Gyroball", "Quick Hands"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...pitchMix(1, [1, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Chris", lastName: "Levonas", position: "P", eligibility: "SO", homeState: "NC", hometown: "Charlotte", jerseyNumber: 29,
      hitForAvg: 18, power: 14, speed: 33, arm: 51, fielding: 30, errorResistance: 41, velocity: 55, control: 46, stamina: 48, stuff: 46,
      clutch: 55, vsLHP: 54, grit: 57, stealing: 13, running: 34, throwing: 64, recovery: 41, wRISP: 41, vsLefty: 42, poise: 43, heater: 51, agile: 41,
      abilities: ["Strong Starter", "Sharpness", "Full Throttle"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Matthew", lastName: "Dallas", position: "P", eligibility: "JR", homeState: "NC", hometown: "Greensboro", jerseyNumber: 37,
      hitForAvg: 17, power: 14, speed: 32, arm: 48, fielding: 30, errorResistance: 42, velocity: 50, control: 47, stamina: 47, stuff: 45,
      clutch: 56, vsLHP: 54, grit: 58, stealing: 13, running: 32, throwing: 63, recovery: 41, wRISP: 41, vsLefty: 42, poise: 44, heater: 48, agile: 38,
      abilities: ["Sharpness", "Wild Fastball"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Cameron", lastName: "Bagwell", position: "P", eligibility: "SO", homeState: "NC", hometown: "Wilmington", jerseyNumber: 40,
      hitForAvg: 18, power: 15, speed: 32, arm: 49, fielding: 30, errorResistance: 42, velocity: 52, control: 49, stamina: 47, stuff: 46,
      clutch: 56, vsLHP: 54, grit: 59, stealing: 13, running: 33, throwing: 64, recovery: 41, wRISP: 43, vsLefty: 43, poise: 45, heater: 49, agile: 39,
      abilities: ["Guts", "Showtime"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [1, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Troy", lastName: "Dressler", position: "P", eligibility: "JR", homeState: "NC", hometown: "Durham", jerseyNumber: 41,
      hitForAvg: 12, power: 9, speed: 29, arm: 31, fielding: 20, errorResistance: 32, velocity: 31, control: 38, stamina: 29, stuff: 28,
      clutch: 39, vsLHP: 38, grit: 41, stealing: 9, running: 23, throwing: 45, recovery: 26, wRISP: 26, vsLefty: 26, poise: 28, heater: 31, agile: 28,
      abilities: ["Fireman"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Will", lastName: "Ray", position: "P", eligibility: "SR", homeState: "NC", hometown: "Winston-Salem", jerseyNumber: 44,
      hitForAvg: 17, power: 14, speed: 32, arm: 44, fielding: 27, errorResistance: 40, velocity: 50, control: 42, stamina: 42, stuff: 41,
      clutch: 54, vsLHP: 51, grit: 56, stealing: 11, running: 29, throwing: 57, recovery: 38, wRISP: 38, vsLefty: 38, poise: 41, heater: 44, agile: 35,
      abilities: ["Guts", "Tunneling"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Josh", lastName: "Hartle", position: "P", eligibility: "JR", homeState: "NC", hometown: "High Point", jerseyNumber: 31,
      hitForAvg: 11, power: 9, speed: 30, arm: 25, fielding: 17, errorResistance: 29, velocity: 39, control: 25, stamina: 23, stuff: 30,
      clutch: 35, vsLHP: 34, grit: 37, stealing: 9, running: 21, throwing: 40, recovery: 21, wRISP: 21, vsLefty: 21, poise: 23, heater: 25, agile: 25,
      abilities: ["High Spin Gyroball"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 0, 3, 4, 4]) },
    { firstName: "Teddy", lastName: "McGraw", position: "P", eligibility: "SO", homeState: "NC", hometown: "Asheville", jerseyNumber: 46,
      hitForAvg: 12, power: 10, speed: 31, arm: 29, fielding: 18, errorResistance: 31, velocity: 42, control: 27, stamina: 25, stuff: 30,
      clutch: 36, vsLHP: 35, grit: 38, stealing: 10, running: 26, throwing: 43, recovery: 23, wRISP: 22, vsLefty: 23, poise: 24, heater: 29, agile: 30,
      abilities: ["Halting Quickness", "Cowardly"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    { firstName: "Ryan", lastName: "Brennecke", position: "P", eligibility: "FR", homeState: "NC", hometown: "Cary", jerseyNumber: 48,
      hitForAvg: 11, power: 8, speed: 31, arm: 32, fielding: 17, errorResistance: 28, velocity: 43, control: 25, stamina: 23, stuff: 30,
      clutch: 31, vsLHP: 30, grit: 33, stealing: 11, running: 28, throwing: 48, recovery: 20, wRISP: 19, vsLefty: 21, poise: 20, heater: 32, agile: 33,
      abilities: ["Release"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 3]) },
    { firstName: "Brandon", lastName: "Reitz", position: "P", eligibility: "FR", homeState: "NC", hometown: "Apex", jerseyNumber: 49,
      hitForAvg: 11, power: 8, speed: 31, arm: 28, fielding: 16, errorResistance: 28, velocity: 42, control: 21, stamina: 19, stuff: 30,
      clutch: 29, vsLHP: 28, grit: 31, stealing: 11, running: 26, throwing: 45, recovery: 18, wRISP: 17, vsLefty: 19, poise: 18, heater: 28, agile: 31,
      abilities: ["Poker Face", "Explosive Fastball"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
    // CATCHERS (2)
    { firstName: "Jimmy", lastName: "Keenan", position: "C", eligibility: "SR", homeState: "NJ", hometown: "Toms River", jerseyNumber: 12,
      hitForAvg: 52, power: 50, speed: 37, arm: 51, fielding: 48, errorResistance: 47, velocity: 0, control: 0, stamina: 30, stuff: 0,
      clutch: 48, vsLHP: 45, grit: 51, stealing: 14, running: 27, throwing: 63, recovery: 39, wRISP: 48, vsLefty: 44, poise: 49, heater: 0, agile: 32,
      abilities: ["Consigliere"], potential: "B+", catcherAbility: 49,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Davis", lastName: "Sharpe", position: "C", eligibility: "FR", homeState: "NC", hometown: "Pinehurst", jerseyNumber: 24,
      hitForAvg: 40, power: 35, speed: 36, arm: 46, fielding: 41, errorResistance: 37, velocity: 0, control: 0, stamina: 25, stuff: 0,
      clutch: 33, vsLHP: 30, grit: 34, stealing: 10, running: 25, throwing: 54, recovery: 30, wRISP: 32, vsLefty: 28, poise: 33, heater: 0, agile: 28,
      abilities: ["Multi-Hit", "Slap Happy", "Contact Hitter"], potential: "B+", catcherAbility: 43,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Kade", lastName: "Lewis", position: "1B", eligibility: "JR", homeState: "NC", hometown: "Davidson", jerseyNumber: 23,
      hitForAvg: 56, power: 61, speed: 55, arm: 46, fielding: 47, errorResistance: 46, velocity: 0, control: 0, stamina: 29, stuff: 0,
      clutch: 53, vsLHP: 49, grit: 54, stealing: 13, running: 32, throwing: 57, recovery: 41, wRISP: 54, vsLefty: 47, poise: 50, heater: 0, agile: 35,
      abilities: ["Power Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...noPitches },
    { firstName: "Austin", lastName: "Hawke", position: "2B", eligibility: "SR", homeState: "NC", hometown: "Concord", jerseyNumber: 8,
      hitForAvg: 58, power: 46, speed: 69, arm: 51, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 31, stuff: 0,
      clutch: 53, vsLHP: 49, grit: 54, stealing: 34, running: 48, throwing: 63, recovery: 44, wRISP: 51, vsLefty: 48, poise: 53, heater: 0, agile: 51,
      abilities: ["Chance Maker"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Dalton", lastName: "Wentz", position: "SS", eligibility: "JR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 3,
      hitForAvg: 55, power: 87, speed: 69, arm: 56, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 31, stuff: 0,
      clutch: 51, vsLHP: 47, grit: 52, stealing: 33, running: 48, throwing: 68, recovery: 42, wRISP: 48, vsLefty: 46, poise: 51, heater: 0, agile: 52,
      abilities: ["Late Night Hero", "Contact Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Blake", lastName: "Schaaf", position: "3B", eligibility: "JR", homeState: "DC", hometown: "Washington", jerseyNumber: 14,
      hitForAvg: 62, power: 49, speed: 55, arm: 52, fielding: 50, errorResistance: 49, velocity: 0, control: 0, stamina: 29, stuff: 0,
      clutch: 52, vsLHP: 49, grit: 53, stealing: 21, running: 39, throwing: 63, recovery: 42, wRISP: 53, vsLefty: 47, poise: 52, heater: 0, agile: 42,
      abilities: ["Contact Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Tyler", lastName: "Figueroa", position: "2B", eligibility: "JR", homeState: "FL", hometown: "Orlando", jerseyNumber: 6,
      hitForAvg: 40, power: 30, speed: 66, arm: 31, fielding: 40, errorResistance: 31, velocity: 0, control: 0, stamina: 19, stuff: 0,
      clutch: 30, vsLHP: 28, grit: 31, stealing: 19, running: 29, throwing: 42, recovery: 26, wRISP: 29, vsLefty: 27, poise: 30, heater: 0, agile: 31,
      abilities: ["Consigliere", "Magician"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "JD", lastName: "Stein", position: "SS", eligibility: "FR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 2,
      hitForAvg: 54, power: 45, speed: 69, arm: 55, fielding: 49, errorResistance: 47, velocity: 0, control: 0, stamina: 29, stuff: 0,
      clutch: 44, vsLHP: 41, grit: 47, stealing: 34, running: 52, throwing: 67, recovery: 38, wRISP: 43, vsLefty: 39, poise: 44, heater: 0, agile: 55,
      abilities: ["Defensive Artisan"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Ryan", lastName: "Caveness", position: "1B", eligibility: "FR", homeState: "NC", hometown: "Mooresville", jerseyNumber: 18,
      hitForAvg: 40, power: 40, speed: 55, arm: 40, fielding: 33, errorResistance: 30, velocity: 0, control: 0, stamina: 21, stuff: 0,
      clutch: 28, vsLHP: 25, grit: 29, stealing: 10, running: 25, throwing: 46, recovery: 24, wRISP: 28, vsLefty: 24, poise: 28, heater: 0, agile: 26,
      abilities: ["vs. Fastballs", "Final Hit"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Javar", lastName: "Williams", position: "OF", eligibility: "JR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 7,
      hitForAvg: 54, power: 48, speed: 88, arm: 50, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 29, stuff: 0,
      clutch: 48, vsLHP: 45, grit: 50, stealing: 35, running: 90, throwing: 61, recovery: 41, wRISP: 47, vsLefty: 44, poise: 48, heater: 0, agile: 50,
      abilities: ["Express Baserunning"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Luke", lastName: "Costello", position: "OF", eligibility: "JR", homeState: "NC", hometown: "Matthews", jerseyNumber: 11,
      hitForAvg: 57, power: 87, speed: 62, arm: 54, fielding: 54, errorResistance: 51, velocity: 0, control: 0, stamina: 31, stuff: 0,
      clutch: 90, vsLHP: 48, grit: 54, stealing: 33, running: 50, throwing: 65, recovery: 43, wRISP: 50, vsLefty: 46, poise: 51, heater: 0, agile: 51,
      abilities: ["Error Prone", "Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Boston", lastName: "Torres", position: "OF", eligibility: "JR", homeState: "VA", hometown: "Lexington", jerseyNumber: 9,
      hitForAvg: 55, power: 50, speed: 60, arm: 46, fielding: 45, errorResistance: 43, velocity: 0, control: 0, stamina: 27, stuff: 0,
      clutch: 48, vsLHP: 45, grit: 49, stealing: 24, running: 39, throwing: 58, recovery: 39, wRISP: 49, vsLefty: 43, poise: 46, heater: 0, agile: 41,
      abilities: ["Power Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Jay", lastName: "Miller", position: "OF", eligibility: "JR", homeState: "SC", hometown: "Greenville", jerseyNumber: 20,
      hitForAvg: 40, power: 36, speed: 50, arm: 37, fielding: 37, errorResistance: 36, velocity: 0, control: 0, stamina: 22, stuff: 0,
      clutch: 35, vsLHP: 32, grit: 36, stealing: 22, running: 35, throwing: 49, recovery: 30, wRISP: 34, vsLefty: 31, poise: 35, heater: 0, agile: 36,
      abilities: ["High Ball Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Travis", lastName: "Driscoll", position: "OF", eligibility: "SO", homeState: "NC", hometown: "Chapel Hill", jerseyNumber: 16,
      hitForAvg: 40, power: 34, speed: 58, arm: 40, fielding: 34, errorResistance: 33, velocity: 0, control: 0, stamina: 21, stuff: 0,
      clutch: 32, vsLHP: 29, grit: 33, stealing: 21, running: 33, throwing: 46, recovery: 27, wRISP: 30, vsLefty: 28, poise: 32, heater: 0, agile: 34,
      abilities: ["Slap Happy", "Timely Whiff"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Parker", lastName: "Thomas", position: "OF", eligibility: "SO", homeState: "SC", hometown: "Greenville", jerseyNumber: 19,
      hitForAvg: 36, power: 32, speed: 52, arm: 35, fielding: 34, errorResistance: 32, velocity: 0, control: 0, stamina: 21, stuff: 0,
      clutch: 30, vsLHP: 26, grit: 31, stealing: 20, running: 32, throwing: 44, recovery: 26, wRISP: 29, vsLefty: 26, poise: 30, heater: 0, agile: 34,
      abilities: ["Shock Commander"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
  ],

  "Boston College": [
      // 35-16/17-10 ACC, D1B #20, Todd Interdonato Yr 3, program-record 17 ACC W. NCAA record 8 SB in inning vs Duke.
      // PITCHERS (10) — 1-8 pitch scale
      // AJ Colarusso — Friday SR RHP, "heart and soul", 5W (6IP/7K vs Clemson), 3.40 over last 42.1 IP — TEAM ELITE STUFF
      { firstName: "AJ", lastName: "Colarusso", position: "P", eligibility: "SR", homeState: "MA", hometown: "Braintree", jerseyNumber: 34,
        hitForAvg: 16, power: 12, speed: 33, arm: 65, fielding: 41, errorResistance: 54, velocity: 69, control: 65, stamina: 69, stuff: 71,
        clutch: 80, vsLHP: 76, grit: 80, stealing: 12, running: 36, throwing: 80, recovery: 57, wRISP: 62, vsLefty: 65, poise: 65, heater: 69, agile: 44,
        abilities: ["Star of Victory", "Strong Starter", "Intimidator", "Heavy Ball", "Winner's Luck", "Pace", "Straddle"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
      // Brady Miller — Saturday LHP SO, 47 K in 45.1 IP, 2.03 ERA over last 40 IP, 6'5"
      { firstName: "Brady", lastName: "Miller", position: "P", eligibility: "SO", homeState: "MA", hometown: "Harwich", jerseyNumber: 27,
        hitForAvg: 14, power: 11, speed: 32, arm: 61, fielding: 35, errorResistance: 46, velocity: 61, control: 61, stamina: 61, stuff: 59,
        clutch: 76, vsLHP: 80, grit: 70, stealing: 8, running: 32, throwing: 74, recovery: 51, wRISP: 56, vsLefty: 64, poise: 61, heater: 61, agile: 42,
        abilities: ["Strong Starter", "Fireman", "Doctor K"], potential: "A", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [1, 0, 0, 1, 0, 0, 4]) },
      // Drew Grumbles — Sunday RHP JR (Johns Hopkins transfer), 2.66 ERA / 103 K in 91.1 IP, D3 COY 2025
      { firstName: "Drew", lastName: "Grumbles", position: "P", eligibility: "JR", homeState: "AR", hometown: "Little Rock", jerseyNumber: 24,
        hitForAvg: 13, power: 10, speed: 32, arm: 55, fielding: 33, errorResistance: 44, velocity: 57, control: 60, stamina: 56, stuff: 53,
        clutch: 66, vsLHP: 60, grit: 66, stealing: 8, running: 30, throwing: 68, recovery: 47, wRISP: 47, vsLefty: 47, poise: 52, heater: 55, agile: 40,
        abilities: ["Strong Starter", "Inside Pitch", "Staredown", "Slugger Killer"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
      // Tyler Mudd — RHP, 11 GS, 3-3, 74 K in 47 IP
      { firstName: "Tyler", lastName: "Mudd", position: "P", eligibility: "JR", homeState: "MA", hometown: "Boston", jerseyNumber: 36,
        hitForAvg: 13, power: 10, speed: 32, arm: 55, fielding: 33, errorResistance: 44, velocity: 58, control: 53, stamina: 55, stuff: 55,
        clutch: 64, vsLHP: 60, grit: 64, stealing: 8, running: 30, throwing: 68, recovery: 45, wRISP: 47, vsLefty: 47, poise: 50, heater: 56, agile: 40,
        abilities: ["Strong Starter", "Doctor K"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
      // Sean Hard — RHP NJ (NY Yankees draft pick from HS, command issues but throws hard)
      { firstName: "Sean", lastName: "Hard", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Toms River", jerseyNumber: 31,
        hitForAvg: 12, power: 10, speed: 32, arm: 58, fielding: 32, errorResistance: 44, velocity: 62, control: 43, stamina: 38, stuff: 55,
        clutch: 60, vsLHP: 56, grit: 60, stealing: 8, running: 30, throwing: 72, recovery: 41, wRISP: 43, vsLefty: 45, poise: 46, heater: 61, agile: 40,
        abilities: ["Explosive Fastball", "Intimidator", "Strikeout", "Gyroball"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 0]) },
      // Gavin Soares — top RP RHP, #6 ACC RP / #34 nation
      { firstName: "Gavin", lastName: "Soares", position: "P", eligibility: "JR", homeState: "MA", hometown: "Fall River", jerseyNumber: 28,
        hitForAvg: 12, power: 10, speed: 32, arm: 58, fielding: 33, errorResistance: 44, velocity: 60, control: 56, stamina: 39, stuff: 56,
        clutch: 76, vsLHP: 70, grit: 70, stealing: 8, running: 30, throwing: 70, recovery: 44, wRISP: 55, vsLefty: 50, poise: 59, heater: 59, agile: 40,
        abilities: ["Fireman", "Doctor K"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 0]) },
      // Cesar Gonzalez — closer (15 saves)
      { firstName: "Cesar", lastName: "Gonzalez", position: "P", eligibility: "SR", homeState: "PR", hometown: "San Juan", jerseyNumber: 39,
        hitForAvg: 12, power: 10, speed: 32, arm: 58, fielding: 33, errorResistance: 44, velocity: 60, control: 55, stamina: 39, stuff: 56,
        clutch: 80, vsLHP: 70, grit: 76, stealing: 8, running: 30, throwing: 72, recovery: 44, wRISP: 59, vsLefty: 55, poise: 63, heater: 59, agile: 40,
        abilities: ["Fireman", "Decisive", "Inside Pitch", "Low Ball"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 0]) },
      // Mason Pelio — JR RHP rotation depth
      { firstName: "Mason", lastName: "Pelio", position: "P", eligibility: "JR", homeState: "MA", hometown: "Needham", jerseyNumber: 29,
        hitForAvg: 14, power: 12, speed: 32, arm: 48, fielding: 30, errorResistance: 42, velocity: 50, control: 45, stamina: 45, stuff: 44,
        clutch: 56, vsLHP: 54, grit: 58, stealing: 9, running: 32, throwing: 62, recovery: 39, wRISP: 39, vsLefty: 42, poise: 42, heater: 48, agile: 38,
        abilities: ["Guts", "Staredown", "Intimidator"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
      // Henry Leake — JR RHP RP
      { firstName: "Henry", lastName: "Leake", position: "P", eligibility: "JR", homeState: "NH", hometown: "Concord", jerseyNumber: 44,
        hitForAvg: 14, power: 12, speed: 32, arm: 50, fielding: 32, errorResistance: 46, velocity: 54, control: 49, stamina: 44, stuff: 47,
        clutch: 60, vsLHP: 56, grit: 60, stealing: 10, running: 32, throwing: 64, recovery: 43, wRISP: 43, vsLefty: 44, poise: 46, heater: 52, agile: 40,
        abilities: ["Fireman", "Fighting Spirit", "Sharpness"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
      // Trevor Shea — FR RHP
      { firstName: "Trevor", lastName: "Shea", position: "P", eligibility: "FR", homeState: "MA", hometown: "Scituate", jerseyNumber: 48,
        hitForAvg: 10, power: 8, speed: 27, arm: 31, fielding: 19, errorResistance: 29, velocity: 38, control: 26, stamina: 23, stuff: 27,
        clutch: 31, vsLHP: 29, grit: 32, stealing: 10, running: 27, throwing: 44, recovery: 20, wRISP: 20, vsLefty: 20, poise: 20, heater: 32, agile: 31,
        abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4]) },
      // CATCHERS (2)
      // Peter Burns — JR C
      { firstName: "Peter", lastName: "Burns", position: "C", eligibility: "JR", homeState: "MA", hometown: "Marshfield", jerseyNumber: 12,
        hitForAvg: 57, power: 51, speed: 38, arm: 60, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 52, vsLHP: 48, grit: 56, stealing: 18, running: 32, throwing: 70, recovery: 46, wRISP: 50, vsLefty: 46, poise: 54, heater: 0, agile: 38,
        abilities: ["High-Speed Laser", "Defensive Artisan"], potential: "B+", catcherAbility: 58,
        throwHand: "R", batHand: "S",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Dylan Kearns — FR C
      { firstName: "Dylan", lastName: "Kearns", position: "C", eligibility: "FR", homeState: "MA", hometown: "Hingham", jerseyNumber: 25,
        hitForAvg: 40, power: 35, speed: 36, arm: 46, fielding: 42, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 32, vsLHP: 28, grit: 34, stealing: 10, running: 26, throwing: 54, recovery: 32, wRISP: 30, vsLefty: 28, poise: 32, heater: 0, agile: 28,
        abilities: ["Final Hit", "Flying Start", "Contact Hitter"], potential: "B+", catcherAbility: 42,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // INFIELDERS (7)
      // Ty Mainolfi — 2B JR (Dayton transfer), 6th ACC 2B, 4-5 vs UMass Lowell
      { firstName: "Ty", lastName: "Mainolfi", position: "2B", eligibility: "JR", homeState: "OH", hometown: "Dayton", jerseyNumber: 1,
        hitForAvg: 83, power: 63, speed: 70, arm: 56, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 76, vsLHP: 70, grit: 76, stealing: 38, running: 52, throwing: 66, recovery: 46, wRISP: 76, vsLefty: 70, poise: 76, heater: 0, agile: 56,
        abilities: ["Contact Hitter", "Express Baserunning", "Chance Maker"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Nick Wang — 1B JR, 15 HRs, 7th ACC 1B
      { firstName: "Nick", lastName: "Wang", position: "1B", eligibility: "JR", homeState: "MA", hometown: "Brookline", jerseyNumber: 2,
        hitForAvg: 77, power: 88, speed: 55, arm: 56, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 70, vsLHP: 64, grit: 70, stealing: 16, running: 36, throwing: 66, recovery: 46, wRISP: 70, vsLefty: 64, poise: 70, heater: 0, agile: 42,
        abilities: ["Artist", "Power Hitter", "Consigliere"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Patrick Roche — 3B SR
      { firstName: "Patrick", lastName: "Roche", position: "3B", eligibility: "SR", homeState: "MA", hometown: "Milton", jerseyNumber: 6,
        hitForAvg: 67, power: 57, speed: 55, arm: 60, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 60, vsLHP: 56, grit: 60, stealing: 22, running: 42, throwing: 70, recovery: 46, wRISP: 60, vsLefty: 54, poise: 60, heater: 0, agile: 46,
        abilities: ["Contact Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Gunnar Johnson — INF, clutch 2-out RBI single vs Clemson
      { firstName: "Gunnar", lastName: "Johnson", position: "3B", eligibility: "JR", homeState: "MA", hometown: "Boston", jerseyNumber: 8,
        hitForAvg: 63, power: 57, speed: 55, arm: 54, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 70, vsLHP: 54, grit: 60, stealing: 24, running: 40, throwing: 64, recovery: 42, wRISP: 70, vsLefty: 54, poise: 60, heater: 0, agile: 44,
        abilities: ["Consigliere"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Eddie Park — SS FR (moved from 2B due to Mainolfi)
      { firstName: "Eddie", lastName: "Park", position: "SS", eligibility: "FR", homeState: "MA", hometown: "Cambridge", jerseyNumber: 14,
        hitForAvg: 53, power: 43, speed: 69, arm: 50, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 46, vsLHP: 42, grit: 48, stealing: 32, running: 46, throwing: 62, recovery: 40, wRISP: 44, vsLefty: 40, poise: 46, heater: 0, agile: 50,
        abilities: ["Express Baserunning"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Matt Kemp — 3B FR
      { firstName: "Matt", lastName: "Kemp", position: "3B", eligibility: "FR", homeState: "NY", hometown: "White Plains", jerseyNumber: 4,
        hitForAvg: 40, power: 35, speed: 55, arm: 40, fielding: 32, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 28, vsLHP: 24, grit: 30, stealing: 18, running: 32, throwing: 48, recovery: 26, wRISP: 26, vsLefty: 24, poise: 28, heater: 0, agile: 36,
        abilities: ["Consigliere"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Chris Donovan — SS FR
      { firstName: "Chris", lastName: "Donovan", position: "SS", eligibility: "FR", homeState: "MA", hometown: "Quincy", jerseyNumber: 18,
        hitForAvg: 35, power: 31, speed: 66, arm: 40, fielding: 40, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 26, vsLHP: 24, grit: 28, stealing: 22, running: 36, throwing: 48, recovery: 26, wRISP: 26, vsLefty: 22, poise: 26, heater: 0, agile: 38,
        abilities: ["Express Baserunning", "Contact Hitter", "Push"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // OUTFIELDERS (6)
      // Kyle Wolff — OF, 4 HR in 4 consecutive games (400-foot blast vs Clemson) — TEAM ELITE POWER
      { firstName: "Kyle", lastName: "Wolff", position: "OF", eligibility: "JR", homeState: "MA", hometown: "Newton", jerseyNumber: 5,
        hitForAvg: 83, power: 95, speed: 62, arm: 56, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 80, vsLHP: 76, grit: 80, stealing: 24, running: 46, throwing: 66, recovery: 44, wRISP: 80, vsLefty: 76, poise: 80, heater: 0, agile: 50,
        abilities: ["Artist", "Power Hitter", "Consigliere"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Julio Solier — OF, multi-hit vs Clemson
      { firstName: "Julio", lastName: "Solier", position: "OF", eligibility: "JR", homeState: "MA", hometown: "Lawrence", jerseyNumber: 10,
        hitForAvg: 67, power: 57, speed: 85, arm: 54, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 56, vsLHP: 52, grit: 58, stealing: 38, running: 90, throwing: 66, recovery: 42, wRISP: 56, vsLefty: 50, poise: 56, heater: 0, agile: 54,
        abilities: ["Express Baserunning", "Contact Hitter"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Jack Cunningham — OF JR
      { firstName: "Jack", lastName: "Cunningham", position: "OF", eligibility: "JR", homeState: "MA", hometown: "Wellesley", jerseyNumber: 7,
        hitForAvg: 44, power: 39, speed: 50, arm: 40, fielding: 40, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 38, vsLHP: 35, grit: 40, stealing: 23, running: 35, throwing: 50, recovery: 31, wRISP: 36, vsLefty: 35, poise: 38, heater: 0, agile: 36,
        abilities: ["Consigliere"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Drew Bowser — OF SO
      { firstName: "Drew", lastName: "Bowser", position: "OF", eligibility: "SO", homeState: "MA", hometown: "Plymouth", jerseyNumber: 9,
        hitForAvg: 57, power: 51, speed: 62, arm: 56, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 50, vsLHP: 46, grit: 52, stealing: 32, running: 50, throwing: 68, recovery: 42, wRISP: 48, vsLefty: 46, poise: 50, heater: 0, agile: 52,
        abilities: ["Express Baserunning"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Kody Huff — OF SR
      { firstName: "Kody", lastName: "Huff", position: "OF", eligibility: "SR", homeState: "CT", hometown: "Stamford", jerseyNumber: 11,
        hitForAvg: 53, power: 49, speed: 60, arm: 48, fielding: 48, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 46, vsLHP: 42, grit: 48, stealing: 26, running: 42, throwing: 60, recovery: 40, wRISP: 44, vsLefty: 42, poise: 46, heater: 0, agile: 44,
        abilities: ["Pull Hit"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Brett Barrera — OF SR
      { firstName: "Brett", lastName: "Barrera", position: "OF", eligibility: "SR", homeState: "MA", hometown: "Andover", jerseyNumber: 20,
        hitForAvg: 40, power: 37, speed: 47, arm: 36, fielding: 36, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 34, vsLHP: 33, grit: 34, stealing: 17, running: 31, throwing: 46, recovery: 30, wRISP: 33, vsLefty: 30, poise: 34, heater: 0, agile: 33,
        abilities: ["Trickster", "Opposite Field Hitter", "Contact Hitter"], potential: "B", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
    ],
};
