import { RealPlayer } from "./realRosters";

function pitchMix(primary: number, secondary: number[]): { pitchFB: number; pitch2S: number; pitchSL: number; pitchCB: number; pitchCH: number; pitchCT: number; pitchSNK: number; pitchSPL: number } {
  return {
    pitchFB: primary,
    pitch2S: secondary[0] || 0,
    pitchSL: secondary[1] || 0,
    pitchCB: secondary[2] || 0,
    pitchCH: secondary[3] || 0,
    pitchCT: secondary[4] || 0,
    pitchSNK: secondary[5] || 0,
    pitchSPL: secondary[6] || 0,
  };
}

const noPitches = { pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0 };

export const ACC_BATCH2_ROSTERS: Record<string, RealPlayer[]> = {
  "Miami": [
    // PITCHERS (8)
    { firstName: "Griffin", lastName: "Hugus", position: "P", eligibility: "SR", homeState: "FL", hometown: "Fort Lauderdale", jerseyNumber: 31,
      hitForAvg: 22, power: 18, speed: 40, arm: 80, fielding: 48, errorResistance: 52, velocity: 82, control: 74, stamina: 76, stuff: 80,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 15, running: 36, throwing: 78, recovery: 68, wRISP: 70, vsLefty: 70, poise: 74, heater: 80, agile: 46,
      abilities: ["Strikeout", "Strong Starter"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [1, 6, 4, 5, 0, 0, 0]) },
    { firstName: "Brian", lastName: "Walters", position: "P", eligibility: "SR", homeState: "FL", hometown: "Tampa", jerseyNumber: 35,
      hitForAvg: 20, power: 16, speed: 38, arm: 74, fielding: 46, errorResistance: 50, velocity: 76, control: 72, stamina: 70, stuff: 72,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 12, running: 34, throwing: 72, recovery: 66, wRISP: 66, vsLefty: 66, poise: 70, heater: 74, agile: 42,
      abilities: ["Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "AJ", lastName: "Ciscar", position: "P", eligibility: "SO", homeState: "FL", hometown: "Miami", jerseyNumber: 22,
      hitForAvg: 24, power: 20, speed: 44, arm: 78, fielding: 44, errorResistance: 48, velocity: 80, control: 68, stamina: 62, stuff: 76,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 16, running: 40, throwing: 76, recovery: 60, wRISP: 64, vsLefty: 64, poise: 66, heater: 78, agile: 48,
      abilities: ["Fireman", "Explosive Fastball"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 7, 0, 5, 3, 0, 0]) },
    { firstName: "Will", lastName: "Smith", position: "P", eligibility: "JR", homeState: "FL", hometown: "Orlando", jerseyNumber: 40,
      hitForAvg: 22, power: 18, speed: 42, arm: 72, fielding: 46, errorResistance: 50, velocity: 74, control: 70, stamina: 68, stuff: 70,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 14, running: 38, throwing: 70, recovery: 64, wRISP: 62, vsLefty: 62, poise: 66, heater: 72, agile: 44,
      abilities: ["Heavy Ball"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 4, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Dorn", position: "P", eligibility: "JR", homeState: "FL", hometown: "Coral Springs", jerseyNumber: 47,
      hitForAvg: 20, power: 16, speed: 40, arm: 76, fielding: 48, errorResistance: 52, velocity: 78, control: 76, stamina: 72, stuff: 74,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 14, running: 36, throwing: 74, recovery: 68, wRISP: 72, vsLefty: 70, poise: 76, heater: 76, agile: 44,
      abilities: ["Sharpness", "Pace"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [1, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Carlos", lastName: "Hernandez", position: "P", eligibility: "JR", homeState: "FL", hometown: "Hialeah", jerseyNumber: 28,
      hitForAvg: 18, power: 15, speed: 38, arm: 70, fielding: 44, errorResistance: 48, velocity: 72, control: 68, stamina: 66, stuff: 68,
      clutch: 60, vsLHP: 58, grit: 64, stealing: 12, running: 34, throwing: 68, recovery: 62, wRISP: 58, vsLefty: 60, poise: 64, heater: 70, agile: 42,
      abilities: ["Low Ball"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Marcus", lastName: "Rivera", position: "P", eligibility: "SO", homeState: "FL", hometown: "Pembroke Pines", jerseyNumber: 33,
      hitForAvg: 20, power: 16, speed: 42, arm: 68, fielding: 42, errorResistance: 46, velocity: 74, control: 64, stamina: 60, stuff: 66,
      clutch: 56, vsLHP: 54, grit: 60, stealing: 14, running: 38, throwing: 66, recovery: 56, wRISP: 54, vsLefty: 58, poise: 58, heater: 72, agile: 44,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 0, 5, 3, 0, 0]) },
    { firstName: "Tyler", lastName: "Frazier", position: "P", eligibility: "FR", homeState: "FL", hometown: "Jacksonville", jerseyNumber: 45,
      hitForAvg: 18, power: 14, speed: 44, arm: 70, fielding: 40, errorResistance: 42, velocity: 76, control: 56, stamina: 52, stuff: 68,
      clutch: 46, vsLHP: 44, grit: 48, stealing: 16, running: 42, throwing: 68, recovery: 46, wRISP: 44, vsLefty: 48, poise: 46, heater: 74, agile: 48,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 3, 4, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Renzo", lastName: "Gonzalez", position: "C", eligibility: "JR", homeState: "FL", hometown: "Doral", jerseyNumber: 8,
      hitForAvg: 58, power: 50, speed: 40, arm: 68, fielding: 64, errorResistance: 62, velocity: 36, control: 34, stamina: 38, stuff: 30,
      clutch: 62, vsLHP: 58, grit: 66, stealing: 20, running: 38, throwing: 70, recovery: 54, wRISP: 60, vsLefty: 56, poise: 62, heater: 34, agile: 44,
      abilities: ["Iron Wall"], potential: "B+", catcherAbility: 66,
      ...noPitches },
    { firstName: "Anthony", lastName: "Vilar", position: "C", eligibility: "SO", homeState: "FL", hometown: "Kendall", jerseyNumber: 19,
      hitForAvg: 44, power: 38, speed: 36, arm: 62, fielding: 56, errorResistance: 52, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 48, vsLHP: 44, grit: 50, stealing: 16, running: 34, throwing: 60, recovery: 44, wRISP: 46, vsLefty: 42, poise: 46, heater: 32, agile: 38,
      abilities: [], potential: "B", catcherAbility: 58,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Daniel", lastName: "Cuvet", position: "3B", eligibility: "JR", homeState: "FL", hometown: "Miami", jerseyNumber: 5,
      hitForAvg: 82, power: 80, speed: 55, arm: 70, fielding: 66, errorResistance: 64, velocity: 38, control: 36, stamina: 38, stuff: 32,
      clutch: 82, vsLHP: 75, grit: 78, stealing: 30, running: 52, throwing: 72, recovery: 58, wRISP: 84, vsLefty: 74, poise: 76, heater: 34, agile: 58,
      abilities: ["Power Slugger", "Clutch Hitter"], potential: "A+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jake", lastName: "Ogden", position: "SS", eligibility: "JR", homeState: "FL", hometown: "Boca Raton", jerseyNumber: 2,
      hitForAvg: 74, power: 58, speed: 68, arm: 72, fielding: 72, errorResistance: 70, velocity: 38, control: 36, stamina: 38, stuff: 32,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 56, running: 66, throwing: 74, recovery: 56, wRISP: 68, vsLefty: 64, poise: 70, heater: 34, agile: 70,
      abilities: ["Speed Demon", "Iron Glove"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Dorian", lastName: "Gonzalez Jr", position: "2B", eligibility: "JR", homeState: "FL", hometown: "Homestead", jerseyNumber: 7,
      hitForAvg: 62, power: 64, speed: 52, arm: 62, fielding: 64, errorResistance: 62, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 66, vsLHP: 60, grit: 66, stealing: 32, running: 50, throwing: 64, recovery: 52, wRISP: 64, vsLefty: 58, poise: 64, heater: 32, agile: 54,
      abilities: ["Gap Power"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Edgardo", lastName: "Villegas", position: "1B", eligibility: "SR", homeState: "FL", hometown: "Kissimmee", jerseyNumber: 24,
      hitForAvg: 56, power: 60, speed: 40, arm: 56, fielding: 60, errorResistance: 58, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 16, running: 38, throwing: 58, recovery: 50, wRISP: 56, vsLefty: 52, poise: 58, heater: 30, agile: 42,
      abilities: ["Tough Out"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Roberto", lastName: "Perez", position: "3B", eligibility: "SO", homeState: "FL", hometown: "Weston", jerseyNumber: 14,
      hitForAvg: 48, power: 44, speed: 46, arm: 58, fielding: 54, errorResistance: 52, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 22, running: 44, throwing: 60, recovery: 46, wRISP: 48, vsLefty: 44, poise: 48, heater: 30, agile: 48,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Yohandy", lastName: "Morales", position: "SS", eligibility: "FR", homeState: "FL", hometown: "Miami Gardens", jerseyNumber: 11,
      hitForAvg: 42, power: 38, speed: 54, arm: 60, fielding: 52, errorResistance: 48, velocity: 32, control: 30, stamina: 34, stuff: 28,
      clutch: 44, vsLHP: 40, grit: 46, stealing: 34, running: 52, throwing: 62, recovery: 42, wRISP: 42, vsLefty: 38, poise: 42, heater: 28, agile: 56,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Derek", lastName: "Williams", position: "OF", eligibility: "JR", homeState: "FL", hometown: "West Palm Beach", jerseyNumber: 10,
      hitForAvg: 72, power: 60, speed: 64, arm: 68, fielding: 66, errorResistance: 64, velocity: 38, control: 36, stamina: 38, stuff: 32,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 38, running: 62, throwing: 70, recovery: 56, wRISP: 66, vsLefty: 62, poise: 68, heater: 34, agile: 66,
      abilities: ["Spray Hitter", "Laser Beam"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Max", lastName: "Galvin", position: "OF", eligibility: "SO", homeState: "OK", hometown: "Stillwater", jerseyNumber: 21,
      hitForAvg: 64, power: 56, speed: 62, arm: 66, fielding: 62, errorResistance: 60, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 40, running: 60, throwing: 68, recovery: 52, wRISP: 60, vsLefty: 56, poise: 60, heater: 32, agile: 64,
      abilities: ["Gap Power"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Lorenzo", lastName: "Gallego", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Naples", jerseyNumber: 16,
      hitForAvg: 54, power: 48, speed: 58, arm: 64, fielding: 60, errorResistance: 58, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 34, running: 56, throwing: 66, recovery: 50, wRISP: 54, vsLefty: 50, poise: 56, heater: 32, agile: 60,
      abilities: ["Table Setter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Diego", lastName: "Castillo", position: "OF", eligibility: "SO", homeState: "FL", hometown: "Coral Gables", jerseyNumber: 17,
      hitForAvg: 50, power: 42, speed: 60, arm: 60, fielding: 56, errorResistance: 54, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 38, running: 58, throwing: 62, recovery: 48, wRISP: 50, vsLefty: 46, poise: 50, heater: 30, agile: 62,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Sammy", lastName: "Dominguez", position: "OF", eligibility: "FR", homeState: "FL", hometown: "Plantation", jerseyNumber: 26,
      hitForAvg: 40, power: 36, speed: 56, arm: 58, fielding: 48, errorResistance: 44, velocity: 32, control: 30, stamina: 34, stuff: 26,
      clutch: 42, vsLHP: 38, grit: 44, stealing: 32, running: 54, throwing: 60, recovery: 40, wRISP: 40, vsLefty: 36, poise: 40, heater: 28, agile: 58,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Javier", lastName: "Santos", position: "OF", eligibility: "FR", homeState: "FL", hometown: "Aventura", jerseyNumber: 30,
      hitForAvg: 38, power: 34, speed: 54, arm: 56, fielding: 46, errorResistance: 42, velocity: 32, control: 30, stamina: 34, stuff: 26,
      clutch: 40, vsLHP: 36, grit: 42, stealing: 30, running: 52, throwing: 58, recovery: 38, wRISP: 38, vsLefty: 34, poise: 38, heater: 28, agile: 56,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "NC State": [
    // PITCHERS (8)
    { firstName: "Matt", lastName: "Willadsen", position: "P", eligibility: "SR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 34,
      hitForAvg: 24, power: 20, speed: 42, arm: 80, fielding: 50, errorResistance: 52, velocity: 80, control: 74, stamina: 78, stuff: 78,
      clutch: 72, vsLHP: 68, grit: 76, stealing: 16, running: 38, throwing: 78, recovery: 70, wRISP: 70, vsLefty: 70, poise: 76, heater: 78, agile: 46,
      abilities: ["Strong Starter", "Strikeout"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [1, 6, 4, 5, 0, 0, 0]) },
    { firstName: "Shane", lastName: "Van Dam", position: "P", eligibility: "JR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 29,
      hitForAvg: 22, power: 18, speed: 40, arm: 76, fielding: 48, errorResistance: 50, velocity: 78, control: 70, stamina: 72, stuff: 74,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 14, running: 36, throwing: 74, recovery: 64, wRISP: 64, vsLefty: 66, poise: 68, heater: 76, agile: 44,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Derrick", lastName: "Smith", position: "P", eligibility: "JR", homeState: "NC", hometown: "Durham", jerseyNumber: 41,
      hitForAvg: 20, power: 16, speed: 42, arm: 74, fielding: 46, errorResistance: 50, velocity: 76, control: 72, stamina: 70, stuff: 72,
      clutch: 64, vsLHP: 62, grit: 66, stealing: 14, running: 38, throwing: 72, recovery: 64, wRISP: 62, vsLefty: 64, poise: 68, heater: 74, agile: 46,
      abilities: ["Pace"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 5, 0, 0, 0]) },
    { firstName: "Jacob", lastName: "Dudan", position: "P", eligibility: "SO", homeState: "NC", hometown: "Cary", jerseyNumber: 38,
      hitForAvg: 20, power: 16, speed: 44, arm: 72, fielding: 44, errorResistance: 48, velocity: 76, control: 66, stamina: 64, stuff: 72,
      clutch: 58, vsLHP: 56, grit: 62, stealing: 16, running: 40, throwing: 70, recovery: 58, wRISP: 56, vsLefty: 60, poise: 60, heater: 74, agile: 48,
      abilities: ["Heavy Ball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 3, 4, 0, 0, 0]) },
    { firstName: "Cooper", lastName: "Consiglio", position: "P", eligibility: "SO", homeState: "NC", hometown: "Apex", jerseyNumber: 27,
      hitForAvg: 18, power: 15, speed: 40, arm: 70, fielding: 44, errorResistance: 48, velocity: 72, control: 68, stamina: 66, stuff: 70,
      clutch: 60, vsLHP: 58, grit: 64, stealing: 14, running: 36, throwing: 68, recovery: 60, wRISP: 58, vsLefty: 62, poise: 62, heater: 70, agile: 42,
      abilities: ["Crossfire"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Brandon", lastName: "Tate", position: "P", eligibility: "JR", homeState: "NC", hometown: "Greensboro", jerseyNumber: 44,
      hitForAvg: 18, power: 14, speed: 38, arm: 68, fielding: 44, errorResistance: 48, velocity: 70, control: 66, stamina: 64, stuff: 66,
      clutch: 58, vsLHP: 56, grit: 62, stealing: 12, running: 34, throwing: 66, recovery: 58, wRISP: 56, vsLefty: 58, poise: 60, heater: 68, agile: 40,
      abilities: ["Groundball Pitcher"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 0, 3, 0, 0]) },
    { firstName: "Cole", lastName: "Harrington", position: "P", eligibility: "SR", homeState: "NC", hometown: "Winston-Salem", jerseyNumber: 36,
      hitForAvg: 20, power: 16, speed: 40, arm: 70, fielding: 46, errorResistance: 50, velocity: 74, control: 70, stamina: 60, stuff: 68,
      clutch: 64, vsLHP: 60, grit: 68, stealing: 14, running: 36, throwing: 68, recovery: 62, wRISP: 62, vsLefty: 64, poise: 66, heater: 72, agile: 42,
      abilities: ["Fireman"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 5, 3, 0, 0]) },
    { firstName: "Drew", lastName: "Pember", position: "P", eligibility: "FR", homeState: "NC", hometown: "Wilmington", jerseyNumber: 48,
      hitForAvg: 16, power: 14, speed: 44, arm: 70, fielding: 40, errorResistance: 42, velocity: 74, control: 56, stamina: 52, stuff: 66,
      clutch: 46, vsLHP: 44, grit: 48, stealing: 16, running: 42, throwing: 68, recovery: 46, wRISP: 44, vsLefty: 48, poise: 46, heater: 72, agile: 48,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 3, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Alex", lastName: "Sosa", position: "C", eligibility: "JR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 12,
      hitForAvg: 56, power: 48, speed: 40, arm: 68, fielding: 66, errorResistance: 64, velocity: 36, control: 34, stamina: 38, stuff: 30,
      clutch: 62, vsLHP: 58, grit: 66, stealing: 18, running: 38, throwing: 70, recovery: 54, wRISP: 60, vsLefty: 56, poise: 62, heater: 34, agile: 44,
      abilities: ["Bazooka Arm"], potential: "B+", catcherAbility: 66,
      ...noPitches },
    { firstName: "Jalen", lastName: "Brooks", position: "C", eligibility: "FR", homeState: "NC", hometown: "Fayetteville", jerseyNumber: 25,
      hitForAvg: 40, power: 36, speed: 36, arm: 60, fielding: 52, errorResistance: 48, velocity: 32, control: 30, stamina: 34, stuff: 26,
      clutch: 42, vsLHP: 38, grit: 44, stealing: 14, running: 34, throwing: 58, recovery: 40, wRISP: 40, vsLefty: 36, poise: 40, heater: 30, agile: 38,
      abilities: [], potential: "B", catcherAbility: 56,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Chris", lastName: "McHugh", position: "1B", eligibility: "SR", homeState: "PA", hometown: "Philadelphia", jerseyNumber: 18,
      hitForAvg: 64, power: 66, speed: 42, arm: 58, fielding: 62, errorResistance: 60, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 16, running: 40, throwing: 60, recovery: 54, wRISP: 68, vsLefty: 62, poise: 66, heater: 32, agile: 44,
      abilities: ["Power Slugger"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Luke", lastName: "Nixon", position: "2B", eligibility: "SO", homeState: "NC", hometown: "Raleigh", jerseyNumber: 3,
      hitForAvg: 50, power: 40, speed: 52, arm: 58, fielding: 60, errorResistance: 58, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 30, running: 50, throwing: 60, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 30, agile: 54,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "Jaros", position: "SS", eligibility: "JR", homeState: "IL", hometown: "Naperville", jerseyNumber: 6,
      hitForAvg: 58, power: 46, speed: 60, arm: 66, fielding: 68, errorResistance: 66, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 38, running: 58, throwing: 68, recovery: 52, wRISP: 60, vsLefty: 56, poise: 60, heater: 32, agile: 62,
      abilities: ["Iron Glove"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Justin", lastName: "DeCriscio", position: "3B", eligibility: "SR", homeState: "NJ", hometown: "Toms River", jerseyNumber: 15,
      hitForAvg: 56, power: 52, speed: 46, arm: 62, fielding: 58, errorResistance: 56, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 22, running: 44, throwing: 64, recovery: 50, wRISP: 58, vsLefty: 54, poise: 58, heater: 32, agile: 48,
      abilities: ["Tough Out"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Caden", lastName: "Martinez", position: "2B", eligibility: "SO", homeState: "NC", hometown: "Matthews", jerseyNumber: 9,
      hitForAvg: 46, power: 38, speed: 54, arm: 56, fielding: 56, errorResistance: 54, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 48, vsLHP: 44, grit: 50, stealing: 32, running: 52, throwing: 58, recovery: 44, wRISP: 46, vsLefty: 42, poise: 46, heater: 30, agile: 56,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Ethan", lastName: "Powers", position: "1B", eligibility: "FR", homeState: "NC", hometown: "Huntersville", jerseyNumber: 23,
      hitForAvg: 42, power: 44, speed: 38, arm: 54, fielding: 50, errorResistance: 48, velocity: 32, control: 30, stamina: 34, stuff: 26,
      clutch: 44, vsLHP: 40, grit: 46, stealing: 14, running: 36, throwing: 56, recovery: 40, wRISP: 42, vsLefty: 38, poise: 42, heater: 28, agile: 40,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Josh", lastName: "Hogue", position: "OF", eligibility: "JR", homeState: "NC", hometown: "Wake Forest", jerseyNumber: 1,
      hitForAvg: 74, power: 56, speed: 66, arm: 68, fielding: 68, errorResistance: 66, velocity: 38, control: 36, stamina: 38, stuff: 32,
      clutch: 72, vsLHP: 66, grit: 72, stealing: 42, running: 64, throwing: 70, recovery: 56, wRISP: 70, vsLefty: 64, poise: 70, heater: 34, agile: 68,
      abilities: ["Contact Master", "Clutch Hitter"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Trenton", lastName: "Lyons", position: "OF", eligibility: "JR", homeState: "GA", hometown: "Marietta", jerseyNumber: 21,
      hitForAvg: 58, power: 50, speed: 62, arm: 64, fielding: 62, errorResistance: 60, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 36, running: 60, throwing: 66, recovery: 50, wRISP: 58, vsLefty: 54, poise: 58, heater: 32, agile: 64,
      abilities: ["Speed Demon"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Ty", lastName: "Head", position: "OF", eligibility: "FR", homeState: "TX", hometown: "Grapevine", jerseyNumber: 4,
      hitForAvg: 52, power: 50, speed: 64, arm: 66, fielding: 56, errorResistance: 50, velocity: 34, control: 32, stamina: 34, stuff: 28,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 40, running: 62, throwing: 68, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 30, agile: 66,
      abilities: ["Gap Power"], potential: "A+", catcherAbility: null,
      ...noPitches },
    { firstName: "Marcus", lastName: "Greer", position: "OF", eligibility: "JR", homeState: "NC", hometown: "Garner", jerseyNumber: 8,
      hitForAvg: 52, power: 44, speed: 58, arm: 62, fielding: 58, errorResistance: 56, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 34, running: 56, throwing: 64, recovery: 48, wRISP: 52, vsLefty: 48, poise: 52, heater: 30, agile: 60,
      abilities: ["Rally Monkey"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Kyle", lastName: "Andrews", position: "OF", eligibility: "SO", homeState: "NC", hometown: "Concord", jerseyNumber: 20,
      hitForAvg: 46, power: 40, speed: 56, arm: 60, fielding: 54, errorResistance: 52, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 48, vsLHP: 44, grit: 50, stealing: 30, running: 54, throwing: 62, recovery: 44, wRISP: 46, vsLefty: 42, poise: 46, heater: 30, agile: 58,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "David", lastName: "Walters", position: "OF", eligibility: "FR", homeState: "NC", hometown: "Asheville", jerseyNumber: 32,
      hitForAvg: 38, power: 34, speed: 54, arm: 58, fielding: 48, errorResistance: 44, velocity: 32, control: 30, stamina: 34, stuff: 26,
      clutch: 40, vsLHP: 36, grit: 42, stealing: 28, running: 52, throwing: 60, recovery: 38, wRISP: 38, vsLefty: 34, poise: 38, heater: 28, agile: 56,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "North Carolina": [
    // PITCHERS (8)
    { firstName: "Matthew", lastName: "Matthijs", position: "P", eligibility: "JR", homeState: "NC", hometown: "Chapel Hill", jerseyNumber: 34,
      hitForAvg: 24, power: 20, speed: 42, arm: 78, fielding: 48, errorResistance: 52, velocity: 80, control: 74, stamina: 76, stuff: 78,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 16, running: 38, throwing: 76, recovery: 68, wRISP: 68, vsLefty: 68, poise: 74, heater: 78, agile: 46,
      abilities: ["Strong Starter", "Sharpness"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [1, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Kyle", lastName: "Percival", position: "P", eligibility: "JR", homeState: "NC", hometown: "Durham", jerseyNumber: 29,
      hitForAvg: 22, power: 18, speed: 40, arm: 76, fielding: 46, errorResistance: 50, velocity: 78, control: 72, stamina: 72, stuff: 74,
      clutch: 66, vsLHP: 62, grit: 70, stealing: 14, running: 36, throwing: 74, recovery: 64, wRISP: 64, vsLefty: 64, poise: 68, heater: 76, agile: 44,
      abilities: ["Pace"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 4, 4, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Knapp", position: "P", eligibility: "SO", homeState: "NC", hometown: "Greensboro", jerseyNumber: 41,
      hitForAvg: 20, power: 16, speed: 44, arm: 74, fielding: 44, errorResistance: 48, velocity: 76, control: 68, stamina: 66, stuff: 72,
      clutch: 60, vsLHP: 58, grit: 64, stealing: 16, running: 40, throwing: 72, recovery: 60, wRISP: 58, vsLefty: 62, poise: 62, heater: 74, agile: 48,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 3, 0, 0, 0]) },
    { firstName: "Hunter", lastName: "Stokely", position: "P", eligibility: "JR", homeState: "NC", hometown: "Winston-Salem", jerseyNumber: 38,
      hitForAvg: 20, power: 16, speed: 40, arm: 72, fielding: 46, errorResistance: 50, velocity: 74, control: 70, stamina: 70, stuff: 70,
      clutch: 64, vsLHP: 62, grit: 68, stealing: 14, running: 36, throwing: 70, recovery: 64, wRISP: 62, vsLefty: 64, poise: 68, heater: 72, agile: 44,
      abilities: ["Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 4, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Lynch", position: "P", eligibility: "SO", homeState: "NC", hometown: "Raleigh", jerseyNumber: 27,
      hitForAvg: 18, power: 15, speed: 42, arm: 70, fielding: 44, errorResistance: 48, velocity: 72, control: 68, stamina: 64, stuff: 70,
      clutch: 58, vsLHP: 56, grit: 62, stealing: 14, running: 38, throwing: 68, recovery: 58, wRISP: 56, vsLefty: 62, poise: 60, heater: 70, agile: 44,
      abilities: ["Crossfire"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Bremner", position: "P", eligibility: "SR", homeState: "NC", hometown: "Cary", jerseyNumber: 44,
      hitForAvg: 20, power: 16, speed: 38, arm: 70, fielding: 46, errorResistance: 50, velocity: 74, control: 72, stamina: 62, stuff: 68,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 12, running: 34, throwing: 68, recovery: 64, wRISP: 64, vsLefty: 64, poise: 70, heater: 72, agile: 40,
      abilities: ["Fireman"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 5, 3, 0, 0]) },
    { firstName: "Jackson", lastName: "Cole", position: "P", eligibility: "JR", homeState: "VA", hometown: "Virginia Beach", jerseyNumber: 36,
      hitForAvg: 18, power: 14, speed: 40, arm: 68, fielding: 44, errorResistance: 48, velocity: 72, control: 66, stamina: 64, stuff: 66,
      clutch: 58, vsLHP: 56, grit: 62, stealing: 12, running: 36, throwing: 66, recovery: 58, wRISP: 56, vsLefty: 58, poise: 60, heater: 70, agile: 42,
      abilities: ["Low Ball"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Noah", lastName: "Pittman", position: "P", eligibility: "FR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 48,
      hitForAvg: 16, power: 14, speed: 44, arm: 72, fielding: 40, errorResistance: 42, velocity: 76, control: 56, stamina: 52, stuff: 68,
      clutch: 46, vsLHP: 44, grit: 48, stealing: 16, running: 42, throwing: 70, recovery: 46, wRISP: 44, vsLefty: 48, poise: 46, heater: 74, agile: 48,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 6, 3, 4, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Macon", lastName: "Winslow", position: "C", eligibility: "JR", homeState: "NC", hometown: "Durham", jerseyNumber: 12,
      hitForAvg: 66, power: 60, speed: 42, arm: 72, fielding: 70, errorResistance: 68, velocity: 38, control: 36, stamina: 40, stuff: 32,
      clutch: 70, vsLHP: 64, grit: 72, stealing: 20, running: 40, throwing: 74, recovery: 56, wRISP: 72, vsLefty: 62, poise: 68, heater: 36, agile: 46,
      abilities: ["Iron Wall", "Clutch Hitter"], potential: "A-", catcherAbility: 72,
      ...noPitches },
    { firstName: "Colin", lastName: "Harper", position: "C", eligibility: "SO", homeState: "NC", hometown: "Apex", jerseyNumber: 25,
      hitForAvg: 42, power: 38, speed: 36, arm: 62, fielding: 56, errorResistance: 52, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 46, vsLHP: 42, grit: 48, stealing: 14, running: 34, throwing: 60, recovery: 42, wRISP: 44, vsLefty: 40, poise: 44, heater: 30, agile: 38,
      abilities: [], potential: "B", catcherAbility: 58,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Gavin", lastName: "Gallaher", position: "3B", eligibility: "JR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 5,
      hitForAvg: 76, power: 72, speed: 54, arm: 70, fielding: 68, errorResistance: 66, velocity: 38, control: 36, stamina: 38, stuff: 32,
      clutch: 80, vsLHP: 72, grit: 76, stealing: 28, running: 52, throwing: 72, recovery: 58, wRISP: 78, vsLefty: 70, poise: 74, heater: 34, agile: 56,
      abilities: ["Clutch Hitter", "Power Slugger"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Jake", lastName: "Schaffner", position: "SS", eligibility: "JR", homeState: "MD", hometown: "Bethesda", jerseyNumber: 2,
      hitForAvg: 62, power: 50, speed: 64, arm: 70, fielding: 70, errorResistance: 68, velocity: 38, control: 36, stamina: 38, stuff: 32,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 42, running: 62, throwing: 72, recovery: 54, wRISP: 62, vsLefty: 58, poise: 64, heater: 34, agile: 66,
      abilities: ["Iron Glove"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Erik", lastName: "Paulsen", position: "1B", eligibility: "JR", homeState: "CA", hometown: "San Clemente", jerseyNumber: 18,
      hitForAvg: 60, power: 64, speed: 42, arm: 58, fielding: 62, errorResistance: 60, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 16, running: 40, throwing: 60, recovery: 52, wRISP: 64, vsLefty: 58, poise: 62, heater: 32, agile: 44,
      abilities: ["Gap Power"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Lee", lastName: "Sowers", position: "2B", eligibility: "SO", homeState: "NC", hometown: "Raleigh", jerseyNumber: 7,
      hitForAvg: 50, power: 42, speed: 56, arm: 58, fielding: 60, errorResistance: 58, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 32, running: 54, throwing: 60, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 30, agile: 58,
      abilities: ["Table Setter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Grant", lastName: "Massey", position: "3B", eligibility: "FR", homeState: "NC", hometown: "Mooresville", jerseyNumber: 14,
      hitForAvg: 42, power: 40, speed: 48, arm: 58, fielding: 50, errorResistance: 46, velocity: 32, control: 30, stamina: 34, stuff: 26,
      clutch: 44, vsLHP: 40, grit: 46, stealing: 22, running: 46, throwing: 60, recovery: 40, wRISP: 42, vsLefty: 38, poise: 42, heater: 28, agile: 50,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Trey", lastName: "Morrison", position: "SS", eligibility: "FR", homeState: "NC", hometown: "Gastonia", jerseyNumber: 11,
      hitForAvg: 40, power: 36, speed: 56, arm: 62, fielding: 52, errorResistance: 48, velocity: 32, control: 30, stamina: 34, stuff: 26,
      clutch: 42, vsLHP: 38, grit: 44, stealing: 34, running: 54, throwing: 64, recovery: 38, wRISP: 40, vsLefty: 36, poise: 40, heater: 28, agile: 58,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Owen", lastName: "Hull", position: "OF", eligibility: "JR", homeState: "VA", hometown: "Richmond", jerseyNumber: 1,
      hitForAvg: 66, power: 56, speed: 66, arm: 68, fielding: 66, errorResistance: 64, velocity: 38, control: 36, stamina: 38, stuff: 32,
      clutch: 68, vsLHP: 62, grit: 68, stealing: 42, running: 64, throwing: 70, recovery: 54, wRISP: 66, vsLefty: 60, poise: 66, heater: 34, agile: 68,
      abilities: ["Spray Hitter", "Speed Demon"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Sawyer", lastName: "Black", position: "OF", eligibility: "SO", homeState: "NC", hometown: "Cornelius", jerseyNumber: 21,
      hitForAvg: 56, power: 48, speed: 62, arm: 64, fielding: 60, errorResistance: 58, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 36, running: 60, throwing: 66, recovery: 50, wRISP: 56, vsLefty: 52, poise: 56, heater: 32, agile: 64,
      abilities: ["Base Burglar"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Perry", lastName: "Hargett", position: "OF", eligibility: "SO", homeState: "NC", hometown: "Wilmington", jerseyNumber: 16,
      hitForAvg: 54, power: 46, speed: 60, arm: 62, fielding: 58, errorResistance: 56, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 34, running: 58, throwing: 64, recovery: 48, wRISP: 54, vsLefty: 50, poise: 54, heater: 32, agile: 62,
      abilities: ["Rally Monkey"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Mason", lastName: "Forbes", position: "OF", eligibility: "JR", homeState: "NC", hometown: "Greensboro", jerseyNumber: 10,
      hitForAvg: 52, power: 44, speed: 58, arm: 62, fielding: 58, errorResistance: 56, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 32, running: 56, throwing: 64, recovery: 48, wRISP: 52, vsLefty: 48, poise: 52, heater: 30, agile: 60,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Brandon", lastName: "Vance", position: "OF", eligibility: "FR", homeState: "NC", hometown: "Fayetteville", jerseyNumber: 24,
      hitForAvg: 40, power: 36, speed: 56, arm: 58, fielding: 48, errorResistance: 44, velocity: 32, control: 30, stamina: 34, stuff: 26,
      clutch: 42, vsLHP: 38, grit: 44, stealing: 30, running: 54, throwing: 60, recovery: 38, wRISP: 40, vsLefty: 36, poise: 40, heater: 28, agile: 58,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Cam", lastName: "Padgett", position: "OF", eligibility: "SO", homeState: "SC", hometown: "Rock Hill", jerseyNumber: 30,
      hitForAvg: 48, power: 42, speed: 58, arm: 60, fielding: 56, errorResistance: 54, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 32, running: 56, throwing: 62, recovery: 46, wRISP: 48, vsLefty: 44, poise: 48, heater: 30, agile: 60,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "Notre Dame": [
    // PITCHERS (8)
    { firstName: "Liam", lastName: "Simon", position: "P", eligibility: "JR", homeState: "IL", hometown: "Naperville", jerseyNumber: 34,
      hitForAvg: 24, power: 20, speed: 42, arm: 80, fielding: 48, errorResistance: 52, velocity: 82, control: 74, stamina: 76, stuff: 80,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 16, running: 38, throwing: 78, recovery: 68, wRISP: 70, vsLefty: 70, poise: 76, heater: 80, agile: 46,
      abilities: ["Strong Starter", "Explosive Fastball"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [1, 6, 4, 5, 0, 0, 0]) },
    { firstName: "Aidan", lastName: "Tyrell", position: "P", eligibility: "SR", homeState: "CA", hometown: "Huntington Beach", jerseyNumber: 29,
      hitForAvg: 22, power: 18, speed: 40, arm: 76, fielding: 48, errorResistance: 52, velocity: 76, control: 74, stamina: 74, stuff: 74,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 14, running: 36, throwing: 74, recovery: 68, wRISP: 68, vsLefty: 68, poise: 74, heater: 74, agile: 42,
      abilities: ["Crossfire", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Radek", lastName: "Birkholz", position: "P", eligibility: "SO", homeState: "IL", hometown: "Glenview", jerseyNumber: 41,
      hitForAvg: 20, power: 16, speed: 44, arm: 74, fielding: 44, errorResistance: 48, velocity: 78, control: 66, stamina: 64, stuff: 74,
      clutch: 58, vsLHP: 56, grit: 62, stealing: 16, running: 40, throwing: 72, recovery: 58, wRISP: 56, vsLefty: 60, poise: 60, heater: 76, agile: 48,
      abilities: ["Heavy Ball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 3, 5, 0, 0, 0]) },
    { firstName: "Jack", lastName: "Findlay", position: "P", eligibility: "JR", homeState: "OH", hometown: "Columbus", jerseyNumber: 38,
      hitForAvg: 22, power: 18, speed: 40, arm: 74, fielding: 46, errorResistance: 50, velocity: 76, control: 72, stamina: 72, stuff: 72,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 14, running: 36, throwing: 72, recovery: 64, wRISP: 64, vsLefty: 64, poise: 68, heater: 74, agile: 44,
      abilities: ["Sharpness"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 4, 0, 0, 0]) },
    { firstName: "Roman", lastName: "Kimball", position: "P", eligibility: "JR", homeState: "IN", hometown: "Carmel", jerseyNumber: 27,
      hitForAvg: 18, power: 15, speed: 40, arm: 70, fielding: 44, errorResistance: 48, velocity: 74, control: 70, stamina: 66, stuff: 70,
      clutch: 62, vsLHP: 60, grit: 66, stealing: 14, running: 36, throwing: 68, recovery: 62, wRISP: 60, vsLefty: 62, poise: 64, heater: 72, agile: 42,
      abilities: ["Pace"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Will", lastName: "Mercer", position: "P", eligibility: "SO", homeState: "IN", hometown: "Fishers", jerseyNumber: 44,
      hitForAvg: 18, power: 14, speed: 42, arm: 68, fielding: 42, errorResistance: 46, velocity: 72, control: 64, stamina: 62, stuff: 66,
      clutch: 56, vsLHP: 54, grit: 60, stealing: 14, running: 38, throwing: 66, recovery: 56, wRISP: 54, vsLefty: 58, poise: 58, heater: 70, agile: 44,
      abilities: ["Groundball Pitcher"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Connor", lastName: "Walsh", position: "P", eligibility: "SR", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 36,
      hitForAvg: 20, power: 16, speed: 38, arm: 70, fielding: 46, errorResistance: 50, velocity: 74, control: 72, stamina: 60, stuff: 68,
      clutch: 66, vsLHP: 62, grit: 70, stealing: 12, running: 34, throwing: 68, recovery: 64, wRISP: 64, vsLefty: 64, poise: 70, heater: 72, agile: 40,
      abilities: ["Fireman"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 5, 3, 0, 0]) },
    { firstName: "Brendan", lastName: "Doyle", position: "P", eligibility: "FR", homeState: "IL", hometown: "Hinsdale", jerseyNumber: 48,
      hitForAvg: 16, power: 14, speed: 44, arm: 72, fielding: 40, errorResistance: 42, velocity: 76, control: 56, stamina: 52, stuff: 68,
      clutch: 46, vsLHP: 44, grit: 48, stealing: 16, running: 42, throwing: 70, recovery: 46, wRISP: 44, vsLefty: 48, poise: 46, heater: 74, agile: 48,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 4, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Carter", lastName: "Putz", position: "C", eligibility: "JR", homeState: "IN", hometown: "South Bend", jerseyNumber: 12,
      hitForAvg: 60, power: 54, speed: 40, arm: 70, fielding: 68, errorResistance: 66, velocity: 38, control: 36, stamina: 40, stuff: 32,
      clutch: 66, vsLHP: 62, grit: 70, stealing: 18, running: 38, throwing: 72, recovery: 56, wRISP: 66, vsLefty: 60, poise: 66, heater: 36, agile: 44,
      abilities: ["The Almanac"], potential: "A-", catcherAbility: 70,
      ...noPitches },
    { firstName: "Michael", lastName: "O'Brien", position: "C", eligibility: "SO", homeState: "IL", hometown: "Wheaton", jerseyNumber: 25,
      hitForAvg: 42, power: 38, speed: 36, arm: 62, fielding: 56, errorResistance: 52, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 46, vsLHP: 42, grit: 48, stealing: 14, running: 34, throwing: 60, recovery: 42, wRISP: 44, vsLefty: 40, poise: 44, heater: 30, agile: 38,
      abilities: [], potential: "B", catcherAbility: 58,
      ...noPitches },
    // INFIELDERS (5)
    { firstName: "David", lastName: "LaManna", position: "2B", eligibility: "SR", homeState: "IL", hometown: "Barrington", jerseyNumber: 6,
      hitForAvg: 66, power: 48, speed: 56, arm: 62, fielding: 68, errorResistance: 66, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 68, vsLHP: 64, grit: 72, stealing: 36, running: 54, throwing: 64, recovery: 54, wRISP: 66, vsLefty: 62, poise: 68, heater: 32, agile: 58,
      abilities: ["Contact Master", "Table Setter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Danny", lastName: "Neri", position: "SS", eligibility: "JR", homeState: "OH", hometown: "Cleveland", jerseyNumber: 2,
      hitForAvg: 62, power: 52, speed: 62, arm: 70, fielding: 70, errorResistance: 68, velocity: 38, control: 36, stamina: 38, stuff: 32,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 40, running: 60, throwing: 72, recovery: 54, wRISP: 62, vsLefty: 58, poise: 64, heater: 34, agile: 64,
      abilities: ["Iron Glove"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Luke", lastName: "Hanson", position: "1B", eligibility: "JR", homeState: "IN", hometown: "Indianapolis", jerseyNumber: 18,
      hitForAvg: 58, power: 62, speed: 40, arm: 56, fielding: 60, errorResistance: 58, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 16, running: 38, throwing: 58, recovery: 50, wRISP: 62, vsLefty: 56, poise: 60, heater: 32, agile: 42,
      abilities: ["Power Slugger"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Sean", lastName: "Cullen", position: "3B", eligibility: "SO", homeState: "OH", hometown: "Dublin", jerseyNumber: 15,
      hitForAvg: 50, power: 46, speed: 48, arm: 60, fielding: 56, errorResistance: 54, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 24, running: 46, throwing: 62, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 30, agile: 50,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Patrick", lastName: "Driscoll", position: "2B", eligibility: "FR", homeState: "IL", hometown: "Park Ridge", jerseyNumber: 9,
      hitForAvg: 40, power: 36, speed: 54, arm: 56, fielding: 52, errorResistance: 48, velocity: 32, control: 30, stamina: 34, stuff: 26,
      clutch: 42, vsLHP: 38, grit: 44, stealing: 30, running: 52, throwing: 58, recovery: 40, wRISP: 40, vsLefty: 36, poise: 40, heater: 28, agile: 56,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (5)
    { firstName: "Jack", lastName: "Radel", position: "OF", eligibility: "JR", homeState: "IN", hometown: "Zionsville", jerseyNumber: 1,
      hitForAvg: 78, power: 70, speed: 68, arm: 72, fielding: 72, errorResistance: 70, velocity: 40, control: 38, stamina: 40, stuff: 34,
      clutch: 78, vsLHP: 72, grit: 76, stealing: 44, running: 66, throwing: 74, recovery: 58, wRISP: 76, vsLefty: 70, poise: 74, heater: 36, agile: 70,
      abilities: ["Power Slugger", "Clutch Hitter"], potential: "A+", catcherAbility: null,
      ...noPitches },
    { firstName: "Brooks", lastName: "Ey", position: "OF", eligibility: "SR", homeState: "OH", hometown: "Toledo", jerseyNumber: 10,
      hitForAvg: 64, power: 54, speed: 60, arm: 66, fielding: 64, errorResistance: 62, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 36, running: 58, throwing: 68, recovery: 54, wRISP: 64, vsLefty: 60, poise: 66, heater: 32, agile: 62,
      abilities: ["Laser Beam"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "TJ", lastName: "Williams", position: "OF", eligibility: "SO", homeState: "IN", hometown: "Fort Wayne", jerseyNumber: 21,
      hitForAvg: 54, power: 48, speed: 64, arm: 64, fielding: 60, errorResistance: 58, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 40, running: 62, throwing: 66, recovery: 48, wRISP: 54, vsLefty: 50, poise: 54, heater: 32, agile: 66,
      abilities: ["Speed Demon"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "McAllister", position: "OF", eligibility: "JR", homeState: "OH", hometown: "Akron", jerseyNumber: 16,
      hitForAvg: 52, power: 44, speed: 58, arm: 62, fielding: 58, errorResistance: 56, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 32, running: 56, throwing: 64, recovery: 48, wRISP: 52, vsLefty: 48, poise: 52, heater: 30, agile: 60,
      abilities: ["Spray Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Ethan", lastName: "Mueller", position: "OF", eligibility: "FR", homeState: "IN", hometown: "Granger", jerseyNumber: 24,
      hitForAvg: 40, power: 38, speed: 56, arm: 60, fielding: 48, errorResistance: 44, velocity: 32, control: 30, stamina: 34, stuff: 26,
      clutch: 42, vsLHP: 38, grit: 44, stealing: 30, running: 54, throwing: 62, recovery: 38, wRISP: 40, vsLefty: 36, poise: 40, heater: 28, agile: 58,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Kevin", lastName: "Heller", position: "3B", eligibility: "FR", homeState: "OH", hometown: "Dayton", jerseyNumber: 23,
      hitForAvg: 42, power: 40, speed: 46, arm: 58, fielding: 50, errorResistance: 46, velocity: 32, control: 30, stamina: 34, stuff: 26,
      clutch: 44, vsLHP: 40, grit: 46, stealing: 20, running: 44, throwing: 60, recovery: 40, wRISP: 42, vsLefty: 38, poise: 42, heater: 28, agile: 48,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Matt", lastName: "Brogan", position: "1B", eligibility: "SO", homeState: "IL", hometown: "Downers Grove", jerseyNumber: 30,
      hitForAvg: 48, power: 52, speed: 38, arm: 54, fielding: 54, errorResistance: 52, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 14, running: 36, throwing: 56, recovery: 44, wRISP: 48, vsLefty: 44, poise: 48, heater: 30, agile: 40,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "Pittsburgh": [
    // PITCHERS (8)
    { firstName: "Drew", lastName: "Lafferty", position: "P", eligibility: "JR", homeState: "PA", hometown: "Pittsburgh", jerseyNumber: 34,
      hitForAvg: 24, power: 20, speed: 42, arm: 78, fielding: 48, errorResistance: 52, velocity: 80, control: 72, stamina: 74, stuff: 76,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 16, running: 38, throwing: 76, recovery: 66, wRISP: 66, vsLefty: 66, poise: 70, heater: 78, agile: 46,
      abilities: ["Strong Starter", "Pace"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [1, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Patrick", lastName: "Gardner", position: "P", eligibility: "SR", homeState: "NY", hometown: "Staten Island", jerseyNumber: 29,
      hitForAvg: 22, power: 18, speed: 40, arm: 74, fielding: 48, errorResistance: 52, velocity: 74, control: 74, stamina: 72, stuff: 72,
      clutch: 70, vsLHP: 66, grit: 74, stealing: 14, running: 36, throwing: 72, recovery: 68, wRISP: 68, vsLefty: 68, poise: 74, heater: 72, agile: 42,
      abilities: ["Crossfire", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Kyle", lastName: "Demi", position: "P", eligibility: "SR", homeState: "PA", hometown: "Wexford", jerseyNumber: 41,
      hitForAvg: 20, power: 16, speed: 40, arm: 72, fielding: 46, errorResistance: 50, velocity: 76, control: 72, stamina: 70, stuff: 72,
      clutch: 66, vsLHP: 62, grit: 70, stealing: 14, running: 36, throwing: 70, recovery: 66, wRISP: 64, vsLefty: 64, poise: 70, heater: 74, agile: 42,
      abilities: ["Heavy Ball"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 4, 0, 0, 0]) },
    { firstName: "Dylan", lastName: "Venturini", position: "P", eligibility: "SO", homeState: "NV", hometown: "Las Vegas", jerseyNumber: 38,
      hitForAvg: 20, power: 16, speed: 44, arm: 74, fielding: 44, errorResistance: 48, velocity: 78, control: 66, stamina: 64, stuff: 74,
      clutch: 58, vsLHP: 56, grit: 62, stealing: 16, running: 40, throwing: 72, recovery: 58, wRISP: 56, vsLefty: 60, poise: 60, heater: 76, agile: 48,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 3, 5, 0, 0, 0]) },
    { firstName: "Antonio", lastName: "Doganiero", position: "P", eligibility: "FR", homeState: "PA", hometown: "Erie", jerseyNumber: 27,
      hitForAvg: 18, power: 14, speed: 44, arm: 70, fielding: 40, errorResistance: 42, velocity: 74, control: 58, stamina: 54, stuff: 68,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 16, running: 42, throwing: 68, recovery: 48, wRISP: 46, vsLefty: 50, poise: 48, heater: 72, agile: 48,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 4, 0, 0, 0]) },
    { firstName: "Matt", lastName: "Kowalski", position: "P", eligibility: "JR", homeState: "PA", hometown: "Allentown", jerseyNumber: 44,
      hitForAvg: 18, power: 14, speed: 38, arm: 68, fielding: 44, errorResistance: 48, velocity: 72, control: 68, stamina: 66, stuff: 66,
      clutch: 60, vsLHP: 58, grit: 64, stealing: 12, running: 34, throwing: 66, recovery: 60, wRISP: 58, vsLefty: 60, poise: 62, heater: 70, agile: 40,
      abilities: ["Low Ball"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Barker", position: "P", eligibility: "SR", homeState: "PA", hometown: "Scranton", jerseyNumber: 36,
      hitForAvg: 20, power: 16, speed: 38, arm: 70, fielding: 46, errorResistance: 50, velocity: 74, control: 70, stamina: 60, stuff: 68,
      clutch: 64, vsLHP: 60, grit: 68, stealing: 12, running: 34, throwing: 68, recovery: 62, wRISP: 62, vsLefty: 62, poise: 68, heater: 72, agile: 40,
      abilities: ["Fireman"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 5, 3, 0, 0]) },
    { firstName: "Trevor", lastName: "Phelps", position: "P", eligibility: "SO", homeState: "PA", hometown: "Bethlehem", jerseyNumber: 48,
      hitForAvg: 18, power: 14, speed: 42, arm: 66, fielding: 42, errorResistance: 46, velocity: 70, control: 64, stamina: 60, stuff: 64,
      clutch: 54, vsLHP: 52, grit: 58, stealing: 14, running: 38, throwing: 64, recovery: 54, wRISP: 52, vsLefty: 56, poise: 56, heater: 68, agile: 44,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 3, 4, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Sebastian", lastName: "Pisacreta", position: "C", eligibility: "JR", homeState: "PA", hometown: "Philadelphia", jerseyNumber: 12,
      hitForAvg: 56, power: 50, speed: 38, arm: 68, fielding: 66, errorResistance: 64, velocity: 36, control: 34, stamina: 38, stuff: 30,
      clutch: 62, vsLHP: 58, grit: 66, stealing: 18, running: 36, throwing: 70, recovery: 54, wRISP: 60, vsLefty: 56, poise: 62, heater: 34, agile: 42,
      abilities: ["Iron Wall"], potential: "B+", catcherAbility: 66,
      ...noPitches },
    { firstName: "Nick", lastName: "Santoro", position: "C", eligibility: "FR", homeState: "PA", hometown: "Greensburg", jerseyNumber: 25,
      hitForAvg: 38, power: 34, speed: 34, arm: 58, fielding: 50, errorResistance: 46, velocity: 32, control: 30, stamina: 34, stuff: 26,
      clutch: 40, vsLHP: 36, grit: 42, stealing: 12, running: 32, throwing: 56, recovery: 38, wRISP: 38, vsLefty: 34, poise: 38, heater: 28, agile: 36,
      abilities: [], potential: "B", catcherAbility: 55,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Caden", lastName: "Dulin", position: "2B", eligibility: "JR", homeState: "NJ", hometown: "Williamstown", jerseyNumber: 6,
      hitForAvg: 58, power: 46, speed: 56, arm: 62, fielding: 66, errorResistance: 64, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 34, running: 54, throwing: 64, recovery: 52, wRISP: 60, vsLefty: 56, poise: 60, heater: 32, agile: 58,
      abilities: ["Table Setter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jake", lastName: "Kendro", position: "SS", eligibility: "JR", homeState: "PA", hometown: "Pittsburgh", jerseyNumber: 2,
      hitForAvg: 60, power: 48, speed: 62, arm: 68, fielding: 70, errorResistance: 68, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 40, running: 60, throwing: 70, recovery: 54, wRISP: 62, vsLefty: 58, poise: 62, heater: 32, agile: 64,
      abilities: ["Iron Glove"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Gavin", lastName: "Miller", position: "3B", eligibility: "JR", homeState: "PA", hometown: "Pittsburgh", jerseyNumber: 15,
      hitForAvg: 56, power: 54, speed: 48, arm: 64, fielding: 58, errorResistance: 56, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 24, running: 46, throwing: 66, recovery: 50, wRISP: 58, vsLefty: 54, poise: 58, heater: 32, agile: 50,
      abilities: ["Gap Power"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Tony", lastName: "Bello", position: "1B", eligibility: "SR", homeState: "PA", hometown: "Harrisburg", jerseyNumber: 18,
      hitForAvg: 54, power: 58, speed: 40, arm: 56, fielding: 60, errorResistance: 58, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 14, running: 38, throwing: 58, recovery: 48, wRISP: 56, vsLefty: 52, poise: 56, heater: 30, agile: 42,
      abilities: ["Tough Out"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Brian", lastName: "Zapp", position: "2B", eligibility: "SO", homeState: "PA", hometown: "State College", jerseyNumber: 9,
      hitForAvg: 46, power: 38, speed: 52, arm: 56, fielding: 58, errorResistance: 56, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 48, vsLHP: 44, grit: 50, stealing: 28, running: 50, throwing: 58, recovery: 44, wRISP: 46, vsLefty: 42, poise: 46, heater: 30, agile: 54,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Dylan", lastName: "Shook", position: "SS", eligibility: "FR", homeState: "PA", hometown: "Lancaster", jerseyNumber: 11,
      hitForAvg: 40, power: 36, speed: 56, arm: 60, fielding: 52, errorResistance: 48, velocity: 32, control: 30, stamina: 34, stuff: 26,
      clutch: 42, vsLHP: 38, grit: 44, stealing: 32, running: 54, throwing: 62, recovery: 38, wRISP: 40, vsLefty: 36, poise: 40, heater: 28, agile: 58,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "AJ", lastName: "Nessler", position: "OF", eligibility: "SR", homeState: "PA", hometown: "Moon Township", jerseyNumber: 1,
      hitForAvg: 68, power: 62, speed: 62, arm: 70, fielding: 68, errorResistance: 66, velocity: 38, control: 36, stamina: 38, stuff: 32,
      clutch: 72, vsLHP: 66, grit: 72, stealing: 38, running: 60, throwing: 72, recovery: 56, wRISP: 70, vsLefty: 64, poise: 70, heater: 34, agile: 64,
      abilities: ["Clutch Hitter", "Laser Beam"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Derrick", lastName: "Tarpley Jr", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Tampa", jerseyNumber: 10,
      hitForAvg: 62, power: 54, speed: 64, arm: 66, fielding: 64, errorResistance: 62, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 40, running: 62, throwing: 68, recovery: 52, wRISP: 62, vsLefty: 58, poise: 62, heater: 32, agile: 66,
      abilities: ["Speed Demon"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Lorenzo", lastName: "Carrier", position: "OF", eligibility: "SO", homeState: "GA", hometown: "Atlanta", jerseyNumber: 21,
      hitForAvg: 54, power: 48, speed: 62, arm: 64, fielding: 58, errorResistance: 56, velocity: 36, control: 34, stamina: 36, stuff: 30,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 38, running: 60, throwing: 66, recovery: 48, wRISP: 54, vsLefty: 50, poise: 54, heater: 32, agile: 64,
      abilities: ["Rally Monkey"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Marcus", lastName: "Garland", position: "OF", eligibility: "JR", homeState: "PA", hometown: "Reading", jerseyNumber: 16,
      hitForAvg: 50, power: 44, speed: 56, arm: 62, fielding: 56, errorResistance: 54, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 30, running: 54, throwing: 64, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 30, agile: 58,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Cole", lastName: "Mitchell", position: "OF", eligibility: "SO", homeState: "PA", hometown: "York", jerseyNumber: 24,
      hitForAvg: 46, power: 40, speed: 58, arm: 60, fielding: 54, errorResistance: 52, velocity: 34, control: 32, stamina: 36, stuff: 28,
      clutch: 48, vsLHP: 44, grit: 50, stealing: 32, running: 56, throwing: 62, recovery: 44, wRISP: 46, vsLefty: 42, poise: 46, heater: 30, agile: 60,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Justin", lastName: "Palmer", position: "OF", eligibility: "FR", homeState: "PA", hometown: "Cranberry Twp", jerseyNumber: 30,
      hitForAvg: 38, power: 34, speed: 54, arm: 58, fielding: 46, errorResistance: 42, velocity: 32, control: 30, stamina: 34, stuff: 26,
      clutch: 40, vsLHP: 36, grit: 42, stealing: 28, running: 52, throwing: 60, recovery: 38, wRISP: 38, vsLefty: 34, poise: 38, heater: 28, agile: 56,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
  ],
};
