import { RealPlayer } from "./realRosters";
import { pitchMix, noPitches } from "./pitchMixHelpers";

export const ACC_BATCH2_ROSTERS: Record<string, RealPlayer[]> = {
  "Miami": [
    // PITCHERS (8)
    { firstName: "Ryan", lastName: "Bilka", position: "P", eligibility: "JR", homeState: "VA", hometown: "Richmond", jerseyNumber: 34,
      hitForAvg: 20, power: 17, speed: 34, arm: 70, fielding: 42, errorResistance: 53, velocity: 69, control: 64, stamina: 88, stuff: 69,
      clutch: 75, vsLHP: 71, grit: 62, stealing: 12, running: 36, throwing: 78, recovery: 58, wRISP: 60, vsLefty: 60, poise: 62, heater: 62, agile: 44,
      abilities: ["Inside Pitch", "Strong Starter", "vs. Strong Batters", "Heavy Ball", "Winner's Luck", "Pace"], potential: "A", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [1, 4, 0, 0, 0, 0, 4, 1, 0, 0]) },
    { firstName: "Jake", lastName: "Dorn", position: "P", eligibility: "JR", homeState: "FL", hometown: "Fort Lauderdale", jerseyNumber: 29,
      hitForAvg: 15, power: 12, speed: 32, arm: 51, fielding: 31, errorResistance: 43, velocity: 55, control: 49, stamina: 92, stuff: 48,
      clutch: 61, vsLHP: 58, grit: 62, stealing: 12, running: 33, throwing: 64, recovery: 44, wRISP: 45, vsLefty: 45, poise: 46, heater: 51, agile: 39,
      abilities: ["Strong Starter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 4, 0, 0, 4, 0, 0, 1, 0]) },
    { firstName: "AJ", lastName: "Ciscar", position: "P", eligibility: "SO", homeState: "FL", hometown: "Orlando", jerseyNumber: 41,
      hitForAvg: 16, power: 13, speed: 33, arm: 50, fielding: 31, errorResistance: 42, velocity: 56, control: 47, stamina: 95, stuff: 47,
      clutch: 58, vsLHP: 55, grit: 60, stealing: 13, running: 36, throwing: 63, recovery: 44, wRISP: 44, vsLefty: 44, poise: 46, heater: 52, agile: 42,
      abilities: ["Fireman", "Quick Hands", "Sharpness"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 0, 0, 4, 0, 0, 4]) },
    { firstName: "TJ", lastName: "Coats", position: "P", eligibility: "JR", homeState: "FL", hometown: "Tampa", jerseyNumber: 27,
      hitForAvg: 14, power: 12, speed: 32, arm: 51, fielding: 31, errorResistance: 43, velocity: 56, control: 50, stamina: 87, stuff: 48,
      clutch: 59, vsLHP: 56, grit: 62, stealing: 11, running: 33, throwing: 65, recovery: 44, wRISP: 44, vsLefty: 44, poise: 46, heater: 51, agile: 40,
      abilities: ["Guts", "Good Pickoff"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4, 0, 0, 0]) },
    { firstName: "Tate", lastName: "DeRias", position: "P", eligibility: "SO", homeState: "FL", hometown: "Jacksonville", jerseyNumber: 38,
      hitForAvg: 16, power: 14, speed: 34, arm: 54, fielding: 33, errorResistance: 44, velocity: 60, control: 51, stamina: 51, stuff: 51,
      clutch: 60, vsLHP: 57, grit: 62, stealing: 14, running: 37, throwing: 68, recovery: 45, wRISP: 45, vsLefty: 46, poise: 46, heater: 55, agile: 44,
      abilities: ["Bad Ball Hitter", "Crossfire", "Gyroball"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 4, 0, 0, 4, 0, 0, 0, 3]) },
    { firstName: "Lyndon", lastName: "Glidewell", position: "P", eligibility: "JR", homeState: "FL", hometown: "Pembroke Pines", jerseyNumber: 44,
      hitForAvg: 10, power: 9, speed: 30, arm: 30, fielding: 18, errorResistance: 30, velocity: 44, control: 28, stamina: 37, stuff: 34,
      clutch: 39, vsLHP: 37, grit: 40, stealing: 8, running: 24, throwing: 44, recovery: 25, wRISP: 25, vsLefty: 26, poise: 26, heater: 31, agile: 28,
      abilities: ["Fireman"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 0, 3, 4, 0, 0, 1, 0]) },
    { firstName: "Marco", lastName: "Reyes", position: "P", eligibility: "FR", homeState: "FL", hometown: "Coral Gables", jerseyNumber: 48,
      hitForAvg: 9, power: 8, speed: 27, arm: 33, fielding: 19, errorResistance: 28, velocity: 39, control: 27, stamina: 34, stuff: 28,
      clutch: 31, vsLHP: 30, grit: 33, stealing: 9, running: 28, throwing: 44, recovery: 22, wRISP: 21, vsLefty: 23, poise: 22, heater: 33, agile: 31,
      abilities: ["Full Throttle"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 0, 1, 0, 0, 4, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Alex", lastName: "Sosa", position: "C", eligibility: "JR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 12,
      hitForAvg: 57, power: 34, speed: 57, arm: 57, fielding: 57, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 53, grit: 58, stealing: 46, running: 46, throwing: 62, recovery: 46, wRISP: 57, vsLefty: 52, poise: 55, heater: 0, agile: 38,
      abilities: ["Consigliere"], potential: "A-", catcherAbility: 57,
      throwHand: "R", batHand: "L",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Alonzo", lastName: "Alvarez", position: "C", eligibility: "FR", homeState: "FL", hometown: "Miami", jerseyNumber: 25,
      hitForAvg: 44, power: 41, speed: 29, arm: 39, fielding: 57, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 44, grit: 46, stealing: 38, running: 38, throwing: 57, recovery: 30, wRISP: 33, vsLefty: 32, poise: 33, heater: 0, agile: 32,
      abilities: ["vs. Breaking Pitches"], potential: "A-", catcherAbility: 43,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // INFIELDERS (6)
    { firstName: "Daniel", lastName: "Cuvet", position: "3B", eligibility: "JR", homeState: "FL", hometown: "Miami", jerseyNumber: 5,
      hitForAvg: 58, power: 58, speed: 50, arm: 47, fielding: 36, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 82, vsLHP: 72, grit: 62, stealing: 46, running: 48, throwing: 62, recovery: 42, wRISP: 90, vsLefty: 70, poise: 78, heater: 0, agile: 45,
      abilities: ["Consigliere", "Head-first Slide", "Bases Loaded Slugger"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Jake", lastName: "Ogden", position: "2B", eligibility: "JR", homeState: "FL", hometown: "Boca Raton", jerseyNumber: 3,
      hitForAvg: 57, power: 48, speed: 57, arm: 44, fielding: 32, errorResistance: 21, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 51, vsLHP: 48, grit: 53, stealing: 46, running: 46, throwing: 57, recovery: 41, wRISP: 51, vsLefty: 47, poise: 50, heater: 0, agile: 48,
      abilities: ["Spray Hitter", "Chance Maker"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Brylan", lastName: "West", position: "1B", eligibility: "JR", homeState: "FL", hometown: "Homestead", jerseyNumber: 24,
      hitForAvg: 57, power: 57, speed: 57, arm: 50, fielding: 31, errorResistance: 57, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 51, grit: 55, stealing: 46, running: 46, throwing: 58, recovery: 43, wRISP: 53, vsLefty: 49, poise: 52, heater: 0, agile: 36,
      abilities: ["Power Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Vance", lastName: "Sheahan", position: "SS", eligibility: "JR", homeState: "SC", hometown: "Spartanburg", jerseyNumber: 6,
      hitForAvg: 61, power: 61, speed: 58, arm: 50, fielding: 31, errorResistance: 61, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 51, grit: 55, stealing: 46, running: 49, throwing: 62, recovery: 43, wRISP: 54, vsLefty: 49, poise: 52, heater: 0, agile: 52,
      abilities: ["Bunt Artisan", "Consigliere"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Cian", lastName: "Copeland", position: "3B", eligibility: "JR", homeState: "FL", hometown: "Miami", jerseyNumber: 18,
      hitForAvg: 50, power: 45, speed: 38, arm: 22, fielding: 53, errorResistance: 43, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 48, grit: 38, stealing: 42, running: 46, throwing: 38, recovery: 31, wRISP: 39, vsLefty: 35, poise: 38, heater: 0, agile: 31,
      abilities: ["Power Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Carlos", lastName: "Rivera", position: "SS", eligibility: "FR", homeState: "FL", hometown: "Kendall", jerseyNumber: 9,
      hitForAvg: 41, power: 33, speed: 57, arm: 57, fielding: 41, errorResistance: 29, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 41, vsLHP: 38, grit: 38, stealing: 52, running: 54, throwing: 53, recovery: 28, wRISP: 30, vsLefty: 27, poise: 30, heater: 0, agile: 43,
      abilities: ["Resilient"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // OUTFIELDERS (9)
    { firstName: "Derek", lastName: "Williams", position: "OF", eligibility: "SR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 1,
      hitForAvg: 59, power: 59, speed: 40, arm: 59, fielding: 59, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 48, grit: 53, stealing: 46, running: 46, throwing: 62, recovery: 42, wRISP: 49, vsLefty: 46, poise: 49, heater: 0, agile: 48,
      abilities: ["Spray Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Max", lastName: "Galvin", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Naples", jerseyNumber: 10,
      hitForAvg: 49, power: 41, speed: 47, arm: 31, fielding: 57, errorResistance: 55, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 48, grit: 38, stealing: 47, running: 51, throwing: 49, recovery: 29, wRISP: 36, vsLefty: 32, poise: 36, heater: 0, agile: 34,
      abilities: ["Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Fabio", lastName: "Peralta", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Hialeah", jerseyNumber: 21,
      hitForAvg: 57, power: 50, speed: 60, arm: 52, fielding: 61, errorResistance: 61, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 51, stealing: 46, running: 50, throwing: 62, recovery: 43, wRISP: 47, vsLefty: 44, poise: 47, heater: 0, agile: 52,
      abilities: ["Bases Loaded Slugger", "Pull Hit"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Jailen", lastName: "Watkins", position: "OF", eligibility: "FR", homeState: "FL", hometown: "Fort Lauderdale", jerseyNumber: 30,
      hitForAvg: 61, power: 56, speed: 61, arm: 61, fielding: 44, errorResistance: 27, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 45, grit: 44, stealing: 54, running: 62, throwing: 62, recovery: 40, wRISP: 42, vsLefty: 38, poise: 42, heater: 0, agile: 66,
      abilities: ["Opposite Field Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "L",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Dario", lastName: "Gonzalez", position: "OF", eligibility: "FR", homeState: "FL", hometown: "Doral", jerseyNumber: 32,
      hitForAvg: 42, power: 35, speed: 40, arm: 57, fielding: 46, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 39, vsLHP: 38, grit: 38, stealing: 54, running: 48, throwing: 54, recovery: 28, wRISP: 28, vsLefty: 26, poise: 28, heater: 0, agile: 43,
      abilities: ["Spray Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Brandon", lastName: "Cruz", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Plantation", jerseyNumber: 16,
      hitForAvg: 61, power: 57, speed: 54, arm: 47, fielding: 60, errorResistance: 61, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 51, vsLHP: 47, grit: 52, stealing: 46, running: 51, throwing: 62, recovery: 43, wRISP: 48, vsLefty: 45, poise: 48, heater: 0, agile: 54,
      abilities: ["Timely Whiff"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Luis", lastName: "Medina", position: "2B", eligibility: "SO", homeState: "FL", hometown: "Coral Springs", jerseyNumber: 20,
      hitForAvg: 42, power: 37, speed: 57, arm: 57, fielding: 41, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 43, grit: 40, stealing: 52, running: 49, throwing: 51, recovery: 29, wRISP: 31, vsLefty: 29, poise: 31, heater: 0, agile: 37,
      abilities: ["High Speed Charge"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Tommy", lastName: "Santiago", position: "P", eligibility: "JR", homeState: "FL", hometown: "Coconut Grove", jerseyNumber: 7,
      hitForAvg: 19, power: 16, speed: 36, arm: 43, fielding: 41, errorResistance: 52, velocity: 50, control: 46, stamina: 49, stuff: 42,
      clutch: 51, vsLHP: 47, grit: 52, stealing: 27, running: 49, throwing: 60, recovery: 32, wRISP: 37, vsLefty: 34, poise: 37, heater: 45, agile: 52,
      abilities: ["vs. Strong Batters", "Staredown"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [1, 0, 0, 1, 0, 0, 4, 0, 0, 0]) },
    { firstName: "Anthony", lastName: "Perez", position: "P", eligibility: "SO", homeState: "FL", hometown: "Weston", jerseyNumber: 8,
      hitForAvg: 14, power: 11, speed: 32, arm: 24, fielding: 22, errorResistance: 34, velocity: 39, control: 26, stamina: 4, stuff: 31,
      clutch: 32, vsLHP: 29, grit: 33, stealing: 20, running: 34, throwing: 39, recovery: 17, wRISP: 19, vsLefty: 17, poise: 19, heater: 25, agile: 37,
      abilities: ["Guts", "Staredown"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 0, 0, 1, 0, 0, 4, 0, 0, 4]) },
    { firstName: "Carlos", lastName: "Arguelles", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Miami", jerseyNumber: 11,
      hitForAvg: 55, power: 55, speed: 55, arm: 55, fielding: 55, errorResistance: 49, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 66, stealing: 48, running: 56, throwing: 68, recovery: 56, wRISP: 62, vsLefty: 58, poise: 62, heater: 0, agile: 58,
      abilities: ["First Pitch King", "Pull Hitter", "vs. Breaking Pitches"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
],

  "NC State": [
    // PITCHERS (8)
    { firstName: "Ryan", lastName: "Marohn", position: "P", eligibility: "JR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 34,
      hitForAvg: 21, power: 17, speed: 34, arm: 70, fielding: 43, errorResistance: 54, velocity: 69, control: 66, stamina: 99, stuff: 67,
      clutch: 79, vsLHP: 75, grit: 65, stealing: 15, running: 37, throwing: 83, recovery: 61, wRISP: 63, vsLefty: 63, poise: 65, heater: 65, agile: 46,
      abilities: ["Strong Finisher", "Strong Starter", "Heavy Ball", "Straddle"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [1, 4, 3, 0, 0, 4, 0, 1, 0, 0]) },
    { firstName: "Jacob", lastName: "Dudan", position: "P", eligibility: "JR", homeState: "NC", hometown: "Cary", jerseyNumber: 38,
      hitForAvg: 16, power: 13, speed: 33, arm: 53, fielding: 33, errorResistance: 45, velocity: 58, control: 50, stamina: 91, stuff: 50,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 13, running: 34, throwing: 67, recovery: 46, wRISP: 46, vsLefty: 46, poise: 48, heater: 53, agile: 41,
      abilities: ["Strong Starter", "Straddle", "Inside Pitch"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 4, 0, 0, 4, 0, 0, 1, 0]) },
    { firstName: "Cam", lastName: "Andrews", position: "P", eligibility: "JR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 29,
      hitForAvg: 15, power: 11, speed: 32, arm: 45, fielding: 28, errorResistance: 39, velocity: 49, control: 43, stamina: 83, stuff: 42,
      clutch: 54, vsLHP: 51, grit: 56, stealing: 10, running: 29, throwing: 60, recovery: 39, wRISP: 39, vsLefty: 39, poise: 42, heater: 45, agile: 36,
      abilities: ["Heavy Ball"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 0, 0, 0, 0, 4, 4, 0, 0, 3]) },
    { firstName: "Anderson", lastName: "Nance", position: "P", eligibility: "JR", homeState: "GA", hometown: "Alpharetta", jerseyNumber: 27,
      hitForAvg: 15, power: 13, speed: 33, arm: 53, fielding: 30, errorResistance: 43, velocity: 57, control: 49, stamina: 88, stuff: 50,
      clutch: 64, vsLHP: 61, grit: 65, stealing: 15, running: 36, throwing: 67, recovery: 41, wRISP: 47, vsLefty: 47, poise: 48, heater: 53, agile: 43,
      abilities: ["Fireman", "Strikeout"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...pitchMix(1, [0, 0, 0, 1, 3, 4, 0, 0, 0, 0]) },
    { firstName: "Collins", lastName: "Black", position: "P", eligibility: "JR", homeState: "NC", hometown: "Greensboro", jerseyNumber: 41,
      hitForAvg: 15, power: 13, speed: 32, arm: 49, fielding: 31, errorResistance: 44, velocity: 53, control: 48, stamina: 50, stuff: 46,
      clutch: 57, vsLHP: 54, grit: 60, stealing: 11, running: 31, throwing: 63, recovery: 42, wRISP: 42, vsLefty: 43, poise: 46, heater: 51, agile: 39,
      abilities: ["Inside Pitch", "Groundball Pitcher", "Gyroball"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 3, 4, 1, 0, 0, 4, 0, 0, 0]) },
    { firstName: "Vincent", lastName: "Decarlo", position: "P", eligibility: "FR", homeState: "NJ", hometown: "Toms River", jerseyNumber: 45,
      hitForAvg: 8, power: 7, speed: 27, arm: 39, fielding: 23, errorResistance: 24, velocity: 44, control: 33, stamina: 48, stuff: 35,
      clutch: 27, vsLHP: 25, grit: 27, stealing: 8, running: 23, throwing: 37, recovery: 27, wRISP: 25, vsLefty: 27, poise: 27, heater: 41, agile: 27,
      abilities: ["Shuuto Spin"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 4, 0, 0, 4, 0, 1, 0, 0]) },
    { firstName: "Aiden", lastName: "Kitchings", position: "P", eligibility: "FR", homeState: "NC", hometown: "Apex", jerseyNumber: 48,
      hitForAvg: 10, power: 8, speed: 31, arm: 29, fielding: 17, errorResistance: 28, velocity: 43, control: 25, stamina: 38, stuff: 31,
      clutch: 30, vsLHP: 29, grit: 32, stealing: 11, running: 29, throwing: 45, recovery: 20, wRISP: 19, vsLefty: 21, poise: 20, heater: 31, agile: 33,
      abilities: ["Sharpness"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 0, 0, 4, 4, 0, 0, 3]) },
    // CATCHERS (2)
    { firstName: "Brandon", lastName: "Crabtree", position: "C", eligibility: "JR", homeState: "NC", hometown: "Wake Forest", jerseyNumber: 12,
      hitForAvg: 54, power: 47, speed: 26, arm: 41, fielding: 59, errorResistance: 57, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 51, vsLHP: 49, grit: 55, stealing: 40, running: 40, throwing: 65, recovery: 44, wRISP: 49, vsLefty: 47, poise: 51, heater: 0, agile: 36,
      abilities: ["Consigliere"], potential: "B+", catcherAbility: 55,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Garrett", lastName: "Payne", position: "C", eligibility: "SO", homeState: "NC", hometown: "Wilmington", jerseyNumber: 25,
      hitForAvg: 47, power: 38, speed: 31, arm: 34, fielding: 56, errorResistance: 55, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 44, grit: 42, stealing: 36, running: 32, throwing: 32, recovery: 29, wRISP: 29, vsLefty: 26, poise: 29, heater: 0, agile: 26,
      abilities: ["Walkoff Hitter", "Resilient"], potential: "B", catcherAbility: 39,
      throwHand: "R", batHand: "S",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // INFIELDERS (7)
    { firstName: "Chris", lastName: "McHugh", position: "1B", eligibility: "JR", homeState: "PA", hometown: "Philadelphia", jerseyNumber: 18,
      hitForAvg: 61, power: 61, speed: 57, arm: 59, fielding: 58, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 57, vsLHP: 54, grit: 59, stealing: 48, running: 48, throwing: 58, recovery: 45, wRISP: 57, vsLefty: 53, poise: 56, heater: 0, agile: 35,
      abilities: ["Power Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "L",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Mikey", lastName: "Ryan", position: "SS", eligibility: "JR", homeState: "CA", hometown: "San Clemente", jerseyNumber: 6,
      hitForAvg: 52, power: 44, speed: 53, arm: 36, fielding: 60, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 45, vsLHP: 51, grit: 48, stealing: 55, running: 51, throwing: 61, recovery: 38, wRISP: 45, vsLefty: 43, poise: 46, heater: 0, agile: 46,
      abilities: ["Defensive Artisan"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "L",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Luke", lastName: "Nixon", position: "2B", eligibility: "JR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 3,
      hitForAvg: 52, power: 42, speed: 61, arm: 52, fielding: 38, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 46, vsLHP: 43, grit: 49, stealing: 56, running: 53, throwing: 59, recovery: 39, wRISP: 45, vsLefty: 42, poise: 45, heater: 0, agile: 45,
      abilities: ["Contact Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Sherman", lastName: "Johnson", position: "3B", eligibility: "SO", homeState: "TX", hometown: "Houston", jerseyNumber: 15,
      hitForAvg: 53, power: 50, speed: 50, arm: 38, fielding: 61, errorResistance: 63, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 47, grit: 49, stealing: 55, running: 52, throwing: 65, recovery: 41, wRISP: 46, vsLefty: 43, poise: 46, heater: 0, agile: 44,
      abilities: ["Multi-Hit", "Contact Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Dalton", lastName: "Bargo", position: "1B", eligibility: "JR", homeState: "TN", hometown: "Knoxville", jerseyNumber: 24,
      hitForAvg: 56, power: 59, speed: 40, arm: 28, fielding: 59, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 49, grit: 54, stealing: 48, running: 48, throwing: 58, recovery: 42, wRISP: 52, vsLefty: 48, poise: 51, heater: 0, agile: 35,
      abilities: ["Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Wyatt", lastName: "Peifer", position: "3B", eligibility: "SR", homeState: "VA", hometown: "Harrisonburg", jerseyNumber: 11,
      hitForAvg: 61, power: 60, speed: 56, arm: 58, fielding: 46, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 55, grit: 61, stealing: 48, running: 48, throwing: 65, recovery: 52, wRISP: 57, vsLefty: 53, poise: 57, heater: 0, agile: 49,
      abilities: ["Push", "Insurer"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Mikey", lastName: "Ragusa", position: "SS", eligibility: "FR", homeState: "NJ", hometown: "Middletown", jerseyNumber: 9,
      hitForAvg: 41, power: 35, speed: 62, arm: 52, fielding: 31, errorResistance: 23, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 42, grit: 41, stealing: 54, running: 51, throwing: 57, recovery: 30, wRISP: 32, vsLefty: 29, poise: 32, heater: 0, agile: 44,
      abilities: ["Revenge", "Timely Whiff"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "S",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // OUTFIELDERS (8)
    { firstName: "Ty", lastName: "Head", position: "OF", eligibility: "SO", homeState: "TX", hometown: "Grapevine", jerseyNumber: 4,
      hitForAvg: 55, power: 61, speed: 51, arm: 41, fielding: 64, errorResistance: 57, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 48, grit: 52, stealing: 48, running: 54, throwing: 65, recovery: 44, wRISP: 48, vsLefty: 45, poise: 49, heater: 0, agile: 57,
      abilities: ["Chance Maker", "Defensive Artisan"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Brayden", lastName: "Fraasman", position: "OF", eligibility: "JR", homeState: "NC", hometown: "Fuquay-Varina", jerseyNumber: 21,
      hitForAvg: 45, power: 40, speed: 63, arm: 56, fielding: 37, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 42, grit: 40, stealing: 50, running: 53, throwing: 50, recovery: 30, wRISP: 34, vsLefty: 31, poise: 34, heater: 0, agile: 38,
      abilities: ["Bunt Artisan"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "S",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Andrew", lastName: "Wiggins", position: "OF", eligibility: "JR", homeState: "GA", hometown: "Marietta", jerseyNumber: 10,
      hitForAvg: 55, power: 51, speed: 61, arm: 52, fielding: 35, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 48, grit: 51, stealing: 48, running: 49, throwing: 65, recovery: 43, wRISP: 48, vsLefty: 44, poise: 48, heater: 0, agile: 53,
      abilities: ["Multi-Hit"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // Rett Johnson — FR OF — PG 2nd Team / Top-200 national
    { firstName: "Rett", lastName: "Johnson", position: "OF", eligibility: "FR", homeState: "NC", hometown: "Huntersville", jerseyNumber: 1,
      hitForAvg: 61, power: 51, speed: 59, arm: 59, fielding: 51, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 51, vsLHP: 51, grit: 47, stealing: 56, running: 53, throwing: 65, recovery: 38, wRISP: 40, vsLefty: 37, poise: 40, heater: 0, agile: 57,
      abilities: ["Pull Hitter"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "L",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Marcus", lastName: "Greer", position: "OF", eligibility: "JR", homeState: "NC", hometown: "Garner", jerseyNumber: 8,
      hitForAvg: 53, power: 46, speed: 64, arm: 56, fielding: 40, errorResistance: 63, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 45, grit: 49, stealing: 56, running: 51, throwing: 65, recovery: 41, wRISP: 46, vsLefty: 43, poise: 46, heater: 0, agile: 52,
      abilities: ["High Speed Charge"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Kyle", lastName: "Fitzgerald", position: "OF", eligibility: "JR", homeState: "VA", hometown: "Richmond", jerseyNumber: 20,
      hitForAvg: 44, power: 38, speed: 64, arm: 55, fielding: 35, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 40, grit: 43, stealing: 56, running: 52, throwing: 51, recovery: 30, wRISP: 32, vsLefty: 30, poise: 32, heater: 0, agile: 37,
      abilities: ["vs. Breaking Pitches"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Tyler", lastName: "Barnes", position: "P", eligibility: "SO", homeState: "NC", hometown: "Concord", jerseyNumber: 32,
      hitForAvg: 13, power: 10, speed: 32, arm: 24, fielding: 23, errorResistance: 32, velocity: 40, control: 28, stamina: 33, stuff: 33,
      clutch: 29, vsLHP: 27, grit: 31, stealing: 19, running: 34, throwing: 37, recovery: 19, wRISP: 19, vsLefty: 17, poise: 19, heater: 26, agile: 37,
      abilities: ["Strong Starter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 3, 0, 0, 0]) },
    { firstName: "Josh", lastName: "Hogue", position: "P", eligibility: "JR", homeState: "NC", hometown: "Wake Forest", jerseyNumber: 7,
      hitForAvg: 14, power: 11, speed: 32, arm: 25, fielding: 23, errorResistance: 35, velocity: 41, control: 27, stamina: 4, stuff: 32,
      clutch: 32, vsLHP: 30, grit: 34, stealing: 19, running: 34, throwing: 40, recovery: 18, wRISP: 19, vsLefty: 18, poise: 19, heater: 26, agile: 36,
      abilities: ["Fireman", "Good Pickoff"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0, 0, 0, 0]) },
    { firstName: "Devonte", lastName: "Brown", position: "OF", eligibility: "JR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 12,
      hitForAvg: 61, power: 50, speed: 56, arm: 54, fielding: 48, errorResistance: 39, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 54, grit: 62, stealing: 50, running: 56, throwing: 64, recovery: 52, wRISP: 58, vsLefty: 54, poise: 62, heater: 0, agile: 58,
      abilities: ["Spray Hitter", "Disturbance"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "dark", hairColor: "black", hairStyle: "short",
      ...noPitches },
],

  // North Carolina — 39-9-1 overall, 19-7 ACC, D1Baseball #2 (May 3, 2026)
  // Real 2026 mid-season stats from goheels.com PDF
  "North Carolina": [
    // PITCHERS (10) — ACC-leading ERA three years running, NCAA #14 fielding
    // Jason DeCaro — Friday ace JR, 9-2 / 1.91 ERA / 66 IP / 61K, Golden Spikes Watch List — TEAM ELITE STUFF
    { firstName: "Jason", lastName: "DeCaro", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Wayne", jerseyNumber: 29,
      hitForAvg: 18, power: 14, speed: 33, arm: 92, fielding: 60, errorResistance: 60, velocity: 97, control: 95, stamina: 91, stuff: 97,
      clutch: 82, vsLHP: 82, grit: 65, stealing: 8, running: 35, throwing: 82, recovery: 65, wRISP: 65, vsLefty: 65, poise: 65, heater: 65, agile: 46,
      abilities: ["Constant Speed", "Inside Pitch", "Strong Starter", "Strikeout"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 0, 4, 0, 0, 5, 0, 1, 0, 0]) },
    // Caden Glauber — FR RHP, 6-0 / 1.95 / 67K / 4 SV, weekend bullpen ace — command-dominant, stuff developing
    { firstName: "Caden", lastName: "Glauber", position: "P", eligibility: "FR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 27,
      hitForAvg: 12, power: 10, speed: 33, arm: 92, fielding: 60, errorResistance: 52, velocity: 88, control: 92, stamina: 98, stuff: 85,
      clutch: 82, vsLHP: 82, grit: 65, stealing: 8, running: 32, throwing: 82, recovery: 65, wRISP: 65, vsLefty: 65, poise: 65, heater: 65, agile: 46,
      abilities: ["Inside Pitch", "Strong Starter", "vs. Strong Batters", "Heavy Ball"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 0, 0, 0, 0, 4, 4, 0, 1, 0]) },
    // Walker McDuffie — SO RHP closer, 6-2 / 2.47 / 26 app / 4 SV / 66K, NC Charlotte
    { firstName: "Walker", lastName: "McDuffie", position: "P", eligibility: "SO", homeState: "NC", hometown: "Charlotte", jerseyNumber: 40,
      hitForAvg: 11, power: 8, speed: 32, arm: 61, fielding: 34, errorResistance: 48, velocity: 63, control: 54, stamina: 82, stuff: 58,
      clutch: 76, vsLHP: 70, grit: 65, stealing: 8, running: 32, throwing: 74, recovery: 44, wRISP: 57, vsLefty: 56, poise: 59, heater: 56, agile: 46,
      abilities: ["Fireman", "vs. Strong Batters", "Groundball Pitcher"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 0, 0, 0, 0, 4, 0, 0, 0, 3]) },
    // Ryan Lynch — SO RHP Saturday SP, 4-4 / 3.75 / 12 GS / 69 IP / 66K
    { firstName: "Ryan", lastName: "Lynch", position: "P", eligibility: "SO", homeState: "NC", hometown: "Durham", jerseyNumber: 53,
      hitForAvg: 13, power: 10, speed: 33, arm: 55, fielding: 34, errorResistance: 48, velocity: 59, control: 52, stamina: 80, stuff: 53,
      clutch: 64, vsLHP: 62, grit: 65, stealing: 8, running: 33, throwing: 68, recovery: 48, wRISP: 47, vsLefty: 48, poise: 48, heater: 55, agile: 42,
      abilities: ["Strong Starter", "True Slider"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 3, 3, 1, 0, 0, 3, 0, 0, 4]) },
    // Folger Boaz — JR LHP Sunday SP, 3-1 record (depth pick when not Glauber)
    { firstName: "Folger", lastName: "Boaz", position: "P", eligibility: "JR", homeState: "NC", hometown: "Greensboro", jerseyNumber: 31,
      hitForAvg: 14, power: 11, speed: 32, arm: 49, fielding: 32, errorResistance: 46, velocity: 51, control: 54, stamina: 51, stuff: 47,
      clutch: 60, vsLHP: 72, grit: 62, stealing: 6, running: 28, throwing: 60, recovery: 43, wRISP: 43, vsLefty: 55, poise: 47, heater: 46, agile: 36,
      abilities: ["Fireman", "Inside Pitch"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4, 0, 0, 0]) },
    // Jackson Rose — JR RHP swing/long, 3-0 / 1.59 / 5 GS / 34 IP / 32K
    { firstName: "Jackson", lastName: "Rose", position: "P", eligibility: "JR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 35,
      hitForAvg: 13, power: 10, speed: 32, arm: 53, fielding: 32, errorResistance: 48, velocity: 58, control: 53, stamina: 36, stuff: 51,
      clutch: 68, vsLHP: 64, grit: 65, stealing: 7, running: 28, throwing: 66, recovery: 46, wRISP: 53, vsLefty: 48, poise: 54, heater: 53, agile: 38,
      abilities: ["Strong Starter"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 0, 0, 0, 0, 4, 4, 1, 0, 0]) },
    // Jake Cackovic — RHP RP, 1.35 ERA / 6.2 IP, low usage but dominant
    { firstName: "Jake", lastName: "Cackovic", position: "P", eligibility: "JR", homeState: "NC", hometown: "Cary", jerseyNumber: 39,
      hitForAvg: 11, power: 9, speed: 31, arm: 45, fielding: 28, errorResistance: 42, velocity: 49, control: 47, stamina: 30, stuff: 45,
      clutch: 60, vsLHP: 56, grit: 60, stealing: 6, running: 26, throwing: 60, recovery: 37, wRISP: 44, vsLefty: 43, poise: 44, heater: 44, agile: 38,
      abilities: ["Fireman", "vs. Strong Batters"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 0, 3, 0, 0, 4, 0, 0, 1, 0]) },
    // Boston Flannery — RHP swing, 1-0 / 3.44 / 4 GS
    { firstName: "Boston", lastName: "Flannery", position: "P", eligibility: "JR", homeState: "MA", hometown: "Boston", jerseyNumber: 42,
      hitForAvg: 12, power: 9, speed: 32, arm: 44, fielding: 28, errorResistance: 40, velocity: 47, control: 41, stamina: 41, stuff: 41,
      clutch: 52, vsLHP: 50, grit: 54, stealing: 6, running: 28, throwing: 58, recovery: 37, wRISP: 37, vsLefty: 38, poise: 40, heater: 44, agile: 36,
      abilities: ["True Slider", "Bad Ball Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0, 0, 0, 0]) },
    // Matthew Matthijs — RP returning from arm injury, 5.32 / 22 IP / 26K / 2 SV
    { firstName: "Matthew", lastName: "Matthijs", position: "P", eligibility: "SR", homeState: "NC", hometown: "Apex", jerseyNumber: 24,
      hitForAvg: 11, power: 9, speed: 31, arm: 47, fielding: 29, errorResistance: 40, velocity: 51, control: 41, stamina: 7, stuff: 46,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 6, running: 26, throwing: 60, recovery: 32, wRISP: 35, vsLefty: 36, poise: 36, heater: 47, agile: 36,
      abilities: ["Strong Starter", "Decisive"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 0, 0, 0, 0, 4, 0, 0, 0, 3]) },
    // AJ Terry — depth RP
    // CATCHERS (2)
    // Colin Hynek — primary C JR, .254/5HR/43RBI, 169 PO/8A/.989 FLD, 7 SBA / 2 CSB
    { firstName: "Colin", lastName: "Hynek", position: "C", eligibility: "JR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 23,
      hitForAvg: 57, power: 57, speed: 52, arm: 58, fielding: 51, errorResistance: 49, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 52, grit: 56, stealing: 40, running: 40, throwing: 65, recovery: 50, wRISP: 56, vsLefty: 50, poise: 56, heater: 0, agile: 34,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: 64,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // Michael Maginnis — backup C/util
    { firstName: "Michael", lastName: "Maginnis", position: "C", eligibility: "FR", homeState: "GA", hometown: "Kennesaw", jerseyNumber: 14,
      hitForAvg: 41, power: 37, speed: 53, arm: 53, fielding: 37, errorResistance: 24, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 39, vsLHP: 43, grit: 48, stealing: 37, running: 34, throwing: 60, recovery: 32, wRISP: 30, vsLefty: 28, poise: 32, heater: 0, agile: 32,
      abilities: ["Line Drive"], potential: "B", catcherAbility: 44,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // INFIELDERS (6)
    // Erik Paulsen — JR 1B transfer from Stony Brook, .293/7HR/39RBI, perfect 1.000 FLD on 374 chances
    { firstName: "Erik", lastName: "Paulsen", position: "1B", eligibility: "JR", homeState: "NY", hometown: "Stony Brook", jerseyNumber: 44,
      hitForAvg: 63, power: 61, speed: 45, arm: 33, fielding: 63, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 65, stealing: 48, running: 48, throwing: 60, recovery: 56, wRISP: 64, vsLefty: 58, poise: 64, heater: 0, agile: 32,
      abilities: ["Power Hitter", "Defensive Artisan"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      skinTone: "light", hairColor: "blonde", hairStyle: "short",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // Gavin Gallaher — JR 2B captain, .273/9HR/40RBI, leads ALL 2B nationally in DRS (12.55), team captain
    { firstName: "Gavin", lastName: "Gallaher", position: "2B", eligibility: "JR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 5,
      hitForAvg: 65, power: 63, speed: 54, arm: 49, fielding: 41, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 65, vsLHP: 64, grit: 78, stealing: 48, running: 48, throwing: 74, recovery: 56, wRISP: 66, vsLefty: 60, poise: 76, heater: 0, agile: 60,
      abilities: ["Good Bunt", "Defensive Artisan", "Consigliere", "Power Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // Jake Schaffner — JR SS, .354/5HR/5 3B/23 SB, 100 A, .982 FLD — table-setter
    { firstName: "Jake", lastName: "Schaffner", position: "SS", eligibility: "JR", homeState: "ND", hometown: "Fargo", jerseyNumber: 2,
      hitForAvg: 59, power: 59, speed: 62, arm: 55, fielding: 47, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 70, vsLHP: 64, grit: 65, stealing: 48, running: 64, throwing: 78, recovery: 56, wRISP: 64, vsLefty: 60, poise: 68, heater: 0, agile: 68,
      abilities: ["Defensive Artisan", "Chance Maker", "vs. Ace"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // Cooper Nicholson — JR 3B, .267/13HR/41RBI, ACC-leading 21 HBPs, power threat (.630 SLG!)
    { firstName: "Cooper", lastName: "Nicholson", position: "3B", eligibility: "JR", homeState: "IA", hometown: "Pinehurst", jerseyNumber: 1,
      hitForAvg: 61, power: 61, speed: 36, arm: 61, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 59, vsLHP: 62, grit: 57, stealing: 48, running: 48, throwing: 57, recovery: 50, wRISP: 70, vsLefty: 60, poise: 70, heater: 0, agile: 40,
      abilities: ["Power Hitter", "Multi-Hit"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // Lee Sowers — SO util infielder/3B backup
    { firstName: "Lee", lastName: "Sowers", position: "3B", eligibility: "SO", homeState: "NC", hometown: "Cary", jerseyNumber: 3,
      hitForAvg: 39, power: 36, speed: 53, arm: 36, fielding: 24, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 37, grit: 41, stealing: 42, running: 48, throwing: 51, recovery: 29, wRISP: 28, vsLefty: 26, poise: 29, heater: 0, agile: 33,
      abilities: ["Consigliere", "Push"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // Jadyn Nunez — FR depth IF
    { firstName: "Jadyn", lastName: "Nunez", position: "1B", eligibility: "FR", homeState: "FL", hometown: "Tampa", jerseyNumber: 28,
      hitForAvg: 37, power: 39, speed: 60, arm: 63, fielding: 56, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 40, grit: 45, stealing: 51, running: 45, throwing: 52, recovery: 30, wRISP: 30, vsLefty: 26, poise: 30, heater: 0, agile: 28,
      abilities: ["Consigliere", "Contact Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // OUTFIELDERS (7)
    // Owen Hull — JR CF transfer from George Mason (.367/8HR/63RBI/42SB last year), .379/4HR/57RBI/16SB at UNC, "fastest player on team", big draft prospect
    { firstName: "Owen", lastName: "Hull", position: "OF", eligibility: "JR", homeState: "VA", hometown: "Fairfax", jerseyNumber: 8,
      hitForAvg: 60, power: 58, speed: 51, arm: 44, fielding: 63, errorResistance: 63, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 59, vsLHP: 57, grit: 76, stealing: 64, running: 66, throwing: 58, recovery: 56, wRISP: 80, vsLefty: 72, poise: 76, heater: 0, agile: 80,
      abilities: ["Walkoff Hitter", "Chance Maker", "Push", "Consigliere"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // Macon Winslow — JR OF (corner), .310/9HR/45RBI, hit team-longest 427-foot HR
    { firstName: "Macon", lastName: "Winslow", position: "OF", eligibility: "JR", homeState: "NC", hometown: "Durham", jerseyNumber: 6,
      hitForAvg: 61, power: 61, speed: 59, arm: 61, fielding: 49, errorResistance: 40, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 48, running: 48, throwing: 70, recovery: 56, wRISP: 66, vsLefty: 60, poise: 64, heater: 0, agile: 44,
      abilities: ["Power Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // Tyler Howe — SO OF, .250/3HR
    { firstName: "Tyler", lastName: "Howe", position: "OF", eligibility: "SO", homeState: "NC", hometown: "Greensboro", jerseyNumber: 12,
      hitForAvg: 57, power: 47, speed: 53, arm: 35, fielding: 56, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 53, grit: 50, stealing: 52, running: 56, throwing: 62, recovery: 40, wRISP: 48, vsLefty: 44, poise: 48, heater: 0, agile: 50,
      abilities: ["Contact Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // Carter French — SR util OF, .231 in 91 AB, 5 SB
    { firstName: "Carter", lastName: "French", position: "OF", eligibility: "SR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 18,
      hitForAvg: 51, power: 43, speed: 58, arm: 63, fielding: 60, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 46, grit: 56, stealing: 56, running: 53, throwing: 60, recovery: 46, wRISP: 44, vsLefty: 42, poise: 50, heater: 0, agile: 50,
      abilities: ["Chance Maker"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // Sawyer Black — SO OF depth
    { firstName: "Sawyer", lastName: "Black", position: "OF", eligibility: "SO", homeState: "NC", hometown: "Winston-Salem", jerseyNumber: 4,
      hitForAvg: 49, power: 45, speed: 42, arm: 63, fielding: 61, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 44, grit: 48, stealing: 53, running: 56, throwing: 65, recovery: 40, wRISP: 42, vsLefty: 38, poise: 42, heater: 0, agile: 50,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // Perry Hargett — SO OF depth
    { firstName: "Perry", lastName: "Hargett", position: "OF", eligibility: "SO", homeState: "NC", hometown: "Raleigh", jerseyNumber: 7,
      hitForAvg: 40, power: 37, speed: 60, arm: 58, fielding: 43, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 40, grit: 40, stealing: 48, running: 52, throwing: 54, recovery: 34, wRISP: 32, vsLefty: 29, poise: 34, heater: 0, agile: 44,
      abilities: ["Multi-Hit", "Unpredictable"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // Rom Kellis V — FR/SO part-time, .300 in 40 AB
    { firstName: "Rom", lastName: "Kellis V", position: "2B", eligibility: "SR", homeState: "NC", hometown: "Asheville", jerseyNumber: 25,
      hitForAvg: 49, power: 41, speed: 51, arm: 28, fielding: 62, errorResistance: 59, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 46, vsLHP: 45, grit: 40, stealing: 48, running: 51, throwing: 40, recovery: 27, wRISP: 32, vsLefty: 29, poise: 30, heater: 0, agile: 32,
      abilities: ["Unpredictable"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Colby", lastName: "Wilkerson", position: "1B", eligibility: "JR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 32,
      hitForAvg: 61, power: 56, speed: 61, arm: 49, fielding: 46, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 56, grit: 62, stealing: 48, running: 48, throwing: 65, recovery: 54, wRISP: 60, vsLefty: 56, poise: 54, heater: 0, agile: 50,
      abilities: ["Power Hitter", "Tough Out"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
  ],

  "Notre Dame": [
    // PITCHERS (8)
    { firstName: "Jack", lastName: "Radel", position: "P", eligibility: "JR", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 34,
      hitForAvg: 23, power: 19, speed: 34, arm: 93, fielding: 62, errorResistance: 54, velocity: 97, control: 95, stamina: 88, stuff: 98,
      clutch: 89, vsLHP: 88, grit: 71, stealing: 14, running: 40, throwing: 95, recovery: 71, wRISP: 71, vsLefty: 71, poise: 71, heater: 71, agile: 48,
      abilities: ["vs. Strong Batters", "True Slider", "Heavy Ball", "Strikeout"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [1, 0, 0, 0, 0, 0, 4, 1, 0, 5]) },
    { firstName: "Ty", lastName: "Uber", position: "P", eligibility: "SR", homeState: "CA", hometown: "Palo Alto", jerseyNumber: 29,
      hitForAvg: 15, power: 11, speed: 32, arm: 49, fielding: 30, errorResistance: 42, velocity: 53, control: 47, stamina: 80, stuff: 45,
      clutch: 59, vsLHP: 55, grit: 61, stealing: 10, running: 30, throwing: 63, recovery: 42, wRISP: 43, vsLefty: 43, poise: 46, heater: 49, agile: 37,
      abilities: ["Strong Starter", "Escape Pitch", "Full Throttle"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 0, 0, 4, 4, 0, 1, 0]) },
    { firstName: "Noah", lastName: "Rooney", position: "P", eligibility: "SR", homeState: "MN", hometown: "Minneapolis", jerseyNumber: 41,
      hitForAvg: 18, power: 13, speed: 32, arm: 57, fielding: 34, errorResistance: 46, velocity: 64, control: 54, stamina: 86, stuff: 53,
      clutch: 63, vsLHP: 61, grit: 67, stealing: 12, running: 33, throwing: 70, recovery: 48, wRISP: 48, vsLefty: 49, poise: 52, heater: 57, agile: 40,
      abilities: ["Poker Face", "Tunneling", "Escape Pitch"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 0, 4, 1, 0, 3, 4, 0, 0, 0]) },
    { firstName: "Eli", lastName: "Thurmond", position: "P", eligibility: "SR", homeState: "GA", hometown: "Savannah", jerseyNumber: 27,
      hitForAvg: 16, power: 14, speed: 33, arm: 56, fielding: 35, errorResistance: 47, velocity: 61, control: 53, stamina: 84, stuff: 50,
      clutch: 65, vsLHP: 60, grit: 66, stealing: 12, running: 35, throwing: 71, recovery: 47, wRISP: 48, vsLefty: 48, poise: 52, heater: 56, agile: 43,
      abilities: ["Guts", "Kageura"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 0, 4, 1, 0, 4, 0, 0, 0, 0]) },
    { firstName: "Chase", lastName: "Van Ameyde", position: "P", eligibility: "SO", homeState: "IN", hometown: "South Bend", jerseyNumber: 38,
      hitForAvg: 14, power: 13, speed: 33, arm: 48, fielding: 29, errorResistance: 43, velocity: 52, control: 45, stamina: 64, stuff: 45,
      clutch: 56, vsLHP: 52, grit: 57, stealing: 13, running: 34, throwing: 63, recovery: 40, wRISP: 40, vsLefty: 42, poise: 43, heater: 50, agile: 41,
      abilities: ["Sharpness", "Strong Finisher", "Winner's Luck"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 0, 0, 0, 0, 3, 0, 0, 3]) },
    { firstName: "Oisin", lastName: "Lee", position: "P", eligibility: "SO", homeState: "IL", hometown: "Chicago", jerseyNumber: 36,
      hitForAvg: 9, power: 8, speed: 30, arm: 29, fielding: 16, errorResistance: 26, velocity: 44, control: 25, stamina: 36, stuff: 31,
      clutch: 35, vsLHP: 34, grit: 37, stealing: 8, running: 22, throwing: 40, recovery: 22, wRISP: 23, vsLefty: 24, poise: 25, heater: 29, agile: 27,
      abilities: ["Fireman"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 0, 0, 0, 3, 4, 0, 1, 0, 0]) },
    // Caden Crowell — FR LHP — PG HM / Top-500 national
    { firstName: "Caden", lastName: "Crowell", position: "P", eligibility: "FR", homeState: "IN", hometown: "Valparaiso", jerseyNumber: 45,
      hitForAvg: 9, power: 7, speed: 26, arm: 36, fielding: 17, errorResistance: 26, velocity: 43, control: 34, stamina: 37, stuff: 34,
      clutch: 30, vsLHP: 29, grit: 31, stealing: 9, running: 25, throwing: 44, recovery: 21, wRISP: 20, vsLefty: 21, poise: 21, heater: 31, agile: 29,
      abilities: ["Strong Finisher", "vs. Strong Batters", "Glass Heart"], potential: "A", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 3, 0, 0, 4, 0, 0, 1, 0]) },
    { firstName: "Dylan", lastName: "Singleton", position: "P", eligibility: "FR", homeState: "OH", hometown: "Columbus", jerseyNumber: 48,
      hitForAvg: 11, power: 9, speed: 31, arm: 34, fielding: 19, errorResistance: 31, velocity: 45, control: 28, stamina: 46, stuff: 32,
      clutch: 33, vsLHP: 33, grit: 35, stealing: 9, running: 29, throwing: 51, recovery: 22, wRISP: 22, vsLefty: 23, poise: 22, heater: 36, agile: 33,
      abilities: ["Strong Starter"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 0, 0, 1, 0, 0, 4, 0, 0, 4]) },
    // CATCHERS (2)
    { firstName: "Ryan", lastName: "Grogan", position: "C", eligibility: "JR", homeState: "IN", hometown: "Indianapolis", jerseyNumber: 8,
      hitForAvg: 54, power: 50, speed: 22, arm: 69, fielding: 68, errorResistance: 59, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 55, grit: 55, stealing: 44, running: 44, throwing: 71, recovery: 47, wRISP: 51, vsLefty: 47, poise: 52, heater: 0, agile: 36,
      abilities: ["Resilient"], potential: "B+", catcherAbility: 58,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Sean", lastName: "Murray", position: "C", eligibility: "SO", homeState: "IL", hometown: "Naperville", jerseyNumber: 19,
      hitForAvg: 44, power: 39, speed: 38, arm: 26, fielding: 68, errorResistance: 68, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 45, grit: 48, stealing: 39, running: 39, throwing: 46, recovery: 31, wRISP: 33, vsLefty: 29, poise: 33, heater: 0, agile: 28,
      abilities: ["Pinch Hitter"], potential: "B", catcherAbility: 42,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // INFIELDERS (7)
    { firstName: "Noah", lastName: "Coy", position: "SS", eligibility: "SO", homeState: "OH", hometown: "Dayton", jerseyNumber: 6,
      hitForAvg: 53, power: 43, speed: 45, arm: 69, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 45, vsLHP: 52, grit: 52, stealing: 60, running: 55, throwing: 66, recovery: 42, wRISP: 46, vsLefty: 43, poise: 46, heater: 0, agile: 51,
      abilities: ["Defensive Artisan"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "S",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Parker", lastName: "Brzustewicz", position: "3B", eligibility: "SO", homeState: "MI", hometown: "Ann Arbor", jerseyNumber: 5,
      hitForAvg: 46, power: 42, speed: 48, arm: 24, fielding: 61, errorResistance: 61, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 41, grit: 39, stealing: 49, running: 43, throwing: 46, recovery: 30, wRISP: 33, vsLefty: 30, poise: 33, heater: 0, agile: 30,
      abilities: ["vs. Fastballs"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Davis", lastName: "Johnson", position: "1B", eligibility: "JR", homeState: "IN", hometown: "Fort Wayne", jerseyNumber: 18,
      hitForAvg: 53, power: 53, speed: 70, arm: 45, fielding: 38, errorResistance: 29, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 53, grit: 56, stealing: 49, running: 53, throwing: 64, recovery: 45, wRISP: 52, vsLefty: 46, poise: 52, heater: 0, agile: 41,
      abilities: ["Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Jamie", lastName: "Zee", position: "2B", eligibility: "FR", homeState: "NJ", hometown: "Oradell", jerseyNumber: 3,
      hitForAvg: 45, power: 33, speed: 75, arm: 37, fielding: 37, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 22, vsLHP: 22, grit: 22, stealing: 22, running: 22, throwing: 22, recovery: 29, wRISP: 30, vsLefty: 27, poise: 30, heater: 0, agile: 41,
      abilities: ["Push"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Matt", lastName: "Sloan", position: "2B", eligibility: "JR", homeState: "OH", hometown: "Cleveland", jerseyNumber: 14,
      hitForAvg: 56, power: 46, speed: 53, arm: 69, fielding: 68, errorResistance: 68, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 46, vsLHP: 53, grit: 52, stealing: 60, running: 53, throwing: 68, recovery: 45, wRISP: 49, vsLefty: 45, poise: 49, heater: 0, agile: 53,
      abilities: ["Push", "Pinch Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Jack", lastName: "Penney", position: "3B", eligibility: "JR", homeState: "PA", hometown: "Pittsburgh", jerseyNumber: 15,
      hitForAvg: 42, power: 32, speed: 75, arm: 36, fielding: 36, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 22, vsLHP: 22, grit: 22, stealing: 22, running: 22, throwing: 22, recovery: 27, wRISP: 29, vsLefty: 27, poise: 29, heater: 0, agile: 29,
      abilities: ["Chance Maker", "Opposite Field Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Tommy", lastName: "O'Brien", position: "SS", eligibility: "JR", homeState: "CT", hometown: "Greenwich", jerseyNumber: 9,
      hitForAvg: 53, power: 48, speed: 64, arm: 64, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 55, grit: 57, stealing: 60, running: 53, throwing: 71, recovery: 44, wRISP: 48, vsLefty: 44, poise: 48, heater: 0, agile: 56,
      abilities: ["Defensive Artisan", "Walkoff Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // OUTFIELDERS (8)
    { firstName: "Jared", lastName: "Zimbardo", position: "OF", eligibility: "SR", homeState: "FL", hometown: "Tampa", jerseyNumber: 1,
      hitForAvg: 53, power: 50, speed: 40, arm: 69, fielding: 57, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 52, grit: 49, stealing: 56, running: 49, throwing: 65, recovery: 43, wRISP: 48, vsLefty: 45, poise: 50, heater: 0, agile: 50,
      abilities: ["Spray Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Bino", lastName: "Watters", position: "OF", eligibility: "FR", homeState: "FL", hometown: "Orlando", jerseyNumber: 24,
      hitForAvg: 60, power: 66, speed: 68, arm: 51, fielding: 41, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 52, grit: 54, stealing: 52, running: 53, throwing: 71, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 57,
      abilities: ["Power Hitter"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Jayce", lastName: "Lee", position: "OF", eligibility: "FR", homeState: "CA", hometown: "San Diego", jerseyNumber: 21,
      hitForAvg: 45, power: 33, speed: 67, arm: 57, fielding: 40, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 41, vsLHP: 42, grit: 36, stealing: 60, running: 58, throwing: 43, recovery: 24, wRISP: 24, vsLefty: 22, poise: 24, heater: 0, agile: 38,
      abilities: ["Pressure Run"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "L",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Michael", lastName: "Hogan", position: "OF", eligibility: "JR", homeState: "IN", hometown: "Carmel", jerseyNumber: 10,
      hitForAvg: 54, power: 49, speed: 41, arm: 69, fielding: 57, errorResistance: 57, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 51, vsLHP: 46, grit: 44, stealing: 60, running: 55, throwing: 67, recovery: 42, wRISP: 47, vsLefty: 44, poise: 47, heater: 0, agile: 51,
      abilities: ["Bunt Artisan"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "S",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Patrick", lastName: "Kelly", position: "OF", eligibility: "JR", homeState: "IL", hometown: "Evanston", jerseyNumber: 16,
      hitForAvg: 55, power: 49, speed: 69, arm: 53, fielding: 33, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 51, vsLHP: 46, grit: 54, stealing: 58, running: 52, throwing: 68, recovery: 44, wRISP: 48, vsLefty: 44, poise: 48, heater: 0, agile: 55,
      abilities: ["Laser Beam", "Bases Loaded Slugger", "Good Infield Hit"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Drew", lastName: "Casper", position: "OF", eligibility: "JR", homeState: "MI", hometown: "Grand Rapids", jerseyNumber: 20,
      hitForAvg: 55, power: 50, speed: 59, arm: 54, fielding: 40, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 51, vsLHP: 49, grit: 55, stealing: 60, running: 54, throwing: 71, recovery: 45, wRISP: 48, vsLefty: 45, poise: 48, heater: 0, agile: 54,
      abilities: ["Pinch Hitter", "Contact Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Brady", lastName: "Walsh", position: "P", eligibility: "SO", homeState: "OH", hometown: "Toledo", jerseyNumber: 32,
      hitForAvg: 18, power: 15, speed: 36, arm: 40, fielding: 38, errorResistance: 50, velocity: 48, control: 44, stamina: 34, stuff: 40,
      clutch: 46, vsLHP: 43, grit: 48, stealing: 28, running: 50, throwing: 57, recovery: 30, wRISP: 33, vsLefty: 30, poise: 33, heater: 42, agile: 52,
      abilities: ["Escape Pitch"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4, 0, 0, 0]) },
    { firstName: "Kevin", lastName: "Burke", position: "P", eligibility: "JR", homeState: "MA", hometown: "Boston", jerseyNumber: 7,
      hitForAvg: 14, power: 11, speed: 30, arm: 30, fielding: 27, errorResistance: 33, velocity: 29, control: 33, stamina: 27, stuff: 29,
      clutch: 32, vsLHP: 29, grit: 33, stealing: 18, running: 33, throwing: 40, recovery: 20, wRISP: 23, vsLefty: 20, poise: 23, heater: 32, agile: 35,
      abilities: ["Cowardly"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 0, 4, 1, 0, 4, 0, 0, 0, 0]) },
  ],

  "Pittsburgh": [
    // PITCHERS (7)
    { firstName: "David", lastName: "Leslie", position: "P", eligibility: "JR", homeState: "PA", hometown: "Pittsburgh", jerseyNumber: 34,
      hitForAvg: 21, power: 16, speed: 34, arm: 70, fielding: 44, errorResistance: 57, velocity: 71, control: 66, stamina: 91, stuff: 67,
      clutch: 77, vsLHP: 72, grit: 63, stealing: 14, running: 41, throwing: 81, recovery: 61, wRISP: 61, vsLefty: 61, poise: 63, heater: 63, agile: 50,
      abilities: ["Strong Starter", "Wild Fastball", "Decisive", "Full Throttle"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [1, 4, 0, 0, 0, 0, 4, 1, 0, 0]) },
    { firstName: "Vincent", lastName: "Spizzoucco", position: "P", eligibility: "JR", homeState: "PA", hometown: "Philadelphia", jerseyNumber: 29,
      hitForAvg: 16, power: 12, speed: 32, arm: 50, fielding: 31, errorResistance: 43, velocity: 55, control: 48, stamina: 80, stuff: 47,
      clutch: 59, vsLHP: 57, grit: 60, stealing: 11, running: 31, throwing: 63, recovery: 44, wRISP: 44, vsLefty: 45, poise: 46, heater: 50, agile: 37,
      abilities: ["Guts", "Natural Shuuto"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 3, 4, 0, 0, 4, 0, 0, 1, 0]) },
    { firstName: "Drew", lastName: "Lafferty", position: "P", eligibility: "JR", homeState: "PA", hometown: "Allentown", jerseyNumber: 41,
      hitForAvg: 15, power: 12, speed: 32, arm: 49, fielding: 31, errorResistance: 43, velocity: 54, control: 48, stamina: 89, stuff: 46,
      clutch: 58, vsLHP: 55, grit: 60, stealing: 11, running: 32, throwing: 63, recovery: 43, wRISP: 43, vsLefty: 44, poise: 46, heater: 46, agile: 40,
      abilities: ["Low Ball", "Winner's Luck"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [1, 0, 0, 0, 0, 0, 4, 0, 0, 3]) },
    { firstName: "Mikey", lastName: "Gray", position: "P", eligibility: "JR", homeState: "PA", hometown: "Erie", jerseyNumber: 27,
      hitForAvg: 14, power: 12, speed: 32, arm: 47, fielding: 27, errorResistance: 40, velocity: 48, control: 43, stamina: 94, stuff: 44,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 12, running: 32, throwing: 61, recovery: 36, wRISP: 42, vsLefty: 42, poise: 45, heater: 46, agile: 38,
      abilities: ["Fireman", "Escape Pitch"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 3, 4, 0, 0, 0, 0]) },
    { firstName: "Daniel", lastName: "McAuliff", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Cherry Hill", jerseyNumber: 38,
      hitForAvg: 15, power: 12, speed: 33, arm: 49, fielding: 29, errorResistance: 40, velocity: 52, control: 44, stamina: 56, stuff: 46,
      clutch: 59, vsLHP: 56, grit: 61, stealing: 12, running: 33, throwing: 62, recovery: 37, wRISP: 44, vsLefty: 44, poise: 46, heater: 46, agile: 40,
      abilities: ["Fireman", "Gyroball"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 1, 3, 0, 0, 0, 0, 4]) },
    { firstName: "Ryan", lastName: "Kowalski", position: "P", eligibility: "SO", homeState: "PA", hometown: "Scranton", jerseyNumber: 44,
      hitForAvg: 10, power: 9, speed: 30, arm: 28, fielding: 17, errorResistance: 29, velocity: 42, control: 26, stamina: 38, stuff: 34,
      clutch: 36, vsLHP: 34, grit: 37, stealing: 8, running: 23, throwing: 42, recovery: 21, wRISP: 21, vsLefty: 23, poise: 23, heater: 28, agile: 27,
      abilities: ["Strength Distribution", "Wild Fastball", "Sharpness"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 0, 0, 0, 0, 4, 4, 0, 1, 0]) },
    // CATCHERS (2)
    { firstName: "Grant", lastName: "Talbot", position: "C", eligibility: "JR", homeState: "PA", hometown: "State College", jerseyNumber: 12,
      hitForAvg: 63, power: 44, speed: 51, arm: 54, fielding: 52, errorResistance: 63, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 52, grit: 59, stealing: 46, running: 46, throwing: 63, recovery: 50, wRISP: 53, vsLefty: 50, poise: 56, heater: 0, agile: 40,
      abilities: ["Storming Home"], potential: "B+", catcherAbility: 62,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Nick", lastName: "Barber", position: "C", eligibility: "SO", homeState: "OH", hometown: "Akron", jerseyNumber: 25,
      hitForAvg: 43, power: 39, speed: 50, arm: 49, fielding: 39, errorResistance: 27, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 43, vsLHP: 39, grit: 40, stealing: 34, running: 37, throwing: 55, recovery: 33, wRISP: 33, vsLefty: 29, poise: 33, heater: 0, agile: 29,
      abilities: ["Batter Intimidator", "Opposite Field Hitter"], potential: "B", catcherAbility: 43,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // INFIELDERS (7)
    { firstName: "Caden", lastName: "Dulin", position: "2B", eligibility: "JR", homeState: "PA", hometown: "Bethel Park", jerseyNumber: 5,
      hitForAvg: 58, power: 46, speed: 52, arm: 43, fielding: 39, errorResistance: 28, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 49, grit: 53, stealing: 46, running: 46, throwing: 57, recovery: 41, wRISP: 52, vsLefty: 47, poise: 50, heater: 0, agile: 44,
      abilities: ["Spray Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Luke", lastName: "Cantwell", position: "1B", eligibility: "JR", homeState: "PA", hometown: "Lancaster", jerseyNumber: 24,
      hitForAvg: 56, power: 57, speed: 41, arm: 59, fielding: 59, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 49, grit: 53, stealing: 46, running: 46, throwing: 59, recovery: 43, wRISP: 52, vsLefty: 47, poise: 50, heater: 0, agile: 35,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Marco", lastName: "Pellegrini", position: "SS", eligibility: "JR", homeState: "PA", hometown: "Moon Township", jerseyNumber: 2,
      hitForAvg: 63, power: 53, speed: 63, arm: 58, fielding: 50, errorResistance: 63, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 46, grit: 49, stealing: 46, running: 49, throwing: 63, recovery: 43, wRISP: 46, vsLefty: 43, poise: 46, heater: 0, agile: 53,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "S",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Evan", lastName: "DeLuca", position: "3B", eligibility: "JR", homeState: "PA", hometown: "Cranberry Township", jerseyNumber: 15,
      hitForAvg: 62, power: 58, speed: 61, arm: 63, fielding: 50, errorResistance: 40, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 51, vsLHP: 48, grit: 54, stealing: 46, running: 46, throwing: 63, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 48,
      abilities: ["Contact Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Tyler", lastName: "Kozak", position: "2B", eligibility: "SO", homeState: "PA", hometown: "Greensburg", jerseyNumber: 9,
      hitForAvg: 44, power: 38, speed: 59, arm: 57, fielding: 50, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 38, grit: 38, stealing: 54, running: 50, throwing: 51, recovery: 31, wRISP: 32, vsLefty: 30, poise: 32, heater: 0, agile: 39,
      abilities: ["Timely Whiff"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Brandon", lastName: "Russo", position: "1B", eligibility: "FR", homeState: "NJ", hometown: "Morristown", jerseyNumber: 23,
      hitForAvg: 41, power: 44, speed: 50, arm: 26, fielding: 56, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 41, grit: 38, stealing: 50, running: 53, throwing: 53, recovery: 31, wRISP: 32, vsLefty: 30, poise: 32, heater: 0, agile: 31,
      abilities: ["Home Defense", "Contact Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Gavin", lastName: "Torres", position: "SS", eligibility: "FR", homeState: "PA", hometown: "Reading", jerseyNumber: 11,
      hitForAvg: 38, power: 35, speed: 57, arm: 47, fielding: 35, errorResistance: 22, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 38, grit: 44, stealing: 54, running: 51, throwing: 52, recovery: 27, wRISP: 28, vsLefty: 25, poise: 28, heater: 0, agile: 41,
      abilities: ["Chance Maker"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // OUTFIELDERS (9)
    { firstName: "AJ", lastName: "Nessler", position: "OF", eligibility: "JR", homeState: "PA", hometown: "Monroeville", jerseyNumber: 1,
      hitForAvg: 59, power: 46, speed: 59, arm: 56, fielding: 56, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 49, grit: 51, stealing: 51, running: 54, throwing: 61, recovery: 40, wRISP: 48, vsLefty: 45, poise: 48, heater: 0, agile: 48,
      abilities: ["Spray Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Jayden", lastName: "Melendez", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Miami", jerseyNumber: 10,
      hitForAvg: 63, power: 59, speed: 63, arm: 47, fielding: 35, errorResistance: 63, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 47, grit: 48, stealing: 50, running: 53, throwing: 63, recovery: 40, wRISP: 45, vsLefty: 42, poise: 45, heater: 0, agile: 50,
      abilities: ["Push", "Disturbance", "Multi-Hit"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    // Mason Ligenza — FR OF — PG All-American / Top-50 national
    { firstName: "Mason", lastName: "Ligenza", position: "OF", eligibility: "FR", homeState: "IL", hometown: "Naperville", jerseyNumber: 21,
      hitForAvg: 59, power: 53, speed: 47, arm: 30, fielding: 59, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 51, grit: 38, stealing: 54, running: 48, throwing: 61, recovery: 34, wRISP: 37, vsLefty: 34, poise: 37, heater: 0, agile: 51,
      abilities: ["Home Defense"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Dom", lastName: "Marrazzo", position: "OF", eligibility: "JR", homeState: "PA", hometown: "Canonsburg", jerseyNumber: 16,
      hitForAvg: 63, power: 60, speed: 63, arm: 53, fielding: 41, errorResistance: 63, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 50, grit: 56, stealing: 46, running: 53, throwing: 63, recovery: 48, wRISP: 51, vsLefty: 48, poise: 51, heater: 0, agile: 57,
      abilities: ["Timely Whiff"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "S",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Cole", lastName: "Peterson", position: "OF", eligibility: "SO", homeState: "PA", hometown: "Williamsport", jerseyNumber: 20,
      hitForAvg: 60, power: 54, speed: 50, arm: 63, fielding: 63, errorResistance: 63, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 46, running: 53, throwing: 63, recovery: 44, wRISP: 46, vsLefty: 42, poise: 46, heater: 0, agile: 58,
      abilities: ["Laser Beam", "Defensive Artisan", "Good Mood"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Jason", lastName: "Mitchell", position: "OF", eligibility: "FR", homeState: "PA", hometown: "West Chester", jerseyNumber: 32,
      hitForAvg: 38, power: 36, speed: 42, arm: 52, fielding: 56, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 38, grit: 41, stealing: 54, running: 51, throwing: 55, recovery: 30, wRISP: 30, vsLefty: 27, poise: 30, heater: 0, agile: 44,
      abilities: ["Defensive Artisan", "Batter Intimidator"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "R",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Anthony", lastName: "Ricci", position: "P", eligibility: "FR", homeState: "NY", hometown: "Staten Island", jerseyNumber: 30,
      hitForAvg: 13, power: 11, speed: 29, arm: 27, fielding: 25, errorResistance: 32, velocity: 29, control: 33, stamina: 34, stuff: 25,
      clutch: 28, vsLHP: 25, grit: 29, stealing: 20, running: 36, throwing: 41, recovery: 18, wRISP: 18, vsLefty: 16, poise: 18, heater: 28, agile: 39,
      abilities: ["Quick Hands", "True Slider"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 0, 4, 1, 0, 4, 0, 0, 0, 0]) },
    { firstName: "Chris", lastName: "Varga", position: "P", eligibility: "JR", homeState: "PA", hometown: "Bethlehem", jerseyNumber: 7,
      hitForAvg: 17, power: 14, speed: 35, arm: 36, fielding: 33, errorResistance: 46, velocity: 37, control: 39, stamina: 40, stuff: 35,
      clutch: 42, vsLHP: 39, grit: 43, stealing: 24, running: 43, throwing: 52, recovery: 26, wRISP: 28, vsLefty: 26, poise: 28, heater: 38, agile: 46,
      abilities: ["Escape Pitch", "Guts"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 0, 0, 0, 0, 4, 0, 0, 3]) },
    { firstName: "Mike", lastName: "Brennan", position: "P", eligibility: "SO", homeState: "PA", hometown: "Norristown", jerseyNumber: 8,
      hitForAvg: 18, power: 15, speed: 35, arm: 38, fielding: 35, errorResistance: 46, velocity: 38, control: 42, stamina: 31, stuff: 36,
      clutch: 43, vsLHP: 39, grit: 44, stealing: 25, running: 46, throwing: 55, recovery: 28, wRISP: 30, vsLefty: 27, poise: 30, heater: 41, agile: 50,
      abilities: ["Sharpness"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 3, 1, 0, 4, 0, 0, 0, 0]) },
      { firstName: "Lorenzo", lastName: "Carrier", position: "P", eligibility: "SR", homeState: "PA", hometown: "Pittsburgh", jerseyNumber: 51,
      hitForAvg: 0, power: 0, speed: 0, arm: 0, fielding: 0, errorResistance: 0, velocity: 60, control: 59, stamina: 7, stuff: 51,
      clutch: 0, vsLHP: 0, grit: 0, stealing: 0, running: 0, throwing: 0, recovery: 0, wRISP: 0, vsLefty: 0, poise: 0, heater: 0, agile: 0,
      abilities: ["Guts", "Strong Finisher"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      pitchFB: 1, pitch2S: 0, pitchSL: 1, pitchCB: 0, pitchCH: 1, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
],
};
