import { RealPlayer } from "./realRosters";
import { pitchMix, noPitches } from "./pitchMixHelpers";

export const ACC_BATCH1_ROSTERS: Record<string, RealPlayer[]> = {
  "Clemson": [
    { firstName: "Aidan", lastName: "Knaak", position: "P", eligibility: "SO", homeState: "FL", hometown: "Fort Myers", jerseyNumber: 34,
      hitForAvg: 22, power: 18, speed: 41, arm: 84, fielding: 51, errorResistance: 66, velocity: 86, control: 73, stamina: 74, stuff: 82,
      clutch: 96, vsLHP: 90, grit: 96, stealing: 17, running: 50, throwing: 96, recovery: 73, wRISP: 77, vsLefty: 78, poise: 80, heater: 89, agile: 52,
      abilities: ["Explosive Fastball", "Strong Starter", "Intimidator", "Tunneling", "Heavy Ball", "Strong Finisher", "Decisive"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [1, 0, 0, 0, 0, 6, 6]) },
    { firstName: "Michael", lastName: "Sharman", position: "P", eligibility: "JR", homeState: "TN", hometown: "Knoxville", jerseyNumber: 29,
      hitForAvg: 12, power: 10, speed: 31, arm: 45, fielding: 27, errorResistance: 39, velocity: 51, control: 44, stamina: 43, stuff: 43,
      clutch: 55, vsLHP: 52, grit: 56, stealing: 9, running: 28, throwing: 60, recovery: 40, wRISP: 40, vsLefty: 41, poise: 43, heater: 46, agile: 34,
      abilities: ["Strong Starter", "Grit"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...pitchMix(1, [0, 5, 6, 1, 0, 0, 0]) },
    { firstName: "Cole", lastName: "Stokes", position: "P", eligibility: "JR", homeState: "OR", hometown: "Portland", jerseyNumber: 36,
      hitForAvg: 15, power: 14, speed: 34, arm: 62, fielding: 33, errorResistance: 44, velocity: 74, control: 52, stamina: 52, stuff: 60,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 14, running: 36, throwing: 77, recovery: 44, wRISP: 50, vsLefty: 52, poise: 52, heater: 69, agile: 44,
      abilities: ["Explosive Fastball", "Constant Speed"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 6, 3, 1, 0, 0, 0]) },
    { firstName: "Talan", lastName: "Bell", position: "P", eligibility: "SO", homeState: "SC", hometown: "Simpsonville", jerseyNumber: 44,
      hitForAvg: 14, power: 11, speed: 33, arm: 46, fielding: 28, errorResistance: 40, velocity: 52, control: 46, stamina: 45, stuff: 44,
      clutch: 54, vsLHP: 53, grit: 57, stealing: 11, running: 32, throwing: 62, recovery: 41, wRISP: 40, vsLefty: 43, poise: 43, heater: 49, agile: 39,
      abilities: ["Guts", "Top Gear"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 6, 1, 0, 0, 0]) },
    { firstName: "Drew", lastName: "Titsworth", position: "P", eligibility: "JR", homeState: "MI", hometown: "Frankenmuth", jerseyNumber: 27,
      hitForAvg: 19, power: 18, speed: 42, arm: 59, fielding: 37, errorResistance: 52, velocity: 66, control: 56, stamina: 59, stuff: 55,
      clutch: 70, vsLHP: 65, grit: 72, stealing: 13, running: 40, throwing: 75, recovery: 51, wRISP: 51, vsLefty: 51, poise: 54, heater: 62, agile: 47,
      abilities: ["Guts", "Heavy Ball", "Inside Pitch"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Jacob", lastName: "McGovern", position: "P", eligibility: "JR", homeState: "GA", hometown: "Roswell", jerseyNumber: 38,
      hitForAvg: 7, power: 6, speed: 22, arm: 21, fielding: 13, errorResistance: 22, velocity: 31, control: 20, stamina: 19, stuff: 22,
      clutch: 28, vsLHP: 26, grit: 29, stealing: 6, running: 18, throwing: 30, recovery: 18, wRISP: 18, vsLefty: 18, poise: 19, heater: 22, agile: 20,
      abilities: ["Fireman"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Braeden", lastName: "Moehler", position: "P", eligibility: "JR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 41,
      hitForAvg: 11, power: 8, speed: 28, arm: 30, fielding: 20, errorResistance: 30, velocity: 28, control: 37, stamina: 28, stuff: 27,
      clutch: 40, vsLHP: 37, grit: 41, stealing: 7, running: 22, throwing: 43, recovery: 26, wRISP: 26, vsLefty: 27, poise: 27, heater: 32, agile: 27,
      abilities: ["Heavy Ball"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 4, 0, 3, 0, 0]) },
    { firstName: "Zach", lastName: "Allen", position: "P", eligibility: "JR", homeState: "SC", hometown: "Spartanburg", jerseyNumber: 33,
      hitForAvg: 9, power: 8, speed: 27, arm: 25, fielding: 17, errorResistance: 27, velocity: 40, control: 25, stamina: 23, stuff: 27,
      clutch: 34, vsLHP: 33, grit: 35, stealing: 7, running: 21, throwing: 37, recovery: 22, wRISP: 22, vsLefty: 23, poise: 23, heater: 27, agile: 24,
      abilities: ["Natural Shuuto", "Showtime", "Intimidator"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 0, 1, 3, 0, 0]) },
    { firstName: "Trey", lastName: "Harwick", position: "P", eligibility: "FR", homeState: "SC", hometown: "Greenville", jerseyNumber: 48,
      hitForAvg: 7, power: 7, speed: 27, arm: 36, fielding: 16, errorResistance: 25, velocity: 49, control: 28, stamina: 29, stuff: 37,
      clutch: 29, vsLHP: 28, grit: 30, stealing: 11, running: 25, throwing: 41, recovery: 18, wRISP: 17, vsLefty: 19, poise: 18, heater: 29, agile: 29,
      abilities: ["Cross Cannon", "Intimidator"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 6, 3, 1, 0, 0, 0]) },
    { firstName: "Camden", lastName: "Cross", position: "P", eligibility: "FR", homeState: "GA", hometown: "Alpharetta", jerseyNumber: 46,
      hitForAvg: 7, power: 7, speed: 23, arm: 23, fielding: 13, errorResistance: 21, velocity: 35, control: 19, stamina: 17, stuff: 22,
      clutch: 24, vsLHP: 23, grit: 26, stealing: 7, running: 20, throwing: 36, recovery: 15, wRISP: 15, vsLefty: 15, poise: 15, heater: 25, agile: 23,
      abilities: ["Houdini", "Release"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Cooper", lastName: "Crighton", position: "C", eligibility: "SR", homeState: "MI", hometown: "Rochester Hills", jerseyNumber: 8,
      hitForAvg: 47, power: 42, speed: 33, arm: 48, fielding: 47, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 41, grit: 47, stealing: 14, running: 29, throwing: 50, recovery: 38, wRISP: 42, vsLefty: 39, poise: 44, heater: 0, agile: 32,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: 44,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Tyler", lastName: "Lichtenberger", position: "SS", eligibility: "SO", homeState: "NC", hometown: "Boone", jerseyNumber: 6,
      hitForAvg: 50, power: 38, speed: 64, arm: 44, fielding: 45, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 39, grit: 44, stealing: 29, running: 39, throwing: 45, recovery: 34, wRISP: 41, vsLefty: 39, poise: 41, heater: 0, agile: 42,
      abilities: ["Defensive Artisan", "Contact Hitter"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Jarren", lastName: "Purify", position: "3B", eligibility: "JR", homeState: "MI", hometown: "Detroit", jerseyNumber: 5,
      hitForAvg: 48, power: 49, speed: 44, arm: 44, fielding: 40, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 40, grit: 44, stealing: 17, running: 32, throwing: 45, recovery: 36, wRISP: 42, vsLefty: 38, poise: 41, heater: 0, agile: 34,
      abilities: ["Power Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Blake", lastName: "Jarrell", position: "2B", eligibility: "SR", homeState: "SC", hometown: "Greer", jerseyNumber: 3,
      hitForAvg: 60, power: 44, speed: 69, arm: 52, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 52, grit: 58, stealing: 32, running: 45, throwing: 52, recovery: 45, wRISP: 52, vsLefty: 50, poise: 56, heater: 0, agile: 50,
      abilities: ["Chance Maker"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Collin", lastName: "Priest", position: "1B", eligibility: "JR", homeState: "GA", hometown: "Marietta", jerseyNumber: 18,
      hitForAvg: 57, power: 63, speed: 53, arm: 54, fielding: 50, errorResistance: 49, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 54, stealing: 17, running: 39, throwing: 55, recovery: 44, wRISP: 52, vsLefty: 49, poise: 52, heater: 0, agile: 42,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Josh", lastName: "Castellani", position: "3B", eligibility: "JR", homeState: "FL", hometown: "Orlando", jerseyNumber: 22,
      hitForAvg: 34, power: 37, speed: 46, arm: 27, fielding: 32, errorResistance: 28, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 30, vsLHP: 28, grit: 31, stealing: 7, running: 20, throwing: 28, recovery: 25, wRISP: 30, vsLefty: 27, poise: 28, heater: 0, agile: 21,
      abilities: ["Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Bryce", lastName: "Clavon", position: "OF", eligibility: "SO", homeState: "GA", hometown: "Athens", jerseyNumber: 1,
      hitForAvg: 47, power: 42, speed: 54, arm: 42, fielding: 41, errorResistance: 41, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 41, vsLHP: 39, grit: 42, stealing: 35, running: 43, throwing: 43, recovery: 35, wRISP: 41, vsLefty: 38, poise: 41, heater: 0, agile: 44,
      abilities: ["Express Baserunning"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Austin", lastName: "Gaffney", position: "OF", eligibility: "JR", homeState: "IN", hometown: "West Lafayette", jerseyNumber: 10,
      hitForAvg: 52, power: 41, speed: 50, arm: 42, fielding: 40, errorResistance: 39, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 42, grit: 45, stealing: 24, running: 37, throwing: 43, recovery: 37, wRISP: 45, vsLefty: 40, poise: 43, heater: 0, agile: 39,
      abilities: ["Contact Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...noPitches },
    { firstName: "TP", lastName: "Wentworth", position: "OF", eligibility: "SO", homeState: "SC", hometown: "Charleston", jerseyNumber: 7,
      hitForAvg: 69, power: 59, speed: 72, arm: 66, fielding: 63, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 59, vsLHP: 56, grit: 60, stealing: 42, running: 63, throwing: 69, recovery: 52, wRISP: 56, vsLefty: 53, poise: 59, heater: 0, agile: 66,
      abilities: ["Pull Hit"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Peyton", lastName: "Caldwell", position: "OF", eligibility: "JR", homeState: "SC", hometown: "Anderson", jerseyNumber: 20,
      hitForAvg: 57, power: 52, speed: 62, arm: 56, fielding: 55, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 47, grit: 53, stealing: 32, running: 52, throwing: 57, recovery: 46, wRISP: 50, vsLefty: 46, poise: 52, heater: 0, agile: 55,
      abilities: ["Error Prone"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Marcus", lastName: "Whitfield", position: "OF", eligibility: "SO", homeState: "GA", hometown: "Lawrenceville", jerseyNumber: 14,
      hitForAvg: 73, power: 64, speed: 79, arm: 71, fielding: 69, errorResistance: 68, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 65, vsLHP: 59, grit: 68, stealing: 48, running: 71, throwing: 73, recovery: 58, wRISP: 63, vsLefty: 58, poise: 65, heater: 0, agile: 73,
      abilities: ["Pull Hitter", "Emergency Strength"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Carter", lastName: "Tompkins", position: "2B", eligibility: "FR", homeState: "SC", hometown: "Columbia", jerseyNumber: 12,
      hitForAvg: 36, power: 28, speed: 61, arm: 36, fielding: 30, errorResistance: 29, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 25, vsLHP: 23, grit: 27, stealing: 20, running: 32, throwing: 33, recovery: 24, wRISP: 24, vsLefty: 22, poise: 24, heater: 0, agile: 33,
      abilities: ["Trickster", "Opposite Field Hitter", "Contact Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Weston", lastName: "Brock", position: "SS", eligibility: "FR", homeState: "GA", hometown: "Augusta", jerseyNumber: 15,
      hitForAvg: 36, power: 28, speed: 58, arm: 39, fielding: 33, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 28, vsLHP: 25, grit: 30, stealing: 24, running: 39, throwing: 39, recovery: 26, wRISP: 26, vsLefty: 24, poise: 26, heater: 0, agile: 39,
      abilities: ["Express Baserunning"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Camden", lastName: "Duffie", position: "OF", eligibility: "FR", homeState: "SC", hometown: "Rock Hill", jerseyNumber: 32,
      hitForAvg: 38, power: 34, speed: 58, arm: 41, fielding: 36, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 31, vsLHP: 29, grit: 32, stealing: 28, running: 42, throwing: 42, recovery: 30, wRISP: 30, vsLefty: 28, poise: 30, heater: 0, agile: 45,
      abilities: ["Consigliere"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Hayden", lastName: "Foster", position: "C", eligibility: "JR", homeState: "SC", hometown: "Clemson", jerseyNumber: 17,
      hitForAvg: 37, power: 30, speed: 35, arm: 37, fielding: 30, errorResistance: 29, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 28, vsLHP: 26, grit: 29, stealing: 17, running: 28, throwing: 34, recovery: 25, wRISP: 27, vsLefty: 25, poise: 28, heater: 0, agile: 30,
      abilities: ["Inside Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
  ],

  "Duke": [
    { firstName: "Aidan", lastName: "Weaver", position: "P", eligibility: "JR", homeState: "PA", hometown: "Pittsburgh", jerseyNumber: 22,
      hitForAvg: 25, power: 22, speed: 40, arm: 81, fielding: 54, errorResistance: 67, velocity: 82, control: 81, stamina: 81, stuff: 79,
      clutch: 93, vsLHP: 87, grit: 93, stealing: 19, running: 51, throwing: 93, recovery: 75, wRISP: 75, vsLefty: 77, poise: 79, heater: 85, agile: 62,
      abilities: ["Strong Starter", "Guts", "Grit", "Intimidator", "Heavy Ball", "Winner's Luck", "Pace"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 6, 1, 0, 0, 0]) },
    { firstName: "Ben", lastName: "Dean", position: "P", eligibility: "JR", homeState: "OH", hometown: "Dayton", jerseyNumber: 33,
      hitForAvg: 11, power: 10, speed: 28, arm: 39, fielding: 24, errorResistance: 33, velocity: 45, control: 38, stamina: 37, stuff: 38,
      clutch: 46, vsLHP: 44, grit: 48, stealing: 8, running: 25, throwing: 51, recovery: 32, wRISP: 32, vsLefty: 33, poise: 35, heater: 42, agile: 31,
      abilities: ["Explosive Fastball", "Intimidator", "Heavy Ball"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 6, 4, 1, 0, 0, 0]) },
    { firstName: "Matt", lastName: "Nochowitz", position: "P", eligibility: "JR", homeState: "NY", hometown: "Cortland", jerseyNumber: 37,
      hitForAvg: 18, power: 14, speed: 39, arm: 58, fielding: 38, errorResistance: 52, velocity: 64, control: 61, stamina: 58, stuff: 54,
      clutch: 71, vsLHP: 66, grit: 73, stealing: 11, running: 36, throwing: 75, recovery: 52, wRISP: 52, vsLefty: 53, poise: 57, heater: 61, agile: 45,
      abilities: ["Guts", "Strength Distribution", "True Slider", "Precision Instrument"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [1, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Aiden", lastName: "O'Connell", position: "P", eligibility: "JR", homeState: "TN", hometown: "Nashville", jerseyNumber: 19,
      hitForAvg: 17, power: 15, speed: 41, arm: 63, fielding: 38, errorResistance: 51, velocity: 72, control: 58, stamina: 53, stuff: 61,
      clutch: 71, vsLHP: 68, grit: 74, stealing: 15, running: 46, throwing: 82, recovery: 51, wRISP: 52, vsLefty: 53, poise: 57, heater: 70, agile: 51,
      abilities: ["Fireman", "Low Ball"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 6, 0, 1, 0, 3, 0]) },
    { firstName: "Jack", lastName: "Hedrick", position: "P", eligibility: "JR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 28,
      hitForAvg: 14, power: 12, speed: 33, arm: 44, fielding: 29, errorResistance: 41, velocity: 50, control: 44, stamina: 42, stuff: 42,
      clutch: 53, vsLHP: 49, grit: 54, stealing: 12, running: 33, throwing: 57, recovery: 37, wRISP: 37, vsLefty: 40, poise: 41, heater: 48, agile: 36,
      abilities: ["Gear Change", "Intimidator"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Leverett", position: "P", eligibility: "JR", homeState: "VA", hometown: "Richmond", jerseyNumber: 31,
      hitForAvg: 10, power: 9, speed: 27, arm: 31, fielding: 20, errorResistance: 30, velocity: 32, control: 38, stamina: 31, stuff: 27,
      clutch: 36, vsLHP: 35, grit: 39, stealing: 7, running: 22, throwing: 40, recovery: 26, wRISP: 25, vsLefty: 27, poise: 27, heater: 33, agile: 25,
      abilities: ["Unlucky Pitch"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 0, 1, 3, 0, 0]) },
    { firstName: "Drew", lastName: "Hartigan", position: "P", eligibility: "SO", homeState: "MD", hometown: "Bethesda", jerseyNumber: 45,
      hitForAvg: 9, power: 9, speed: 27, arm: 24, fielding: 14, errorResistance: 24, velocity: 26, control: 20, stamina: 18, stuff: 26,
      clutch: 25, vsLHP: 25, grit: 27, stealing: 9, running: 23, throwing: 39, recovery: 16, wRISP: 15, vsLefty: 17, poise: 16, heater: 25, agile: 25,
      abilities: ["Top Gear", "Intimidator", "Groundball Pitcher"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    { firstName: "Nick", lastName: "Thornton", position: "P", eligibility: "FR", homeState: "VA", hometown: "Charlottesville", jerseyNumber: 42,
      hitForAvg: 9, power: 9, speed: 25, arm: 24, fielding: 13, errorResistance: 24, velocity: 37, control: 20, stamina: 18, stuff: 24,
      clutch: 25, vsLHP: 24, grit: 28, stealing: 8, running: 21, throwing: 37, recovery: 16, wRISP: 15, vsLefty: 16, poise: 16, heater: 26, agile: 24,
      abilities: ["Natural Shuuto", "Gas Tank", "Intimidator"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...pitchMix(1, [0, 5, 0, 1, 3, 0, 0]) },
    { firstName: "Marcus", lastName: "Holloway", position: "P", eligibility: "JR", homeState: "NC", hometown: "Durham", jerseyNumber: 35,
      hitForAvg: 10, power: 8, speed: 27, arm: 26, fielding: 17, errorResistance: 27, velocity: 38, control: 26, stamina: 26, stuff: 27,
      clutch: 33, vsLHP: 31, grit: 34, stealing: 5, running: 20, throwing: 38, recovery: 22, wRISP: 21, vsLefty: 23, poise: 23, heater: 27, agile: 24,
      abilities: ["Winner's Luck"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 5, 0, 3, 0, 0]) },
    { firstName: "Cider", lastName: "Canon", position: "C", eligibility: "JR", homeState: "NC", hometown: "Davidson", jerseyNumber: 14,
      hitForAvg: 62, power: 58, speed: 36, arm: 52, fielding: 51, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 51, grit: 54, stealing: 14, running: 28, throwing: 54, recovery: 42, wRISP: 54, vsLefty: 48, poise: 52, heater: 0, agile: 34,
      abilities: ["Consigliere", "Power Hitter"], potential: "A", catcherAbility: 48,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Gavin", lastName: "Morelli", position: "C", eligibility: "FR", homeState: "NJ", hometown: "Montclair", jerseyNumber: 24,
      hitForAvg: 38, power: 31, speed: 35, arm: 40, fielding: 38, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 29, vsLHP: 27, grit: 30, stealing: 8, running: 23, throwing: 39, recovery: 28, wRISP: 28, vsLefty: 25, poise: 28, heater: 0, agile: 25,
      abilities: ["First Pitch Hitter", "Flying Start", "Contact Hitter"], potential: "B+", catcherAbility: 38,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Jake", lastName: "Lambdin", position: "SS", eligibility: "JR", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 2,
      hitForAvg: 71, power: 56, speed: 84, arm: 70, fielding: 70, errorResistance: 70, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 59, grit: 66, stealing: 45, running: 58, throwing: 70, recovery: 54, wRISP: 63, vsLefty: 58, poise: 64, heater: 0, agile: 63,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Coltin", lastName: "Quagliano", position: "2B", eligibility: "JR", homeState: "IL", hometown: "Champaign", jerseyNumber: 7,
      hitForAvg: 39, power: 29, speed: 48, arm: 34, fielding: 38, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 34, vsLHP: 31, grit: 35, stealing: 20, running: 30, throwing: 35, recovery: 29, wRISP: 32, vsLefty: 30, poise: 34, heater: 0, agile: 32,
      abilities: ["Chance Maker"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "RJ", lastName: "Hamilton", position: "3B", eligibility: "JR", homeState: "TN", hometown: "Nashville", jerseyNumber: 11,
      hitForAvg: 54, power: 50, speed: 82, arm: 54, fielding: 51, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 45, grit: 51, stealing: 23, running: 40, throwing: 56, recovery: 42, wRISP: 47, vsLefty: 43, poise: 47, heater: 0, agile: 43,
      abilities: ["Bases Loaded Slugger", "Disturbance"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Jeff", lastName: "Lougee", position: "1B", eligibility: "SO", homeState: "MA", hometown: "Andover", jerseyNumber: 16,
      hitForAvg: 33, power: 33, speed: 45, arm: 33, fielding: 28, errorResistance: 28, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 28, vsLHP: 26, grit: 28, stealing: 9, running: 21, throwing: 30, recovery: 25, wRISP: 27, vsLefty: 25, poise: 27, heater: 0, agile: 24,
      abilities: ["Ace Killer"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Kaden", lastName: "Smith", position: "1B", eligibility: "JR", homeState: "SC", hometown: "Charleston", jerseyNumber: 21,
      hitForAvg: 47, power: 43, speed: 47, arm: 48, fielding: 46, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 41, grit: 46, stealing: 18, running: 37, throwing: 51, recovery: 39, wRISP: 42, vsLefty: 39, poise: 44, heater: 0, agile: 39,
      abilities: ["Contact Hitter", "Good Bunt", "Head-first Slide"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Brooks", lastName: "Perez", position: "3B", eligibility: "FR", homeState: "FL", hometown: "Tampa", jerseyNumber: 9,
      hitForAvg: 39, power: 39, speed: 55, arm: 39, fielding: 33, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 33, vsLHP: 29, grit: 33, stealing: 9, running: 24, throwing: 37, recovery: 28, wRISP: 31, vsLefty: 28, poise: 31, heater: 0, agile: 27,
      abilities: ["Power Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Cameron", lastName: "Wiley", position: "SS", eligibility: "FR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 3,
      hitForAvg: 27, power: 23, speed: 45, arm: 31, fielding: 26, errorResistance: 24, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 23, vsLHP: 21, grit: 23, stealing: 21, running: 31, throwing: 31, recovery: 22, wRISP: 22, vsLefty: 19, poise: 22, heater: 0, agile: 31,
      abilities: ["High Ball Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Tyler", lastName: "Albright", position: "OF", eligibility: "JR", homeState: "VA", hometown: "Fairfax", jerseyNumber: 1,
      hitForAvg: 56, power: 52, speed: 71, arm: 49, fielding: 48, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 48, grit: 50, stealing: 29, running: 43, throwing: 50, recovery: 40, wRISP: 49, vsLefty: 47, poise: 49, heater: 0, agile: 47,
      abilities: ["Consigliere"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Michael", lastName: "DiMartini", position: "OF", eligibility: "JR", homeState: "OH", hometown: "Dayton", jerseyNumber: 5,
      hitForAvg: 94, power: 80, speed: 84, arm: 72, fielding: 71, errorResistance: 67, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 80, vsLHP: 78, grit: 80, stealing: 49, running: 67, throwing: 77, recovery: 64, wRISP: 84, vsLefty: 77, poise: 80, heater: 0, agile: 72,
      abilities: ["Contact Hitter", "Power Hitter"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...noPitches },
    { firstName: "Adin", lastName: "Zorn", position: "OF", eligibility: "JR", homeState: "OH", hometown: "Dayton", jerseyNumber: 8,
      hitForAvg: 46, power: 39, speed: 50, arm: 42, fielding: 41, errorResistance: 40, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 39, vsLHP: 36, grit: 40, stealing: 27, running: 39, throwing: 44, recovery: 35, wRISP: 37, vsLefty: 35, poise: 39, heater: 0, agile: 41,
      abilities: ["Hit Machine", "vs. Breaking Pitches"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Bobby", lastName: "Marsh", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Miami", jerseyNumber: 17,
      hitForAvg: 48, power: 41, speed: 53, arm: 47, fielding: 44, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 41, vsLHP: 38, grit: 42, stealing: 26, running: 41, throwing: 48, recovery: 37, wRISP: 40, vsLefty: 37, poise: 41, heater: 0, agile: 44,
      abilities: ["Error Prone"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Nolan", lastName: "Johnson", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Coral Gables", jerseyNumber: 13,
      hitForAvg: 52, power: 46, speed: 55, arm: 50, fielding: 47, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 46, vsLHP: 42, grit: 47, stealing: 27, running: 43, throwing: 52, recovery: 41, wRISP: 43, vsLefty: 41, poise: 46, heater: 0, agile: 47,
      abilities: ["Artist"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Nate", lastName: "Rodriguez", position: "OF", eligibility: "FR", homeState: "NC", hometown: "Chapel Hill", jerseyNumber: 10,
      hitForAvg: 35, power: 31, speed: 53, arm: 37, fielding: 34, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 30, vsLHP: 26, grit: 31, stealing: 25, running: 37, throwing: 39, recovery: 29, wRISP: 29, vsLefty: 25, poise: 29, heater: 0, agile: 39,
      abilities: ["Defensive Artisan"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...noPitches },
    { firstName: "Ethan", lastName: "Brooks", position: "P", eligibility: "JR", homeState: "VA", hometown: "Virginia Beach", jerseyNumber: 6,
      hitForAvg: 16, power: 13, speed: 30, arm: 34, fielding: 30, errorResistance: 40, velocity: 36, control: 36, stamina: 37, stuff: 32,
      clutch: 39, vsLHP: 37, grit: 40, stealing: 26, running: 42, throwing: 48, recovery: 25, wRISP: 28, vsLefty: 25, poise: 29, heater: 34, agile: 44,
      abilities: ["Quick Hands"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
  ],

  "Florida State": [
      // 35-15, D1B #14, Link Jarrett Yr 4. Lost Arnold/Volini/Lodise/Faurot to draft. Bailey season-ending injury. 13 portal arms in.
      // PITCHERS (10) — 1-8 pitch scale
      // Trey Beard — LHP JR Friday ace (FAU transfer), 118K/86 IP / 32 BB in 2025, 33.7% K-rate, highest LHP release point — TEAM ELITE STUFF
      { firstName: "Trey", lastName: "Beard", position: "P", eligibility: "JR", homeState: "FL", hometown: "Boca Raton", jerseyNumber: 27,
        hitForAvg: 16, power: 12, speed: 38, arm: 77, fielding: 43, errorResistance: 58, velocity: 82, control: 74, stamina: 81, stuff: 83,
        clutch: 88, vsLHP: 88, grit: 88, stealing: 10, running: 35, throwing: 88, recovery: 67, wRISP: 74, vsLefty: 81, poise: 77, heater: 74, agile: 48,
        abilities: ["Star of Victory", "Intimidator", "Fireman", "Heavy Ball", "Strong Finisher", "Winner's Luck"], potential: "A+", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [7, 0, 0, 1, 0, 6, 0]) },
      // Cooper Whited — LHP JR Saturday starter, confirmed in starting mix
      { firstName: "Cooper", lastName: "Whited", position: "P", eligibility: "JR", homeState: "FL", hometown: "Tallahassee", jerseyNumber: 41,
        hitForAvg: 15, power: 10, speed: 34, arm: 64, fielding: 39, errorResistance: 50, velocity: 67, control: 62, stamina: 65, stuff: 61,
        clutch: 76, vsLHP: 82, grit: 76, stealing: 8, running: 32, throwing: 78, recovery: 55, wRISP: 55, vsLefty: 65, poise: 61, heater: 65, agile: 44,
        abilities: ["Strong Starter", "Fireman", "Perfect Combustion", "Heavy Ball", "Bad Ball Hitter"], potential: "A-", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [6, 0, 0, 1, 0, 5, 0]) },
      // John Abraham — JR RHP Sunday/rotation
      { firstName: "John", lastName: "Abraham", position: "P", eligibility: "JR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 44,
        hitForAvg: 13, power: 11, speed: 35, arm: 60, fielding: 36, errorResistance: 47, velocity: 64, control: 59, stamina: 60, stuff: 57,
        clutch: 70, vsLHP: 64, grit: 70, stealing: 8, running: 33, throwing: 75, recovery: 51, wRISP: 51, vsLefty: 53, poise: 56, heater: 62, agile: 43,
        abilities: ["Guts", "Wild Fastball"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
      // Joey Mebil — RHP closer (struck out the side in 9th vs Jacksonville)
      { firstName: "Joey", lastName: "Mebil", position: "P", eligibility: "JR", homeState: "FL", hometown: "Miami", jerseyNumber: 30,
        hitForAvg: 12, power: 10, speed: 32, arm: 59, fielding: 33, errorResistance: 44, velocity: 62, control: 54, stamina: 39, stuff: 57,
        clutch: 75, vsLHP: 69, grit: 69, stealing: 8, running: 29, throwing: 73, recovery: 44, wRISP: 54, vsLefty: 55, poise: 59, heater: 60, agile: 39,
        abilities: ["Fireman", "Doctor K", "Intimidator", "Gyroball"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 7, 0, 1, 0, 4, 0]) },
      // Brodie Purcell — JR RHP RP
      { firstName: "Brodie", lastName: "Purcell", position: "P", eligibility: "JR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 38,
        hitForAvg: 11, power: 9, speed: 29, arm: 51, fielding: 29, errorResistance: 40, velocity: 54, control: 46, stamina: 35, stuff: 47,
        clutch: 60, vsLHP: 56, grit: 62, stealing: 9, running: 29, throwing: 64, recovery: 38, wRISP: 43, vsLefty: 44, poise: 47, heater: 53, agile: 37,
        abilities: ["Fireman", "Explosive Fastball", "Flyball Pitcher", "Intimidator"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 7, 0, 1, 0, 4, 0]) },
      // Ernesto Lugo-Canchola — RHP RP, high-leverage
      { firstName: "Ernesto", lastName: "Lugo-Canchola", position: "P", eligibility: "FR", homeState: "PR", hometown: "San Juan", jerseyNumber: 39,
        hitForAvg: 11, power: 10, speed: 30, arm: 51, fielding: 29, errorResistance: 40, velocity: 54, control: 48, stamina: 37, stuff: 47,
        clutch: 61, vsLHP: 56, grit: 61, stealing: 8, running: 29, throwing: 62, recovery: 39, wRISP: 44, vsLefty: 44, poise: 47, heater: 52, agile: 37,
        abilities: ["Guts", "Tunneling", "Natural Shuuto", "Intimidator"], potential: "B+", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
      // Billy Barlow — RHP RP
      { firstName: "Billy", lastName: "Barlow", position: "P", eligibility: "JR", homeState: "FL", hometown: "Jacksonville", jerseyNumber: 35,
        hitForAvg: 10, power: 7, speed: 25, arm: 40, fielding: 24, errorResistance: 33, velocity: 43, control: 40, stamina: 29, stuff: 37,
        clutch: 49, vsLHP: 45, grit: 50, stealing: 6, running: 24, throwing: 52, recovery: 31, wRISP: 33, vsLefty: 35, poise: 37, heater: 41, agile: 30,
        abilities: ["Explosive Fastball", "Kageura", "Intimidator"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
      // Hunter Knier — RHP, 2.0 scoreless IP, 0H/0BB/1K
      { firstName: "Hunter", lastName: "Knier", position: "P", eligibility: "SO", homeState: "FL", hometown: "Pensacola", jerseyNumber: 36,
        hitForAvg: 9, power: 7, speed: 24, arm: 40, fielding: 24, errorResistance: 33, velocity: 44, control: 41, stamina: 38, stuff: 38,
        clutch: 49, vsLHP: 46, grit: 49, stealing: 7, running: 23, throwing: 51, recovery: 34, wRISP: 34, vsLefty: 36, poise: 38, heater: 41, agile: 30,
        abilities: ["Inside Pitch", "Fireman"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 0, 1, 4, 0, 0]) },
      // Marcus Harrell — FR RHP depth
      { firstName: "Marcus", lastName: "Harrell", position: "P", eligibility: "FR", homeState: "FL", hometown: "Jacksonville", jerseyNumber: 48,
        hitForAvg: 6, power: 5, speed: 19, arm: 29, fielding: 13, errorResistance: 20, velocity: 35, control: 25, stamina: 23, stuff: 31,
        clutch: 22, vsLHP: 20, grit: 23, stealing: 6, running: 17, throwing: 32, recovery: 16, wRISP: 14, vsLefty: 15, poise: 15, heater: 24, agile: 22,
        abilities: ["Monster Stuff", "Guts"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "deep", hairColor: "black", hairStyle: "fade",
        ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
      // Jaylen Cartwright — FR RHP depth
      { firstName: "Jaylen", lastName: "Cartwright", position: "P", eligibility: "FR", homeState: "GA", hometown: "Valdosta", jerseyNumber: 46,
        hitForAvg: 8, power: 8, speed: 25, arm: 25, fielding: 13, errorResistance: 24, velocity: 36, control: 20, stamina: 20, stuff: 24,
        clutch: 25, vsLHP: 24, grit: 25, stealing: 7, running: 22, throwing: 37, recovery: 16, wRISP: 15, vsLefty: 16, poise: 16, heater: 27, agile: 25,
        abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "deep", hairColor: "black", hairStyle: "fade",
        ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
      // CATCHERS (2)
      // Hunter Carns — JR C, returning starter
      { firstName: "Hunter", lastName: "Carns", position: "C", eligibility: "JR", homeState: "GA", hometown: "Buford", jerseyNumber: 12,
        hitForAvg: 43, power: 40, speed: 26, arm: 44, fielding: 42, errorResistance: 39, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 39, vsLHP: 36, grit: 41, stealing: 9, running: 22, throwing: 44, recovery: 32, wRISP: 39, vsLefty: 36, poise: 39, heater: 0, agile: 25,
        abilities: ["High-Speed Laser", "Consigliere", "Defensive Artisan"], potential: "A+", catcherAbility: 49,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Nate Cmeyla — SR C
      { firstName: "Nate", lastName: "Cmeyla", position: "C", eligibility: "SR", homeState: "FL", hometown: "Tampa", jerseyNumber: 24,
        hitForAvg: 35, power: 30, speed: 28, arm: 32, fielding: 32, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 29, vsLHP: 28, grit: 31, stealing: 6, running: 18, throwing: 34, recovery: 26, wRISP: 28, vsLefty: 26, poise: 29, heater: 0, agile: 21,
        abilities: ["Resilient", "Good Infield Hit", "Disturbance"], potential: "B+", catcherAbility: 31,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // INFIELDERS (7)
      // Cal Fisher — 3B JR, key returning bat
      { firstName: "Cal", lastName: "Fisher", position: "3B", eligibility: "JR", homeState: "VA", hometown: "Richmond", jerseyNumber: 18,
        hitForAvg: 79, power: 72, speed: 57, arm: 61, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 72, vsLHP: 65, grit: 72, stealing: 19, running: 43, throwing: 61, recovery: 50, wRISP: 72, vsLefty: 65, poise: 72, heater: 0, agile: 47,
        abilities: ["Gambler", "Power Hitter", "Consigliere", "Contact Hitter"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Gabe Nard — 2B SR, table-setter
      { firstName: "Gabe", lastName: "Nard", position: "2B", eligibility: "SR", homeState: "GA", hometown: "Savannah", jerseyNumber: 7,
        hitForAvg: 55, power: 42, speed: 57, arm: 50, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 48, vsLHP: 45, grit: 50, stealing: 27, running: 43, throwing: 50, recovery: 39, wRISP: 46, vsLefty: 43, poise: 48, heater: 0, agile: 46,
        abilities: ["Chance Maker", "Defensive Artisan"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Carter McCulley — 2B/INF, breakout 2026 performer (featured after Pitt sweep)
      { firstName: "Carter", lastName: "McCulley", position: "2B", eligibility: "JR", homeState: "FL", hometown: "Orlando", jerseyNumber: 6,
        hitForAvg: 64, power: 57, speed: 62, arm: 49, fielding: 51, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 58, vsLHP: 53, grit: 58, stealing: 22, running: 41, throwing: 49, recovery: 40, wRISP: 58, vsLefty: 53, poise: 58, heater: 0, agile: 45,
        abilities: ["Contact Hitter", "Power Hitter"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Jace Estes — INF middle infield candidate
      { firstName: "Jace", lastName: "Estes", position: "SS", eligibility: "SO", homeState: "FL", hometown: "Tampa", jerseyNumber: 4,
        hitForAvg: 45, power: 39, speed: 52, arm: 44, fielding: 44, errorResistance: 43, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 40, vsLHP: 37, grit: 42, stealing: 22, running: 38, throwing: 44, recovery: 34, wRISP: 38, vsLefty: 35, poise: 40, heater: 0, agile: 43,
        abilities: ["Defensive Artisan"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Ty MeGahee — utility/INF, active contributor
      { firstName: "Ty", lastName: "MeGahee", position: "1B", eligibility: "JR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 13,
        hitForAvg: 35, power: 37, speed: 30, arm: 28, fielding: 29, errorResistance: 28, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 30, vsLHP: 29, grit: 32, stealing: 5, running: 20, throwing: 28, recovery: 24, wRISP: 30, vsLefty: 29, poise: 30, heater: 0, agile: 21,
        abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Ethan Rigsby — 2B FR depth
      { firstName: "Ethan", lastName: "Rigsby", position: "2B", eligibility: "FR", homeState: "FL", hometown: "Gainesville", jerseyNumber: 9,
        hitForAvg: 39, power: 30, speed: 65, arm: 39, fielding: 35, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 29, vsLHP: 27, grit: 31, stealing: 24, running: 37, throwing: 39, recovery: 27, wRISP: 27, vsLefty: 25, poise: 29, heater: 0, agile: 39,
        abilities: ["Contact Hitter"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "S",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Tristan Weeks — SS FR depth
      { firstName: "Tristan", lastName: "Weeks", position: "SS", eligibility: "FR", homeState: "FL", hometown: "St. Augustine", jerseyNumber: 3,
        hitForAvg: 32, power: 27, speed: 54, arm: 35, fielding: 31, errorResistance: 29, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 26, vsLHP: 23, grit: 26, stealing: 23, running: 35, throwing: 36, recovery: 24, wRISP: 24, vsLefty: 23, poise: 26, heater: 0, agile: 36,
        abilities: ["Express Baserunning"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // OUTFIELDERS (6)
      // Brayden Dowd — CF JR, key OF presence
      { firstName: "Brayden", lastName: "Dowd", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 1,
        hitForAvg: 52, power: 49, speed: 48, arm: 38, fielding: 38, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 46, vsLHP: 41, grit: 46, stealing: 24, running: 37, throwing: 38, recovery: 33, wRISP: 46, vsLefty: 41, poise: 46, heater: 0, agile: 38,
        abilities: ["Power Hitter", "Consigliere"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "S",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Brody DeLamielleure — RF JR
      { firstName: "Brody", lastName: "DeLamielleure", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Ponte Vedra", jerseyNumber: 8,
        hitForAvg: 50, power: 49, speed: 50, arm: 44, fielding: 43, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 44, vsLHP: 42, grit: 44, stealing: 26, running: 39, throwing: 44, recovery: 34, wRISP: 43, vsLefty: 40, poise: 44, heater: 0, agile: 42,
        abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Jaxon Byrd — OF SO speedster
      { firstName: "Jaxon", lastName: "Byrd", position: "OF", eligibility: "SO", homeState: "FL", hometown: "Pensacola", jerseyNumber: 21,
        hitForAvg: 55, power: 47, speed: 56, arm: 53, fielding: 53, errorResistance: 49, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 47, vsLHP: 44, grit: 49, stealing: 35, running: 53, throwing: 55, recovery: 40, wRISP: 44, vsLefty: 40, poise: 47, heater: 0, agile: 55,
        abilities: ["Express Baserunning", "Contact Hitter"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Noah Sheffield — OF JR
      { firstName: "Noah", lastName: "Sheffield", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Orlando", jerseyNumber: 5,
        hitForAvg: 41, power: 35, speed: 46, arm: 36, fielding: 35, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 38, vsLHP: 35, grit: 38, stealing: 25, running: 35, throwing: 36, recovery: 31, wRISP: 36, vsLefty: 35, poise: 36, heater: 0, agile: 36,
        abilities: ["Consigliere"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Chase Mitchell — OF JR
      { firstName: "Chase", lastName: "Mitchell", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Sarasota", jerseyNumber: 20,
        hitForAvg: 43, power: 37, speed: 51, arm: 39, fielding: 38, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 37, vsLHP: 35, grit: 38, stealing: 25, running: 38, throwing: 42, recovery: 31, wRISP: 35, vsLefty: 34, poise: 37, heater: 0, agile: 39,
        abilities: ["Locked and Loaded", "Predicament", "Insurer"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Landon Pierce — OF SO
      { firstName: "Landon", lastName: "Pierce", position: "OF", eligibility: "SO", homeState: "FL", hometown: "Tallahassee", jerseyNumber: 14,
        hitForAvg: 41, power: 37, speed: 52, arm: 39, fielding: 38, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 36, vsLHP: 35, grit: 36, stealing: 25, running: 38, throwing: 41, recovery: 31, wRISP: 35, vsLefty: 33, poise: 36, heater: 0, agile: 39,
        abilities: ["Heat Up", "Contact Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
    ],
  
  // Georgia Tech — 39-8 / 19-5 ACC, D1Baseball #3 (May 3, 2026), 1st-yr coach James Ramsey
  // Best offense in modern P4 history: .357/.466/.619, 10.5 R/G, 7 players >.600 SLG, 5 players >3.00 WAR (NCAA-leading)
  "Georgia Tech": [
    // PITCHERS (10) — moderate staff carrying historic offense
    // Tate McKee — Friday SP, JR, 7-1 / 4.18 / 56 IP / 64K, 92-96 + slider best pitch (50% miss rate), 25 consecutive series openers
    { firstName: "Tate", lastName: "McKee", position: "P", eligibility: "JR", homeState: "GA", hometown: "Alpharetta", jerseyNumber: 22,
      hitForAvg: 16, power: 11, speed: 31, arm: 59, fielding: 38, errorResistance: 52, velocity: 64, control: 54, stamina: 58, stuff: 58,
      clutch: 67, vsLHP: 64, grit: 73, stealing: 8, running: 31, throwing: 73, recovery: 54, wRISP: 50, vsLefty: 52, poise: 57, heater: 58, agile: 44,
      abilities: ["Star of Victory", "Guts", "Sharpness", "Intimidator", "Groundball Pitcher"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [4, 7, 4, 1, 4, 0, 0]) },
    // Mason Patel — closer GR, 4 SV, 13.2 scoreless IP / 1.20 ERA / 18K, All-American 2025 (NCBWA), Stopper of Year finalist
    { firstName: "Mason", lastName: "Patel", position: "P", eligibility: "SR", homeState: "GA", hometown: "Johns Creek", jerseyNumber: 30,
      hitForAvg: 8, power: 7, speed: 28, arm: 51, fielding: 30, errorResistance: 44, velocity: 55, control: 51, stamina: 24, stuff: 53,
      clutch: 70, vsLHP: 63, grit: 66, stealing: 6, running: 26, throwing: 65, recovery: 39, wRISP: 51, vsLefty: 48, poise: 55, heater: 48, agile: 37,
      abilities: ["Fireman", "Doctor K", "Staredown", "Strikeout", "Inside Pitch"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...pitchMix(1, [0, 7, 0, 1, 0, 4, 0]) },
    // Justin Shadek — Sat SP, RS-SO, transfer from Rutgers, 2025 weekend starter
    { firstName: "Justin", lastName: "Shadek", position: "P", eligibility: "SO", homeState: "PA", hometown: "Philadelphia", jerseyNumber: 31,
      hitForAvg: 8, power: 7, speed: 22, arm: 35, fielding: 22, errorResistance: 32, velocity: 37, control: 33, stamina: 35, stuff: 32,
      clutch: 41, vsLHP: 39, grit: 44, stealing: 5, running: 20, throwing: 44, recovery: 30, wRISP: 29, vsLefty: 30, poise: 32, heater: 35, agile: 26,
      abilities: ["Strong Starter", "Grit"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    // Dylan Loy — Sun SP LHP, JR, transfer from Tennessee, 2024 Frosh All-American (SEC leader in app)
    { firstName: "Dylan", lastName: "Loy", position: "P", eligibility: "JR", homeState: "FL", hometown: "Tampa", jerseyNumber: 37,
      hitForAvg: 9, power: 6, speed: 23, arm: 36, fielding: 23, errorResistance: 32, velocity: 39, control: 38, stamina: 32, stuff: 36,
      clutch: 44, vsLHP: 53, grit: 46, stealing: 5, running: 19, throwing: 43, recovery: 31, wRISP: 32, vsLefty: 41, poise: 36, heater: 32, agile: 25,
      abilities: ["Fireman", "Inside Pitch"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [4, 5, 4, 1, 0, 0, 0]) },
    // Cooper Underwood — top FR RHP, 12th-round MLB pick chose college, 2025 Prep BB GA Player of Year
    { firstName: "Cooper", lastName: "Underwood", position: "P", eligibility: "FR", homeState: "GA", hometown: "Woodstock", jerseyNumber: 46,
      hitForAvg: 10, power: 6, speed: 27, arm: 46, fielding: 23, errorResistance: 32, velocity: 47, control: 37, stamina: 31, stuff: 45,
      clutch: 41, vsLHP: 38, grit: 43, stealing: 5, running: 22, throwing: 57, recovery: 31, wRISP: 30, vsLefty: 31, poise: 31, heater: 44, agile: 32,
      abilities: ["Strong Starter", "Sharpness", "True Slider"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    // Charlie Willcox — FR RHP depth
    { firstName: "Charlie", lastName: "Willcox", position: "P", eligibility: "FR", homeState: "GA", hometown: "Cumming", jerseyNumber: 48,
      hitForAvg: 8, power: 7, speed: 23, arm: 36, fielding: 18, errorResistance: 26, velocity: 43, control: 33, stamina: 29, stuff: 33,
      clutch: 27, vsLHP: 26, grit: 29, stealing: 5, running: 21, throwing: 42, recovery: 21, wRISP: 20, vsLefty: 21, poise: 21, heater: 32, agile: 24,
      abilities: ["Top Gear"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "blonde", hairStyle: "short",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    // Carson Ballard — JR RHP RP depth
    { firstName: "Carson", lastName: "Ballard", position: "P", eligibility: "JR", homeState: "GA", hometown: "Marietta", jerseyNumber: 41,
      hitForAvg: 8, power: 7, speed: 23, arm: 27, fielding: 18, errorResistance: 27, velocity: 26, control: 28, stamina: 20, stuff: 25,
      clutch: 33, vsLHP: 32, grit: 34, stealing: 5, running: 19, throwing: 36, recovery: 23, wRISP: 23, vsLefty: 24, poise: 25, heater: 27, agile: 23,
      abilities: ["Guts"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    // Ben Hjelle — RHP RP depth
    { firstName: "Ben", lastName: "Hjelle", position: "P", eligibility: "SR", homeState: "MN", hometown: "Minneapolis", jerseyNumber: 26,
      hitForAvg: 9, power: 7, speed: 23, arm: 30, fielding: 19, errorResistance: 30, velocity: 30, control: 30, stamina: 19, stuff: 30,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 5, running: 19, throwing: 41, recovery: 25, wRISP: 25, vsLefty: 27, poise: 27, heater: 30, agile: 24,
      abilities: ["Painter", "Intimidator"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    // Iyan Wilson — RHP RP
    { firstName: "Iyan", lastName: "Wilson", position: "P", eligibility: "SO", homeState: "GA", hometown: "Atlanta", jerseyNumber: 32,
      hitForAvg: 8, power: 6, speed: 23, arm: 28, fielding: 19, errorResistance: 28, velocity: 28, control: 27, stamina: 19, stuff: 30,
      clutch: 32, vsLHP: 30, grit: 33, stealing: 4, running: 20, throwing: 39, recovery: 21, wRISP: 21, vsLefty: 22, poise: 22, heater: 30, agile: 23,
      abilities: ["Winner's Luck", "Tunneling", "Perfect Combustion"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "deep", hairColor: "black", hairStyle: "fade",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    // Cade Brown — depth RP
    { firstName: "Cade", lastName: "Brown", position: "P", eligibility: "FR", homeState: "GA", hometown: "Macon", jerseyNumber: 19,
      hitForAvg: 8, power: 7, speed: 24, arm: 28, fielding: 17, errorResistance: 28, velocity: 40, control: 25, stamina: 19, stuff: 24,
      clutch: 30, vsLHP: 29, grit: 32, stealing: 4, running: 20, throwing: 40, recovery: 20, wRISP: 20, vsLefty: 20, poise: 20, heater: 30, agile: 24,
      abilities: ["Monster Stuff", "Winner's Luck", "Intimidator"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    // CATCHERS (2)
    // Vahn Lackey — JR C, .425/.545/.851, 9 HR, 45 RBI, .789 SLG team-leader, USA Collegiate, #2 D1B catcher, 1st Team Preseason All-American, top catcher in MLB Draft, played 8 positions in single game
    { firstName: "Vahn", lastName: "Lackey", position: "C", eligibility: "JR", homeState: "GA", hometown: "Suwanee", jerseyNumber: 25,
      hitForAvg: 82, power: 76, speed: 37, arm: 66, fielding: 68, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 79, vsLHP: 70, grit: 71, stealing: 26, running: 43, throwing: 66, recovery: 52, wRISP: 73, vsLefty: 68, poise: 73, heater: 0, agile: 48,
      abilities: ["Power Hitter", "Consigliere", "High-Speed Laser"], potential: "A+", catcherAbility: 68,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Dominic Stephenson — FR backup C
    { firstName: "Dominic", lastName: "Stephenson", position: "C", eligibility: "FR", homeState: "GA", hometown: "Roswell", jerseyNumber: 15,
      hitForAvg: 44, power: 32, speed: 27, arm: 37, fielding: 34, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 24, vsLHP: 22, grit: 27, stealing: 6, running: 19, throwing: 37, recovery: 24, wRISP: 22, vsLefty: 20, poise: 24, heater: 0, agile: 22,
      abilities: ["Counterattack", "Contact Hitter", "Push"], potential: "A", catcherAbility: 34,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // INFIELDERS (7)
    // Will Baker — DH/1B, .662 SLG, 27 R, power threat
    { firstName: "Will", lastName: "Baker", position: "1B", eligibility: "JR", homeState: "GA", hometown: "Athens", jerseyNumber: 16,
      hitForAvg: 66, power: 73, speed: 47, arm: 48, fielding: 51, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 59, vsLHP: 56, grit: 59, stealing: 5, running: 24, throwing: 48, recovery: 48, wRISP: 65, vsLefty: 54, poise: 59, heater: 0, agile: 31,
      abilities: ["Power Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Jarren Advincula — JR 2B (transfer), 2nd-Team All-ACC, leads ALL 2B nationally in WAR (3.66), Golden Spikes Watch, .613 SLG, 27 R
    { firstName: "Jarren", lastName: "Advincula", position: "2B", eligibility: "JR", homeState: "CA", hometown: "San Jose", jerseyNumber: 2,
      hitForAvg: 92, power: 75, speed: 75, arm: 64, fielding: 83, errorResistance: 74, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 85, vsLHP: 76, grit: 81, stealing: 34, running: 60, throwing: 64, recovery: 64, wRISP: 83, vsLefty: 76, poise: 81, heater: 0, agile: 67,
      abilities: ["Gambler", "Contact Hitter", "Defensive Artisan", "Power Hitter", "Storming Home"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Carson Kerce — JR SS, Brooks Wallace SS Watch List semifinalist, top-50 SS, .621 SLG, 3.14 WAR
    { firstName: "Carson", lastName: "Kerce", position: "SS", eligibility: "JR", homeState: "GA", hometown: "Kennesaw", jerseyNumber: 3,
      hitForAvg: 76, power: 66, speed: 65, arm: 65, fielding: 71, errorResistance: 65, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 65, vsLHP: 62, grit: 67, stealing: 25, running: 48, throwing: 65, recovery: 52, wRISP: 67, vsLefty: 62, poise: 67, heater: 0, agile: 56,
      abilities: ["High-Speed Laser", "Defensive Artisan", "Power Hitter", "Consigliere"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Ryan Zuckerman — JR 3B (Pitt transfer), .743 SLG TEAM LEADER, 9 HR, 44 RBI, 26 R, 3.85 WAR (#1), 17-game OB streak
    { firstName: "Ryan", lastName: "Zuckerman", position: "3B", eligibility: "JR", homeState: "PA", hometown: "Pittsburgh", jerseyNumber: 17,
      hitForAvg: 70, power: 73, speed: 45, arm: 52, fielding: 49, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 73, vsLHP: 62, grit: 63, stealing: 7, running: 28, throwing: 52, recovery: 44, wRISP: 68, vsLefty: 59, poise: 65, heater: 0, agile: 36,
      abilities: ["Power Hitter", "Consigliere", "Artist"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Ethan Dolan — JR backup SS/util
    { firstName: "Ethan", lastName: "Dolan", position: "SS", eligibility: "JR", homeState: "GA", hometown: "Savannah", jerseyNumber: 4,
      hitForAvg: 42, power: 35, speed: 51, arm: 41, fielding: 44, errorResistance: 41, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 37, vsLHP: 34, grit: 39, stealing: 22, running: 37, throwing: 43, recovery: 34, wRISP: 35, vsLefty: 32, poise: 37, heater: 0, agile: 41,
      abilities: ["Outside Hitter", "Contact Hitter", "Final Hit"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Jake Whitfield — SO 2B backup
    { firstName: "Jake", lastName: "Whitfield", position: "2B", eligibility: "SO", homeState: "GA", hometown: "Decatur", jerseyNumber: 11,
      hitForAvg: 40, power: 33, speed: 51, arm: 38, fielding: 41, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 35, vsLHP: 32, grit: 36, stealing: 19, running: 35, throwing: 39, recovery: 30, wRISP: 33, vsLefty: 32, poise: 35, heater: 0, agile: 38,
      abilities: ["Counterattack", "Contact Hitter", "Insurer"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "S",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Marcus Terrell — JR depth IF
    { firstName: "Marcus", lastName: "Terrell", position: "3B", eligibility: "JR", homeState: "SC", hometown: "Greenville", jerseyNumber: 18,
      hitForAvg: 33, power: 30, speed: 37, arm: 34, fielding: 33, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 28, vsLHP: 27, grit: 30, stealing: 9, running: 22, throwing: 34, recovery: 25, wRISP: 28, vsLefty: 25, poise: 28, heater: 0, agile: 25,
      abilities: ["Trickster"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "deep", hairColor: "black", hairStyle: "fade",
      ...noPitches },
    // OUTFIELDERS (6)
    // Drew Burress — JR CF, ONLY DI player with career .756 SLG, 55 R (team most), 7HR/31RBI/49R 2026, ACC POW, top OF in MLB Draft, 56-game OB streak last yr
    { firstName: "Drew", lastName: "Burress", position: "OF", eligibility: "JR", homeState: "GA", hometown: "Stockbridge", jerseyNumber: 1,
      hitForAvg: 99, power: 99, speed: 93, arm: 98, fielding: 99, errorResistance: 95, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 99, vsLHP: 99, grit: 99, stealing: 52, running: 95, throwing: 95, recovery: 82, wRISP: 99, vsLefty: 99, poise: 99, heater: 0, agile: 95,
      abilities: ["Artist", "Consigliere", "Contact Hitter"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Alex Hernandez — SO OF, 30 R, 34-game on-base streak
    { firstName: "Alex", lastName: "Hernandez", position: "OF", eligibility: "SO", homeState: "FL", hometown: "Miami", jerseyNumber: 44,
      hitForAvg: 68, power: 56, speed: 56, arm: 50, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 53, grit: 62, stealing: 25, running: 46, throwing: 52, recovery: 44, wRISP: 58, vsLefty: 53, poise: 58, heater: 0, agile: 50,
      abilities: ["Chance Maker", "Contact Hitter"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Caleb Daniel — JR OF, .603 SLG (one of seven >.600), Duluth GA
    { firstName: "Caleb", lastName: "Daniel", position: "OF", eligibility: "JR", homeState: "GA", hometown: "Duluth", jerseyNumber: 6,
      hitForAvg: 60, power: 58, speed: 47, arm: 41, fielding: 41, errorResistance: 39, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 50, grit: 52, stealing: 13, running: 35, throwing: 41, recovery: 38, wRISP: 52, vsLefty: 48, poise: 51, heater: 0, agile: 38,
      abilities: ["Power Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "S",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Parker Brosius — SR OF
    { firstName: "Parker", lastName: "Brosius", position: "OF", eligibility: "SR", homeState: "GA", hometown: "Suwanee", jerseyNumber: 5,
      hitForAvg: 50, power: 46, speed: 54, arm: 48, fielding: 47, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 42, grit: 48, stealing: 25, running: 40, throwing: 48, recovery: 39, wRISP: 45, vsLefty: 40, poise: 47, heater: 0, agile: 45,
      abilities: ["Resilient", "Emergency Strength"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Coleman Lewis — FR OF speed
    { firstName: "Coleman", lastName: "Lewis", position: "OF", eligibility: "FR", homeState: "GA", hometown: "Canton", jerseyNumber: 21,
      hitForAvg: 44, power: 33, speed: 47, arm: 34, fielding: 31, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 25, vsLHP: 25, grit: 28, stealing: 28, running: 41, throwing: 35, recovery: 25, wRISP: 25, vsLefty: 23, poise: 25, heater: 0, agile: 42,
      abilities: ["Express Baserunning"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Nathan Pruitt — JR OF
    { firstName: "Nathan", lastName: "Pruitt", position: "OF", eligibility: "JR", homeState: "GA", hometown: "Athens", jerseyNumber: 14,
      hitForAvg: 37, power: 32, speed: 39, arm: 36, fielding: 33, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 30, grit: 33, stealing: 18, running: 31, throwing: 36, recovery: 26, wRISP: 31, vsLefty: 29, poise: 32, heater: 0, agile: 33,
      abilities: ["Walkoff Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
  ],

  "Louisville": [
    { firstName: "Ethan", lastName: "Eberle", position: "P", eligibility: "SO", homeState: "KY", hometown: "Louisville", jerseyNumber: 34,
      hitForAvg: 23, power: 20, speed: 40, arm: 81, fielding: 51, errorResistance: 64, velocity: 81, control: 78, stamina: 78, stuff: 78,
      clutch: 92, vsLHP: 87, grit: 93, stealing: 18, running: 48, throwing: 93, recovery: 72, wRISP: 73, vsLefty: 76, poise: 77, heater: 83, agile: 57,
      abilities: ["Star of Victory", "Strong Starter", "Intimidator", "Straddle"], potential: "A+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 5, 6, 1, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Bean", position: "P", eligibility: "JR", homeState: "OH", hometown: "Kent", jerseyNumber: 27,
      hitForAvg: 15, power: 14, speed: 36, arm: 60, fielding: 38, errorResistance: 52, velocity: 65, control: 60, stamina: 60, stuff: 60,
      clutch: 71, vsLHP: 68, grit: 72, stealing: 12, running: 36, throwing: 76, recovery: 54, wRISP: 54, vsLefty: 56, poise: 57, heater: 64, agile: 45,
      abilities: ["Guts", "Wild Fastball", "Perfect Combustion"], potential: "A", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [1, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Wyatt", lastName: "Danilowicz", position: "P", eligibility: "SO", homeState: "IN", hometown: "Indianapolis", jerseyNumber: 44,
      hitForAvg: 16, power: 14, speed: 35, arm: 54, fielding: 34, errorResistance: 46, velocity: 59, control: 54, stamina: 52, stuff: 52,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 14, running: 36, throwing: 67, recovery: 47, wRISP: 47, vsLefty: 48, poise: 48, heater: 56, agile: 43,
      abilities: ["Sharpness", "Inside Pitch"], potential: "A", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 6, 1, 0, 0, 0]) },
    { firstName: "Dominic", lastName: "Jacoby", position: "P", eligibility: "JR", homeState: "FL", hometown: "Jacksonville", jerseyNumber: 38,
      hitForAvg: 19, power: 17, speed: 40, arm: 66, fielding: 41, errorResistance: 55, velocity: 72, control: 63, stamina: 63, stuff: 63,
      clutch: 74, vsLHP: 70, grit: 78, stealing: 15, running: 42, throwing: 81, recovery: 57, wRISP: 57, vsLefty: 58, poise: 60, heater: 71, agile: 53,
      abilities: ["Kageura", "vs. Strong Batters", "Decisive", "Staredown"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Schweitzer", position: "P", eligibility: "SO", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 36,
      hitForAvg: 8, power: 7, speed: 26, arm: 22, fielding: 14, errorResistance: 24, velocity: 36, control: 22, stamina: 21, stuff: 26,
      clutch: 32, vsLHP: 29, grit: 32, stealing: 6, running: 18, throwing: 34, recovery: 19, wRISP: 19, vsLefty: 19, poise: 19, heater: 25, agile: 21,
      abilities: ["Iron Arm", "Quick Hands", "True Slider"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 5, 0, 1, 3, 0, 0]) },
    { firstName: "Eli", lastName: "Hoyt", position: "P", eligibility: "SR", homeState: "KY", hometown: "Bowling Green", jerseyNumber: 29,
      hitForAvg: 19, power: 17, speed: 38, arm: 59, fielding: 37, errorResistance: 52, velocity: 64, control: 61, stamina: 55, stuff: 56,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 10, running: 37, throwing: 74, recovery: 53, wRISP: 53, vsLefty: 55, poise: 56, heater: 63, agile: 46,
      abilities: ["Fireman", "True Slider"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 6, 0, 1, 0, 3, 0]) },
    { firstName: "Peter", lastName: "Michael", position: "P", eligibility: "SR", homeState: "OH", hometown: "Columbus", jerseyNumber: 22,
      hitForAvg: 9, power: 8, speed: 26, arm: 23, fielding: 15, errorResistance: 25, velocity: 36, control: 25, stamina: 22, stuff: 26,
      clutch: 33, vsLHP: 32, grit: 34, stealing: 5, running: 19, throwing: 35, recovery: 21, wRISP: 21, vsLefty: 21, poise: 21, heater: 26, agile: 23,
      abilities: ["Strikeout", "Straddle", "Walk"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 4, 0, 3, 0, 0]) },
    { firstName: "Tanner", lastName: "Thomas", position: "P", eligibility: "FR", homeState: "KY", hometown: "Covington", jerseyNumber: 48,
      hitForAvg: 7, power: 7, speed: 24, arm: 34, fielding: 15, errorResistance: 24, velocity: 43, control: 28, stamina: 27, stuff: 32,
      clutch: 27, vsLHP: 24, grit: 28, stealing: 10, running: 24, throwing: 38, recovery: 18, wRISP: 18, vsLefty: 18, poise: 18, heater: 29, agile: 27,
      abilities: ["Lefty Killer", "Bad Ball Hitter"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Kade", lastName: "Elam", position: "P", eligibility: "FR", homeState: "KY", hometown: "Lexington", jerseyNumber: 46,
      hitForAvg: 8, power: 8, speed: 28, arm: 26, fielding: 15, errorResistance: 24, velocity: 39, control: 21, stamina: 19, stuff: 26,
      clutch: 29, vsLHP: 26, grit: 30, stealing: 8, running: 23, throwing: 38, recovery: 18, wRISP: 18, vsLefty: 18, poise: 18, heater: 30, agile: 28,
      abilities: ["Star of Victory", "Lightweight Ball"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Kyle", lastName: "Haynes", position: "C", eligibility: "JR", homeState: "KY", hometown: "Louisville", jerseyNumber: 12,
      hitForAvg: 38, power: 30, speed: 32, arm: 38, fielding: 38, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 29, vsLHP: 28, grit: 31, stealing: 8, running: 19, throwing: 36, recovery: 26, wRISP: 29, vsLefty: 27, poise: 29, heater: 0, agile: 22,
      abilities: ["Artist"], potential: "B+", catcherAbility: 31,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Collin", lastName: "Osenbaugh", position: "C", eligibility: "FR", homeState: "IN", hometown: "Carmel", jerseyNumber: 25,
      hitForAvg: 40, power: 38, speed: 35, arm: 48, fielding: 41, errorResistance: 39, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 36, vsLHP: 32, grit: 38, stealing: 11, running: 27, throwing: 47, recovery: 35, wRISP: 35, vsLefty: 31, poise: 35, heater: 0, agile: 31,
      abilities: ["Heavy Tank", "Locked and Loaded"], potential: "B+", catcherAbility: 45,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "AJ", lastName: "Martin", position: "2B", eligibility: "JR", homeState: "SC", hometown: "Charleston", jerseyNumber: 2,
      hitForAvg: 57, power: 51, speed: 62, arm: 48, fielding: 50, errorResistance: 49, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 29, running: 42, throwing: 49, recovery: 42, wRISP: 50, vsLefty: 46, poise: 49, heater: 0, agile: 45,
      abilities: ["Contact Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Alex", lastName: "Alicea", position: "SS", eligibility: "JR", homeState: "FL", hometown: "Orlando", jerseyNumber: 7,
      hitForAvg: 57, power: 46, speed: 76, arm: 56, fielding: 57, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 51, vsLHP: 47, grit: 52, stealing: 37, running: 49, throwing: 57, recovery: 45, wRISP: 49, vsLefty: 46, poise: 51, heater: 0, agile: 52,
      abilities: ["Defensive Artisan"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Bayram", lastName: "Hot", position: "3B", eligibility: "SR", homeState: "CA", hometown: "San Diego", jerseyNumber: 18,
      hitForAvg: 45, power: 43, speed: 43, arm: 41, fielding: 40, errorResistance: 39, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 41, vsLHP: 39, grit: 43, stealing: 14, running: 30, throwing: 43, recovery: 34, wRISP: 41, vsLefty: 37, poise: 41, heater: 0, agile: 33,
      abilities: ["Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Tague", lastName: "Davis", position: "1B", eligibility: "SO", homeState: "KY", hometown: "Frankfort", jerseyNumber: 11,
      hitForAvg: 48, power: 84, speed: 48, arm: 45, fielding: 44, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 79, vsLHP: 40, grit: 44, stealing: 20, running: 37, throwing: 47, recovery: 37, wRISP: 42, vsLefty: 38, poise: 42, heater: 0, agile: 40,
      abilities: ["Multi-Hit"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Brandon", lastName: "Shannon", position: "3B", eligibility: "FR", homeState: "KY", hometown: "Owensboro", jerseyNumber: 15,
      hitForAvg: 37, power: 35, speed: 47, arm: 40, fielding: 35, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 31, vsLHP: 28, grit: 32, stealing: 17, running: 33, throwing: 43, recovery: 29, wRISP: 29, vsLefty: 26, poise: 29, heater: 0, agile: 36,
      abilities: ["Unrelenting", "Contact Hitter", "Push"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...noPitches },
    { firstName: "Lucas", lastName: "Moore", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Tampa", jerseyNumber: 1,
      hitForAvg: 43, power: 35, speed: 73, arm: 35, fielding: 38, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 37, grit: 38, stealing: 39, running: 41, throwing: 37, recovery: 32, wRISP: 38, vsLefty: 35, poise: 38, heater: 0, agile: 41,
      abilities: ["Express Baserunning", "Contact Hitter"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Zion", lastName: "Rose", position: "OF", eligibility: "SO", homeState: "GA", hometown: "Macon", jerseyNumber: 10,
      hitForAvg: 56, power: 51, speed: 69, arm: 55, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 38, grit: 38, stealing: 38, running: 49, throwing: 49, recovery: 23, wRISP: 38, vsLefty: 36, poise: 38, heater: 0, agile: 38,
      abilities: ["Express Baserunning"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Ben", lastName: "Slanker", position: "OF", eligibility: "JR", homeState: "OH", hometown: "Toledo", jerseyNumber: 8,
      hitForAvg: 61, power: 66, speed: 58, arm: 54, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 52, grit: 56, stealing: 23, running: 42, throwing: 56, recovery: 45, wRISP: 57, vsLefty: 50, poise: 54, heater: 0, agile: 45,
      abilities: ["Power Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Griffin", lastName: "Crain", position: "OF", eligibility: "SO", homeState: "KY", hometown: "Louisville", jerseyNumber: 17,
      hitForAvg: 37, power: 34, speed: 46, arm: 36, fielding: 34, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 34, vsLHP: 31, grit: 34, stealing: 20, running: 32, throwing: 37, recovery: 27, wRISP: 32, vsLefty: 29, poise: 34, heater: 0, agile: 34,
      abilities: ["Error Prone"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Kyle", lastName: "Campbell", position: "OF", eligibility: "SO", homeState: "KY", hometown: "Lexington", jerseyNumber: 20,
      hitForAvg: 49, power: 44, speed: 55, arm: 50, fielding: 45, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 45, vsLHP: 43, grit: 45, stealing: 29, running: 45, throwing: 51, recovery: 41, wRISP: 44, vsLefty: 41, poise: 45, heater: 0, agile: 50,
      abilities: ["First Pitch King", "Contact Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "R",
      ...noPitches },
    { firstName: "Zane", lastName: "Stahl", position: "OF", eligibility: "FR", homeState: "IN", hometown: "Bloomington", jerseyNumber: 21,
      hitForAvg: 35, power: 33, speed: 50, arm: 37, fielding: 33, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 29, vsLHP: 27, grit: 30, stealing: 24, running: 37, throwing: 37, recovery: 28, wRISP: 28, vsLefty: 24, poise: 28, heater: 0, agile: 39,
      abilities: ["Express Baserunning"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Ryan", lastName: "Mercer", position: "1B", eligibility: "JR", homeState: "OH", hometown: "Dayton", jerseyNumber: 33,
      hitForAvg: 37, power: 37, speed: 51, arm: 37, fielding: 30, errorResistance: 29, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 29, vsLHP: 28, grit: 30, stealing: 9, running: 20, throwing: 30, recovery: 25, wRISP: 29, vsLefty: 26, poise: 29, heater: 0, agile: 24,
      abilities: ["Trickster", "Contact Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Tyler", lastName: "Jennings", position: "P", eligibility: "SO", homeState: "IN", hometown: "Terre Haute", jerseyNumber: 14,
      hitForAvg: 14, power: 12, speed: 32, arm: 33, fielding: 31, errorResistance: 41, velocity: 34, control: 35, stamina: 36, stuff: 32,
      clutch: 40, vsLHP: 36, grit: 41, stealing: 27, running: 42, throwing: 46, recovery: 25, wRISP: 27, vsLefty: 25, poise: 29, heater: 33, agile: 45,
      abilities: ["Hot Head"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Derek", lastName: "Collins", position: "2B", eligibility: "JR", homeState: "KY", hometown: "Paducah", jerseyNumber: 9,
      hitForAvg: 47, power: 41, speed: 58, arm: 46, fielding: 45, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 41, vsLHP: 37, grit: 42, stealing: 25, running: 41, throwing: 48, recovery: 37, wRISP: 40, vsLefty: 37, poise: 41, heater: 0, agile: 45,
      abilities: ["Low Ball Hitter", "High Speed Charge", "Contact Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
  ],
};
