import type { RealPlayer } from "./realRosters";

function pitchMix(primary: number, secondary: number[]): { pitchFB: number; pitch2S: number; pitchSL: number; pitchCB: number; pitchCH: number; pitchCT: number; pitchSNK: number; pitchSPL: number } {
  return {
    pitchFB: primary,
    pitch2S: secondary[0] || 0,
    pitchSL: secondary[1] || 0,
    pitchCB: secondary[2] || 0,
    pitchCH: secondary[3] || 0,
    pitchCT: secondary[4] || 0,
    pitchSNK: secondary[5] || 0,
    pitchSPL: secondary[6] || 0,
  };
}

const noPitches = { pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0 };

export const ACC_SUPPLEMENTAL: Record<string, RealPlayer[]> = {
  "Clemson": [
    { firstName: "Chase", lastName: "Brevard", position: "P", eligibility: "FR", homeState: "SC", hometown: "Greenville", jerseyNumber: 47,
      hitForAvg: 20, power: 16, speed: 44, arm: 70, fielding: 42, errorResistance: 44, velocity: 72, control: 58, stamina: 60, stuff: 68,
      clutch: 48, vsLHP: 50, grit: 52, stealing: 14, running: 42, throwing: 68, recovery: 52, wRISP: 48, vsLefty: 50, poise: 50, heater: 70, agile: 46,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 3, 0, 0, 0]) },
    { firstName: "Amare", lastName: "Thomas", position: "OF", eligibility: "FR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 23,
      hitForAvg: 55, power: 52, speed: 65, arm: 58, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 48, stuff: 0,
      clutch: 52, vsLHP: 50, grit: 56, stealing: 55, running: 62, throwing: 56, recovery: 48, wRISP: 50, vsLefty: 48, poise: 50, heater: 0, agile: 62,
      abilities: ["Speed Demon"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Jayse", lastName: "McLaughlin", position: "SS", eligibility: "FR", homeState: "FL", hometown: "Orlando", jerseyNumber: 14,
      hitForAvg: 52, power: 40, speed: 60, arm: 56, fielding: 58, errorResistance: 54, velocity: 0, control: 0, stamina: 46, stuff: 0,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 48, running: 58, throwing: 54, recovery: 46, wRISP: 48, vsLefty: 46, poise: 48, heater: 0, agile: 58,
      abilities: ["Table Setter"], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Duke": [
    { firstName: "Luke", lastName: "Stevenson", position: "P", eligibility: "FR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 40,
      hitForAvg: 18, power: 14, speed: 42, arm: 68, fielding: 40, errorResistance: 42, velocity: 70, control: 60, stamina: 62, stuff: 66,
      clutch: 46, vsLHP: 48, grit: 50, stealing: 12, running: 40, throwing: 66, recovery: 54, wRISP: 46, vsLefty: 48, poise: 48, heater: 68, agile: 44,
      abilities: ["Strong Starter"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 3, 0, 0, 0]) },
    { firstName: "Isaiah", lastName: "Lowe", position: "SS", eligibility: "FR", homeState: "GA", hometown: "Savannah", jerseyNumber: 10,
      hitForAvg: 50, power: 38, speed: 62, arm: 55, fielding: 56, errorResistance: 52, velocity: 0, control: 0, stamina: 46, stuff: 0,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 52, running: 60, throwing: 54, recovery: 44, wRISP: 46, vsLefty: 44, poise: 46, heater: 0, agile: 60,
      abilities: ["Speed Demon"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Brody", lastName: "Rooney", position: "C", eligibility: "FR", homeState: "VA", hometown: "Ashburn", jerseyNumber: 18,
      hitForAvg: 48, power: 44, speed: 36, arm: 60, fielding: 56, errorResistance: 52, velocity: 0, control: 0, stamina: 44, stuff: 0,
      clutch: 50, vsLHP: 48, grit: 54, stealing: 18, running: 34, throwing: 58, recovery: 48, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 38,
      abilities: ["Clutch Gene"], potential: "B+", catcherAbility: 58,
      ...noPitches },
  ],

  "Florida State": [
    { firstName: "JR", lastName: "Marquez", position: "P", eligibility: "FR", homeState: "FL", hometown: "Miami", jerseyNumber: 43,
      hitForAvg: 20, power: 16, speed: 42, arm: 72, fielding: 44, errorResistance: 46, velocity: 74, control: 56, stamina: 58, stuff: 70,
      clutch: 50, vsLHP: 48, grit: 54, stealing: 14, running: 40, throwing: 70, recovery: 52, wRISP: 48, vsLefty: 50, poise: 50, heater: 72, agile: 44,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 3, 4, 0, 0, 0]) },
    { firstName: "Marcus", lastName: "Harris", position: "OF", eligibility: "FR", homeState: "FL", hometown: "Jacksonville", jerseyNumber: 24,
      hitForAvg: 54, power: 48, speed: 62, arm: 56, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 46, stuff: 0,
      clutch: 52, vsLHP: 50, grit: 54, stealing: 50, running: 60, throwing: 54, recovery: 48, wRISP: 50, vsLefty: 48, poise: 48, heater: 0, agile: 60,
      abilities: ["Power Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Cam", lastName: "Cauley", position: "SS", eligibility: "FR", homeState: "FL", hometown: "Tampa", jerseyNumber: 7,
      hitForAvg: 56, power: 42, speed: 64, arm: 58, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 48, stuff: 0,
      clutch: 54, vsLHP: 52, grit: 52, stealing: 54, running: 62, throwing: 56, recovery: 48, wRISP: 52, vsLefty: 50, poise: 50, heater: 0, agile: 62,
      abilities: ["Speed Demon", "Table Setter"], potential: "A-", catcherAbility: null,
      ...noPitches },
  ],

  "Georgia Tech": [
    { firstName: "Braeden", lastName: "Boyle", position: "P", eligibility: "FR", homeState: "GA", hometown: "Roswell", jerseyNumber: 39,
      hitForAvg: 18, power: 14, speed: 40, arm: 70, fielding: 42, errorResistance: 44, velocity: 72, control: 60, stamina: 64, stuff: 68,
      clutch: 48, vsLHP: 46, grit: 52, stealing: 12, running: 38, throwing: 68, recovery: 54, wRISP: 46, vsLefty: 48, poise: 48, heater: 70, agile: 42,
      abilities: ["Workhorse"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Chandler", lastName: "Simpson", position: "SS", eligibility: "FR", homeState: "GA", hometown: "Marietta", jerseyNumber: 3,
      hitForAvg: 58, power: 38, speed: 68, arm: 56, fielding: 62, errorResistance: 58, velocity: 0, control: 0, stamina: 48, stuff: 0,
      clutch: 52, vsLHP: 54, grit: 54, stealing: 60, running: 66, throwing: 54, recovery: 48, wRISP: 50, vsLefty: 52, poise: 50, heater: 0, agile: 66,
      abilities: ["Speed Demon", "Table Setter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Quint", lastName: "Heady", position: "OF", eligibility: "FR", homeState: "TN", hometown: "Nashville", jerseyNumber: 20,
      hitForAvg: 52, power: 46, speed: 56, arm: 54, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 46, stuff: 0,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 42, running: 54, throwing: 52, recovery: 46, wRISP: 48, vsLefty: 46, poise: 48, heater: 0, agile: 54,
      abilities: ["Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Louisville": [
    { firstName: "Bryce", lastName: "McGowan", position: "P", eligibility: "FR", homeState: "KY", hometown: "Lexington", jerseyNumber: 31,
      hitForAvg: 20, power: 16, speed: 44, arm: 72, fielding: 42, errorResistance: 44, velocity: 74, control: 58, stamina: 62, stuff: 70,
      clutch: 50, vsLHP: 48, grit: 54, stealing: 14, running: 42, throwing: 70, recovery: 54, wRISP: 48, vsLefty: 50, poise: 50, heater: 72, agile: 46,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 4, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Mastrobuoni", position: "OF", eligibility: "FR", homeState: "FL", hometown: "Fort Lauderdale", jerseyNumber: 23,
      hitForAvg: 56, power: 44, speed: 60, arm: 56, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 48, stuff: 0,
      clutch: 54, vsLHP: 52, grit: 56, stealing: 48, running: 58, throwing: 54, recovery: 48, wRISP: 52, vsLefty: 50, poise: 50, heater: 0, agile: 58,
      abilities: ["Table Setter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Aiden", lastName: "Kuhns", position: "C", eligibility: "FR", homeState: "KY", hometown: "Louisville", jerseyNumber: 15,
      hitForAvg: 50, power: 46, speed: 35, arm: 62, fielding: 58, errorResistance: 54, velocity: 0, control: 0, stamina: 44, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 56, stealing: 18, running: 33, throwing: 60, recovery: 48, wRISP: 50, vsLefty: 46, poise: 52, heater: 0, agile: 38,
      abilities: ["Guts"], potential: "B+", catcherAbility: 60,
      ...noPitches },
  ],

  "Miami": [
    { firstName: "Gage", lastName: "Jump", position: "P", eligibility: "FR", homeState: "CA", hometown: "Huntington Beach", jerseyNumber: 37,
      hitForAvg: 22, power: 18, speed: 42, arm: 74, fielding: 44, errorResistance: 46, velocity: 76, control: 56, stamina: 58, stuff: 72,
      clutch: 50, vsLHP: 52, grit: 54, stealing: 14, running: 40, throwing: 72, recovery: 52, wRISP: 50, vsLefty: 52, poise: 52, heater: 74, agile: 44,
      abilities: ["Explosive Fastball", "Ace"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 4, 5, 0, 0, 0]) },
    { firstName: "Nolan", lastName: "Schanuel", position: "1B", eligibility: "FR", homeState: "FL", hometown: "Palm Beach", jerseyNumber: 21,
      hitForAvg: 62, power: 58, speed: 42, arm: 52, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 48, stuff: 0,
      clutch: 58, vsLHP: 56, grit: 58, stealing: 20, running: 40, throwing: 50, recovery: 50, wRISP: 58, vsLefty: 54, poise: 56, heater: 0, agile: 42,
      abilities: ["Contact Machine", "Clutch Gene"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Brandon", lastName: "Diaz", position: "SS", eligibility: "FR", homeState: "FL", hometown: "Miami", jerseyNumber: 4,
      hitForAvg: 54, power: 40, speed: 62, arm: 58, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 48, stuff: 0,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 52, running: 60, throwing: 56, recovery: 46, wRISP: 48, vsLefty: 46, poise: 48, heater: 0, agile: 60,
      abilities: ["Speed Demon"], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "NC State": [
    { firstName: "Tyler", lastName: "Keenan", position: "P", eligibility: "FR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 43,
      hitForAvg: 20, power: 16, speed: 40, arm: 70, fielding: 42, errorResistance: 44, velocity: 72, control: 60, stamina: 64, stuff: 68,
      clutch: 48, vsLHP: 50, grit: 52, stealing: 12, running: 38, throwing: 68, recovery: 54, wRISP: 48, vsLefty: 50, poise: 50, heater: 70, agile: 42,
      abilities: ["Strong Starter"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 4, 0, 0, 0]) },
    { firstName: "Tommy", lastName: "White", position: "3B", eligibility: "FR", homeState: "FL", hometown: "St. Petersburg", jerseyNumber: 24,
      hitForAvg: 60, power: 65, speed: 44, arm: 58, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 48, stuff: 0,
      clutch: 58, vsLHP: 56, grit: 58, stealing: 22, running: 42, throwing: 56, recovery: 50, wRISP: 58, vsLefty: 54, poise: 54, heater: 0, agile: 44,
      abilities: ["Power Hitter", "Clutch Gene"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Jordan", lastName: "Lawlar", position: "SS", eligibility: "FR", homeState: "TX", hometown: "Dallas", jerseyNumber: 2,
      hitForAvg: 58, power: 48, speed: 66, arm: 60, fielding: 62, errorResistance: 58, velocity: 0, control: 0, stamina: 50, stuff: 0,
      clutch: 54, vsLHP: 52, grit: 56, stealing: 56, running: 64, throwing: 58, recovery: 48, wRISP: 52, vsLefty: 50, poise: 52, heater: 0, agile: 64,
      abilities: ["Speed Demon", "Table Setter"], potential: "A-", catcherAbility: null,
      ...noPitches },
  ],

  "North Carolina": [
    { firstName: "Robert", lastName: "Hogan", position: "P", eligibility: "FR", homeState: "NC", hometown: "Greensboro", jerseyNumber: 38,
      hitForAvg: 18, power: 14, speed: 42, arm: 70, fielding: 40, errorResistance: 42, velocity: 72, control: 58, stamina: 62, stuff: 68,
      clutch: 48, vsLHP: 46, grit: 52, stealing: 12, running: 40, throwing: 68, recovery: 54, wRISP: 46, vsLefty: 48, poise: 48, heater: 70, agile: 44,
      abilities: ["Workhorse"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Marcus", lastName: "Nelson", position: "OF", eligibility: "FR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 23,
      hitForAvg: 56, power: 50, speed: 62, arm: 58, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 48, stuff: 0,
      clutch: 54, vsLHP: 52, grit: 56, stealing: 50, running: 60, throwing: 56, recovery: 48, wRISP: 52, vsLefty: 50, poise: 50, heater: 0, agile: 60,
      abilities: ["Power Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Cade", lastName: "Kuehler", position: "SS", eligibility: "FR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 7,
      hitForAvg: 52, power: 38, speed: 58, arm: 54, fielding: 56, errorResistance: 52, velocity: 0, control: 0, stamina: 46, stuff: 0,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 48, running: 56, throwing: 52, recovery: 44, wRISP: 46, vsLefty: 44, poise: 46, heater: 0, agile: 56,
      abilities: ["Table Setter"], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Notre Dame": [
    { firstName: "Cole", lastName: "Doman", position: "P", eligibility: "FR", homeState: "CA", hometown: "San Diego", jerseyNumber: 41,
      hitForAvg: 20, power: 16, speed: 44, arm: 72, fielding: 44, errorResistance: 46, velocity: 74, control: 58, stamina: 60, stuff: 70,
      clutch: 50, vsLHP: 48, grit: 54, stealing: 14, running: 42, throwing: 70, recovery: 52, wRISP: 48, vsLefty: 50, poise: 50, heater: 72, agile: 46,
      abilities: ["Filthy Breaking Ball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 6, 4, 0, 0, 0]) },
    { firstName: "Aaron", lastName: "Piersall", position: "OF", eligibility: "FR", homeState: "IN", hometown: "Indianapolis", jerseyNumber: 20,
      hitForAvg: 54, power: 50, speed: 60, arm: 58, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 48, stuff: 0,
      clutch: 52, vsLHP: 50, grit: 54, stealing: 48, running: 58, throwing: 56, recovery: 48, wRISP: 52, vsLefty: 48, poise: 50, heater: 0, agile: 58,
      abilities: ["Cannon Arm"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Mark", lastName: "Vierling", position: "SS", eligibility: "FR", homeState: "PA", hometown: "Pittsburgh", jerseyNumber: 6,
      hitForAvg: 56, power: 42, speed: 58, arm: 56, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 48, stuff: 0,
      clutch: 52, vsLHP: 50, grit: 52, stealing: 46, running: 56, throwing: 54, recovery: 46, wRISP: 50, vsLefty: 48, poise: 48, heater: 0, agile: 56,
      abilities: ["Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Pittsburgh": [
    { firstName: "Blake", lastName: "Hely", position: "P", eligibility: "FR", homeState: "PA", hometown: "Philadelphia", jerseyNumber: 37,
      hitForAvg: 18, power: 14, speed: 40, arm: 68, fielding: 40, errorResistance: 42, velocity: 70, control: 60, stamina: 64, stuff: 66,
      clutch: 46, vsLHP: 46, grit: 50, stealing: 10, running: 38, throwing: 66, recovery: 54, wRISP: 46, vsLefty: 48, poise: 48, heater: 68, agile: 42,
      abilities: ["Strong Starter"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 5, 0, 0, 0]) },
    { firstName: "Jason", lastName: "Montenegro", position: "3B", eligibility: "FR", homeState: "FL", hometown: "Hialeah", jerseyNumber: 12,
      hitForAvg: 54, power: 52, speed: 48, arm: 58, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 46, stuff: 0,
      clutch: 52, vsLHP: 50, grit: 54, stealing: 28, running: 46, throwing: 56, recovery: 48, wRISP: 52, vsLefty: 48, poise: 50, heater: 0, agile: 48,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Gabriel", lastName: "Montenegro", position: "OF", eligibility: "FR", homeState: "FL", hometown: "Hialeah", jerseyNumber: 19,
      hitForAvg: 50, power: 44, speed: 58, arm: 54, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 46, stuff: 0,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 44, running: 56, throwing: 52, recovery: 46, wRISP: 46, vsLefty: 44, poise: 46, heater: 0, agile: 56,
      abilities: ["Speed Demon"], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "California": [
    { firstName: "Reggie", lastName: "Crawford", position: "P", eligibility: "FR", homeState: "CT", hometown: "Stamford", jerseyNumber: 42,
      hitForAvg: 22, power: 20, speed: 46, arm: 75, fielding: 44, errorResistance: 46, velocity: 78, control: 54, stamina: 56, stuff: 74,
      clutch: 52, vsLHP: 50, grit: 56, stealing: 16, running: 44, throwing: 74, recovery: 52, wRISP: 50, vsLefty: 52, poise: 52, heater: 76, agile: 48,
      abilities: ["Explosive Fastball", "Ace"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 3, 5, 0, 0, 0]) },
    { firstName: "Nathan", lastName: "Martorella", position: "1B", eligibility: "FR", homeState: "CA", hometown: "Newport Beach", jerseyNumber: 26,
      hitForAvg: 60, power: 62, speed: 40, arm: 52, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 48, stuff: 0,
      clutch: 56, vsLHP: 54, grit: 56, stealing: 18, running: 38, throwing: 50, recovery: 50, wRISP: 56, vsLefty: 52, poise: 54, heater: 0, agile: 40,
      abilities: ["Power Hitter", "Clutch Gene"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Cole", lastName: "Elvis", position: "OF", eligibility: "FR", homeState: "CA", hometown: "Sacramento", jerseyNumber: 17,
      hitForAvg: 52, power: 44, speed: 58, arm: 54, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 46, stuff: 0,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 46, running: 56, throwing: 52, recovery: 46, wRISP: 46, vsLefty: 44, poise: 46, heater: 0, agile: 56,
      abilities: ["Table Setter"], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Stanford": [
    { firstName: "Blake", lastName: "Bittner", position: "P", eligibility: "FR", homeState: "CA", hometown: "San Jose", jerseyNumber: 35,
      hitForAvg: 20, power: 16, speed: 42, arm: 70, fielding: 42, errorResistance: 44, velocity: 72, control: 60, stamina: 64, stuff: 68,
      clutch: 48, vsLHP: 48, grit: 52, stealing: 12, running: 40, throwing: 68, recovery: 54, wRISP: 48, vsLefty: 50, poise: 50, heater: 70, agile: 44,
      abilities: ["Wipeout Slider"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 4, 4, 0, 0, 0]) },
    { firstName: "Braden", lastName: "Montgomery", position: "OF", eligibility: "FR", homeState: "TN", hometown: "Madison", jerseyNumber: 6,
      hitForAvg: 58, power: 62, speed: 56, arm: 60, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 48, stuff: 0,
      clutch: 56, vsLHP: 54, grit: 58, stealing: 42, running: 54, throwing: 58, recovery: 50, wRISP: 56, vsLefty: 52, poise: 54, heater: 0, agile: 54,
      abilities: ["Power Hitter", "Clutch Gene"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Xavier", lastName: "Ruiz", position: "SS", eligibility: "FR", homeState: "TX", hometown: "San Antonio", jerseyNumber: 2,
      hitForAvg: 52, power: 40, speed: 60, arm: 56, fielding: 58, errorResistance: 54, velocity: 0, control: 0, stamina: 46, stuff: 0,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 50, running: 58, throwing: 54, recovery: 46, wRISP: 48, vsLefty: 46, poise: 48, heater: 0, agile: 58,
      abilities: ["Iron Glove"], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Virginia": [
    { firstName: "Ethan", lastName: "Anderson", position: "P", eligibility: "FR", homeState: "VA", hometown: "Richmond", jerseyNumber: 39,
      hitForAvg: 18, power: 14, speed: 42, arm: 72, fielding: 42, errorResistance: 44, velocity: 74, control: 58, stamina: 62, stuff: 70,
      clutch: 50, vsLHP: 48, grit: 54, stealing: 12, running: 40, throwing: 70, recovery: 54, wRISP: 48, vsLefty: 50, poise: 50, heater: 72, agile: 44,
      abilities: ["Strong Starter"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Griff", lastName: "OFerrall", position: "SS", eligibility: "FR", homeState: "VA", hometown: "Charlottesville", jerseyNumber: 8,
      hitForAvg: 58, power: 44, speed: 62, arm: 60, fielding: 64, errorResistance: 58, velocity: 0, control: 0, stamina: 48, stuff: 0,
      clutch: 54, vsLHP: 52, grit: 56, stealing: 50, running: 60, throwing: 58, recovery: 48, wRISP: 52, vsLefty: 50, poise: 52, heater: 0, agile: 62,
      abilities: ["Iron Glove", "Table Setter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Harrison", lastName: "Didawick", position: "3B", eligibility: "FR", homeState: "VA", hometown: "Glen Allen", jerseyNumber: 14,
      hitForAvg: 54, power: 50, speed: 50, arm: 56, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 46, stuff: 0,
      clutch: 52, vsLHP: 50, grit: 54, stealing: 30, running: 48, throwing: 54, recovery: 48, wRISP: 52, vsLefty: 48, poise: 50, heater: 0, agile: 50,
      abilities: ["Clutch Gene"], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Virginia Tech": [
    { firstName: "Griffin", lastName: "Green", position: "P", eligibility: "FR", homeState: "VA", hometown: "Roanoke", jerseyNumber: 44,
      hitForAvg: 18, power: 14, speed: 40, arm: 70, fielding: 42, errorResistance: 44, velocity: 72, control: 62, stamina: 66, stuff: 68,
      clutch: 48, vsLHP: 46, grit: 52, stealing: 10, running: 38, throwing: 68, recovery: 56, wRISP: 48, vsLefty: 48, poise: 50, heater: 70, agile: 42,
      abilities: ["Workhorse"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Kyle", lastName: "Teel", position: "C", eligibility: "FR", homeState: "VA", hometown: "Mahwah", jerseyNumber: 3,
      hitForAvg: 62, power: 50, speed: 44, arm: 64, fielding: 62, errorResistance: 58, velocity: 0, control: 0, stamina: 48, stuff: 0,
      clutch: 58, vsLHP: 56, grit: 60, stealing: 26, running: 42, throwing: 62, recovery: 52, wRISP: 58, vsLefty: 54, poise: 56, heater: 0, agile: 44,
      abilities: ["Clutch Gene", "Contact Machine"], potential: "A-", catcherAbility: 65,
      ...noPitches },
    { firstName: "Gavin", lastName: "Cross", position: "OF", eligibility: "FR", homeState: "VA", hometown: "Bristol", jerseyNumber: 17,
      hitForAvg: 58, power: 60, speed: 58, arm: 62, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 48, stuff: 0,
      clutch: 56, vsLHP: 54, grit: 58, stealing: 44, running: 56, throwing: 60, recovery: 50, wRISP: 56, vsLefty: 52, poise: 54, heater: 0, agile: 56,
      abilities: ["Power Hitter", "Cannon Arm"], potential: "A-", catcherAbility: null,
      ...noPitches },
  ],

  "Wake Forest": [
    { firstName: "Chase", lastName: "Hampton", position: "P", eligibility: "FR", homeState: "TX", hometown: "Houston", jerseyNumber: 40,
      hitForAvg: 20, power: 16, speed: 44, arm: 74, fielding: 44, errorResistance: 46, velocity: 76, control: 56, stamina: 58, stuff: 72,
      clutch: 52, vsLHP: 50, grit: 56, stealing: 14, running: 42, throwing: 72, recovery: 52, wRISP: 50, vsLefty: 52, poise: 52, heater: 74, agile: 46,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 4, 4, 0, 0, 0]) },
    { firstName: "Seth", lastName: "Keener", position: "SS", eligibility: "FR", homeState: "NC", hometown: "Winston-Salem", jerseyNumber: 8,
      hitForAvg: 54, power: 40, speed: 60, arm: 56, fielding: 58, errorResistance: 54, velocity: 0, control: 0, stamina: 46, stuff: 0,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 50, running: 58, throwing: 54, recovery: 46, wRISP: 48, vsLefty: 46, poise: 48, heater: 0, agile: 58,
      abilities: ["Table Setter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Michael", lastName: "Turconi", position: "2B", eligibility: "FR", homeState: "NC", hometown: "Greensboro", jerseyNumber: 4,
      hitForAvg: 56, power: 36, speed: 58, arm: 52, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 46, stuff: 0,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 48, running: 56, throwing: 50, recovery: 46, wRISP: 48, vsLefty: 46, poise: 48, heater: 0, agile: 56,
      abilities: ["Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "SMU": [
    { firstName: "Brock", lastName: "Burns", position: "P", eligibility: "FR", homeState: "TX", hometown: "Austin", jerseyNumber: 33,
      hitForAvg: 20, power: 16, speed: 42, arm: 72, fielding: 42, errorResistance: 44, velocity: 74, control: 58, stamina: 62, stuff: 70,
      clutch: 50, vsLHP: 48, grit: 54, stealing: 12, running: 40, throwing: 70, recovery: 54, wRISP: 48, vsLefty: 50, poise: 50, heater: 72, agile: 44,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 4, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Collins", position: "OF", eligibility: "FR", homeState: "TX", hometown: "Dallas", jerseyNumber: 22,
      hitForAvg: 54, power: 48, speed: 60, arm: 56, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 48, stuff: 0,
      clutch: 52, vsLHP: 50, grit: 54, stealing: 48, running: 58, throwing: 54, recovery: 48, wRISP: 50, vsLefty: 48, poise: 50, heater: 0, agile: 58,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Reid", lastName: "Thompson", position: "SS", eligibility: "FR", homeState: "TX", hometown: "Fort Worth", jerseyNumber: 7,
      hitForAvg: 52, power: 38, speed: 62, arm: 56, fielding: 58, errorResistance: 54, velocity: 0, control: 0, stamina: 46, stuff: 0,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 52, running: 60, throwing: 54, recovery: 44, wRISP: 46, vsLefty: 44, poise: 46, heater: 0, agile: 60,
      abilities: ["Speed Demon"], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Boston College": [
    { firstName: "Tyler", lastName: "Bosma", position: "P", eligibility: "FR", homeState: "MA", hometown: "Braintree", jerseyNumber: 36,
      hitForAvg: 18, power: 14, speed: 40, arm: 68, fielding: 40, errorResistance: 42, velocity: 70, control: 62, stamina: 66, stuff: 66,
      clutch: 46, vsLHP: 46, grit: 50, stealing: 10, running: 38, throwing: 66, recovery: 56, wRISP: 46, vsLefty: 48, poise: 48, heater: 68, agile: 42,
      abilities: ["Workhorse"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 3, 0, 0, 0]) },
    { firstName: "Joey", lastName: "Walsh", position: "OF", eligibility: "FR", homeState: "MA", hometown: "Boston", jerseyNumber: 21,
      hitForAvg: 52, power: 46, speed: 56, arm: 54, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 46, stuff: 0,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 42, running: 54, throwing: 52, recovery: 46, wRISP: 48, vsLefty: 46, poise: 48, heater: 0, agile: 54,
      abilities: ["Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Nick", lastName: "Yorke", position: "2B", eligibility: "FR", homeState: "CA", hometown: "San Jose", jerseyNumber: 5,
      hitForAvg: 60, power: 50, speed: 54, arm: 52, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 48, stuff: 0,
      clutch: 56, vsLHP: 54, grit: 56, stealing: 40, running: 52, throwing: 50, recovery: 48, wRISP: 56, vsLefty: 52, poise: 54, heater: 0, agile: 52,
      abilities: ["Contact Machine", "Clutch Gene"], potential: "A-", catcherAbility: null,
      ...noPitches },
  ],
};
