import { RealPlayer } from "./realRosters";

function pitchMix(primary: number, secondary: number[]): { pitchFB: number; pitch2S: number; pitchSL: number; pitchCB: number; pitchCH: number; pitchCT: number; pitchSNK: number; pitchSPL: number } {
  return {
    pitchFB: primary,
    pitch2S: secondary[0] || 0,
    pitchSL: secondary[1] || 0,
    pitchCB: secondary[2] || 0,
    pitchCH: secondary[3] || 0,
    pitchCT: secondary[4] || 0,
    pitchSNK: secondary[5] || 0,
    pitchSPL: secondary[6] || 0,
  };
}

const noPitches = { pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0 };

export const BIG_TEN_BATCH1_ROSTERS: Record<string, RealPlayer[]> = {
  "Illinois": [
    // PITCHERS (10)
    { firstName: "Regan", lastName: "Hall", position: "P", eligibility: "JR", homeState: "IL", hometown: "Champaign", jerseyNumber: 34,
      hitForAvg: 18, power: 14, speed: 40, arm: 84, fielding: 50, errorResistance: 52, velocity: 86, control: 78, stamina: 80, stuff: 84,
      clutch: 76, vsLHP: 72, grit: 78, stealing: 12, running: 36, throwing: 82, recovery: 70, wRISP: 74, vsLefty: 76, poise: 78, heater: 84, agile: 46,
      abilities: ["Ace", "Strong Starter", "Filthy Breaking Ball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 7, 6, 5, 0, 0, 0]) },
    { firstName: "Zach", lastName: "Bates", position: "P", eligibility: "SR", homeState: "IL", hometown: "Peoria", jerseyNumber: 29,
      hitForAvg: 18, power: 14, speed: 38, arm: 78, fielding: 48, errorResistance: 50, velocity: 80, control: 76, stamina: 68, stuff: 78,
      clutch: 74, vsLHP: 68, grit: 76, stealing: 10, running: 34, throwing: 76, recovery: 70, wRISP: 72, vsLefty: 72, poise: 76, heater: 78, agile: 44,
      abilities: ["Fireman", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 7, 5, 4, 0, 0, 0]) },
    { firstName: "Mitch", lastName: "Dye", position: "P", eligibility: "SR", homeState: "IL", hometown: "Bloomington", jerseyNumber: 38,
      hitForAvg: 16, power: 12, speed: 38, arm: 72, fielding: 48, errorResistance: 50, velocity: 74, control: 72, stamina: 66, stuff: 72,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 10, running: 34, throwing: 70, recovery: 66, wRISP: 66, vsLefty: 68, poise: 70, heater: 72, agile: 42,
      abilities: ["Workhorse"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Jorge", lastName: "DeCardenas", position: "P", eligibility: "JR", homeState: "FL", hometown: "Miami", jerseyNumber: 22,
      hitForAvg: 16, power: 12, speed: 40, arm: 70, fielding: 46, errorResistance: 48, velocity: 72, control: 68, stamina: 68, stuff: 70,
      clutch: 62, vsLHP: 60, grit: 64, stealing: 12, running: 36, throwing: 68, recovery: 62, wRISP: 60, vsLefty: 64, poise: 64, heater: 70, agile: 44,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Landon", lastName: "Yorek", position: "P", eligibility: "JR", homeState: "IL", hometown: "Naperville", jerseyNumber: 40,
      hitForAvg: 18, power: 14, speed: 38, arm: 72, fielding: 46, errorResistance: 48, velocity: 74, control: 70, stamina: 70, stuff: 72,
      clutch: 64, vsLHP: 62, grit: 66, stealing: 10, running: 34, throwing: 70, recovery: 64, wRISP: 62, vsLefty: 66, poise: 66, heater: 72, agile: 42,
      abilities: ["Filthy Breaking Ball"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 5, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Johnson", position: "P", eligibility: "JR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 42,
      hitForAvg: 18, power: 14, speed: 40, arm: 74, fielding: 48, errorResistance: 50, velocity: 76, control: 72, stamina: 70, stuff: 74,
      clutch: 66, vsLHP: 64, grit: 68, stealing: 12, running: 36, throwing: 72, recovery: 64, wRISP: 64, vsLefty: 66, poise: 68, heater: 74, agile: 44,
      abilities: ["Strong Starter"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 4, 0, 0, 0]) },
    { firstName: "Tore", lastName: "Indomenico", position: "P", eligibility: "JR", homeState: "IN", hometown: "Granger", jerseyNumber: 44,
      hitForAvg: 16, power: 12, speed: 38, arm: 70, fielding: 46, errorResistance: 48, velocity: 72, control: 70, stamina: 68, stuff: 70,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 10, running: 34, throwing: 68, recovery: 62, wRISP: 62, vsLefty: 64, poise: 66, heater: 70, agile: 42,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Liam", lastName: "McKillop", position: "P", eligibility: "JR", homeState: "IL", hometown: "Edwardsville", jerseyNumber: 46,
      hitForAvg: 16, power: 12, speed: 38, arm: 68, fielding: 44, errorResistance: 46, velocity: 70, control: 66, stamina: 66, stuff: 68,
      clutch: 60, vsLHP: 58, grit: 62, stealing: 10, running: 34, throwing: 66, recovery: 60, wRISP: 58, vsLefty: 62, poise: 62, heater: 68, agile: 42,
      abilities: [], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Ike", lastName: "Young", position: "P", eligibility: "FR", homeState: "IL", hometown: "Monticello", jerseyNumber: 48,
      hitForAvg: 14, power: 10, speed: 42, arm: 64, fielding: 38, errorResistance: 40, velocity: 65, control: 50, stamina: 48, stuff: 62,
      clutch: 42, vsLHP: 40, grit: 44, stealing: 14, running: 38, throwing: 62, recovery: 42, wRISP: 40, vsLefty: 44, poise: 42, heater: 64, agile: 46,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 4, 0, 0, 0]) },
    { firstName: "Aiden", lastName: "Flinn", position: "P", eligibility: "FR", homeState: "IL", hometown: "Elmhurst", jerseyNumber: 50,
      hitForAvg: 12, power: 10, speed: 40, arm: 62, fielding: 36, errorResistance: 38, velocity: 62, control: 48, stamina: 46, stuff: 58,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 12, running: 36, throwing: 60, recovery: 40, wRISP: 38, vsLefty: 42, poise: 40, heater: 60, agile: 44,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Daniel", lastName: "Contreras", position: "C", eligibility: "JR", homeState: "IL", hometown: "Normal", jerseyNumber: 14,
      hitForAvg: 62, power: 55, speed: 40, arm: 72, fielding: 70, errorResistance: 68, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 18, running: 38, throwing: 74, recovery: 54, wRISP: 62, vsLefty: 58, poise: 64, heater: 0, agile: 44,
      abilities: ["Iron Glove"], potential: "B+", catcherAbility: 68,
      ...noPitches },
    { firstName: "Brady", lastName: "Schultz", position: "C", eligibility: "FR", homeState: "IL", hometown: "Barrington", jerseyNumber: 18,
      hitForAvg: 42, power: 36, speed: 36, arm: 58, fielding: 52, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 14, running: 34, throwing: 60, recovery: 38, wRISP: 38, vsLefty: 36, poise: 40, heater: 0, agile: 38,
      abilities: [], potential: "B+", catcherAbility: 58,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Cole", lastName: "Warehime", position: "1B", eligibility: "JR", homeState: "MO", hometown: "Cape Girardeau", jerseyNumber: 8,
      hitForAvg: 66, power: 64, speed: 44, arm: 62, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 16, running: 42, throwing: 64, recovery: 54, wRISP: 64, vsLefty: 58, poise: 64, heater: 0, agile: 46,
      abilities: ["Power Surge"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Michael", lastName: "Farina", position: "2B", eligibility: "JR", homeState: "IL", hometown: "Orland Park", jerseyNumber: 10,
      hitForAvg: 64, power: 50, speed: 56, arm: 62, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 36, running: 54, throwing: 64, recovery: 52, wRISP: 60, vsLefty: 56, poise: 62, heater: 0, agile: 60,
      abilities: ["Table Setter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Matt", lastName: "Rose", position: "3B", eligibility: "JR", homeState: "IL", hometown: "Springfield", jerseyNumber: 5,
      hitForAvg: 66, power: 60, speed: 50, arm: 68, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 28, running: 48, throwing: 70, recovery: 54, wRISP: 62, vsLefty: 58, poise: 64, heater: 0, agile: 54,
      abilities: ["Contact Machine"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "J.R.", lastName: "Nelson", position: "SS", eligibility: "JR", homeState: "OH", hometown: "Athens", jerseyNumber: 2,
      hitForAvg: 68, power: 54, speed: 66, arm: 74, fielding: 74, errorResistance: 72, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 48, running: 64, throwing: 76, recovery: 56, wRISP: 64, vsLefty: 60, poise: 66, heater: 0, agile: 70,
      abilities: ["Iron Glove", "Speed Demon"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Ethan", lastName: "Driscoll", position: "2B", eligibility: "FR", homeState: "IL", hometown: "Libertyville", jerseyNumber: 24,
      hitForAvg: 42, power: 32, speed: 52, arm: 54, fielding: 50, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 30, running: 50, throwing: 56, recovery: 38, wRISP: 38, vsLefty: 36, poise: 40, heater: 0, agile: 54,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (7)
    { firstName: "Collin", lastName: "Jennings", position: "OF", eligibility: "JR", homeState: "IL", hometown: "Yorkville", jerseyNumber: 1,
      hitForAvg: 74, power: 76, speed: 64, arm: 70, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 74, vsLHP: 70, grit: 76, stealing: 44, running: 62, throwing: 72, recovery: 58, wRISP: 74, vsLefty: 68, poise: 74, heater: 0, agile: 66,
      abilities: ["Power Surge", "Clutch Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Nick", lastName: "Groves", position: "OF", eligibility: "SR", homeState: "IL", hometown: "Normal", jerseyNumber: 4,
      hitForAvg: 70, power: 64, speed: 60, arm: 68, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 40, running: 58, throwing: 70, recovery: 56, wRISP: 66, vsLefty: 62, poise: 68, heater: 0, agile: 62,
      abilities: ["Cannon Arm"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "Pruitt", position: "OF", eligibility: "JR", homeState: "IL", hometown: "Dunlap", jerseyNumber: 7,
      hitForAvg: 66, power: 56, speed: 62, arm: 66, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 42, running: 60, throwing: 68, recovery: 52, wRISP: 62, vsLefty: 58, poise: 64, heater: 0, agile: 64,
      abilities: ["Contact Machine"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Cole", lastName: "Crafton", position: "OF", eligibility: "JR", homeState: "KY", hometown: "Louisville", jerseyNumber: 9,
      hitForAvg: 64, power: 58, speed: 58, arm: 66, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 38, running: 56, throwing: 68, recovery: 52, wRISP: 60, vsLefty: 56, poise: 62, heater: 0, agile: 60,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Kyle", lastName: "Remington", position: "OF", eligibility: "JR", homeState: "MN", hometown: "Woodbury", jerseyNumber: 11,
      hitForAvg: 60, power: 52, speed: 60, arm: 68, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 40, running: 58, throwing: 70, recovery: 50, wRISP: 56, vsLefty: 52, poise: 58, heater: 0, agile: 62,
      abilities: [], potential: "B-", catcherAbility: null,
      ...noPitches },
    { firstName: "Nolan", lastName: "Hartman", position: "OF", eligibility: "FR", homeState: "IL", hometown: "Wheaton", jerseyNumber: 26,
      hitForAvg: 40, power: 34, speed: 56, arm: 54, fielding: 46, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 34, running: 54, throwing: 56, recovery: 36, wRISP: 36, vsLefty: 34, poise: 38, heater: 0, agile: 58,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Drew", lastName: "Pearson", position: "DH", eligibility: "JR", homeState: "IL", hometown: "Champaign", jerseyNumber: 20,
      hitForAvg: 62, power: 58, speed: 40, arm: 50, fielding: 42, errorResistance: 40, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 14, running: 38, throwing: 52, recovery: 50, wRISP: 60, vsLefty: 56, poise: 60, heater: 0, agile: 42,
      abilities: ["Clutch Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Marcus", lastName: "Tanner", position: "1B", eligibility: "SO", homeState: "IL", hometown: "Plainfield", jerseyNumber: 32,
      hitForAvg: 44, power: 40, speed: 38, arm: 52, fielding: 46, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 38, grit: 44, stealing: 14, running: 36, throwing: 54, recovery: 38, wRISP: 40, vsLefty: 36, poise: 40, heater: 0, agile: 40,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
  ],

  "Indiana": [
    // PITCHERS (10)
    { firstName: "Tony", lastName: "Neubeck", position: "P", eligibility: "SR", homeState: "MO", hometown: "Columbia", jerseyNumber: 34,
      hitForAvg: 20, power: 16, speed: 42, arm: 84, fielding: 50, errorResistance: 52, velocity: 86, control: 76, stamina: 78, stuff: 84,
      clutch: 74, vsLHP: 70, grit: 76, stealing: 12, running: 38, throwing: 82, recovery: 70, wRISP: 72, vsLefty: 74, poise: 76, heater: 84, agile: 46,
      abilities: ["Ace", "Explosive Fastball", "Strong Starter"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 7, 5, 6, 0, 0, 0]) },
    { firstName: "Jackson", lastName: "Bergman", position: "P", eligibility: "SR", homeState: "OH", hometown: "Toledo", jerseyNumber: 29,
      hitForAvg: 18, power: 14, speed: 38, arm: 76, fielding: 48, errorResistance: 50, velocity: 78, control: 74, stamina: 74, stuff: 76,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 10, running: 34, throwing: 74, recovery: 68, wRISP: 68, vsLefty: 70, poise: 72, heater: 76, agile: 44,
      abilities: ["Workhorse", "Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 4, 0, 0, 0]) },
    { firstName: "Chase", lastName: "Linn", position: "P", eligibility: "JR", homeState: "IN", hometown: "Fishers", jerseyNumber: 22,
      hitForAvg: 16, power: 12, speed: 40, arm: 72, fielding: 46, errorResistance: 48, velocity: 74, control: 70, stamina: 70, stuff: 72,
      clutch: 64, vsLHP: 62, grit: 66, stealing: 12, running: 36, throwing: 70, recovery: 64, wRISP: 62, vsLefty: 66, poise: 66, heater: 72, agile: 44,
      abilities: ["Filthy Breaking Ball"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 5, 0, 0, 0]) },
    { firstName: "Pete", lastName: "Haas", position: "P", eligibility: "SR", homeState: "IN", hometown: "Carmel", jerseyNumber: 38,
      hitForAvg: 18, power: 14, speed: 36, arm: 72, fielding: 48, errorResistance: 50, velocity: 74, control: 72, stamina: 70, stuff: 72,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 10, running: 32, throwing: 70, recovery: 66, wRISP: 66, vsLefty: 68, poise: 70, heater: 72, agile: 42,
      abilities: ["Fireman"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 0, 5, 0, 0]) },
    { firstName: "Brayton", lastName: "Thomas", position: "P", eligibility: "SO", homeState: "IN", hometown: "Noblesville", jerseyNumber: 37,
      hitForAvg: 16, power: 12, speed: 40, arm: 70, fielding: 46, errorResistance: 48, velocity: 72, control: 66, stamina: 66, stuff: 70,
      clutch: 58, vsLHP: 56, grit: 62, stealing: 12, running: 36, throwing: 68, recovery: 58, wRISP: 56, vsLefty: 60, poise: 60, heater: 70, agile: 44,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Gavin", lastName: "Seebold", position: "P", eligibility: "SR", homeState: "IN", hometown: "Westfield", jerseyNumber: 40,
      hitForAvg: 18, power: 14, speed: 38, arm: 70, fielding: 48, errorResistance: 50, velocity: 72, control: 72, stamina: 68, stuff: 70,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 10, running: 34, throwing: 68, recovery: 64, wRISP: 64, vsLefty: 66, poise: 68, heater: 70, agile: 42,
      abilities: ["Guts"], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Anthony", lastName: "Gubitosi", position: "P", eligibility: "SR", homeState: "NJ", hometown: "Toms River", jerseyNumber: 42,
      hitForAvg: 16, power: 12, speed: 38, arm: 68, fielding: 44, errorResistance: 46, velocity: 70, control: 68, stamina: 66, stuff: 68,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 10, running: 34, throwing: 66, recovery: 60, wRISP: 60, vsLefty: 62, poise: 64, heater: 68, agile: 42,
      abilities: [], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Owen", lastName: "Keiser", position: "P", eligibility: "SO", homeState: "IN", hometown: "Greenwood", jerseyNumber: 44,
      hitForAvg: 14, power: 10, speed: 40, arm: 66, fielding: 42, errorResistance: 44, velocity: 68, control: 62, stamina: 62, stuff: 66,
      clutch: 54, vsLHP: 52, grit: 58, stealing: 12, running: 36, throwing: 64, recovery: 54, wRISP: 52, vsLefty: 56, poise: 56, heater: 66, agile: 44,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 5, 0, 0, 0]) },
    { firstName: "Bryce", lastName: "Donnelly", position: "P", eligibility: "FR", homeState: "IN", hometown: "Brownsburg", jerseyNumber: 48,
      hitForAvg: 12, power: 10, speed: 42, arm: 62, fielding: 38, errorResistance: 40, velocity: 64, control: 50, stamina: 48, stuff: 60,
      clutch: 42, vsLHP: 40, grit: 44, stealing: 14, running: 38, throwing: 60, recovery: 42, wRISP: 40, vsLefty: 44, poise: 42, heater: 62, agile: 46,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 4, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Costigan", position: "P", eligibility: "FR", homeState: "IN", hometown: "Zionsville", jerseyNumber: 50,
      hitForAvg: 12, power: 10, speed: 40, arm: 60, fielding: 36, errorResistance: 38, velocity: 62, control: 48, stamina: 46, stuff: 58,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 12, running: 36, throwing: 58, recovery: 40, wRISP: 38, vsLefty: 42, poise: 40, heater: 60, agile: 44,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "T.J.", lastName: "Schuyler", position: "C", eligibility: "JR", homeState: "IN", hometown: "Indianapolis", jerseyNumber: 12,
      hitForAvg: 62, power: 56, speed: 40, arm: 72, fielding: 70, errorResistance: 68, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 18, running: 38, throwing: 74, recovery: 54, wRISP: 62, vsLefty: 58, poise: 64, heater: 0, agile: 44,
      abilities: ["Iron Glove"], potential: "B+", catcherAbility: 68,
      ...noPitches },
    { firstName: "Hogan", lastName: "Denny", position: "C", eligibility: "SO", homeState: "IN", hometown: "Terre Haute", jerseyNumber: 19,
      hitForAvg: 56, power: 50, speed: 44, arm: 64, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 22, running: 42, throwing: 66, recovery: 48, wRISP: 54, vsLefty: 50, poise: 56, heater: 0, agile: 46,
      abilities: [], potential: "B+", catcherAbility: 60,
      ...noPitches },
    // INFIELDERS (5)
    { firstName: "Jake", lastName: "Hanley", position: "1B", eligibility: "SO", homeState: "IL", hometown: "Naperville", jerseyNumber: 8,
      hitForAvg: 78, power: 80, speed: 48, arm: 64, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 78, vsLHP: 74, grit: 78, stealing: 18, running: 46, throwing: 66, recovery: 60, wRISP: 78, vsLefty: 72, poise: 76, heater: 0, agile: 50,
      abilities: ["Power Surge", "Clutch Hitter", "Contact Machine"], potential: "A+", catcherAbility: null,
      ...noPitches },
    { firstName: "Cooper", lastName: "Malamazian", position: "SS", eligibility: "SO", homeState: "CA", hometown: "Thousand Oaks", jerseyNumber: 2,
      hitForAvg: 68, power: 54, speed: 68, arm: 74, fielding: 74, errorResistance: 72, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 50, running: 66, throwing: 76, recovery: 56, wRISP: 64, vsLefty: 60, poise: 66, heater: 0, agile: 72,
      abilities: ["Iron Glove", "Speed Demon"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Will", lastName: "Moore", position: "3B", eligibility: "SO", homeState: "IN", hometown: "Bloomington", jerseyNumber: 6,
      hitForAvg: 64, power: 58, speed: 52, arm: 68, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 28, running: 50, throwing: 70, recovery: 52, wRISP: 60, vsLefty: 56, poise: 62, heater: 0, agile: 54,
      abilities: ["Contact Machine"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Ayden", lastName: "Crouse", position: "2B", eligibility: "SR", homeState: "IN", hometown: "Evansville", jerseyNumber: 3,
      hitForAvg: 64, power: 50, speed: 58, arm: 62, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 38, running: 56, throwing: 64, recovery: 54, wRISP: 62, vsLefty: 58, poise: 64, heater: 0, agile: 60,
      abilities: ["Table Setter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Trey", lastName: "Meyers", position: "SS", eligibility: "FR", homeState: "IN", hometown: "Columbus", jerseyNumber: 24,
      hitForAvg: 44, power: 34, speed: 58, arm: 56, fielding: 52, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 40, grit: 44, stealing: 36, running: 56, throwing: 58, recovery: 38, wRISP: 40, vsLefty: 38, poise: 42, heater: 0, agile: 60,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Cole", lastName: "Decker", position: "OF", eligibility: "SO", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 1,
      hitForAvg: 64, power: 52, speed: 70, arm: 66, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 52, running: 68, throwing: 68, recovery: 52, wRISP: 60, vsLefty: 56, poise: 62, heater: 0, agile: 72,
      abilities: ["Speed Demon"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Caleb", lastName: "Koskie", position: "OF", eligibility: "SO", homeState: "MN", hometown: "Eden Prairie", jerseyNumber: 7,
      hitForAvg: 60, power: 54, speed: 60, arm: 68, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 40, running: 58, throwing: 70, recovery: 50, wRISP: 56, vsLefty: 52, poise: 58, heater: 0, agile: 62,
      abilities: ["Cannon Arm"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Brayden", lastName: "Ricketts", position: "OF", eligibility: "SO", homeState: "IN", hometown: "Greenfield", jerseyNumber: 9,
      hitForAvg: 58, power: 54, speed: 50, arm: 60, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 24, running: 48, throwing: 62, recovery: 48, wRISP: 56, vsLefty: 52, poise: 56, heater: 0, agile: 52,
      abilities: ["Clutch Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Cal", lastName: "Gates", position: "OF", eligibility: "FR", homeState: "CA", hometown: "San Diego", jerseyNumber: 11,
      hitForAvg: 52, power: 48, speed: 62, arm: 60, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 44, grit: 50, stealing: 40, running: 60, throwing: 62, recovery: 42, wRISP: 46, vsLefty: 42, poise: 48, heater: 0, agile: 64,
      abilities: [], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Noah", lastName: "Drake", position: "OF", eligibility: "FR", homeState: "IN", hometown: "Carmel", jerseyNumber: 26,
      hitForAvg: 42, power: 36, speed: 58, arm: 56, fielding: 48, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 36, running: 56, throwing: 58, recovery: 38, wRISP: 38, vsLefty: 36, poise: 40, heater: 0, agile: 60,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Grant", lastName: "Richardson", position: "DH", eligibility: "SO", homeState: "IN", hometown: "Terre Haute", jerseyNumber: 20,
      hitForAvg: 58, power: 54, speed: 42, arm: 52, fielding: 44, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 14, running: 40, throwing: 54, recovery: 48, wRISP: 56, vsLefty: 52, poise: 56, heater: 0, agile: 44,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Luke", lastName: "Preston", position: "1B", eligibility: "JR", homeState: "IN", hometown: "Fishers", jerseyNumber: 32,
      hitForAvg: 56, power: 52, speed: 40, arm: 56, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 14, running: 38, throwing: 58, recovery: 46, wRISP: 54, vsLefty: 50, poise: 54, heater: 0, agile: 42,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "James", lastName: "Hoffman", position: "OF", eligibility: "JR", homeState: "IN", hometown: "Muncie", jerseyNumber: 28,
      hitForAvg: 54, power: 48, speed: 58, arm: 60, fielding: 56, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 36, running: 56, throwing: 62, recovery: 46, wRISP: 50, vsLefty: 46, poise: 52, heater: 0, agile: 60,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "Iowa": [
    // PITCHERS (10)
    { firstName: "Tyler", lastName: "Guerin", position: "P", eligibility: "SO", homeState: "IA", hometown: "Ankeny", jerseyNumber: 11,
      hitForAvg: 16, power: 12, speed: 40, arm: 76, fielding: 48, errorResistance: 50, velocity: 78, control: 72, stamina: 74, stuff: 76,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 12, running: 36, throwing: 74, recovery: 64, wRISP: 66, vsLefty: 68, poise: 70, heater: 76, agile: 44,
      abilities: ["Strong Starter", "Workhorse"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 5, 0, 0, 0]) },
    { firstName: "Logan", lastName: "Runde", position: "P", eligibility: "SR", homeState: "FL", hometown: "Miami", jerseyNumber: 33,
      hitForAvg: 18, power: 14, speed: 38, arm: 78, fielding: 48, errorResistance: 50, velocity: 80, control: 74, stamina: 74, stuff: 78,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 10, running: 34, throwing: 76, recovery: 70, wRISP: 70, vsLefty: 72, poise: 74, heater: 78, agile: 44,
      abilities: ["Ace", "Explosive Fastball"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 7, 5, 5, 0, 0, 0]) },
    { firstName: "Joe", lastName: "Husak", position: "P", eligibility: "JR", homeState: "IL", hometown: "Normal", jerseyNumber: 35,
      hitForAvg: 18, power: 14, speed: 40, arm: 76, fielding: 48, errorResistance: 50, velocity: 78, control: 74, stamina: 66, stuff: 76,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 12, running: 36, throwing: 74, recovery: 68, wRISP: 70, vsLefty: 72, poise: 74, heater: 76, agile: 44,
      abilities: ["Fireman", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 7, 5, 4, 0, 0, 0]) },
    { firstName: "Justin", lastName: "Hackett", position: "P", eligibility: "JR", homeState: "IA", hometown: "Iowa City", jerseyNumber: 38,
      hitForAvg: 16, power: 12, speed: 38, arm: 72, fielding: 46, errorResistance: 48, velocity: 74, control: 70, stamina: 70, stuff: 72,
      clutch: 64, vsLHP: 62, grit: 66, stealing: 10, running: 34, throwing: 70, recovery: 64, wRISP: 62, vsLefty: 66, poise: 66, heater: 72, agile: 42,
      abilities: ["Filthy Breaking Ball"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 5, 0, 0, 0]) },
    { firstName: "Ganon", lastName: "Archer", position: "P", eligibility: "JR", homeState: "IA", hometown: "Davenport", jerseyNumber: 40,
      hitForAvg: 18, power: 14, speed: 36, arm: 70, fielding: 48, errorResistance: 50, velocity: 72, control: 70, stamina: 70, stuff: 70,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 10, running: 32, throwing: 68, recovery: 64, wRISP: 64, vsLefty: 66, poise: 68, heater: 70, agile: 42,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Marcus", lastName: "Kruzan", position: "P", eligibility: "JR", homeState: "IN", hometown: "Greenwood", jerseyNumber: 42,
      hitForAvg: 16, power: 12, speed: 38, arm: 68, fielding: 44, errorResistance: 46, velocity: 70, control: 68, stamina: 66, stuff: 68,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 10, running: 34, throwing: 66, recovery: 60, wRISP: 60, vsLefty: 62, poise: 64, heater: 68, agile: 42,
      abilities: [], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Derek", lastName: "Nagel", position: "P", eligibility: "JR", homeState: "IA", hometown: "Urbandale", jerseyNumber: 44,
      hitForAvg: 16, power: 12, speed: 38, arm: 68, fielding: 44, errorResistance: 46, velocity: 70, control: 66, stamina: 66, stuff: 68,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 10, running: 34, throwing: 66, recovery: 58, wRISP: 58, vsLefty: 60, poise: 62, heater: 68, agile: 42,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Braden", lastName: "Halladay", position: "P", eligibility: "SO", homeState: "IA", hometown: "Cedar Rapids", jerseyNumber: 46,
      hitForAvg: 14, power: 10, speed: 40, arm: 66, fielding: 42, errorResistance: 44, velocity: 68, control: 62, stamina: 62, stuff: 66,
      clutch: 54, vsLHP: 52, grit: 58, stealing: 12, running: 36, throwing: 64, recovery: 54, wRISP: 52, vsLefty: 56, poise: 56, heater: 66, agile: 44,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 5, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Stedman", position: "P", eligibility: "FR", homeState: "IA", hometown: "Waukee", jerseyNumber: 48,
      hitForAvg: 12, power: 10, speed: 42, arm: 64, fielding: 38, errorResistance: 40, velocity: 65, control: 50, stamina: 48, stuff: 62,
      clutch: 42, vsLHP: 40, grit: 44, stealing: 14, running: 38, throwing: 62, recovery: 42, wRISP: 40, vsLefty: 44, poise: 42, heater: 64, agile: 46,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 4, 0, 0, 0]) },
    { firstName: "Jaron", lastName: "Bleeker", position: "P", eligibility: "FR", homeState: "IA", hometown: "Pella", jerseyNumber: 50,
      hitForAvg: 12, power: 10, speed: 40, arm: 62, fielding: 36, errorResistance: 38, velocity: 62, control: 48, stamina: 46, stuff: 58,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 12, running: 36, throwing: 58, recovery: 40, wRISP: 38, vsLefty: 42, poise: 40, heater: 60, agile: 44,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Drew", lastName: "Deremer", position: "C", eligibility: "SO", homeState: "IA", hometown: "Marion", jerseyNumber: 14,
      hitForAvg: 56, power: 48, speed: 38, arm: 68, fielding: 66, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 16, running: 36, throwing: 70, recovery: 50, wRISP: 56, vsLefty: 52, poise: 58, heater: 0, agile: 42,
      abilities: ["Iron Glove"], potential: "B+", catcherAbility: 66,
      ...noPitches },
    { firstName: "Ben", lastName: "DeTaeye", position: "C", eligibility: "SR", homeState: "IA", hometown: "Johnston", jerseyNumber: 18,
      hitForAvg: 58, power: 50, speed: 36, arm: 66, fielding: 64, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 14, running: 34, throwing: 68, recovery: 52, wRISP: 58, vsLefty: 54, poise: 60, heater: 0, agile: 40,
      abilities: ["Cannon Arm"], potential: "B", catcherAbility: 64,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Jack", lastName: "Whitlock", position: "1B", eligibility: "SR", homeState: "IA", hometown: "Des Moines", jerseyNumber: 8,
      hitForAvg: 70, power: 72, speed: 44, arm: 62, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 16, running: 42, throwing: 64, recovery: 58, wRISP: 70, vsLefty: 64, poise: 70, heater: 0, agile: 46,
      abilities: ["Power Surge", "Clutch Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Anthony", lastName: "Watts", position: "2B", eligibility: "JR", homeState: "IA", hometown: "North Liberty", jerseyNumber: 3,
      hitForAvg: 64, power: 50, speed: 60, arm: 64, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 40, running: 58, throwing: 66, recovery: 52, wRISP: 60, vsLefty: 56, poise: 62, heater: 0, agile: 62,
      abilities: ["Table Setter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Chas", lastName: "Wheatley", position: "3B", eligibility: "SR", homeState: "IA", hometown: "Ankeny", jerseyNumber: 5,
      hitForAvg: 68, power: 64, speed: 50, arm: 68, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 26, running: 48, throwing: 70, recovery: 56, wRISP: 66, vsLefty: 62, poise: 68, heater: 0, agile: 52,
      abilities: ["Contact Machine"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Aaron", lastName: "Savary", position: "SS", eligibility: "JR", homeState: "IA", hometown: "Urbandale", jerseyNumber: 2,
      hitForAvg: 66, power: 52, speed: 66, arm: 74, fielding: 74, errorResistance: 72, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 48, running: 64, throwing: 76, recovery: 56, wRISP: 64, vsLefty: 60, poise: 66, heater: 0, agile: 70,
      abilities: ["Iron Glove"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Garrett", lastName: "Luett", position: "SS", eligibility: "FR", homeState: "IA", hometown: "Bettendorf", jerseyNumber: 24,
      hitForAvg: 44, power: 34, speed: 58, arm: 56, fielding: 52, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 40, grit: 44, stealing: 36, running: 56, throwing: 58, recovery: 38, wRISP: 40, vsLefty: 38, poise: 42, heater: 0, agile: 60,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Gavin", lastName: "DeJesus", position: "2B", eligibility: "FR", homeState: "IL", hometown: "Naperville", jerseyNumber: 16,
      hitForAvg: 42, power: 32, speed: 54, arm: 54, fielding: 50, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 32, running: 52, throwing: 56, recovery: 38, wRISP: 38, vsLefty: 36, poise: 40, heater: 0, agile: 56,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (5)
    { firstName: "Gable", lastName: "Mitchell", position: "OF", eligibility: "SR", homeState: "IA", hometown: "Iowa City", jerseyNumber: 1,
      hitForAvg: 74, power: 68, speed: 66, arm: 72, fielding: 70, errorResistance: 68, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 74, vsLHP: 70, grit: 76, stealing: 48, running: 64, throwing: 74, recovery: 58, wRISP: 72, vsLefty: 68, poise: 74, heater: 0, agile: 68,
      abilities: ["Contact Machine", "Clutch Hitter", "Cannon Arm"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Cade", lastName: "Obermueller", position: "OF", eligibility: "JR", homeState: "IA", hometown: "Waukee", jerseyNumber: 7,
      hitForAvg: 62, power: 54, speed: 62, arm: 66, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 42, running: 60, throwing: 68, recovery: 52, wRISP: 58, vsLefty: 54, poise: 60, heater: 0, agile: 64,
      abilities: ["Speed Demon"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Elliot", lastName: "Cadieux-Lanoue", position: "OF", eligibility: "SO", homeState: "MN", hometown: "Edina", jerseyNumber: 9,
      hitForAvg: 56, power: 48, speed: 62, arm: 64, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 42, running: 60, throwing: 66, recovery: 46, wRISP: 52, vsLefty: 48, poise: 54, heater: 0, agile: 64,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jack", lastName: "Young", position: "OF", eligibility: "SR", homeState: "IA", hometown: "Sioux City", jerseyNumber: 4,
      hitForAvg: 64, power: 56, speed: 58, arm: 66, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 38, running: 56, throwing: 68, recovery: 54, wRISP: 62, vsLefty: 58, poise: 64, heater: 0, agile: 60,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Joey", lastName: "Oakie", position: "OF", eligibility: "FR", homeState: "IA", hometown: "Dubuque", jerseyNumber: 26,
      hitForAvg: 40, power: 34, speed: 56, arm: 54, fielding: 46, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 34, running: 54, throwing: 56, recovery: 36, wRISP: 36, vsLefty: 34, poise: 38, heater: 0, agile: 58,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Sam", lastName: "Hart", position: "DH", eligibility: "SR", homeState: "IA", hometown: "Cedar Falls", jerseyNumber: 20,
      hitForAvg: 66, power: 62, speed: 40, arm: 52, fielding: 44, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 14, running: 38, throwing: 54, recovery: 52, wRISP: 64, vsLefty: 60, poise: 64, heater: 0, agile: 42,
      abilities: ["Clutch Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Will", lastName: "Heldt", position: "1B", eligibility: "SO", homeState: "IA", hometown: "Dubuque", jerseyNumber: 32,
      hitForAvg: 48, power: 46, speed: 38, arm: 56, fielding: 52, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 44, grit: 50, stealing: 14, running: 36, throwing: 58, recovery: 42, wRISP: 46, vsLefty: 42, poise: 46, heater: 0, agile: 40,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "Maryland": [
    // PITCHERS (10)
    { firstName: "Lance", lastName: "Williams", position: "P", eligibility: "SO", homeState: "NC", hometown: "Greenville", jerseyNumber: 34,
      hitForAvg: 20, power: 16, speed: 42, arm: 86, fielding: 52, errorResistance: 54, velocity: 88, control: 74, stamina: 76, stuff: 86,
      clutch: 76, vsLHP: 72, grit: 78, stealing: 14, running: 38, throwing: 84, recovery: 68, wRISP: 74, vsLefty: 76, poise: 76, heater: 88, agile: 48,
      abilities: ["Ace", "Explosive Fastball", "Strong Starter"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 7, 5, 6, 0, 0, 0]) },
    { firstName: "Austin", lastName: "Weiss", position: "P", eligibility: "FR", homeState: "MD", hometown: "Annapolis", jerseyNumber: 29,
      hitForAvg: 14, power: 10, speed: 40, arm: 68, fielding: 40, errorResistance: 42, velocity: 70, control: 58, stamina: 54, stuff: 68,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 12, running: 36, throwing: 66, recovery: 46, wRISP: 48, vsLefty: 50, poise: 50, heater: 68, agile: 44,
      abilities: [], potential: "A+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Cristofer", lastName: "Cespedes", position: "P", eligibility: "SO", homeState: "FL", hometown: "Miami", jerseyNumber: 37,
      hitForAvg: 16, power: 12, speed: 40, arm: 72, fielding: 46, errorResistance: 48, velocity: 74, control: 68, stamina: 66, stuff: 72,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 12, running: 36, throwing: 70, recovery: 58, wRISP: 60, vsLefty: 62, poise: 62, heater: 72, agile: 44,
      abilities: ["Fireman"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 4, 5, 0, 0, 0]) },
    { firstName: "Logan", lastName: "Hastings", position: "P", eligibility: "SO", homeState: "MD", hometown: "Columbia", jerseyNumber: 35,
      hitForAvg: 16, power: 12, speed: 38, arm: 70, fielding: 46, errorResistance: 48, velocity: 72, control: 68, stamina: 68, stuff: 70,
      clutch: 60, vsLHP: 58, grit: 64, stealing: 10, running: 34, throwing: 68, recovery: 60, wRISP: 58, vsLefty: 62, poise: 62, heater: 70, agile: 42,
      abilities: ["Filthy Breaking Ball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 6, 4, 0, 0, 0]) },
    { firstName: "Evan", lastName: "Smith", position: "P", eligibility: "JR", homeState: "MD", hometown: "Bethesda", jerseyNumber: 22,
      hitForAvg: 16, power: 12, speed: 38, arm: 70, fielding: 46, errorResistance: 48, velocity: 72, control: 70, stamina: 64, stuff: 70,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 10, running: 34, throwing: 68, recovery: 58, wRISP: 60, vsLefty: 62, poise: 64, heater: 70, agile: 42,
      abilities: ["Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Brayden", lastName: "Ryan", position: "P", eligibility: "JR", homeState: "MD", hometown: "Severna Park", jerseyNumber: 38,
      hitForAvg: 18, power: 14, speed: 36, arm: 68, fielding: 48, errorResistance: 50, velocity: 70, control: 70, stamina: 68, stuff: 68,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 10, running: 32, throwing: 66, recovery: 62, wRISP: 62, vsLefty: 64, poise: 66, heater: 68, agile: 42,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Bailey", position: "P", eligibility: "JR", homeState: "VA", hometown: "Ashburn", jerseyNumber: 40,
      hitForAvg: 16, power: 12, speed: 38, arm: 68, fielding: 44, errorResistance: 46, velocity: 70, control: 68, stamina: 66, stuff: 68,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 10, running: 34, throwing: 66, recovery: 60, wRISP: 60, vsLefty: 62, poise: 64, heater: 68, agile: 42,
      abilities: [], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Yeager", position: "P", eligibility: "JR", homeState: "PA", hometown: "Doylestown", jerseyNumber: 42,
      hitForAvg: 16, power: 12, speed: 38, arm: 66, fielding: 44, errorResistance: 46, velocity: 68, control: 66, stamina: 66, stuff: 66,
      clutch: 58, vsLHP: 56, grit: 60, stealing: 10, running: 34, throwing: 64, recovery: 58, wRISP: 56, vsLefty: 60, poise: 60, heater: 66, agile: 42,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 5, 0, 0, 0]) },
    { firstName: "Max", lastName: "Mendez", position: "P", eligibility: "SO", homeState: "TN", hometown: "Nashville", jerseyNumber: 44,
      hitForAvg: 16, power: 12, speed: 40, arm: 72, fielding: 46, errorResistance: 48, velocity: 74, control: 68, stamina: 66, stuff: 72,
      clutch: 62, vsLHP: 60, grit: 64, stealing: 12, running: 36, throwing: 70, recovery: 58, wRISP: 60, vsLefty: 62, poise: 62, heater: 72, agile: 44,
      abilities: ["Workhorse"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 4, 0, 0, 0]) },
    { firstName: "Nic", lastName: "Morlang", position: "P", eligibility: "FR", homeState: "MD", hometown: "Ellicott City", jerseyNumber: 50,
      hitForAvg: 12, power: 10, speed: 40, arm: 62, fielding: 36, errorResistance: 38, velocity: 64, control: 48, stamina: 46, stuff: 60,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 12, running: 36, throwing: 60, recovery: 40, wRISP: 38, vsLefty: 42, poise: 40, heater: 62, agile: 44,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Rylen", lastName: "Stockton", position: "C", eligibility: "SO", homeState: "NC", hometown: "Asheville", jerseyNumber: 14,
      hitForAvg: 68, power: 58, speed: 40, arm: 72, fielding: 70, errorResistance: 68, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 18, running: 38, throwing: 74, recovery: 56, wRISP: 66, vsLefty: 62, poise: 68, heater: 0, agile: 44,
      abilities: ["Iron Glove", "Contact Machine"], potential: "A-", catcherAbility: 70,
      ...noPitches },
    { firstName: "Devin", lastName: "Russell", position: "C", eligibility: "JR", homeState: "MD", hometown: "Pasadena", jerseyNumber: 18,
      hitForAvg: 52, power: 46, speed: 36, arm: 64, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 14, running: 34, throwing: 66, recovery: 48, wRISP: 52, vsLefty: 48, poise: 52, heater: 0, agile: 40,
      abilities: [], potential: "B", catcherAbility: 62,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Ryan", lastName: "Costello", position: "1B", eligibility: "JR", homeState: "LA", hometown: "Baton Rouge", jerseyNumber: 8,
      hitForAvg: 66, power: 68, speed: 44, arm: 62, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 16, running: 42, throwing: 64, recovery: 56, wRISP: 66, vsLefty: 60, poise: 66, heater: 0, agile: 46,
      abilities: ["Power Surge"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jordan", lastName: "Crosland", position: "2B", eligibility: "SO", homeState: "MD", hometown: "Bowie", jerseyNumber: 3,
      hitForAvg: 72, power: 50, speed: 60, arm: 64, fielding: 70, errorResistance: 68, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 42, running: 58, throwing: 66, recovery: 54, wRISP: 66, vsLefty: 62, poise: 68, heater: 0, agile: 62,
      abilities: ["Contact Machine", "Table Setter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Brayden", lastName: "Martin", position: "3B", eligibility: "JR", homeState: "MD", hometown: "Severna Park", jerseyNumber: 5,
      hitForAvg: 72, power: 62, speed: 56, arm: 68, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 34, running: 54, throwing: 70, recovery: 56, wRISP: 68, vsLefty: 64, poise: 70, heater: 0, agile: 58,
      abilities: ["Clutch Hitter", "Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Ty", lastName: "Kaunas", position: "SS", eligibility: "FR", homeState: "MD", hometown: "Columbia", jerseyNumber: 2,
      hitForAvg: 56, power: 44, speed: 64, arm: 62, fielding: 58, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 42, running: 62, throwing: 64, recovery: 42, wRISP: 48, vsLefty: 44, poise: 50, heater: 0, agile: 66,
      abilities: ["Speed Demon"], potential: "A+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jackson", lastName: "Sirois", position: "SS", eligibility: "SO", homeState: "VA", hometown: "Charlottesville", jerseyNumber: 10,
      hitForAvg: 62, power: 48, speed: 62, arm: 68, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 44, running: 60, throwing: 70, recovery: 50, wRISP: 58, vsLefty: 54, poise: 60, heater: 0, agile: 64,
      abilities: ["Iron Glove"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Luke", lastName: "Crawford", position: "1B", eligibility: "JR", homeState: "MD", hometown: "Bethesda", jerseyNumber: 32,
      hitForAvg: 56, power: 54, speed: 38, arm: 56, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 14, running: 36, throwing: 58, recovery: 46, wRISP: 52, vsLefty: 48, poise: 52, heater: 0, agile: 40,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (5)
    { firstName: "Aden", lastName: "Hill", position: "OF", eligibility: "SR", homeState: "VA", hometown: "Richmond", jerseyNumber: 1,
      hitForAvg: 70, power: 64, speed: 64, arm: 70, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 44, running: 62, throwing: 72, recovery: 58, wRISP: 68, vsLefty: 64, poise: 70, heater: 0, agile: 66,
      abilities: ["Cannon Arm", "Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Bud", lastName: "Coombs", position: "OF", eligibility: "FR", homeState: "MD", hometown: "Bel Air", jerseyNumber: 7,
      hitForAvg: 52, power: 46, speed: 62, arm: 60, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 44, grit: 50, stealing: 40, running: 60, throwing: 62, recovery: 42, wRISP: 46, vsLefty: 42, poise: 48, heater: 0, agile: 64,
      abilities: [], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Nate", lastName: "Hawton-Henley", position: "OF", eligibility: "FR", homeState: "MD", hometown: "Rockville", jerseyNumber: 9,
      hitForAvg: 40, power: 34, speed: 56, arm: 54, fielding: 46, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 34, running: 54, throwing: 56, recovery: 36, wRISP: 36, vsLefty: 34, poise: 38, heater: 0, agile: 58,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Chris", lastName: "Patterson", position: "OF", eligibility: "SR", homeState: "MD", hometown: "Bowie", jerseyNumber: 4,
      hitForAvg: 64, power: 56, speed: 60, arm: 66, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 40, running: 58, throwing: 68, recovery: 52, wRISP: 60, vsLefty: 56, poise: 62, heater: 0, agile: 62,
      abilities: ["Speed Demon"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Tyler", lastName: "Hoffman", position: "DH", eligibility: "JR", homeState: "MD", hometown: "Pasadena", jerseyNumber: 20,
      hitForAvg: 62, power: 58, speed: 42, arm: 52, fielding: 44, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 14, running: 40, throwing: 54, recovery: 50, wRISP: 60, vsLefty: 56, poise: 60, heater: 0, agile: 44,
      abilities: ["Clutch Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Kevin", lastName: "Brennan", position: "3B", eligibility: "SR", homeState: "MD", hometown: "Bel Air", jerseyNumber: 16,
      hitForAvg: 58, power: 52, speed: 48, arm: 62, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 22, running: 46, throwing: 64, recovery: 48, wRISP: 56, vsLefty: 52, poise: 56, heater: 0, agile: 50,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Matt", lastName: "Whitmore", position: "OF", eligibility: "SO", homeState: "VA", hometown: "Fairfax", jerseyNumber: 28,
      hitForAvg: 52, power: 46, speed: 58, arm: 60, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 36, running: 56, throwing: 62, recovery: 44, wRISP: 48, vsLefty: 44, poise: 50, heater: 0, agile: 60,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "Michigan": [
    // PITCHERS (10)
    { firstName: "Tate", lastName: "Carey", position: "P", eligibility: "SO", homeState: "MI", hometown: "Grand Rapids", jerseyNumber: 34,
      hitForAvg: 18, power: 14, speed: 42, arm: 82, fielding: 50, errorResistance: 52, velocity: 84, control: 76, stamina: 76, stuff: 82,
      clutch: 74, vsLHP: 70, grit: 76, stealing: 14, running: 38, throwing: 80, recovery: 68, wRISP: 72, vsLefty: 74, poise: 76, heater: 82, agile: 46,
      abilities: ["Ace", "Explosive Fastball"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 7, 5, 6, 0, 0, 0]) },
    { firstName: "Kurt", lastName: "Barr", position: "P", eligibility: "SR", homeState: "MI", hometown: "Ann Arbor", jerseyNumber: 29,
      hitForAvg: 18, power: 14, speed: 38, arm: 76, fielding: 48, errorResistance: 50, velocity: 78, control: 76, stamina: 76, stuff: 76,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 10, running: 34, throwing: 74, recovery: 70, wRISP: 70, vsLefty: 72, poise: 74, heater: 76, agile: 44,
      abilities: ["Strong Starter", "Workhorse"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 5, 0, 0, 0]) },
    { firstName: "Gavin", lastName: "DeVooght", position: "P", eligibility: "JR", homeState: "MI", hometown: "Brighton", jerseyNumber: 33,
      hitForAvg: 16, power: 12, speed: 40, arm: 72, fielding: 46, errorResistance: 48, velocity: 74, control: 70, stamina: 70, stuff: 72,
      clutch: 64, vsLHP: 62, grit: 66, stealing: 12, running: 36, throwing: 70, recovery: 64, wRISP: 62, vsLefty: 66, poise: 66, heater: 72, agile: 44,
      abilities: ["Filthy Breaking Ball"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 6, 4, 0, 0, 0]) },
    { firstName: "Max", lastName: "Debiec", position: "P", eligibility: "SR", homeState: "MI", hometown: "Shelby Township", jerseyNumber: 38,
      hitForAvg: 18, power: 14, speed: 36, arm: 74, fielding: 48, errorResistance: 50, velocity: 76, control: 72, stamina: 74, stuff: 74,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 10, running: 32, throwing: 72, recovery: 66, wRISP: 66, vsLefty: 68, poise: 70, heater: 74, agile: 42,
      abilities: ["Strong Starter", "Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 4, 0, 0, 0]) },
    { firstName: "Brandon", lastName: "Mann", position: "P", eligibility: "SR", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 22,
      hitForAvg: 18, power: 14, speed: 38, arm: 72, fielding: 48, errorResistance: 50, velocity: 74, control: 72, stamina: 70, stuff: 72,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 10, running: 34, throwing: 70, recovery: 66, wRISP: 66, vsLefty: 68, poise: 70, heater: 72, agile: 42,
      abilities: ["Fireman"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 0, 5, 0, 0]) },
    { firstName: "Wyatt", lastName: "Novara", position: "P", eligibility: "JR", homeState: "MI", hometown: "Traverse City", jerseyNumber: 40,
      hitForAvg: 16, power: 12, speed: 38, arm: 70, fielding: 46, errorResistance: 48, velocity: 72, control: 70, stamina: 68, stuff: 70,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 10, running: 34, throwing: 68, recovery: 62, wRISP: 62, vsLefty: 64, poise: 66, heater: 70, agile: 42,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Cade", lastName: "Montgomery", position: "P", eligibility: "JR", homeState: "MI", hometown: "Portage", jerseyNumber: 42,
      hitForAvg: 16, power: 12, speed: 40, arm: 70, fielding: 44, errorResistance: 46, velocity: 72, control: 68, stamina: 66, stuff: 70,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 12, running: 36, throwing: 68, recovery: 60, wRISP: 60, vsLefty: 62, poise: 64, heater: 70, agile: 44,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 5, 0, 0, 0]) },
    { firstName: "David", lastName: "Lally Jr", position: "P", eligibility: "SR", homeState: "MI", hometown: "Novi", jerseyNumber: 44,
      hitForAvg: 16, power: 12, speed: 36, arm: 68, fielding: 46, errorResistance: 48, velocity: 70, control: 70, stamina: 68, stuff: 68,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 10, running: 32, throwing: 66, recovery: 62, wRISP: 62, vsLefty: 64, poise: 66, heater: 68, agile: 42,
      abilities: ["Guts"], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 5, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Bischoff", position: "P", eligibility: "FR", homeState: "MI", hometown: "Rochester Hills", jerseyNumber: 48,
      hitForAvg: 12, power: 10, speed: 42, arm: 64, fielding: 38, errorResistance: 40, velocity: 65, control: 50, stamina: 48, stuff: 62,
      clutch: 42, vsLHP: 40, grit: 44, stealing: 14, running: 38, throwing: 62, recovery: 42, wRISP: 40, vsLefty: 44, poise: 42, heater: 64, agile: 46,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 4, 0, 0, 0]) },
    { firstName: "Ethan", lastName: "VanBuskirk", position: "P", eligibility: "FR", homeState: "MI", hometown: "Holland", jerseyNumber: 50,
      hitForAvg: 12, power: 10, speed: 40, arm: 60, fielding: 36, errorResistance: 38, velocity: 62, control: 48, stamina: 46, stuff: 58,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 12, running: 36, throwing: 58, recovery: 40, wRISP: 38, vsLefty: 42, poise: 40, heater: 60, agile: 44,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Noah", lastName: "Miller", position: "C", eligibility: "SO", homeState: "MI", hometown: "Clarkston", jerseyNumber: 14,
      hitForAvg: 66, power: 56, speed: 40, arm: 72, fielding: 70, errorResistance: 68, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 18, running: 38, throwing: 74, recovery: 56, wRISP: 64, vsLefty: 60, poise: 66, heater: 0, agile: 44,
      abilities: ["Iron Glove", "Contact Machine"], potential: "A-", catcherAbility: 70,
      ...noPitches },
    { firstName: "Luke", lastName: "Sefcik", position: "C", eligibility: "JR", homeState: "MI", hometown: "Macomb", jerseyNumber: 19,
      hitForAvg: 50, power: 44, speed: 36, arm: 64, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 14, running: 34, throwing: 66, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 40,
      abilities: [], potential: "B", catcherAbility: 60,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Joe", lastName: "Longo", position: "1B", eligibility: "SR", homeState: "NJ", hometown: "Westfield", jerseyNumber: 8,
      hitForAvg: 70, power: 68, speed: 44, arm: 62, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 16, running: 42, throwing: 64, recovery: 58, wRISP: 68, vsLefty: 64, poise: 70, heater: 0, agile: 46,
      abilities: ["Power Surge", "Clutch Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Brayden", lastName: "Jefferis", position: "2B", eligibility: "SO", homeState: "MI", hometown: "Canton", jerseyNumber: 3,
      hitForAvg: 62, power: 48, speed: 60, arm: 64, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 40, running: 58, throwing: 66, recovery: 52, wRISP: 58, vsLefty: 54, poise: 60, heater: 0, agile: 62,
      abilities: ["Table Setter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Colby", lastName: "Turner", position: "3B", eligibility: "JR", homeState: "MI", hometown: "Saline", jerseyNumber: 5,
      hitForAvg: 66, power: 60, speed: 52, arm: 68, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 28, running: 50, throwing: 70, recovery: 54, wRISP: 64, vsLefty: 60, poise: 66, heater: 0, agile: 54,
      abilities: ["Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Drew", lastName: "Culbertson", position: "SS", eligibility: "JR", homeState: "OH", hometown: "Dublin", jerseyNumber: 2,
      hitForAvg: 64, power: 52, speed: 66, arm: 74, fielding: 72, errorResistance: 70, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 48, running: 64, throwing: 76, recovery: 54, wRISP: 60, vsLefty: 56, poise: 62, heater: 0, agile: 68,
      abilities: ["Iron Glove", "Speed Demon"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Carson", lastName: "Luna", position: "SS", eligibility: "FR", homeState: "AZ", hometown: "Scottsdale", jerseyNumber: 24,
      hitForAvg: 48, power: 38, speed: 60, arm: 58, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 42, grit: 46, stealing: 38, running: 58, throwing: 60, recovery: 40, wRISP: 42, vsLefty: 40, poise: 44, heater: 0, agile: 62,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Dane", lastName: "Morrow", position: "2B", eligibility: "FR", homeState: "MI", hometown: "East Lansing", jerseyNumber: 16,
      hitForAvg: 44, power: 34, speed: 54, arm: 54, fielding: 50, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 40, grit: 44, stealing: 32, running: 52, throwing: 56, recovery: 38, wRISP: 40, vsLefty: 38, poise: 42, heater: 0, agile: 56,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (5)
    { firstName: "Jonathan", lastName: "Kim", position: "OF", eligibility: "SR", homeState: "CA", hometown: "Irvine", jerseyNumber: 1,
      hitForAvg: 70, power: 62, speed: 64, arm: 70, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 46, running: 62, throwing: 72, recovery: 56, wRISP: 66, vsLefty: 62, poise: 68, heater: 0, agile: 66,
      abilities: ["Cannon Arm", "Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Greg", lastName: "Pace Jr", position: "OF", eligibility: "JR", homeState: "GA", hometown: "Marietta", jerseyNumber: 7,
      hitForAvg: 64, power: 58, speed: 62, arm: 68, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 42, running: 60, throwing: 70, recovery: 52, wRISP: 60, vsLefty: 56, poise: 62, heater: 0, agile: 64,
      abilities: ["Speed Demon"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Brenden", lastName: "Stressler", position: "OF", eligibility: "JR", homeState: "PA", hometown: "State College", jerseyNumber: 9,
      hitForAvg: 60, power: 54, speed: 58, arm: 66, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 38, running: 56, throwing: 68, recovery: 50, wRISP: 56, vsLefty: 52, poise: 58, heater: 0, agile: 60,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Evan", lastName: "Haeger", position: "OF", eligibility: "SO", homeState: "MI", hometown: "Kalamazoo", jerseyNumber: 11,
      hitForAvg: 56, power: 48, speed: 62, arm: 64, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 42, running: 60, throwing: 66, recovery: 46, wRISP: 52, vsLefty: 48, poise: 54, heater: 0, agile: 64,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jack", lastName: "Summers", position: "OF", eligibility: "FR", homeState: "MI", hometown: "Grosse Pointe", jerseyNumber: 26,
      hitForAvg: 40, power: 34, speed: 56, arm: 54, fielding: 46, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 34, running: 54, throwing: 56, recovery: 36, wRISP: 36, vsLefty: 34, poise: 38, heater: 0, agile: 58,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Marcus", lastName: "Chen", position: "DH", eligibility: "JR", homeState: "MI", hometown: "Ann Arbor", jerseyNumber: 20,
      hitForAvg: 60, power: 56, speed: 40, arm: 50, fielding: 42, errorResistance: 40, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 14, running: 38, throwing: 52, recovery: 48, wRISP: 58, vsLefty: 54, poise: 58, heater: 0, agile: 42,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "Walsh", position: "OF", eligibility: "SO", homeState: "MI", hometown: "Birmingham", jerseyNumber: 28,
      hitForAvg: 42, power: 36, speed: 58, arm: 56, fielding: 48, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 36, running: 56, throwing: 58, recovery: 38, wRISP: 38, vsLefty: 36, poise: 40, heater: 0, agile: 60,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
  ],

  "Michigan State": [
    // PITCHERS (10)
    { firstName: "Nick", lastName: "Powers", position: "P", eligibility: "JR", homeState: "MI", hometown: "Grand Rapids", jerseyNumber: 34,
      hitForAvg: 18, power: 14, speed: 40, arm: 74, fielding: 48, errorResistance: 50, velocity: 76, control: 72, stamina: 74, stuff: 74,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 12, running: 36, throwing: 72, recovery: 66, wRISP: 66, vsLefty: 68, poise: 70, heater: 74, agile: 44,
      abilities: ["Ace", "Strong Starter"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 5, 0, 0, 0]) },
    { firstName: "Derek", lastName: "Kontul", position: "P", eligibility: "SR", homeState: "MI", hometown: "Midland", jerseyNumber: 29,
      hitForAvg: 18, power: 14, speed: 38, arm: 72, fielding: 48, errorResistance: 50, velocity: 74, control: 72, stamina: 72, stuff: 72,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 10, running: 34, throwing: 70, recovery: 66, wRISP: 66, vsLefty: 68, poise: 70, heater: 72, agile: 44,
      abilities: ["Workhorse"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Szczepanski", position: "P", eligibility: "JR", homeState: "MI", hometown: "Dearborn", jerseyNumber: 33,
      hitForAvg: 16, power: 12, speed: 40, arm: 70, fielding: 46, errorResistance: 48, velocity: 72, control: 68, stamina: 68, stuff: 70,
      clutch: 62, vsLHP: 60, grit: 64, stealing: 12, running: 36, throwing: 68, recovery: 60, wRISP: 60, vsLefty: 64, poise: 64, heater: 70, agile: 44,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Wyatt", lastName: "Rush", position: "P", eligibility: "FR", homeState: "OH", hometown: "Columbus", jerseyNumber: 37,
      hitForAvg: 14, power: 10, speed: 42, arm: 66, fielding: 40, errorResistance: 42, velocity: 68, control: 54, stamina: 52, stuff: 64,
      clutch: 46, vsLHP: 44, grit: 48, stealing: 14, running: 38, throwing: 64, recovery: 44, wRISP: 44, vsLefty: 48, poise: 46, heater: 66, agile: 46,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 5, 3, 4, 0, 0, 0]) },
    { firstName: "Jacob", lastName: "Kelley", position: "P", eligibility: "FR", homeState: "MI", hometown: "Lansing", jerseyNumber: 38,
      hitForAvg: 12, power: 10, speed: 40, arm: 64, fielding: 38, errorResistance: 40, velocity: 66, control: 52, stamina: 50, stuff: 62,
      clutch: 44, vsLHP: 42, grit: 46, stealing: 12, running: 36, throwing: 62, recovery: 42, wRISP: 42, vsLefty: 46, poise: 44, heater: 64, agile: 44,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 3, 0, 0, 0]) },
    { firstName: "Marcus", lastName: "Webb", position: "P", eligibility: "JR", homeState: "IN", hometown: "Fort Wayne", jerseyNumber: 22,
      hitForAvg: 16, power: 12, speed: 38, arm: 68, fielding: 44, errorResistance: 46, velocity: 70, control: 66, stamina: 66, stuff: 68,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 10, running: 34, throwing: 66, recovery: 58, wRISP: 58, vsLefty: 60, poise: 62, heater: 68, agile: 42,
      abilities: ["Fireman"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 4, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Vlasak", position: "P", eligibility: "SO", homeState: "MI", hometown: "Portage", jerseyNumber: 40,
      hitForAvg: 14, power: 10, speed: 40, arm: 66, fielding: 42, errorResistance: 44, velocity: 68, control: 62, stamina: 62, stuff: 66,
      clutch: 54, vsLHP: 52, grit: 58, stealing: 12, running: 36, throwing: 64, recovery: 54, wRISP: 52, vsLefty: 56, poise: 56, heater: 66, agile: 44,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Andrew", lastName: "Miller", position: "P", eligibility: "FR", homeState: "MI", hometown: "Troy", jerseyNumber: 42,
      hitForAvg: 12, power: 10, speed: 42, arm: 62, fielding: 38, errorResistance: 40, velocity: 64, control: 50, stamina: 48, stuff: 60,
      clutch: 42, vsLHP: 40, grit: 44, stealing: 14, running: 38, throwing: 60, recovery: 42, wRISP: 40, vsLefty: 44, poise: 42, heater: 62, agile: 46,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 4, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Kelmer", position: "P", eligibility: "FR", homeState: "MI", hometown: "Kalamazoo", jerseyNumber: 44,
      hitForAvg: 12, power: 10, speed: 40, arm: 60, fielding: 36, errorResistance: 38, velocity: 62, control: 48, stamina: 46, stuff: 58,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 12, running: 36, throwing: 58, recovery: 40, wRISP: 38, vsLefty: 42, poise: 40, heater: 60, agile: 44,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    { firstName: "Kyle", lastName: "Tishinski", position: "P", eligibility: "SO", homeState: "MI", hometown: "Macomb", jerseyNumber: 46,
      hitForAvg: 14, power: 10, speed: 38, arm: 66, fielding: 42, errorResistance: 44, velocity: 68, control: 64, stamina: 64, stuff: 66,
      clutch: 56, vsLHP: 54, grit: 58, stealing: 10, running: 34, throwing: 64, recovery: 56, wRISP: 54, vsLefty: 58, poise: 58, heater: 66, agile: 42,
      abilities: ["Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 5, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Dylan", lastName: "Campbell", position: "C", eligibility: "JR", homeState: "MI", hometown: "Rochester Hills", jerseyNumber: 14,
      hitForAvg: 58, power: 50, speed: 38, arm: 68, fielding: 66, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 16, running: 36, throwing: 70, recovery: 52, wRISP: 58, vsLefty: 54, poise: 60, heater: 0, agile: 42,
      abilities: ["Iron Glove"], potential: "B", catcherAbility: 66,
      ...noPitches },
    { firstName: "Bryce", lastName: "Kelley", position: "C", eligibility: "SO", homeState: "MI", hometown: "Traverse City", jerseyNumber: 18,
      hitForAvg: 48, power: 42, speed: 36, arm: 62, fielding: 58, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 14, running: 34, throwing: 64, recovery: 44, wRISP: 48, vsLefty: 44, poise: 48, heater: 0, agile: 38,
      abilities: [], potential: "B", catcherAbility: 58,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Ryan", lastName: "McKay", position: "2B", eligibility: "JR", homeState: "MI", hometown: "Ann Arbor", jerseyNumber: 2,
      hitForAvg: 76, power: 62, speed: 66, arm: 68, fielding: 76, errorResistance: 74, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 74, vsLHP: 70, grit: 76, stealing: 50, running: 64, throwing: 70, recovery: 60, wRISP: 72, vsLefty: 68, poise: 74, heater: 0, agile: 70,
      abilities: ["Contact Machine", "Iron Glove", "Table Setter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Brendan", lastName: "Walsh", position: "1B", eligibility: "JR", homeState: "IL", hometown: "Naperville", jerseyNumber: 8,
      hitForAvg: 64, power: 62, speed: 42, arm: 60, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 14, running: 40, throwing: 62, recovery: 54, wRISP: 62, vsLefty: 58, poise: 64, heater: 0, agile: 44,
      abilities: ["Power Surge"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Josh", lastName: "Terracina", position: "3B", eligibility: "SR", homeState: "MI", hometown: "Sterling Heights", jerseyNumber: 5,
      hitForAvg: 62, power: 56, speed: 50, arm: 66, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 26, running: 48, throwing: 68, recovery: 52, wRISP: 60, vsLefty: 56, poise: 62, heater: 0, agile: 52,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Aiden", lastName: "Marsh", position: "SS", eligibility: "JR", homeState: "OH", hometown: "Dublin", jerseyNumber: 6,
      hitForAvg: 60, power: 48, speed: 64, arm: 70, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 44, running: 62, throwing: 72, recovery: 50, wRISP: 56, vsLefty: 52, poise: 58, heater: 0, agile: 66,
      abilities: ["Speed Demon"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Cole", lastName: "Van Ameyde", position: "SS", eligibility: "FR", homeState: "MI", hometown: "Grand Haven", jerseyNumber: 24,
      hitForAvg: 44, power: 34, speed: 58, arm: 56, fielding: 52, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 40, grit: 44, stealing: 36, running: 56, throwing: 58, recovery: 38, wRISP: 40, vsLefty: 38, poise: 42, heater: 0, agile: 60,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Drew", lastName: "Orenchuk", position: "3B", eligibility: "SO", homeState: "MI", hometown: "Canton", jerseyNumber: 16,
      hitForAvg: 52, power: 48, speed: 48, arm: 62, fielding: 58, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 22, running: 46, throwing: 64, recovery: 44, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 50,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (5)
    { firstName: "Jack", lastName: "Crighton", position: "OF", eligibility: "SR", homeState: "MI", hometown: "Brighton", jerseyNumber: 1,
      hitForAvg: 66, power: 60, speed: 64, arm: 68, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 44, running: 62, throwing: 70, recovery: 54, wRISP: 64, vsLefty: 60, poise: 66, heater: 0, agile: 66,
      abilities: ["Cannon Arm"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Brady", lastName: "Collins", position: "OF", eligibility: "JR", homeState: "MI", hometown: "Novi", jerseyNumber: 7,
      hitForAvg: 60, power: 52, speed: 62, arm: 66, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 42, running: 60, throwing: 68, recovery: 50, wRISP: 56, vsLefty: 52, poise: 58, heater: 0, agile: 64,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Gavin", lastName: "Redmond", position: "OF", eligibility: "SO", homeState: "MI", hometown: "East Lansing", jerseyNumber: 9,
      hitForAvg: 54, power: 46, speed: 60, arm: 64, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 40, running: 58, throwing: 66, recovery: 46, wRISP: 50, vsLefty: 46, poise: 52, heater: 0, agile: 62,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Luke", lastName: "Ritter", position: "OF", eligibility: "JR", homeState: "IN", hometown: "Carmel", jerseyNumber: 4,
      hitForAvg: 62, power: 56, speed: 58, arm: 66, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 38, running: 56, throwing: 68, recovery: 52, wRISP: 60, vsLefty: 56, poise: 62, heater: 0, agile: 60,
      abilities: ["Clutch Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Mason", lastName: "Kraft", position: "DH", eligibility: "SR", homeState: "MI", hometown: "Okemos", jerseyNumber: 20,
      hitForAvg: 62, power: 58, speed: 40, arm: 52, fielding: 44, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 14, running: 38, throwing: 54, recovery: 50, wRISP: 62, vsLefty: 58, poise: 62, heater: 0, agile: 42,
      abilities: ["Clutch Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Tyler", lastName: "Bowen", position: "OF", eligibility: "SO", homeState: "MI", hometown: "Shelby Township", jerseyNumber: 28,
      hitForAvg: 50, power: 44, speed: 58, arm: 60, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 44, grit: 50, stealing: 36, running: 56, throwing: 62, recovery: 42, wRISP: 46, vsLefty: 42, poise: 48, heater: 0, agile: 60,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Nolan", lastName: "Fischer", position: "DH", eligibility: "JR", homeState: "MI", hometown: "Holland", jerseyNumber: 15,
      hitForAvg: 58, power: 54, speed: 40, arm: 52, fielding: 44, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 14, running: 38, throwing: 54, recovery: 48, wRISP: 56, vsLefty: 52, poise: 56, heater: 0, agile: 42,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
  ],
};
