import { RealPlayer } from "./realRosters";

function pitchMix(primary: number, secondary: number[]): { pitchFB: number; pitch2S: number; pitchSL: number; pitchCB: number; pitchCH: number; pitchCT: number; pitchSNK: number; pitchSPL: number } {
  return { pitchFB: primary, pitch2S: secondary[0] || 0, pitchSL: secondary[1] || 0, pitchCB: secondary[2] || 0, pitchCH: secondary[3] || 0, pitchCT: secondary[4] || 0, pitchSNK: secondary[5] || 0, pitchSPL: secondary[6] || 0 };
}

const noPitches = { pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0 };

export const BIG_TEN_BATCH2_ROSTERS: Record<string, RealPlayer[]> = {
  "Minnesota": [
    // PITCHERS (12)
    { firstName: "Cole", lastName: "Selvig", position: "P", eligibility: "JR", homeState: "MN", hometown: "Wayzata", jerseyNumber: 17,
      hitForAvg: 20, power: 16, speed: 40, arm: 82, fielding: 52, errorResistance: 54, velocity: 86, control: 78, stamina: 80, stuff: 84,
      clutch: 76, vsLHP: 72, grit: 78, stealing: 10, running: 36, throwing: 80, recovery: 72, wRISP: 74, vsLefty: 74, poise: 78, heater: 86, agile: 46,
      abilities: ["Ace", "Strong Starter", "Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 7, 6, 5, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Hemmesch", position: "P", eligibility: "JR", homeState: "MN", hometown: "Cold Spring", jerseyNumber: 31,
      hitForAvg: 18, power: 14, speed: 40, arm: 76, fielding: 48, errorResistance: 50, velocity: 78, control: 74, stamina: 76, stuff: 76,
      clutch: 68, vsLHP: 64, grit: 72, stealing: 10, running: 36, throwing: 74, recovery: 66, wRISP: 66, vsLefty: 68, poise: 72, heater: 78, agile: 44,
      abilities: ["Strong Starter", "Workhorse"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 5, 0, 0, 0]) },
    { firstName: "Will", lastName: "Whelan", position: "P", eligibility: "JR", homeState: "MN", hometown: "Minnetonka", jerseyNumber: 22,
      hitForAvg: 18, power: 14, speed: 42, arm: 76, fielding: 48, errorResistance: 50, velocity: 80, control: 72, stamina: 74, stuff: 76,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 12, running: 38, throwing: 74, recovery: 66, wRISP: 68, vsLefty: 68, poise: 72, heater: 80, agile: 46,
      abilities: ["Strong Starter", "Filthy Breaking Ball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 7, 5, 5, 0, 0, 0]) },
    { firstName: "Brandon", lastName: "Jaenke", position: "P", eligibility: "JR", homeState: "MN", hometown: "Shakopee", jerseyNumber: 38,
      hitForAvg: 18, power: 14, speed: 42, arm: 78, fielding: 48, errorResistance: 50, velocity: 82, control: 72, stamina: 58, stuff: 78,
      clutch: 74, vsLHP: 68, grit: 76, stealing: 10, running: 36, throwing: 76, recovery: 70, wRISP: 72, vsLefty: 70, poise: 76, heater: 82, agile: 46,
      abilities: ["Fireman", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 5, 4, 0, 0]) },
    { firstName: "Marcus", lastName: "Kruzan", position: "P", eligibility: "JR", homeState: "MN", hometown: "Woodbury", jerseyNumber: 28,
      hitForAvg: 16, power: 12, speed: 40, arm: 72, fielding: 46, errorResistance: 48, velocity: 76, control: 70, stamina: 72, stuff: 74,
      clutch: 64, vsLHP: 62, grit: 66, stealing: 10, running: 36, throwing: 70, recovery: 64, wRISP: 62, vsLefty: 64, poise: 66, heater: 76, agile: 44,
      abilities: ["Workhorse"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Adam", lastName: "Urban", position: "P", eligibility: "SO", homeState: "MN", hometown: "Lakeville", jerseyNumber: 42,
      hitForAvg: 16, power: 12, speed: 42, arm: 70, fielding: 44, errorResistance: 46, velocity: 74, control: 66, stamina: 66, stuff: 70,
      clutch: 58, vsLHP: 56, grit: 60, stealing: 12, running: 38, throwing: 68, recovery: 58, wRISP: 56, vsLefty: 58, poise: 60, heater: 74, agile: 46,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Isaac", lastName: "Morton", position: "P", eligibility: "JR", homeState: "IA", hometown: "Cedar Rapids", jerseyNumber: 40,
      hitForAvg: 18, power: 14, speed: 40, arm: 72, fielding: 46, errorResistance: 48, velocity: 76, control: 70, stamina: 70, stuff: 72,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 10, running: 36, throwing: 70, recovery: 64, wRISP: 62, vsLefty: 62, poise: 66, heater: 76, agile: 44,
      abilities: ["Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 4, 0, 0, 0]) },
    { firstName: "Ben", lastName: "Gregory", position: "P", eligibility: "JR", homeState: "WI", hometown: "Madison", jerseyNumber: 46,
      hitForAvg: 16, power: 12, speed: 40, arm: 70, fielding: 44, errorResistance: 46, velocity: 74, control: 68, stamina: 68, stuff: 72,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 10, running: 36, throwing: 68, recovery: 62, wRISP: 60, vsLefty: 60, poise: 64, heater: 74, agile: 44,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 5, 0, 0, 0]) },
    { firstName: "Ethan", lastName: "Felling", position: "P", eligibility: "FR", homeState: "MN", hometown: "St. Cloud", jerseyNumber: 36,
      hitForAvg: 14, power: 10, speed: 42, arm: 66, fielding: 42, errorResistance: 44, velocity: 72, control: 60, stamina: 58, stuff: 68,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 12, running: 40, throwing: 64, recovery: 50, wRISP: 48, vsLefty: 50, poise: 50, heater: 72, agile: 46,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 4, 0, 0, 0]) },
    { firstName: "Eli", lastName: "Kokenge", position: "P", eligibility: "FR", homeState: "MN", hometown: "Prior Lake", jerseyNumber: 48,
      hitForAvg: 14, power: 10, speed: 40, arm: 64, fielding: 40, errorResistance: 42, velocity: 70, control: 58, stamina: 56, stuff: 66,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 12, running: 38, throwing: 62, recovery: 48, wRISP: 46, vsLefty: 48, poise: 48, heater: 70, agile: 44,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 3, 0, 0, 0]) },
    { firstName: "Zach", lastName: "Trettin", position: "P", eligibility: "FR", homeState: "MN", hometown: "Rosemount", jerseyNumber: 50,
      hitForAvg: 14, power: 10, speed: 40, arm: 64, fielding: 40, errorResistance: 42, velocity: 68, control: 56, stamina: 54, stuff: 64,
      clutch: 46, vsLHP: 44, grit: 48, stealing: 12, running: 38, throwing: 62, recovery: 46, wRISP: 44, vsLefty: 46, poise: 46, heater: 68, agile: 44,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    { firstName: "Tristan", lastName: "Moore", position: "P", eligibility: "FR", homeState: "MN", hometown: "Eagan", jerseyNumber: 44,
      hitForAvg: 14, power: 10, speed: 42, arm: 66, fielding: 42, errorResistance: 44, velocity: 70, control: 58, stamina: 56, stuff: 66,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 12, running: 40, throwing: 64, recovery: 48, wRISP: 46, vsLefty: 48, poise: 48, heater: 70, agile: 46,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 4, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Weber", lastName: "Neels", position: "C", eligibility: "SR", homeState: "MN", hometown: "Maple Grove", jerseyNumber: 6,
      hitForAvg: 74, power: 72, speed: 42, arm: 76, fielding: 74, errorResistance: 72, velocity: 0, control: 0, stamina: 38, stuff: 0,
      clutch: 76, vsLHP: 72, grit: 78, stealing: 18, running: 40, throwing: 78, recovery: 60, wRISP: 76, vsLefty: 70, poise: 76, heater: 0, agile: 46,
      abilities: ["Iron Glove", "Power Surge", "Cannon Arm"], potential: "A-", catcherAbility: 70,
      ...noPitches },
    { firstName: "Tyler", lastName: "Albrecht", position: "C", eligibility: "SO", homeState: "MN", hometown: "Plymouth", jerseyNumber: 18,
      hitForAvg: 50, power: 42, speed: 38, arm: 64, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 14, running: 36, throwing: 66, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 40,
      abilities: [], potential: "B", catcherAbility: 58,
      ...noPitches },
    // INFIELDERS (5)
    { firstName: "Charlie", lastName: "Sutherland", position: "SS", eligibility: "JR", homeState: "MN", hometown: "Eden Prairie", jerseyNumber: 2,
      hitForAvg: 68, power: 52, speed: 64, arm: 72, fielding: 74, errorResistance: 72, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 44, running: 62, throwing: 74, recovery: 54, wRISP: 64, vsLefty: 60, poise: 66, heater: 0, agile: 68,
      abilities: ["Iron Glove", "Table Setter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Sam", lastName: "Marek", position: "2B", eligibility: "JR", homeState: "IL", hometown: "Naperville", jerseyNumber: 10,
      hitForAvg: 66, power: 50, speed: 58, arm: 64, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 38, running: 56, throwing: 66, recovery: 54, wRISP: 62, vsLefty: 58, poise: 64, heater: 0, agile: 60,
      abilities: ["Table Setter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Luke", lastName: "Ryerse", position: "1B", eligibility: "JR", homeState: "IN", hometown: "Carmel", jerseyNumber: 24,
      hitForAvg: 64, power: 62, speed: 42, arm: 60, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 14, running: 40, throwing: 62, recovery: 52, wRISP: 62, vsLefty: 56, poise: 62, heater: 0, agile: 44,
      abilities: ["Power Surge"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Jake", lastName: "Doskow", position: "3B", eligibility: "JR", homeState: "MN", hometown: "Burnsville", jerseyNumber: 5,
      hitForAvg: 62, power: 56, speed: 48, arm: 68, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 20, running: 46, throwing: 70, recovery: 52, wRISP: 58, vsLefty: 54, poise: 60, heater: 0, agile: 50,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Nathan", lastName: "O'Donnell", position: "SS", eligibility: "FR", homeState: "MN", hometown: "Edina", jerseyNumber: 14,
      hitForAvg: 42, power: 34, speed: 56, arm: 58, fielding: 52, errorResistance: 48, velocity: 0, control: 0, stamina: 28, stuff: 0,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 34, running: 54, throwing: 60, recovery: 38, wRISP: 38, vsLefty: 36, poise: 40, heater: 0, agile: 58,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Easton", lastName: "Richter", position: "OF", eligibility: "JR", homeState: "MN", hometown: "Owatonna", jerseyNumber: 7,
      hitForAvg: 70, power: 68, speed: 60, arm: 68, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 40, running: 58, throwing: 70, recovery: 56, wRISP: 68, vsLefty: 64, poise: 70, heater: 0, agile: 62,
      abilities: ["Power Surge", "Clutch Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jack", lastName: "Spanier", position: "OF", eligibility: "JR", homeState: "MN", hometown: "Stillwater", jerseyNumber: 9,
      hitForAvg: 64, power: 54, speed: 62, arm: 66, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 42, running: 60, throwing: 68, recovery: 52, wRISP: 60, vsLefty: 56, poise: 62, heater: 0, agile: 64,
      abilities: ["Speed Demon"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "Dardis", position: "OF", eligibility: "JR", homeState: "MN", hometown: "Bloomington", jerseyNumber: 1,
      hitForAvg: 66, power: 58, speed: 64, arm: 68, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 44, running: 62, throwing: 70, recovery: 54, wRISP: 62, vsLefty: 58, poise: 64, heater: 0, agile: 66,
      abilities: ["Cannon Arm"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Cade", lastName: "Anderson", position: "OF", eligibility: "SO", homeState: "MN", hometown: "Duluth", jerseyNumber: 11,
      hitForAvg: 56, power: 46, speed: 62, arm: 64, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 42, running: 60, throwing: 66, recovery: 48, wRISP: 52, vsLefty: 48, poise: 54, heater: 0, agile: 64,
      abilities: [], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Drew", lastName: "Hilliard", position: "OF", eligibility: "JR", homeState: "WI", hometown: "Waukesha", jerseyNumber: 20,
      hitForAvg: 62, power: 56, speed: 56, arm: 62, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 36, running: 54, throwing: 64, recovery: 50, wRISP: 58, vsLefty: 54, poise: 60, heater: 0, agile: 58,
      abilities: ["Contact Machine"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Brady", lastName: "Wilson", position: "OF", eligibility: "SO", homeState: "MN", hometown: "Mankato", jerseyNumber: 26,
      hitForAvg: 54, power: 44, speed: 60, arm: 62, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 40, running: 58, throwing: 64, recovery: 46, wRISP: 50, vsLefty: 46, poise: 52, heater: 0, agile: 62,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Nebraska": [
    // PITCHERS (10)
    { firstName: "Ty", lastName: "Horn", position: "P", eligibility: "JR", homeState: "NE", hometown: "Omaha", jerseyNumber: 17,
      hitForAvg: 20, power: 16, speed: 40, arm: 82, fielding: 52, errorResistance: 54, velocity: 84, control: 78, stamina: 80, stuff: 82,
      clutch: 76, vsLHP: 72, grit: 78, stealing: 10, running: 36, throwing: 80, recovery: 72, wRISP: 74, vsLefty: 74, poise: 78, heater: 84, agile: 46,
      abilities: ["Ace", "Strong Starter", "Workhorse"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 7, 6, 5, 0, 0, 0]) },
    { firstName: "Carson", lastName: "Jasa", position: "P", eligibility: "SO", homeState: "NE", hometown: "Elkhorn", jerseyNumber: 31,
      hitForAvg: 18, power: 14, speed: 42, arm: 80, fielding: 48, errorResistance: 50, velocity: 88, control: 68, stamina: 66, stuff: 84,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 12, running: 38, throwing: 78, recovery: 64, wRISP: 68, vsLefty: 68, poise: 70, heater: 88, agile: 48,
      abilities: ["Explosive Fastball", "Fireman"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 7, 4, 4, 0, 0, 0]) },
    { firstName: "Cooper", lastName: "Timmerman", position: "P", eligibility: "JR", homeState: "NE", hometown: "Lincoln", jerseyNumber: 22,
      hitForAvg: 18, power: 14, speed: 40, arm: 74, fielding: 48, errorResistance: 50, velocity: 78, control: 72, stamina: 74, stuff: 74,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 10, running: 36, throwing: 72, recovery: 64, wRISP: 64, vsLefty: 66, poise: 68, heater: 78, agile: 44,
      abilities: ["Strong Starter"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 4, 0, 0, 0]) },
    { firstName: "Kevin", lastName: "Mannell", position: "P", eligibility: "JR", homeState: "MS", hometown: "Brandon", jerseyNumber: 35,
      hitForAvg: 18, power: 14, speed: 40, arm: 76, fielding: 48, errorResistance: 50, velocity: 80, control: 74, stamina: 74, stuff: 78,
      clutch: 68, vsLHP: 64, grit: 72, stealing: 10, running: 36, throwing: 74, recovery: 66, wRISP: 66, vsLefty: 68, poise: 72, heater: 80, agile: 44,
      abilities: ["Filthy Breaking Ball", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 7, 5, 5, 0, 0, 0]) },
    { firstName: "Cooper", lastName: "Katskee", position: "P", eligibility: "JR", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 28,
      hitForAvg: 18, power: 14, speed: 40, arm: 78, fielding: 48, errorResistance: 50, velocity: 82, control: 74, stamina: 76, stuff: 78,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 10, running: 36, throwing: 76, recovery: 68, wRISP: 68, vsLefty: 68, poise: 72, heater: 82, agile: 44,
      abilities: ["Strong Starter", "Workhorse"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 6, 4, 0, 0, 0]) },
    { firstName: "J.D.", lastName: "Hennen", position: "P", eligibility: "JR", homeState: "MN", hometown: "Shakopee", jerseyNumber: 40,
      hitForAvg: 16, power: 12, speed: 40, arm: 72, fielding: 46, errorResistance: 48, velocity: 76, control: 70, stamina: 70, stuff: 72,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 10, running: 36, throwing: 70, recovery: 64, wRISP: 62, vsLefty: 62, poise: 66, heater: 76, agile: 44,
      abilities: ["Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Gavin", lastName: "Blachowicz", position: "P", eligibility: "SO", homeState: "IL", hometown: "Naperville", jerseyNumber: 42,
      hitForAvg: 16, power: 12, speed: 42, arm: 70, fielding: 44, errorResistance: 46, velocity: 74, control: 66, stamina: 66, stuff: 70,
      clutch: 58, vsLHP: 56, grit: 60, stealing: 12, running: 38, throwing: 68, recovery: 58, wRISP: 56, vsLefty: 58, poise: 60, heater: 74, agile: 46,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 4, 0, 0, 0]) },
    { firstName: "Jalen", lastName: "Worthley", position: "P", eligibility: "SR", homeState: "NE", hometown: "Bellevue", jerseyNumber: 38,
      hitForAvg: 20, power: 16, speed: 40, arm: 74, fielding: 50, errorResistance: 52, velocity: 78, control: 74, stamina: 72, stuff: 74,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 10, running: 36, throwing: 72, recovery: 68, wRISP: 70, vsLefty: 70, poise: 74, heater: 78, agile: 44,
      abilities: ["Fireman", "Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 0, 5, 4, 0, 0]) },
    { firstName: "Brady", lastName: "Hansen", position: "P", eligibility: "FR", homeState: "NE", hometown: "Grand Island", jerseyNumber: 46,
      hitForAvg: 14, power: 10, speed: 40, arm: 64, fielding: 40, errorResistance: 42, velocity: 70, control: 58, stamina: 56, stuff: 66,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 12, running: 38, throwing: 62, recovery: 48, wRISP: 46, vsLefty: 48, poise: 48, heater: 70, agile: 44,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 4, 0, 0, 0]) },
    { firstName: "Chase", lastName: "Henderson", position: "P", eligibility: "FR", homeState: "NE", hometown: "Kearney", jerseyNumber: 48,
      hitForAvg: 14, power: 10, speed: 42, arm: 66, fielding: 42, errorResistance: 44, velocity: 72, control: 60, stamina: 58, stuff: 68,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 12, running: 40, throwing: 64, recovery: 50, wRISP: 48, vsLefty: 50, poise: 50, heater: 72, agile: 46,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 3, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Jeter", lastName: "Worthley", position: "C", eligibility: "FR", homeState: "NE", hometown: "Bellevue", jerseyNumber: 12,
      hitForAvg: 44, power: 38, speed: 38, arm: 62, fielding: 56, errorResistance: 52, velocity: 0, control: 0, stamina: 30, stuff: 0,
      clutch: 44, vsLHP: 40, grit: 46, stealing: 14, running: 36, throwing: 64, recovery: 40, wRISP: 42, vsLefty: 38, poise: 44, heater: 0, agile: 40,
      abilities: [], potential: "A-", catcherAbility: 58,
      ...noPitches },
    { firstName: "Tyler", lastName: "Nolan", position: "C", eligibility: "SO", homeState: "NE", hometown: "Papillion", jerseyNumber: 18,
      hitForAvg: 52, power: 44, speed: 38, arm: 66, fielding: 62, errorResistance: 58, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 14, running: 36, throwing: 68, recovery: 48, wRISP: 52, vsLefty: 48, poise: 54, heater: 0, agile: 42,
      abilities: [], potential: "B+", catcherAbility: 60,
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Dylan", lastName: "Carey", position: "SS", eligibility: "SR", homeState: "NE", hometown: "Omaha", jerseyNumber: 2,
      hitForAvg: 70, power: 54, speed: 64, arm: 74, fielding: 76, errorResistance: 74, velocity: 0, control: 0, stamina: 38, stuff: 0,
      clutch: 72, vsLHP: 68, grit: 76, stealing: 46, running: 62, throwing: 76, recovery: 58, wRISP: 70, vsLefty: 66, poise: 74, heater: 0, agile: 68,
      abilities: ["Iron Glove", "Table Setter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Josh", lastName: "Overbeek", position: "3B", eligibility: "SR", homeState: "NE", hometown: "Lincoln", jerseyNumber: 5,
      hitForAvg: 68, power: 60, speed: 50, arm: 70, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 38, stuff: 0,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 20, running: 48, throwing: 72, recovery: 56, wRISP: 70, vsLefty: 64, poise: 72, heater: 0, agile: 52,
      abilities: ["Clutch Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Case", lastName: "Sanderson", position: "1B", eligibility: "JR", homeState: "NE", hometown: "Hastings", jerseyNumber: 24,
      hitForAvg: 68, power: 64, speed: 44, arm: 62, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 16, running: 42, throwing: 64, recovery: 54, wRISP: 66, vsLefty: 60, poise: 66, heater: 0, agile: 46,
      abilities: ["Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jett", lastName: "Buck", position: "2B", eligibility: "SR", homeState: "CA", hometown: "San Diego", jerseyNumber: 3,
      hitForAvg: 78, power: 76, speed: 58, arm: 68, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 38, stuff: 0,
      clutch: 78, vsLHP: 74, grit: 80, stealing: 38, running: 56, throwing: 70, recovery: 60, wRISP: 78, vsLefty: 72, poise: 78, heater: 0, agile: 60,
      abilities: ["Power Surge", "Clutch Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Nico", lastName: "Newhan", position: "2B", eligibility: "JR", homeState: "CA", hometown: "El Cajon", jerseyNumber: 8,
      hitForAvg: 78, power: 74, speed: 56, arm: 66, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 76, vsLHP: 72, grit: 78, stealing: 36, running: 54, throwing: 68, recovery: 58, wRISP: 76, vsLefty: 70, poise: 76, heater: 0, agile: 58,
      abilities: ["Power Surge", "Contact Machine"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Luke", lastName: "Tillman", position: "SS", eligibility: "FR", homeState: "NE", hometown: "Gretna", jerseyNumber: 14,
      hitForAvg: 42, power: 34, speed: 56, arm: 58, fielding: 52, errorResistance: 48, velocity: 0, control: 0, stamina: 28, stuff: 0,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 34, running: 54, throwing: 60, recovery: 38, wRISP: 38, vsLefty: 36, poise: 40, heater: 0, agile: 58,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Marcus", lastName: "Young", position: "3B", eligibility: "SO", homeState: "NE", hometown: "North Platte", jerseyNumber: 16,
      hitForAvg: 54, power: 46, speed: 50, arm: 64, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 24, running: 48, throwing: 66, recovery: 46, wRISP: 50, vsLefty: 46, poise: 52, heater: 0, agile: 52,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Devin", lastName: "Nunez", position: "OF", eligibility: "SO", homeState: "CA", hometown: "Corona", jerseyNumber: 1,
      hitForAvg: 72, power: 58, speed: 70, arm: 68, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 52, running: 68, throwing: 70, recovery: 56, wRISP: 68, vsLefty: 64, poise: 70, heater: 0, agile: 72,
      abilities: ["Speed Demon", "Contact Machine"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Trey", lastName: "Buettenback", position: "OF", eligibility: "JR", homeState: "NE", hometown: "Columbus", jerseyNumber: 7,
      hitForAvg: 66, power: 60, speed: 60, arm: 70, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 38, running: 58, throwing: 72, recovery: 54, wRISP: 64, vsLefty: 60, poise: 66, heater: 0, agile: 62,
      abilities: ["Cannon Arm"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Cole", lastName: "Kitchens", position: "OF", eligibility: "JR", homeState: "GA", hometown: "Alpharetta", jerseyNumber: 9,
      hitForAvg: 76, power: 68, speed: 46, arm: 60, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 74, vsLHP: 70, grit: 76, stealing: 16, running: 44, throwing: 62, recovery: 56, wRISP: 74, vsLefty: 68, poise: 74, heater: 0, agile: 48,
      abilities: ["Clutch Hitter", "Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Preston", lastName: "Freeman", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Jacksonville", jerseyNumber: 20,
      hitForAvg: 64, power: 56, speed: 64, arm: 68, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 44, running: 62, throwing: 70, recovery: 52, wRISP: 60, vsLefty: 56, poise: 62, heater: 0, agile: 66,
      abilities: ["Speed Demon"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "Metzger", position: "OF", eligibility: "FR", homeState: "NE", hometown: "La Vista", jerseyNumber: 26,
      hitForAvg: 40, power: 34, speed: 58, arm: 56, fielding: 46, errorResistance: 42, velocity: 0, control: 0, stamina: 28, stuff: 0,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 36, running: 56, throwing: 58, recovery: 36, wRISP: 36, vsLefty: 34, poise: 38, heater: 0, agile: 60,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "Mitchell", position: "OF", eligibility: "JR", homeState: "NE", hometown: "Norfolk", jerseyNumber: 30,
      hitForAvg: 60, power: 52, speed: 62, arm: 66, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 40, running: 60, throwing: 68, recovery: 50, wRISP: 56, vsLefty: 52, poise: 58, heater: 0, agile: 64,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "Northwestern": [
    // PITCHERS (10)
    { firstName: "Sam", lastName: "Hliboki", position: "P", eligibility: "SR", homeState: "LA", hometown: "Baton Rouge", jerseyNumber: 31,
      hitForAvg: 22, power: 18, speed: 40, arm: 82, fielding: 52, errorResistance: 54, velocity: 84, control: 78, stamina: 80, stuff: 84,
      clutch: 78, vsLHP: 74, grit: 80, stealing: 10, running: 36, throwing: 80, recovery: 74, wRISP: 76, vsLefty: 76, poise: 80, heater: 84, agile: 46,
      abilities: ["Ace", "Strong Starter", "Filthy Breaking Ball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 8, 6, 5, 0, 0, 0]) },
    { firstName: "Garrett", lastName: "Shearer", position: "P", eligibility: "JR", homeState: "IL", hometown: "Lake Forest", jerseyNumber: 22,
      hitForAvg: 18, power: 14, speed: 40, arm: 78, fielding: 48, errorResistance: 50, velocity: 80, control: 76, stamina: 76, stuff: 78,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 10, running: 36, throwing: 76, recovery: 70, wRISP: 70, vsLefty: 70, poise: 74, heater: 80, agile: 44,
      abilities: ["Strong Starter", "Workhorse"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 6, 5, 0, 0, 0]) },
    { firstName: "Matt", lastName: "Kouser", position: "P", eligibility: "SO", homeState: "IL", hometown: "Glenview", jerseyNumber: 35,
      hitForAvg: 16, power: 12, speed: 42, arm: 72, fielding: 46, errorResistance: 48, velocity: 76, control: 68, stamina: 68, stuff: 72,
      clutch: 60, vsLHP: 58, grit: 62, stealing: 12, running: 38, throwing: 70, recovery: 60, wRISP: 58, vsLefty: 60, poise: 62, heater: 76, agile: 46,
      abilities: ["Explosive Fastball"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Weaver", position: "P", eligibility: "SR", homeState: "IL", hometown: "Barrington", jerseyNumber: 38,
      hitForAvg: 20, power: 16, speed: 40, arm: 76, fielding: 50, errorResistance: 52, velocity: 78, control: 74, stamina: 74, stuff: 76,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 10, running: 36, throwing: 74, recovery: 68, wRISP: 70, vsLefty: 70, poise: 74, heater: 78, agile: 44,
      abilities: ["Guts", "Workhorse"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 0, 6, 4, 0, 0]) },
    { firstName: "Dylan", lastName: "Carmody", position: "P", eligibility: "JR", homeState: "IL", hometown: "Hinsdale", jerseyNumber: 28,
      hitForAvg: 16, power: 12, speed: 40, arm: 72, fielding: 46, errorResistance: 48, velocity: 76, control: 70, stamina: 72, stuff: 72,
      clutch: 64, vsLHP: 62, grit: 66, stealing: 10, running: 36, throwing: 70, recovery: 64, wRISP: 62, vsLefty: 64, poise: 66, heater: 76, agile: 44,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Ben", lastName: "Williams", position: "P", eligibility: "SO", homeState: "IL", hometown: "Naperville", jerseyNumber: 42,
      hitForAvg: 16, power: 12, speed: 42, arm: 68, fielding: 44, errorResistance: 46, velocity: 72, control: 64, stamina: 64, stuff: 68,
      clutch: 56, vsLHP: 54, grit: 58, stealing: 12, running: 38, throwing: 66, recovery: 56, wRISP: 54, vsLefty: 56, poise: 58, heater: 72, agile: 46,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 5, 0, 0, 0]) },
    { firstName: "Kyle", lastName: "Porter", position: "P", eligibility: "JR", homeState: "IL", hometown: "Winnetka", jerseyNumber: 40,
      hitForAvg: 18, power: 14, speed: 40, arm: 72, fielding: 46, errorResistance: 48, velocity: 74, control: 70, stamina: 70, stuff: 72,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 10, running: 36, throwing: 70, recovery: 64, wRISP: 62, vsLefty: 62, poise: 66, heater: 74, agile: 44,
      abilities: ["Fireman"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 0, 4, 0, 0]) },
    { firstName: "Tyler", lastName: "Chadwick", position: "P", eligibility: "SO", homeState: "IL", hometown: "Wilmette", jerseyNumber: 46,
      hitForAvg: 16, power: 12, speed: 42, arm: 66, fielding: 42, errorResistance: 44, velocity: 70, control: 60, stamina: 58, stuff: 66,
      clutch: 52, vsLHP: 50, grit: 54, stealing: 14, running: 40, throwing: 64, recovery: 52, wRISP: 50, vsLefty: 52, poise: 52, heater: 70, agile: 46,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 4, 0, 0, 0]) },
    { firstName: "Owen", lastName: "Mitchell", position: "P", eligibility: "FR", homeState: "IL", hometown: "Park Ridge", jerseyNumber: 48,
      hitForAvg: 14, power: 10, speed: 40, arm: 64, fielding: 40, errorResistance: 42, velocity: 68, control: 58, stamina: 56, stuff: 66,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 12, running: 38, throwing: 62, recovery: 48, wRISP: 46, vsLefty: 48, poise: 48, heater: 68, agile: 44,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 4, 0, 0, 0]) },
    { firstName: "Drew", lastName: "Parker", position: "P", eligibility: "FR", homeState: "IN", hometown: "Carmel", jerseyNumber: 50,
      hitForAvg: 14, power: 10, speed: 42, arm: 66, fielding: 42, errorResistance: 44, velocity: 70, control: 60, stamina: 58, stuff: 68,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 12, running: 40, throwing: 64, recovery: 50, wRISP: 48, vsLefty: 50, poise: 50, heater: 70, agile: 46,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 3, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Matt", lastName: "Johnson", position: "C", eligibility: "JR", homeState: "IL", hometown: "Evanston", jerseyNumber: 12,
      hitForAvg: 60, power: 52, speed: 40, arm: 72, fielding: 70, errorResistance: 68, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 16, running: 38, throwing: 74, recovery: 54, wRISP: 62, vsLefty: 58, poise: 64, heater: 0, agile: 44,
      abilities: ["Iron Glove"], potential: "B", catcherAbility: 66,
      ...noPitches },
    { firstName: "Tyler", lastName: "Bennett", position: "C", eligibility: "SO", homeState: "WI", hometown: "Milwaukee", jerseyNumber: 18,
      hitForAvg: 48, power: 40, speed: 38, arm: 62, fielding: 58, errorResistance: 54, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 14, running: 36, throwing: 64, recovery: 44, wRISP: 48, vsLefty: 44, poise: 48, heater: 0, agile: 40,
      abilities: [], potential: "B", catcherAbility: 58,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Ryan", lastName: "Kucherak", position: "SS", eligibility: "JR", homeState: "IL", hometown: "Libertyville", jerseyNumber: 2,
      hitForAvg: 74, power: 74, speed: 60, arm: 74, fielding: 74, errorResistance: 72, velocity: 0, control: 0, stamina: 38, stuff: 0,
      clutch: 76, vsLHP: 72, grit: 78, stealing: 42, running: 58, throwing: 76, recovery: 58, wRISP: 76, vsLefty: 70, poise: 76, heater: 0, agile: 64,
      abilities: ["Power Surge", "Iron Glove", "Clutch Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Owen", lastName: "McElfatrick", position: "3B", eligibility: "SR", homeState: "IL", hometown: "Deerfield", jerseyNumber: 5,
      hitForAvg: 68, power: 60, speed: 50, arm: 68, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 38, stuff: 0,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 20, running: 48, throwing: 70, recovery: 56, wRISP: 66, vsLefty: 62, poise: 68, heater: 0, agile: 52,
      abilities: ["Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Noah", lastName: "Ruiz", position: "1B", eligibility: "SR", homeState: "CA", hometown: "La Mirada", jerseyNumber: 24,
      hitForAvg: 72, power: 74, speed: 44, arm: 62, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 38, stuff: 0,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 14, running: 42, throwing: 64, recovery: 56, wRISP: 72, vsLefty: 66, poise: 72, heater: 0, agile: 46,
      abilities: ["Power Surge", "Clutch Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Nick", lastName: "Barron", position: "2B", eligibility: "JR", homeState: "IL", hometown: "Elmhurst", jerseyNumber: 10,
      hitForAvg: 64, power: 50, speed: 58, arm: 64, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 38, running: 56, throwing: 66, recovery: 52, wRISP: 60, vsLefty: 56, poise: 62, heater: 0, agile: 60,
      abilities: ["Table Setter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Noah", lastName: "Brocklebank", position: "SS", eligibility: "FR", homeState: "IL", hometown: "Wheaton", jerseyNumber: 14,
      hitForAvg: 44, power: 36, speed: 56, arm: 58, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 28, stuff: 0,
      clutch: 42, vsLHP: 40, grit: 44, stealing: 34, running: 54, throwing: 60, recovery: 40, wRISP: 40, vsLefty: 38, poise: 42, heater: 0, agile: 58,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Drew", lastName: "Harrison", position: "2B", eligibility: "SO", homeState: "IL", hometown: "Highland Park", jerseyNumber: 16,
      hitForAvg: 56, power: 44, speed: 56, arm: 62, fielding: 62, errorResistance: 58, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 36, running: 54, throwing: 64, recovery: 48, wRISP: 52, vsLefty: 48, poise: 54, heater: 0, agile: 58,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (5)
    { firstName: "Jack", lastName: "Lausch", position: "OF", eligibility: "SR", homeState: "IL", hometown: "Lake Forest", jerseyNumber: 1,
      hitForAvg: 76, power: 70, speed: 64, arm: 70, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 38, stuff: 0,
      clutch: 76, vsLHP: 72, grit: 78, stealing: 44, running: 62, throwing: 72, recovery: 60, wRISP: 76, vsLefty: 70, poise: 76, heater: 0, agile: 66,
      abilities: ["Power Surge", "Clutch Hitter", "Cannon Arm"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Jackson", lastName: "Freeman", position: "OF", eligibility: "JR", homeState: "IL", hometown: "Northbrook", jerseyNumber: 7,
      hitForAvg: 70, power: 60, speed: 66, arm: 70, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 48, running: 64, throwing: 72, recovery: 56, wRISP: 66, vsLefty: 62, poise: 68, heater: 0, agile: 68,
      abilities: ["Speed Demon", "Cannon Arm"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Jay", lastName: "Slater", position: "OF", eligibility: "JR", homeState: "IL", hometown: "Buffalo Grove", jerseyNumber: 9,
      hitForAvg: 64, power: 58, speed: 54, arm: 62, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 28, running: 52, throwing: 64, recovery: 52, wRISP: 62, vsLefty: 58, poise: 64, heater: 0, agile: 56,
      abilities: ["Contact Machine"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Jack", lastName: "Sullivan", position: "OF", eligibility: "FR", homeState: "WI", hometown: "Wauwatosa", jerseyNumber: 26,
      hitForAvg: 42, power: 36, speed: 58, arm: 56, fielding: 48, errorResistance: 44, velocity: 0, control: 0, stamina: 28, stuff: 0,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 36, running: 56, throwing: 58, recovery: 38, wRISP: 38, vsLefty: 36, poise: 40, heater: 0, agile: 60,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Tyler", lastName: "Walsh", position: "OF", eligibility: "FR", homeState: "OH", hometown: "Dublin", jerseyNumber: 30,
      hitForAvg: 40, power: 34, speed: 56, arm: 54, fielding: 46, errorResistance: 42, velocity: 0, control: 0, stamina: 28, stuff: 0,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 34, running: 54, throwing: 56, recovery: 36, wRISP: 36, vsLefty: 34, poise: 38, heater: 0, agile: 58,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Luke", lastName: "Patterson", position: "OF", eligibility: "JR", homeState: "IL", hometown: "Oak Park", jerseyNumber: 20,
      hitForAvg: 62, power: 54, speed: 62, arm: 66, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 40, running: 60, throwing: 68, recovery: 52, wRISP: 58, vsLefty: 54, poise: 60, heater: 0, agile: 64,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "Cooper", position: "OF", eligibility: "SO", homeState: "MI", hometown: "Ann Arbor", jerseyNumber: 11,
      hitForAvg: 56, power: 46, speed: 60, arm: 64, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 40, running: 58, throwing: 66, recovery: 48, wRISP: 52, vsLefty: 48, poise: 54, heater: 0, agile: 62,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Ohio State": [
    // PITCHERS (10)
    { firstName: "Pierce", lastName: "Herrenbruck", position: "P", eligibility: "JR", homeState: "IN", hometown: "Fishers", jerseyNumber: 17,
      hitForAvg: 20, power: 16, speed: 40, arm: 82, fielding: 52, errorResistance: 54, velocity: 84, control: 78, stamina: 78, stuff: 82,
      clutch: 76, vsLHP: 72, grit: 78, stealing: 10, running: 36, throwing: 80, recovery: 72, wRISP: 74, vsLefty: 74, poise: 78, heater: 84, agile: 46,
      abilities: ["Ace", "Strong Starter", "Filthy Breaking Ball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 7, 6, 5, 0, 0, 0]) },
    { firstName: "Caden", lastName: "Marcum", position: "P", eligibility: "JR", homeState: "KY", hometown: "Louisville", jerseyNumber: 31,
      hitForAvg: 18, power: 14, speed: 40, arm: 78, fielding: 48, errorResistance: 50, velocity: 82, control: 74, stamina: 74, stuff: 80,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 10, running: 36, throwing: 76, recovery: 68, wRISP: 70, vsLefty: 70, poise: 74, heater: 82, agile: 44,
      abilities: ["Strong Starter", "Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 7, 5, 5, 0, 0, 0]) },
    { firstName: "Gavin", lastName: "Grahovac", position: "P", eligibility: "SR", homeState: "OH", hometown: "Medina", jerseyNumber: 22,
      hitForAvg: 20, power: 16, speed: 40, arm: 76, fielding: 50, errorResistance: 52, velocity: 78, control: 76, stamina: 76, stuff: 76,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 10, running: 36, throwing: 74, recovery: 70, wRISP: 70, vsLefty: 70, poise: 74, heater: 78, agile: 44,
      abilities: ["Workhorse", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 5, 0, 0, 0]) },
    { firstName: "Colin", lastName: "Monasmith", position: "P", eligibility: "JR", homeState: "OH", hometown: "Columbus", jerseyNumber: 38,
      hitForAvg: 18, power: 14, speed: 40, arm: 74, fielding: 48, errorResistance: 50, velocity: 78, control: 72, stamina: 60, stuff: 76,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 10, running: 36, throwing: 72, recovery: 68, wRISP: 68, vsLefty: 68, poise: 72, heater: 78, agile: 44,
      abilities: ["Fireman", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 5, 4, 0, 0]) },
    { firstName: "Tyler", lastName: "Kean", position: "P", eligibility: "SO", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 35,
      hitForAvg: 16, power: 12, speed: 42, arm: 70, fielding: 44, errorResistance: 46, velocity: 74, control: 66, stamina: 66, stuff: 70,
      clutch: 58, vsLHP: 56, grit: 60, stealing: 12, running: 38, throwing: 68, recovery: 58, wRISP: 56, vsLefty: 58, poise: 60, heater: 74, agile: 46,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Josh", lastName: "Romano", position: "P", eligibility: "JR", homeState: "OH", hometown: "Akron", jerseyNumber: 28,
      hitForAvg: 16, power: 12, speed: 40, arm: 72, fielding: 46, errorResistance: 48, velocity: 76, control: 70, stamina: 72, stuff: 72,
      clutch: 64, vsLHP: 62, grit: 66, stealing: 10, running: 36, throwing: 70, recovery: 64, wRISP: 62, vsLefty: 64, poise: 66, heater: 76, agile: 44,
      abilities: ["Workhorse"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Dylan", lastName: "Ray", position: "P", eligibility: "SO", homeState: "OH", hometown: "Dayton", jerseyNumber: 42,
      hitForAvg: 16, power: 12, speed: 42, arm: 68, fielding: 44, errorResistance: 46, velocity: 72, control: 64, stamina: 64, stuff: 68,
      clutch: 56, vsLHP: 54, grit: 58, stealing: 12, running: 38, throwing: 66, recovery: 56, wRISP: 54, vsLefty: 56, poise: 58, heater: 72, agile: 46,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 5, 0, 0, 0]) },
    { firstName: "Will", lastName: "Morrison", position: "P", eligibility: "JR", homeState: "OH", hometown: "Westerville", jerseyNumber: 40,
      hitForAvg: 18, power: 14, speed: 40, arm: 70, fielding: 46, errorResistance: 48, velocity: 74, control: 68, stamina: 68, stuff: 70,
      clutch: 62, vsLHP: 60, grit: 64, stealing: 10, running: 36, throwing: 68, recovery: 62, wRISP: 60, vsLefty: 62, poise: 64, heater: 74, agile: 44,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Jude", lastName: "Fisher", position: "P", eligibility: "FR", homeState: "OH", hometown: "Mason", jerseyNumber: 46,
      hitForAvg: 16, power: 12, speed: 42, arm: 70, fielding: 44, errorResistance: 46, velocity: 78, control: 64, stamina: 62, stuff: 74,
      clutch: 56, vsLHP: 54, grit: 60, stealing: 12, running: 40, throwing: 68, recovery: 54, wRISP: 54, vsLefty: 56, poise: 58, heater: 78, agile: 48,
      abilities: ["Explosive Fastball"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 6, 4, 4, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Stafford", position: "P", eligibility: "FR", homeState: "OH", hometown: "Dublin", jerseyNumber: 48,
      hitForAvg: 14, power: 10, speed: 40, arm: 64, fielding: 40, errorResistance: 42, velocity: 68, control: 58, stamina: 56, stuff: 66,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 12, running: 38, throwing: 62, recovery: 48, wRISP: 46, vsLefty: 48, poise: 48, heater: 68, agile: 44,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Matt", lastName: "Graveline", position: "C", eligibility: "SR", homeState: "OH", hometown: "Cleveland", jerseyNumber: 12,
      hitForAvg: 62, power: 56, speed: 40, arm: 74, fielding: 72, errorResistance: 70, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 16, running: 38, throwing: 76, recovery: 56, wRISP: 64, vsLefty: 60, poise: 66, heater: 0, agile: 44,
      abilities: ["Iron Glove", "Cannon Arm"], potential: "B+", catcherAbility: 68,
      ...noPitches },
    { firstName: "Jack", lastName: "Thompson", position: "C", eligibility: "SO", homeState: "OH", hometown: "Westlake", jerseyNumber: 18,
      hitForAvg: 50, power: 42, speed: 38, arm: 64, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 14, running: 36, throwing: 66, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 40,
      abilities: [], potential: "B", catcherAbility: 58,
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Mason", lastName: "Eckelman", position: "SS", eligibility: "JR", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 2,
      hitForAvg: 74, power: 64, speed: 64, arm: 74, fielding: 76, errorResistance: 74, velocity: 0, control: 0, stamina: 38, stuff: 0,
      clutch: 74, vsLHP: 70, grit: 76, stealing: 46, running: 62, throwing: 76, recovery: 58, wRISP: 74, vsLefty: 68, poise: 74, heater: 0, agile: 68,
      abilities: ["Iron Glove", "Clutch Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Henry", lastName: "Kaczmar", position: "3B", eligibility: "SR", homeState: "MI", hometown: "Grosse Pointe", jerseyNumber: 5,
      hitForAvg: 76, power: 70, speed: 50, arm: 70, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 38, stuff: 0,
      clutch: 76, vsLHP: 72, grit: 78, stealing: 22, running: 48, throwing: 72, recovery: 60, wRISP: 76, vsLefty: 70, poise: 76, heater: 0, agile: 52,
      abilities: ["Power Surge", "Clutch Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Gavin", lastName: "Kuzniewski", position: "2B", eligibility: "JR", homeState: "OH", hometown: "Avon", jerseyNumber: 3,
      hitForAvg: 68, power: 56, speed: 58, arm: 66, fielding: 70, errorResistance: 68, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 38, running: 56, throwing: 68, recovery: 54, wRISP: 64, vsLefty: 60, poise: 66, heater: 0, agile: 60,
      abilities: ["Table Setter", "Iron Glove"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Dane", lastName: "Harvey", position: "1B", eligibility: "JR", homeState: "IN", hometown: "Zionsville", jerseyNumber: 24,
      hitForAvg: 74, power: 70, speed: 44, arm: 62, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 14, running: 42, throwing: 64, recovery: 56, wRISP: 72, vsLefty: 66, poise: 72, heater: 0, agile: 46,
      abilities: ["Power Surge", "Contact Machine"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Tyler", lastName: "Knox", position: "SS", eligibility: "FR", homeState: "OH", hometown: "Centerville", jerseyNumber: 14,
      hitForAvg: 42, power: 34, speed: 56, arm: 58, fielding: 52, errorResistance: 48, velocity: 0, control: 0, stamina: 28, stuff: 0,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 34, running: 54, throwing: 60, recovery: 38, wRISP: 38, vsLefty: 36, poise: 40, heater: 0, agile: 58,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Drew", lastName: "Mitchell", position: "2B", eligibility: "FR", homeState: "OH", hometown: "Toledo", jerseyNumber: 16,
      hitForAvg: 40, power: 32, speed: 52, arm: 54, fielding: 50, errorResistance: 46, velocity: 0, control: 0, stamina: 28, stuff: 0,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 30, running: 50, throwing: 56, recovery: 36, wRISP: 36, vsLefty: 34, poise: 38, heater: 0, agile: 54,
      abilities: [], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Luke", lastName: "Brennan", position: "1B", eligibility: "JR", homeState: "OH", hometown: "Findlay", jerseyNumber: 34,
      hitForAvg: 62, power: 60, speed: 42, arm: 60, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 14, running: 40, throwing: 62, recovery: 50, wRISP: 58, vsLefty: 54, poise: 60, heater: 0, agile: 44,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (4)
    { firstName: "Lee", lastName: "Ellis", position: "OF", eligibility: "JR", homeState: "OH", hometown: "Strongsville", jerseyNumber: 7,
      hitForAvg: 72, power: 66, speed: 68, arm: 72, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 50, running: 66, throwing: 74, recovery: 58, wRISP: 70, vsLefty: 66, poise: 72, heater: 0, agile: 70,
      abilities: ["Speed Demon", "Cannon Arm", "Clutch Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Alonzo", lastName: "Paul Jr", position: "OF", eligibility: "JR", homeState: "SC", hometown: "Columbia", jerseyNumber: 1,
      hitForAvg: 68, power: 64, speed: 66, arm: 70, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 46, running: 64, throwing: 72, recovery: 56, wRISP: 66, vsLefty: 62, poise: 68, heater: 0, agile: 68,
      abilities: ["Power Surge", "Speed Demon"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Drew", lastName: "Novak", position: "OF", eligibility: "JR", homeState: "OH", hometown: "Solon", jerseyNumber: 9,
      hitForAvg: 62, power: 54, speed: 62, arm: 66, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 40, running: 60, throwing: 68, recovery: 52, wRISP: 58, vsLefty: 54, poise: 60, heater: 0, agile: 64,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Drew", lastName: "Palmer", position: "OF", eligibility: "FR", homeState: "OH", hometown: "Powell", jerseyNumber: 26,
      hitForAvg: 42, power: 36, speed: 58, arm: 56, fielding: 48, errorResistance: 44, velocity: 0, control: 0, stamina: 28, stuff: 0,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 36, running: 56, throwing: 58, recovery: 38, wRISP: 38, vsLefty: 36, poise: 40, heater: 0, agile: 60,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "Walsh", position: "OF", eligibility: "SO", homeState: "OH", hometown: "Worthington", jerseyNumber: 11,
      hitForAvg: 58, power: 50, speed: 62, arm: 66, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 42, running: 60, throwing: 68, recovery: 50, wRISP: 54, vsLefty: 50, poise: 56, heater: 0, agile: 64,
      abilities: ["Speed Demon"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Matt", lastName: "Dingledine", position: "OF", eligibility: "JR", homeState: "OH", hometown: "Zanesville", jerseyNumber: 30,
      hitForAvg: 62, power: 56, speed: 58, arm: 64, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 36, running: 56, throwing: 66, recovery: 50, wRISP: 58, vsLefty: 54, poise: 60, heater: 0, agile: 60,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "Oregon": [
    // PITCHERS (10)
    { firstName: "Collin", lastName: "Clarke", position: "P", eligibility: "JR", homeState: "OR", hometown: "Lake Oswego", jerseyNumber: 17,
      hitForAvg: 20, power: 16, speed: 40, arm: 82, fielding: 52, errorResistance: 54, velocity: 84, control: 78, stamina: 80, stuff: 84,
      clutch: 76, vsLHP: 72, grit: 78, stealing: 10, running: 36, throwing: 80, recovery: 72, wRISP: 74, vsLefty: 74, poise: 78, heater: 84, agile: 46,
      abilities: ["Ace", "Strong Starter", "Filthy Breaking Ball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 7, 6, 5, 0, 0, 0]) },
    { firstName: "Will", lastName: "Sanford", position: "P", eligibility: "JR", homeState: "OR", hometown: "Portland", jerseyNumber: 31,
      hitForAvg: 18, power: 14, speed: 40, arm: 76, fielding: 48, errorResistance: 50, velocity: 78, control: 74, stamina: 76, stuff: 76,
      clutch: 68, vsLHP: 64, grit: 72, stealing: 10, running: 36, throwing: 74, recovery: 66, wRISP: 66, vsLefty: 68, poise: 72, heater: 78, agile: 44,
      abilities: ["Strong Starter", "Workhorse"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 0, 6, 5, 0, 0]) },
    { firstName: "Ian", lastName: "Umlandt", position: "P", eligibility: "JR", homeState: "OR", hometown: "Bend", jerseyNumber: 22,
      hitForAvg: 18, power: 14, speed: 42, arm: 76, fielding: 48, errorResistance: 50, velocity: 80, control: 72, stamina: 74, stuff: 76,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 12, running: 38, throwing: 74, recovery: 66, wRISP: 66, vsLefty: 66, poise: 70, heater: 80, agile: 46,
      abilities: ["Strong Starter", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 5, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Jones", position: "P", eligibility: "SO", homeState: "CA", hometown: "Sacramento", jerseyNumber: 35,
      hitForAvg: 16, power: 12, speed: 42, arm: 72, fielding: 46, errorResistance: 48, velocity: 76, control: 66, stamina: 68, stuff: 72,
      clutch: 60, vsLHP: 58, grit: 62, stealing: 12, running: 38, throwing: 70, recovery: 60, wRISP: 58, vsLefty: 60, poise: 62, heater: 76, agile: 46,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Toby", lastName: "Twist", position: "P", eligibility: "JR", homeState: "WA", hometown: "Seattle", jerseyNumber: 38,
      hitForAvg: 18, power: 14, speed: 40, arm: 74, fielding: 48, errorResistance: 50, velocity: 76, control: 72, stamina: 60, stuff: 74,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 10, running: 36, throwing: 72, recovery: 66, wRISP: 66, vsLefty: 66, poise: 70, heater: 76, agile: 44,
      abilities: ["Fireman", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 0, 6, 4, 0, 0]) },
    { firstName: "Sean", lastName: "Murphy", position: "P", eligibility: "SO", homeState: "OR", hometown: "Eugene", jerseyNumber: 42,
      hitForAvg: 16, power: 12, speed: 42, arm: 68, fielding: 44, errorResistance: 46, velocity: 72, control: 64, stamina: 64, stuff: 68,
      clutch: 56, vsLHP: 54, grit: 58, stealing: 12, running: 38, throwing: 66, recovery: 56, wRISP: 54, vsLefty: 56, poise: 58, heater: 72, agile: 46,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 5, 0, 0, 0]) },
    { firstName: "Dylan", lastName: "Greer", position: "P", eligibility: "JR", homeState: "OR", hometown: "Salem", jerseyNumber: 28,
      hitForAvg: 16, power: 12, speed: 40, arm: 72, fielding: 46, errorResistance: 48, velocity: 76, control: 70, stamina: 72, stuff: 72,
      clutch: 64, vsLHP: 62, grit: 66, stealing: 10, running: 36, throwing: 70, recovery: 64, wRISP: 62, vsLefty: 64, poise: 66, heater: 76, agile: 44,
      abilities: ["Workhorse"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Kyle", lastName: "Henderson", position: "P", eligibility: "SO", homeState: "WA", hometown: "Tacoma", jerseyNumber: 40,
      hitForAvg: 16, power: 12, speed: 42, arm: 66, fielding: 42, errorResistance: 44, velocity: 70, control: 62, stamina: 60, stuff: 66,
      clutch: 52, vsLHP: 50, grit: 54, stealing: 12, running: 40, throwing: 64, recovery: 52, wRISP: 50, vsLefty: 52, poise: 52, heater: 70, agile: 46,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 4, 0, 0, 0]) },
    { firstName: "Kai", lastName: "Nakamura", position: "P", eligibility: "FR", homeState: "WA", hometown: "Bellevue", jerseyNumber: 46,
      hitForAvg: 14, power: 10, speed: 42, arm: 66, fielding: 42, errorResistance: 44, velocity: 72, control: 60, stamina: 58, stuff: 68,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 12, running: 40, throwing: 64, recovery: 50, wRISP: 48, vsLefty: 50, poise: 50, heater: 72, agile: 46,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 3, 0, 0, 0]) },
    { firstName: "Tanner", lastName: "Bjornstad", position: "P", eligibility: "FR", homeState: "OR", hometown: "Hillsboro", jerseyNumber: 48,
      hitForAvg: 14, power: 10, speed: 40, arm: 64, fielding: 40, errorResistance: 42, velocity: 70, control: 58, stamina: 56, stuff: 66,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 12, running: 38, throwing: 62, recovery: 48, wRISP: 46, vsLefty: 48, poise: 48, heater: 70, agile: 44,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Burke-Lee", lastName: "Mabeus", position: "C", eligibility: "SO", homeState: "OR", hometown: "Tigard", jerseyNumber: 12,
      hitForAvg: 60, power: 54, speed: 40, arm: 70, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 16, running: 38, throwing: 72, recovery: 54, wRISP: 62, vsLefty: 58, poise: 64, heater: 0, agile: 44,
      abilities: ["Iron Glove"], potential: "A-", catcherAbility: 64,
      ...noPitches },
    { firstName: "Wyatt", lastName: "Christiansen", position: "C", eligibility: "FR", homeState: "WA", hometown: "Olympia", jerseyNumber: 18,
      hitForAvg: 42, power: 36, speed: 36, arm: 60, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 28, stuff: 0,
      clutch: 42, vsLHP: 38, grit: 44, stealing: 12, running: 34, throwing: 62, recovery: 38, wRISP: 40, vsLefty: 36, poise: 40, heater: 0, agile: 38,
      abilities: [], potential: "A-", catcherAbility: 55,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Maddox", lastName: "Molony", position: "SS", eligibility: "JR", homeState: "OR", hometown: "West Linn", jerseyNumber: 2,
      hitForAvg: 76, power: 68, speed: 64, arm: 74, fielding: 74, errorResistance: 72, velocity: 0, control: 0, stamina: 38, stuff: 0,
      clutch: 76, vsLHP: 72, grit: 78, stealing: 44, running: 62, throwing: 76, recovery: 58, wRISP: 76, vsLefty: 70, poise: 76, heater: 0, agile: 68,
      abilities: ["Power Surge", "Iron Glove", "Clutch Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "Cooney", position: "2B", eligibility: "JR", homeState: "CA", hometown: "San Clemente", jerseyNumber: 10,
      hitForAvg: 66, power: 52, speed: 58, arm: 64, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 38, running: 56, throwing: 66, recovery: 52, wRISP: 62, vsLefty: 58, poise: 64, heater: 0, agile: 60,
      abilities: ["Table Setter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Dominic", lastName: "Hellman", position: "1B", eligibility: "JR", homeState: "CA", hometown: "Fresno", jerseyNumber: 24,
      hitForAvg: 68, power: 66, speed: 44, arm: 62, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 14, running: 42, throwing: 64, recovery: 54, wRISP: 66, vsLefty: 62, poise: 68, heater: 0, agile: 46,
      abilities: ["Power Surge", "Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jake", lastName: "Morrison", position: "3B", eligibility: "JR", homeState: "OR", hometown: "Corvallis", jerseyNumber: 5,
      hitForAvg: 62, power: 56, speed: 50, arm: 68, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 22, running: 48, throwing: 70, recovery: 52, wRISP: 60, vsLefty: 56, poise: 62, heater: 0, agile: 52,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Brayden", lastName: "Schultz", position: "SS", eligibility: "FR", homeState: "WA", hometown: "Vancouver", jerseyNumber: 14,
      hitForAvg: 44, power: 36, speed: 58, arm: 58, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 28, stuff: 0,
      clutch: 42, vsLHP: 40, grit: 44, stealing: 36, running: 56, throwing: 60, recovery: 40, wRISP: 40, vsLefty: 38, poise: 42, heater: 0, agile: 60,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Owen", lastName: "Richards", position: "1B", eligibility: "SO", homeState: "OR", hometown: "Medford", jerseyNumber: 34,
      hitForAvg: 56, power: 52, speed: 40, arm: 58, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 12, running: 38, throwing: 60, recovery: 46, wRISP: 52, vsLefty: 48, poise: 54, heater: 0, agile: 42,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (5)
    { firstName: "Drew", lastName: "Smith", position: "OF", eligibility: "JR", homeState: "OR", hometown: "Beaverton", jerseyNumber: 7,
      hitForAvg: 70, power: 66, speed: 64, arm: 70, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 44, running: 62, throwing: 72, recovery: 56, wRISP: 68, vsLefty: 64, poise: 70, heater: 0, agile: 66,
      abilities: ["Power Surge", "Cannon Arm"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Angel", lastName: "Laya", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Miami", jerseyNumber: 1,
      hitForAvg: 66, power: 70, speed: 58, arm: 68, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 34, running: 56, throwing: 70, recovery: 54, wRISP: 66, vsLefty: 60, poise: 66, heater: 0, agile: 60,
      abilities: ["Power Surge"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Elijah", lastName: "Cook", position: "OF", eligibility: "SR", homeState: "CA", hometown: "Oakland", jerseyNumber: 9,
      hitForAvg: 68, power: 58, speed: 66, arm: 68, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 38, stuff: 0,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 46, running: 64, throwing: 70, recovery: 56, wRISP: 66, vsLefty: 62, poise: 68, heater: 0, agile: 68,
      abilities: ["Speed Demon", "Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Tyler", lastName: "Nash", position: "OF", eligibility: "SO", homeState: "WA", hometown: "Spokane", jerseyNumber: 20,
      hitForAvg: 56, power: 48, speed: 62, arm: 64, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 42, running: 60, throwing: 66, recovery: 48, wRISP: 52, vsLefty: 48, poise: 54, heater: 0, agile: 64,
      abilities: ["Speed Demon"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Cole", lastName: "Hendrickson", position: "OF", eligibility: "FR", homeState: "OR", hometown: "Springfield", jerseyNumber: 26,
      hitForAvg: 42, power: 36, speed: 58, arm: 56, fielding: 48, errorResistance: 44, velocity: 0, control: 0, stamina: 28, stuff: 0,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 36, running: 56, throwing: 58, recovery: 38, wRISP: 38, vsLefty: 36, poise: 40, heater: 0, agile: 60,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Drew", lastName: "Kenworthy", position: "OF", eligibility: "JR", homeState: "OR", hometown: "Grants Pass", jerseyNumber: 20,
      hitForAvg: 62, power: 54, speed: 64, arm: 66, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 44, running: 62, throwing: 68, recovery: 52, wRISP: 58, vsLefty: 54, poise: 60, heater: 0, agile: 66,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Bryce", lastName: "Peterson", position: "OF", eligibility: "SO", homeState: "WA", hometown: "Kirkland", jerseyNumber: 30,
      hitForAvg: 56, power: 48, speed: 60, arm: 64, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 40, running: 58, throwing: 66, recovery: 48, wRISP: 52, vsLefty: 48, poise: 54, heater: 0, agile: 62,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Penn State": [
    // PITCHERS (10)
    { firstName: "Colin", lastName: "Fitzgerald", position: "P", eligibility: "SR", homeState: "PA", hometown: "West Chester", jerseyNumber: 31,
      hitForAvg: 22, power: 18, speed: 40, arm: 82, fielding: 52, errorResistance: 54, velocity: 84, control: 80, stamina: 80, stuff: 82,
      clutch: 78, vsLHP: 74, grit: 80, stealing: 10, running: 36, throwing: 80, recovery: 74, wRISP: 76, vsLefty: 76, poise: 80, heater: 84, agile: 46,
      abilities: ["Ace", "Strong Starter", "Workhorse"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 7, 6, 5, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Reynolds", position: "P", eligibility: "JR", homeState: "PA", hometown: "Allentown", jerseyNumber: 22,
      hitForAvg: 18, power: 14, speed: 40, arm: 76, fielding: 48, errorResistance: 50, velocity: 80, control: 72, stamina: 74, stuff: 76,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 10, running: 36, throwing: 74, recovery: 66, wRISP: 66, vsLefty: 68, poise: 70, heater: 80, agile: 44,
      abilities: ["Strong Starter", "Filthy Breaking Ball"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 7, 5, 5, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Walsh", position: "P", eligibility: "SO", homeState: "NJ", hometown: "Cherry Hill", jerseyNumber: 35,
      hitForAvg: 16, power: 12, speed: 42, arm: 72, fielding: 46, errorResistance: 48, velocity: 76, control: 68, stamina: 68, stuff: 72,
      clutch: 60, vsLHP: 58, grit: 62, stealing: 12, running: 38, throwing: 70, recovery: 60, wRISP: 58, vsLefty: 60, poise: 62, heater: 76, agile: 46,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Quinn", position: "P", eligibility: "JR", homeState: "PA", hometown: "Lancaster", jerseyNumber: 38,
      hitForAvg: 18, power: 14, speed: 40, arm: 74, fielding: 48, errorResistance: 50, velocity: 78, control: 72, stamina: 60, stuff: 74,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 10, running: 36, throwing: 72, recovery: 66, wRISP: 66, vsLefty: 66, poise: 70, heater: 78, agile: 44,
      abilities: ["Fireman", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 5, 4, 0, 0]) },
    { firstName: "Matt", lastName: "Bradshaw", position: "P", eligibility: "SO", homeState: "PA", hometown: "Pittsburgh", jerseyNumber: 42,
      hitForAvg: 16, power: 12, speed: 42, arm: 68, fielding: 44, errorResistance: 46, velocity: 72, control: 64, stamina: 64, stuff: 68,
      clutch: 56, vsLHP: 54, grit: 58, stealing: 12, running: 38, throwing: 66, recovery: 56, wRISP: 54, vsLefty: 56, poise: 58, heater: 72, agile: 46,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 5, 0, 0, 0]) },
    { firstName: "Aidan", lastName: "Fobare", position: "P", eligibility: "JR", homeState: "MD", hometown: "Bethesda", jerseyNumber: 28,
      hitForAvg: 16, power: 12, speed: 40, arm: 72, fielding: 46, errorResistance: 48, velocity: 76, control: 70, stamina: 72, stuff: 72,
      clutch: 64, vsLHP: 62, grit: 66, stealing: 10, running: 36, throwing: 70, recovery: 64, wRISP: 62, vsLefty: 64, poise: 66, heater: 76, agile: 44,
      abilities: ["Workhorse"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Drew", lastName: "Hartman", position: "P", eligibility: "JR", homeState: "PA", hometown: "York", jerseyNumber: 40,
      hitForAvg: 18, power: 14, speed: 40, arm: 70, fielding: 46, errorResistance: 48, velocity: 74, control: 68, stamina: 68, stuff: 70,
      clutch: 62, vsLHP: 60, grit: 64, stealing: 10, running: 36, throwing: 68, recovery: 62, wRISP: 60, vsLefty: 62, poise: 64, heater: 74, agile: 44,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Nolan", lastName: "Berger", position: "P", eligibility: "SO", homeState: "PA", hometown: "Doylestown", jerseyNumber: 46,
      hitForAvg: 16, power: 12, speed: 42, arm: 66, fielding: 42, errorResistance: 44, velocity: 70, control: 62, stamina: 60, stuff: 66,
      clutch: 52, vsLHP: 50, grit: 54, stealing: 12, running: 40, throwing: 64, recovery: 52, wRISP: 50, vsLefty: 52, poise: 52, heater: 70, agile: 46,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 4, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Schwartz", position: "P", eligibility: "FR", homeState: "PA", hometown: "Harrisburg", jerseyNumber: 48,
      hitForAvg: 14, power: 10, speed: 42, arm: 66, fielding: 42, errorResistance: 44, velocity: 72, control: 60, stamina: 58, stuff: 68,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 12, running: 40, throwing: 64, recovery: 50, wRISP: 48, vsLefty: 50, poise: 50, heater: 72, agile: 46,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 3, 0, 0, 0]) },
    { firstName: "Dylan", lastName: "Haines", position: "P", eligibility: "FR", homeState: "NJ", hometown: "Toms River", jerseyNumber: 50,
      hitForAvg: 14, power: 10, speed: 40, arm: 64, fielding: 40, errorResistance: 42, velocity: 68, control: 58, stamina: 56, stuff: 64,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 12, running: 38, throwing: 62, recovery: 48, wRISP: 46, vsLefty: 48, poise: 48, heater: 68, agile: 44,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Nate", lastName: "Voss", position: "C", eligibility: "JR", homeState: "PA", hometown: "Reading", jerseyNumber: 12,
      hitForAvg: 58, power: 56, speed: 38, arm: 72, fielding: 70, errorResistance: 68, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 66, stealing: 14, running: 36, throwing: 74, recovery: 54, wRISP: 60, vsLefty: 56, poise: 64, heater: 0, agile: 42,
      abilities: ["Iron Glove", "Cannon Arm"], potential: "B+", catcherAbility: 66,
      ...noPitches },
    { firstName: "Ryan", lastName: "Corcoran", position: "C", eligibility: "FR", homeState: "PA", hometown: "Scranton", jerseyNumber: 18,
      hitForAvg: 42, power: 36, speed: 36, arm: 60, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 28, stuff: 0,
      clutch: 40, vsLHP: 36, grit: 42, stealing: 12, running: 34, throwing: 62, recovery: 38, wRISP: 38, vsLefty: 34, poise: 38, heater: 0, agile: 38,
      abilities: [], potential: "A-", catcherAbility: 55,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Bryce", lastName: "Molinaro", position: "3B", eligibility: "JR", homeState: "PA", hometown: "State College", jerseyNumber: 2,
      hitForAvg: 76, power: 72, speed: 52, arm: 72, fielding: 70, errorResistance: 68, velocity: 0, control: 0, stamina: 38, stuff: 0,
      clutch: 78, vsLHP: 74, grit: 80, stealing: 22, running: 50, throwing: 74, recovery: 60, wRISP: 78, vsLefty: 72, poise: 78, heater: 0, agile: 54,
      abilities: ["Power Surge", "Clutch Hitter", "Contact Machine"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Kevin", lastName: "Karstetter", position: "1B", eligibility: "JR", homeState: "PA", hometown: "State College", jerseyNumber: 24,
      hitForAvg: 64, power: 62, speed: 44, arm: 62, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 14, running: 42, throwing: 64, recovery: 54, wRISP: 62, vsLefty: 58, poise: 64, heater: 0, agile: 46,
      abilities: ["Power Surge"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Jayden", lastName: "Davis", position: "2B", eligibility: "JR", homeState: "TN", hometown: "Nashville", jerseyNumber: 10,
      hitForAvg: 70, power: 54, speed: 60, arm: 66, fielding: 70, errorResistance: 68, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 42, running: 58, throwing: 68, recovery: 56, wRISP: 66, vsLefty: 62, poise: 68, heater: 0, agile: 62,
      abilities: ["Table Setter", "Iron Glove"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Spencer", lastName: "Barnett", position: "SS", eligibility: "JR", homeState: "WV", hometown: "Morgantown", jerseyNumber: 3,
      hitForAvg: 66, power: 52, speed: 62, arm: 70, fielding: 72, errorResistance: 70, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 44, running: 60, throwing: 72, recovery: 54, wRISP: 62, vsLefty: 58, poise: 64, heater: 0, agile: 64,
      abilities: ["Iron Glove", "Speed Demon"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Preston", lastName: "Yaucher", position: "SS", eligibility: "FR", homeState: "PA", hometown: "Mechanicsburg", jerseyNumber: 14,
      hitForAvg: 44, power: 36, speed: 58, arm: 58, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 28, stuff: 0,
      clutch: 42, vsLHP: 40, grit: 44, stealing: 36, running: 56, throwing: 60, recovery: 40, wRISP: 40, vsLefty: 38, poise: 42, heater: 0, agile: 60,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Drew", lastName: "Wilson", position: "2B", eligibility: "SO", homeState: "PA", hometown: "Erie", jerseyNumber: 16,
      hitForAvg: 54, power: 42, speed: 56, arm: 62, fielding: 62, errorResistance: 58, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 36, running: 54, throwing: 64, recovery: 46, wRISP: 50, vsLefty: 46, poise: 52, heater: 0, agile: 58,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (5)
    { firstName: "Jack", lastName: "Porter", position: "OF", eligibility: "JR", homeState: "PA", hometown: "Williamsport", jerseyNumber: 7,
      hitForAvg: 72, power: 66, speed: 60, arm: 68, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 40, running: 58, throwing: 70, recovery: 56, wRISP: 72, vsLefty: 66, poise: 72, heater: 0, agile: 62,
      abilities: ["Power Surge", "Clutch Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jesse", lastName: "Jaconski", position: "OF", eligibility: "JR", homeState: "PA", hometown: "Bethlehem", jerseyNumber: 1,
      hitForAvg: 74, power: 62, speed: 64, arm: 68, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 44, running: 62, throwing: 70, recovery: 56, wRISP: 72, vsLefty: 66, poise: 72, heater: 0, agile: 66,
      abilities: ["Contact Machine", "Clutch Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Michael", lastName: "Anderson", position: "OF", eligibility: "JR", homeState: "AR", hometown: "Little Rock", jerseyNumber: 9,
      hitForAvg: 66, power: 60, speed: 58, arm: 66, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 36, running: 56, throwing: 68, recovery: 52, wRISP: 64, vsLefty: 60, poise: 66, heater: 0, agile: 60,
      abilities: ["Cannon Arm"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Cohl", lastName: "Mercado", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Tampa", jerseyNumber: 20,
      hitForAvg: 64, power: 54, speed: 68, arm: 66, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 36, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 50, running: 66, throwing: 68, recovery: 54, wRISP: 60, vsLefty: 56, poise: 62, heater: 0, agile: 70,
      abilities: ["Speed Demon"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Maddox", lastName: "McDonald", position: "OF", eligibility: "FR", homeState: "PA", hometown: "Media", jerseyNumber: 26,
      hitForAvg: 42, power: 36, speed: 58, arm: 56, fielding: 48, errorResistance: 44, velocity: 0, control: 0, stamina: 28, stuff: 0,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 36, running: 56, throwing: 58, recovery: 38, wRISP: 38, vsLefty: 36, poise: 40, heater: 0, agile: 60,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Luke", lastName: "Bradley", position: "OF", eligibility: "JR", homeState: "PA", hometown: "Easton", jerseyNumber: 11,
      hitForAvg: 62, power: 54, speed: 62, arm: 66, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 40, running: 60, throwing: 68, recovery: 52, wRISP: 58, vsLefty: 54, poise: 60, heater: 0, agile: 64,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Tyler", lastName: "Bennett", position: "OF", eligibility: "SO", homeState: "PA", hometown: "Altoona", jerseyNumber: 30,
      hitForAvg: 56, power: 46, speed: 60, arm: 64, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 34, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 40, running: 58, throwing: 66, recovery: 48, wRISP: 52, vsLefty: 48, poise: 54, heater: 0, agile: 62,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],
};
