import type { RealPlayer } from "./realRosters";
import { pitchMix, noPitches } from "./pitchMixHelpers";

export const BIG_TEN_BATCH3_ROSTERS: Record<string, RealPlayer[]> = {
  "Purdue": [
    // PITCHERS (10)
    { firstName: "Cole", lastName: "Van Assen", position: "P", eligibility: "JR", homeState: "IN", hometown: "Crown Point", jerseyNumber: 19,
      hitForAvg: 20, power: 16, speed: 42, arm: 70, fielding: 41, errorResistance: 52, velocity: 70, control: 62, stamina: 69, stuff: 69,
      clutch: 74, vsLHP: 70, grit: 90, stealing: 10, running: 38, throwing: 78, recovery: 59, wRISP: 59, vsLefty: 60, poise: 62, heater: 72, agile: 46,
      abilities: ["Star of Victory", "Strong Starter", "Guts", "Intimidator", "Heavy Ball", "Winner's Luck", "Pace"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 7, 6, 1, 0, 0, 0]) },
    { firstName: "Zach", lastName: "Erdman", position: "P", eligibility: "JR", homeState: "TX", hometown: "Lubbock", jerseyNumber: 34,
      hitForAvg: 15, power: 12, speed: 34, arm: 49, fielding: 31, errorResistance: 43, velocity: 49, control: 47, stamina: 49, stuff: 47,
      clutch: 59, vsLHP: 56, grit: 61, stealing: 9, running: 31, throwing: 62, recovery: 44, wRISP: 44, vsLefty: 45, poise: 47, heater: 52, agile: 37,
      abilities: ["Strong Starter", "Explosive Fastball"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Jarvis", lastName: "Evans", position: "P", eligibility: "JR", homeState: "SC", hometown: "Columbia", jerseyNumber: 27,
      hitForAvg: 15, power: 12, speed: 33, arm: 46, fielding: 30, errorResistance: 41, velocity: 44, control: 44, stamina: 46, stuff: 44,
      clutch: 56, vsLHP: 53, grit: 58, stealing: 8, running: 29, throwing: 59, recovery: 41, wRISP: 41, vsLefty: 42, poise: 44, heater: 48, agile: 36,
      abilities: ["Strong Starter", "Guts", "True Slider"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 6, 1, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Kramer", position: "P", eligibility: "SR", homeState: "IN", hometown: "Fishers", jerseyNumber: 41,
      hitForAvg: 14, power: 11, speed: 29, arm: 45, fielding: 28, errorResistance: 42, velocity: 45, control: 45, stamina: 39, stuff: 44,
      clutch: 61, vsLHP: 55, grit: 61, stealing: 8, running: 26, throwing: 58, recovery: 43, wRISP: 45, vsLefty: 43, poise: 46, heater: 49, agile: 32,
      abilities: ["Fireman", "Explosive Fastball", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 7, 0, 1, 0, 0, 0]) },
    { firstName: "Barron", lastName: "Sawyer", position: "P", eligibility: "SR", homeState: "IN", hometown: "Westfield", jerseyNumber: 45,
      hitForAvg: 14, power: 13, speed: 32, arm: 51, fielding: 33, errorResistance: 45, velocity: 51, control: 48, stamina: 49, stuff: 49,
      clutch: 59, vsLHP: 55, grit: 61, stealing: 9, running: 29, throwing: 64, recovery: 45, wRISP: 45, vsLefty: 45, poise: 47, heater: 55, agile: 36,
      abilities: ["Explosive Fastball", "Wild Fastball", "vs. Strong Batters", "Inside Pitch"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Westin", lastName: "Boyle", position: "P", eligibility: "JR", homeState: "IN", hometown: "Carmel", jerseyNumber: 38,
      hitForAvg: 9, power: 6, speed: 23, arm: 25, fielding: 17, errorResistance: 28, velocity: 30, control: 24, stamina: 25, stuff: 30,
      clutch: 36, vsLHP: 34, grit: 36, stealing: 6, running: 20, throwing: 39, recovery: 22, wRISP: 21, vsLefty: 22, poise: 22, heater: 27, agile: 25,
      abilities: ["Full Throttle", "Strikeout"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "O'Connell", position: "P", eligibility: "SO", homeState: "IL", hometown: "Naperville", jerseyNumber: 46,
      hitForAvg: 11, power: 8, speed: 28, arm: 35, fielding: 22, errorResistance: 32, velocity: 32, control: 32, stamina: 33, stuff: 32,
      clutch: 39, vsLHP: 38, grit: 41, stealing: 8, running: 25, throwing: 46, recovery: 27, wRISP: 27, vsLefty: 30, poise: 30, heater: 36, agile: 30,
      abilities: ["Hot Head"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Logan", lastName: "Beaman", position: "P", eligibility: "JR", homeState: "IN", hometown: "Lafayette", jerseyNumber: 32,
      hitForAvg: 11, power: 8, speed: 23, arm: 42, fielding: 27, errorResistance: 29, velocity: 40, control: 40, stamina: 40, stuff: 39,
      clutch: 37, vsLHP: 36, grit: 38, stealing: 6, running: 20, throwing: 40, recovery: 37, wRISP: 36, vsLefty: 38, poise: 38, heater: 44, agile: 25,
      abilities: ["Shuuto Spin"], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Josh", lastName: "Willman", position: "P", eligibility: "SO", homeState: "IN", hometown: "Brownsburg", jerseyNumber: 48,
      hitForAvg: 12, power: 9, speed: 32, arm: 36, fielding: 24, errorResistance: 35, velocity: 35, control: 33, stamina: 33, stuff: 33,
      clutch: 41, vsLHP: 40, grit: 43, stealing: 11, running: 29, throwing: 51, recovery: 28, wRISP: 28, vsLefty: 30, poise: 28, heater: 38, agile: 35,
      abilities: ["Flyball Pitcher"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    { firstName: "Kade", lastName: "Hoover", position: "P", eligibility: "FR", homeState: "OH", hometown: "Columbus", jerseyNumber: 50,
      hitForAvg: 10, power: 9, speed: 30, arm: 34, fielding: 21, errorResistance: 33, velocity: 32, control: 32, stamina: 32, stuff: 31,
      clutch: 37, vsLHP: 36, grit: 39, stealing: 9, running: 27, throwing: 47, recovery: 25, wRISP: 24, vsLefty: 27, poise: 25, heater: 36, agile: 33,
      abilities: ["Halting Quickness", "Gyroball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Jackson", lastName: "Bessette", position: "C", eligibility: "JR", homeState: "IL", hometown: "Chicago", jerseyNumber: 12,
      hitForAvg: 60, power: 54, speed: 37, arm: 60, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 55, vsLHP: 51, grit: 56, stealing: 14, running: 30, throwing: 62, recovery: 47, wRISP: 53, vsLefty: 50, poise: 55, heater: 0, agile: 36,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: 56,
      ...noPitches },
    { firstName: "Nolan", lastName: "Wilkerson", position: "C", eligibility: "SO", homeState: "IN", hometown: "Muncie", jerseyNumber: 15,
      hitForAvg: 41, power: 37, speed: 28, arm: 42, fielding: 39, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 35, vsLHP: 33, grit: 37, stealing: 10, running: 23, throwing: 44, recovery: 31, wRISP: 34, vsLefty: 31, poise: 34, heater: 0, agile: 26,
      abilities: ["Chance Maker", "Late Night Hero"], potential: "B", catcherAbility: 39,
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Dylan", lastName: "Drake", position: "SS", eligibility: "JR", homeState: "IN", hometown: "Indianapolis", jerseyNumber: 2,
      hitForAvg: 56, power: 46, speed: 52, arm: 53, fielding: 54, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 45, grit: 49, stealing: 35, running: 46, throwing: 54, recovery: 40, wRISP: 46, vsLefty: 43, poise: 48, heater: 0, agile: 52,
      abilities: ["Defensive Artisan", "Express Baserunning"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Eli", lastName: "Anderson", position: "2B", eligibility: "JR", homeState: "IN", hometown: "Zionsville", jerseyNumber: 6,
      hitForAvg: 61, power: 49, speed: 56, arm: 57, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 49, grit: 54, stealing: 34, running: 49, throwing: 58, recovery: 47, wRISP: 52, vsLefty: 48, poise: 53, heater: 0, agile: 54,
      abilities: ["Chance Maker"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Sam", lastName: "Flores", position: "3B", eligibility: "SO", homeState: "CA", hometown: "San Diego", jerseyNumber: 8,
      hitForAvg: 58, power: 51, speed: 47, arm: 58, fielding: 55, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 47, grit: 51, stealing: 19, running: 41, throwing: 60, recovery: 43, wRISP: 48, vsLefty: 44, poise: 50, heater: 0, agile: 44,
      abilities: ["Good Mood", "vs. Fastballs"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Ross", lastName: "Highfill", position: "1B", eligibility: "JR", homeState: "IN", hometown: "Greenwood", jerseyNumber: 24,
      hitForAvg: 67, power: 66, speed: 42, arm: 56, fielding: 59, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 59, vsLHP: 54, grit: 60, stealing: 12, running: 36, throwing: 59, recovery: 47, wRISP: 56, vsLefty: 53, poise: 59, heater: 0, agile: 41,
      abilities: ["Contact Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Tyler", lastName: "Reeves", position: "SS", eligibility: "FR", homeState: "IN", hometown: "Noblesville", jerseyNumber: 3,
      hitForAvg: 37, power: 31, speed: 45, arm: 39, fielding: 36, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 29, vsLHP: 27, grit: 30, stealing: 25, running: 39, throwing: 41, recovery: 27, wRISP: 28, vsLefty: 25, poise: 28, heater: 0, agile: 42,
      abilities: ["Outside Hitter", "Final Hit", "Home Defense"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Maddux", lastName: "Houghton", position: "1B", eligibility: "FR", homeState: "IN", hometown: "Avon", jerseyNumber: 28,
      hitForAvg: 40, power: 38, speed: 32, arm: 40, fielding: 37, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 31, vsLHP: 28, grit: 33, stealing: 11, running: 26, throwing: 41, recovery: 28, wRISP: 29, vsLefty: 26, poise: 29, heater: 0, agile: 29,
      abilities: ["Storming Home", "Ace Killer"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "Walstad", position: "2B", eligibility: "FR", homeState: "MN", hometown: "Edina", jerseyNumber: 14,
      hitForAvg: 34, power: 29, speed: 40, arm: 35, fielding: 33, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 25, vsLHP: 24, grit: 27, stealing: 22, running: 35, throwing: 36, recovery: 24, wRISP: 24, vsLefty: 22, poise: 25, heater: 0, agile: 37,
      abilities: ["High Ball Hitter", "Defensive Artisan"], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Aaron", lastName: "Manias", position: "OF", eligibility: "SR", homeState: "TX", hometown: "Big Spring", jerseyNumber: 7,
      hitForAvg: 68, power: 65, speed: 49, arm: 53, fielding: 50, errorResistance: 49, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 61, vsLHP: 58, grit: 62, stealing: 26, running: 43, throwing: 55, recovery: 47, wRISP: 61, vsLefty: 56, poise: 59, heater: 0, agile: 47,
      abilities: ["Power Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "CJ", lastName: "Richmond", position: "OF", eligibility: "JR", homeState: "IN", hometown: "Terre Haute", jerseyNumber: 22,
      hitForAvg: 53, power: 47, speed: 52, arm: 49, fielding: 46, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 45, vsLHP: 42, grit: 46, stealing: 33, running: 46, throwing: 51, recovery: 37, wRISP: 43, vsLefty: 40, poise: 45, heater: 0, agile: 49,
      abilities: ["Express Baserunning"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Camden", lastName: "Gasser", position: "OF", eligibility: "SO", homeState: "IN", hometown: "Brownsburg", jerseyNumber: 9,
      hitForAvg: 54, power: 47, speed: 54, arm: 52, fielding: 49, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 45, vsLHP: 42, grit: 47, stealing: 32, running: 49, throwing: 54, recovery: 39, wRISP: 44, vsLefty: 40, poise: 45, heater: 0, agile: 52,
      abilities: ["High-Speed Laser", "Contact Hitter", "Push"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jake", lastName: "Jarvis", position: "OF", eligibility: "JR", homeState: "IN", hometown: "Evansville", jerseyNumber: 20,
      hitForAvg: 55, power: 49, speed: 54, arm: 52, fielding: 48, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 44, grit: 48, stealing: 34, running: 48, throwing: 53, recovery: 39, wRISP: 45, vsLefty: 42, poise: 47, heater: 0, agile: 52,
      abilities: ["Emergency Strength", "Contact Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Brennan", lastName: "Hein", position: "OF", eligibility: "FR", homeState: "IN", hometown: "Lafayette", jerseyNumber: 26,
      hitForAvg: 40, power: 36, speed: 48, arm: 43, fielding: 37, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 30, grit: 33, stealing: 26, running: 43, throwing: 44, recovery: 30, wRISP: 30, vsLefty: 29, poise: 30, heater: 0, agile: 46,
      abilities: ["Heavy Tank", "vs. Breaking Pitches", "Bad Mood"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Brady", lastName: "Moore", position: "OF", eligibility: "SO", homeState: "IN", hometown: "Bloomington", jerseyNumber: 30,
      hitForAvg: 57, power: 49, speed: 57, arm: 55, fielding: 52, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 45, grit: 50, stealing: 34, running: 52, throwing: 57, recovery: 41, wRISP: 46, vsLefty: 42, poise: 48, heater: 0, agile: 55,
      abilities: ["Laser Beam", "Defensive Artisan"], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "Rutgers": [
    // PITCHERS (10)
    { firstName: "Joe", lastName: "Mazza", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Toms River", jerseyNumber: 17,
      hitForAvg: 21, power: 17, speed: 41, arm: 70, fielding: 43, errorResistance: 54, velocity: 71, control: 65, stamina: 69, stuff: 69,
      clutch: 75, vsLHP: 71, grit: 77, stealing: 11, running: 37, throwing: 90, recovery: 60, wRISP: 60, vsLefty: 61, poise: 63, heater: 72, agile: 45,
      abilities: ["Strong Starter", "Sharpness", "vs. Strong Batters", "Kageura", "Strong Finisher"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 6, 1, 0, 0, 0]) },
    { firstName: "Zack", lastName: "Konstantinovsky", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Marlboro", jerseyNumber: 22,
      hitForAvg: 15, power: 11, speed: 31, arm: 48, fielding: 30, errorResistance: 41, velocity: 45, control: 46, stamina: 48, stuff: 45,
      clutch: 58, vsLHP: 55, grit: 60, stealing: 8, running: 28, throwing: 61, recovery: 42, wRISP: 42, vsLefty: 44, poise: 45, heater: 49, agile: 34,
      abilities: ["Strong Starter", "Guts", "Strong Finisher"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Dallin", lastName: "Harrison", position: "P", eligibility: "JR", homeState: "CA", hometown: "San Diego", jerseyNumber: 35,
      hitForAvg: 16, power: 13, speed: 36, arm: 51, fielding: 33, errorResistance: 44, velocity: 49, control: 49, stamina: 51, stuff: 48,
      clutch: 60, vsLHP: 57, grit: 61, stealing: 9, running: 32, throwing: 64, recovery: 45, wRISP: 45, vsLefty: 46, poise: 47, heater: 53, agile: 39,
      abilities: ["Guts", "Big Boy Speed"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Vincent", lastName: "Borghese", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Cherry Hill", jerseyNumber: 40,
      hitForAvg: 14, power: 10, speed: 29, arm: 43, fielding: 27, errorResistance: 40, velocity: 40, control: 42, stamina: 42, stuff: 41,
      clutch: 55, vsLHP: 52, grit: 57, stealing: 7, running: 26, throwing: 57, recovery: 38, wRISP: 39, vsLefty: 39, poise: 41, heater: 45, agile: 32,
      abilities: ["Explosive Fastball", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Jordan", lastName: "Savinon", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Newark", jerseyNumber: 29,
      hitForAvg: 12, power: 10, speed: 32, arm: 43, fielding: 27, errorResistance: 38, velocity: 41, control: 41, stamina: 43, stuff: 40,
      clutch: 51, vsLHP: 50, grit: 53, stealing: 8, running: 29, throwing: 56, recovery: 38, wRISP: 37, vsLefty: 39, poise: 39, heater: 45, agile: 35,
      abilities: ["Fireman", "Natural Shuuto"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Marcus", lastName: "Holden", position: "P", eligibility: "SO", homeState: "NJ", hometown: "Woodbridge", jerseyNumber: 46,
      hitForAvg: 12, power: 8, speed: 29, arm: 33, fielding: 21, errorResistance: 34, velocity: 31, control: 31, stamina: 33, stuff: 31,
      clutch: 41, vsLHP: 39, grit: 42, stealing: 8, running: 26, throwing: 48, recovery: 27, wRISP: 27, vsLefty: 29, poise: 29, heater: 35, agile: 31,
      abilities: ["Pace", "Tunneling"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Jake", lastName: "DeLeo", position: "P", eligibility: "SO", homeState: "NJ", hometown: "Princeton", jerseyNumber: 48,
      hitForAvg: 9, power: 8, speed: 27, arm: 26, fielding: 18, errorResistance: 29, velocity: 30, control: 26, stamina: 26, stuff: 30,
      clutch: 35, vsLHP: 33, grit: 35, stealing: 9, running: 24, throwing: 42, recovery: 21, wRISP: 21, vsLefty: 22, poise: 22, heater: 28, agile: 29,
      abilities: ["Strikeout", "Delayed Arm"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    { firstName: "Cole", lastName: "Stetzar", position: "P", eligibility: "SO", homeState: "NJ", hometown: "Haddonfield", jerseyNumber: 33,
      hitForAvg: 10, power: 8, speed: 25, arm: 29, fielding: 19, errorResistance: 30, velocity: 30, control: 28, stamina: 28, stuff: 30,
      clutch: 37, vsLHP: 35, grit: 38, stealing: 6, running: 23, throwing: 43, recovery: 23, wRISP: 23, vsLefty: 25, poise: 24, heater: 30, agile: 28,
      abilities: ["Miracle Sharpness"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    { firstName: "Matt", lastName: "Reardon", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Edison", jerseyNumber: 36,
      hitForAvg: 13, power: 9, speed: 26, arm: 33, fielding: 21, errorResistance: 33, velocity: 30, control: 31, stamina: 31, stuff: 30,
      clutch: 43, vsLHP: 41, grit: 44, stealing: 7, running: 23, throwing: 46, recovery: 29, wRISP: 28, vsLefty: 30, poise: 30, heater: 34, agile: 28,
      abilities: ["Wild Fastball"], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Hogan", position: "P", eligibility: "FR", homeState: "PA", hometown: "Allentown", jerseyNumber: 50,
      hitForAvg: 10, power: 9, speed: 29, arm: 32, fielding: 20, errorResistance: 32, velocity: 30, control: 31, stamina: 31, stuff: 30,
      clutch: 36, vsLHP: 35, grit: 37, stealing: 9, running: 26, throwing: 46, recovery: 24, wRISP: 23, vsLefty: 25, poise: 24, heater: 33, agile: 32,
      abilities: ["Escape Pitch", "Halting Quickness"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Matt", lastName: "Chatelle", position: "C", eligibility: "SR", homeState: "NJ", hometown: "Bridgewater", jerseyNumber: 12,
      hitForAvg: 58, power: 51, speed: 33, arm: 55, fielding: 55, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 55, stealing: 12, running: 27, throwing: 56, recovery: 44, wRISP: 51, vsLefty: 47, poise: 53, heater: 0, agile: 32,
      abilities: ["Defensive Artisan", "Tough Out"], potential: "B+", catcherAbility: 52,
      ...noPitches },
    { firstName: "Trey", lastName: "Wells", position: "C", eligibility: "SR", homeState: "NJ", hometown: "Middletown", jerseyNumber: 18,
      hitForAvg: 46, power: 42, speed: 29, arm: 45, fielding: 43, errorResistance: 41, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 39, vsLHP: 37, grit: 41, stealing: 10, running: 24, throwing: 46, recovery: 35, wRISP: 38, vsLefty: 36, poise: 39, heater: 0, agile: 26,
      abilities: ["Bad Mood"], potential: "B", catcherAbility: 42,
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Yomar", lastName: "Carreras", position: "SS", eligibility: "SO", homeState: "FL", hometown: "Miami", jerseyNumber: 2,
      hitForAvg: 62, power: 50, speed: 59, arm: 58, fielding: 58, errorResistance: 57, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 51, grit: 55, stealing: 41, running: 54, throwing: 60, recovery: 44, wRISP: 52, vsLefty: 50, poise: 54, heater: 0, agile: 57,
      abilities: ["Defensive Artisan", "Express Baserunning"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Charlie", lastName: "Meglio", position: "3B", eligibility: "JR", homeState: "NC", hometown: "Buies Creek", jerseyNumber: 8,
      hitForAvg: 64, power: 67, speed: 41, arm: 55, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 55, grit: 60, stealing: 14, running: 36, throwing: 57, recovery: 46, wRISP: 58, vsLefty: 54, poise: 57, heater: 0, agile: 39,
      abilities: ["Power Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "Jaros", position: "1B", eligibility: "JR", homeState: "NJ", hometown: "Westfield", jerseyNumber: 24,
      hitForAvg: 59, power: 57, speed: 38, arm: 50, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 13, running: 32, throwing: 52, recovery: 42, wRISP: 49, vsLefty: 45, poise: 50, heater: 0, agile: 36,
      abilities: ["Contact Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Quinten", lastName: "Perilli", position: "2B", eligibility: "JR", homeState: "NJ", hometown: "Summit", jerseyNumber: 6,
      hitForAvg: 54, power: 42, speed: 47, arm: 48, fielding: 51, errorResistance: 49, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 42, grit: 47, stealing: 28, running: 42, throwing: 49, recovery: 39, wRISP: 43, vsLefty: 40, poise: 44, heater: 0, agile: 47,
      abilities: ["Chance Maker"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Tristan", lastName: "Salinas", position: "SS", eligibility: "JR", homeState: "CA", hometown: "Anaheim", jerseyNumber: 5,
      hitForAvg: 51, power: 41, speed: 50, arm: 51, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 43, vsLHP: 40, grit: 44, stealing: 31, running: 44, throwing: 53, recovery: 37, wRISP: 42, vsLefty: 39, poise: 43, heater: 0, agile: 50,
      abilities: ["Tough Out", "Resilient", "Chance Maker"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Anthony", lastName: "Stephan", position: "3B", eligibility: "FR", homeState: "NJ", hometown: "Morristown", jerseyNumber: 3,
      hitForAvg: 35, power: 30, speed: 40, arm: 36, fielding: 33, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 26, vsLHP: 25, grit: 28, stealing: 22, running: 34, throwing: 37, recovery: 25, wRISP: 26, vsLefty: 23, poise: 26, heater: 0, agile: 37,
      abilities: ["High Ball Hitter", "Pressure Run"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Max", lastName: "Brown", position: "1B", eligibility: "FR", homeState: "PA", hometown: "Doylestown", jerseyNumber: 28,
      hitForAvg: 41, power: 39, speed: 33, arm: 42, fielding: 39, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 29, grit: 34, stealing: 11, running: 28, throwing: 43, recovery: 29, wRISP: 31, vsLefty: 28, poise: 31, heater: 0, agile: 31,
      abilities: ["Batter Intimidator", "Artist"], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Peyton", lastName: "Bonds", position: "OF", eligibility: "JR", homeState: "NJ", hometown: "Piscataway", jerseyNumber: 7,
      hitForAvg: 56, power: 51, speed: 53, arm: 47, fielding: 48, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 47, grit: 50, stealing: 40, running: 48, throwing: 48, recovery: 40, wRISP: 48, vsLefty: 45, poise: 49, heater: 0, agile: 50,
      abilities: ["Express Baserunning", "Power Hitter", "Contact Hitter"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Chase", lastName: "Krewson", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Orlando", jerseyNumber: 10,
      hitForAvg: 61, power: 53, speed: 53, arm: 53, fielding: 51, errorResistance: 49, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 49, grit: 54, stealing: 34, running: 48, throwing: 54, recovery: 43, wRISP: 51, vsLefty: 48, poise: 53, heater: 0, agile: 51,
      abilities: ["Contact Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Nick", lastName: "Cimillo", position: "OF", eligibility: "JR", homeState: "NJ", hometown: "Cranford", jerseyNumber: 9,
      hitForAvg: 56, power: 50, speed: 52, arm: 52, fielding: 49, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 44, grit: 49, stealing: 31, running: 45, throwing: 53, recovery: 39, wRISP: 45, vsLefty: 43, poise: 48, heater: 0, agile: 49,
      abilities: ["God of Pinch Hitting", "Locked and Loaded"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Evan", lastName: "Sleight", position: "OF", eligibility: "SO", homeState: "NY", hometown: "Poughkeepsie", jerseyNumber: 20,
      hitForAvg: 63, power: 54, speed: 64, arm: 62, fielding: 57, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 50, grit: 56, stealing: 37, running: 57, throwing: 63, recovery: 46, wRISP: 52, vsLefty: 47, poise: 53, heater: 0, agile: 62,
      abilities: ["Disturbance", "vs. Breaking Pitches"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "Gale", position: "OF", eligibility: "FR", homeState: "NJ", hometown: "Hoboken", jerseyNumber: 26,
      hitForAvg: 38, power: 32, speed: 45, arm: 40, fielding: 35, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 29, vsLHP: 28, grit: 31, stealing: 25, running: 40, throwing: 41, recovery: 28, wRISP: 28, vsLefty: 26, poise: 28, heater: 0, agile: 43,
      abilities: ["Pressure Run", "Milliner"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Liam", lastName: "Bendo", position: "OF", eligibility: "FR", homeState: "CT", hometown: "Greenwich", jerseyNumber: 30,
      hitForAvg: 37, power: 30, speed: 46, arm: 41, fielding: 36, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 29, vsLHP: 26, grit: 30, stealing: 25, running: 41, throwing: 42, recovery: 26, wRISP: 26, vsLefty: 25, poise: 29, heater: 0, agile: 44,
      abilities: ["Disturbance", "Counterattack", "Contact Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "USC": [
      // 37-12/19-8 BT, D1B #18, Andy Stankiewicz Yr 4. Best start in program history (19-0). Staff #1 nation H/9 (6.86), #1 SHO (8).
      // PITCHERS (10) — 1-8 pitch scale
      // Mason Edwards — LHP JR Thursday ace, 7-0/1.74, #2 nationally per D1B Top 100 SP — TEAM ELITE STUFF
      { firstName: "Mason", lastName: "Edwards", position: "P", eligibility: "JR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 31,
        hitForAvg: 16, power: 12, speed: 38, arm: 65, fielding: 41, errorResistance: 54, velocity: 61, control: 69, stamina: 69, stuff: 71,
        clutch: 80, vsLHP: 90, grit: 80, stealing: 8, running: 32, throwing: 78, recovery: 57, wRISP: 65, vsLefty: 69, poise: 65, heater: 65, agile: 44,
        abilities: ["Star of Victory", "Inside Pitch", "Intimidator", "Heavy Ball", "Winner's Luck"], potential: "A+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [6, 0, 0, 1, 0, 6, 0]) },
      // Grant Govel — RHP SO Friday/weekend, 9-1/2.55
      { firstName: "Grant", lastName: "Govel", position: "P", eligibility: "FR", homeState: "CA", hometown: "San Diego", jerseyNumber: 27,
        hitForAvg: 14, power: 10, speed: 32, arm: 61, fielding: 35, errorResistance: 46, velocity: 58, control: 61, stamina: 62, stuff: 58,
        clutch: 76, vsLHP: 70, grit: 76, stealing: 8, running: 30, throwing: 74, recovery: 51, wRISP: 56, vsLefty: 56, poise: 61, heater: 62, agile: 40,
        abilities: ["Strong Starter", "Inside Pitch", "Painter", "Guts", "Intimidator"], potential: "A+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
      // Diego Velazquez — RHP Saturday starter, 5-1/3.32
      { firstName: "Diego", lastName: "Velazquez", position: "P", eligibility: "JR", homeState: "CA", hometown: "Anaheim", jerseyNumber: 19,
        hitForAvg: 13, power: 10, speed: 32, arm: 55, fielding: 33, errorResistance: 44, velocity: 52, control: 55, stamina: 55, stuff: 53,
        clutch: 64, vsLHP: 60, grit: 66, stealing: 8, running: 30, throwing: 68, recovery: 47, wRISP: 47, vsLefty: 48, poise: 52, heater: 56, agile: 40,
        abilities: ["Strong Starter", "Halting Quickness", "Intimidator"], potential: "A-", catcherAbility: null,
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
      // Andrew Johnson — SO RHP swing, 4-2/3.75 in 60 IP (14 apps)
      { firstName: "Andrew", lastName: "Johnson", position: "P", eligibility: "FR", homeState: "CA", hometown: "Thousand Oaks", jerseyNumber: 35,
        hitForAvg: 12, power: 9, speed: 34, arm: 51, fielding: 31, errorResistance: 42, velocity: 50, control: 49, stamina: 54, stuff: 49,
        clutch: 60, vsLHP: 58, grit: 62, stealing: 8, running: 30, throwing: 66, recovery: 45, wRISP: 43, vsLefty: 45, poise: 48, heater: 54, agile: 40,
        abilities: ["Guts", "Pace", "Winner's Luck", "True Slider"], potential: "A-", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
      // Adam Troy — closer, 11 SV (3rd nation), 32 K in 25.2 IP
      { firstName: "Adam", lastName: "Troy", position: "P", eligibility: "SR", homeState: "CA", hometown: "Long Beach", jerseyNumber: 23,
        hitForAvg: 12, power: 10, speed: 34, arm: 60, fielding: 33, errorResistance: 44, velocity: 57, control: 57, stamina: 39, stuff: 58,
        clutch: 80, vsLHP: 70, grit: 76, stealing: 8, running: 30, throwing: 74, recovery: 44, wRISP: 60, vsLefty: 57, poise: 63, heater: 61, agile: 40,
        abilities: ["Fireman", "Doctor K", "Decisive", "Strong Finisher", "Straddle"], potential: "A", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 7, 0, 1, 0, 4, 0]) },
      // Henry Chabot — SR RHP rotation depth
      { firstName: "Henry", lastName: "Chabot", position: "P", eligibility: "SR", homeState: "CA", hometown: "Orange", jerseyNumber: 41,
        hitForAvg: 14, power: 11, speed: 32, arm: 51, fielding: 32, errorResistance: 44, velocity: 48, control: 51, stamina: 49, stuff: 48,
        clutch: 60, vsLHP: 56, grit: 62, stealing: 8, running: 28, throwing: 64, recovery: 45, wRISP: 45, vsLefty: 46, poise: 48, heater: 52, agile: 36,
        abilities: ["Guts", "Crossfire"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
      // Landon Sims — JR RP
      { firstName: "Landon", lastName: "Sims", position: "P", eligibility: "JR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 38,
        hitForAvg: 13, power: 10, speed: 32, arm: 50, fielding: 30, errorResistance: 42, velocity: 49, control: 49, stamina: 38, stuff: 50,
        clutch: 60, vsLHP: 56, grit: 62, stealing: 8, running: 30, throwing: 64, recovery: 41, wRISP: 43, vsLefty: 44, poise: 47, heater: 53, agile: 38,
        abilities: ["Fireman", "Sharpness"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 7, 0, 1, 0, 0, 0]) },
      // Gavin Lauridsen — FR RHP
      { firstName: "Gavin", lastName: "Lauridsen", position: "P", eligibility: "FR", homeState: "CA", hometown: "Riverside", jerseyNumber: 36,
        hitForAvg: 10, power: 8, speed: 28, arm: 34, fielding: 20, errorResistance: 32, velocity: 33, control: 30, stamina: 30, stuff: 31,
        clutch: 36, vsLHP: 34, grit: 38, stealing: 8, running: 26, throwing: 48, recovery: 24, wRISP: 24, vsLefty: 26, poise: 26, heater: 38, agile: 30,
        abilities: ["Explosive Fastball"], potential: "A", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
      // Jake Snider — SO RHP depth
      { firstName: "Jake", lastName: "Snider", position: "P", eligibility: "FR", homeState: "CA", hometown: "Irvine", jerseyNumber: 48,
        hitForAvg: 10, power: 8, speed: 28, arm: 32, fielding: 20, errorResistance: 32, velocity: 30, control: 31, stamina: 29, stuff: 30,
        clutch: 38, vsLHP: 36, grit: 40, stealing: 9, running: 26, throwing: 46, recovery: 25, wRISP: 24, vsLefty: 27, poise: 27, heater: 33, agile: 32,
        abilities: ["Groundball Pitcher"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
      // Alex Williams — SO RHP depth
      { firstName: "Alex", lastName: "Williams", position: "P", eligibility: "FR", homeState: "CA", hometown: "Fresno", jerseyNumber: 50,
        hitForAvg: 11, power: 9, speed: 30, arm: 36, fielding: 22, errorResistance: 34, velocity: 33, control: 35, stamina: 35, stuff: 33,
        clutch: 40, vsLHP: 38, grit: 42, stealing: 8, running: 28, throwing: 50, recovery: 28, wRISP: 26, vsLefty: 29, poise: 29, heater: 38, agile: 34,
        abilities: ["Halting Quickness"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
      // CATCHERS (2)
      // Isaac Cadena — JR C, transfer (TCU/Ohio St), .304/.442/.519, 6 HR
      { firstName: "Isaac", lastName: "Cadena", position: "C", eligibility: "JR", homeState: "TX", hometown: "Fort Worth", jerseyNumber: 14,
        hitForAvg: 83, power: 67, speed: 36, arm: 60, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 76, vsLHP: 70, grit: 76, stealing: 12, running: 32, throwing: 60, recovery: 48, wRISP: 76, vsLefty: 70, poise: 76, heater: 0, agile: 38,
        abilities: ["Contact Hitter", "Power Hitter", "Consigliere"], potential: "A+", catcherAbility: 60,
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Richard Tejeda — C backup, big game vs Northwestern (3 RBI, 2-run HR)
      { firstName: "Richard", lastName: "Tejeda", position: "C", eligibility: "SO", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 15,
        hitForAvg: 53, power: 53, speed: 32, arm: 50, fielding: 48, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 50, vsLHP: 44, grit: 48, stealing: 10, running: 26, throwing: 50, recovery: 38, wRISP: 50, vsLefty: 44, poise: 48, heater: 0, agile: 32,
        abilities: ["Power Hitter"], potential: "B+", catcherAbility: 48,
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // INFIELDERS (7)
      // Kevin Takeuchi — INF JR, offensive leader, .300/54H/44 RBI/48R/13 SB (14 att)/31 BB/11 2B/3 3B
      { firstName: "Kevin", lastName: "Takeuchi", position: "2B", eligibility: "JR", homeState: "CA", hometown: "Torrance", jerseyNumber: 4,
        hitForAvg: 87, power: 63, speed: 74, arm: 56, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 80, vsLHP: 74, grit: 80, stealing: 56, running: 64, throwing: 56, recovery: 46, wRISP: 80, vsLefty: 74, poise: 80, heater: 0, agile: 60,
        abilities: ["Contact Hitter", "Express Baserunning", "Chance Maker"], potential: "A+", catcherAbility: null,
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Maximo Martinez — INF breakout, .257/.374/.390
      { firstName: "Maximo", lastName: "Martinez", position: "3B", eligibility: "SO", homeState: "CA", hometown: "Whittier", jerseyNumber: 5,
        hitForAvg: 63, power: 57, speed: 46, arm: 56, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 56, vsLHP: 52, grit: 58, stealing: 18, running: 40, throwing: 56, recovery: 42, wRISP: 56, vsLefty: 52, poise: 56, heater: 0, agile: 46,
        abilities: ["Power Hitter"], potential: "A-", catcherAbility: null,
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Maddox Riske — INF, 5-for-6 game vs Cal Poly
      { firstName: "Maddox", lastName: "Riske", position: "SS", eligibility: "SO", homeState: "CA", hometown: "Newport Beach", jerseyNumber: 6,
        hitForAvg: 67, power: 55, speed: 54, arm: 60, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 56, vsLHP: 52, grit: 58, stealing: 28, running: 48, throwing: 60, recovery: 44, wRISP: 56, vsLefty: 52, poise: 56, heater: 0, agile: 56,
        abilities: ["Defensive Artisan", "Contact Hitter"], potential: "A", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Abbrie Covarrubias — SS JR, 4 RBI vs Rutgers
      { firstName: "Abbrie", lastName: "Covarrubias", position: "SS", eligibility: "JR", homeState: "CA", hometown: "Whittier", jerseyNumber: 2,
        hitForAvg: 67, power: 57, speed: 60, arm: 60, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 60, vsLHP: 54, grit: 60, stealing: 40, running: 52, throwing: 60, recovery: 44, wRISP: 60, vsLefty: 54, poise: 60, heater: 0, agile: 60,
        abilities: ["Defensive Artisan", "Express Baserunning", "Consigliere"], potential: "A-", catcherAbility: null,
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Adrian Lopez — 3B JR
      { firstName: "Adrian", lastName: "Lopez", position: "3B", eligibility: "JR", homeState: "CA", hometown: "La Puente", jerseyNumber: 8,
        hitForAvg: 63, power: 57, speed: 42, arm: 52, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 54, vsLHP: 50, grit: 56, stealing: 16, running: 36, throwing: 54, recovery: 42, wRISP: 54, vsLefty: 48, poise: 54, heater: 0, agile: 40,
        abilities: ["Contact Hitter"], potential: "B+", catcherAbility: null,
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Dean Carpentier — 1B JR
      { firstName: "Dean", lastName: "Carpentier", position: "1B", eligibility: "JR", homeState: "CA", hometown: "Santa Monica", jerseyNumber: 24,
        hitForAvg: 63, power: 67, speed: 40, arm: 50, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 56, vsLHP: 52, grit: 58, stealing: 12, running: 34, throwing: 52, recovery: 44, wRISP: 56, vsLefty: 50, poise: 56, heater: 0, agile: 38,
        abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Caden Dana — 2B JR utility
      { firstName: "Caden", lastName: "Dana", position: "2B", eligibility: "JR", homeState: "CA", hometown: "Mission Viejo", jerseyNumber: 9,
        hitForAvg: 63, power: 51, speed: 58, arm: 60, fielding: 64, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 54, vsLHP: 50, grit: 56, stealing: 34, running: 50, throwing: 60, recovery: 46, wRISP: 52, vsLefty: 48, poise: 54, heater: 0, agile: 56,
        abilities: ["Chance Maker", "Defensive Artisan"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // OUTFIELDERS (6)
      // Jack Basseer — OF SR, .600 SLG, 14 RBI, 19 R
      { firstName: "Jack", lastName: "Basseer", position: "OF", eligibility: "SR", homeState: "CA", hometown: "San Diego", jerseyNumber: 7,
        hitForAvg: 77, power: 83, speed: 54, arm: 56, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 70, vsLHP: 64, grit: 70, stealing: 30, running: 48, throwing: 56, recovery: 44, wRISP: 70, vsLefty: 64, poise: 70, heater: 0, agile: 50,
        abilities: ["Artist", "Power Hitter", "Consigliere"], potential: "A", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Brock Slaton — OF SR
      { firstName: "Brock", lastName: "Slaton", position: "OF", eligibility: "SR", homeState: "LA", hometown: "New Orleans", jerseyNumber: 17,
        hitForAvg: 63, power: 61, speed: 54, arm: 56, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 56, vsLHP: 52, grit: 58, stealing: 34, running: 48, throwing: 56, recovery: 44, wRISP: 56, vsLefty: 52, poise: 56, heater: 0, agile: 50,
        abilities: ["Power Hitter", "High-Speed Laser"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Rhylan Thomas — OF JR
      { firstName: "Rhylan", lastName: "Thomas", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Long Beach", jerseyNumber: 1,
        hitForAvg: 61, power: 55, speed: 58, arm: 52, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 52, vsLHP: 48, grit: 54, stealing: 36, running: 50, throwing: 54, recovery: 42, wRISP: 50, vsLefty: 46, poise: 52, heater: 0, agile: 54,
        abilities: ["Express Baserunning", "Contact Hitter"], potential: "A-", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Dominic Hellman — OF SO speedster
      { firstName: "Dominic", lastName: "Hellman", position: "OF", eligibility: "SO", homeState: "CA", hometown: "Torrance", jerseyNumber: 11,
        hitForAvg: 63, power: 57, speed: 64, arm: 64, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 54, vsLHP: 50, grit: 56, stealing: 38, running: 58, throwing: 64, recovery: 46, wRISP: 52, vsLefty: 48, poise: 54, heater: 0, agile: 64,
        abilities: ["Express Baserunning", "Contact Hitter"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Theo Denlinger — OF JR
      { firstName: "Theo", lastName: "Denlinger", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Santa Monica", jerseyNumber: 20,
        hitForAvg: 53, power: 53, speed: 32, arm: 36, fielding: 36, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 46, vsLHP: 42, grit: 46, stealing: 9, running: 28, throwing: 38, recovery: 34, wRISP: 46, vsLefty: 40, poise: 46, heater: 0, agile: 28,
        abilities: ["Consigliere"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Braden Davis — OF SO
      { firstName: "Braden", lastName: "Davis", position: "OF", eligibility: "SO", homeState: "TX", hometown: "Austin", jerseyNumber: 26,
        hitForAvg: 53, power: 47, speed: 52, arm: 48, fielding: 46, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 44, vsLHP: 42, grit: 46, stealing: 30, running: 46, throwing: 50, recovery: 38, wRISP: 44, vsLefty: 40, poise: 44, heater: 0, agile: 48,
        abilities: ["Resilient", "Double Play"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
    ],
  
  // UCLA — 45-4 overall, 25-0 Big Ten, D1Baseball #1 (May 3, 2026)
  // Real 2026 mid-season stats from uclabruins.com PDF + Daily Bruin/Baseball America rotation pieces
  "UCLA": [
    // PITCHERS (10) — staff-leading 3.07 ERA, deepest rotation in country
    // Logan Reddemann — Friday SP, JR transfer from USD, projected first-rd, 8 quality starts, elite FB + tantalizing CH
    { firstName: "Logan", lastName: "Reddemann", position: "P", eligibility: "JR", homeState: "CA", hometown: "San Diego", jerseyNumber: 21,
      hitForAvg: 18, power: 14, speed: 38, arm: 71, fielding: 43, errorResistance: 56, velocity: 67, control: 71, stamina: 66, stuff: 71,
      clutch: 78, vsLHP: 75, grit: 80, stealing: 8, running: 33, throwing: 80, recovery: 62, wRISP: 64, vsLefty: 62, poise: 67, heater: 66, agile: 48,
      abilities: ["Star of Victory", "Inside Pitch", "Intimidator", "Natural Shuuto", "Kageura", "Heavy Ball", "True Slider"], potential: "A", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    // Wylan Moss — Saturday bulk reliever / piggyback, SO, team-best 0.89 ERA, 93-95 + elite CH (20" horizontal break), top-15 2027 prospect
    { firstName: "Wylan", lastName: "Moss", position: "P", eligibility: "SO", homeState: "CA", hometown: "Calabasas", jerseyNumber: 40,
      hitForAvg: 12, power: 10, speed: 35, arm: 64, fielding: 39, errorResistance: 52, velocity: 60, control: 64, stamina: 52, stuff: 66,
      clutch: 76, vsLHP: 72, grit: 76, stealing: 7, running: 30, throwing: 75, recovery: 52, wRISP: 63, vsLefty: 59, poise: 63, heater: 56, agile: 50,
      abilities: ["Strong Starter", "Inside Pitch", "Sharpness"], potential: "A", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "medium",
      ...pitchMix(1, [0, 4, 0, 1, 0, 0, 0]) },
    // Michael Barnett — Saturday opener, SR, 3.74 ERA, 244 career IP, four-pitch mix (sinker/CH/SL/CB)
    { firstName: "Michael", lastName: "Barnett", position: "P", eligibility: "SR", homeState: "CA", hometown: "Manhattan Beach", jerseyNumber: 34,
      hitForAvg: 16, power: 12, speed: 30, arm: 55, fielding: 39, errorResistance: 56, velocity: 47, control: 60, stamina: 55, stuff: 50,
      clutch: 70, vsLHP: 68, grit: 74, stealing: 6, running: 26, throwing: 65, recovery: 52, wRISP: 53, vsLefty: 55, poise: 58, heater: 47, agile: 38,
      abilities: ["Strong Starter", "Guts", "Inside Pitch", "Delayed Arm"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 4, 1, 0, 5, 0]) },
    // Landon Stump — Sunday SP, JR, 4.33 ERA, ~3 IP/start, surviving Sundays
    { firstName: "Landon", lastName: "Stump", position: "P", eligibility: "JR", homeState: "CA", hometown: "Huntington Beach", jerseyNumber: 14,
      hitForAvg: 14, power: 11, speed: 32, arm: 48, fielding: 33, errorResistance: 48, velocity: 49, control: 45, stamina: 41, stuff: 45,
      clutch: 56, vsLHP: 54, grit: 58, stealing: 6, running: 28, throwing: 60, recovery: 41, wRISP: 41, vsLefty: 42, poise: 44, heater: 48, agile: 42,
      abilities: ["Guts", "Release", "Inside Pitch"], potential: "B", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    // Easton Hawk — closer, SO, mid-90s + tight horizontal SL, 16 scoreless app, Big Ten Co-Pitcher of Week, Woodland Hills CA
    { firstName: "Easton", lastName: "Hawk", position: "P", eligibility: "SO", homeState: "CA", hometown: "Woodland Hills", jerseyNumber: 27,
      hitForAvg: 11, power: 8, speed: 35, arm: 62, fielding: 34, errorResistance: 48, velocity: 57, control: 56, stamina: 30, stuff: 59,
      clutch: 80, vsLHP: 72, grit: 76, stealing: 7, running: 30, throwing: 75, recovery: 47, wRISP: 61, vsLefty: 56, poise: 62, heater: 53, agile: 48,
      abilities: ["Fireman", "Doctor K", "Intimidator"], potential: "A-", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 6, 0, 1, 0, 0, 0]) },
    // Cal Randall — JR setup, 98mph FB touching 100, 21K/11IP (42% K rate, 8th P4), walks 1 of 5
    { firstName: "Cal", lastName: "Randall", position: "P", eligibility: "JR", homeState: "CA", hometown: "Temecula", jerseyNumber: 33,
      hitForAvg: 10, power: 8, speed: 32, arm: 66, fielding: 32, errorResistance: 44, velocity: 64, control: 37, stamina: 23, stuff: 61,
      clutch: 64, vsLHP: 60, grit: 60, stealing: 6, running: 28, throwing: 78, recovery: 38, wRISP: 46, vsLefty: 46, poise: 47, heater: 60, agile: 50,
      abilities: ["Fireman", "Explosive Fastball", "Walk"], potential: "A-", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 0, 1, 0, 0, 0]) },
    // Angel Cervantes — FR, RHP, 2nd-round talent who chose college, top young prospect
    { firstName: "Angel", lastName: "Cervantes", position: "P", eligibility: "FR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 29,
      hitForAvg: 11, power: 8, speed: 30, arm: 55, fielding: 29, errorResistance: 40, velocity: 52, control: 46, stamina: 43, stuff: 55,
      clutch: 50, vsLHP: 48, grit: 50, stealing: 7, running: 27, throwing: 68, recovery: 37, wRISP: 37, vsLefty: 38, poise: 38, heater: 53, agile: 42,
      abilities: ["Strong Starter", "Sharpness", "Kageura"], potential: "A", catcherAbility: null,
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    // Zach Strickland — FR RHP, weekend bullpen, elite K/BB
    { firstName: "Zach", lastName: "Strickland", position: "P", eligibility: "FR", homeState: "CA", hometown: "Redondo Beach", jerseyNumber: 45,
      hitForAvg: 10, power: 7, speed: 28, arm: 41, fielding: 23, errorResistance: 36, velocity: 39, control: 51, stamina: 28, stuff: 39,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 6, running: 25, throwing: 56, recovery: 32, wRISP: 36, vsLefty: 36, poise: 38, heater: 41, agile: 36,
      abilities: ["Inside Pitch"], potential: "A-", catcherAbility: null,
      skinTone: "light", hairColor: "blonde", hairStyle: "short",
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    // Ian May — RS-Sr LHP, multi-inning long man
    { firstName: "Ian", lastName: "May", position: "P", eligibility: "SR", homeState: "CA", hometown: "Rancho Cucamonga", jerseyNumber: 38,
      hitForAvg: 12, power: 9, speed: 26, arm: 44, fielding: 30, errorResistance: 46, velocity: 38, control: 47, stamina: 41, stuff: 38,
      clutch: 54, vsLHP: 70, grit: 56, stealing: 5, running: 22, throwing: 56, recovery: 38, wRISP: 38, vsLefty: 52, poise: 41, heater: 37, agile: 32,
      abilities: ["Fireman", "Guts", "Houdini"], potential: "B", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    // Jake Swenson — JR depth pitcher
    { firstName: "Jake", lastName: "Swenson", position: "P", eligibility: "JR", homeState: "WA", hometown: "Seattle", jerseyNumber: 48,
      hitForAvg: 11, power: 9, speed: 28, arm: 37, fielding: 25, errorResistance: 38, velocity: 36, control: 37, stamina: 34, stuff: 35,
      clutch: 46, vsLHP: 44, grit: 46, stealing: 7, running: 24, throwing: 52, recovery: 31, wRISP: 31, vsLefty: 32, poise: 32, heater: 38, agile: 32,
      abilities: ["True Slider", "Gear Change"], potential: "B", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 3, 3, 1, 0, 0, 0]) },
    // CATCHERS (2)
    // Cashel Dugger — JR C, Buster Posey Award watch list, primary backstop
    { firstName: "Cashel", lastName: "Dugger", position: "C", eligibility: "JR", homeState: "CA", hometown: "Torrance", jerseyNumber: 16,
      hitForAvg: 67, power: 63, speed: 32, arm: 76, fielding: 70, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 65, vsLHP: 62, grit: 70, stealing: 12, running: 28, throwing: 76, recovery: 56, wRISP: 64, vsLefty: 60, poise: 68, heater: 0, agile: 38,
      abilities: ["Defensive Artisan", "High-Speed Laser", "Consigliere"], potential: "A-", catcherAbility: 70,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Khansarinia — backup C, allowed 10 SB on 12 attempts (mentioned in PDF SBA)
    { firstName: "Sam", lastName: "Khansarinia", position: "C", eligibility: "SO", homeState: "CA", hometown: "Irvine", jerseyNumber: 18,
      hitForAvg: 37, power: 33, speed: 26, arm: 50, fielding: 44, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 30, grit: 35, stealing: 6, running: 20, throwing: 50, recovery: 30, wRISP: 30, vsLefty: 28, poise: 32, heater: 0, agile: 26,
      abilities: ["Bases Loaded Slugger", "Tough Out", "Resilient"], potential: "B-", catcherAbility: 42,
      skinTone: "light", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // INFIELDERS (7)
    // Roch Cholowsky — JR SS, projected #1 overall MLB pick, .335/18HR/62R, leads B10 in runs, generational talent
    { firstName: "Roch", lastName: "Cholowsky", position: "SS", eligibility: "JR", homeState: "CA", hometown: "Oceanside", jerseyNumber: 2,
      hitForAvg: 95, power: 93, speed: 74, arm: 80, fielding: 84, errorResistance: 80, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 88, vsLHP: 86, grit: 84, stealing: 38, running: 70, throwing: 82, recovery: 68, wRISP: 88, vsLefty: 86, poise: 86, heater: 0, agile: 70,
      abilities: ["Iron Man", "Push", "Power Hitter", "Consigliere", "Contact Hitter", "Tough Out"], potential: "A+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Mulivai Levu — 1B, .347/14HR/54RBI, All-Conference 2025
    { firstName: "Mulivai", lastName: "Levu", position: "1B", eligibility: "JR", homeState: "HI", hometown: "Honolulu", jerseyNumber: 24,
      hitForAvg: 85, power: 81, speed: 34, arm: 56, fielding: 60, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 76, vsLHP: 70, grit: 74, stealing: 8, running: 28, throwing: 56, recovery: 54, wRISP: 78, vsLefty: 68, poise: 74, heater: 0, agile: 32,
      abilities: ["Power Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Roman Martin — SO, .339/7HR, All-Conference, hybrid C/3B per Daily Bruin
    { firstName: "Roman", lastName: "Martin", position: "3B", eligibility: "SO", homeState: "CA", hometown: "Chino Hills", jerseyNumber: 8,
      hitForAvg: 83, power: 67, speed: 42, arm: 64, fielding: 62, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 70, vsLHP: 68, grit: 68, stealing: 14, running: 35, throwing: 65, recovery: 52, wRISP: 70, vsLefty: 66, poise: 70, heater: 0, agile: 44,
      abilities: ["Contact Hitter", "Defensive Artisan"], potential: "A-", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Aidan Espinoza — FR INF, .360 (team batting leader), Sherman Oaks/Notre Dame HS
    { firstName: "Aidan", lastName: "Espinoza", position: "2B", eligibility: "FR", homeState: "CA", hometown: "Sherman Oaks", jerseyNumber: 6,
      hitForAvg: 85, power: 57, speed: 54, arm: 56, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 65, vsLHP: 64, grit: 62, stealing: 22, running: 47, throwing: 56, recovery: 50, wRISP: 68, vsLefty: 66, poise: 64, heater: 0, agile: 54,
      abilities: ["Contact Hitter", "Chance Maker"], potential: "A", catcherAbility: null,
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Phoenix Call — SO INF, 1 HR, role player
    { firstName: "Phoenix", lastName: "Call", position: "SS", eligibility: "SO", homeState: "CA", hometown: "Anaheim", jerseyNumber: 3,
      hitForAvg: 45, power: 39, speed: 46, arm: 50, fielding: 52, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 22, running: 40, throwing: 52, recovery: 36, wRISP: 38, vsLefty: 36, poise: 40, heater: 0, agile: 50,
      abilities: ["Iron Man", "Error Prone"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "medium",
      ...noPitches },
    // Cole Lee — depth IF (mentioned in PDF SBA totals)
    { firstName: "Cole", lastName: "Lee", position: "2B", eligibility: "FR", homeState: "CA", hometown: "Glendale", jerseyNumber: 14,
      hitForAvg: 39, power: 33, speed: 42, arm: 42, fielding: 40, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 30, grit: 34, stealing: 18, running: 36, throwing: 42, recovery: 30, wRISP: 30, vsLefty: 28, poise: 32, heater: 0, agile: 42,
      abilities: ["Pinch Hitter"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Tommy Bott — backup 1B/depth (mentioned in PDF SBA)
    { firstName: "Tommy", lastName: "Bott", position: "1B", eligibility: "FR", homeState: "CA", hometown: "San Clemente", jerseyNumber: 28,
      hitForAvg: 37, power: 39, speed: 29, arm: 44, fielding: 40, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 30, vsLHP: 28, grit: 32, stealing: 8, running: 24, throwing: 44, recovery: 30, wRISP: 30, vsLefty: 27, poise: 30, heater: 0, agile: 28,
      abilities: ["Double Play"], potential: "B", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // OUTFIELDERS (6)
    // Will Gasparino — JR OF, Texas transfer, .322/18HR (team co-leader), LA/Harvard-Westlake, two-time All-Big 12, SEC All-Defense
    { firstName: "Will", lastName: "Gasparino", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 11,
      hitForAvg: 81, power: 87, speed: 56, arm: 70, fielding: 68, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 72, vsLHP: 68, grit: 70, stealing: 28, running: 50, throwing: 70, recovery: 56, wRISP: 76, vsLefty: 68, poise: 72, heater: 0, agile: 56,
      abilities: ["Power Hitter", "High-Speed Laser", "Good Infield Hit"], potential: "A-", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "medium",
      ...noPitches },
    // Dean West — LF leadoff, .470 OBP, JR, walks/HBP machine
    { firstName: "Dean", lastName: "West", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Temecula", jerseyNumber: 7,
      hitForAvg: 75, power: 57, speed: 64, arm: 54, fielding: 58, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 64, grit: 76, stealing: 42, running: 58, throwing: 56, recovery: 52, wRISP: 64, vsLefty: 64, poise: 68, heater: 0, agile: 60,
      abilities: ["Chance Maker", "Express Baserunning"], potential: "A-", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Payton Brennan — JR OF, 8 HR, 6 SB
    { firstName: "Payton", lastName: "Brennan", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Anaheim", jerseyNumber: 9,
      hitForAvg: 67, power: 67, speed: 59, arm: 56, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 35, running: 52, throwing: 58, recovery: 48, wRISP: 60, vsLefty: 56, poise: 60, heater: 0, agile: 52,
      abilities: ["Consigliere"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Daylen Reyes — SO OF speed/defense
    { firstName: "Daylen", lastName: "Reyes", position: "OF", eligibility: "SO", homeState: "CA", hometown: "Oxnard", jerseyNumber: 30,
      hitForAvg: 53, power: 47, speed: 68, arm: 60, fielding: 58, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 42, grit: 48, stealing: 42, running: 60, throwing: 60, recovery: 44, wRISP: 44, vsLefty: 42, poise: 46, heater: 0, agile: 60,
      abilities: ["Express Baserunning"], potential: "B+", catcherAbility: null,
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Tristan Iwanaga — depth OF (mentioned PDF SBA 2-2)
    { firstName: "Tristan", lastName: "Iwanaga", position: "OF", eligibility: "SO", homeState: "HI", hometown: "Honolulu", jerseyNumber: 17,
      hitForAvg: 45, power: 39, speed: 54, arm: 48, fielding: 50, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 36, grit: 42, stealing: 28, running: 48, throwing: 50, recovery: 38, wRISP: 38, vsLefty: 36, poise: 40, heater: 0, agile: 50,
      abilities: ["Multi-Hit", "Late Night Hero", "Contact Hitter"], potential: "B", catcherAbility: null,
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Michael Curialle — JR OF depth
    { firstName: "Michael", lastName: "Curialle", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Rancho Cucamonga", jerseyNumber: 26,
      hitForAvg: 43, power: 39, speed: 40, arm: 42, fielding: 42, errorResistance: 40, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 36, vsLHP: 34, grit: 38, stealing: 18, running: 34, throwing: 42, recovery: 32, wRISP: 34, vsLefty: 32, poise: 36, heater: 0, agile: 38,
      abilities: ["Good Mood"], potential: "B", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
  ],

  "Washington": [
    // PITCHERS (10)
    { firstName: "Hayden", lastName: "Lewis", position: "P", eligibility: "SR", homeState: "AZ", hometown: "Tucson", jerseyNumber: 17,
      hitForAvg: 21, power: 16, speed: 39, arm: 68, fielding: 43, errorResistance: 55, velocity: 71, control: 65, stamina: 65, stuff: 65,
      clutch: 78, vsLHP: 74, grit: 90, stealing: 10, running: 35, throwing: 80, recovery: 60, wRISP: 62, vsLefty: 64, poise: 65, heater: 69, agile: 43,
      abilities: ["Star of Victory", "Strong Starter", "Guts", "Escape Pitch", "Gyroball", "Wild Fastball"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 7, 5, 1, 0, 0, 0]) },
    { firstName: "Nate", lastName: "Tichy", position: "P", eligibility: "SO", homeState: "CA", hometown: "Malibu", jerseyNumber: 18,
      hitForAvg: 13, power: 10, speed: 37, arm: 49, fielding: 30, errorResistance: 41, velocity: 48, control: 45, stamina: 47, stuff: 47,
      clutch: 56, vsLHP: 52, grit: 57, stealing: 10, running: 33, throwing: 62, recovery: 39, wRISP: 41, vsLefty: 42, poise: 43, heater: 52, agile: 40,
      abilities: ["Strong Starter", "Explosive Fastball", "Intimidator", "Quick Hands"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Liam", lastName: "Lierman", position: "P", eligibility: "FR", homeState: "AK", hometown: "Anchorage", jerseyNumber: 15,
      hitForAvg: 11, power: 8, speed: 27, arm: 32, fielding: 20, errorResistance: 31, velocity: 32, control: 30, stamina: 31, stuff: 30,
      clutch: 38, vsLHP: 37, grit: 40, stealing: 8, running: 24, throwing: 46, recovery: 25, wRISP: 25, vsLefty: 26, poise: 26, heater: 35, agile: 30,
      abilities: ["Guts"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Cooper", lastName: "Benson", position: "P", eligibility: "SR", homeState: "OR", hometown: "Portland", jerseyNumber: 41,
      hitForAvg: 14, power: 11, speed: 28, arm: 43, fielding: 28, errorResistance: 41, velocity: 42, control: 43, stamina: 41, stuff: 40,
      clutch: 56, vsLHP: 52, grit: 56, stealing: 8, running: 25, throwing: 56, recovery: 40, wRISP: 40, vsLefty: 41, poise: 41, heater: 45, agile: 32,
      abilities: ["Fireman", "Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 1, 4, 0, 0]) },
    { firstName: "Parker", lastName: "Pistone", position: "P", eligibility: "JR", homeState: "WA", hometown: "Redmond", jerseyNumber: 22,
      hitForAvg: 14, power: 11, speed: 31, arm: 43, fielding: 27, errorResistance: 38, velocity: 40, control: 43, stamina: 44, stuff: 41,
      clutch: 53, vsLHP: 49, grit: 54, stealing: 8, running: 27, throwing: 56, recovery: 38, wRISP: 38, vsLefty: 39, poise: 40, heater: 45, agile: 34,
      abilities: ["Strong Starter", "Flyball Pitcher", "Low Ball"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Sam", lastName: "Strohl", position: "P", eligibility: "JR", homeState: "WA", hometown: "Olympia", jerseyNumber: 38,
      hitForAvg: 16, power: 12, speed: 32, arm: 44, fielding: 29, errorResistance: 40, velocity: 42, control: 44, stamina: 42, stuff: 42,
      clutch: 53, vsLHP: 50, grit: 54, stealing: 9, running: 29, throwing: 57, recovery: 39, wRISP: 37, vsLefty: 40, poise: 40, heater: 47, agile: 36,
      abilities: ["Natural Shuuto", "Star of Victory"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Quinn", lastName: "Mathews", position: "P", eligibility: "SO", homeState: "WA", hometown: "Spokane", jerseyNumber: 48,
      hitForAvg: 10, power: 9, speed: 30, arm: 33, fielding: 21, errorResistance: 33, velocity: 31, control: 32, stamina: 31, stuff: 30,
      clutch: 40, vsLHP: 39, grit: 41, stealing: 10, running: 27, throwing: 47, recovery: 26, wRISP: 26, vsLefty: 28, poise: 27, heater: 35, agile: 33,
      abilities: ["Guts", "Phantasmagoric"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Bremner", position: "P", eligibility: "SO", homeState: "OR", hometown: "Eugene", jerseyNumber: 50,
      hitForAvg: 9, power: 8, speed: 25, arm: 42, fielding: 27, errorResistance: 28, velocity: 41, control: 41, stamina: 41, stuff: 39,
      clutch: 33, vsLHP: 32, grit: 35, stealing: 8, running: 23, throwing: 41, recovery: 32, wRISP: 32, vsLefty: 35, poise: 33, heater: 45, agile: 28,
      abilities: ["Cowardly"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 1, 0, 0, 0]) },
    { firstName: "Nate", lastName: "Weeldreyer", position: "P", eligibility: "JR", homeState: "WA", hometown: "Lynnwood", jerseyNumber: 36,
      hitForAvg: 11, power: 8, speed: 23, arm: 27, fielding: 18, errorResistance: 29, velocity: 30, control: 26, stamina: 26, stuff: 30,
      clutch: 38, vsLHP: 37, grit: 39, stealing: 6, running: 20, throwing: 41, recovery: 24, wRISP: 24, vsLefty: 25, poise: 25, heater: 29, agile: 25,
      abilities: ["Monster Stuff"], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Harmon", position: "P", eligibility: "SO", homeState: "CA", hometown: "San Bernardino", jerseyNumber: 45,
      hitForAvg: 11, power: 8, speed: 27, arm: 34, fielding: 23, errorResistance: 32, velocity: 33, control: 33, stamina: 33, stuff: 31,
      clutch: 39, vsLHP: 37, grit: 40, stealing: 8, running: 25, throwing: 45, recovery: 27, wRISP: 27, vsLefty: 29, poise: 29, heater: 37, agile: 31,
      abilities: ["Poor Finisher"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Colton", lastName: "Bower", position: "C", eligibility: "JR", homeState: "WA", hometown: "Pullman", jerseyNumber: 2,
      hitForAvg: 62, power: 55, speed: 36, arm: 62, fielding: 60, errorResistance: 59, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 53, grit: 59, stealing: 14, running: 31, throwing: 63, recovery: 48, wRISP: 55, vsLefty: 52, poise: 56, heater: 0, agile: 36,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: 56,
      ...noPitches },
    { firstName: "Ethan", lastName: "Swidler", position: "C", eligibility: "SR", homeState: "PA", hometown: "Easton", jerseyNumber: 4,
      hitForAvg: 58, power: 51, speed: 34, arm: 57, fielding: 55, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 49, grit: 54, stealing: 12, running: 28, throwing: 59, recovery: 44, wRISP: 51, vsLefty: 47, poise: 52, heater: 0, agile: 31,
      abilities: ["Contact Hitter"], potential: "B", catcherAbility: 52,
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Ty", lastName: "Cowan", position: "SS", eligibility: "SR", homeState: "WA", hometown: "Kirkland", jerseyNumber: 1,
      hitForAvg: 56, power: 48, speed: 52, arm: 52, fielding: 53, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 46, grit: 51, stealing: 37, running: 46, throwing: 53, recovery: 41, wRISP: 48, vsLefty: 46, poise: 49, heater: 0, agile: 51,
      abilities: ["Defensive Artisan", "Express Baserunning"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Chase", lastName: "Cretti", position: "3B", eligibility: "JR", homeState: "WA", hometown: "Sammamish", jerseyNumber: 3,
      hitForAvg: 62, power: 56, speed: 45, arm: 58, fielding: 56, errorResistance: 55, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 55, vsLHP: 51, grit: 56, stealing: 20, running: 40, throwing: 59, recovery: 45, wRISP: 53, vsLefty: 49, poise: 55, heater: 0, agile: 44,
      abilities: ["Contact Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Blake", lastName: "Wilson", position: "1B", eligibility: "JR", homeState: "WA", hometown: "Bellevue", jerseyNumber: 7,
      hitForAvg: 62, power: 60, speed: 40, arm: 53, fielding: 55, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 55, vsLHP: 52, grit: 56, stealing: 14, running: 35, throwing: 55, recovery: 45, wRISP: 53, vsLefty: 50, poise: 55, heater: 0, agile: 38,
      abilities: ["Power Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Casen", lastName: "Taggart", position: "2B", eligibility: "SR", homeState: "WA", hometown: "Pullman", jerseyNumber: 12,
      hitForAvg: 61, power: 49, speed: 54, arm: 54, fielding: 58, errorResistance: 57, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 50, grit: 54, stealing: 33, running: 48, throwing: 57, recovery: 45, wRISP: 52, vsLefty: 48, poise: 53, heater: 0, agile: 53,
      abilities: ["Chance Maker"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Landon", lastName: "Young", position: "SS", eligibility: "FR", homeState: "TX", hometown: "Fort Worth", jerseyNumber: 6,
      hitForAvg: 42, power: 35, speed: 48, arm: 42, fielding: 39, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 34, vsLHP: 31, grit: 35, stealing: 28, running: 42, throwing: 44, recovery: 29, wRISP: 32, vsLefty: 29, poise: 32, heater: 0, agile: 45,
      abilities: ["Late Night Hero"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Alexander", lastName: "Pearson", position: "1B", eligibility: "FR", homeState: "WA", hometown: "Seattle", jerseyNumber: 11,
      hitForAvg: 48, power: 45, speed: 39, arm: 50, fielding: 46, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 35, grit: 41, stealing: 13, running: 34, throwing: 51, recovery: 35, wRISP: 37, vsLefty: 34, poise: 37, heater: 0, agile: 37,
      abilities: ["Storming Home", "Artist"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jake", lastName: "Dukart", position: "2B", eligibility: "FR", homeState: "WA", hometown: "Pasco", jerseyNumber: 14,
      hitForAvg: 40, power: 32, speed: 47, arm: 42, fielding: 39, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 29, grit: 33, stealing: 25, running: 42, throwing: 43, recovery: 28, wRISP: 29, vsLefty: 28, poise: 32, heater: 0, agile: 45,
      abilities: ["Hit Machine", "Good Mood", "Good Bunt"], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Aidan", lastName: "Dougherty", position: "OF", eligibility: "SR", homeState: "CA", hometown: "San Jose", jerseyNumber: 9,
      hitForAvg: 61, power: 56, speed: 56, arm: 54, fielding: 53, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 52, grit: 56, stealing: 36, running: 49, throwing: 56, recovery: 43, wRISP: 54, vsLefty: 49, poise: 54, heater: 0, agile: 53,
      abilities: ["High-Speed Laser", "Consigliere"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Braeden", lastName: "Terry", position: "OF", eligibility: "SR", homeState: "WA", hometown: "Tacoma", jerseyNumber: 10,
      hitForAvg: 56, power: 52, speed: 51, arm: 52, fielding: 49, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 47, grit: 52, stealing: 32, running: 45, throwing: 53, recovery: 41, wRISP: 48, vsLefty: 45, poise: 49, heater: 0, agile: 48,
      abilities: ["Contact Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Mic", lastName: "Paul", position: "OF", eligibility: "JR", homeState: "LA", hometown: "Baton Rouge", jerseyNumber: 13,
      hitForAvg: 55, power: 51, speed: 52, arm: 49, fielding: 47, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 44, grit: 48, stealing: 36, running: 47, throwing: 50, recovery: 38, wRISP: 45, vsLefty: 42, poise: 47, heater: 0, agile: 49,
      abilities: ["Express Baserunning", "Contact Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jackson", lastName: "Hotchkiss", position: "OF", eligibility: "SO", homeState: "WA", hometown: "Vancouver", jerseyNumber: 19,
      hitForAvg: 53, power: 46, speed: 53, arm: 50, fielding: 47, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 41, grit: 46, stealing: 31, running: 47, throwing: 51, recovery: 38, wRISP: 42, vsLefty: 39, poise: 44, heater: 0, agile: 50,
      abilities: ["Slap Happy", "Contact Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Kyle", lastName: "Seymour", position: "OF", eligibility: "FR", homeState: "WA", hometown: "Lynnwood", jerseyNumber: 26,
      hitForAvg: 39, power: 34, speed: 48, arm: 41, fielding: 37, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 31, vsLHP: 30, grit: 32, stealing: 26, running: 41, throwing: 44, recovery: 30, wRISP: 30, vsLefty: 27, poise: 30, heater: 0, agile: 45,
      abilities: ["Slap Happy"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "JR", lastName: "Ritger", position: "OF", eligibility: "SO", homeState: "WI", hometown: "Appleton", jerseyNumber: 30,
      hitForAvg: 43, power: 38, speed: 42, arm: 40, fielding: 37, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 35, vsLHP: 32, grit: 36, stealing: 25, running: 37, throwing: 41, recovery: 30, wRISP: 33, vsLefty: 31, poise: 35, heater: 0, agile: 40,
      abilities: ["Trickster", "Pressure Run"], potential: "B", catcherAbility: null,
      ...noPitches },
  ],
};
