import { RealPlayer } from "./realRosters";
import { pitchMix, noPitches } from "./pitchMixHelpers";

export const BIG_TEN_BATCH2_ROSTERS: Record<string, RealPlayer[]> = {
  "Minnesota": [
    // PITCHERS (12)
    { firstName: "Cole", lastName: "Selvig", position: "P", eligibility: "JR", homeState: "MN", hometown: "Wayzata", jerseyNumber: 17,
      hitForAvg: 26, power: 21, speed: 43, arm: 89, fielding: 56, errorResistance: 72, velocity: 91, control: 85, stamina: 86, stuff: 86,
      clutch: 99, vsLHP: 95, grit: 99, stealing: 13, running: 48, throwing: 99, recovery: 78, wRISP: 79, vsLefty: 79, poise: 85, heater: 93, agile: 61,
      abilities: ["Star of Victory", "Strong Starter", "Intimidator", "Heavy Ball", "Winner's Luck", "Pace", "Straddle"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 7, 6, 1, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Hemmesch", position: "P", eligibility: "JR", homeState: "MN", hometown: "Cold Spring", jerseyNumber: 31,
      hitForAvg: 15, power: 11, speed: 33, arm: 48, fielding: 29, errorResistance: 42, velocity: 51, control: 46, stamina: 48, stuff: 45,
      clutch: 55, vsLHP: 53, grit: 60, stealing: 8, running: 30, throwing: 61, recovery: 42, wRISP: 42, vsLefty: 42, poise: 45, heater: 49, agile: 36,
      abilities: ["Strong Starter", "Guts"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Will", lastName: "Whelan", position: "P", eligibility: "JR", homeState: "MN", hometown: "Minnetonka", jerseyNumber: 22,
      hitForAvg: 19, power: 16, speed: 42, arm: 63, fielding: 39, errorResistance: 56, velocity: 69, control: 59, stamina: 62, stuff: 59,
      clutch: 77, vsLHP: 73, grit: 79, stealing: 13, running: 42, throwing: 82, recovery: 56, wRISP: 57, vsLefty: 57, poise: 59, heater: 67, agile: 51,
      abilities: ["Strong Starter", "Sharpness"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 7, 5, 1, 0, 0, 0]) },
    { firstName: "Brandon", lastName: "Jaenke", position: "P", eligibility: "JR", homeState: "MN", hometown: "Shakopee", jerseyNumber: 38,
      hitForAvg: 20, power: 15, speed: 39, arm: 64, fielding: 39, errorResistance: 53, velocity: 70, control: 58, stamina: 49, stuff: 61,
      clutch: 80, vsLHP: 73, grit: 83, stealing: 11, running: 39, throwing: 83, recovery: 58, wRISP: 58, vsLefty: 58, poise: 63, heater: 68, agile: 50,
      abilities: ["Fireman", "Guts", "Halting Quickness", "Pace"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 6, 0, 1, 4, 0, 0]) },
    { firstName: "Marcus", lastName: "Kruzan", position: "P", eligibility: "JR", homeState: "MN", hometown: "Woodbury", jerseyNumber: 28,
      hitForAvg: 16, power: 13, speed: 37, arm: 59, fielding: 36, errorResistance: 51, velocity: 60, control: 56, stamina: 59, stuff: 56,
      clutch: 68, vsLHP: 66, grit: 69, stealing: 10, running: 37, throwing: 72, recovery: 52, wRISP: 51, vsLefty: 52, poise: 53, heater: 60, agile: 46,
      abilities: ["Guts", "Sharpness", "Good Pickoff", "Pace"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Adam", lastName: "Urban", position: "P", eligibility: "SO", homeState: "MN", hometown: "Lakeville", jerseyNumber: 42,
      hitForAvg: 8, power: 7, speed: 24, arm: 23, fielding: 14, errorResistance: 24, velocity: 33, control: 22, stamina: 22, stuff: 24,
      clutch: 30, vsLHP: 29, grit: 30, stealing: 7, running: 20, throwing: 35, recovery: 20, wRISP: 18, vsLefty: 20, poise: 20, heater: 24, agile: 24,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Isaac", lastName: "Morton", position: "P", eligibility: "JR", homeState: "IA", hometown: "Cedar Rapids", jerseyNumber: 40,
      hitForAvg: 10, power: 8, speed: 28, arm: 25, fielding: 16, errorResistance: 25, velocity: 34, control: 24, stamina: 24, stuff: 28,
      clutch: 32, vsLHP: 31, grit: 35, stealing: 6, running: 18, throwing: 37, recovery: 21, wRISP: 21, vsLefty: 21, poise: 22, heater: 26, agile: 22,
      abilities: ["Guts"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Ben", lastName: "Gregory", position: "P", eligibility: "JR", homeState: "WI", hometown: "Madison", jerseyNumber: 46,
      hitForAvg: 10, power: 5, speed: 27, arm: 25, fielding: 15, errorResistance: 26, velocity: 34, control: 24, stamina: 24, stuff: 27,
      clutch: 33, vsLHP: 32, grit: 34, stealing: 5, running: 19, throwing: 38, recovery: 21, wRISP: 21, vsLefty: 21, poise: 21, heater: 26, agile: 25,
      abilities: ["Explosive Fastball"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Ethan", lastName: "Felling", position: "P", eligibility: "FR", homeState: "MN", hometown: "St. Cloud", jerseyNumber: 36,
      hitForAvg: 9, power: 5, speed: 27, arm: 36, fielding: 16, errorResistance: 27, velocity: 44, control: 31, stamina: 30, stuff: 35,
      clutch: 28, vsLHP: 28, grit: 30, stealing: 8, running: 24, throwing: 38, recovery: 18, wRISP: 17, vsLefty: 18, poise: 18, heater: 27, agile: 27,
      abilities: ["Houdini", "Intimidator"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Eli", lastName: "Kokenge", position: "P", eligibility: "FR", homeState: "MN", hometown: "Prior Lake", jerseyNumber: 48,
      hitForAvg: 12, power: 8, speed: 31, arm: 36, fielding: 21, errorResistance: 34, velocity: 47, control: 32, stamina: 31, stuff: 34,
      clutch: 40, vsLHP: 36, grit: 40, stealing: 10, running: 30, throwing: 50, recovery: 28, wRISP: 26, vsLefty: 28, poise: 28, heater: 40, agile: 35,
      abilities: ["Inside Pitch", "True Slider"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    { firstName: "Zach", lastName: "Trettin", position: "2B", eligibility: "FR", homeState: "MN", hometown: "Rosemount", jerseyNumber: 50,
      hitForAvg: 48, power: 34, speed: 53, arm: 40, fielding: 27, errorResistance: 28, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 29, vsLHP: 28, grit: 29, stealing: 7, running: 25, throwing: 39, recovery: 29, wRISP: 28, vsLefty: 29, poise: 29, heater: 0, agile: 28,
      abilities: ["Contact Hitter", "Hit Machine", "Error Prone"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Tristan", lastName: "Moore", position: "3B", eligibility: "FR", homeState: "MN", hometown: "Eagan", jerseyNumber: 44,
      hitForAvg: 42, power: 30, speed: 49, arm: 45, fielding: 27, errorResistance: 28, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 31, grit: 33, stealing: 8, running: 27, throwing: 44, recovery: 32, wRISP: 31, vsLefty: 32, poise: 32, heater: 0, agile: 31,
      abilities: ["Contact Hitter", "Artist"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // CATCHERS (2)
    { firstName: "Weber", lastName: "Neels", position: "C", eligibility: "SR", homeState: "MN", hometown: "Maple Grove", jerseyNumber: 6,
      hitForAvg: 55, power: 54, speed: 32, arm: 50, fielding: 48, errorResistance: 47, velocity: 0, control: 0, stamina: 25, stuff: 0,
      clutch: 50, vsLHP: 47, grit: 51, stealing: 12, running: 26, throwing: 51, recovery: 40, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 30,
      abilities: ["Defensive Artisan", "Power Hitter", "High-Speed Laser"], potential: "A-", catcherAbility: 46,
      throwHand: "R", batHand: "S",
      ...noPitches },
    { firstName: "Tyler", lastName: "Albrecht", position: "C", eligibility: "SO", homeState: "MN", hometown: "Plymouth", jerseyNumber: 18,
      hitForAvg: 38, power: 32, speed: 32, arm: 40, fielding: 38, errorResistance: 36, velocity: 0, control: 0, stamina: 22, stuff: 0,
      clutch: 32, vsLHP: 31, grit: 34, stealing: 8, running: 24, throwing: 42, recovery: 30, wRISP: 32, vsLefty: 30, poise: 32, heater: 0, agile: 26,
      abilities: ["Batter Intimidator", "Outside Hitter", "Contact Hitter"], potential: "B", catcherAbility: 37,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // INFIELDERS (5)
    { firstName: "Charlie", lastName: "Sutherland", position: "SS", eligibility: "JR", homeState: "MN", hometown: "Eden Prairie", jerseyNumber: 2,
      hitForAvg: 49, power: 38, speed: 60, arm: 45, fielding: 47, errorResistance: 45, velocity: 0, control: 0, stamina: 23, stuff: 0,
      clutch: 41, vsLHP: 38, grit: 43, stealing: 28, running: 38, throwing: 47, recovery: 33, wRISP: 39, vsLefty: 37, poise: 41, heater: 0, agile: 43,
      abilities: ["Defensive Artisan", "Chance Maker"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Sam", lastName: "Marek", position: "2B", eligibility: "JR", homeState: "IL", hometown: "Naperville", jerseyNumber: 10,
      hitForAvg: 49, power: 38, speed: 62, arm: 41, fielding: 44, errorResistance: 43, velocity: 0, control: 0, stamina: 24, stuff: 0,
      clutch: 41, vsLHP: 38, grit: 43, stealing: 24, running: 36, throwing: 43, recovery: 35, wRISP: 39, vsLefty: 37, poise: 41, heater: 0, agile: 38,
      abilities: ["Chance Maker"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...noPitches },
    { firstName: "Luke", lastName: "Ryerse", position: "1B", eligibility: "JR", homeState: "IN", hometown: "Carmel", jerseyNumber: 24,
      hitForAvg: 41, power: 40, speed: 46, arm: 33, fielding: 35, errorResistance: 33, velocity: 0, control: 0, stamina: 18, stuff: 0,
      clutch: 35, vsLHP: 32, grit: 35, stealing: 8, running: 21, throwing: 35, recovery: 28, wRISP: 35, vsLefty: 30, poise: 35, heater: 0, agile: 23,
      abilities: ["Power Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Jake", lastName: "Doskow", position: "3B", eligibility: "JR", homeState: "MN", hometown: "Burnsville", jerseyNumber: 5,
      hitForAvg: 81, power: 76, speed: 74, arm: 80, fielding: 76, errorResistance: 72, velocity: 0, control: 0, stamina: 42, stuff: 0,
      clutch: 71, vsLHP: 66, grit: 72, stealing: 24, running: 53, throwing: 81, recovery: 62, wRISP: 67, vsLefty: 63, poise: 71, heater: 0, agile: 60,
      abilities: ["Outside Hitter", "Contact Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Nathan", lastName: "O'Donnell", position: "SS", eligibility: "FR", homeState: "MN", hometown: "Edina", jerseyNumber: 14,
      hitForAvg: 41, power: 34, speed: 68, arm: 48, fielding: 43, errorResistance: 38, velocity: 0, control: 0, stamina: 23, stuff: 0,
      clutch: 33, vsLHP: 32, grit: 33, stealing: 27, running: 44, throwing: 49, recovery: 32, wRISP: 32, vsLefty: 29, poise: 33, heater: 0, agile: 48,
      abilities: ["Contact Hitter", "Express Baserunning", "Push"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Easton", lastName: "Richter", position: "OF", eligibility: "JR", homeState: "MN", hometown: "Owatonna", jerseyNumber: 7,
      hitForAvg: 54, power: 92, speed: 63, arm: 45, fielding: 44, errorResistance: 42, velocity: 0, control: 0, stamina: 24, stuff: 0,
      clutch: 47, vsLHP: 44, grit: 48, stealing: 28, running: 39, throwing: 47, recovery: 38, wRISP: 45, vsLefty: 42, poise: 47, heater: 0, agile: 41,
      abilities: ["Power Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Jack", lastName: "Spanier", position: "OF", eligibility: "JR", homeState: "MN", hometown: "Stillwater", jerseyNumber: 9,
      hitForAvg: 46, power: 40, speed: 54, arm: 40, fielding: 39, errorResistance: 37, velocity: 0, control: 0, stamina: 22, stuff: 0,
      clutch: 37, vsLHP: 34, grit: 39, stealing: 26, running: 37, throwing: 41, recovery: 31, wRISP: 37, vsLefty: 33, poise: 37, heater: 0, agile: 39,
      abilities: ["Express Baserunning"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Ryan", lastName: "Dardis", position: "OF", eligibility: "JR", homeState: "MN", hometown: "Bloomington", jerseyNumber: 1,
      hitForAvg: 42, power: 38, speed: 48, arm: 38, fielding: 36, errorResistance: 35, velocity: 0, control: 0, stamina: 21, stuff: 0,
      clutch: 36, vsLHP: 34, grit: 37, stealing: 25, running: 35, throwing: 39, recovery: 31, wRISP: 35, vsLefty: 32, poise: 36, heater: 0, agile: 37,
      abilities: ["High-Speed Laser"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Cade", lastName: "Anderson", position: "OF", eligibility: "SO", homeState: "MN", hometown: "Duluth", jerseyNumber: 11,
      hitForAvg: 29, power: 25, speed: 41, arm: 29, fielding: 25, errorResistance: 25, velocity: 0, control: 0, stamina: 15, stuff: 0,
      clutch: 24, vsLHP: 22, grit: 25, stealing: 18, running: 26, throwing: 29, recovery: 22, wRISP: 23, vsLefty: 22, poise: 24, heater: 0, agile: 29,
      abilities: ["Tough Out", "Double Play"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Drew", lastName: "Hilliard", position: "OF", eligibility: "JR", homeState: "WI", hometown: "Waukesha", jerseyNumber: 20,
      hitForAvg: 55, power: 50, speed: 56, arm: 49, fielding: 46, errorResistance: 45, velocity: 0, control: 0, stamina: 28, stuff: 0,
      clutch: 46, vsLHP: 43, grit: 49, stealing: 29, running: 41, throwing: 50, recovery: 40, wRISP: 45, vsLefty: 41, poise: 46, heater: 0, agile: 45,
      abilities: ["Contact Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Brady", lastName: "Wilson", position: "OF", eligibility: "SO", homeState: "MN", hometown: "Mankato", jerseyNumber: 26,
      hitForAvg: 33, power: 28, speed: 49, arm: 33, fielding: 28, errorResistance: 28, velocity: 0, control: 0, stamina: 16, stuff: 0,
      clutch: 26, vsLHP: 24, grit: 28, stealing: 20, running: 29, throwing: 32, recovery: 23, wRISP: 24, vsLefty: 23, poise: 26, heater: 0, agile: 31,
      abilities: ["Good Infield Hit", "Ace Killer"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
  ],

  "Nebraska": [
      // 33-11/12-3 B1G, peaked top 25, Will Bolt. 11-game W streak, swept back-to-back B1G series.
      // PITCHERS (10) — 1-8 pitch scale
      // Ty Horn — Friday JR RHP, started Oregon series opener — TEAM ELITE STUFF
      { firstName: "Ty", lastName: "Horn", position: "P", eligibility: "JR", homeState: "NE", hometown: "Omaha", jerseyNumber: 17,
        hitForAvg: 20, power: 15, speed: 43, arm: 84, fielding: 53, errorResistance: 69, velocity: 89, control: 84, stamina: 84, stuff: 90,
        clutch: 99, vsLHP: 90, grit: 99, stealing: 13, running: 46, throwing: 99, recovery: 73, wRISP: 79, vsLefty: 79, poise: 84, heater: 88, agile: 57,
        abilities: ["Star of Victory", "Strong Starter", "Intimidator", "Low Ball", "Heavy Ball"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 7, 6, 1, 0, 0, 0]) },
      // Carson Jasa — SO RHP, weekend rotation
      { firstName: "Carson", lastName: "Jasa", position: "P", eligibility: "FR", homeState: "NE", hometown: "Elkhorn", jerseyNumber: 31,
        hitForAvg: 11, power: 9, speed: 27, arm: 46, fielding: 28, errorResistance: 36, velocity: 50, control: 41, stamina: 38, stuff: 45,
        clutch: 50, vsLHP: 46, grit: 51, stealing: 8, running: 27, throwing: 57, recovery: 34, wRISP: 35, vsLefty: 37, poise: 38, heater: 49, agile: 32,
        abilities: ["Explosive Fastball", "Strong Starter"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 7, 5, 1, 0, 0, 0]) },
      // Cooper Katskee — JR RHP rotation
      { firstName: "Cooper", lastName: "Katskee", position: "P", eligibility: "JR", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 28,
        hitForAvg: 17, power: 14, speed: 37, arm: 63, fielding: 39, errorResistance: 53, velocity: 68, control: 62, stamina: 63, stuff: 60,
        clutch: 73, vsLHP: 69, grit: 77, stealing: 11, running: 37, throwing: 78, recovery: 53, wRISP: 53, vsLefty: 56, poise: 60, heater: 68, agile: 46,
        abilities: ["Strong Starter", "Guts", "Slugger Killer"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 6, 1, 0, 0, 0]) },
      // Shea Wendt — JR RHP, team-leading 14 G, 3.58 ERA
      { firstName: "Shea", lastName: "Wendt", position: "P", eligibility: "JR", homeState: "NE", hometown: "Blair", jerseyNumber: 33,
        hitForAvg: 10, power: 8, speed: 25, arm: 40, fielding: 25, errorResistance: 34, velocity: 42, control: 40, stamina: 29, stuff: 38,
        clutch: 54, vsLHP: 49, grit: 51, stealing: 7, running: 25, throwing: 51, recovery: 33, wRISP: 37, vsLefty: 35, poise: 40, heater: 41, agile: 31,
        abilities: ["Fireman", "Inside Pitch", "Poker Face"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
      // Jimmy Burke — R-SR RHP, 26 K (2nd among RPs), 4.44 ERA in 26.1 IP
      { firstName: "Jimmy", lastName: "Burke", position: "P", eligibility: "SR", homeState: "NE", hometown: "Lincoln", jerseyNumber: 39,
        hitForAvg: 10, power: 8, speed: 25, arm: 41, fielding: 25, errorResistance: 34, velocity: 43, control: 39, stamina: 30, stuff: 39,
        clutch: 49, vsLHP: 46, grit: 51, stealing: 6, running: 23, throwing: 51, recovery: 31, wRISP: 36, vsLefty: 36, poise: 39, heater: 42, agile: 30,
        abilities: ["Fireman", "Doctor K"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 0, 1, 0, 4, 0]) },
      // Kevin Mannell — JR RHP
      { firstName: "Kevin", lastName: "Mannell", position: "P", eligibility: "JR", homeState: "MS", hometown: "Brandon", jerseyNumber: 35,
        hitForAvg: 12, power: 9, speed: 26, arm: 40, fielding: 25, errorResistance: 35, velocity: 43, control: 39, stamina: 37, stuff: 37,
        clutch: 46, vsLHP: 45, grit: 48, stealing: 7, running: 25, throwing: 51, recovery: 34, wRISP: 34, vsLefty: 35, poise: 36, heater: 41, agile: 31,
        abilities: ["Sharpness", "Guts"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
      // Jalen Worthley — SR RHP RP
      { firstName: "Jalen", lastName: "Worthley", position: "P", eligibility: "SR", homeState: "NE", hometown: "Bellevue", jerseyNumber: 38,
        hitForAvg: 16, power: 14, speed: 39, arm: 64, fielding: 43, errorResistance: 57, velocity: 68, control: 64, stamina: 56, stuff: 61,
        clutch: 80, vsLHP: 75, grit: 83, stealing: 11, running: 41, throwing: 80, recovery: 56, wRISP: 60, vsLefty: 60, poise: 63, heater: 67, agile: 48,
        abilities: ["Fireman", "Guts", "Doctor K", "Inside Pitch"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 0, 1, 4, 0, 0]) },
      // Cooper Timmerman — JR RHP
      { firstName: "Cooper", lastName: "Timmerman", position: "P", eligibility: "JR", homeState: "NE", hometown: "Lincoln", jerseyNumber: 22,
        hitForAvg: 11, power: 8, speed: 27, arm: 30, fielding: 19, errorResistance: 30, velocity: 27, control: 35, stamina: 29, stuff: 26,
        clutch: 37, vsLHP: 35, grit: 38, stealing: 5, running: 21, throwing: 40, recovery: 26, wRISP: 26, vsLefty: 26, poise: 26, heater: 30, agile: 25,
        abilities: ["Strong Starter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
      // J.D. Hennen — JR RHP
      { firstName: "J.D.", lastName: "Hennen", position: "P", eligibility: "JR", homeState: "MN", hometown: "Shakopee", jerseyNumber: 40,
        hitForAvg: 9, power: 6, speed: 24, arm: 26, fielding: 17, errorResistance: 26, velocity: 28, control: 31, stamina: 26, stuff: 24,
        clutch: 34, vsLHP: 31, grit: 36, stealing: 5, running: 20, throwing: 37, recovery: 22, wRISP: 22, vsLefty: 22, poise: 25, heater: 28, agile: 23,
        abilities: ["Guts"], potential: "B", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
      // Brady Hansen — FR RHP — PG HM / Top-500 national
      { firstName: "Brady", lastName: "Hansen", position: "P", eligibility: "FR", homeState: "NE", hometown: "Grand Island", jerseyNumber: 46,
        hitForAvg: 8, power: 5, speed: 23, arm: 31, fielding: 14, errorResistance: 23, velocity: 39, control: 26, stamina: 25, stuff: 31,
        clutch: 24, vsLHP: 23, grit: 25, stealing: 6, running: 20, throwing: 31, recovery: 14, wRISP: 14, vsLefty: 14, poise: 14, heater: 23, agile: 23,
        abilities: ["Lefty Killer", "Intimidator"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
      // CATCHERS (2)
      // Tyler Nolan — SO C
      { firstName: "Tyler", lastName: "Nolan", position: "C", eligibility: "SO", homeState: "NE", hometown: "Papillion", jerseyNumber: 18,
        hitForAvg: 38, power: 30, speed: 29, arm: 38, fielding: 34, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 29, vsLHP: 27, grit: 29, stealing: 9, running: 19, throwing: 38, recovery: 27, wRISP: 29, vsLefty: 27, poise: 29, heater: 0, agile: 24,
        abilities: ["Counterattack", "Bad Mood"], potential: "B+", catcherAbility: 34,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Jeter Worthley — FR C
      { firstName: "Jeter", lastName: "Worthley", position: "C", eligibility: "FR", homeState: "NE", hometown: "Bellevue", jerseyNumber: 12,
        hitForAvg: 38, power: 32, speed: 34, arm: 40, fielding: 38, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 29, vsLHP: 24, grit: 29, stealing: 9, running: 22, throwing: 40, recovery: 27, wRISP: 27, vsLefty: 24, poise: 29, heater: 0, agile: 24,
        abilities: ["Chance Maker"], potential: "A-", catcherAbility: 36,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // INFIELDERS (7)
      // Nico Newhan — 2B JR — TEAM ELITE HIT
      { firstName: "Nico", lastName: "Newhan", position: "2B", eligibility: "JR", homeState: "CA", hometown: "El Cajon", jerseyNumber: 8,
        hitForAvg: 83, power: 69, speed: 67, arm: 55, fielding: 55, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 78, vsLHP: 74, grit: 78, stealing: 29, running: 45, throwing: 55, recovery: 45, wRISP: 78, vsLefty: 74, poise: 78, heater: 0, agile: 49,
        abilities: ["Hit Machine", "Contact Hitter", "Power Hitter", "Consigliere"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Case Sanderson — 1B JR, 2-RBI single key contributor
      { firstName: "Case", lastName: "Sanderson", position: "1B", eligibility: "JR", homeState: "NE", hometown: "Hastings", jerseyNumber: 24,
        hitForAvg: 67, power: 67, speed: 48, arm: 47, fielding: 47, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 61, vsLHP: 56, grit: 61, stealing: 12, running: 31, throwing: 47, recovery: 41, wRISP: 61, vsLefty: 56, poise: 61, heater: 0, agile: 34,
        abilities: ["Artist", "Power Hitter", "Contact Hitter"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Dylan Carey — SS SR, RBI single Oregon series
      { firstName: "Dylan", lastName: "Carey", position: "SS", eligibility: "SR", homeState: "NE", hometown: "Omaha", jerseyNumber: 2,
        hitForAvg: 69, power: 93, speed: 75, arm: 61, fielding: 66, errorResistance: 61, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 88, vsLHP: 59, grit: 66, stealing: 39, running: 52, throwing: 61, recovery: 48, wRISP: 61, vsLefty: 54, poise: 66, heater: 0, agile: 54,
        abilities: ["Defensive Artisan", "Chance Maker"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "S",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Josh Overbeek — 3B SR
      { firstName: "Josh", lastName: "Overbeek", position: "3B", eligibility: "SR", homeState: "NE", hometown: "Lincoln", jerseyNumber: 5,
        hitForAvg: 54, power: 49, speed: 47, arm: 46, fielding: 45, errorResistance: 43, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 48, vsLHP: 45, grit: 48, stealing: 11, running: 31, throwing: 48, recovery: 36, wRISP: 48, vsLefty: 43, poise: 48, heater: 0, agile: 32,
        abilities: ["Consigliere", "Power Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Jett Buck — 2B SR
      { firstName: "Jett", lastName: "Buck", position: "2B", eligibility: "SR", homeState: "CA", hometown: "San Diego", jerseyNumber: 3,
        hitForAvg: 50, power: 50, speed: 58, arm: 39, fielding: 39, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 44, vsLHP: 42, grit: 44, stealing: 21, running: 32, throwing: 39, recovery: 34, wRISP: 44, vsLefty: 40, poise: 44, heater: 0, agile: 34,
        abilities: ["Power Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Marcus Young — 3B SO
      { firstName: "Marcus", lastName: "Young", position: "3B", eligibility: "SO", homeState: "NE", hometown: "North Platte", jerseyNumber: 16,
        hitForAvg: 40, power: 35, speed: 41, arm: 40, fielding: 37, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 32, vsLHP: 30, grit: 32, stealing: 17, running: 30, throwing: 42, recovery: 29, wRISP: 32, vsLefty: 29, poise: 32, heater: 0, agile: 32,
        abilities: ["Defensive Artisan", "God of Pinch Hitting"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Luke Tillman — SS FR
      { firstName: "Luke", lastName: "Tillman", position: "SS", eligibility: "FR", homeState: "NE", hometown: "Gretna", jerseyNumber: 14,
        hitForAvg: 33, power: 24, speed: 54, arm: 33, fielding: 25, errorResistance: 24, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 21, vsLHP: 20, grit: 23, stealing: 18, running: 28, throwing: 31, recovery: 20, wRISP: 20, vsLefty: 18, poise: 21, heater: 0, agile: 28,
        abilities: ["vs. Ace"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // OUTFIELDERS (6)
      // Mac Moyer — OF, equalizing solo HR vs Oregon
      { firstName: "Mac", lastName: "Moyer", position: "OF", eligibility: "JR", homeState: "NE", hometown: "Omaha", jerseyNumber: 6,
        hitForAvg: 62, power: 62, speed: 57, arm: 50, fielding: 49, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 65, vsLHP: 51, grit: 56, stealing: 23, running: 41, throwing: 51, recovery: 41, wRISP: 65, vsLefty: 51, poise: 56, heater: 0, agile: 43,
        abilities: ["Power Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Cole Kitchens — OF JR
      { firstName: "Cole", lastName: "Kitchens", position: "OF", eligibility: "JR", homeState: "GA", hometown: "Alpharetta", jerseyNumber: 9,
        hitForAvg: 55, power: 50, speed: 49, arm: 40, fielding: 37, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 50, vsLHP: 45, grit: 50, stealing: 12, running: 30, throwing: 40, recovery: 37, wRISP: 50, vsLefty: 45, poise: 50, heater: 0, agile: 32,
        abilities: ["Consigliere", "Contact Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Trey Buettenback — OF JR
      { firstName: "Trey", lastName: "Buettenback", position: "OF", eligibility: "JR", homeState: "NE", hometown: "Columbus", jerseyNumber: 7,
        hitForAvg: 48, power: 43, speed: 50, arm: 46, fielding: 41, errorResistance: 39, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 43, vsLHP: 39, grit: 44, stealing: 25, running: 38, throwing: 46, recovery: 35, wRISP: 41, vsLefty: 38, poise: 43, heater: 0, agile: 39,
        abilities: ["High-Speed Laser"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Devin Nunez — OF SO
      { firstName: "Devin", lastName: "Nunez", position: "OF", eligibility: "SO", homeState: "CA", hometown: "Corona", jerseyNumber: 1,
        hitForAvg: 40, power: 32, speed: 44, arm: 33, fielding: 31, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 33, vsLHP: 31, grit: 34, stealing: 23, running: 33, throwing: 33, recovery: 25, wRISP: 31, vsLefty: 30, poise: 33, heater: 0, agile: 35,
        abilities: ["Express Baserunning", "Contact Hitter"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Preston Freeman — OF JR
      { firstName: "Preston", lastName: "Freeman", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Jacksonville", jerseyNumber: 20,
        hitForAvg: 38, power: 35, speed: 45, arm: 35, fielding: 32, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 32, vsLHP: 31, grit: 32, stealing: 21, running: 32, throwing: 35, recovery: 26, wRISP: 31, vsLefty: 29, poise: 32, heater: 0, agile: 34,
        abilities: ["Express Baserunning"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Ryan Metzger — OF FR
      { firstName: "Ryan", lastName: "Metzger", position: "OF", eligibility: "FR", homeState: "NE", hometown: "La Vista", jerseyNumber: 26,
        hitForAvg: 31, power: 27, speed: 48, arm: 35, fielding: 30, errorResistance: 27, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 23, vsLHP: 22, grit: 26, stealing: 22, running: 35, throwing: 36, recovery: 22, wRISP: 22, vsLefty: 22, poise: 23, heater: 0, agile: 38,
        abilities: ["Push"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
    ],

  "Northwestern": [
    // PITCHERS (10)
    { firstName: "Sam", lastName: "Hliboki", position: "P", eligibility: "SR", homeState: "LA", hometown: "Baton Rouge", jerseyNumber: 31,
      hitForAvg: 29, power: 23, speed: 43, arm: 87, fielding: 56, errorResistance: 70, velocity: 87, control: 82, stamina: 85, stuff: 85,
      clutch: 99, vsLHP: 95, grit: 99, stealing: 13, running: 46, throwing: 99, recovery: 78, wRISP: 81, vsLefty: 81, poise: 85, heater: 88, agile: 59,
      abilities: ["Star of Victory", "Strong Starter", "Sharpness", "Intimidator", "Heavy Ball", "Bad Ball Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 8, 6, 1, 0, 0, 0]) },
    { firstName: "Garrett", lastName: "Shearer", position: "P", eligibility: "JR", homeState: "IL", hometown: "Lake Forest", jerseyNumber: 22,
      hitForAvg: 15, power: 10, speed: 29, arm: 45, fielding: 27, errorResistance: 37, velocity: 47, control: 43, stamina: 43, stuff: 41,
      clutch: 54, vsLHP: 52, grit: 55, stealing: 8, running: 27, throwing: 56, recovery: 39, wRISP: 39, vsLefty: 39, poise: 41, heater: 45, agile: 33,
      abilities: ["Strong Starter", "Guts"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 6, 6, 1, 0, 0, 0]) },
    { firstName: "Matt", lastName: "Kouser", position: "P", eligibility: "SO", homeState: "IL", hometown: "Glenview", jerseyNumber: 35,
      hitForAvg: 11, power: 9, speed: 28, arm: 38, fielding: 24, errorResistance: 34, velocity: 44, control: 37, stamina: 37, stuff: 36,
      clutch: 44, vsLHP: 41, grit: 45, stealing: 9, running: 28, throwing: 51, recovery: 32, wRISP: 30, vsLefty: 32, poise: 33, heater: 41, agile: 33,
      abilities: ["Explosive Fastball", "Intimidator", "Release"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Weaver", position: "P", eligibility: "SR", homeState: "IL", hometown: "Barrington", jerseyNumber: 38,
      hitForAvg: 18, power: 14, speed: 32, arm: 52, fielding: 35, errorResistance: 47, velocity: 56, control: 51, stamina: 51, stuff: 49,
      clutch: 65, vsLHP: 60, grit: 67, stealing: 9, running: 32, throwing: 67, recovery: 47, wRISP: 49, vsLefty: 49, poise: 51, heater: 55, agile: 40,
      abilities: ["Guts", "Strong Finisher", "Intimidator"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 0, 1, 4, 0, 0]) },
    { firstName: "Dylan", lastName: "Carmody", position: "P", eligibility: "JR", homeState: "IL", hometown: "Hinsdale", jerseyNumber: 28,
      hitForAvg: 13, power: 9, speed: 31, arm: 45, fielding: 28, errorResistance: 39, velocity: 49, control: 43, stamina: 45, stuff: 41,
      clutch: 52, vsLHP: 50, grit: 55, stealing: 8, running: 30, throwing: 58, recovery: 38, wRISP: 38, vsLefty: 38, poise: 41, heater: 47, agile: 37,
      abilities: ["Strikeout", "vs. Strong Batters", "Flyball Pitcher"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Ben", lastName: "Williams", position: "P", eligibility: "SO", homeState: "IL", hometown: "Naperville", jerseyNumber: 42,
      hitForAvg: 10, power: 7, speed: 29, arm: 27, fielding: 18, errorResistance: 28, velocity: 39, control: 25, stamina: 25, stuff: 28,
      clutch: 35, vsLHP: 33, grit: 35, stealing: 7, running: 23, throwing: 40, recovery: 22, wRISP: 22, vsLefty: 22, poise: 22, heater: 29, agile: 28,
      abilities: ["Low Ball"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    { firstName: "Kyle", lastName: "Porter", position: "P", eligibility: "JR", homeState: "IL", hometown: "Winnetka", jerseyNumber: 40,
      hitForAvg: 7, power: 6, speed: 23, arm: 21, fielding: 13, errorResistance: 22, velocity: 31, control: 20, stamina: 20, stuff: 23,
      clutch: 28, vsLHP: 27, grit: 31, stealing: 5, running: 16, throwing: 32, recovery: 17, wRISP: 17, vsLefty: 17, poise: 19, heater: 22, agile: 20,
      abilities: ["Fireman"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 4, 0, 4, 0, 0]) },
    { firstName: "Tyler", lastName: "Chadwick", position: "P", eligibility: "SO", homeState: "IL", hometown: "Wilmette", jerseyNumber: 46,
      hitForAvg: 9, power: 8, speed: 26, arm: 28, fielding: 18, errorResistance: 28, velocity: 28, control: 24, stamina: 24, stuff: 25,
      clutch: 33, vsLHP: 32, grit: 34, stealing: 8, running: 24, throwing: 40, recovery: 23, wRISP: 22, vsLefty: 23, poise: 23, heater: 30, agile: 29,
      abilities: ["Gas Tank", "Intimidator"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    { firstName: "Owen", lastName: "Mitchell", position: "P", eligibility: "FR", homeState: "IL", hometown: "Park Ridge", jerseyNumber: 48,
      hitForAvg: 10, power: 6, speed: 29, arm: 42, fielding: 20, errorResistance: 30, velocity: 47, control: 37, stamina: 37, stuff: 38,
      clutch: 35, vsLHP: 33, grit: 36, stealing: 9, running: 27, throwing: 45, recovery: 24, wRISP: 22, vsLefty: 24, poise: 24, heater: 34, agile: 31,
      abilities: ["Fighting Spirit", "Tunneling"], potential: "A", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    { firstName: "Drew", lastName: "Parker", position: "P", eligibility: "FR", homeState: "IN", hometown: "Carmel", jerseyNumber: 50,
      hitForAvg: 9, power: 5, speed: 29, arm: 24, fielding: 15, errorResistance: 27, velocity: 36, control: 22, stamina: 21, stuff: 28,
      clutch: 30, vsLHP: 29, grit: 30, stealing: 6, running: 24, throwing: 38, recovery: 18, wRISP: 17, vsLefty: 18, poise: 18, heater: 26, agile: 28,
      abilities: ["Perfect Combustion"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Matt", lastName: "Johnson", position: "C", eligibility: "JR", homeState: "IL", hometown: "Evanston", jerseyNumber: 12,
      hitForAvg: 36, power: 31, speed: 26, arm: 37, fielding: 36, errorResistance: 35, velocity: 0, control: 0, stamina: 18, stuff: 0,
      clutch: 31, vsLHP: 30, grit: 33, stealing: 8, running: 19, throwing: 38, recovery: 27, wRISP: 31, vsLefty: 28, poise: 31, heater: 0, agile: 22,
      abilities: ["Defensive Artisan"], potential: "B", catcherAbility: 33,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Tyler", lastName: "Bennett", position: "C", eligibility: "SO", homeState: "WI", hometown: "Milwaukee", jerseyNumber: 18,
      hitForAvg: 35, power: 31, speed: 30, arm: 38, fielding: 35, errorResistance: 33, velocity: 0, control: 0, stamina: 21, stuff: 0,
      clutch: 31, vsLHP: 29, grit: 32, stealing: 9, running: 23, throwing: 39, recovery: 27, wRISP: 30, vsLefty: 27, poise: 30, heater: 0, agile: 25,
      abilities: ["Locked and Loaded"], potential: "B", catcherAbility: 35,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Ryan", lastName: "Kucherak", position: "SS", eligibility: "JR", homeState: "IL", hometown: "Libertyville", jerseyNumber: 2,
      hitForAvg: 43, power: 43, speed: 56, arm: 37, fielding: 37, errorResistance: 35, velocity: 0, control: 0, stamina: 19, stuff: 0,
      clutch: 38, vsLHP: 35, grit: 39, stealing: 20, running: 28, throwing: 38, recovery: 28, wRISP: 38, vsLefty: 35, poise: 38, heater: 0, agile: 32,
      abilities: ["Power Hitter", "Defensive Artisan", "Consigliere"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Owen", lastName: "McElfatrick", position: "3B", eligibility: "SR", homeState: "IL", hometown: "Deerfield", jerseyNumber: 5,
      hitForAvg: 53, power: 48, speed: 49, arm: 47, fielding: 47, errorResistance: 46, velocity: 0, control: 0, stamina: 27, stuff: 0,
      clutch: 47, vsLHP: 44, grit: 48, stealing: 15, running: 33, throwing: 48, recovery: 39, wRISP: 46, vsLefty: 43, poise: 47, heater: 0, agile: 36,
      abilities: ["Contact Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...noPitches },
    { firstName: "Noah", lastName: "Ruiz", position: "1B", eligibility: "SR", homeState: "CA", hometown: "La Mirada", jerseyNumber: 24,
      hitForAvg: 84, power: 85, speed: 68, arm: 64, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 40, stuff: 0,
      clutch: 75, vsLHP: 70, grit: 77, stealing: 15, running: 43, throwing: 66, recovery: 59, wRISP: 75, vsLefty: 69, poise: 75, heater: 0, agile: 48,
      abilities: ["Power Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Nick", lastName: "Barron", position: "2B", eligibility: "JR", homeState: "IL", hometown: "Elmhurst", jerseyNumber: 10,
      hitForAvg: 44, power: 35, speed: 57, arm: 37, fielding: 40, errorResistance: 38, velocity: 0, control: 0, stamina: 21, stuff: 0,
      clutch: 35, vsLHP: 34, grit: 37, stealing: 23, running: 33, throwing: 38, recovery: 30, wRISP: 35, vsLefty: 33, poise: 35, heater: 0, agile: 35,
      abilities: ["Chance Maker"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...noPitches },
    { firstName: "Noah", lastName: "Brocklebank", position: "SS", eligibility: "FR", homeState: "IL", hometown: "Wheaton", jerseyNumber: 14,
      hitForAvg: 29, power: 23, speed: 49, arm: 29, fielding: 26, errorResistance: 24, velocity: 0, control: 0, stamina: 14, stuff: 0,
      clutch: 20, vsLHP: 19, grit: 21, stealing: 17, running: 26, throwing: 29, recovery: 19, wRISP: 19, vsLefty: 19, poise: 20, heater: 0, agile: 28,
      abilities: ["Slap Happy"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Drew", lastName: "Harrison", position: "2B", eligibility: "SO", homeState: "IL", hometown: "Highland Park", jerseyNumber: 16,
      hitForAvg: 36, power: 30, speed: 57, arm: 35, fielding: 34, errorResistance: 32, velocity: 0, control: 0, stamina: 19, stuff: 0,
      clutch: 30, vsLHP: 28, grit: 30, stealing: 20, running: 30, throwing: 35, recovery: 27, wRISP: 30, vsLefty: 27, poise: 30, heater: 0, agile: 32,
      abilities: ["Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    // OUTFIELDERS (5)
    { firstName: "Jack", lastName: "Lausch", position: "OF", eligibility: "SR", homeState: "IL", hometown: "Lake Forest", jerseyNumber: 1,
      hitForAvg: 74, power: 99, speed: 71, arm: 60, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 32, stuff: 0,
      clutch: 65, vsLHP: 61, grit: 67, stealing: 37, running: 53, throwing: 61, recovery: 51, wRISP: 65, vsLefty: 60, poise: 65, heater: 0, agile: 56,
      abilities: ["Power Hitter", "Consigliere", "High-Speed Laser"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...noPitches },
    { firstName: "Jackson", lastName: "Freeman", position: "OF", eligibility: "JR", homeState: "IL", hometown: "Northbrook", jerseyNumber: 7,
      hitForAvg: 84, power: 72, speed: 84, arm: 74, fielding: 71, errorResistance: 68, velocity: 0, control: 0, stamina: 38, stuff: 0,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 50, running: 68, throwing: 77, recovery: 60, wRISP: 71, vsLefty: 67, poise: 72, heater: 0, agile: 72,
      abilities: ["Express Baserunning", "Contact Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Jay", lastName: "Slater", position: "OF", eligibility: "JR", homeState: "IL", hometown: "Buffalo Grove", jerseyNumber: 9,
      hitForAvg: 49, power: 46, speed: 56, arm: 42, fielding: 39, errorResistance: 39, velocity: 0, control: 0, stamina: 24, stuff: 0,
      clutch: 43, vsLHP: 39, grit: 44, stealing: 19, running: 35, throwing: 43, recovery: 35, wRISP: 42, vsLefty: 39, poise: 43, heater: 0, agile: 37,
      abilities: ["Contact Hitter"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "S",
      ...noPitches },
    { firstName: "Jack", lastName: "Sullivan", position: "OF", eligibility: "FR", homeState: "WI", hometown: "Wauwatosa", jerseyNumber: 26,
      hitForAvg: 36, power: 27, speed: 52, arm: 36, fielding: 29, errorResistance: 25, velocity: 0, control: 0, stamina: 16, stuff: 0,
      clutch: 25, vsLHP: 23, grit: 25, stealing: 22, running: 34, throwing: 36, recovery: 23, wRISP: 23, vsLefty: 22, poise: 25, heater: 0, agile: 36,
      abilities: ["Milliner"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Tyler", lastName: "Walsh", position: "OF", eligibility: "FR", homeState: "OH", hometown: "Dublin", jerseyNumber: 30,
      hitForAvg: 31, power: 23, speed: 46, arm: 31, fielding: 26, errorResistance: 23, velocity: 0, control: 0, stamina: 15, stuff: 0,
      clutch: 21, vsLHP: 21, grit: 22, stealing: 19, running: 29, throwing: 32, recovery: 21, wRISP: 21, vsLefty: 19, poise: 21, heater: 0, agile: 33,
      abilities: ["Consigliere", "Gambler", "Double Play"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "S",
      ...noPitches },
    { firstName: "Luke", lastName: "Patterson", position: "OF", eligibility: "JR", homeState: "IL", hometown: "Oak Park", jerseyNumber: 20,
      hitForAvg: 56, power: 49, speed: 59, arm: 51, fielding: 49, errorResistance: 46, velocity: 0, control: 0, stamina: 27, stuff: 0,
      clutch: 46, vsLHP: 45, grit: 49, stealing: 31, running: 46, throwing: 53, recovery: 40, wRISP: 45, vsLefty: 42, poise: 46, heater: 0, agile: 50,
      abilities: ["Pressure Run"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Ryan", lastName: "Cooper", position: "2B", eligibility: "SO", homeState: "MI", hometown: "Ann Arbor", jerseyNumber: 11,
      hitForAvg: 57, power: 48, speed: 68, arm: 58, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 31, stuff: 0,
      clutch: 48, vsLHP: 44, grit: 50, stealing: 37, running: 52, throwing: 59, recovery: 42, wRISP: 47, vsLefty: 42, poise: 48, heater: 0, agile: 57,
      abilities: ["Storming Home"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
  ],

  "Ohio State": [
    // PITCHERS (10)
    { firstName: "Pierce", lastName: "Herrenbruck", position: "P", eligibility: "JR", homeState: "IN", hometown: "Fishers", jerseyNumber: 17,
      hitForAvg: 26, power: 21, speed: 45, arm: 88, fielding: 56, errorResistance: 71, velocity: 92, control: 84, stamina: 84, stuff: 85,
      clutch: 99, vsLHP: 95, grit: 99, stealing: 13, running: 47, throwing: 99, recovery: 77, wRISP: 79, vsLefty: 79, poise: 84, heater: 90, agile: 60,
      abilities: ["Star of Victory", "Strong Starter", "Sharpness", "Intimidator", "Heavy Ball", "Flyball Pitcher"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 7, 6, 1, 0, 0, 0]) },
    { firstName: "Caden", lastName: "Marcum", position: "P", eligibility: "JR", homeState: "KY", hometown: "Louisville", jerseyNumber: 31,
      hitForAvg: 18, power: 13, speed: 35, arm: 59, fielding: 36, errorResistance: 48, velocity: 67, control: 56, stamina: 56, stuff: 58,
      clutch: 68, vsLHP: 65, grit: 70, stealing: 9, running: 35, throwing: 71, recovery: 51, wRISP: 54, vsLefty: 54, poise: 56, heater: 62, agile: 41,
      abilities: ["Strong Starter", "Explosive Fastball", "Intimidator"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 7, 5, 1, 0, 0, 0]) },
    { firstName: "Gavin", lastName: "Grahovac", position: "P", eligibility: "SR", homeState: "OH", hometown: "Medina", jerseyNumber: 22,
      hitForAvg: 20, power: 15, speed: 36, arm: 55, fielding: 36, errorResistance: 50, velocity: 57, control: 55, stamina: 55, stuff: 51,
      clutch: 68, vsLHP: 65, grit: 71, stealing: 10, running: 34, throwing: 71, recovery: 51, wRISP: 51, vsLefty: 51, poise: 54, heater: 55, agile: 41,
      abilities: ["Guts", "Constant Speed"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Colin", lastName: "Monasmith", position: "P", eligibility: "JR", homeState: "OH", hometown: "Columbus", jerseyNumber: 38,
      hitForAvg: 20, power: 15, speed: 40, arm: 62, fielding: 41, errorResistance: 55, velocity: 65, control: 62, stamina: 49, stuff: 61,
      clutch: 77, vsLHP: 73, grit: 80, stealing: 11, running: 39, throwing: 80, recovery: 59, wRISP: 59, vsLefty: 59, poise: 62, heater: 65, agile: 48,
      abilities: ["Fireman", "Guts"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "R",
      ...pitchMix(1, [0, 6, 0, 1, 4, 0, 0]) },
    { firstName: "Tyler", lastName: "Kean", position: "P", eligibility: "SO", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 35,
      hitForAvg: 9, power: 5, speed: 24, arm: 21, fielding: 13, errorResistance: 22, velocity: 33, control: 21, stamina: 21, stuff: 24,
      clutch: 27, vsLHP: 27, grit: 28, stealing: 5, running: 18, throwing: 33, recovery: 17, wRISP: 16, vsLefty: 17, poise: 18, heater: 22, agile: 22,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Josh", lastName: "Romano", position: "P", eligibility: "JR", homeState: "OH", hometown: "Akron", jerseyNumber: 28,
      hitForAvg: 17, power: 13, speed: 38, arm: 57, fielding: 37, errorResistance: 50, velocity: 62, control: 54, stamina: 57, stuff: 54,
      clutch: 67, vsLHP: 64, grit: 69, stealing: 10, running: 37, throwing: 71, recovery: 51, wRISP: 49, vsLefty: 51, poise: 52, heater: 60, agile: 46,
      abilities: ["Guts", "Staredown", "Quick Hands", "Good Pickoff"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Dylan", lastName: "Ray", position: "P", eligibility: "SO", homeState: "OH", hometown: "Dayton", jerseyNumber: 42,
      hitForAvg: 8, power: 7, speed: 26, arm: 25, fielding: 17, errorResistance: 26, velocity: 37, control: 24, stamina: 24, stuff: 25,
      clutch: 32, vsLHP: 30, grit: 33, stealing: 7, running: 21, throwing: 38, recovery: 21, wRISP: 20, vsLefty: 21, poise: 21, heater: 26, agile: 26,
      abilities: ["Staredown"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    { firstName: "Will", lastName: "Morrison", position: "P", eligibility: "JR", homeState: "OH", hometown: "Westerville", jerseyNumber: 40,
      hitForAvg: 12, power: 10, speed: 29, arm: 30, fielding: 21, errorResistance: 30, velocity: 28, control: 37, stamina: 29, stuff: 28,
      clutch: 39, vsLHP: 38, grit: 41, stealing: 6, running: 23, throwing: 42, recovery: 26, wRISP: 26, vsLefty: 26, poise: 28, heater: 32, agile: 28,
      abilities: ["Winner's Luck", "Decisive", "Gear Change"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Jude", lastName: "Fisher", position: "P", eligibility: "FR", homeState: "OH", hometown: "Mason", jerseyNumber: 46,
      hitForAvg: 8, power: 6, speed: 24, arm: 33, fielding: 14, errorResistance: 23, velocity: 42, control: 28, stamina: 27, stuff: 33,
      clutch: 28, vsLHP: 26, grit: 28, stealing: 6, running: 20, throwing: 33, recovery: 17, wRISP: 17, vsLefty: 18, poise: 19, heater: 25, agile: 24,
      abilities: ["Explosive Fastball"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 6, 4, 1, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Stafford", position: "P", eligibility: "FR", homeState: "OH", hometown: "Dublin", jerseyNumber: 48,
      hitForAvg: 10, power: 7, speed: 27, arm: 31, fielding: 19, errorResistance: 29, velocity: 40, control: 28, stamina: 27, stuff: 29,
      clutch: 35, vsLHP: 33, grit: 36, stealing: 8, running: 27, throwing: 43, recovery: 23, wRISP: 22, vsLefty: 23, poise: 23, heater: 34, agile: 31,
      abilities: ["Miracle Sharpness", "Intimidator", "Bad Ball Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 3, 4, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Matt", lastName: "Graveline", position: "C", eligibility: "SR", homeState: "OH", hometown: "Cleveland", jerseyNumber: 12,
      hitForAvg: 52, power: 48, speed: 32, arm: 55, fielding: 53, errorResistance: 51, velocity: 0, control: 0, stamina: 27, stuff: 0,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 12, running: 28, throwing: 55, recovery: 42, wRISP: 47, vsLefty: 43, poise: 48, heater: 0, agile: 31,
      abilities: ["Defensive Artisan", "High-Speed Laser"], potential: "B+", catcherAbility: 50,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Jack", lastName: "Thompson", position: "C", eligibility: "SO", homeState: "OH", hometown: "Westlake", jerseyNumber: 18,
      hitForAvg: 35, power: 30, speed: 32, arm: 36, fielding: 35, errorResistance: 32, velocity: 0, control: 0, stamina: 19, stuff: 0,
      clutch: 30, vsLHP: 27, grit: 31, stealing: 8, running: 21, throwing: 38, recovery: 27, wRISP: 29, vsLefty: 27, poise: 29, heater: 0, agile: 23,
      abilities: ["Resilient", "Artist"], potential: "B", catcherAbility: 32,
      throwHand: "R", batHand: "L",
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Mason", lastName: "Eckelman", position: "SS", eligibility: "JR", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 2,
      hitForAvg: 50, power: 44, speed: 57, arm: 44, fielding: 45, errorResistance: 44, velocity: 0, control: 0, stamina: 22, stuff: 0,
      clutch: 44, vsLHP: 42, grit: 45, stealing: 27, running: 37, throwing: 45, recovery: 34, wRISP: 44, vsLefty: 40, poise: 44, heater: 0, agile: 40,
      abilities: ["Defensive Artisan", "Consigliere"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Henry", lastName: "Kaczmar", position: "3B", eligibility: "SR", homeState: "MI", hometown: "Grosse Pointe", jerseyNumber: 5,
      hitForAvg: 61, power: 56, speed: 53, arm: 49, fielding: 49, errorResistance: 48, velocity: 0, control: 0, stamina: 28, stuff: 0,
      clutch: 53, vsLHP: 51, grit: 55, stealing: 16, running: 34, throwing: 51, recovery: 43, wRISP: 53, vsLefty: 49, poise: 53, heater: 0, agile: 37,
      abilities: ["Power Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Gavin", lastName: "Kuzniewski", position: "2B", eligibility: "JR", homeState: "OH", hometown: "Avon", jerseyNumber: 3,
      hitForAvg: 43, power: 36, speed: 51, arm: 36, fielding: 39, errorResistance: 38, velocity: 0, control: 0, stamina: 21, stuff: 0,
      clutch: 36, vsLHP: 34, grit: 38, stealing: 22, running: 31, throwing: 38, recovery: 30, wRISP: 35, vsLefty: 33, poise: 36, heater: 0, agile: 33,
      abilities: ["Chance Maker", "Defensive Artisan"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Dane", lastName: "Harvey", position: "1B", eligibility: "JR", homeState: "IN", hometown: "Zionsville", jerseyNumber: 24,
      hitForAvg: 52, power: 73, speed: 45, arm: 38, fielding: 40, errorResistance: 38, velocity: 0, control: 0, stamina: 24, stuff: 0,
      clutch: 66, vsLHP: 42, grit: 46, stealing: 10, running: 26, throwing: 40, recovery: 34, wRISP: 44, vsLefty: 41, poise: 44, heater: 0, agile: 29,
      abilities: ["Power Hitter", "Contact Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Tyler", lastName: "Knox", position: "SS", eligibility: "FR", homeState: "OH", hometown: "Centerville", jerseyNumber: 14,
      hitForAvg: 30, power: 22, speed: 50, arm: 30, fielding: 26, errorResistance: 25, velocity: 0, control: 0, stamina: 14, stuff: 0,
      clutch: 20, vsLHP: 19, grit: 21, stealing: 17, running: 27, throwing: 30, recovery: 19, wRISP: 19, vsLefty: 18, poise: 20, heater: 0, agile: 29,
      abilities: ["Trickster", "Multi-Hit"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // Drew Mitchell — FR 2B — PG 2nd Team / Top-200 national
    { firstName: "Drew", lastName: "Mitchell", position: "2B", eligibility: "FR", homeState: "OH", hometown: "Toledo", jerseyNumber: 16,
      hitForAvg: 49, power: 33, speed: 57, arm: 35, fielding: 28, errorResistance: 26, velocity: 0, control: 0, stamina: 15, stuff: 0,
      clutch: 21, vsLHP: 20, grit: 23, stealing: 16, running: 28, throwing: 31, recovery: 20, wRISP: 20, vsLefty: 19, poise: 21, heater: 0, agile: 30,
      abilities: ["Consigliere"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Luke", lastName: "Brennan", position: "1B", eligibility: "JR", homeState: "OH", hometown: "Findlay", jerseyNumber: 34,
      hitForAvg: 36, power: 33, speed: 45, arm: 29, fielding: 33, errorResistance: 29, velocity: 0, control: 0, stamina: 16, stuff: 0,
      clutch: 29, vsLHP: 26, grit: 30, stealing: 7, running: 18, throwing: 30, recovery: 24, wRISP: 26, vsLefty: 25, poise: 29, heater: 0, agile: 21,
      abilities: ["Pull Hit", "Final Hit"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // OUTFIELDERS (4)
    { firstName: "Lee", lastName: "Ellis", position: "OF", eligibility: "JR", homeState: "OH", hometown: "Strongsville", jerseyNumber: 7,
      hitForAvg: 43, power: 39, speed: 49, arm: 37, fielding: 35, errorResistance: 35, velocity: 0, control: 0, stamina: 19, stuff: 0,
      clutch: 37, vsLHP: 35, grit: 38, stealing: 26, running: 35, throwing: 38, recovery: 30, wRISP: 36, vsLefty: 35, poise: 37, heater: 0, agile: 36,
      abilities: ["Express Baserunning", "Contact Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Alonzo", lastName: "Paul Jr", position: "OF", eligibility: "JR", homeState: "SC", hometown: "Columbia", jerseyNumber: 1,
      hitForAvg: 43, power: 41, speed: 50, arm: 39, fielding: 37, errorResistance: 35, velocity: 0, control: 0, stamina: 20, stuff: 0,
      clutch: 38, vsLHP: 35, grit: 39, stealing: 24, running: 35, throwing: 40, recovery: 32, wRISP: 37, vsLefty: 34, poise: 38, heater: 0, agile: 38,
      abilities: ["Power Hitter", "Express Baserunning"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Drew", lastName: "Novak", position: "OF", eligibility: "JR", homeState: "OH", hometown: "Solon", jerseyNumber: 9,
      hitForAvg: 43, power: 38, speed: 47, arm: 40, fielding: 38, errorResistance: 36, velocity: 0, control: 0, stamina: 20, stuff: 0,
      clutch: 36, vsLHP: 33, grit: 38, stealing: 24, running: 36, throwing: 41, recovery: 32, wRISP: 35, vsLefty: 33, poise: 36, heater: 0, agile: 39,
      abilities: ["Trickster"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Drew", lastName: "Palmer", position: "OF", eligibility: "FR", homeState: "OH", hometown: "Powell", jerseyNumber: 26,
      hitForAvg: 39, power: 32, speed: 58, arm: 40, fielding: 33, errorResistance: 32, velocity: 0, control: 0, stamina: 20, stuff: 0,
      clutch: 29, vsLHP: 28, grit: 30, stealing: 25, running: 40, throwing: 41, recovery: 28, wRISP: 28, vsLefty: 25, poise: 29, heater: 0, agile: 42,
      abilities: ["Puller Hitter", "vs. Ace", "vs. Fastballs"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...noPitches },
    { firstName: "Ryan", lastName: "Walters", position: "OF", eligibility: "SO", homeState: "OH", hometown: "Worthington", jerseyNumber: 11,
      hitForAvg: 56, power: 50, speed: 61, arm: 56, fielding: 51, errorResistance: 50, velocity: 0, control: 0, stamina: 29, stuff: 0,
      clutch: 47, vsLHP: 45, grit: 50, stealing: 36, running: 51, throwing: 57, recovery: 43, wRISP: 46, vsLefty: 43, poise: 47, heater: 0, agile: 53,
      abilities: ["Express Baserunning"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Matt", lastName: "Dingledine", position: "OF", eligibility: "JR", homeState: "OH", hometown: "Zanesville", jerseyNumber: 30,
      hitForAvg: 44, power: 41, speed: 52, arm: 39, fielding: 37, errorResistance: 35, velocity: 0, control: 0, stamina: 22, stuff: 0,
      clutch: 37, vsLHP: 35, grit: 38, stealing: 22, running: 35, throwing: 41, recovery: 30, wRISP: 35, vsLefty: 33, poise: 37, heater: 0, agile: 37,
      abilities: ["Heat Up", "Contact Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
  ],

  "Oregon": [
      // 35-12/17-7 BT (T-2nd), D1B #13, Mark Wasikowski Yr 7, BT POY 2025. Top-25 in 9 categories. Leads nation in H/9 (6.96).
      // PITCHERS (10) — 1-8 pitch scale
      // Will Sanford — Friday SO RHP, 3.64/84K in 59.1, .184 BAA, 11.77 K/9, BA #39 2027 — TEAM ELITE STUFF
      { firstName: "Will", lastName: "Sanford", position: "P", eligibility: "SO", homeState: "OR", hometown: "Portland", jerseyNumber: 31,
        hitForAvg: 20, power: 15, speed: 41, arm: 82, fielding: 47, errorResistance: 63, velocity: 85, control: 79, stamina: 86, stuff: 89,
        clutch: 99, vsLHP: 99, grit: 99, stealing: 11, running: 41, throwing: 96, recovery: 72, wRISP: 79, vsLefty: 82, poise: 82, heater: 82, agile: 53,
        abilities: ["Star of Victory", "Intimidator", "Strong Starter", "Fireman"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 7, 6, 1, 0, 0, 0]) },
      // Collin Clarke — Saturday JR RHP, sinker/slider/CH pitch-to-contact
      { firstName: "Collin", lastName: "Clarke", position: "P", eligibility: "JR", homeState: "OR", hometown: "Lake Oswego", jerseyNumber: 17,
        hitForAvg: 16, power: 12, speed: 35, arm: 66, fielding: 38, errorResistance: 52, velocity: 71, control: 70, stamina: 67, stuff: 60,
        clutch: 78, vsLHP: 72, grit: 78, stealing: 11, running: 34, throwing: 81, recovery: 58, wRISP: 58, vsLefty: 59, poise: 62, heater: 66, agile: 44,
        abilities: ["Strong Starter", "Inside Pitch", "Poker Face"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 0, 1, 5, 0, 0]) },
      // Cal Scolari — Sunday RS-SO RHP (USD transfer), All-WCC, 4-0/2.81 early, BA top-300
      { firstName: "Cal", lastName: "Scolari", position: "P", eligibility: "SO", homeState: "CA", hometown: "San Diego", jerseyNumber: 33,
        hitForAvg: 15, power: 12, speed: 36, arm: 67, fielding: 37, errorResistance: 49, velocity: 73, control: 66, stamina: 63, stuff: 63,
        clutch: 78, vsLHP: 72, grit: 78, stealing: 9, running: 34, throwing: 81, recovery: 55, wRISP: 57, vsLefty: 59, poise: 63, heater: 69, agile: 45,
        abilities: ["Strong Starter", "Doctor K", "Heavy Ball", "Sharpness"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 7, 5, 1, 0, 0, 0]) },
      // Ryan Featherston — JR RHP rotation depth/midweek
      { firstName: "Ryan", lastName: "Featherston", position: "P", eligibility: "JR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 28,
        hitForAvg: 10, power: 8, speed: 25, arm: 44, fielding: 26, errorResistance: 35, velocity: 46, control: 44, stamina: 45, stuff: 41,
        clutch: 52, vsLHP: 48, grit: 53, stealing: 7, running: 25, throwing: 55, recovery: 38, wRISP: 38, vsLefty: 39, poise: 41, heater: 45, agile: 32,
        abilities: ["Guts", "Fighting Spirit", "Strikeout", "Quick Hands"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
      // Toby Twist — JR RHP closer/RP
      { firstName: "Toby", lastName: "Twist", position: "P", eligibility: "JR", homeState: "WA", hometown: "Seattle", jerseyNumber: 38,
        hitForAvg: 13, power: 10, speed: 31, arm: 57, fielding: 33, errorResistance: 43, velocity: 62, control: 54, stamina: 39, stuff: 56,
        clutch: 69, vsLHP: 64, grit: 69, stealing: 9, running: 30, throwing: 71, recovery: 43, wRISP: 50, vsLefty: 51, poise: 54, heater: 59, agile: 39,
        abilities: ["Fireman", "Explosive Fastball"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 7, 0, 1, 4, 0, 0]) },
      // Ian Umlandt — JR RHP RP
      { firstName: "Ian", lastName: "Umlandt", position: "P", eligibility: "JR", homeState: "OR", hometown: "Bend", jerseyNumber: 22,
        hitForAvg: 11, power: 9, speed: 27, arm: 45, fielding: 27, errorResistance: 39, velocity: 48, control: 45, stamina: 43, stuff: 43,
        clutch: 54, vsLHP: 50, grit: 55, stealing: 7, running: 26, throwing: 57, recovery: 39, wRISP: 39, vsLefty: 40, poise: 43, heater: 46, agile: 34,
        abilities: ["Guts", "Staredown", "Winner's Luck", "Fireman"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
      // Dylan Greer — JR RHP
      { firstName: "Dylan", lastName: "Greer", position: "P", eligibility: "JR", homeState: "OR", hometown: "Salem", jerseyNumber: 26,
        hitForAvg: 12, power: 10, speed: 30, arm: 48, fielding: 30, errorResistance: 41, velocity: 50, control: 48, stamina: 48, stuff: 44,
        clutch: 55, vsLHP: 54, grit: 57, stealing: 7, running: 29, throwing: 59, recovery: 41, wRISP: 41, vsLefty: 42, poise: 44, heater: 51, agile: 37,
        abilities: ["Guts", "Flyball Pitcher"], potential: "B", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
      // Tyler Jones — SO RP
      { firstName: "Tyler", lastName: "Jones", position: "P", eligibility: "SO", homeState: "CA", hometown: "Sacramento", jerseyNumber: 35,
        hitForAvg: 7, power: 5, speed: 19, arm: 24, fielding: 15, errorResistance: 23, velocity: 30, control: 22, stamina: 22, stuff: 22,
        clutch: 28, vsLHP: 26, grit: 28, stealing: 5, running: 16, throwing: 32, recovery: 21, wRISP: 19, vsLefty: 21, poise: 21, heater: 26, agile: 22,
        abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
      // Sean Murphy — SO depth
      { firstName: "Sean", lastName: "Murphy", position: "P", eligibility: "SO", homeState: "OR", hometown: "Eugene", jerseyNumber: 42,
        hitForAvg: 8, power: 7, speed: 25, arm: 27, fielding: 18, errorResistance: 27, velocity: 29, control: 25, stamina: 25, stuff: 25,
        clutch: 32, vsLHP: 31, grit: 34, stealing: 7, running: 21, throwing: 38, recovery: 22, wRISP: 21, vsLefty: 22, poise: 23, heater: 29, agile: 25,
        abilities: ["Intimidator", "Constant Speed"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
      // Kai Nakamura — FR depth
      { firstName: "Kai", lastName: "Nakamura", position: "P", eligibility: "FR", homeState: "WA", hometown: "Bellevue", jerseyNumber: 46,
        hitForAvg: 7, power: 5, speed: 26, arm: 40, fielding: 24, errorResistance: 33, velocity: 47, control: 35, stamina: 32, stuff: 40,
        clutch: 46, vsLHP: 49, grit: 47, stealing: 6, running: 23, throwing: 49, recovery: 32, wRISP: 33, vsLefty: 43, poise: 35, heater: 40, agile: 32,
        abilities: ["Painter", "Crossfire"], potential: "A", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
      // CATCHERS (2)
      // Brayden Jaksa — FR C/1B, BA #7 2028 draft, hits 2nd, 7-for-17 with 2 HR/3 RBI in big stretch
      { firstName: "Brayden", lastName: "Jaksa", position: "C", eligibility: "FR", homeState: "CA", hometown: "Mission Viejo", jerseyNumber: 8,
        hitForAvg: 60, power: 53, speed: 30, arm: 51, fielding: 47, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 52, vsLHP: 47, grit: 54, stealing: 10, running: 28, throwing: 51, recovery: 40, wRISP: 52, vsLefty: 47, poise: 54, heater: 0, agile: 33,
        abilities: ["Power Hitter", "Contact Hitter", "Defensive Artisan"], potential: "A+", catcherAbility: 47,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Burke-Lee Mabeus — SO C, 2025 All-Freshman
      { firstName: "Burke-Lee", lastName: "Mabeus", position: "C", eligibility: "SO", homeState: "OR", hometown: "Tigard", jerseyNumber: 12,
        hitForAvg: 44, power: 39, speed: 28, arm: 43, fielding: 46, errorResistance: 43, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 38, vsLHP: 36, grit: 40, stealing: 7, running: 21, throwing: 44, recovery: 34, wRISP: 37, vsLefty: 34, poise: 38, heater: 0, agile: 27,
        abilities: ["Defensive Artisan"], potential: "A-", catcherAbility: 43,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // INFIELDERS (7)
      // Ryan Cooney — 2B JR, .353/16 2B/8 HR, 3x BT POW, BA #134 — TEAM ELITE HIT
      { firstName: "Ryan", lastName: "Cooney", position: "2B", eligibility: "JR", homeState: "CA", hometown: "San Clemente", jerseyNumber: 10,
        hitForAvg: 99, power: 83, speed: 76, arm: 61, fielding: 69, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 86, vsLHP: 82, grit: 86, stealing: 31, running: 54, throwing: 61, recovery: 52, wRISP: 86, vsLefty: 82, poise: 86, heater: 0, agile: 61,
        abilities: ["Hit Machine", "Contact Hitter", "Chance Maker", "Consigliere"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Maddox Molony — SS JR, BA #122 2026 draft
      { firstName: "Maddox", lastName: "Molony", position: "SS", eligibility: "JR", homeState: "OR", hometown: "West Linn", jerseyNumber: 2,
        hitForAvg: 66, power: 63, speed: 64, arm: 55, fielding: 58, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 58, vsLHP: 53, grit: 58, stealing: 26, running: 41, throwing: 55, recovery: 41, wRISP: 58, vsLefty: 53, poise: 58, heater: 0, agile: 47,
        abilities: ["High-Speed Laser", "Power Hitter", "Defensive Artisan", "Consigliere"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Naulivou Lauaki Jr — DH RS-FR, .371/3 HR
      { firstName: "Naulivou", lastName: "Lauaki Jr.", position: "1B", eligibility: "FR", homeState: "HI", hometown: "Honolulu", jerseyNumber: 25,
        hitForAvg: 59, power: 50, speed: 39, arm: 35, fielding: 35, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 50, vsLHP: 46, grit: 50, stealing: 5, running: 21, throwing: 35, recovery: 31, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 25,
        abilities: ["Contact Hitter", "Power Hitter"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Dominic Hellman — 1B JR
      { firstName: "Dominic", lastName: "Hellman", position: "1B", eligibility: "JR", homeState: "CA", hometown: "Fresno", jerseyNumber: 24,
        hitForAvg: 45, power: 47, speed: 39, arm: 37, fielding: 40, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 40, vsLHP: 37, grit: 41, stealing: 7, running: 23, throwing: 37, recovery: 31, wRISP: 40, vsLefty: 37, poise: 40, heater: 0, agile: 26,
        abilities: ["Power Hitter", "Contact Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Jake Morrison — 3B JR
      { firstName: "Jake", lastName: "Morrison", position: "3B", eligibility: "JR", homeState: "OR", hometown: "Corvallis", jerseyNumber: 5,
        hitForAvg: 38, power: 37, speed: 37, arm: 39, fielding: 37, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 34, vsLHP: 32, grit: 35, stealing: 11, running: 27, throwing: 39, recovery: 29, wRISP: 34, vsLefty: 31, poise: 34, heater: 0, agile: 30,
        abilities: ["Spirit Head", "Contact Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Owen Richards — 1B SO depth
      { firstName: "Owen", lastName: "Richards", position: "1B", eligibility: "SO", homeState: "OR", hometown: "Medford", jerseyNumber: 34,
        hitForAvg: 38, power: 36, speed: 43, arm: 35, fielding: 35, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 31, vsLHP: 30, grit: 33, stealing: 7, running: 24, throwing: 35, recovery: 26, wRISP: 30, vsLefty: 27, poise: 31, heater: 0, agile: 24,
        abilities: ["High Ball Hitter", "Insurer"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "S",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Brayden Schultz — SS FR depth
      { firstName: "Brayden", lastName: "Schultz", position: "SS", eligibility: "FR", homeState: "WA", hometown: "Vancouver", jerseyNumber: 14,
        hitForAvg: 33, power: 26, speed: 55, arm: 33, fielding: 28, errorResistance: 25, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 21, vsLHP: 20, grit: 23, stealing: 18, running: 28, throwing: 30, recovery: 20, wRISP: 20, vsLefty: 20, poise: 21, heater: 0, agile: 30,
        abilities: ["vs. Ace", "First Pitch Hitter"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // OUTFIELDERS (6)
      // Drew Smith — OF JR, 14 HR (team lead)
      { firstName: "Drew", lastName: "Smith", position: "OF", eligibility: "JR", homeState: "OR", hometown: "Beaverton", jerseyNumber: 7,
        hitForAvg: 61, power: 78, speed: 56, arm: 50, fielding: 49, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 58, vsLHP: 54, grit: 58, stealing: 29, running: 46, throwing: 50, recovery: 42, wRISP: 58, vsLefty: 54, poise: 58, heater: 0, agile: 47,
        abilities: ["Artist", "Contact Hitter", "Power Hitter"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Angel Laya — OF FR, .302/40 RBI/13 HR (BT best frosh, BA #10 2028)
      { firstName: "Angel", lastName: "Laya", position: "OF", eligibility: "FR", homeState: "FL", hometown: "Miami", jerseyNumber: 1,
        hitForAvg: 47, power: 54, speed: 41, arm: 37, fielding: 34, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 42, vsLHP: 39, grit: 42, stealing: 17, running: 33, throwing: 37, recovery: 30, wRISP: 42, vsLefty: 39, poise: 42, heater: 0, agile: 34,
        abilities: ["Power Hitter", "Consigliere", "Contact Hitter"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Elijah Cook — OF SR
      { firstName: "Elijah", lastName: "Cook", position: "OF", eligibility: "SR", homeState: "CA", hometown: "Oakland", jerseyNumber: 9,
        hitForAvg: 46, power: 40, speed: 46, arm: 41, fielding: 39, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 41, vsLHP: 38, grit: 41, stealing: 26, running: 38, throwing: 41, recovery: 34, wRISP: 39, vsLefty: 37, poise: 41, heater: 0, agile: 41,
        abilities: ["Express Baserunning", "Contact Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "deep", hairColor: "black", hairStyle: "fade",
        ...noPitches },
      // Tyler Nash — OF SO
      { firstName: "Tyler", lastName: "Nash", position: "OF", eligibility: "SO", homeState: "WA", hometown: "Spokane", jerseyNumber: 20,
        hitForAvg: 37, power: 33, speed: 44, arm: 37, fielding: 34, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 31, vsLHP: 28, grit: 33, stealing: 24, running: 35, throwing: 38, recovery: 28, wRISP: 30, vsLefty: 28, poise: 31, heater: 0, agile: 37,
        abilities: ["Express Baserunning"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Drew Kenworthy — OF JR
      { firstName: "Drew", lastName: "Kenworthy", position: "OF", eligibility: "JR", homeState: "OR", hometown: "Grants Pass", jerseyNumber: 23,
        hitForAvg: 36, power: 33, speed: 42, arm: 34, fielding: 32, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 32, vsLHP: 29, grit: 32, stealing: 21, running: 32, throwing: 36, recovery: 26, wRISP: 31, vsLefty: 27, poise: 32, heater: 0, agile: 34,
        abilities: ["Resilient", "Spirit Head"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Cole Hendrickson — OF FR
      { firstName: "Cole", lastName: "Hendrickson", position: "OF", eligibility: "SO", homeState: "OR", hometown: "Springfield", jerseyNumber: 26,
        hitForAvg: 34, power: 27, speed: 50, arm: 34, fielding: 28, errorResistance: 27, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 23, vsLHP: 22, grit: 25, stealing: 22, running: 31, throwing: 34, recovery: 23, wRISP: 22, vsLefty: 22, poise: 23, heater: 0, agile: 36,
        abilities: ["Inside Hitter"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
    ],
  
  "Penn State": [
    // PITCHERS (10)
    { firstName: "Colin", lastName: "Fitzgerald", position: "P", eligibility: "SR", homeState: "PA", hometown: "West Chester", jerseyNumber: 31,
      hitForAvg: 26, power: 22, speed: 37, arm: 79, fielding: 50, errorResistance: 64, velocity: 78, control: 79, stamina: 79, stuff: 78,
      clutch: 93, vsLHP: 86, grit: 94, stealing: 11, running: 44, throwing: 94, recovery: 72, wRISP: 76, vsLefty: 76, poise: 79, heater: 79, agile: 54,
      abilities: ["Star of Victory", "Strong Starter", "Guts", "Fireman", "Intimidator", "Strength Distribution"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 7, 6, 1, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Reynolds", position: "P", eligibility: "JR", homeState: "PA", hometown: "Allentown", jerseyNumber: 22,
      hitForAvg: 20, power: 15, speed: 39, arm: 62, fielding: 40, errorResistance: 54, velocity: 67, control: 59, stamina: 61, stuff: 59,
      clutch: 72, vsLHP: 67, grit: 74, stealing: 11, running: 39, throwing: 79, recovery: 55, wRISP: 55, vsLefty: 56, poise: 58, heater: 65, agile: 48,
      abilities: ["Strong Starter", "Sharpness", "Good Pickoff", "Quick Hands"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 7, 5, 1, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Walden", position: "P", eligibility: "SO", homeState: "NJ", hometown: "Cherry Hill", jerseyNumber: 35,
      hitForAvg: 8, power: 6, speed: 20, arm: 23, fielding: 15, errorResistance: 22, velocity: 30, control: 22, stamina: 22, stuff: 21,
      clutch: 28, vsLHP: 27, grit: 28, stealing: 6, running: 17, throwing: 33, recovery: 20, wRISP: 18, vsLefty: 20, poise: 20, heater: 25, agile: 21,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Quinn", position: "P", eligibility: "JR", homeState: "PA", hometown: "Lancaster", jerseyNumber: 38,
      hitForAvg: 18, power: 13, speed: 33, arm: 57, fielding: 36, errorResistance: 48, velocity: 62, control: 54, stamina: 45, stuff: 53,
      clutch: 67, vsLHP: 62, grit: 68, stealing: 10, running: 35, throwing: 69, recovery: 51, wRISP: 51, vsLefty: 51, poise: 52, heater: 58, agile: 42,
      abilities: ["Fireman", "Guts", "Staredown"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 6, 0, 1, 4, 0, 0]) },
    { firstName: "Matt", lastName: "Bradshaw", position: "P", eligibility: "SO", homeState: "PA", hometown: "Pittsburgh", jerseyNumber: 42,
      hitForAvg: 9, power: 7, speed: 24, arm: 25, fielding: 16, errorResistance: 25, velocity: 34, control: 24, stamina: 24, stuff: 23,
      clutch: 32, vsLHP: 29, grit: 32, stealing: 7, running: 21, throwing: 36, recovery: 22, wRISP: 20, vsLefty: 22, poise: 22, heater: 26, agile: 25,
      abilities: ["Perfect Combustion"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    { firstName: "Aidan", lastName: "Fobare", position: "P", eligibility: "JR", homeState: "MD", hometown: "Bethesda", jerseyNumber: 28,
      hitForAvg: 13, power: 9, speed: 31, arm: 45, fielding: 27, errorResistance: 39, velocity: 47, control: 42, stamina: 45, stuff: 41,
      clutch: 51, vsLHP: 49, grit: 54, stealing: 8, running: 31, throwing: 56, recovery: 39, wRISP: 38, vsLefty: 39, poise: 40, heater: 47, agile: 35,
      abilities: ["Guts", "Kageura"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Drew", lastName: "Hartman", position: "P", eligibility: "JR", homeState: "PA", hometown: "York", jerseyNumber: 40,
      hitForAvg: 19, power: 15, speed: 33, arm: 55, fielding: 37, errorResistance: 48, velocity: 58, control: 53, stamina: 53, stuff: 53,
      clutch: 64, vsLHP: 60, grit: 65, stealing: 10, running: 37, throwing: 68, recovery: 48, wRISP: 46, vsLefty: 48, poise: 50, heater: 58, agile: 44,
      abilities: ["Escape Pitch", "Star of Victory", "Kageura"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Nolan", lastName: "Berger", position: "P", eligibility: "SO", homeState: "PA", hometown: "Doylestown", jerseyNumber: 46,
      hitForAvg: 10, power: 7, speed: 24, arm: 27, fielding: 17, errorResistance: 26, velocity: 36, control: 26, stamina: 24, stuff: 24,
      clutch: 31, vsLHP: 29, grit: 32, stealing: 7, running: 23, throwing: 38, recovery: 21, wRISP: 21, vsLefty: 21, poise: 21, heater: 29, agile: 28,
      abilities: ["Kageura", "Delayed Arm"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Schwartz", position: "P", eligibility: "FR", homeState: "PA", hometown: "Harrisburg", jerseyNumber: 48,
      hitForAvg: 10, power: 7, speed: 30, arm: 40, fielding: 22, errorResistance: 32, velocity: 50, control: 39, stamina: 39, stuff: 41,
      clutch: 38, vsLHP: 34, grit: 39, stealing: 9, running: 29, throwing: 47, recovery: 27, wRISP: 25, vsLefty: 27, poise: 27, heater: 37, agile: 33,
      abilities: ["Winner's Luck", "Painter", "Intimidator"], potential: "A", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    { firstName: "Dylan", lastName: "Haines", position: "P", eligibility: "FR", homeState: "NJ", hometown: "Toms River", jerseyNumber: 50,
      hitForAvg: 9, power: 6, speed: 23, arm: 28, fielding: 17, errorResistance: 26, velocity: 36, control: 25, stamina: 24, stuff: 26,
      clutch: 30, vsLHP: 29, grit: 31, stealing: 7, running: 23, throwing: 39, recovery: 21, wRISP: 20, vsLefty: 21, poise: 21, heater: 30, agile: 27,
      abilities: ["Indomitable Soul", "Frozen"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 3, 4, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Nate", lastName: "Voss", position: "C", eligibility: "JR", homeState: "PA", hometown: "Reading", jerseyNumber: 12,
      hitForAvg: 41, power: 40, speed: 30, arm: 43, fielding: 42, errorResistance: 41, velocity: 0, control: 0, stamina: 22, stuff: 0,
      clutch: 37, vsLHP: 34, grit: 40, stealing: 8, running: 22, throwing: 45, recovery: 31, wRISP: 35, vsLefty: 33, poise: 38, heater: 0, agile: 25,
      abilities: ["Defensive Artisan", "High-Speed Laser"], potential: "B+", catcherAbility: 40,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Ryan", lastName: "Corcoran", position: "C", eligibility: "FR", homeState: "PA", hometown: "Scranton", jerseyNumber: 18,
      hitForAvg: 39, power: 30, speed: 34, arm: 40, fielding: 39, errorResistance: 32, velocity: 0, control: 0, stamina: 18, stuff: 0,
      clutch: 26, vsLHP: 25, grit: 27, stealing: 8, running: 23, throwing: 40, recovery: 26, wRISP: 26, vsLefty: 23, poise: 26, heater: 0, agile: 26,
      abilities: ["Wide Angle Cannon", "Contact Hitter"], potential: "A-", catcherAbility: 36,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Bryce", lastName: "Molinaro", position: "3B", eligibility: "JR", homeState: "PA", hometown: "State College", jerseyNumber: 2,
      hitForAvg: 53, power: 78, speed: 50, arm: 45, fielding: 44, errorResistance: 43, velocity: 0, control: 0, stamina: 23, stuff: 0,
      clutch: 50, vsLHP: 47, grit: 50, stealing: 13, running: 31, throwing: 47, recovery: 37, wRISP: 50, vsLefty: 45, poise: 50, heater: 0, agile: 34,
      abilities: ["Power Hitter", "Consigliere", "Contact Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Kevin", lastName: "Karstetter", position: "1B", eligibility: "JR", homeState: "PA", hometown: "State College", jerseyNumber: 24,
      hitForAvg: 33, power: 32, speed: 39, arm: 27, fielding: 28, errorResistance: 27, velocity: 0, control: 0, stamina: 16, stuff: 0,
      clutch: 28, vsLHP: 26, grit: 28, stealing: 7, running: 19, throwing: 28, recovery: 23, wRISP: 27, vsLefty: 25, poise: 28, heater: 0, agile: 20,
      abilities: ["Power Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Jayden", lastName: "Davis", position: "2B", eligibility: "JR", homeState: "TN", hometown: "Nashville", jerseyNumber: 10,
      hitForAvg: 45, power: 36, speed: 55, arm: 36, fielding: 39, errorResistance: 37, velocity: 0, control: 0, stamina: 20, stuff: 0,
      clutch: 37, vsLHP: 36, grit: 39, stealing: 23, running: 31, throwing: 37, recovery: 30, wRISP: 36, vsLefty: 35, poise: 37, heater: 0, agile: 35,
      abilities: ["Chance Maker", "Defensive Artisan"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Spencer", lastName: "Barnett", position: "SS", eligibility: "JR", homeState: "WV", hometown: "Morgantown", jerseyNumber: 3,
      hitForAvg: 45, power: 38, speed: 58, arm: 42, fielding: 44, errorResistance: 42, velocity: 0, control: 0, stamina: 22, stuff: 0,
      clutch: 38, vsLHP: 37, grit: 39, stealing: 26, running: 37, throwing: 44, recovery: 33, wRISP: 38, vsLefty: 35, poise: 38, heater: 0, agile: 38,
      abilities: ["Defensive Artisan", "Express Baserunning"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...noPitches },
    { firstName: "Preston", lastName: "Yaucher", position: "SS", eligibility: "FR", homeState: "PA", hometown: "Mechanicsburg", jerseyNumber: 14,
      hitForAvg: 39, power: 27, speed: 64, arm: 39, fielding: 31, errorResistance: 29, velocity: 0, control: 0, stamina: 17, stuff: 0,
      clutch: 24, vsLHP: 23, grit: 26, stealing: 20, running: 32, throwing: 35, recovery: 23, wRISP: 23, vsLefty: 22, poise: 24, heater: 0, agile: 35,
      abilities: ["Heat Up"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Drew", lastName: "Wilson", position: "2B", eligibility: "SO", homeState: "PA", hometown: "Erie", jerseyNumber: 16,
      hitForAvg: 37, power: 30, speed: 55, arm: 35, fielding: 35, errorResistance: 33, velocity: 0, control: 0, stamina: 19, stuff: 0,
      clutch: 29, vsLHP: 27, grit: 31, stealing: 20, running: 31, throwing: 36, recovery: 26, wRISP: 28, vsLefty: 26, poise: 29, heater: 0, agile: 33,
      abilities: ["Good Bunt", "Tough Out", "Pinch Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // OUTFIELDERS (5)
    { firstName: "Jack", lastName: "Porter", position: "OF", eligibility: "JR", homeState: "PA", hometown: "Williamsport", jerseyNumber: 7,
      hitForAvg: 58, power: 55, speed: 58, arm: 50, fielding: 49, errorResistance: 46, velocity: 0, control: 0, stamina: 26, stuff: 0,
      clutch: 52, vsLHP: 50, grit: 54, stealing: 30, running: 42, throwing: 51, recovery: 41, wRISP: 52, vsLefty: 49, poise: 52, heater: 0, agile: 44,
      abilities: ["Power Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Jesse", lastName: "Jaconski", position: "OF", eligibility: "JR", homeState: "PA", hometown: "Bethlehem", jerseyNumber: 1,
      hitForAvg: 57, power: 50, speed: 60, arm: 46, fielding: 44, errorResistance: 43, velocity: 0, control: 0, stamina: 23, stuff: 0,
      clutch: 49, vsLHP: 46, grit: 51, stealing: 29, running: 42, throwing: 48, recovery: 39, wRISP: 49, vsLefty: 44, poise: 49, heater: 0, agile: 44,
      abilities: ["Contact Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Michael", lastName: "Anderson", position: "OF", eligibility: "JR", homeState: "AR", hometown: "Little Rock", jerseyNumber: 9,
      hitForAvg: 65, power: 84, speed: 66, arm: 58, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 31, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 58, stealing: 31, running: 48, throwing: 58, recovery: 45, wRISP: 56, vsLefty: 52, poise: 58, heater: 0, agile: 52,
      abilities: ["High-Speed Laser"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...noPitches },
    { firstName: "Cohl", lastName: "Mercado", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Tampa", jerseyNumber: 20,
      hitForAvg: 56, power: 47, speed: 58, arm: 50, fielding: 49, errorResistance: 47, velocity: 0, control: 0, stamina: 28, stuff: 0,
      clutch: 47, vsLHP: 44, grit: 49, stealing: 39, running: 50, throwing: 51, recovery: 40, wRISP: 46, vsLefty: 42, poise: 47, heater: 0, agile: 53,
      abilities: ["Express Baserunning"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Maddox", lastName: "McDonald", position: "OF", eligibility: "FR", homeState: "PA", hometown: "Media", jerseyNumber: 26,
      hitForAvg: 36, power: 28, speed: 53, arm: 36, fielding: 29, errorResistance: 25, velocity: 0, control: 0, stamina: 17, stuff: 0,
      clutch: 23, vsLHP: 23, grit: 24, stealing: 22, running: 34, throwing: 35, recovery: 23, wRISP: 23, vsLefty: 22, poise: 23, heater: 0, agile: 36,
      abilities: ["Strike Thrower", "Contact Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Luke", lastName: "Bradley", position: "OF", eligibility: "JR", homeState: "PA", hometown: "Easton", jerseyNumber: 11,
      hitForAvg: 47, power: 41, speed: 55, arm: 45, fielding: 40, errorResistance: 39, velocity: 0, control: 0, stamina: 22, stuff: 0,
      clutch: 39, vsLHP: 38, grit: 40, stealing: 26, running: 39, throwing: 46, recovery: 34, wRISP: 39, vsLefty: 35, poise: 39, heater: 0, agile: 42,
      abilities: ["Outside Hitter", "Contact Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Tyler", lastName: "Bennett", position: "2B", eligibility: "SO", homeState: "PA", hometown: "Altoona", jerseyNumber: 30,
      hitForAvg: 43, power: 37, speed: 59, arm: 43, fielding: 38, errorResistance: 37, velocity: 0, control: 0, stamina: 22, stuff: 0,
      clutch: 37, vsLHP: 34, grit: 37, stealing: 26, running: 38, throwing: 43, recovery: 32, wRISP: 35, vsLefty: 32, poise: 37, heater: 0, agile: 42,
      abilities: ["Trickster", "Contact Hitter", "First Pitch Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
  ],
};
