import type { RealPlayer } from "./realRosters";

function pitchMix(primary: number, secondary: number[]): { pitchFB: number; pitch2S: number; pitchSL: number; pitchCB: number; pitchCH: number; pitchCT: number; pitchSNK: number; pitchSPL: number } {
  return {
    pitchFB: primary,
    pitch2S: secondary[0] || 0,
    pitchSL: secondary[1] || 0,
    pitchCB: secondary[2] || 0,
    pitchCH: secondary[3] || 0,
    pitchCT: secondary[4] || 0,
    pitchSNK: secondary[5] || 0,
    pitchSPL: secondary[6] || 0,
  };
}

const noPitches = { pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0 };

export const BIG_TEN_BATCH2_ROSTERS: Record<string, RealPlayer[]> = {
  "Minnesota": [
    // PITCHERS (9)
    { firstName: "Sam", lastName: "Ireland", position: "P", eligibility: "JR", homeState: "MN", hometown: "Woodbury", jerseyNumber: 17,
      hitForAvg: 20, power: 15, speed: 42, arm: 80, fielding: 50, errorResistance: 52, velocity: 84, control: 76, stamina: 78, stuff: 82,
      clutch: 74, vsLHP: 70, grit: 76, stealing: 10, running: 38, throwing: 80, recovery: 70, wRISP: 72, vsLefty: 74, poise: 76, heater: 82, agile: 48,
      abilities: ["Ace", "Strong Starter", "Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 7, 6, 5, 0, 0, 0]) },
    { firstName: "Brooks", lastName: "Lee", position: "P", eligibility: "SR", homeState: "CA", hometown: "San Luis Obispo", jerseyNumber: 44,
      hitForAvg: 22, power: 18, speed: 38, arm: 74, fielding: 48, errorResistance: 52, velocity: 76, control: 74, stamina: 58, stuff: 72,
      clutch: 76, vsLHP: 70, grit: 78, stealing: 12, running: 34, throwing: 72, recovery: 70, wRISP: 74, vsLefty: 68, poise: 78, heater: 74, agile: 44,
      abilities: ["Fireman", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 5, 4, 0, 0]) },
    { firstName: "Joe", lastName: "Moran", position: "P", eligibility: "SO", homeState: "MN", hometown: "Edina", jerseyNumber: 32,
      hitForAvg: 16, power: 12, speed: 40, arm: 70, fielding: 44, errorResistance: 46, velocity: 72, control: 66, stamina: 68, stuff: 70,
      clutch: 58, vsLHP: 56, grit: 60, stealing: 12, running: 38, throwing: 68, recovery: 58, wRISP: 56, vsLefty: 58, poise: 60, heater: 70, agile: 44,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Lunke", position: "P", eligibility: "JR", homeState: "WI", hometown: "Waukesha", jerseyNumber: 28,
      hitForAvg: 18, power: 14, speed: 38, arm: 72, fielding: 46, errorResistance: 48, velocity: 74, control: 70, stamina: 72, stuff: 72,
      clutch: 64, vsLHP: 62, grit: 66, stealing: 10, running: 34, throwing: 70, recovery: 64, wRISP: 62, vsLefty: 64, poise: 66, heater: 72, agile: 42,
      abilities: ["Workhorse"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 5, 0, 0, 0]) },
    { firstName: "Pierson", lastName: "Ohl", position: "P", eligibility: "SR", homeState: "MN", hometown: "Minnetonka", jerseyNumber: 36,
      hitForAvg: 20, power: 16, speed: 40, arm: 74, fielding: 50, errorResistance: 52, velocity: 76, control: 74, stamina: 70, stuff: 74,
      clutch: 72, vsLHP: 66, grit: 74, stealing: 12, running: 36, throwing: 72, recovery: 68, wRISP: 70, vsLefty: 68, poise: 74, heater: 74, agile: 44,
      abilities: ["Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 0, 4, 0, 0]) },
    { firstName: "Devon", lastName: "Smith", position: "P", eligibility: "JR", homeState: "IL", hometown: "Naperville", jerseyNumber: 22,
      hitForAvg: 18, power: 14, speed: 40, arm: 70, fielding: 46, errorResistance: 48, velocity: 72, control: 68, stamina: 66, stuff: 70,
      clutch: 62, vsLHP: 60, grit: 64, stealing: 12, running: 36, throwing: 68, recovery: 62, wRISP: 60, vsLefty: 62, poise: 64, heater: 70, agile: 44,
      abilities: [], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Kyle", lastName: "Kempf", position: "P", eligibility: "SO", homeState: "MN", hometown: "Plymouth", jerseyNumber: 40,
      hitForAvg: 16, power: 12, speed: 42, arm: 68, fielding: 44, errorResistance: 46, velocity: 70, control: 64, stamina: 64, stuff: 68,
      clutch: 56, vsLHP: 54, grit: 58, stealing: 14, running: 38, throwing: 66, recovery: 56, wRISP: 54, vsLefty: 56, poise: 58, heater: 68, agile: 46,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 5, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Sweeney", position: "P", eligibility: "SO", homeState: "MN", hometown: "Lakeville", jerseyNumber: 46,
      hitForAvg: 16, power: 12, speed: 42, arm: 66, fielding: 42, errorResistance: 44, velocity: 68, control: 58, stamina: 56, stuff: 66,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 14, running: 40, throwing: 64, recovery: 50, wRISP: 48, vsLefty: 50, poise: 50, heater: 66, agile: 46,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 4, 0, 0, 0]) },
    { firstName: "Owen", lastName: "Shugart", position: "P", eligibility: "SO", homeState: "IA", hometown: "Des Moines", jerseyNumber: 48,
      hitForAvg: 14, power: 10, speed: 40, arm: 64, fielding: 40, errorResistance: 42, velocity: 66, control: 56, stamina: 54, stuff: 64,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 12, running: 38, throwing: 62, recovery: 48, wRISP: 46, vsLefty: 48, poise: 48, heater: 64, agile: 44,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    { firstName: "Trent", lastName: "Palmer", position: "P", eligibility: "JR", homeState: "MN", hometown: "Mankato", jerseyNumber: 50,
      hitForAvg: 18, power: 14, speed: 38, arm: 70, fielding: 46, errorResistance: 48, velocity: 72, control: 68, stamina: 68, stuff: 70,
      clutch: 62, vsLHP: 60, grit: 64, stealing: 10, running: 34, throwing: 68, recovery: 62, wRISP: 60, vsLefty: 62, poise: 64, heater: 70, agile: 42,
      abilities: [], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Jack", lastName: "Kelly", position: "C", eligibility: "JR", homeState: "MN", hometown: "Eagan", jerseyNumber: 12,
      hitForAvg: 62, power: 55, speed: 40, arm: 72, fielding: 70, errorResistance: 68, velocity: 36, control: 32, stamina: 36, stuff: 30,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 18, running: 38, throwing: 74, recovery: 56, wRISP: 64, vsLefty: 60, poise: 66, heater: 32, agile: 44,
      abilities: ["Iron Glove"], potential: "B", catcherAbility: 72,
      ...noPitches },
    { firstName: "Isaiah", lastName: "Thomas", position: "C", eligibility: "SO", homeState: "MN", hometown: "Maple Grove", jerseyNumber: 18,
      hitForAvg: 50, power: 42, speed: 38, arm: 64, fielding: 58, errorResistance: 54, velocity: 32, control: 28, stamina: 34, stuff: 26,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 14, running: 36, throwing: 66, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 28, agile: 40,
      abilities: [], potential: "B", catcherAbility: 60,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Matt", lastName: "Higgins", position: "3B", eligibility: "SR", homeState: "MN", hometown: "St. Paul", jerseyNumber: 5,
      hitForAvg: 76, power: 72, speed: 48, arm: 68, fielding: 66, errorResistance: 64, velocity: 36, control: 32, stamina: 38, stuff: 30,
      clutch: 74, vsLHP: 70, grit: 76, stealing: 20, running: 46, throwing: 70, recovery: 58, wRISP: 74, vsLefty: 68, poise: 74, heater: 32, agile: 52,
      abilities: ["Power Hitter", "Clutch Gene"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Joe", lastName: "Vos", position: "2B", eligibility: "SR", homeState: "WI", hometown: "Milwaukee", jerseyNumber: 3,
      hitForAvg: 72, power: 58, speed: 56, arm: 64, fielding: 70, errorResistance: 68, velocity: 34, control: 30, stamina: 36, stuff: 28,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 34, running: 54, throwing: 66, recovery: 56, wRISP: 68, vsLefty: 64, poise: 70, heater: 30, agile: 58,
      abilities: ["Table Setter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Zach", lastName: "Carr", position: "SS", eligibility: "JR", homeState: "MN", hometown: "Rochester", jerseyNumber: 2,
      hitForAvg: 68, power: 52, speed: 66, arm: 72, fielding: 74, errorResistance: 72, velocity: 36, control: 32, stamina: 34, stuff: 28,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 48, running: 64, throwing: 74, recovery: 54, wRISP: 64, vsLefty: 60, poise: 66, heater: 32, agile: 70,
      abilities: ["Iron Glove", "Speed Demon"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Easton", lastName: "Bertrand", position: "1B", eligibility: "JR", homeState: "MN", hometown: "Burnsville", jerseyNumber: 24,
      hitForAvg: 64, power: 62, speed: 42, arm: 60, fielding: 62, errorResistance: 60, velocity: 34, control: 30, stamina: 34, stuff: 28,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 16, running: 40, throwing: 62, recovery: 52, wRISP: 62, vsLefty: 56, poise: 62, heater: 30, agile: 44,
      abilities: ["Power Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Patrick", lastName: "Winkel", position: "1B", eligibility: "FR", homeState: "CT", hometown: "Enfield", jerseyNumber: 34,
      hitForAvg: 44, power: 42, speed: 36, arm: 52, fielding: 46, errorResistance: 42, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 42, vsLHP: 38, grit: 44, stealing: 12, running: 34, throwing: 54, recovery: 38, wRISP: 40, vsLefty: 36, poise: 40, heater: 26, agile: 38,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Michael", lastName: "Taylor", position: "SS", eligibility: "FR", homeState: "MN", hometown: "Bloomington", jerseyNumber: 14,
      hitForAvg: 40, power: 32, speed: 54, arm: 56, fielding: 50, errorResistance: 46, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 32, running: 52, throwing: 58, recovery: 36, wRISP: 36, vsLefty: 34, poise: 38, heater: 26, agile: 56,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS & DH (7)
    { firstName: "Edouard", lastName: "Julien", position: "OF", eligibility: "SR", homeState: "QC", hometown: "Quebec City", jerseyNumber: 1,
      hitForAvg: 78, power: 74, speed: 58, arm: 66, fielding: 68, errorResistance: 66, velocity: 36, control: 32, stamina: 38, stuff: 30,
      clutch: 76, vsLHP: 72, grit: 78, stealing: 40, running: 56, throwing: 68, recovery: 60, wRISP: 76, vsLefty: 70, poise: 76, heater: 32, agile: 60,
      abilities: ["Power Hitter", "Clutch Gene"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Drew", lastName: "Gilbert", position: "OF", eligibility: "JR", homeState: "TX", hometown: "Stillwater", jerseyNumber: 7,
      hitForAvg: 70, power: 60, speed: 72, arm: 68, fielding: 66, errorResistance: 64, velocity: 36, control: 32, stamina: 36, stuff: 30,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 54, running: 70, throwing: 70, recovery: 56, wRISP: 66, vsLefty: 62, poise: 68, heater: 32, agile: 72,
      abilities: ["Speed Demon", "Cannon Arm"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Cole", lastName: "Lee", position: "OF", eligibility: "SO", homeState: "MN", hometown: "Prior Lake", jerseyNumber: 9,
      hitForAvg: 58, power: 50, speed: 62, arm: 64, fielding: 60, errorResistance: 58, velocity: 34, control: 30, stamina: 34, stuff: 28,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 42, running: 60, throwing: 66, recovery: 48, wRISP: 54, vsLefty: 50, poise: 56, heater: 30, agile: 64,
      abilities: ["Speed Demon"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Bryce", lastName: "Berzin", position: "DH", eligibility: "JR", homeState: "MN", hometown: "Duluth", jerseyNumber: 20,
      hitForAvg: 66, power: 64, speed: 40, arm: 50, fielding: 42, errorResistance: 40, velocity: 32, control: 28, stamina: 32, stuff: 26,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 14, running: 38, throwing: 52, recovery: 52, wRISP: 64, vsLefty: 60, poise: 64, heater: 28, agile: 42,
      abilities: ["Clutch Gene"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Will", lastName: "Walsh", position: "OF", eligibility: "FR", homeState: "MN", hometown: "Wayzata", jerseyNumber: 26,
      hitForAvg: 42, power: 36, speed: 56, arm: 54, fielding: 46, errorResistance: 42, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 40, vsLHP: 36, grit: 42, stealing: 36, running: 54, throwing: 56, recovery: 38, wRISP: 38, vsLefty: 34, poise: 38, heater: 26, agile: 58,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Cam", lastName: "Caminiti", position: "2B", eligibility: "FR", homeState: "AZ", hometown: "Scottsdale", jerseyNumber: 15,
      hitForAvg: 38, power: 30, speed: 50, arm: 52, fielding: 48, errorResistance: 44, velocity: 28, control: 24, stamina: 28, stuff: 22,
      clutch: 36, vsLHP: 34, grit: 38, stealing: 28, running: 48, throwing: 54, recovery: 34, wRISP: 34, vsLefty: 32, poise: 36, heater: 24, agile: 52,
      abilities: [], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Austin", lastName: "Nye", position: "OF", eligibility: "FR", homeState: "MN", hometown: "Eden Prairie", jerseyNumber: 30,
      hitForAvg: 40, power: 34, speed: 58, arm: 56, fielding: 44, errorResistance: 40, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 36, running: 56, throwing: 58, recovery: 36, wRISP: 36, vsLefty: 34, poise: 38, heater: 26, agile: 60,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Nebraska": [
    // PITCHERS (9)
    { firstName: "Rhett", lastName: "Schroder", position: "P", eligibility: "SR", homeState: "NE", hometown: "Omaha", jerseyNumber: 31,
      hitForAvg: 22, power: 18, speed: 40, arm: 82, fielding: 52, errorResistance: 54, velocity: 84, control: 78, stamina: 80, stuff: 84,
      clutch: 76, vsLHP: 72, grit: 80, stealing: 10, running: 36, throwing: 82, recovery: 72, wRISP: 76, vsLefty: 74, poise: 80, heater: 84, agile: 46,
      abilities: ["Ace", "Strong Starter", "Filthy Breaking Ball"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 7, 6, 5, 0, 0, 0]) },
    { firstName: "Drew", lastName: "Christo", position: "P", eligibility: "JR", homeState: "NE", hometown: "Lincoln", jerseyNumber: 22,
      hitForAvg: 18, power: 14, speed: 40, arm: 76, fielding: 48, errorResistance: 50, velocity: 78, control: 72, stamina: 74, stuff: 76,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 12, running: 36, throwing: 74, recovery: 66, wRISP: 66, vsLefty: 68, poise: 70, heater: 76, agile: 44,
      abilities: ["Strong Starter"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 4, 0, 0, 0]) },
    { firstName: "Emmett", lastName: "Olson", position: "P", eligibility: "SO", homeState: "NE", hometown: "Bellevue", jerseyNumber: 35,
      hitForAvg: 16, power: 12, speed: 42, arm: 72, fielding: 46, errorResistance: 48, velocity: 74, control: 66, stamina: 68, stuff: 72,
      clutch: 60, vsLHP: 58, grit: 62, stealing: 14, running: 38, throwing: 70, recovery: 60, wRISP: 58, vsLefty: 60, poise: 62, heater: 72, agile: 46,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Mason", lastName: "McGregor", position: "P", eligibility: "SR", homeState: "NE", hometown: "Grand Island", jerseyNumber: 38,
      hitForAvg: 20, power: 16, speed: 38, arm: 74, fielding: 50, errorResistance: 52, velocity: 76, control: 74, stamina: 72, stuff: 74,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 10, running: 34, throwing: 72, recovery: 68, wRISP: 70, vsLefty: 70, poise: 74, heater: 74, agile: 44,
      abilities: ["Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 0, 5, 4, 0, 0]) },
    { firstName: "Tyler", lastName: "Martin", position: "P", eligibility: "JR", homeState: "KS", hometown: "Overland Park", jerseyNumber: 28,
      hitForAvg: 18, power: 14, speed: 38, arm: 72, fielding: 46, errorResistance: 48, velocity: 74, control: 70, stamina: 70, stuff: 72,
      clutch: 64, vsLHP: 62, grit: 66, stealing: 10, running: 34, throwing: 70, recovery: 64, wRISP: 62, vsLefty: 64, poise: 66, heater: 72, agile: 42,
      abilities: ["Workhorse"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 5, 0, 0, 0]) },
    { firstName: "Bryce", lastName: "Willits", position: "P", eligibility: "SO", homeState: "NE", hometown: "Kearney", jerseyNumber: 42,
      hitForAvg: 16, power: 12, speed: 40, arm: 68, fielding: 44, errorResistance: 46, velocity: 70, control: 64, stamina: 64, stuff: 68,
      clutch: 56, vsLHP: 54, grit: 58, stealing: 12, running: 36, throwing: 66, recovery: 56, wRISP: 54, vsLefty: 56, poise: 58, heater: 68, agile: 44,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 4, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Matson", position: "P", eligibility: "JR", homeState: "MN", hometown: "Minneapolis", jerseyNumber: 40,
      hitForAvg: 18, power: 14, speed: 40, arm: 70, fielding: 46, errorResistance: 48, velocity: 72, control: 68, stamina: 66, stuff: 70,
      clutch: 62, vsLHP: 60, grit: 64, stealing: 12, running: 36, throwing: 68, recovery: 62, wRISP: 60, vsLefty: 62, poise: 64, heater: 70, agile: 44,
      abilities: ["Fireman"], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 0, 3, 0, 0]) },
    { firstName: "Brayden", lastName: "Marchand", position: "P", eligibility: "SO", homeState: "NE", hometown: "Norfolk", jerseyNumber: 46,
      hitForAvg: 16, power: 12, speed: 42, arm: 66, fielding: 42, errorResistance: 44, velocity: 68, control: 58, stamina: 56, stuff: 66,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 14, running: 40, throwing: 64, recovery: 50, wRISP: 48, vsLefty: 50, poise: 50, heater: 66, agile: 46,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 4, 0, 0, 0]) },
    { firstName: "Drew", lastName: "Yochum", position: "P", eligibility: "SO", homeState: "MO", hometown: "St. Louis", jerseyNumber: 48,
      hitForAvg: 14, power: 10, speed: 40, arm: 64, fielding: 40, errorResistance: 42, velocity: 66, control: 56, stamina: 54, stuff: 64,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 12, running: 38, throwing: 62, recovery: 48, wRISP: 46, vsLefty: 48, poise: 48, heater: 64, agile: 44,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    { firstName: "Caleb", lastName: "Rath", position: "P", eligibility: "JR", homeState: "NE", hometown: "Lincoln", jerseyNumber: 50,
      hitForAvg: 18, power: 14, speed: 38, arm: 70, fielding: 46, errorResistance: 48, velocity: 72, control: 68, stamina: 68, stuff: 70,
      clutch: 62, vsLHP: 60, grit: 64, stealing: 10, running: 34, throwing: 68, recovery: 62, wRISP: 60, vsLefty: 62, poise: 64, heater: 70, agile: 42,
      abilities: [], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Josh", lastName: "Caron", position: "C", eligibility: "JR", homeState: "NE", hometown: "Papillion", jerseyNumber: 12,
      hitForAvg: 64, power: 58, speed: 40, arm: 74, fielding: 72, errorResistance: 70, velocity: 36, control: 32, stamina: 36, stuff: 30,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 18, running: 38, throwing: 76, recovery: 58, wRISP: 66, vsLefty: 62, poise: 68, heater: 32, agile: 44,
      abilities: ["Iron Glove", "Cannon Arm"], potential: "A-", catcherAbility: 74,
      ...noPitches },
    { firstName: "Will", lastName: "Rigney", position: "C", eligibility: "SO", homeState: "IA", hometown: "Cedar Rapids", jerseyNumber: 18,
      hitForAvg: 50, power: 44, speed: 38, arm: 62, fielding: 58, errorResistance: 54, velocity: 32, control: 28, stamina: 34, stuff: 26,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 14, running: 36, throwing: 64, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 28, agile: 40,
      abilities: [], potential: "B", catcherAbility: 58,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Core", lastName: "Jackson", position: "SS", eligibility: "SR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 2,
      hitForAvg: 74, power: 62, speed: 72, arm: 76, fielding: 78, errorResistance: 76, velocity: 38, control: 34, stamina: 38, stuff: 32,
      clutch: 74, vsLHP: 70, grit: 76, stealing: 56, running: 70, throwing: 78, recovery: 60, wRISP: 72, vsLefty: 68, poise: 74, heater: 34, agile: 74,
      abilities: ["Iron Glove", "Speed Demon"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Max", lastName: "Anderson", position: "3B", eligibility: "SR", homeState: "NE", hometown: "Omaha", jerseyNumber: 5,
      hitForAvg: 76, power: 78, speed: 50, arm: 70, fielding: 68, errorResistance: 66, velocity: 36, control: 32, stamina: 38, stuff: 30,
      clutch: 76, vsLHP: 72, grit: 78, stealing: 22, running: 48, throwing: 72, recovery: 60, wRISP: 76, vsLefty: 70, poise: 76, heater: 32, agile: 52,
      abilities: ["Power Hitter", "Clutch Gene"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Tyler", lastName: "Palmer", position: "1B", eligibility: "JR", homeState: "NE", hometown: "Hastings", jerseyNumber: 24,
      hitForAvg: 66, power: 64, speed: 42, arm: 60, fielding: 62, errorResistance: 60, velocity: 34, control: 30, stamina: 34, stuff: 28,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 16, running: 40, throwing: 62, recovery: 54, wRISP: 64, vsLefty: 58, poise: 64, heater: 30, agile: 44,
      abilities: ["Power Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Garrett", lastName: "Anglim", position: "2B", eligibility: "SO", homeState: "NE", hometown: "Fremont", jerseyNumber: 10,
      hitForAvg: 56, power: 44, speed: 58, arm: 60, fielding: 62, errorResistance: 58, velocity: 32, control: 28, stamina: 32, stuff: 26,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 38, running: 56, throwing: 62, recovery: 48, wRISP: 52, vsLefty: 48, poise: 54, heater: 28, agile: 60,
      abilities: ["Table Setter"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Cooper", lastName: "Carlson", position: "SS", eligibility: "FR", homeState: "NE", hometown: "Elkhorn", jerseyNumber: 14,
      hitForAvg: 42, power: 34, speed: 56, arm: 56, fielding: 52, errorResistance: 48, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 34, running: 54, throwing: 58, recovery: 38, wRISP: 38, vsLefty: 36, poise: 40, heater: 26, agile: 58,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Mason", lastName: "Barnett", position: "2B", eligibility: "FR", homeState: "KS", hometown: "Wichita", jerseyNumber: 16,
      hitForAvg: 38, power: 30, speed: 52, arm: 52, fielding: 48, errorResistance: 44, velocity: 28, control: 24, stamina: 28, stuff: 22,
      clutch: 36, vsLHP: 34, grit: 38, stealing: 30, running: 50, throwing: 54, recovery: 34, wRISP: 34, vsLefty: 32, poise: 36, heater: 24, agile: 54,
      abilities: [], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Jake", lastName: "Hjelle", position: "1B", eligibility: "FR", homeState: "MN", hometown: "Rosemount", jerseyNumber: 34,
      hitForAvg: 44, power: 42, speed: 36, arm: 52, fielding: 46, errorResistance: 42, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 42, vsLHP: 38, grit: 44, stealing: 12, running: 34, throwing: 54, recovery: 38, wRISP: 40, vsLefty: 36, poise: 40, heater: 26, agile: 38,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS & DH (7)
    { firstName: "Case", lastName: "Williams", position: "OF", eligibility: "JR", homeState: "NE", hometown: "Columbus", jerseyNumber: 7,
      hitForAvg: 68, power: 58, speed: 66, arm: 70, fielding: 66, errorResistance: 64, velocity: 36, control: 32, stamina: 36, stuff: 30,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 48, running: 64, throwing: 72, recovery: 54, wRISP: 64, vsLefty: 60, poise: 66, heater: 32, agile: 68,
      abilities: ["Speed Demon", "Cannon Arm"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Cam", lastName: "Chick", position: "OF", eligibility: "SR", homeState: "AZ", hometown: "Phoenix", jerseyNumber: 1,
      hitForAvg: 74, power: 72, speed: 62, arm: 68, fielding: 66, errorResistance: 64, velocity: 36, control: 32, stamina: 38, stuff: 30,
      clutch: 74, vsLHP: 70, grit: 76, stealing: 44, running: 60, throwing: 70, recovery: 60, wRISP: 74, vsLefty: 68, poise: 74, heater: 32, agile: 64,
      abilities: ["Power Hitter", "Clutch Gene"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Brice", lastName: "Matthews", position: "DH", eligibility: "JR", homeState: "NE", hometown: "North Platte", jerseyNumber: 20,
      hitForAvg: 64, power: 60, speed: 40, arm: 50, fielding: 42, errorResistance: 40, velocity: 32, control: 28, stamina: 32, stuff: 26,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 14, running: 38, throwing: 52, recovery: 50, wRISP: 62, vsLefty: 58, poise: 62, heater: 28, agile: 42,
      abilities: ["Contact Machine"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Luke", lastName: "Jessen", position: "OF", eligibility: "SO", homeState: "NE", hometown: "Gretna", jerseyNumber: 9,
      hitForAvg: 56, power: 48, speed: 62, arm: 64, fielding: 58, errorResistance: 56, velocity: 34, control: 30, stamina: 34, stuff: 28,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 42, running: 60, throwing: 66, recovery: 48, wRISP: 52, vsLefty: 48, poise: 54, heater: 30, agile: 64,
      abilities: [], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Dylan", lastName: "Deyzel", position: "OF", eligibility: "FR", homeState: "NE", hometown: "La Vista", jerseyNumber: 26,
      hitForAvg: 40, power: 36, speed: 58, arm: 56, fielding: 46, errorResistance: 42, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 36, running: 56, throwing: 58, recovery: 36, wRISP: 36, vsLefty: 34, poise: 38, heater: 26, agile: 60,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Tommy", lastName: "Sacco", position: "OF", eligibility: "FR", homeState: "CO", hometown: "Denver", jerseyNumber: 30,
      hitForAvg: 42, power: 34, speed: 56, arm: 54, fielding: 44, errorResistance: 40, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 40, vsLHP: 36, grit: 42, stealing: 34, running: 54, throwing: 56, recovery: 38, wRISP: 38, vsLefty: 34, poise: 38, heater: 26, agile: 58,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Northwestern": [
    // PITCHERS (9)
    { firstName: "Mike", lastName: "Vasil", position: "P", eligibility: "SR", homeState: "MA", hometown: "Wellesley", jerseyNumber: 31,
      hitForAvg: 22, power: 18, speed: 38, arm: 82, fielding: 52, errorResistance: 54, velocity: 82, control: 80, stamina: 78, stuff: 82,
      clutch: 78, vsLHP: 74, grit: 80, stealing: 10, running: 34, throwing: 80, recovery: 74, wRISP: 76, vsLefty: 76, poise: 82, heater: 80, agile: 44,
      abilities: ["Ace", "Strong Starter", "Workhorse"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [1, 6, 5, 6, 0, 0, 0]) },
    { firstName: "Josh", lastName: "Levy", position: "P", eligibility: "JR", homeState: "IL", hometown: "Highland Park", jerseyNumber: 22,
      hitForAvg: 18, power: 14, speed: 40, arm: 74, fielding: 48, errorResistance: 50, velocity: 76, control: 72, stamina: 72, stuff: 74,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 12, running: 36, throwing: 72, recovery: 64, wRISP: 64, vsLefty: 66, poise: 68, heater: 74, agile: 44,
      abilities: ["Strong Starter"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 6, 4, 0, 0, 0]) },
    { firstName: "Ty", lastName: "Cummings", position: "P", eligibility: "SO", homeState: "IL", hometown: "Libertyville", jerseyNumber: 35,
      hitForAvg: 16, power: 12, speed: 42, arm: 70, fielding: 44, errorResistance: 46, velocity: 72, control: 66, stamina: 68, stuff: 70,
      clutch: 58, vsLHP: 56, grit: 60, stealing: 14, running: 38, throwing: 68, recovery: 58, wRISP: 56, vsLefty: 58, poise: 60, heater: 70, agile: 46,
      abilities: ["Explosive Fastball"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Luke", lastName: "Dauch", position: "P", eligibility: "SR", homeState: "OH", hometown: "Columbus", jerseyNumber: 38,
      hitForAvg: 20, power: 16, speed: 40, arm: 74, fielding: 50, errorResistance: 52, velocity: 76, control: 74, stamina: 70, stuff: 74,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 12, running: 36, throwing: 72, recovery: 68, wRISP: 70, vsLefty: 70, poise: 74, heater: 74, agile: 44,
      abilities: ["Fireman", "Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 4, 4, 0, 0]) },
    { firstName: "Mac", lastName: "Leith", position: "P", eligibility: "JR", homeState: "IL", hometown: "Winnetka", jerseyNumber: 28,
      hitForAvg: 18, power: 14, speed: 38, arm: 72, fielding: 46, errorResistance: 48, velocity: 74, control: 70, stamina: 70, stuff: 72,
      clutch: 64, vsLHP: 62, grit: 66, stealing: 10, running: 34, throwing: 70, recovery: 64, wRISP: 62, vsLefty: 64, poise: 66, heater: 72, agile: 42,
      abilities: ["Workhorse"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 5, 0, 0, 0]) },
    { firstName: "Owen", lastName: "Murphy", position: "P", eligibility: "SO", homeState: "IL", hometown: "Glenview", jerseyNumber: 42,
      hitForAvg: 16, power: 12, speed: 40, arm: 68, fielding: 44, errorResistance: 46, velocity: 70, control: 64, stamina: 64, stuff: 68,
      clutch: 56, vsLHP: 54, grit: 58, stealing: 12, running: 36, throwing: 66, recovery: 56, wRISP: 54, vsLefty: 56, poise: 58, heater: 68, agile: 44,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 5, 0, 0, 0]) },
    { firstName: "Vince", lastName: "Biegel", position: "P", eligibility: "JR", homeState: "WI", hometown: "Hartland", jerseyNumber: 40,
      hitForAvg: 18, power: 14, speed: 40, arm: 70, fielding: 46, errorResistance: 48, velocity: 72, control: 68, stamina: 66, stuff: 70,
      clutch: 62, vsLHP: 60, grit: 64, stealing: 12, running: 36, throwing: 68, recovery: 62, wRISP: 60, vsLefty: 62, poise: 64, heater: 70, agile: 44,
      abilities: [], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 0, 3, 0, 0]) },
    { firstName: "Drew", lastName: "Stone", position: "P", eligibility: "SO", homeState: "IL", hometown: "Naperville", jerseyNumber: 46,
      hitForAvg: 16, power: 12, speed: 42, arm: 66, fielding: 42, errorResistance: 44, velocity: 68, control: 58, stamina: 56, stuff: 66,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 14, running: 40, throwing: 64, recovery: 50, wRISP: 48, vsLefty: 50, poise: 50, heater: 66, agile: 46,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 4, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Thome", position: "P", eligibility: "SO", homeState: "IL", hometown: "Barrington", jerseyNumber: 48,
      hitForAvg: 14, power: 10, speed: 40, arm: 64, fielding: 40, errorResistance: 42, velocity: 66, control: 56, stamina: 54, stuff: 64,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 12, running: 38, throwing: 62, recovery: 48, wRISP: 46, vsLefty: 48, poise: 48, heater: 64, agile: 44,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    { firstName: "Ben", lastName: "Steinberg", position: "P", eligibility: "JR", homeState: "IL", hometown: "Skokie", jerseyNumber: 50,
      hitForAvg: 18, power: 14, speed: 38, arm: 70, fielding: 46, errorResistance: 48, velocity: 72, control: 68, stamina: 68, stuff: 70,
      clutch: 62, vsLHP: 60, grit: 64, stealing: 10, running: 34, throwing: 68, recovery: 62, wRISP: 60, vsLefty: 62, poise: 64, heater: 70, agile: 42,
      abilities: [], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Michael", lastName: "Trautwein", position: "C", eligibility: "JR", homeState: "IL", hometown: "Hinsdale", jerseyNumber: 12,
      hitForAvg: 62, power: 56, speed: 40, arm: 72, fielding: 70, errorResistance: 68, velocity: 36, control: 32, stamina: 36, stuff: 30,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 18, running: 38, throwing: 74, recovery: 56, wRISP: 64, vsLefty: 60, poise: 66, heater: 32, agile: 44,
      abilities: ["Iron Glove"], potential: "B", catcherAbility: 70,
      ...noPitches },
    { firstName: "Leo", lastName: "Nierenberg", position: "C", eligibility: "SO", homeState: "IL", hometown: "Wilmette", jerseyNumber: 18,
      hitForAvg: 50, power: 42, speed: 38, arm: 62, fielding: 58, errorResistance: 54, velocity: 32, control: 28, stamina: 34, stuff: 26,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 14, running: 36, throwing: 64, recovery: 46, wRISP: 50, vsLefty: 46, poise: 50, heater: 28, agile: 40,
      abilities: [], potential: "B", catcherAbility: 58,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Vincent", lastName: "Biegel", position: "SS", eligibility: "SR", homeState: "WI", hometown: "Hartland", jerseyNumber: 3,
      hitForAvg: 72, power: 58, speed: 64, arm: 74, fielding: 76, errorResistance: 74, velocity: 36, control: 32, stamina: 36, stuff: 30,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 46, running: 62, throwing: 76, recovery: 58, wRISP: 70, vsLefty: 66, poise: 72, heater: 32, agile: 66,
      abilities: ["Iron Glove", "Table Setter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "David", lastName: "Dunn", position: "1B", eligibility: "SR", homeState: "CA", hometown: "San Diego", jerseyNumber: 5,
      hitForAvg: 74, power: 76, speed: 44, arm: 62, fielding: 66, errorResistance: 64, velocity: 36, control: 32, stamina: 38, stuff: 30,
      clutch: 74, vsLHP: 70, grit: 76, stealing: 16, running: 42, throwing: 64, recovery: 58, wRISP: 74, vsLefty: 68, poise: 74, heater: 32, agile: 46,
      abilities: ["Power Hitter", "Clutch Gene"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Anthony", lastName: "Calarco", position: "3B", eligibility: "SR", homeState: "IL", hometown: "Elmhurst", jerseyNumber: 8,
      hitForAvg: 70, power: 64, speed: 50, arm: 68, fielding: 66, errorResistance: 64, velocity: 36, control: 32, stamina: 36, stuff: 30,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 22, running: 48, throwing: 70, recovery: 56, wRISP: 68, vsLefty: 64, poise: 70, heater: 32, agile: 52,
      abilities: ["Contact Machine"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Jake", lastName: "Artz", position: "2B", eligibility: "JR", homeState: "IL", hometown: "Deerfield", jerseyNumber: 10,
      hitForAvg: 64, power: 50, speed: 58, arm: 62, fielding: 66, errorResistance: 64, velocity: 34, control: 30, stamina: 34, stuff: 28,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 38, running: 56, throwing: 64, recovery: 52, wRISP: 60, vsLefty: 56, poise: 62, heater: 30, agile: 60,
      abilities: ["Table Setter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Drew", lastName: "Gray", position: "SS", eligibility: "FR", homeState: "IL", hometown: "Park Ridge", jerseyNumber: 14,
      hitForAvg: 42, power: 34, speed: 54, arm: 56, fielding: 52, errorResistance: 48, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 32, running: 52, throwing: 58, recovery: 38, wRISP: 38, vsLefty: 36, poise: 40, heater: 26, agile: 56,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Sam", lastName: "Jackson", position: "2B", eligibility: "FR", homeState: "IN", hometown: "Carmel", jerseyNumber: 16,
      hitForAvg: 38, power: 30, speed: 50, arm: 52, fielding: 48, errorResistance: 44, velocity: 28, control: 24, stamina: 28, stuff: 22,
      clutch: 36, vsLHP: 34, grit: 38, stealing: 28, running: 48, throwing: 54, recovery: 34, wRISP: 34, vsLefty: 32, poise: 36, heater: 24, agile: 52,
      abilities: [], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Jace", lastName: "Johnson", position: "1B", eligibility: "FR", homeState: "OH", hometown: "Dublin", jerseyNumber: 34,
      hitForAvg: 44, power: 42, speed: 36, arm: 52, fielding: 46, errorResistance: 42, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 42, vsLHP: 38, grit: 44, stealing: 12, running: 34, throwing: 54, recovery: 38, wRISP: 40, vsLefty: 36, poise: 40, heater: 26, agile: 38,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS & DH (5)
    { firstName: "Ethan", lastName: "O'Donnell", position: "OF", eligibility: "JR", homeState: "IL", hometown: "Lake Forest", jerseyNumber: 7,
      hitForAvg: 68, power: 58, speed: 66, arm: 70, fielding: 66, errorResistance: 64, velocity: 36, control: 32, stamina: 36, stuff: 30,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 48, running: 64, throwing: 72, recovery: 54, wRISP: 64, vsLefty: 60, poise: 66, heater: 32, agile: 68,
      abilities: ["Speed Demon", "Cannon Arm"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Bennett", lastName: "Hostetler", position: "OF", eligibility: "JR", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 9,
      hitForAvg: 64, power: 56, speed: 60, arm: 66, fielding: 62, errorResistance: 60, velocity: 34, control: 30, stamina: 34, stuff: 28,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 40, running: 58, throwing: 68, recovery: 52, wRISP: 60, vsLefty: 56, poise: 62, heater: 30, agile: 62,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Cam", lastName: "Smith", position: "OF", eligibility: "SO", homeState: "IL", hometown: "Evanston", jerseyNumber: 11,
      hitForAvg: 56, power: 48, speed: 62, arm: 64, fielding: 58, errorResistance: 56, velocity: 34, control: 30, stamina: 34, stuff: 28,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 42, running: 60, throwing: 66, recovery: 48, wRISP: 52, vsLefty: 48, poise: 54, heater: 30, agile: 64,
      abilities: ["Speed Demon"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Shawn", lastName: "Goosenberg", position: "DH", eligibility: "JR", homeState: "IL", hometown: "Buffalo Grove", jerseyNumber: 20,
      hitForAvg: 66, power: 62, speed: 42, arm: 52, fielding: 44, errorResistance: 42, velocity: 32, control: 28, stamina: 32, stuff: 26,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 16, running: 40, throwing: 54, recovery: 52, wRISP: 64, vsLefty: 60, poise: 64, heater: 28, agile: 44,
      abilities: ["Clutch Gene"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Nick", lastName: "Paciorek", position: "OF", eligibility: "FR", homeState: "MI", hometown: "Birmingham", jerseyNumber: 26,
      hitForAvg: 40, power: 36, speed: 56, arm: 54, fielding: 46, errorResistance: 42, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 34, running: 54, throwing: 56, recovery: 36, wRISP: 36, vsLefty: 34, poise: 38, heater: 26, agile: 58,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Tommy", lastName: "Nance", position: "OF", eligibility: "FR", homeState: "IL", hometown: "Wheaton", jerseyNumber: 30,
      hitForAvg: 42, power: 34, speed: 58, arm: 56, fielding: 44, errorResistance: 40, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 40, vsLHP: 36, grit: 42, stealing: 36, running: 56, throwing: 58, recovery: 38, wRISP: 38, vsLefty: 34, poise: 38, heater: 26, agile: 60,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Ohio State": [
    // PITCHERS (9)
    { firstName: "Gavin", lastName: "Bruni", position: "P", eligibility: "JR", homeState: "OH", hometown: "Mason", jerseyNumber: 17,
      hitForAvg: 20, power: 15, speed: 42, arm: 80, fielding: 50, errorResistance: 52, velocity: 82, control: 76, stamina: 78, stuff: 80,
      clutch: 74, vsLHP: 70, grit: 76, stealing: 10, running: 38, throwing: 80, recovery: 70, wRISP: 72, vsLefty: 74, poise: 76, heater: 80, agile: 48,
      abilities: ["Ace", "Strong Starter", "Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 7, 5, 6, 0, 0, 0]) },
    { firstName: "Isaiah", lastName: "Coupet", position: "P", eligibility: "SR", homeState: "OH", hometown: "Columbus", jerseyNumber: 31,
      hitForAvg: 22, power: 18, speed: 40, arm: 78, fielding: 50, errorResistance: 54, velocity: 80, control: 76, stamina: 74, stuff: 78,
      clutch: 76, vsLHP: 72, grit: 78, stealing: 10, running: 36, throwing: 76, recovery: 72, wRISP: 74, vsLefty: 74, poise: 78, heater: 78, agile: 44,
      abilities: ["Filthy Breaking Ball", "Wipeout Slider"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 8, 5, 4, 0, 0, 0]) },
    { firstName: "Nate", lastName: "Haberthier", position: "P", eligibility: "SO", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 35,
      hitForAvg: 16, power: 12, speed: 42, arm: 72, fielding: 46, errorResistance: 48, velocity: 74, control: 66, stamina: 68, stuff: 72,
      clutch: 60, vsLHP: 58, grit: 62, stealing: 14, running: 38, throwing: 70, recovery: 60, wRISP: 58, vsLefty: 60, poise: 62, heater: 72, agile: 46,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Johnson", position: "P", eligibility: "SR", homeState: "OH", hometown: "Westerville", jerseyNumber: 38,
      hitForAvg: 20, power: 16, speed: 38, arm: 74, fielding: 50, errorResistance: 52, velocity: 76, control: 74, stamina: 60, stuff: 74,
      clutch: 74, vsLHP: 68, grit: 76, stealing: 10, running: 34, throwing: 72, recovery: 70, wRISP: 72, vsLefty: 70, poise: 76, heater: 74, agile: 44,
      abilities: ["Fireman", "Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 5, 4, 0, 0]) },
    { firstName: "Wyatt", lastName: "Loncar", position: "P", eligibility: "JR", homeState: "OH", hometown: "Akron", jerseyNumber: 28,
      hitForAvg: 18, power: 14, speed: 38, arm: 72, fielding: 46, errorResistance: 48, velocity: 74, control: 70, stamina: 72, stuff: 72,
      clutch: 64, vsLHP: 62, grit: 66, stealing: 10, running: 34, throwing: 70, recovery: 64, wRISP: 62, vsLefty: 64, poise: 66, heater: 72, agile: 42,
      abilities: ["Workhorse"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 5, 0, 0, 0]) },
    { firstName: "TJ", lastName: "Brock", position: "P", eligibility: "SO", homeState: "OH", hometown: "Dayton", jerseyNumber: 42,
      hitForAvg: 16, power: 12, speed: 40, arm: 68, fielding: 44, errorResistance: 46, velocity: 70, control: 64, stamina: 64, stuff: 68,
      clutch: 56, vsLHP: 54, grit: 58, stealing: 12, running: 36, throwing: 66, recovery: 56, wRISP: 54, vsLefty: 56, poise: 58, heater: 68, agile: 44,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 5, 0, 0, 0]) },
    { firstName: "Seth", lastName: "Lonsway", position: "P", eligibility: "JR", homeState: "OH", hometown: "Celina", jerseyNumber: 22,
      hitForAvg: 18, power: 14, speed: 40, arm: 70, fielding: 46, errorResistance: 48, velocity: 72, control: 68, stamina: 66, stuff: 70,
      clutch: 62, vsLHP: 60, grit: 64, stealing: 12, running: 36, throwing: 68, recovery: 62, wRISP: 60, vsLefty: 62, poise: 64, heater: 70, agile: 44,
      abilities: [], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 0, 4, 0, 0]) },
    { firstName: "Cole", lastName: "Snyder", position: "P", eligibility: "SO", homeState: "PA", hometown: "Pittsburgh", jerseyNumber: 46,
      hitForAvg: 16, power: 12, speed: 42, arm: 66, fielding: 42, errorResistance: 44, velocity: 68, control: 58, stamina: 56, stuff: 66,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 14, running: 40, throwing: 64, recovery: 50, wRISP: 48, vsLefty: 50, poise: 50, heater: 66, agile: 46,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 4, 0, 0, 0]) },
    { firstName: "Kyle", lastName: "Brnovich", position: "P", eligibility: "SO", homeState: "AZ", hometown: "Chandler", jerseyNumber: 48,
      hitForAvg: 14, power: 10, speed: 40, arm: 64, fielding: 40, errorResistance: 42, velocity: 66, control: 56, stamina: 54, stuff: 64,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 12, running: 38, throwing: 62, recovery: 48, wRISP: 46, vsLefty: 48, poise: 48, heater: 64, agile: 44,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    { firstName: "Will", lastName: "Pfennig", position: "P", eligibility: "JR", homeState: "OH", hometown: "Cleveland", jerseyNumber: 50,
      hitForAvg: 18, power: 14, speed: 38, arm: 70, fielding: 46, errorResistance: 48, velocity: 72, control: 68, stamina: 68, stuff: 70,
      clutch: 62, vsLHP: 60, grit: 64, stealing: 10, running: 34, throwing: 68, recovery: 62, wRISP: 60, vsLefty: 62, poise: 64, heater: 70, agile: 42,
      abilities: [], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Tyler", lastName: "Pettorini", position: "C", eligibility: "JR", homeState: "OH", hometown: "Medina", jerseyNumber: 12,
      hitForAvg: 64, power: 58, speed: 40, arm: 74, fielding: 72, errorResistance: 70, velocity: 36, control: 32, stamina: 36, stuff: 30,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 18, running: 38, throwing: 76, recovery: 58, wRISP: 66, vsLefty: 62, poise: 68, heater: 32, agile: 44,
      abilities: ["Iron Glove", "Cannon Arm"], potential: "A-", catcherAbility: 74,
      ...noPitches },
    { firstName: "Archer", lastName: "Brookman", position: "C", eligibility: "SO", homeState: "OH", hometown: "Dublin", jerseyNumber: 18,
      hitForAvg: 52, power: 44, speed: 38, arm: 64, fielding: 60, errorResistance: 56, velocity: 32, control: 28, stamina: 34, stuff: 26,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 14, running: 36, throwing: 66, recovery: 48, wRISP: 52, vsLefty: 48, poise: 52, heater: 28, agile: 40,
      abilities: [], potential: "B", catcherAbility: 62,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Marcus", lastName: "Ernst", position: "2B", eligibility: "SR", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 2,
      hitForAvg: 74, power: 58, speed: 60, arm: 66, fielding: 72, errorResistance: 70, velocity: 34, control: 30, stamina: 36, stuff: 28,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 42, running: 58, throwing: 68, recovery: 58, wRISP: 72, vsLefty: 66, poise: 72, heater: 30, agile: 62,
      abilities: ["Table Setter", "Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Henry", lastName: "Kaczmar", position: "3B", eligibility: "SR", homeState: "MI", hometown: "Grosse Pointe", jerseyNumber: 5,
      hitForAvg: 76, power: 70, speed: 50, arm: 70, fielding: 68, errorResistance: 66, velocity: 36, control: 32, stamina: 38, stuff: 30,
      clutch: 76, vsLHP: 72, grit: 78, stealing: 22, running: 48, throwing: 72, recovery: 60, wRISP: 76, vsLefty: 70, poise: 76, heater: 32, agile: 52,
      abilities: ["Power Hitter", "Clutch Gene"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Nick", lastName: "Erwin", position: "SS", eligibility: "JR", homeState: "OH", hometown: "Centerville", jerseyNumber: 3,
      hitForAvg: 66, power: 52, speed: 66, arm: 72, fielding: 74, errorResistance: 72, velocity: 36, control: 32, stamina: 34, stuff: 28,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 48, running: 64, throwing: 74, recovery: 54, wRISP: 62, vsLefty: 58, poise: 64, heater: 32, agile: 68,
      abilities: ["Iron Glove", "Speed Demon"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Josh", lastName: "McAlister", position: "1B", eligibility: "JR", homeState: "TN", hometown: "Nashville", jerseyNumber: 24,
      hitForAvg: 66, power: 64, speed: 42, arm: 60, fielding: 62, errorResistance: 60, velocity: 34, control: 30, stamina: 34, stuff: 28,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 16, running: 40, throwing: 62, recovery: 54, wRISP: 64, vsLefty: 58, poise: 64, heater: 30, agile: 44,
      abilities: ["Power Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Josh", lastName: "Todys", position: "SS", eligibility: "FR", homeState: "OH", hometown: "Toledo", jerseyNumber: 14,
      hitForAvg: 42, power: 34, speed: 56, arm: 56, fielding: 52, errorResistance: 48, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 34, running: 54, throwing: 58, recovery: 38, wRISP: 38, vsLefty: 36, poise: 40, heater: 26, agile: 58,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Jack", lastName: "Arend", position: "2B", eligibility: "FR", homeState: "OH", hometown: "Westlake", jerseyNumber: 16,
      hitForAvg: 38, power: 30, speed: 50, arm: 52, fielding: 48, errorResistance: 44, velocity: 28, control: 24, stamina: 28, stuff: 22,
      clutch: 36, vsLHP: 34, grit: 38, stealing: 28, running: 48, throwing: 54, recovery: 34, wRISP: 34, vsLefty: 32, poise: 36, heater: 24, agile: 52,
      abilities: [], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Tyler", lastName: "Johnson", position: "1B", eligibility: "FR", homeState: "OH", hometown: "Youngstown", jerseyNumber: 34,
      hitForAvg: 44, power: 42, speed: 36, arm: 52, fielding: 46, errorResistance: 42, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 42, vsLHP: 38, grit: 44, stealing: 12, running: 34, throwing: 54, recovery: 38, wRISP: 40, vsLefty: 36, poise: 40, heater: 26, agile: 38,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS & DH (5)
    { firstName: "Trey", lastName: "Lipsey", position: "OF", eligibility: "JR", homeState: "GA", hometown: "Savannah", jerseyNumber: 7,
      hitForAvg: 68, power: 60, speed: 72, arm: 68, fielding: 66, errorResistance: 64, velocity: 36, control: 32, stamina: 36, stuff: 30,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 54, running: 70, throwing: 70, recovery: 54, wRISP: 64, vsLefty: 60, poise: 66, heater: 32, agile: 72,
      abilities: ["Speed Demon", "Cannon Arm"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Kade", lastName: "Kern", position: "OF", eligibility: "SR", homeState: "OH", hometown: "Archbold", jerseyNumber: 1,
      hitForAvg: 74, power: 68, speed: 62, arm: 68, fielding: 68, errorResistance: 66, velocity: 36, control: 32, stamina: 38, stuff: 30,
      clutch: 74, vsLHP: 70, grit: 76, stealing: 44, running: 60, throwing: 70, recovery: 60, wRISP: 74, vsLefty: 68, poise: 74, heater: 32, agile: 64,
      abilities: ["Power Hitter", "Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Mitchell", lastName: "Okuley", position: "OF", eligibility: "SO", homeState: "OH", hometown: "Powell", jerseyNumber: 9,
      hitForAvg: 58, power: 50, speed: 62, arm: 66, fielding: 60, errorResistance: 58, velocity: 34, control: 30, stamina: 34, stuff: 28,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 42, running: 60, throwing: 68, recovery: 48, wRISP: 54, vsLefty: 50, poise: 56, heater: 30, agile: 64,
      abilities: [], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Colton", lastName: "Bauer", position: "DH", eligibility: "JR", homeState: "OH", hometown: "Mentor", jerseyNumber: 20,
      hitForAvg: 64, power: 62, speed: 40, arm: 50, fielding: 42, errorResistance: 40, velocity: 32, control: 28, stamina: 32, stuff: 26,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 14, running: 38, throwing: 52, recovery: 50, wRISP: 62, vsLefty: 58, poise: 62, heater: 28, agile: 42,
      abilities: ["Clutch Gene"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Gavin", lastName: "Turley", position: "OF", eligibility: "FR", homeState: "AZ", hometown: "Gilbert", jerseyNumber: 26,
      hitForAvg: 40, power: 36, speed: 58, arm: 56, fielding: 46, errorResistance: 42, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 36, running: 56, throwing: 58, recovery: 36, wRISP: 36, vsLefty: 34, poise: 38, heater: 26, agile: 60,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Brady", lastName: "Lyons", position: "OF", eligibility: "FR", homeState: "OH", hometown: "Avon", jerseyNumber: 30,
      hitForAvg: 42, power: 34, speed: 56, arm: 54, fielding: 44, errorResistance: 40, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 40, vsLHP: 36, grit: 42, stealing: 34, running: 54, throwing: 56, recovery: 38, wRISP: 38, vsLefty: 34, poise: 38, heater: 26, agile: 58,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Oregon": [
    // PITCHERS (9)
    { firstName: "RJ", lastName: "Gordon", position: "P", eligibility: "JR", homeState: "OR", hometown: "Portland", jerseyNumber: 17,
      hitForAvg: 20, power: 15, speed: 42, arm: 80, fielding: 50, errorResistance: 52, velocity: 84, control: 76, stamina: 78, stuff: 82,
      clutch: 74, vsLHP: 70, grit: 76, stealing: 10, running: 38, throwing: 80, recovery: 70, wRISP: 72, vsLefty: 74, poise: 76, heater: 82, agile: 48,
      abilities: ["Ace", "Strong Starter", "Filthy Breaking Ball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 7, 6, 5, 0, 0, 0]) },
    { firstName: "Matt", lastName: "Dallas", position: "P", eligibility: "SR", homeState: "CA", hometown: "San Jose", jerseyNumber: 31,
      hitForAvg: 22, power: 18, speed: 38, arm: 78, fielding: 50, errorResistance: 54, velocity: 80, control: 76, stamina: 76, stuff: 78,
      clutch: 76, vsLHP: 72, grit: 78, stealing: 10, running: 34, throwing: 76, recovery: 72, wRISP: 74, vsLefty: 74, poise: 78, heater: 78, agile: 44,
      abilities: ["Strong Starter", "Workhorse"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [1, 6, 5, 5, 0, 0, 0]) },
    { firstName: "Jace", lastName: "Stoffal", position: "P", eligibility: "SO", homeState: "OR", hometown: "Bend", jerseyNumber: 35,
      hitForAvg: 16, power: 12, speed: 42, arm: 72, fielding: 46, errorResistance: 48, velocity: 74, control: 66, stamina: 68, stuff: 72,
      clutch: 60, vsLHP: 58, grit: 62, stealing: 14, running: 38, throwing: 70, recovery: 60, wRISP: 58, vsLefty: 60, poise: 62, heater: 72, agile: 46,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Jackson", lastName: "Ferris", position: "P", eligibility: "JR", homeState: "CA", hometown: "Thousand Oaks", jerseyNumber: 22,
      hitForAvg: 18, power: 14, speed: 40, arm: 76, fielding: 48, errorResistance: 50, velocity: 78, control: 72, stamina: 74, stuff: 76,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 12, running: 36, throwing: 74, recovery: 66, wRISP: 66, vsLefty: 68, poise: 70, heater: 76, agile: 44,
      abilities: ["Wipeout Slider"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 8, 5, 4, 0, 0, 0]) },
    { firstName: "Kolby", lastName: "Somers", position: "P", eligibility: "SR", homeState: "OR", hometown: "Eugene", jerseyNumber: 38,
      hitForAvg: 20, power: 16, speed: 40, arm: 74, fielding: 50, errorResistance: 52, velocity: 76, control: 74, stamina: 72, stuff: 74,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 12, running: 36, throwing: 72, recovery: 68, wRISP: 70, vsLefty: 70, poise: 74, heater: 74, agile: 44,
      abilities: ["Fireman", "Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 5, 4, 0, 0]) },
    { firstName: "Nico", lastName: "Tellache", position: "P", eligibility: "JR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 28,
      hitForAvg: 18, power: 14, speed: 38, arm: 72, fielding: 46, errorResistance: 48, velocity: 74, control: 70, stamina: 70, stuff: 72,
      clutch: 64, vsLHP: 62, grit: 66, stealing: 10, running: 34, throwing: 70, recovery: 64, wRISP: 62, vsLefty: 64, poise: 66, heater: 72, agile: 42,
      abilities: ["Workhorse"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 5, 0, 0, 0]) },
    { firstName: "Wyatt", lastName: "Hoffman", position: "P", eligibility: "SO", homeState: "WA", hometown: "Seattle", jerseyNumber: 42,
      hitForAvg: 16, power: 12, speed: 40, arm: 68, fielding: 44, errorResistance: 46, velocity: 70, control: 64, stamina: 64, stuff: 68,
      clutch: 56, vsLHP: 54, grit: 58, stealing: 12, running: 36, throwing: 66, recovery: 56, wRISP: 54, vsLefty: 56, poise: 58, heater: 68, agile: 44,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 5, 0, 0, 0]) },
    { firstName: "Brennan", lastName: "Milone", position: "P", eligibility: "SO", homeState: "CA", hometown: "Fresno", jerseyNumber: 46,
      hitForAvg: 16, power: 12, speed: 42, arm: 66, fielding: 42, errorResistance: 44, velocity: 68, control: 58, stamina: 56, stuff: 66,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 14, running: 40, throwing: 64, recovery: 50, wRISP: 48, vsLefty: 50, poise: 50, heater: 66, agile: 46,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 4, 0, 0, 0]) },
    { firstName: "Keenan", lastName: "Taylor", position: "P", eligibility: "SO", homeState: "OR", hometown: "Salem", jerseyNumber: 48,
      hitForAvg: 14, power: 10, speed: 40, arm: 64, fielding: 40, errorResistance: 42, velocity: 66, control: 56, stamina: 54, stuff: 64,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 12, running: 38, throwing: 62, recovery: 48, wRISP: 46, vsLefty: 48, poise: 48, heater: 64, agile: 44,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    { firstName: "Sam", lastName: "Novitske", position: "P", eligibility: "JR", homeState: "OR", hometown: "Lake Oswego", jerseyNumber: 50,
      hitForAvg: 18, power: 14, speed: 38, arm: 70, fielding: 46, errorResistance: 48, velocity: 72, control: 68, stamina: 68, stuff: 70,
      clutch: 62, vsLHP: 60, grit: 64, stealing: 10, running: 34, throwing: 68, recovery: 62, wRISP: 60, vsLefty: 62, poise: 64, heater: 70, agile: 42,
      abilities: [], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Bennett", lastName: "Thompson", position: "C", eligibility: "JR", homeState: "OR", hometown: "Lake Oswego", jerseyNumber: 12,
      hitForAvg: 62, power: 56, speed: 40, arm: 74, fielding: 72, errorResistance: 70, velocity: 36, control: 32, stamina: 36, stuff: 30,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 18, running: 38, throwing: 76, recovery: 58, wRISP: 66, vsLefty: 62, poise: 68, heater: 32, agile: 44,
      abilities: ["Iron Glove", "Cannon Arm"], potential: "A-", catcherAbility: 74,
      ...noPitches },
    { firstName: "Tyler", lastName: "Mack", position: "C", eligibility: "SO", homeState: "WA", hometown: "Tacoma", jerseyNumber: 18,
      hitForAvg: 52, power: 44, speed: 38, arm: 64, fielding: 60, errorResistance: 56, velocity: 32, control: 28, stamina: 34, stuff: 26,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 14, running: 36, throwing: 66, recovery: 48, wRISP: 52, vsLefty: 48, poise: 52, heater: 28, agile: 40,
      abilities: [], potential: "B", catcherAbility: 60,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Josh", lastName: "Kasevich", position: "2B", eligibility: "SR", homeState: "OR", hometown: "Tigard", jerseyNumber: 2,
      hitForAvg: 74, power: 56, speed: 58, arm: 66, fielding: 74, errorResistance: 72, velocity: 34, control: 30, stamina: 36, stuff: 28,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 40, running: 56, throwing: 68, recovery: 58, wRISP: 72, vsLefty: 66, poise: 72, heater: 30, agile: 60,
      abilities: ["Iron Glove", "Table Setter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Kenyon", lastName: "Yovan", position: "3B", eligibility: "SR", homeState: "OR", hometown: "Springfield", jerseyNumber: 5,
      hitForAvg: 72, power: 74, speed: 48, arm: 70, fielding: 66, errorResistance: 64, velocity: 36, control: 32, stamina: 38, stuff: 30,
      clutch: 74, vsLHP: 70, grit: 76, stealing: 18, running: 46, throwing: 72, recovery: 58, wRISP: 74, vsLefty: 68, poise: 74, heater: 32, agile: 50,
      abilities: ["Power Hitter", "Clutch Gene"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jacob", lastName: "Walsh", position: "1B", eligibility: "JR", homeState: "CA", hometown: "Newport Beach", jerseyNumber: 24,
      hitForAvg: 68, power: 66, speed: 44, arm: 62, fielding: 64, errorResistance: 62, velocity: 34, control: 30, stamina: 34, stuff: 28,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 16, running: 42, throwing: 64, recovery: 56, wRISP: 66, vsLefty: 60, poise: 66, heater: 30, agile: 46,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jack", lastName: "Scanlon", position: "SS", eligibility: "JR", homeState: "CA", hometown: "Encinitas", jerseyNumber: 3,
      hitForAvg: 66, power: 52, speed: 66, arm: 72, fielding: 74, errorResistance: 72, velocity: 36, control: 32, stamina: 34, stuff: 28,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 48, running: 64, throwing: 74, recovery: 54, wRISP: 62, vsLefty: 58, poise: 64, heater: 32, agile: 68,
      abilities: ["Iron Glove", "Speed Demon"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Bryce", lastName: "Boettcher", position: "SS", eligibility: "FR", homeState: "OR", hometown: "Corvallis", jerseyNumber: 14,
      hitForAvg: 42, power: 34, speed: 56, arm: 56, fielding: 52, errorResistance: 48, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 34, running: 54, throwing: 58, recovery: 38, wRISP: 38, vsLefty: 36, poise: 40, heater: 26, agile: 58,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "AJ", lastName: "Balta", position: "2B", eligibility: "FR", homeState: "CA", hometown: "Irvine", jerseyNumber: 16,
      hitForAvg: 38, power: 30, speed: 52, arm: 52, fielding: 48, errorResistance: 44, velocity: 28, control: 24, stamina: 28, stuff: 22,
      clutch: 36, vsLHP: 34, grit: 38, stealing: 30, running: 50, throwing: 54, recovery: 34, wRISP: 34, vsLefty: 32, poise: 36, heater: 24, agile: 54,
      abilities: [], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "Campos", position: "1B", eligibility: "FR", homeState: "CA", hometown: "Bakersfield", jerseyNumber: 34,
      hitForAvg: 44, power: 42, speed: 36, arm: 52, fielding: 46, errorResistance: 42, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 42, vsLHP: 38, grit: 44, stealing: 12, running: 34, throwing: 54, recovery: 38, wRISP: 40, vsLefty: 36, poise: 40, heater: 26, agile: 38,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS & DH (5)
    { firstName: "Drew", lastName: "Cowley", position: "OF", eligibility: "SR", homeState: "OR", hometown: "Medford", jerseyNumber: 1,
      hitForAvg: 76, power: 70, speed: 64, arm: 70, fielding: 68, errorResistance: 66, velocity: 36, control: 32, stamina: 38, stuff: 30,
      clutch: 76, vsLHP: 72, grit: 78, stealing: 46, running: 62, throwing: 72, recovery: 60, wRISP: 76, vsLefty: 70, poise: 76, heater: 32, agile: 66,
      abilities: ["Power Hitter", "Cannon Arm"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Tanner", lastName: "Smith", position: "OF", eligibility: "JR", homeState: "OR", hometown: "Hillsboro", jerseyNumber: 7,
      hitForAvg: 68, power: 58, speed: 70, arm: 68, fielding: 66, errorResistance: 64, velocity: 36, control: 32, stamina: 36, stuff: 30,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 52, running: 68, throwing: 70, recovery: 54, wRISP: 64, vsLefty: 60, poise: 66, heater: 32, agile: 72,
      abilities: ["Speed Demon", "Cannon Arm"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Colby", lastName: "Shade", position: "OF", eligibility: "SO", homeState: "WA", hometown: "Vancouver", jerseyNumber: 9,
      hitForAvg: 58, power: 52, speed: 64, arm: 66, fielding: 60, errorResistance: 58, velocity: 34, control: 30, stamina: 34, stuff: 28,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 44, running: 62, throwing: 68, recovery: 48, wRISP: 54, vsLefty: 50, poise: 56, heater: 30, agile: 66,
      abilities: ["Speed Demon"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Aaron", lastName: "Zavala", position: "DH", eligibility: "JR", homeState: "CA", hometown: "Clovis", jerseyNumber: 20,
      hitForAvg: 72, power: 68, speed: 44, arm: 54, fielding: 46, errorResistance: 44, velocity: 32, control: 28, stamina: 32, stuff: 26,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 16, running: 42, throwing: 56, recovery: 54, wRISP: 72, vsLefty: 66, poise: 70, heater: 28, agile: 46,
      abilities: ["Clutch Gene", "Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Gus", lastName: "Steiger", position: "OF", eligibility: "FR", homeState: "OR", hometown: "Beaverton", jerseyNumber: 26,
      hitForAvg: 40, power: 36, speed: 58, arm: 56, fielding: 46, errorResistance: 42, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 36, running: 56, throwing: 58, recovery: 36, wRISP: 36, vsLefty: 34, poise: 38, heater: 26, agile: 60,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Jake", lastName: "Pfennigs", position: "OF", eligibility: "FR", homeState: "WA", hometown: "Spokane", jerseyNumber: 30,
      hitForAvg: 42, power: 34, speed: 56, arm: 54, fielding: 44, errorResistance: 40, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 40, vsLHP: 36, grit: 42, stealing: 34, running: 54, throwing: 56, recovery: 38, wRISP: 38, vsLefty: 34, poise: 38, heater: 26, agile: 58,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Penn State": [
    // PITCHERS (9)
    { firstName: "Travis", lastName: "Eckert", position: "P", eligibility: "SR", homeState: "PA", hometown: "State College", jerseyNumber: 31,
      hitForAvg: 22, power: 18, speed: 40, arm: 82, fielding: 52, errorResistance: 54, velocity: 84, control: 78, stamina: 80, stuff: 82,
      clutch: 78, vsLHP: 74, grit: 80, stealing: 10, running: 36, throwing: 82, recovery: 74, wRISP: 76, vsLefty: 76, poise: 80, heater: 82, agile: 46,
      abilities: ["Ace", "Strong Starter", "Filthy Breaking Ball"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 7, 6, 5, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Partridge", position: "P", eligibility: "JR", homeState: "PA", hometown: "Allentown", jerseyNumber: 22,
      hitForAvg: 18, power: 14, speed: 40, arm: 76, fielding: 48, errorResistance: 50, velocity: 78, control: 72, stamina: 74, stuff: 76,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 12, running: 36, throwing: 74, recovery: 66, wRISP: 66, vsLefty: 68, poise: 70, heater: 76, agile: 44,
      abilities: ["Strong Starter"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 4, 0, 0, 0]) },
    { firstName: "Michael", lastName: "Morissette", position: "P", eligibility: "SO", homeState: "CT", hometown: "Hartford", jerseyNumber: 35,
      hitForAvg: 16, power: 12, speed: 42, arm: 72, fielding: 46, errorResistance: 48, velocity: 74, control: 66, stamina: 68, stuff: 72,
      clutch: 60, vsLHP: 58, grit: 62, stealing: 14, running: 38, throwing: 70, recovery: 60, wRISP: 58, vsLefty: 60, poise: 62, heater: 72, agile: 46,
      abilities: ["Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Mason", lastName: "Mellott", position: "P", eligibility: "SR", homeState: "PA", hometown: "Johnstown", jerseyNumber: 38,
      hitForAvg: 20, power: 16, speed: 38, arm: 74, fielding: 50, errorResistance: 52, velocity: 76, control: 74, stamina: 70, stuff: 74,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 10, running: 34, throwing: 72, recovery: 68, wRISP: 70, vsLefty: 70, poise: 74, heater: 74, agile: 44,
      abilities: ["Fireman", "Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 5, 4, 0, 0]) },
    { firstName: "Kyle", lastName: "Virbitsky", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Cherry Hill", jerseyNumber: 28,
      hitForAvg: 18, power: 14, speed: 38, arm: 72, fielding: 46, errorResistance: 48, velocity: 74, control: 70, stamina: 72, stuff: 72,
      clutch: 64, vsLHP: 62, grit: 66, stealing: 10, running: 34, throwing: 70, recovery: 64, wRISP: 62, vsLefty: 64, poise: 66, heater: 72, agile: 42,
      abilities: ["Workhorse"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 5, 0, 0, 0]) },
    { firstName: "Matt", lastName: "Svanson", position: "P", eligibility: "SO", homeState: "PA", hometown: "Lancaster", jerseyNumber: 42,
      hitForAvg: 16, power: 12, speed: 40, arm: 68, fielding: 44, errorResistance: 46, velocity: 70, control: 64, stamina: 64, stuff: 68,
      clutch: 56, vsLHP: 54, grit: 58, stealing: 12, running: 36, throwing: 66, recovery: 56, wRISP: 54, vsLefty: 56, poise: 58, heater: 68, agile: 44,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 5, 0, 0, 0]) },
    { firstName: "Jaden", lastName: "Henline", position: "P", eligibility: "JR", homeState: "PA", hometown: "York", jerseyNumber: 40,
      hitForAvg: 18, power: 14, speed: 40, arm: 70, fielding: 46, errorResistance: 48, velocity: 72, control: 68, stamina: 66, stuff: 70,
      clutch: 62, vsLHP: 60, grit: 64, stealing: 12, running: 36, throwing: 68, recovery: 62, wRISP: 60, vsLefty: 62, poise: 64, heater: 70, agile: 44,
      abilities: [], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 0, 3, 0, 0]) },
    { firstName: "Josh", lastName: "Shapiro", position: "P", eligibility: "SO", homeState: "PA", hometown: "Philadelphia", jerseyNumber: 46,
      hitForAvg: 16, power: 12, speed: 42, arm: 66, fielding: 42, errorResistance: 44, velocity: 68, control: 58, stamina: 56, stuff: 66,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 14, running: 40, throwing: 64, recovery: 50, wRISP: 48, vsLefty: 50, poise: 50, heater: 66, agile: 46,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 4, 0, 0, 0]) },
    { firstName: "Nolan", lastName: "Berger", position: "P", eligibility: "SO", homeState: "MD", hometown: "Bethesda", jerseyNumber: 48,
      hitForAvg: 14, power: 10, speed: 40, arm: 64, fielding: 40, errorResistance: 42, velocity: 66, control: 56, stamina: 54, stuff: 64,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 12, running: 38, throwing: 62, recovery: 48, wRISP: 46, vsLefty: 48, poise: 48, heater: 64, agile: 44,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    { firstName: "Cole", lastName: "Percival", position: "P", eligibility: "JR", homeState: "PA", hometown: "Doylestown", jerseyNumber: 50,
      hitForAvg: 18, power: 14, speed: 38, arm: 70, fielding: 46, errorResistance: 48, velocity: 72, control: 68, stamina: 68, stuff: 70,
      clutch: 62, vsLHP: 60, grit: 64, stealing: 10, running: 34, throwing: 68, recovery: 62, wRISP: 60, vsLefty: 62, poise: 64, heater: 70, agile: 42,
      abilities: [], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Grant", lastName: "Koch", position: "C", eligibility: "JR", homeState: "PA", hometown: "Harrisburg", jerseyNumber: 12,
      hitForAvg: 64, power: 58, speed: 40, arm: 74, fielding: 72, errorResistance: 70, velocity: 36, control: 32, stamina: 36, stuff: 30,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 18, running: 38, throwing: 76, recovery: 58, wRISP: 66, vsLefty: 62, poise: 68, heater: 32, agile: 44,
      abilities: ["Iron Glove", "Cannon Arm"], potential: "A-", catcherAbility: 74,
      ...noPitches },
    { firstName: "Derek", lastName: "Cabell", position: "C", eligibility: "SO", homeState: "PA", hometown: "Pittsburgh", jerseyNumber: 18,
      hitForAvg: 52, power: 44, speed: 38, arm: 64, fielding: 60, errorResistance: 56, velocity: 32, control: 28, stamina: 34, stuff: 26,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 14, running: 36, throwing: 66, recovery: 48, wRISP: 52, vsLefty: 48, poise: 52, heater: 28, agile: 40,
      abilities: [], potential: "B", catcherAbility: 60,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Tayven", lastName: "Kelley", position: "SS", eligibility: "SR", homeState: "PA", hometown: "Williamsport", jerseyNumber: 2,
      hitForAvg: 72, power: 58, speed: 66, arm: 74, fielding: 76, errorResistance: 74, velocity: 36, control: 32, stamina: 36, stuff: 30,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 48, running: 64, throwing: 76, recovery: 58, wRISP: 70, vsLefty: 66, poise: 72, heater: 32, agile: 68,
      abilities: ["Iron Glove", "Speed Demon"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Matt", lastName: "Wood", position: "1B", eligibility: "SR", homeState: "PA", hometown: "Scranton", jerseyNumber: 5,
      hitForAvg: 74, power: 76, speed: 42, arm: 62, fielding: 66, errorResistance: 64, velocity: 36, control: 32, stamina: 38, stuff: 30,
      clutch: 74, vsLHP: 70, grit: 76, stealing: 14, running: 40, throwing: 64, recovery: 58, wRISP: 74, vsLefty: 68, poise: 74, heater: 32, agile: 44,
      abilities: ["Power Hitter", "Clutch Gene"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Cole", lastName: "Bartels", position: "2B", eligibility: "SR", homeState: "PA", hometown: "Reading", jerseyNumber: 8,
      hitForAvg: 70, power: 56, speed: 58, arm: 64, fielding: 70, errorResistance: 68, velocity: 34, control: 30, stamina: 36, stuff: 28,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 38, running: 56, throwing: 66, recovery: 56, wRISP: 68, vsLefty: 64, poise: 70, heater: 30, agile: 60,
      abilities: ["Table Setter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Johnny", lastName: "Piacentino", position: "3B", eligibility: "JR", homeState: "NJ", hometown: "Toms River", jerseyNumber: 10,
      hitForAvg: 66, power: 62, speed: 50, arm: 68, fielding: 66, errorResistance: 64, velocity: 36, control: 32, stamina: 36, stuff: 30,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 24, running: 48, throwing: 70, recovery: 54, wRISP: 64, vsLefty: 60, poise: 66, heater: 32, agile: 52,
      abilities: ["Contact Machine"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Connor", lastName: "Cox", position: "SS", eligibility: "FR", homeState: "VA", hometown: "Richmond", jerseyNumber: 14,
      hitForAvg: 42, power: 34, speed: 56, arm: 56, fielding: 52, errorResistance: 48, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 34, running: 54, throwing: 58, recovery: 38, wRISP: 38, vsLefty: 36, poise: 40, heater: 26, agile: 58,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Sam", lastName: "Sternberg", position: "2B", eligibility: "FR", homeState: "NY", hometown: "White Plains", jerseyNumber: 16,
      hitForAvg: 38, power: 30, speed: 50, arm: 52, fielding: 48, errorResistance: 44, velocity: 28, control: 24, stamina: 28, stuff: 22,
      clutch: 36, vsLHP: 34, grit: 38, stealing: 28, running: 48, throwing: 54, recovery: 34, wRISP: 34, vsLefty: 32, poise: 36, heater: 24, agile: 52,
      abilities: [], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Matt", lastName: "Gorski", position: "1B", eligibility: "FR", homeState: "PA", hometown: "Erie", jerseyNumber: 34,
      hitForAvg: 44, power: 42, speed: 36, arm: 52, fielding: 46, errorResistance: 42, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 42, vsLHP: 38, grit: 44, stealing: 12, running: 34, throwing: 54, recovery: 38, wRISP: 40, vsLefty: 36, poise: 40, heater: 26, agile: 38,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS & DH (5)
    { firstName: "Jay", lastName: "Harry", position: "OF", eligibility: "JR", homeState: "PA", hometown: "Media", jerseyNumber: 7,
      hitForAvg: 68, power: 60, speed: 68, arm: 70, fielding: 66, errorResistance: 64, velocity: 36, control: 32, stamina: 36, stuff: 30,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 50, running: 66, throwing: 72, recovery: 54, wRISP: 64, vsLefty: 60, poise: 66, heater: 32, agile: 70,
      abilities: ["Speed Demon", "Cannon Arm"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Gavin", lastName: "Homer", position: "OF", eligibility: "JR", homeState: "PA", hometown: "Bethlehem", jerseyNumber: 9,
      hitForAvg: 64, power: 56, speed: 60, arm: 66, fielding: 62, errorResistance: 60, velocity: 34, control: 30, stamina: 34, stuff: 28,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 40, running: 58, throwing: 68, recovery: 52, wRISP: 60, vsLefty: 56, poise: 62, heater: 30, agile: 62,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Parker", lastName: "Harms", position: "OF", eligibility: "SO", homeState: "PA", hometown: "Easton", jerseyNumber: 11,
      hitForAvg: 56, power: 48, speed: 62, arm: 64, fielding: 58, errorResistance: 56, velocity: 34, control: 30, stamina: 34, stuff: 28,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 42, running: 60, throwing: 66, recovery: 48, wRISP: 52, vsLefty: 48, poise: 54, heater: 30, agile: 64,
      abilities: ["Speed Demon"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Danny", lastName: "Pyne", position: "DH", eligibility: "JR", homeState: "NJ", hometown: "Morristown", jerseyNumber: 20,
      hitForAvg: 66, power: 62, speed: 42, arm: 52, fielding: 44, errorResistance: 42, velocity: 32, control: 28, stamina: 32, stuff: 26,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 16, running: 40, throwing: 54, recovery: 52, wRISP: 64, vsLefty: 60, poise: 64, heater: 28, agile: 44,
      abilities: ["Clutch Gene"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Tyler", lastName: "Warren", position: "OF", eligibility: "FR", homeState: "PA", hometown: "Norristown", jerseyNumber: 26,
      hitForAvg: 40, power: 36, speed: 58, arm: 56, fielding: 46, errorResistance: 42, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 36, running: 56, throwing: 58, recovery: 36, wRISP: 36, vsLefty: 34, poise: 38, heater: 26, agile: 60,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Nick", lastName: "DeLeon", position: "OF", eligibility: "FR", homeState: "DE", hometown: "Wilmington", jerseyNumber: 30,
      hitForAvg: 42, power: 34, speed: 56, arm: 54, fielding: 44, errorResistance: 40, velocity: 30, control: 26, stamina: 30, stuff: 24,
      clutch: 40, vsLHP: 36, grit: 42, stealing: 34, running: 54, throwing: 56, recovery: 38, wRISP: 38, vsLefty: 34, poise: 38, heater: 26, agile: 58,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],
};
