import type { RealPlayer } from "./realRosters";

function pitchMix(primary: number, secondary: number[]): { pitchFB: number; pitch2S: number; pitchSL: number; pitchCB: number; pitchCH: number; pitchCT: number; pitchSNK: number; pitchSPL: number } {
  return {
    pitchFB: primary,
    pitch2S: secondary[0] || 0,
    pitchSL: secondary[1] || 0,
    pitchCB: secondary[2] || 0,
    pitchCH: secondary[3] || 0,
    pitchCT: secondary[4] || 0,
    pitchSNK: secondary[5] || 0,
    pitchSPL: secondary[6] || 0,
  };
}

const noPitches = { pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0 };

export const BIG_TEN_BATCH3_ROSTERS: Record<string, RealPlayer[]> = {
  "Purdue": [
    // PITCHERS (10)
    { firstName: "Cole", lastName: "Van Assen", position: "P", eligibility: "JR", homeState: "IN", hometown: "Crown Point", jerseyNumber: 19,
      hitForAvg: 20, power: 16, speed: 42, arm: 80, fielding: 50, errorResistance: 52, velocity: 82, control: 76, stamina: 80, stuff: 80,
      clutch: 74, vsLHP: 70, grit: 78, stealing: 10, running: 38, throwing: 78, recovery: 72, wRISP: 72, vsLefty: 74, poise: 76, heater: 82, agile: 46,
      abilities: ["Ace", "Strong Starter", "Workhorse"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 7, 6, 5, 0, 0, 0]) },
    { firstName: "Zach", lastName: "Erdman", position: "P", eligibility: "JR", homeState: "TX", hometown: "Lubbock", jerseyNumber: 34,
      hitForAvg: 15, power: 12, speed: 34, arm: 64, fielding: 40, errorResistance: 43, velocity: 68, control: 62, stamina: 64, stuff: 66,
      clutch: 59, vsLHP: 56, grit: 61, stealing: 9, running: 31, throwing: 62, recovery: 58, wRISP: 58, vsLefty: 59, poise: 61, heater: 68, agile: 37,
      abilities: ["Strong Starter", "Explosive Fastball"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 5, 0, 0, 0]) },
    { firstName: "Jarvis", lastName: "Evans", position: "P", eligibility: "JR", homeState: "SC", hometown: "Columbia", jerseyNumber: 27,
      hitForAvg: 15, power: 12, speed: 33, arm: 61, fielding: 40, errorResistance: 41, velocity: 64, control: 59, stamina: 61, stuff: 62,
      clutch: 56, vsLHP: 53, grit: 58, stealing: 8, running: 29, throwing: 59, recovery: 55, wRISP: 55, vsLefty: 56, poise: 58, heater: 64, agile: 36,
      abilities: ["Strong Starter", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 6, 5, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Kramer", position: "P", eligibility: "SR", homeState: "IN", hometown: "Fishers", jerseyNumber: 41,
      hitForAvg: 14, power: 11, speed: 29, arm: 60, fielding: 38, errorResistance: 42, velocity: 65, control: 60, stamina: 52, stuff: 63,
      clutch: 61, vsLHP: 55, grit: 61, stealing: 8, running: 26, throwing: 58, recovery: 57, wRISP: 60, vsLefty: 57, poise: 61, heater: 65, agile: 32,
      abilities: ["Fireman", "Explosive Fastball", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 7, 0, 5, 0, 0, 0]) },
    { firstName: "Barron", lastName: "Sawyer", position: "P", eligibility: "SR", homeState: "IN", hometown: "Westfield", jerseyNumber: 45,
      hitForAvg: 14, power: 13, speed: 32, arm: 66, fielding: 43, errorResistance: 45, velocity: 71, control: 62, stamina: 64, stuff: 68,
      clutch: 59, vsLHP: 55, grit: 61, stealing: 9, running: 29, throwing: 64, recovery: 58, wRISP: 58, vsLefty: 59, poise: 61, heater: 71, agile: 36,
      abilities: ["Explosive Fastball"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Westin", lastName: "Boyle", position: "P", eligibility: "JR", homeState: "IN", hometown: "Carmel", jerseyNumber: 38,
      hitForAvg: 9, power: 6, speed: 23, arm: 40, fielding: 27, errorResistance: 28, velocity: 44, control: 39, stamina: 40, stuff: 41,
      clutch: 36, vsLHP: 34, grit: 36, stealing: 6, running: 20, throwing: 39, recovery: 36, wRISP: 34, vsLefty: 36, poise: 36, heater: 44, agile: 25,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "O'Connell", position: "P", eligibility: "SO", homeState: "IL", hometown: "Naperville", jerseyNumber: 46,
      hitForAvg: 11, power: 8, speed: 28, arm: 48, fielding: 30, errorResistance: 32, velocity: 50, control: 45, stamina: 46, stuff: 49,
      clutch: 39, vsLHP: 38, grit: 41, stealing: 8, running: 25, throwing: 46, recovery: 38, wRISP: 38, vsLefty: 41, poise: 41, heater: 50, agile: 30,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Logan", lastName: "Beaman", position: "P", eligibility: "JR", homeState: "IN", hometown: "Lafayette", jerseyNumber: 32,
      hitForAvg: 11, power: 8, speed: 23, arm: 42, fielding: 27, errorResistance: 29, velocity: 44, control: 40, stamina: 40, stuff: 42,
      clutch: 37, vsLHP: 36, grit: 38, stealing: 6, running: 20, throwing: 40, recovery: 37, wRISP: 36, vsLefty: 38, poise: 38, heater: 44, agile: 25,
      abilities: [], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Josh", lastName: "Willman", position: "P", eligibility: "SO", homeState: "IN", hometown: "Brownsburg", jerseyNumber: 48,
      hitForAvg: 12, power: 9, speed: 32, arm: 52, fielding: 34, errorResistance: 35, velocity: 55, control: 48, stamina: 48, stuff: 52,
      clutch: 41, vsLHP: 40, grit: 43, stealing: 11, running: 29, throwing: 51, recovery: 40, wRISP: 40, vsLefty: 43, poise: 41, heater: 55, agile: 35,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 4, 0, 0, 0]) },
    { firstName: "Kade", lastName: "Hoover", position: "P", eligibility: "FR", homeState: "OH", hometown: "Columbus", jerseyNumber: 50,
      hitForAvg: 10, power: 9, speed: 30, arm: 50, fielding: 31, errorResistance: 33, velocity: 53, control: 47, stamina: 47, stuff: 50,
      clutch: 37, vsLHP: 36, grit: 39, stealing: 9, running: 27, throwing: 47, recovery: 37, wRISP: 36, vsLefty: 39, poise: 37, heater: 53, agile: 33,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Jackson", lastName: "Bessette", position: "C", eligibility: "JR", homeState: "IL", hometown: "Chicago", jerseyNumber: 12,
      hitForAvg: 53, power: 47, speed: 33, arm: 60, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 55, vsLHP: 51, grit: 56, stealing: 14, running: 30, throwing: 62, recovery: 47, wRISP: 53, vsLefty: 50, poise: 55, heater: 0, agile: 36,
      abilities: ["Iron Glove"], potential: "B+", catcherAbility: 56,
      ...noPitches },
    { firstName: "Nolan", lastName: "Wilkerson", position: "C", eligibility: "SO", homeState: "IN", hometown: "Muncie", jerseyNumber: 15,
      hitForAvg: 34, power: 30, speed: 24, arm: 42, fielding: 39, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 35, vsLHP: 33, grit: 37, stealing: 10, running: 23, throwing: 44, recovery: 31, wRISP: 34, vsLefty: 31, poise: 34, heater: 0, agile: 26,
      abilities: [], potential: "B", catcherAbility: 39,
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Dylan", lastName: "Drake", position: "SS", eligibility: "JR", homeState: "IN", hometown: "Indianapolis", jerseyNumber: 2,
      hitForAvg: 49, power: 39, speed: 48, arm: 53, fielding: 54, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 45, grit: 49, stealing: 35, running: 46, throwing: 54, recovery: 40, wRISP: 46, vsLefty: 43, poise: 48, heater: 0, agile: 52,
      abilities: ["Iron Glove", "Speed Demon"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Eli", lastName: "Anderson", position: "2B", eligibility: "JR", homeState: "IN", hometown: "Zionsville", jerseyNumber: 6,
      hitForAvg: 54, power: 42, speed: 52, arm: 57, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 49, grit: 54, stealing: 34, running: 49, throwing: 58, recovery: 47, wRISP: 52, vsLefty: 48, poise: 53, heater: 0, agile: 54,
      abilities: ["Table Setter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Sam", lastName: "Flores", position: "3B", eligibility: "SO", homeState: "CA", hometown: "San Diego", jerseyNumber: 8,
      hitForAvg: 51, power: 44, speed: 43, arm: 58, fielding: 55, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 47, grit: 51, stealing: 19, running: 41, throwing: 60, recovery: 43, wRISP: 48, vsLefty: 44, poise: 50, heater: 0, agile: 44,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Ross", lastName: "Highfill", position: "1B", eligibility: "JR", homeState: "IN", hometown: "Greenwood", jerseyNumber: 24,
      hitForAvg: 60, power: 59, speed: 38, arm: 56, fielding: 59, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 59, vsLHP: 54, grit: 60, stealing: 12, running: 36, throwing: 59, recovery: 47, wRISP: 56, vsLefty: 53, poise: 59, heater: 0, agile: 41,
      abilities: ["Contact Machine"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Tyler", lastName: "Reeves", position: "SS", eligibility: "FR", homeState: "IN", hometown: "Noblesville", jerseyNumber: 3,
      hitForAvg: 30, power: 24, speed: 41, arm: 39, fielding: 36, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 29, vsLHP: 27, grit: 30, stealing: 25, running: 39, throwing: 41, recovery: 27, wRISP: 28, vsLefty: 25, poise: 28, heater: 0, agile: 42,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Maddux", lastName: "Houghton", position: "1B", eligibility: "FR", homeState: "IN", hometown: "Avon", jerseyNumber: 28,
      hitForAvg: 33, power: 31, speed: 28, arm: 40, fielding: 37, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 31, vsLHP: 28, grit: 33, stealing: 11, running: 26, throwing: 41, recovery: 28, wRISP: 29, vsLefty: 26, poise: 29, heater: 0, agile: 29,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "Walstad", position: "2B", eligibility: "FR", homeState: "MN", hometown: "Edina", jerseyNumber: 14,
      hitForAvg: 27, power: 22, speed: 36, arm: 35, fielding: 33, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 25, vsLHP: 24, grit: 27, stealing: 22, running: 35, throwing: 36, recovery: 24, wRISP: 24, vsLefty: 22, poise: 25, heater: 0, agile: 37,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Aaron", lastName: "Manias", position: "OF", eligibility: "SR", homeState: "TX", hometown: "Big Spring", jerseyNumber: 7,
      hitForAvg: 61, power: 58, speed: 45, arm: 53, fielding: 50, errorResistance: 49, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 61, vsLHP: 58, grit: 62, stealing: 26, running: 43, throwing: 55, recovery: 47, wRISP: 61, vsLefty: 56, poise: 59, heater: 0, agile: 47,
      abilities: ["Power Surge", "Clutch Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "CJ", lastName: "Richmond", position: "OF", eligibility: "JR", homeState: "IN", hometown: "Terre Haute", jerseyNumber: 22,
      hitForAvg: 46, power: 40, speed: 48, arm: 49, fielding: 46, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 45, vsLHP: 42, grit: 46, stealing: 33, running: 46, throwing: 51, recovery: 37, wRISP: 43, vsLefty: 40, poise: 45, heater: 0, agile: 49,
      abilities: ["Speed Demon"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Camden", lastName: "Gasser", position: "OF", eligibility: "SO", homeState: "IN", hometown: "Brownsburg", jerseyNumber: 9,
      hitForAvg: 47, power: 40, speed: 50, arm: 52, fielding: 49, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 45, vsLHP: 42, grit: 47, stealing: 32, running: 49, throwing: 54, recovery: 39, wRISP: 44, vsLefty: 40, poise: 45, heater: 0, agile: 52,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jake", lastName: "Jarvis", position: "OF", eligibility: "JR", homeState: "IN", hometown: "Evansville", jerseyNumber: 20,
      hitForAvg: 48, power: 42, speed: 50, arm: 52, fielding: 48, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 44, grit: 48, stealing: 34, running: 48, throwing: 53, recovery: 39, wRISP: 45, vsLefty: 42, poise: 47, heater: 0, agile: 52,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Brennan", lastName: "Hein", position: "OF", eligibility: "FR", homeState: "IN", hometown: "Lafayette", jerseyNumber: 26,
      hitForAvg: 33, power: 29, speed: 44, arm: 43, fielding: 37, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 30, grit: 33, stealing: 26, running: 43, throwing: 44, recovery: 30, wRISP: 30, vsLefty: 29, poise: 30, heater: 0, agile: 46,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Brady", lastName: "Moore", position: "OF", eligibility: "SO", homeState: "IN", hometown: "Bloomington", jerseyNumber: 30,
      hitForAvg: 50, power: 42, speed: 53, arm: 55, fielding: 52, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 45, grit: 50, stealing: 34, running: 52, throwing: 57, recovery: 41, wRISP: 46, vsLefty: 42, poise: 48, heater: 0, agile: 55,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "Rutgers": [
    // PITCHERS (10)
    { firstName: "Joe", lastName: "Mazza", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Toms River", jerseyNumber: 17,
      hitForAvg: 21, power: 17, speed: 41, arm: 81, fielding: 52, errorResistance: 54, velocity: 82, control: 79, stamina: 81, stuff: 81,
      clutch: 75, vsLHP: 71, grit: 77, stealing: 11, running: 37, throwing: 79, recovery: 73, wRISP: 73, vsLefty: 75, poise: 77, heater: 82, agile: 45,
      abilities: ["Strong Starter", "Filthy Breaking Ball"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 6, 5, 0, 0, 0]) },
    { firstName: "Zack", lastName: "Konstantinovsky", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Marlboro", jerseyNumber: 22,
      hitForAvg: 15, power: 11, speed: 31, arm: 63, fielding: 39, errorResistance: 41, velocity: 65, control: 61, stamina: 63, stuff: 63,
      clutch: 58, vsLHP: 55, grit: 60, stealing: 8, running: 28, throwing: 61, recovery: 56, wRISP: 56, vsLefty: 58, poise: 60, heater: 65, agile: 34,
      abilities: ["Strong Starter", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 5, 0, 0, 0]) },
    { firstName: "Dallin", lastName: "Harrison", position: "P", eligibility: "JR", homeState: "CA", hometown: "San Diego", jerseyNumber: 35,
      hitForAvg: 16, power: 13, speed: 36, arm: 66, fielding: 43, errorResistance: 44, velocity: 69, control: 64, stamina: 66, stuff: 67,
      clutch: 60, vsLHP: 57, grit: 61, stealing: 9, running: 32, throwing: 64, recovery: 58, wRISP: 58, vsLefty: 60, poise: 61, heater: 69, agile: 39,
      abilities: ["Workhorse"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 5, 0, 0, 0]) },
    { firstName: "Vincent", lastName: "Borghese", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Cherry Hill", jerseyNumber: 40,
      hitForAvg: 14, power: 10, speed: 29, arm: 58, fielding: 36, errorResistance: 40, velocity: 61, control: 57, stamina: 57, stuff: 59,
      clutch: 55, vsLHP: 52, grit: 57, stealing: 7, running: 26, throwing: 57, recovery: 52, wRISP: 53, vsLefty: 53, poise: 55, heater: 61, agile: 32,
      abilities: ["Explosive Fastball", "Workhorse"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 4, 0, 0, 0]) },
    { firstName: "Jordan", lastName: "Savinon", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Newark", jerseyNumber: 29,
      hitForAvg: 12, power: 10, speed: 32, arm: 58, fielding: 37, errorResistance: 38, velocity: 61, control: 56, stamina: 58, stuff: 59,
      clutch: 51, vsLHP: 50, grit: 53, stealing: 8, running: 29, throwing: 56, recovery: 51, wRISP: 50, vsLefty: 53, poise: 53, heater: 61, agile: 35,
      abilities: ["Fireman"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Marcus", lastName: "Holden", position: "P", eligibility: "SO", homeState: "NJ", hometown: "Woodbridge", jerseyNumber: 46,
      hitForAvg: 12, power: 8, speed: 29, arm: 49, fielding: 31, errorResistance: 34, velocity: 52, control: 46, stamina: 48, stuff: 50,
      clutch: 41, vsLHP: 39, grit: 42, stealing: 8, running: 26, throwing: 48, recovery: 39, wRISP: 39, vsLefty: 42, poise: 42, heater: 52, agile: 31,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Jake", lastName: "DeLeo", position: "P", eligibility: "SO", homeState: "NJ", hometown: "Princeton", jerseyNumber: 48,
      hitForAvg: 9, power: 8, speed: 27, arm: 42, fielding: 28, errorResistance: 29, velocity: 44, control: 41, stamina: 41, stuff: 43,
      clutch: 35, vsLHP: 33, grit: 35, stealing: 9, running: 24, throwing: 42, recovery: 33, wRISP: 33, vsLefty: 35, poise: 35, heater: 44, agile: 29,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 4, 0, 0, 0]) },
    { firstName: "Cole", lastName: "Stetzar", position: "P", eligibility: "SO", homeState: "NJ", hometown: "Haddonfield", jerseyNumber: 33,
      hitForAvg: 10, power: 8, speed: 25, arm: 44, fielding: 29, errorResistance: 30, velocity: 47, control: 43, stamina: 43, stuff: 44,
      clutch: 37, vsLHP: 35, grit: 38, stealing: 6, running: 23, throwing: 43, recovery: 35, wRISP: 35, vsLefty: 38, poise: 37, heater: 47, agile: 28,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 4, 0, 0, 0]) },
    { firstName: "Matt", lastName: "Reardon", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Edison", jerseyNumber: 36,
      hitForAvg: 13, power: 9, speed: 26, arm: 48, fielding: 31, errorResistance: 33, velocity: 50, control: 46, stamina: 46, stuff: 48,
      clutch: 43, vsLHP: 41, grit: 44, stealing: 7, running: 23, throwing: 46, recovery: 43, wRISP: 41, vsLefty: 44, poise: 44, heater: 50, agile: 28,
      abilities: [], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Hogan", position: "P", eligibility: "FR", homeState: "PA", hometown: "Allentown", jerseyNumber: 50,
      hitForAvg: 10, power: 9, speed: 29, arm: 48, fielding: 30, errorResistance: 32, velocity: 50, control: 46, stamina: 46, stuff: 48,
      clutch: 36, vsLHP: 35, grit: 37, stealing: 9, running: 26, throwing: 46, recovery: 36, wRISP: 35, vsLefty: 37, poise: 36, heater: 50, agile: 32,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Matt", lastName: "Chatelle", position: "C", eligibility: "SR", homeState: "NJ", hometown: "Bridgewater", jerseyNumber: 12,
      hitForAvg: 51, power: 44, speed: 29, arm: 55, fielding: 55, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 55, stealing: 12, running: 27, throwing: 56, recovery: 44, wRISP: 51, vsLefty: 47, poise: 53, heater: 0, agile: 32,
      abilities: ["Iron Glove", "Guts"], potential: "B+", catcherAbility: 52,
      ...noPitches },
    { firstName: "Trey", lastName: "Wells", position: "C", eligibility: "SR", homeState: "NJ", hometown: "Middletown", jerseyNumber: 18,
      hitForAvg: 39, power: 35, speed: 25, arm: 45, fielding: 43, errorResistance: 41, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 39, vsLHP: 37, grit: 41, stealing: 10, running: 24, throwing: 46, recovery: 35, wRISP: 38, vsLefty: 36, poise: 39, heater: 0, agile: 26,
      abilities: [], potential: "B", catcherAbility: 42,
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Yomar", lastName: "Carreras", position: "SS", eligibility: "SO", homeState: "FL", hometown: "Miami", jerseyNumber: 2,
      hitForAvg: 55, power: 43, speed: 55, arm: 58, fielding: 58, errorResistance: 57, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 51, grit: 55, stealing: 41, running: 54, throwing: 60, recovery: 44, wRISP: 52, vsLefty: 50, poise: 54, heater: 0, agile: 57,
      abilities: ["Iron Glove", "Speed Demon"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Charlie", lastName: "Meglio", position: "3B", eligibility: "JR", homeState: "NC", hometown: "Buies Creek", jerseyNumber: 8,
      hitForAvg: 57, power: 60, speed: 37, arm: 55, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 55, grit: 60, stealing: 14, running: 36, throwing: 57, recovery: 46, wRISP: 58, vsLefty: 54, poise: 57, heater: 0, agile: 39,
      abilities: ["Power Surge", "Clutch Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "Jaros", position: "1B", eligibility: "JR", homeState: "NJ", hometown: "Westfield", jerseyNumber: 24,
      hitForAvg: 52, power: 50, speed: 34, arm: 50, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 13, running: 32, throwing: 52, recovery: 42, wRISP: 49, vsLefty: 45, poise: 50, heater: 0, agile: 36,
      abilities: ["Contact Machine"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Quinten", lastName: "Perilli", position: "2B", eligibility: "JR", homeState: "NJ", hometown: "Summit", jerseyNumber: 6,
      hitForAvg: 47, power: 35, speed: 43, arm: 48, fielding: 51, errorResistance: 49, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 42, grit: 47, stealing: 28, running: 42, throwing: 49, recovery: 39, wRISP: 43, vsLefty: 40, poise: 44, heater: 0, agile: 47,
      abilities: ["Table Setter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Tristan", lastName: "Salinas", position: "SS", eligibility: "JR", homeState: "CA", hometown: "Anaheim", jerseyNumber: 5,
      hitForAvg: 44, power: 34, speed: 46, arm: 51, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 43, vsLHP: 40, grit: 44, stealing: 31, running: 44, throwing: 53, recovery: 37, wRISP: 42, vsLefty: 39, poise: 43, heater: 0, agile: 50,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Anthony", lastName: "Stephan", position: "3B", eligibility: "FR", homeState: "NJ", hometown: "Morristown", jerseyNumber: 3,
      hitForAvg: 28, power: 23, speed: 36, arm: 36, fielding: 33, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 26, vsLHP: 25, grit: 28, stealing: 22, running: 34, throwing: 37, recovery: 25, wRISP: 26, vsLefty: 23, poise: 26, heater: 0, agile: 37,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Max", lastName: "Brown", position: "1B", eligibility: "FR", homeState: "PA", hometown: "Doylestown", jerseyNumber: 28,
      hitForAvg: 34, power: 32, speed: 29, arm: 42, fielding: 39, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 29, grit: 34, stealing: 11, running: 28, throwing: 43, recovery: 29, wRISP: 31, vsLefty: 28, poise: 31, heater: 0, agile: 31,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Peyton", lastName: "Bonds", position: "OF", eligibility: "JR", homeState: "NJ", hometown: "Piscataway", jerseyNumber: 7,
      hitForAvg: 49, power: 44, speed: 49, arm: 47, fielding: 48, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 47, grit: 50, stealing: 40, running: 48, throwing: 48, recovery: 40, wRISP: 48, vsLefty: 45, poise: 49, heater: 0, agile: 50,
      abilities: ["Speed Demon", "Power Surge", "Cannon Arm"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Chase", lastName: "Krewson", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Orlando", jerseyNumber: 10,
      hitForAvg: 54, power: 46, speed: 49, arm: 53, fielding: 51, errorResistance: 49, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 49, grit: 54, stealing: 34, running: 48, throwing: 54, recovery: 43, wRISP: 51, vsLefty: 48, poise: 53, heater: 0, agile: 51,
      abilities: ["Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Nick", lastName: "Cimillo", position: "OF", eligibility: "JR", homeState: "NJ", hometown: "Cranford", jerseyNumber: 9,
      hitForAvg: 49, power: 43, speed: 48, arm: 52, fielding: 49, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 44, grit: 49, stealing: 31, running: 45, throwing: 53, recovery: 39, wRISP: 45, vsLefty: 43, poise: 48, heater: 0, agile: 49,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Evan", lastName: "Sleight", position: "OF", eligibility: "SO", homeState: "NY", hometown: "Poughkeepsie", jerseyNumber: 20,
      hitForAvg: 56, power: 47, speed: 60, arm: 62, fielding: 57, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 50, grit: 56, stealing: 37, running: 57, throwing: 63, recovery: 46, wRISP: 52, vsLefty: 47, poise: 53, heater: 0, agile: 62,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "Gale", position: "OF", eligibility: "FR", homeState: "NJ", hometown: "Hoboken", jerseyNumber: 26,
      hitForAvg: 31, power: 25, speed: 41, arm: 40, fielding: 35, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 29, vsLHP: 28, grit: 31, stealing: 25, running: 40, throwing: 41, recovery: 28, wRISP: 28, vsLefty: 26, poise: 28, heater: 0, agile: 43,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Liam", lastName: "Bendo", position: "OF", eligibility: "FR", homeState: "CT", hometown: "Greenwich", jerseyNumber: 30,
      hitForAvg: 30, power: 23, speed: 42, arm: 41, fielding: 36, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 29, vsLHP: 26, grit: 30, stealing: 25, running: 41, throwing: 42, recovery: 26, wRISP: 26, vsLefty: 25, poise: 29, heater: 0, agile: 44,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "USC": [
    // PITCHERS (10)
    { firstName: "Mason", lastName: "Edwards", position: "P", eligibility: "JR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 31,
      hitForAvg: 20, power: 16, speed: 42, arm: 84, fielding: 52, errorResistance: 54, velocity: 86, control: 80, stamina: 82, stuff: 84,
      clutch: 78, vsLHP: 74, grit: 80, stealing: 10, running: 39, throwing: 82, recovery: 76, wRISP: 76, vsLefty: 78, poise: 80, heater: 86, agile: 46,
      abilities: ["Ace", "Strong Starter", "Filthy Breaking Ball"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 7, 6, 6, 0, 0, 0]) },
    { firstName: "Grant", lastName: "Govel", position: "P", eligibility: "SO", homeState: "CA", hometown: "San Diego", jerseyNumber: 27,
      hitForAvg: 14, power: 11, speed: 31, arm: 59, fielding: 37, errorResistance: 39, velocity: 61, control: 55, stamina: 57, stuff: 61,
      clutch: 52, vsLHP: 50, grit: 54, stealing: 8, running: 28, throwing: 57, recovery: 51, wRISP: 51, vsLefty: 52, poise: 54, heater: 61, agile: 34,
      abilities: ["Strong Starter", "Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 5, 0, 0, 0]) },
    { firstName: "Andrew", lastName: "Johnson", position: "P", eligibility: "SO", homeState: "CA", hometown: "Thousand Oaks", jerseyNumber: 35,
      hitForAvg: 12, power: 9, speed: 34, arm: 58, fielding: 37, errorResistance: 38, velocity: 62, control: 55, stamina: 57, stuff: 58,
      clutch: 51, vsLHP: 48, grit: 52, stealing: 9, running: 30, throwing: 57, recovery: 48, wRISP: 49, vsLefty: 51, poise: 52, heater: 62, agile: 37,
      abilities: ["Guts"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 5, 0, 0, 0]) },
    { firstName: "Henry", lastName: "Chabot", position: "P", eligibility: "SR", homeState: "CA", hometown: "Orange", jerseyNumber: 41,
      hitForAvg: 15, power: 12, speed: 32, arm: 65, fielding: 44, errorResistance: 45, velocity: 68, control: 65, stamina: 62, stuff: 66,
      clutch: 61, vsLHP: 57, grit: 62, stealing: 9, running: 27, throwing: 62, recovery: 59, wRISP: 59, vsLefty: 61, poise: 62, heater: 68, agile: 35,
      abilities: ["Workhorse", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 4, 0, 0, 0]) },
    { firstName: "Gavin", lastName: "Lauridsen", position: "P", eligibility: "FR", homeState: "CA", hometown: "Riverside", jerseyNumber: 36,
      hitForAvg: 10, power: 7, speed: 25, arm: 44, fielding: 28, errorResistance: 29, velocity: 48, control: 41, stamina: 41, stuff: 45,
      clutch: 35, vsLHP: 34, grit: 37, stealing: 7, running: 23, throwing: 42, recovery: 34, wRISP: 34, vsLefty: 37, poise: 37, heater: 48, agile: 28,
      abilities: ["Explosive Fastball"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Landon", lastName: "Sims", position: "P", eligibility: "JR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 38,
      hitForAvg: 15, power: 12, speed: 34, arm: 62, fielding: 40, errorResistance: 42, velocity: 67, control: 60, stamina: 57, stuff: 64,
      clutch: 55, vsLHP: 52, grit: 57, stealing: 8, running: 30, throwing: 60, recovery: 54, wRISP: 54, vsLefty: 55, poise: 57, heater: 67, agile: 37,
      abilities: ["Fireman", "Filthy Breaking Ball"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 8, 0, 4, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Snider", position: "P", eligibility: "SO", homeState: "CA", hometown: "Irvine", jerseyNumber: 48,
      hitForAvg: 10, power: 8, speed: 28, arm: 45, fielding: 29, errorResistance: 31, velocity: 48, control: 45, stamina: 43, stuff: 46,
      clutch: 38, vsLHP: 36, grit: 39, stealing: 9, running: 26, throwing: 45, recovery: 36, wRISP: 36, vsLefty: 39, poise: 38, heater: 48, agile: 31,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 4, 0, 0, 0]) },
    { firstName: "Alex", lastName: "Williams", position: "P", eligibility: "SO", homeState: "CA", hometown: "Fresno", jerseyNumber: 50,
      hitForAvg: 11, power: 9, speed: 31, arm: 51, fielding: 33, errorResistance: 34, velocity: 54, control: 49, stamina: 49, stuff: 51,
      clutch: 40, vsLHP: 39, grit: 41, stealing: 9, running: 28, throwing: 49, recovery: 39, wRISP: 39, vsLefty: 41, poise: 40, heater: 54, agile: 34,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    { firstName: "Derek", lastName: "Campos", position: "P", eligibility: "JR", homeState: "CA", hometown: "Ventura", jerseyNumber: 33,
      hitForAvg: 13, power: 10, speed: 27, arm: 50, fielding: 33, errorResistance: 34, velocity: 52, control: 48, stamina: 48, stuff: 50,
      clutch: 44, vsLHP: 43, grit: 46, stealing: 7, running: 24, throwing: 48, recovery: 44, wRISP: 43, vsLefty: 46, poise: 46, heater: 52, agile: 30,
      abilities: [], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Chandler", lastName: "Murphy", position: "P", eligibility: "SO", homeState: "CA", hometown: "Pasadena", jerseyNumber: 45,
      hitForAvg: 11, power: 8, speed: 26, arm: 44, fielding: 28, errorResistance: 29, velocity: 46, control: 43, stamina: 43, stuff: 44,
      clutch: 36, vsLHP: 35, grit: 37, stealing: 8, running: 23, throwing: 43, recovery: 35, wRISP: 35, vsLefty: 37, poise: 37, heater: 46, agile: 28,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Blake", lastName: "Sabol", position: "C", eligibility: "SR", homeState: "CA", hometown: "Irvine", jerseyNumber: 12,
      hitForAvg: 56, power: 50, speed: 33, arm: 60, fielding: 59, errorResistance: 57, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 57, vsLHP: 54, grit: 59, stealing: 15, running: 31, throwing: 62, recovery: 47, wRISP: 56, vsLefty: 52, poise: 57, heater: 0, agile: 36,
      abilities: ["Iron Glove", "Clutch Hitter"], potential: "B+", catcherAbility: 57,
      ...noPitches },
    { firstName: "Xavier", lastName: "Casserilla", position: "C", eligibility: "SO", homeState: "CA", hometown: "Riverside", jerseyNumber: 15,
      hitForAvg: 38, power: 34, speed: 27, arm: 46, fielding: 43, errorResistance: 41, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 39, vsLHP: 36, grit: 41, stealing: 11, running: 25, throwing: 48, recovery: 34, wRISP: 38, vsLefty: 35, poise: 38, heater: 0, agile: 28,
      abilities: [], potential: "B", catcherAbility: 42,
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Abbrie", lastName: "Covarrubias", position: "SS", eligibility: "JR", homeState: "CA", hometown: "Whittier", jerseyNumber: 2,
      hitForAvg: 55, power: 43, speed: 53, arm: 57, fielding: 58, errorResistance: 57, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 50, grit: 55, stealing: 41, running: 52, throwing: 58, recovery: 45, wRISP: 52, vsLefty: 49, poise: 53, heater: 0, agile: 57,
      abilities: ["Iron Glove", "Speed Demon"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Adrian", lastName: "Lopez", position: "3B", eligibility: "JR", homeState: "CA", hometown: "La Puente", jerseyNumber: 8,
      hitForAvg: 54, power: 50, speed: 37, arm: 51, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 50, grit: 54, stealing: 17, running: 37, throwing: 53, recovery: 42, wRISP: 53, vsLefty: 48, poise: 53, heater: 0, agile: 39,
      abilities: ["Contact Machine", "Clutch Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Dean", lastName: "Carpentier", position: "1B", eligibility: "JR", homeState: "CA", hometown: "Santa Monica", jerseyNumber: 24,
      hitForAvg: 54, power: 58, speed: 35, arm: 50, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 55, vsLHP: 52, grit: 57, stealing: 12, running: 33, throwing: 52, recovery: 44, wRISP: 55, vsLefty: 50, poise: 55, heater: 0, agile: 37,
      abilities: ["Power Surge"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Caden", lastName: "Dana", position: "2B", eligibility: "JR", homeState: "CA", hometown: "Mission Viejo", jerseyNumber: 6,
      hitForAvg: 58, power: 45, speed: 54, arm: 59, fielding: 63, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 55, vsLHP: 51, grit: 58, stealing: 35, running: 51, throwing: 62, recovery: 48, wRISP: 54, vsLefty: 50, poise: 55, heater: 0, agile: 58,
      abilities: ["Table Setter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Diego", lastName: "Velazquez", position: "SS", eligibility: "FR", homeState: "CA", hometown: "Anaheim", jerseyNumber: 3,
      hitForAvg: 47, power: 37, speed: 54, arm: 53, fielding: 51, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 40, grit: 46, stealing: 36, running: 53, throwing: 54, recovery: 39, wRISP: 43, vsLefty: 39, poise: 43, heater: 0, agile: 57,
      abilities: ["Speed Demon"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Cole", lastName: "Carrigg", position: "1B", eligibility: "FR", homeState: "CA", hometown: "Newport Beach", jerseyNumber: 28,
      hitForAvg: 31, power: 30, speed: 26, arm: 38, fielding: 34, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 30, vsLHP: 26, grit: 31, stealing: 9, running: 25, throwing: 39, recovery: 26, wRISP: 27, vsLefty: 25, poise: 27, heater: 0, agile: 27,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Marcus", lastName: "Smith", position: "2B", eligibility: "FR", homeState: "CA", hometown: "Sacramento", jerseyNumber: 14,
      hitForAvg: 29, power: 24, speed: 40, arm: 39, fielding: 37, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 28, vsLHP: 27, grit: 29, stealing: 24, running: 39, throwing: 40, recovery: 27, wRISP: 27, vsLefty: 26, poise: 28, heater: 0, agile: 42,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Brock", lastName: "Slaton", position: "OF", eligibility: "SR", homeState: "LA", hometown: "New Orleans", jerseyNumber: 7,
      hitForAvg: 55, power: 51, speed: 49, arm: 54, fielding: 51, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 55, vsLHP: 51, grit: 56, stealing: 34, running: 48, throwing: 55, recovery: 44, wRISP: 55, vsLefty: 50, poise: 55, heater: 0, agile: 50,
      abilities: ["Power Surge", "Cannon Arm"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Rhylan", lastName: "Thomas", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Long Beach", jerseyNumber: 9,
      hitForAvg: 51, power: 46, speed: 51, arm: 51, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 51, stealing: 36, running: 50, throwing: 52, recovery: 40, wRISP: 48, vsLefty: 45, poise: 50, heater: 0, agile: 52,
      abilities: ["Speed Demon", "Contact Machine"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Dominic", lastName: "Hellman", position: "OF", eligibility: "SO", homeState: "CA", hometown: "Torrance", jerseyNumber: 11,
      hitForAvg: 55, power: 49, speed: 59, arm: 62, fielding: 58, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 55, stealing: 38, running: 58, throwing: 63, recovery: 46, wRISP: 51, vsLefty: 49, poise: 54, heater: 0, agile: 62,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Theo", lastName: "Denlinger", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Santa Monica", jerseyNumber: 20,
      hitForAvg: 45, power: 44, speed: 27, arm: 35, fielding: 34, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 45, vsLHP: 41, grit: 46, stealing: 9, running: 26, throwing: 37, recovery: 34, wRISP: 45, vsLefty: 40, poise: 44, heater: 0, agile: 28,
      abilities: ["Clutch Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Braden", lastName: "Davis", position: "OF", eligibility: "SO", homeState: "TX", hometown: "Austin", jerseyNumber: 26,
      hitForAvg: 46, power: 40, speed: 47, arm: 48, fielding: 46, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 41, grit: 46, stealing: 30, running: 46, throwing: 50, recovery: 38, wRISP: 43, vsLefty: 40, poise: 44, heater: 0, agile: 48,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jake", lastName: "Reeves", position: "OF", eligibility: "FR", homeState: "CA", hometown: "Bakersfield", jerseyNumber: 30,
      hitForAvg: 30, power: 25, speed: 45, arm: 44, fielding: 38, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 29, vsLHP: 28, grit: 30, stealing: 28, running: 44, throwing: 45, recovery: 28, wRISP: 28, vsLefty: 25, poise: 29, heater: 0, agile: 46,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  // UCLA — 45-4 overall, 25-0 Big Ten, D1Baseball #1 (May 3, 2026)
  // Real 2026 mid-season stats from uclabruins.com PDF + Daily Bruin/Baseball America rotation pieces
  "UCLA": [
    // PITCHERS (10) — staff-leading 3.07 ERA, deepest rotation in country
    // Logan Reddemann — Friday SP, JR transfer from USD, projected first-rd, 8 quality starts, elite FB + tantalizing CH
    { firstName: "Logan", lastName: "Reddemann", position: "P", eligibility: "JR", homeState: "CA", hometown: "San Diego", jerseyNumber: 21,
      hitForAvg: 18, power: 14, speed: 38, arm: 86, fielding: 52, errorResistance: 56, velocity: 88, control: 86, stamina: 80, stuff: 90,
      clutch: 78, vsLHP: 75, grit: 80, stealing: 8, running: 33, throwing: 80, recovery: 75, wRISP: 78, vsLefty: 76, poise: 82, heater: 80, agile: 48,
      abilities: ["Ace", "Pinpoint", "Doctor K"], potential: "A", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(6, [0, 4, 3, 7, 0, 0, 0]) },
    // Wylan Moss — Saturday bulk reliever / piggyback, SO, team-best 0.89 ERA, 93-95 + elite CH (20" horizontal break), top-15 2027 prospect
    { firstName: "Wylan", lastName: "Moss", position: "P", eligibility: "SO", homeState: "CA", hometown: "Calabasas", jerseyNumber: 40,
      hitForAvg: 12, power: 10, speed: 35, arm: 80, fielding: 48, errorResistance: 52, velocity: 80, control: 80, stamina: 65, stuff: 86,
      clutch: 76, vsLHP: 72, grit: 76, stealing: 7, running: 30, throwing: 75, recovery: 65, wRISP: 78, vsLefty: 74, poise: 78, heater: 70, agile: 50,
      abilities: ["Strong Starter", "Pinpoint", "Filthy Breaking Ball"], potential: "A", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "medium",
      ...pitchMix(5, [0, 4, 0, 7, 0, 0, 0]) },
    // Michael Barnett — Saturday opener, SR, 3.74 ERA, 244 career IP, four-pitch mix (sinker/CH/SL/CB)
    { firstName: "Michael", lastName: "Barnett", position: "P", eligibility: "SR", homeState: "CA", hometown: "Manhattan Beach", jerseyNumber: 34,
      hitForAvg: 16, power: 12, speed: 30, arm: 70, fielding: 50, errorResistance: 56, velocity: 65, control: 76, stamina: 70, stuff: 68,
      clutch: 70, vsLHP: 68, grit: 74, stealing: 6, running: 26, throwing: 65, recovery: 66, wRISP: 68, vsLefty: 70, poise: 74, heater: 60, agile: 38,
      abilities: ["Strong Starter", "Workhorse", "Pinpoint"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(4, [0, 4, 4, 5, 0, 5, 0]) },
    // Landon Stump — Sunday SP, JR, 4.33 ERA, ~3 IP/start, surviving Sundays
    { firstName: "Landon", lastName: "Stump", position: "P", eligibility: "JR", homeState: "CA", hometown: "Huntington Beach", jerseyNumber: 14,
      hitForAvg: 14, power: 11, speed: 32, arm: 64, fielding: 44, errorResistance: 48, velocity: 68, control: 60, stamina: 55, stuff: 64,
      clutch: 56, vsLHP: 54, grit: 58, stealing: 6, running: 28, throwing: 60, recovery: 55, wRISP: 55, vsLefty: 56, poise: 58, heater: 64, agile: 42,
      abilities: ["Guts"], potential: "B", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(4, [0, 4, 4, 4, 0, 0, 0]) },
    // Easton Hawk — closer, SO, mid-90s + tight horizontal SL, 16 scoreless app, Big Ten Co-Pitcher of Week, Woodland Hills CA
    { firstName: "Easton", lastName: "Hawk", position: "P", eligibility: "SO", homeState: "CA", hometown: "Woodland Hills", jerseyNumber: 27,
      hitForAvg: 11, power: 8, speed: 35, arm: 80, fielding: 44, errorResistance: 48, velocity: 78, control: 72, stamina: 38, stuff: 80,
      clutch: 80, vsLHP: 72, grit: 76, stealing: 7, running: 30, throwing: 75, recovery: 60, wRISP: 78, vsLefty: 72, poise: 80, heater: 68, agile: 48,
      abilities: ["Fireman", "Doctor K"], potential: "A-", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(6, [0, 6, 0, 2, 0, 0, 0]) },
    // Cal Randall — JR setup, 98mph FB touching 100, 21K/11IP (42% K rate, 8th P4), walks 1 of 5
    { firstName: "Cal", lastName: "Randall", position: "P", eligibility: "JR", homeState: "CA", hometown: "Temecula", jerseyNumber: 33,
      hitForAvg: 10, power: 8, speed: 32, arm: 86, fielding: 42, errorResistance: 44, velocity: 90, control: 48, stamina: 30, stuff: 84,
      clutch: 64, vsLHP: 60, grit: 60, stealing: 6, running: 28, throwing: 78, recovery: 50, wRISP: 60, vsLefty: 60, poise: 62, heater: 78, agile: 50,
      abilities: ["Fireman", "Explosive Fastball", "Wild"], potential: "A-", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(7, [0, 4, 0, 2, 0, 0, 0]) },
    // Angel Cervantes — FR, RHP, 2nd-round talent who chose college, top young prospect
    { firstName: "Angel", lastName: "Cervantes", position: "P", eligibility: "FR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 29,
      hitForAvg: 11, power: 8, speed: 30, arm: 72, fielding: 38, errorResistance: 40, velocity: 75, control: 60, stamina: 56, stuff: 76,
      clutch: 50, vsLHP: 48, grit: 50, stealing: 7, running: 27, throwing: 68, recovery: 48, wRISP: 48, vsLefty: 50, poise: 50, heater: 70, agile: 42,
      abilities: ["Strong Starter", "Filthy Breaking Ball"], potential: "A", catcherAbility: null,
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...pitchMix(5, [0, 5, 4, 5, 0, 0, 0]) },
    // Zach Strickland — FR RHP, weekend bullpen, elite K/BB
    { firstName: "Zach", lastName: "Strickland", position: "P", eligibility: "FR", homeState: "CA", hometown: "Redondo Beach", jerseyNumber: 45,
      hitForAvg: 10, power: 7, speed: 28, arm: 56, fielding: 32, errorResistance: 36, velocity: 60, control: 70, stamina: 38, stuff: 58,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 6, running: 25, throwing: 56, recovery: 44, wRISP: 50, vsLefty: 50, poise: 52, heater: 56, agile: 36,
      abilities: ["Pinpoint"], potential: "A-", catcherAbility: null,
      skinTone: "light", hairColor: "blonde", hairStyle: "short",
      ...pitchMix(4, [0, 4, 3, 4, 0, 0, 0]) },
    // Ian May — RS-Sr LHP, multi-inning long man
    { firstName: "Ian", lastName: "May", position: "P", eligibility: "SR", homeState: "CA", hometown: "Rancho Cucamonga", jerseyNumber: 38,
      hitForAvg: 12, power: 9, speed: 26, arm: 60, fielding: 40, errorResistance: 46, velocity: 56, control: 64, stamina: 56, stuff: 56,
      clutch: 54, vsLHP: 70, grit: 56, stealing: 5, running: 22, throwing: 56, recovery: 52, wRISP: 52, vsLefty: 70, poise: 56, heater: 50, agile: 32,
      abilities: ["LOOGY", "Workhorse"], potential: "B", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(4, [0, 4, 4, 4, 0, 0, 0]) },
    // Jake Swenson — JR depth pitcher
    { firstName: "Jake", lastName: "Swenson", position: "P", eligibility: "JR", homeState: "WA", hometown: "Seattle", jerseyNumber: 48,
      hitForAvg: 11, power: 9, speed: 28, arm: 52, fielding: 36, errorResistance: 38, velocity: 56, control: 52, stamina: 48, stuff: 54,
      clutch: 46, vsLHP: 44, grit: 46, stealing: 7, running: 24, throwing: 52, recovery: 44, wRISP: 44, vsLefty: 46, poise: 46, heater: 54, agile: 32,
      abilities: [], potential: "B", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(3, [0, 3, 3, 3, 0, 0, 0]) },
    // CATCHERS (2)
    // Cashel Dugger — JR C, Buster Posey Award watch list, primary backstop
    { firstName: "Cashel", lastName: "Dugger", position: "C", eligibility: "JR", homeState: "CA", hometown: "Torrance", jerseyNumber: 16,
      hitForAvg: 60, power: 56, speed: 28, arm: 76, fielding: 70, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 65, vsLHP: 62, grit: 70, stealing: 12, running: 28, throwing: 76, recovery: 56, wRISP: 64, vsLefty: 60, poise: 68, heater: 0, agile: 38,
      abilities: ["Iron Glove", "Cannon Arm", "Clutch Hitter"], potential: "A-", catcherAbility: 70,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Khansarinia — backup C, allowed 10 SB on 12 attempts (mentioned in PDF SBA)
    { firstName: "Sam", lastName: "Khansarinia", position: "C", eligibility: "SO", homeState: "CA", hometown: "Irvine", jerseyNumber: 18,
      hitForAvg: 30, power: 26, speed: 22, arm: 50, fielding: 44, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 30, grit: 35, stealing: 6, running: 20, throwing: 50, recovery: 30, wRISP: 30, vsLefty: 28, poise: 32, heater: 0, agile: 26,
      abilities: [], potential: "B-", catcherAbility: 42,
      skinTone: "light", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // INFIELDERS (7)
    // Roch Cholowsky — JR SS, projected #1 overall MLB pick, .335/18HR/62R, leads B10 in runs, generational talent
    { firstName: "Roch", lastName: "Cholowsky", position: "SS", eligibility: "JR", homeState: "CA", hometown: "Oceanside", jerseyNumber: 2,
      hitForAvg: 90, power: 86, speed: 70, arm: 80, fielding: 84, errorResistance: 80, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 88, vsLHP: 86, grit: 84, stealing: 38, running: 70, throwing: 82, recovery: 68, wRISP: 88, vsLefty: 86, poise: 86, heater: 0, agile: 70,
      abilities: ["Power Surge", "Clutch Hitter", "Contact Machine"], potential: "A", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Mulivai Levu — 1B, .347/14HR/54RBI, All-Conference 2025
    { firstName: "Mulivai", lastName: "Levu", position: "1B", eligibility: "JR", homeState: "HI", hometown: "Honolulu", jerseyNumber: 24,
      hitForAvg: 78, power: 74, speed: 30, arm: 56, fielding: 60, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 76, vsLHP: 70, grit: 74, stealing: 8, running: 28, throwing: 56, recovery: 54, wRISP: 78, vsLefty: 68, poise: 74, heater: 0, agile: 32,
      abilities: ["Power Surge", "Clutch Hitter"], potential: "A-", catcherAbility: null,
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Roman Martin — SO, .339/7HR, All-Conference, hybrid C/3B per Daily Bruin
    { firstName: "Roman", lastName: "Martin", position: "3B", eligibility: "SO", homeState: "CA", hometown: "Chino Hills", jerseyNumber: 8,
      hitForAvg: 76, power: 60, speed: 38, arm: 64, fielding: 62, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 70, vsLHP: 68, grit: 68, stealing: 14, running: 35, throwing: 65, recovery: 52, wRISP: 70, vsLefty: 66, poise: 70, heater: 0, agile: 44,
      abilities: ["Contact Machine", "Iron Glove"], potential: "A-", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Aidan Espinoza — FR INF, .360 (team batting leader), Sherman Oaks/Notre Dame HS
    { firstName: "Aidan", lastName: "Espinoza", position: "2B", eligibility: "FR", homeState: "CA", hometown: "Sherman Oaks", jerseyNumber: 6,
      hitForAvg: 78, power: 50, speed: 50, arm: 56, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 65, vsLHP: 64, grit: 62, stealing: 22, running: 47, throwing: 56, recovery: 50, wRISP: 68, vsLefty: 66, poise: 64, heater: 0, agile: 54,
      abilities: ["Contact Machine", "Table Setter"], potential: "A", catcherAbility: null,
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Phoenix Call — SO INF, 1 HR, role player
    { firstName: "Phoenix", lastName: "Call", position: "SS", eligibility: "SO", homeState: "CA", hometown: "Anaheim", jerseyNumber: 3,
      hitForAvg: 38, power: 32, speed: 42, arm: 50, fielding: 52, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 22, running: 40, throwing: 52, recovery: 36, wRISP: 38, vsLefty: 36, poise: 40, heater: 0, agile: 50,
      abilities: [], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "medium",
      ...noPitches },
    // Cole Lee — depth IF (mentioned in PDF SBA totals)
    { firstName: "Cole", lastName: "Lee", position: "2B", eligibility: "FR", homeState: "CA", hometown: "Glendale", jerseyNumber: 14,
      hitForAvg: 32, power: 26, speed: 38, arm: 42, fielding: 40, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 30, grit: 34, stealing: 18, running: 36, throwing: 42, recovery: 30, wRISP: 30, vsLefty: 28, poise: 32, heater: 0, agile: 42,
      abilities: [], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Tommy Bott — backup 1B/depth (mentioned in PDF SBA)
    { firstName: "Tommy", lastName: "Bott", position: "1B", eligibility: "FR", homeState: "CA", hometown: "San Clemente", jerseyNumber: 28,
      hitForAvg: 30, power: 32, speed: 25, arm: 44, fielding: 40, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 30, vsLHP: 28, grit: 32, stealing: 8, running: 24, throwing: 44, recovery: 30, wRISP: 30, vsLefty: 27, poise: 30, heater: 0, agile: 28,
      abilities: [], potential: "B", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // OUTFIELDERS (6)
    // Will Gasparino — JR OF, Texas transfer, .322/18HR (team co-leader), LA/Harvard-Westlake, two-time All-Big 12, SEC All-Defense
    { firstName: "Will", lastName: "Gasparino", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 11,
      hitForAvg: 74, power: 80, speed: 52, arm: 70, fielding: 68, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 72, vsLHP: 68, grit: 70, stealing: 28, running: 50, throwing: 70, recovery: 56, wRISP: 76, vsLefty: 68, poise: 72, heater: 0, agile: 56,
      abilities: ["Power Surge", "Cannon Arm"], potential: "A-", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "medium",
      ...noPitches },
    // Dean West — LF leadoff, .470 OBP, JR, walks/HBP machine
    { firstName: "Dean", lastName: "West", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Temecula", jerseyNumber: 7,
      hitForAvg: 68, power: 50, speed: 60, arm: 54, fielding: 58, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 64, grit: 76, stealing: 42, running: 58, throwing: 56, recovery: 52, wRISP: 64, vsLefty: 64, poise: 68, heater: 0, agile: 60,
      abilities: ["Table Setter", "Speed Demon"], potential: "A-", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Payton Brennan — JR OF, 8 HR, 6 SB
    { firstName: "Payton", lastName: "Brennan", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Anaheim", jerseyNumber: 9,
      hitForAvg: 60, power: 60, speed: 55, arm: 56, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 35, running: 52, throwing: 58, recovery: 48, wRISP: 60, vsLefty: 56, poise: 60, heater: 0, agile: 52,
      abilities: ["Clutch Hitter"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Daylen Reyes — SO OF speed/defense
    { firstName: "Daylen", lastName: "Reyes", position: "OF", eligibility: "SO", homeState: "CA", hometown: "Oxnard", jerseyNumber: 30,
      hitForAvg: 46, power: 40, speed: 64, arm: 60, fielding: 58, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 42, grit: 48, stealing: 42, running: 60, throwing: 60, recovery: 44, wRISP: 44, vsLefty: 42, poise: 46, heater: 0, agile: 60,
      abilities: ["Speed Demon"], potential: "B+", catcherAbility: null,
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Tristan Iwanaga — depth OF (mentioned PDF SBA 2-2)
    { firstName: "Tristan", lastName: "Iwanaga", position: "OF", eligibility: "SO", homeState: "HI", hometown: "Honolulu", jerseyNumber: 17,
      hitForAvg: 38, power: 32, speed: 50, arm: 48, fielding: 50, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 36, grit: 42, stealing: 28, running: 48, throwing: 50, recovery: 38, wRISP: 38, vsLefty: 36, poise: 40, heater: 0, agile: 50,
      abilities: [], potential: "B", catcherAbility: null,
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Michael Curialle — JR OF depth
    { firstName: "Michael", lastName: "Curialle", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Rancho Cucamonga", jerseyNumber: 26,
      hitForAvg: 36, power: 32, speed: 36, arm: 42, fielding: 42, errorResistance: 40, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 36, vsLHP: 34, grit: 38, stealing: 18, running: 34, throwing: 42, recovery: 32, wRISP: 34, vsLefty: 32, poise: 36, heater: 0, agile: 38,
      abilities: [], potential: "B", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
  ],

  "Washington": [
    // PITCHERS (10)
    { firstName: "Hayden", lastName: "Lewis", position: "P", eligibility: "SR", homeState: "AZ", hometown: "Tucson", jerseyNumber: 17,
      hitForAvg: 21, power: 16, speed: 39, arm: 83, fielding: 53, errorResistance: 55, velocity: 85, control: 80, stamina: 80, stuff: 83,
      clutch: 78, vsLHP: 74, grit: 80, stealing: 10, running: 35, throwing: 80, recovery: 74, wRISP: 76, vsLefty: 78, poise: 80, heater: 85, agile: 43,
      abilities: ["Ace", "Strong Starter", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 7, 5, 5, 0, 0, 0]) },
    { firstName: "Nate", lastName: "Tichy", position: "P", eligibility: "SO", homeState: "CA", hometown: "Malibu", jerseyNumber: 18,
      hitForAvg: 13, power: 10, speed: 37, arm: 64, fielding: 40, errorResistance: 41, velocity: 68, control: 60, stamina: 62, stuff: 66,
      clutch: 56, vsLHP: 52, grit: 57, stealing: 10, running: 33, throwing: 62, recovery: 52, wRISP: 54, vsLefty: 56, poise: 57, heater: 68, agile: 40,
      abilities: ["Strong Starter", "Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 5, 0, 0, 0]) },
    { firstName: "Liam", lastName: "Lierman", position: "P", eligibility: "FR", homeState: "AK", hometown: "Anchorage", jerseyNumber: 15,
      hitForAvg: 11, power: 8, speed: 27, arm: 48, fielding: 30, errorResistance: 31, velocity: 52, control: 45, stamina: 46, stuff: 49,
      clutch: 38, vsLHP: 37, grit: 40, stealing: 8, running: 24, throwing: 46, recovery: 37, wRISP: 37, vsLefty: 39, poise: 39, heater: 52, agile: 30,
      abilities: ["Guts"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Cooper", lastName: "Benson", position: "P", eligibility: "SR", homeState: "OR", hometown: "Portland", jerseyNumber: 41,
      hitForAvg: 14, power: 11, speed: 28, arm: 58, fielding: 38, errorResistance: 41, velocity: 61, control: 58, stamina: 56, stuff: 58,
      clutch: 56, vsLHP: 52, grit: 56, stealing: 8, running: 25, throwing: 56, recovery: 54, wRISP: 54, vsLefty: 56, poise: 56, heater: 61, agile: 32,
      abilities: ["Fireman", "Workhorse"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 6, 0, 5, 4, 0, 0]) },
    { firstName: "Parker", lastName: "Pistone", position: "P", eligibility: "JR", homeState: "WA", hometown: "Redmond", jerseyNumber: 22,
      hitForAvg: 14, power: 11, speed: 31, arm: 58, fielding: 36, errorResistance: 38, velocity: 61, control: 58, stamina: 59, stuff: 59,
      clutch: 53, vsLHP: 49, grit: 54, stealing: 8, running: 27, throwing: 56, recovery: 51, wRISP: 51, vsLefty: 53, poise: 54, heater: 61, agile: 34,
      abilities: ["Strong Starter"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Sam", lastName: "Strohl", position: "P", eligibility: "JR", homeState: "WA", hometown: "Olympia", jerseyNumber: 38,
      hitForAvg: 16, power: 12, speed: 32, arm: 59, fielding: 39, errorResistance: 40, velocity: 63, control: 59, stamina: 57, stuff: 60,
      clutch: 53, vsLHP: 50, grit: 54, stealing: 9, running: 29, throwing: 57, recovery: 53, wRISP: 50, vsLefty: 54, poise: 54, heater: 63, agile: 36,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Quinn", lastName: "Mathews", position: "P", eligibility: "SO", homeState: "WA", hometown: "Spokane", jerseyNumber: 48,
      hitForAvg: 10, power: 9, speed: 30, arm: 49, fielding: 31, errorResistance: 33, velocity: 51, control: 47, stamina: 46, stuff: 49,
      clutch: 40, vsLHP: 39, grit: 41, stealing: 10, running: 27, throwing: 47, recovery: 39, wRISP: 39, vsLefty: 41, poise: 40, heater: 51, agile: 33,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 4, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Bremner", position: "P", eligibility: "SO", homeState: "OR", hometown: "Eugene", jerseyNumber: 50,
      hitForAvg: 9, power: 8, speed: 25, arm: 42, fielding: 27, errorResistance: 28, velocity: 45, control: 41, stamina: 41, stuff: 42,
      clutch: 33, vsLHP: 32, grit: 35, stealing: 8, running: 23, throwing: 41, recovery: 32, wRISP: 32, vsLefty: 35, poise: 33, heater: 45, agile: 28,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    { firstName: "Nate", lastName: "Weeldreyer", position: "P", eligibility: "JR", homeState: "WA", hometown: "Lynnwood", jerseyNumber: 36,
      hitForAvg: 11, power: 8, speed: 23, arm: 42, fielding: 28, errorResistance: 29, velocity: 45, control: 41, stamina: 41, stuff: 42,
      clutch: 38, vsLHP: 37, grit: 39, stealing: 6, running: 20, throwing: 41, recovery: 38, wRISP: 37, vsLefty: 39, poise: 39, heater: 45, agile: 25,
      abilities: [], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Harmon", position: "P", eligibility: "SO", homeState: "CA", hometown: "San Bernardino", jerseyNumber: 45,
      hitForAvg: 11, power: 8, speed: 27, arm: 46, fielding: 31, errorResistance: 32, velocity: 50, control: 45, stamina: 45, stuff: 46,
      clutch: 39, vsLHP: 37, grit: 40, stealing: 8, running: 25, throwing: 45, recovery: 37, wRISP: 37, vsLefty: 40, poise: 40, heater: 50, agile: 31,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Colton", lastName: "Bower", position: "C", eligibility: "JR", homeState: "WA", hometown: "Pullman", jerseyNumber: 2,
      hitForAvg: 55, power: 48, speed: 32, arm: 62, fielding: 60, errorResistance: 59, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 53, grit: 59, stealing: 14, running: 31, throwing: 63, recovery: 48, wRISP: 55, vsLefty: 52, poise: 56, heater: 0, agile: 36,
      abilities: ["Iron Glove"], potential: "B+", catcherAbility: 56,
      ...noPitches },
    { firstName: "Ethan", lastName: "Swidler", position: "C", eligibility: "SR", homeState: "PA", hometown: "Easton", jerseyNumber: 4,
      hitForAvg: 51, power: 44, speed: 30, arm: 57, fielding: 55, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 49, grit: 54, stealing: 12, running: 28, throwing: 59, recovery: 44, wRISP: 51, vsLefty: 47, poise: 52, heater: 0, agile: 31,
      abilities: ["Guts"], potential: "B", catcherAbility: 52,
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Ty", lastName: "Cowan", position: "SS", eligibility: "SR", homeState: "WA", hometown: "Kirkland", jerseyNumber: 1,
      hitForAvg: 49, power: 41, speed: 48, arm: 52, fielding: 53, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 46, grit: 51, stealing: 37, running: 46, throwing: 53, recovery: 41, wRISP: 48, vsLefty: 46, poise: 49, heater: 0, agile: 51,
      abilities: ["Iron Glove", "Speed Demon"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Chase", lastName: "Cretti", position: "3B", eligibility: "JR", homeState: "WA", hometown: "Sammamish", jerseyNumber: 3,
      hitForAvg: 55, power: 49, speed: 41, arm: 58, fielding: 56, errorResistance: 55, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 55, vsLHP: 51, grit: 56, stealing: 20, running: 40, throwing: 59, recovery: 45, wRISP: 53, vsLefty: 49, poise: 55, heater: 0, agile: 44,
      abilities: ["Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Blake", lastName: "Wilson", position: "1B", eligibility: "JR", homeState: "WA", hometown: "Bellevue", jerseyNumber: 7,
      hitForAvg: 55, power: 53, speed: 36, arm: 53, fielding: 55, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 55, vsLHP: 52, grit: 56, stealing: 14, running: 35, throwing: 55, recovery: 45, wRISP: 53, vsLefty: 50, poise: 55, heater: 0, agile: 38,
      abilities: ["Power Surge"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Casen", lastName: "Taggart", position: "2B", eligibility: "SR", homeState: "WA", hometown: "Pullman", jerseyNumber: 12,
      hitForAvg: 54, power: 42, speed: 50, arm: 54, fielding: 58, errorResistance: 57, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 50, grit: 54, stealing: 33, running: 48, throwing: 57, recovery: 45, wRISP: 52, vsLefty: 48, poise: 53, heater: 0, agile: 53,
      abilities: ["Table Setter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Landon", lastName: "Young", position: "SS", eligibility: "FR", homeState: "TX", hometown: "Fort Worth", jerseyNumber: 6,
      hitForAvg: 35, power: 28, speed: 44, arm: 42, fielding: 39, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 34, vsLHP: 31, grit: 35, stealing: 28, running: 42, throwing: 44, recovery: 29, wRISP: 32, vsLefty: 29, poise: 32, heater: 0, agile: 45,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Alexander", lastName: "Pearson", position: "1B", eligibility: "FR", homeState: "WA", hometown: "Seattle", jerseyNumber: 11,
      hitForAvg: 41, power: 38, speed: 35, arm: 50, fielding: 46, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 35, grit: 41, stealing: 13, running: 34, throwing: 51, recovery: 35, wRISP: 37, vsLefty: 34, poise: 37, heater: 0, agile: 37,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jake", lastName: "Dukart", position: "2B", eligibility: "FR", homeState: "WA", hometown: "Pasco", jerseyNumber: 14,
      hitForAvg: 33, power: 25, speed: 43, arm: 42, fielding: 39, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 29, grit: 33, stealing: 25, running: 42, throwing: 43, recovery: 28, wRISP: 29, vsLefty: 28, poise: 32, heater: 0, agile: 45,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Aidan", lastName: "Dougherty", position: "OF", eligibility: "SR", homeState: "CA", hometown: "San Jose", jerseyNumber: 9,
      hitForAvg: 54, power: 49, speed: 52, arm: 54, fielding: 53, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 52, grit: 56, stealing: 36, running: 49, throwing: 56, recovery: 43, wRISP: 54, vsLefty: 49, poise: 54, heater: 0, agile: 53,
      abilities: ["Cannon Arm", "Clutch Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Braeden", lastName: "Terry", position: "OF", eligibility: "SR", homeState: "WA", hometown: "Tacoma", jerseyNumber: 10,
      hitForAvg: 49, power: 45, speed: 47, arm: 52, fielding: 49, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 47, grit: 52, stealing: 32, running: 45, throwing: 53, recovery: 41, wRISP: 48, vsLefty: 45, poise: 49, heater: 0, agile: 48,
      abilities: ["Contact Machine"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Mic", lastName: "Paul", position: "OF", eligibility: "JR", homeState: "LA", hometown: "Baton Rouge", jerseyNumber: 13,
      hitForAvg: 48, power: 44, speed: 48, arm: 49, fielding: 47, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 44, grit: 48, stealing: 36, running: 47, throwing: 50, recovery: 38, wRISP: 45, vsLefty: 42, poise: 47, heater: 0, agile: 49,
      abilities: ["Speed Demon", "Cannon Arm"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jackson", lastName: "Hotchkiss", position: "OF", eligibility: "SO", homeState: "WA", hometown: "Vancouver", jerseyNumber: 19,
      hitForAvg: 46, power: 39, speed: 49, arm: 50, fielding: 47, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 41, grit: 46, stealing: 31, running: 47, throwing: 51, recovery: 38, wRISP: 42, vsLefty: 39, poise: 44, heater: 0, agile: 50,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Kyle", lastName: "Seymour", position: "OF", eligibility: "FR", homeState: "WA", hometown: "Lynnwood", jerseyNumber: 26,
      hitForAvg: 32, power: 27, speed: 44, arm: 41, fielding: 37, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 31, vsLHP: 30, grit: 32, stealing: 26, running: 41, throwing: 44, recovery: 30, wRISP: 30, vsLefty: 27, poise: 30, heater: 0, agile: 45,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "JR", lastName: "Ritger", position: "OF", eligibility: "SO", homeState: "WI", hometown: "Appleton", jerseyNumber: 30,
      hitForAvg: 36, power: 31, speed: 38, arm: 40, fielding: 37, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 35, vsLHP: 32, grit: 36, stealing: 25, running: 37, throwing: 41, recovery: 30, wRISP: 33, vsLefty: 31, poise: 35, heater: 0, agile: 40,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
  ],
};
