import { RealPlayer } from "./realRosters";
import { pitchMix, noPitches } from "./pitchMixHelpers";

export const BIG_TEN_BATCH1_ROSTERS: Record<string, RealPlayer[]> = {
  "Illinois": [
    // PITCHERS (10)
    { firstName: "Regan", lastName: "Hall", position: "P", eligibility: "JR", homeState: "IL", hometown: "Champaign", jerseyNumber: 34,
      hitForAvg: 18, power: 14, speed: 40, arm: 53, fielding: 32, errorResistance: 52, velocity: 58, control: 49, stamina: 50, stuff: 53,
      clutch: 77, vsLHP: 72, grit: 79, stealing: 12, running: 36, throwing: 82, recovery: 44, wRISP: 46, vsLefty: 49, poise: 49, heater: 53, agile: 46,
      abilities: ["Star of Victory", "Strong Starter", "Sharpness", "Groundball Pitcher", "Intimidator", "Heavy Ball", "vs. Strong Batters"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 7, 6, 1, 0, 0, 0]) },
    { firstName: "Zach", lastName: "Bates", position: "P", eligibility: "SR", homeState: "IL", hometown: "Peoria", jerseyNumber: 29,
      hitForAvg: 16, power: 13, speed: 33, arm: 37, fielding: 22, errorResistance: 44, velocity: 38, control: 36, stamina: 32, stuff: 37,
      clutch: 65, vsLHP: 60, grit: 66, stealing: 8, running: 29, throwing: 66, recovery: 33, wRISP: 34, vsLefty: 34, poise: 36, heater: 37, agile: 39,
      abilities: ["Fireman", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 7, 5, 1, 0, 0, 0]) },
    { firstName: "Mitch", lastName: "Dye", position: "P", eligibility: "SR", homeState: "IL", hometown: "Bloomington", jerseyNumber: 38,
      hitForAvg: 13, power: 10, speed: 32, arm: 31, fielding: 21, errorResistance: 43, velocity: 29, control: 31, stamina: 28, stuff: 31,
      clutch: 58, vsLHP: 55, grit: 60, stealing: 9, running: 29, throwing: 60, recovery: 28, wRISP: 28, vsLefty: 29, poise: 30, heater: 31, agile: 36,
      abilities: ["Guts", "Strong Finisher"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Jorge", lastName: "DeCardenas", position: "P", eligibility: "JR", homeState: "FL", hometown: "Miami", jerseyNumber: 22,
      hitForAvg: 9, power: 7, speed: 23, arm: 25, fielding: 16, errorResistance: 27, velocity: 24, control: 24, stamina: 24, stuff: 25,
      clutch: 35, vsLHP: 35, grit: 37, stealing: 7, running: 21, throwing: 39, recovery: 21, wRISP: 21, vsLefty: 23, poise: 23, heater: 25, agile: 25,
      abilities: ["Fireman", "Low Ball"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Landon", lastName: "Yorek", position: "P", eligibility: "JR", homeState: "IL", hometown: "Naperville", jerseyNumber: 40,
      hitForAvg: 17, power: 14, speed: 37, arm: 39, fielding: 25, errorResistance: 46, velocity: 39, control: 38, stamina: 38, stuff: 39,
      clutch: 62, vsLHP: 60, grit: 64, stealing: 9, running: 33, throwing: 68, recovery: 34, wRISP: 34, vsLefty: 36, poise: 36, heater: 39, agile: 40,
      abilities: ["Sharpness", "Showtime", "Intimidator", "Straddle"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 1, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Johnson", position: "P", eligibility: "JR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 42,
      hitForAvg: 15, power: 11, speed: 33, arm: 30, fielding: 20, errorResistance: 42, velocity: 33, control: 30, stamina: 28, stuff: 30,
      clutch: 55, vsLHP: 53, grit: 57, stealing: 10, running: 30, throwing: 60, recovery: 26, wRISP: 26, vsLefty: 27, poise: 28, heater: 30, agile: 37,
      abilities: ["Strong Starter", "Iron Arm"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Tore", lastName: "Indomenico", position: "P", eligibility: "JR", homeState: "IN", hometown: "Granger", jerseyNumber: 44,
      hitForAvg: 11, power: 8, speed: 26, arm: 20, fielding: 13, errorResistance: 33, velocity: 20, control: 20, stamina: 19, stuff: 20,
      clutch: 44, vsLHP: 41, grit: 46, stealing: 7, running: 23, throwing: 47, recovery: 17, wRISP: 17, vsLefty: 18, poise: 19, heater: 20, agile: 29,
      abilities: ["Houdini", "Flyball Pitcher"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Liam", lastName: "McKillop", position: "P", eligibility: "JR", homeState: "IL", hometown: "Edwardsville", jerseyNumber: 46,
      hitForAvg: 12, power: 8, speed: 27, arm: 33, fielding: 21, errorResistance: 32, velocity: 35, control: 32, stamina: 32, stuff: 33,
      clutch: 43, vsLHP: 42, grit: 44, stealing: 7, running: 24, throwing: 47, recovery: 29, wRISP: 29, vsLefty: 30, poise: 30, heater: 33, agile: 30,
      abilities: ["Explosive Fastball"], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Ike", lastName: "Young", position: "P", eligibility: "FR", homeState: "IL", hometown: "Monticello", jerseyNumber: 48,
      hitForAvg: 11, power: 8, speed: 34, arm: 18, fielding: 11, errorResistance: 32, velocity: 19, control: 14, stamina: 14, stuff: 18,
      clutch: 34, vsLHP: 32, grit: 35, stealing: 11, running: 31, throwing: 51, recovery: 12, wRISP: 11, vsLefty: 12, poise: 12, heater: 18, agile: 37,
      abilities: ["Wizard Mode", "Wild Fastball", "Hot Head"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    { firstName: "Aiden", lastName: "Flinn", position: "P", eligibility: "FR", homeState: "IL", hometown: "Elmhurst", jerseyNumber: 50,
      hitForAvg: 11, power: 9, speed: 37, arm: 26, fielding: 15, errorResistance: 36, velocity: 25, control: 21, stamina: 20, stuff: 25,
      clutch: 37, vsLHP: 36, grit: 39, stealing: 11, running: 33, throwing: 56, recovery: 17, wRISP: 17, vsLefty: 18, poise: 17, heater: 25, agile: 41,
      abilities: ["Strikeout", "Flyball Pitcher"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Daniel", lastName: "Contreras", position: "C", eligibility: "JR", homeState: "IL", hometown: "Normal", jerseyNumber: 14,
      hitForAvg: 52, power: 46, speed: 34, arm: 61, fielding: 60, errorResistance: 57, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 55, vsLHP: 51, grit: 56, stealing: 16, running: 33, throwing: 63, recovery: 46, wRISP: 52, vsLefty: 49, poise: 55, heater: 0, agile: 38,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: 57,
      ...noPitches },
    { firstName: "Brady", lastName: "Schultz", position: "C", eligibility: "FR", homeState: "IL", hometown: "Barrington", jerseyNumber: 18,
      hitForAvg: 32, power: 27, speed: 27, arm: 43, fielding: 39, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 31, vsLHP: 29, grit: 32, stealing: 11, running: 25, throwing: 45, recovery: 29, wRISP: 29, vsLefty: 27, poise: 31, heater: 0, agile: 29,
      abilities: ["Trash Talker", "Walkoff Hitter"], potential: "B+", catcherAbility: 43,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Cole", lastName: "Warehime", position: "1B", eligibility: "JR", homeState: "MO", hometown: "Cape Girardeau", jerseyNumber: 8,
      hitForAvg: 59, power: 58, speed: 39, arm: 55, fielding: 58, errorResistance: 55, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 59, stealing: 14, running: 38, throwing: 58, recovery: 49, wRISP: 58, vsLefty: 51, poise: 58, heater: 0, agile: 41,
      abilities: ["Power Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Michael", lastName: "Farina", position: "2B", eligibility: "JR", homeState: "IL", hometown: "Orland Park", jerseyNumber: 10,
      hitForAvg: 59, power: 45, speed: 51, arm: 57, fielding: 62, errorResistance: 61, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 57, vsLHP: 53, grit: 59, stealing: 34, running: 49, throwing: 59, recovery: 48, wRISP: 55, vsLefty: 51, poise: 57, heater: 0, agile: 55,
      abilities: ["Chance Maker"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Matt", lastName: "Rose", position: "3B", eligibility: "JR", homeState: "IL", hometown: "Springfield", jerseyNumber: 5,
      hitForAvg: 55, power: 51, speed: 42, arm: 57, fielding: 55, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 51, grit: 55, stealing: 23, running: 40, throwing: 59, recovery: 45, wRISP: 52, vsLefty: 48, poise: 54, heater: 0, agile: 45,
      abilities: ["Contact Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "J.R.", lastName: "Nelson", position: "SS", eligibility: "JR", homeState: "OH", hometown: "Athens", jerseyNumber: 2,
      hitForAvg: 49, power: 39, speed: 48, arm: 54, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 45, grit: 49, stealing: 35, running: 46, throwing: 55, recovery: 40, wRISP: 46, vsLefty: 43, poise: 48, heater: 0, agile: 51,
      abilities: ["Defensive Artisan", "Express Baserunning"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Ethan", lastName: "Driscoll", position: "2B", eligibility: "FR", homeState: "IL", hometown: "Libertyville", jerseyNumber: 24,
      hitForAvg: 33, power: 25, speed: 41, arm: 43, fielding: 40, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 31, vsLHP: 29, grit: 33, stealing: 23, running: 40, throwing: 44, recovery: 29, wRISP: 29, vsLefty: 28, poise: 31, heater: 0, agile: 43,
      abilities: ["Tough Out", "Bad Mood"], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (7)
    { firstName: "Collin", lastName: "Jennings", position: "OF", eligibility: "JR", homeState: "IL", hometown: "Yorkville", jerseyNumber: 1,
      hitForAvg: 49, power: 50, speed: 42, arm: 46, fielding: 45, errorResistance: 43, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 46, grit: 50, stealing: 29, running: 41, throwing: 47, recovery: 38, wRISP: 49, vsLefty: 45, poise: 49, heater: 0, agile: 43,
      abilities: ["Power Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Nick", lastName: "Groves", position: "OF", eligibility: "SR", homeState: "IL", hometown: "Normal", jerseyNumber: 4,
      hitForAvg: 51, power: 47, speed: 44, arm: 50, fielding: 48, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 47, grit: 51, stealing: 29, running: 42, throwing: 51, recovery: 40, wRISP: 48, vsLefty: 45, poise: 50, heater: 0, agile: 45,
      abilities: ["High-Speed Laser"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "Pruitt", position: "OF", eligibility: "JR", homeState: "IL", hometown: "Dunlap", jerseyNumber: 7,
      hitForAvg: 50, power: 42, speed: 46, arm: 50, fielding: 48, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 45, grit: 50, stealing: 31, running: 45, throwing: 52, recovery: 39, wRISP: 46, vsLefty: 43, poise: 48, heater: 0, agile: 48,
      abilities: ["Contact Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Cole", lastName: "Crafton", position: "OF", eligibility: "JR", homeState: "KY", hometown: "Louisville", jerseyNumber: 9,
      hitForAvg: 54, power: 50, speed: 50, arm: 56, fielding: 53, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 50, grit: 54, stealing: 33, running: 48, throwing: 58, recovery: 44, wRISP: 51, vsLefty: 48, poise: 53, heater: 0, agile: 51,
      abilities: ["Walkoff Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Kyle", lastName: "Remington", position: "OF", eligibility: "JR", homeState: "MN", hometown: "Woodbury", jerseyNumber: 11,
      hitForAvg: 48, power: 42, speed: 48, arm: 55, fielding: 48, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 44, grit: 48, stealing: 33, running: 47, throwing: 57, recovery: 41, wRISP: 45, vsLefty: 42, poise: 47, heater: 0, agile: 50,
      abilities: ["Trickster", "Consigliere"], potential: "B-", catcherAbility: null,
      ...noPitches },
    { firstName: "Nolan", lastName: "Hartman", position: "OF", eligibility: "FR", homeState: "IL", hometown: "Wheaton", jerseyNumber: 26,
      hitForAvg: 36, power: 30, speed: 49, arm: 48, fielding: 40, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 33, vsLHP: 32, grit: 36, stealing: 30, running: 48, throwing: 49, recovery: 32, wRISP: 32, vsLefty: 30, poise: 33, heater: 0, agile: 52,
      abilities: ["Error Prone"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Drew", lastName: "Pearson", position: "DH", eligibility: "JR", homeState: "IL", hometown: "Champaign", jerseyNumber: 20,
      hitForAvg: 44, power: 41, speed: 28, arm: 35, fielding: 30, errorResistance: 28, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 41, grit: 46, stealing: 10, running: 27, throwing: 37, recovery: 35, wRISP: 43, vsLefty: 40, poise: 43, heater: 0, agile: 30,
      abilities: ["Consigliere"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Marcus", lastName: "Tanner", position: "1B", eligibility: "SO", homeState: "IL", hometown: "Plainfield", jerseyNumber: 32,
      hitForAvg: 36, power: 33, speed: 32, arm: 43, fielding: 39, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 35, vsLHP: 32, grit: 36, stealing: 11, running: 30, throwing: 44, recovery: 32, wRISP: 33, vsLefty: 30, poise: 33, heater: 0, agile: 33,
      abilities: ["Surprise!", "Contact Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
  ],

  "Indiana": [
    // PITCHERS (10)
    { firstName: "Tony", lastName: "Neubeck", position: "P", eligibility: "SR", homeState: "MO", hometown: "Columbia", jerseyNumber: 34,
      hitForAvg: 20, power: 16, speed: 41, arm: 52, fielding: 31, errorResistance: 51, velocity: 56, control: 48, stamina: 48, stuff: 52,
      clutch: 74, vsLHP: 70, grit: 76, stealing: 12, running: 37, throwing: 82, recovery: 44, wRISP: 45, vsLefty: 46, poise: 48, heater: 52, agile: 45,
      abilities: ["Star of Victory", "Intimidator", "Strong Starter", "Heavy Ball", "Winner's Luck", "Pace", "Straddle"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 7, 5, 1, 0, 0, 0]) },
    { firstName: "Jackson", lastName: "Bergman", position: "P", eligibility: "SR", homeState: "OH", hometown: "Toledo", jerseyNumber: 29,
      hitForAvg: 16, power: 13, speed: 35, arm: 39, fielding: 24, errorResistance: 46, velocity: 42, control: 38, stamina: 38, stuff: 39,
      clutch: 65, vsLHP: 60, grit: 67, stealing: 9, running: 32, throwing: 68, recovery: 34, wRISP: 34, vsLefty: 37, poise: 37, heater: 39, agile: 41,
      abilities: ["Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Chase", lastName: "Linn", position: "P", eligibility: "JR", homeState: "IN", hometown: "Fishers", jerseyNumber: 22,
      hitForAvg: 13, power: 10, speed: 32, arm: 28, fielding: 18, errorResistance: 39, velocity: 28, control: 27, stamina: 27, stuff: 28,
      clutch: 52, vsLHP: 51, grit: 53, stealing: 10, running: 29, throwing: 57, recovery: 24, wRISP: 24, vsLefty: 25, poise: 25, heater: 28, agile: 36,
      abilities: ["Sharpness", "Intimidator"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 1, 0, 0, 0]) },
    { firstName: "Pete", lastName: "Haas", position: "P", eligibility: "SR", homeState: "IN", hometown: "Carmel", jerseyNumber: 38,
      hitForAvg: 17, power: 12, speed: 33, arm: 35, fielding: 23, errorResistance: 45, velocity: 35, control: 35, stamina: 33, stuff: 35,
      clutch: 62, vsLHP: 58, grit: 63, stealing: 9, running: 29, throwing: 63, recovery: 32, wRISP: 32, vsLefty: 33, poise: 33, heater: 35, agile: 37,
      abilities: ["Fireman", "Gyroball", "Quick Hands"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 0, 5, 0, 0]) },
    { firstName: "Brayton", lastName: "Thomas", position: "P", eligibility: "SO", homeState: "IN", hometown: "Noblesville", jerseyNumber: 37,
      hitForAvg: 10, power: 8, speed: 24, arm: 27, fielding: 18, errorResistance: 29, velocity: 29, control: 25, stamina: 25, stuff: 27,
      clutch: 36, vsLHP: 34, grit: 38, stealing: 8, running: 22, throwing: 42, recovery: 23, wRISP: 22, vsLefty: 23, poise: 23, heater: 27, agile: 27,
      abilities: ["Cross Cannon", "Intimidator"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Gavin", lastName: "Seebold", position: "P", eligibility: "SR", homeState: "IN", hometown: "Westfield", jerseyNumber: 40,
      hitForAvg: 16, power: 13, speed: 34, arm: 33, fielding: 23, errorResistance: 44, velocity: 34, control: 33, stamina: 32, stuff: 33,
      clutch: 59, vsLHP: 56, grit: 62, stealing: 9, running: 31, throwing: 62, recovery: 29, wRISP: 29, vsLefty: 31, poise: 32, heater: 33, agile: 38,
      abilities: ["Guts", "Painter"], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Anthony", lastName: "Gubitosi", position: "P", eligibility: "SR", homeState: "NJ", hometown: "Toms River", jerseyNumber: 42,
      hitForAvg: 11, power: 8, speed: 25, arm: 30, fielding: 19, errorResistance: 30, velocity: 30, control: 30, stamina: 29, stuff: 30,
      clutch: 41, vsLHP: 38, grit: 42, stealing: 7, running: 22, throwing: 44, recovery: 26, wRISP: 26, vsLefty: 27, poise: 28, heater: 30, agile: 27,
      abilities: ["Kageura"], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Owen", lastName: "Keiser", position: "P", eligibility: "SO", homeState: "IN", hometown: "Greenwood", jerseyNumber: 44,
      hitForAvg: 9, power: 6, speed: 27, arm: 28, fielding: 18, errorResistance: 30, velocity: 29, control: 27, stamina: 27, stuff: 28,
      clutch: 36, vsLHP: 35, grit: 39, stealing: 8, running: 24, throwing: 43, recovery: 23, wRISP: 22, vsLefty: 24, poise: 24, heater: 28, agile: 30,
      abilities: ["Slugger Killer"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    { firstName: "Bryce", lastName: "Donnelly", position: "P", eligibility: "FR", homeState: "IN", hometown: "Brownsburg", jerseyNumber: 48,
      hitForAvg: 10, power: 9, speed: 36, arm: 23, fielding: 14, errorResistance: 34, velocity: 23, control: 18, stamina: 18, stuff: 21,
      clutch: 36, vsLHP: 34, grit: 37, stealing: 12, running: 32, throwing: 50, recovery: 16, wRISP: 15, vsLefty: 16, poise: 16, heater: 23, agile: 39,
      abilities: ["Indomitable Soul", "Intimidator"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Costigan", position: "P", eligibility: "FR", homeState: "IN", hometown: "Zionsville", jerseyNumber: 50,
      hitForAvg: 9, power: 8, speed: 31, arm: 28, fielding: 17, errorResistance: 29, velocity: 29, control: 22, stamina: 21, stuff: 27,
      clutch: 31, vsLHP: 29, grit: 32, stealing: 9, running: 28, throwing: 44, recovery: 19, wRISP: 18, vsLefty: 20, poise: 19, heater: 28, agile: 34,
      abilities: ["Gas Tank"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "T.J.", lastName: "Schuyler", position: "C", eligibility: "JR", homeState: "IN", hometown: "Indianapolis", jerseyNumber: 12,
      hitForAvg: 57, power: 52, speed: 37, arm: 67, fielding: 65, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 61, stealing: 16, running: 35, throwing: 69, recovery: 50, wRISP: 57, vsLefty: 54, poise: 60, heater: 0, agile: 41,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: 64,
      ...noPitches },
    { firstName: "Hogan", lastName: "Denny", position: "C", eligibility: "SO", homeState: "IN", hometown: "Terre Haute", jerseyNumber: 19,
      hitForAvg: 49, power: 44, speed: 39, arm: 57, fielding: 53, errorResistance: 49, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 46, grit: 51, stealing: 20, running: 37, throwing: 58, recovery: 42, wRISP: 48, vsLefty: 44, poise: 49, heater: 0, agile: 40,
      abilities: ["Disturbance"], potential: "B+", catcherAbility: 53,
      ...noPitches },
    // INFIELDERS (5)
    { firstName: "Jake", lastName: "Hanley", position: "1B", eligibility: "SO", homeState: "IL", hometown: "Naperville", jerseyNumber: 8,
      hitForAvg: 63, power: 64, speed: 39, arm: 52, fielding: 53, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 63, vsLHP: 60, grit: 63, stealing: 14, running: 37, throwing: 53, recovery: 49, wRISP: 63, vsLefty: 58, poise: 61, heater: 0, agile: 41,
      abilities: ["Power Hitter", "Consigliere", "Contact Hitter"], potential: "A+", catcherAbility: null,
      ...noPitches },
    { firstName: "Cooper", lastName: "Malamazian", position: "SS", eligibility: "SO", homeState: "CA", hometown: "Thousand Oaks", jerseyNumber: 2,
      hitForAvg: 54, power: 43, speed: 54, arm: 59, fielding: 59, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 49, grit: 54, stealing: 40, running: 53, throwing: 61, recovery: 45, wRISP: 51, vsLefty: 48, poise: 53, heater: 0, agile: 58,
      abilities: ["Defensive Artisan", "Express Baserunning"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Will", lastName: "Moore", position: "3B", eligibility: "SO", homeState: "IN", hometown: "Bloomington", jerseyNumber: 6,
      hitForAvg: 50, power: 45, speed: 40, arm: 53, fielding: 51, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 45, grit: 50, stealing: 22, running: 39, throwing: 55, recovery: 40, wRISP: 47, vsLefty: 43, poise: 48, heater: 0, agile: 42,
      abilities: ["Contact Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Ayden", lastName: "Crouse", position: "2B", eligibility: "SR", homeState: "IN", hometown: "Evansville", jerseyNumber: 3,
      hitForAvg: 49, power: 38, speed: 44, arm: 47, fielding: 51, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 46, grit: 50, stealing: 29, running: 43, throwing: 49, recovery: 40, wRISP: 47, vsLefty: 44, poise: 49, heater: 0, agile: 46,
      abilities: ["Chance Maker"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Trey", lastName: "Meyers", position: "SS", eligibility: "FR", homeState: "IN", hometown: "Columbus", jerseyNumber: 24,
      hitForAvg: 33, power: 24, speed: 42, arm: 41, fielding: 38, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 30, vsLHP: 29, grit: 33, stealing: 27, running: 41, throwing: 42, recovery: 28, wRISP: 29, vsLefty: 28, poise: 30, heater: 0, agile: 44,
      abilities: ["Chance Maker"], potential: "A-", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Cole", lastName: "Decker", position: "OF", eligibility: "SO", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 1,
      hitForAvg: 47, power: 38, speed: 51, arm: 48, fielding: 48, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 45, vsLHP: 42, grit: 47, stealing: 38, running: 49, throwing: 49, recovery: 38, wRISP: 43, vsLefty: 40, poise: 45, heater: 0, agile: 52,
      abilities: ["Express Baserunning"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Caleb", lastName: "Koskie", position: "OF", eligibility: "SO", homeState: "MN", hometown: "Eden Prairie", jerseyNumber: 7,
      hitForAvg: 53, power: 48, speed: 53, arm: 61, fielding: 55, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 53, stealing: 36, running: 52, throwing: 62, recovery: 45, wRISP: 49, vsLefty: 46, poise: 52, heater: 0, agile: 55,
      abilities: ["High-Speed Laser"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Brayden", lastName: "Ricketts", position: "OF", eligibility: "SO", homeState: "IN", hometown: "Greenfield", jerseyNumber: 9,
      hitForAvg: 45, power: 42, speed: 39, arm: 47, fielding: 44, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 45, vsLHP: 42, grit: 47, stealing: 19, running: 38, throwing: 49, recovery: 38, wRISP: 44, vsLefty: 41, poise: 44, heater: 0, agile: 41,
      abilities: ["Consigliere"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Cal", lastName: "Gates", position: "OF", eligibility: "FR", homeState: "CA", hometown: "San Diego", jerseyNumber: 11,
      hitForAvg: 29, power: 26, speed: 35, arm: 34, fielding: 30, errorResistance: 28, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 26, vsLHP: 25, grit: 28, stealing: 23, running: 34, throwing: 35, recovery: 24, wRISP: 26, vsLefty: 24, poise: 26, heater: 0, agile: 36,
      abilities: ["High Speed Charge"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Noah", lastName: "Drake", position: "OF", eligibility: "FR", homeState: "IN", hometown: "Carmel", jerseyNumber: 26,
      hitForAvg: 31, power: 27, speed: 43, arm: 42, fielding: 36, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 30, vsLHP: 28, grit: 31, stealing: 27, running: 42, throwing: 43, recovery: 28, wRISP: 28, vsLefty: 27, poise: 30, heater: 0, agile: 44,
      abilities: ["Predicament"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Grant", lastName: "Richardson", position: "DH", eligibility: "SO", homeState: "IN", hometown: "Terre Haute", jerseyNumber: 20,
      hitForAvg: 38, power: 35, speed: 27, arm: 33, fielding: 28, errorResistance: 27, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 35, grit: 38, stealing: 9, running: 26, throwing: 35, recovery: 31, wRISP: 36, vsLefty: 33, poise: 36, heater: 0, agile: 28,
      abilities: ["Late Night Hero"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Luke", lastName: "Preston", position: "1B", eligibility: "JR", homeState: "IN", hometown: "Fishers", jerseyNumber: 32,
      hitForAvg: 36, power: 34, speed: 26, arm: 36, fielding: 34, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 36, vsLHP: 34, grit: 37, stealing: 9, running: 24, throwing: 37, recovery: 30, wRISP: 34, vsLefty: 32, poise: 34, heater: 0, agile: 27,
      abilities: ["Resilient", "First Pitch Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "James", lastName: "Hoffman", position: "OF", eligibility: "JR", homeState: "IN", hometown: "Muncie", jerseyNumber: 28,
      hitForAvg: 49, power: 44, speed: 54, arm: 55, fielding: 51, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 44, grit: 49, stealing: 34, running: 51, throwing: 57, recovery: 43, wRISP: 46, vsLefty: 43, poise: 48, heater: 0, agile: 55,
      abilities: ["Locked and Loaded", "Insurer"], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "Iowa": [
    // PITCHERS (10)
    { firstName: "Tyler", lastName: "Guerin", position: "P", eligibility: "SO", homeState: "IA", hometown: "Ankeny", jerseyNumber: 11,
      hitForAvg: 12, power: 9, speed: 30, arm: 27, fielding: 17, errorResistance: 39, velocity: 29, control: 26, stamina: 27, stuff: 27,
      clutch: 52, vsLHP: 49, grit: 54, stealing: 9, running: 27, throwing: 57, recovery: 23, wRISP: 24, vsLefty: 24, poise: 26, heater: 27, agile: 34,
      abilities: ["Strong Starter", "Guts", "Good Pickoff"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Logan", lastName: "Runde", position: "P", eligibility: "SR", homeState: "FL", hometown: "Miami", jerseyNumber: 33,
      hitForAvg: 22, power: 16, speed: 46, arm: 58, fielding: 37, errorResistance: 61, velocity: 62, control: 59, stamina: 59, stuff: 59,
      clutch: 86, vsLHP: 82, grit: 89, stealing: 12, running: 41, throwing: 87, recovery: 56, wRISP: 56, vsLefty: 57, poise: 59, heater: 60, agile: 53,
      abilities: ["Star of Victory", "Intimidator", "Heavy Ball", "Winner's Luck"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 7, 5, 1, 0, 0, 0]) },
    { firstName: "Joe", lastName: "Husak", position: "P", eligibility: "JR", homeState: "IL", hometown: "Normal", jerseyNumber: 35,
      hitForAvg: 14, power: 11, speed: 32, arm: 28, fielding: 18, errorResistance: 39, velocity: 29, control: 28, stamina: 24, stuff: 28,
      clutch: 56, vsLHP: 53, grit: 58, stealing: 10, running: 28, throwing: 58, recovery: 25, wRISP: 26, vsLefty: 26, poise: 28, heater: 28, agile: 34,
      abilities: ["Fireman", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 7, 5, 1, 0, 0, 0]) },
    { firstName: "Justin", lastName: "Hackett", position: "P", eligibility: "JR", homeState: "IA", hometown: "Iowa City", jerseyNumber: 38,
      hitForAvg: 14, power: 10, speed: 33, arm: 32, fielding: 20, errorResistance: 42, velocity: 32, control: 31, stamina: 31, stuff: 32,
      clutch: 56, vsLHP: 54, grit: 58, stealing: 9, running: 30, throwing: 61, recovery: 28, wRISP: 28, vsLefty: 30, poise: 30, heater: 32, agile: 37,
      abilities: ["Sharpness", "Natural Shuuto"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 1, 0, 0, 0]) },
    { firstName: "Ganon", lastName: "Archer", position: "P", eligibility: "JR", homeState: "IA", hometown: "Davenport", jerseyNumber: 40,
      hitForAvg: 15, power: 12, speed: 31, arm: 30, fielding: 20, errorResistance: 42, velocity: 30, control: 30, stamina: 30, stuff: 30,
      clutch: 56, vsLHP: 53, grit: 58, stealing: 9, running: 27, throwing: 58, recovery: 27, wRISP: 27, vsLefty: 28, poise: 28, heater: 30, agile: 36,
      abilities: ["Strength Distribution", "Pace", "Big Boy Speed"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Marcus", lastName: "Kruzan", position: "P", eligibility: "JR", homeState: "IN", hometown: "Greenwood", jerseyNumber: 42,
      hitForAvg: 11, power: 8, speed: 26, arm: 20, fielding: 13, errorResistance: 32, velocity: 20, control: 20, stamina: 19, stuff: 20,
      clutch: 44, vsLHP: 41, grit: 44, stealing: 7, running: 24, throwing: 46, recovery: 17, wRISP: 17, vsLefty: 19, poise: 19, heater: 20, agile: 29,
      abilities: ["Slugger Killer", "Intimidator"], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Derek", lastName: "Nagel", position: "P", eligibility: "JR", homeState: "IA", hometown: "Urbandale", jerseyNumber: 44,
      hitForAvg: 12, power: 9, speed: 28, arm: 20, fielding: 13, errorResistance: 34, velocity: 20, control: 20, stamina: 20, stuff: 20,
      clutch: 44, vsLHP: 41, grit: 46, stealing: 8, running: 25, throwing: 49, recovery: 17, wRISP: 17, vsLefty: 17, poise: 18, heater: 20, agile: 31,
      abilities: ["Straddle", "Houdini", "Slow Starter"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Braden", lastName: "Halladay", position: "P", eligibility: "SO", homeState: "IA", hometown: "Cedar Rapids", jerseyNumber: 46,
      hitForAvg: 11, power: 7, speed: 29, arm: 20, fielding: 14, errorResistance: 33, velocity: 22, control: 19, stamina: 19, stuff: 20,
      clutch: 40, vsLHP: 39, grit: 43, stealing: 9, running: 27, throwing: 47, recovery: 17, wRISP: 16, vsLefty: 17, poise: 17, heater: 20, agile: 33,
      abilities: ["Explosive Fastball", "Intimidator"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Stedman", position: "P", eligibility: "FR", homeState: "IA", hometown: "Waukee", jerseyNumber: 48,
      hitForAvg: 10, power: 8, speed: 33, arm: 33, fielding: 19, errorResistance: 31, velocity: 33, control: 25, stamina: 25, stuff: 32,
      clutch: 33, vsLHP: 31, grit: 34, stealing: 11, running: 30, throwing: 49, recovery: 21, wRISP: 20, vsLefty: 22, poise: 21, heater: 33, agile: 36,
      abilities: ["Tunneling"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    { firstName: "Jaron", lastName: "Bleeker", position: "P", eligibility: "FR", homeState: "IA", hometown: "Pella", jerseyNumber: 50,
      hitForAvg: 9, power: 7, speed: 29, arm: 28, fielding: 16, errorResistance: 28, velocity: 28, control: 22, stamina: 21, stuff: 26,
      clutch: 29, vsLHP: 28, grit: 31, stealing: 9, running: 26, throwing: 43, recovery: 18, wRISP: 17, vsLefty: 19, poise: 18, heater: 27, agile: 32,
      abilities: ["Bad Ball Hitter", "Perfect Combustion"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Drew", lastName: "Deremer", position: "C", eligibility: "SO", homeState: "IA", hometown: "Marion", jerseyNumber: 14,
      hitForAvg: 50, power: 43, speed: 35, arm: 61, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 49, grit: 54, stealing: 14, running: 32, throwing: 63, recovery: 45, wRISP: 50, vsLefty: 46, poise: 52, heater: 0, agile: 38,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: 60,
      ...noPitches },
    { firstName: "Ben", lastName: "DeTaeye", position: "C", eligibility: "SR", homeState: "IA", hometown: "Johnston", jerseyNumber: 18,
      hitForAvg: 53, power: 46, speed: 33, arm: 61, fielding: 59, errorResistance: 55, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 55, vsLHP: 52, grit: 57, stealing: 13, running: 31, throwing: 62, recovery: 47, wRISP: 53, vsLefty: 50, poise: 55, heater: 0, agile: 37,
      abilities: ["High-Speed Laser"], potential: "B", catcherAbility: 59,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Jack", lastName: "Whitlock", position: "1B", eligibility: "SR", homeState: "IA", hometown: "Des Moines", jerseyNumber: 8,
      hitForAvg: 50, power: 51, speed: 31, arm: 44, fielding: 46, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 47, grit: 51, stealing: 12, running: 30, throwing: 46, recovery: 41, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 32,
      abilities: ["Power Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Anthony", lastName: "Watts", position: "2B", eligibility: "JR", homeState: "IA", hometown: "North Liberty", jerseyNumber: 3,
      hitForAvg: 48, power: 38, speed: 45, arm: 48, fielding: 52, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 44, grit: 48, stealing: 31, running: 44, throwing: 51, recovery: 40, wRISP: 45, vsLefty: 43, poise: 47, heater: 0, agile: 47,
      abilities: ["Chance Maker"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Chas", lastName: "Wheatley", position: "3B", eligibility: "SR", homeState: "IA", hometown: "Ankeny", jerseyNumber: 5,
      hitForAvg: 56, power: 53, speed: 41, arm: 56, fielding: 54, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 53, grit: 58, stealing: 22, running: 40, throwing: 58, recovery: 46, wRISP: 54, vsLefty: 50, poise: 56, heater: 0, agile: 43,
      abilities: ["Contact Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Aaron", lastName: "Savary", position: "SS", eligibility: "JR", homeState: "IA", hometown: "Urbandale", jerseyNumber: 2,
      hitForAvg: 46, power: 36, speed: 46, arm: 51, fielding: 51, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 46, vsLHP: 43, grit: 47, stealing: 33, running: 45, throwing: 53, recovery: 39, wRISP: 45, vsLefty: 42, poise: 46, heater: 0, agile: 48,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Garrett", lastName: "Luett", position: "SS", eligibility: "FR", homeState: "IA", hometown: "Bettendorf", jerseyNumber: 24,
      hitForAvg: 28, power: 22, speed: 37, arm: 35, fielding: 33, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 27, vsLHP: 25, grit: 28, stealing: 23, running: 35, throwing: 37, recovery: 24, wRISP: 25, vsLefty: 24, poise: 27, heater: 0, agile: 38,
      abilities: ["Bad Mood"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Gavin", lastName: "DeJesus", position: "2B", eligibility: "FR", homeState: "IL", hometown: "Naperville", jerseyNumber: 16,
      hitForAvg: 34, power: 27, speed: 45, arm: 45, fielding: 41, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 33, vsLHP: 32, grit: 34, stealing: 27, running: 43, throwing: 46, recovery: 32, wRISP: 32, vsLefty: 29, poise: 33, heater: 0, agile: 46,
      abilities: ["Batter Intimidator"], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (5)
    { firstName: "Gable", lastName: "Mitchell", position: "OF", eligibility: "SR", homeState: "IA", hometown: "Iowa City", jerseyNumber: 1,
      hitForAvg: 47, power: 44, speed: 43, arm: 47, fielding: 45, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 45, grit: 49, stealing: 31, running: 41, throwing: 47, recovery: 38, wRISP: 47, vsLefty: 44, poise: 47, heater: 0, agile: 44,
      abilities: ["Contact Hitter", "Consigliere", "High-Speed Laser"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Cade", lastName: "Obermueller", position: "OF", eligibility: "JR", homeState: "IA", hometown: "Waukee", jerseyNumber: 7,
      hitForAvg: 57, power: 50, speed: 57, arm: 60, fielding: 57, errorResistance: 55, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 55, vsLHP: 51, grit: 57, stealing: 38, running: 55, throwing: 62, recovery: 47, wRISP: 53, vsLefty: 50, poise: 55, heater: 0, agile: 59,
      abilities: ["Express Baserunning"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Elliot", lastName: "Cadieux-Lanoue", position: "OF", eligibility: "SO", homeState: "MN", hometown: "Edina", jerseyNumber: 9,
      hitForAvg: 55, power: 47, speed: 60, arm: 63, fielding: 56, errorResistance: 55, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 55, stealing: 40, running: 59, throwing: 64, recovery: 44, wRISP: 51, vsLefty: 47, poise: 52, heater: 0, agile: 63,
      abilities: ["Batter Intimidator", "First Pitch Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jack", lastName: "Young", position: "OF", eligibility: "SR", homeState: "IA", hometown: "Sioux City", jerseyNumber: 4,
      hitForAvg: 51, power: 45, speed: 46, arm: 53, fielding: 51, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 51, vsLHP: 49, grit: 53, stealing: 31, running: 45, throwing: 55, recovery: 43, wRISP: 50, vsLefty: 46, poise: 51, heater: 0, agile: 49,
      abilities: ["vs. Fastballs"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Joey", lastName: "Oakie", position: "OF", eligibility: "FR", homeState: "IA", hometown: "Dubuque", jerseyNumber: 26,
      hitForAvg: 29, power: 25, speed: 40, arm: 39, fielding: 33, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 28, vsLHP: 26, grit: 29, stealing: 25, running: 39, throwing: 40, recovery: 26, wRISP: 26, vsLefty: 25, poise: 28, heater: 0, agile: 42,
      abilities: ["Counterattack", "Pressure Run", "Multi-Hit"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Sam", lastName: "Hart", position: "OF", eligibility: "SR", homeState: "IA", hometown: "Cedar Falls", jerseyNumber: 20,
      hitForAvg: 40, power: 38, speed: 25, arm: 31, fielding: 27, errorResistance: 26, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 9, running: 23, throwing: 33, recovery: 31, wRISP: 39, vsLefty: 37, poise: 39, heater: 0, agile: 26,
      abilities: ["Consigliere"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Will", lastName: "Heldt", position: "1B", eligibility: "SO", homeState: "IA", hometown: "Dubuque", jerseyNumber: 32,
      hitForAvg: 34, power: 33, speed: 27, arm: 40, fielding: 37, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 34, vsLHP: 31, grit: 35, stealing: 10, running: 25, throwing: 41, recovery: 30, wRISP: 33, vsLefty: 30, poise: 33, heater: 0, agile: 29,
      abilities: ["Counterattack", "First Pitch Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "Maryland": [
    // PITCHERS (10)
    { firstName: "Lance", lastName: "Williams", position: "P", eligibility: "SO", homeState: "NC", hometown: "Greenville", jerseyNumber: 34,
      hitForAvg: 21, power: 17, speed: 45, arm: 56, fielding: 36, errorResistance: 58, velocity: 60, control: 52, stamina: 53, stuff: 57,
      clutch: 82, vsLHP: 78, grit: 84, stealing: 15, running: 41, throwing: 87, recovery: 48, wRISP: 52, vsLefty: 53, poise: 53, heater: 58, agile: 51,
      abilities: ["Star of Victory", "Intimidator", "Strong Starter", "Straddle", "Heavy Ball", "Inside Pitch"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 7, 5, 1, 0, 0, 0]) },
    { firstName: "Austin", lastName: "Weiss", position: "P", eligibility: "FR", homeState: "MD", hometown: "Annapolis", jerseyNumber: 29,
      hitForAvg: 12, power: 8, speed: 33, arm: 38, fielding: 23, errorResistance: 34, velocity: 39, control: 32, stamina: 30, stuff: 38,
      clutch: 40, vsLHP: 39, grit: 42, stealing: 10, running: 30, throwing: 53, recovery: 26, wRISP: 27, vsLefty: 28, poise: 28, heater: 38, agile: 36,
      abilities: ["Flyball Pitcher", "Glass Heart"], potential: "A+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Cristofer", lastName: "Cespedes", position: "P", eligibility: "SO", homeState: "FL", hometown: "Miami", jerseyNumber: 37,
      hitForAvg: 15, power: 12, speed: 37, arm: 36, fielding: 23, errorResistance: 46, velocity: 38, control: 34, stamina: 33, stuff: 36,
      clutch: 58, vsLHP: 55, grit: 61, stealing: 12, running: 34, throwing: 67, recovery: 29, wRISP: 31, vsLefty: 31, poise: 31, heater: 36, agile: 42,
      abilities: ["Fireman", "True Slider", "Gyroball", "vs. Strong Batters"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 4, 1, 0, 0, 0]) },
    { firstName: "Logan", lastName: "Hastings", position: "P", eligibility: "SO", homeState: "MD", hometown: "Columbia", jerseyNumber: 35,
      hitForAvg: 15, power: 11, speed: 35, arm: 34, fielding: 23, errorResistance: 45, velocity: 34, control: 34, stamina: 34, stuff: 34,
      clutch: 56, vsLHP: 54, grit: 59, stealing: 9, running: 32, throwing: 64, recovery: 30, wRISP: 28, vsLefty: 30, poise: 30, heater: 34, agile: 39,
      abilities: ["Sharpness", "Bad Ball Hitter", "True Slider"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 6, 1, 0, 0, 0]) },
    { firstName: "Evan", lastName: "Smith", position: "P", eligibility: "JR", homeState: "MD", hometown: "Bethesda", jerseyNumber: 22,
      hitForAvg: 11, power: 8, speed: 27, arm: 33, fielding: 23, errorResistance: 33, velocity: 35, control: 33, stamina: 31, stuff: 33,
      clutch: 44, vsLHP: 41, grit: 45, stealing: 7, running: 24, throwing: 47, recovery: 28, wRISP: 29, vsLefty: 30, poise: 31, heater: 33, agile: 30,
      abilities: ["Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Brayden", lastName: "Ryan", position: "P", eligibility: "JR", homeState: "MD", hometown: "Severna Park", jerseyNumber: 38,
      hitForAvg: 17, power: 13, speed: 34, arm: 34, fielding: 24, errorResistance: 47, velocity: 35, control: 35, stamina: 34, stuff: 34,
      clutch: 61, vsLHP: 57, grit: 62, stealing: 10, running: 30, throwing: 62, recovery: 30, wRISP: 30, vsLefty: 33, poise: 33, heater: 34, agile: 40,
      abilities: ["Iron Arm", "Staredown", "Intimidator"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Bailey", position: "P", eligibility: "JR", homeState: "VA", hometown: "Ashburn", jerseyNumber: 40,
      hitForAvg: 11, power: 8, speed: 25, arm: 16, fielding: 11, errorResistance: 30, velocity: 16, control: 16, stamina: 15, stuff: 16,
      clutch: 40, vsLHP: 37, grit: 41, stealing: 7, running: 22, throwing: 42, recovery: 14, wRISP: 14, vsLefty: 14, poise: 15, heater: 16, agile: 28,
      abilities: ["Monster Stuff", "Heavy Ball", "Intimidator"], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Yeager", position: "P", eligibility: "JR", homeState: "PA", hometown: "Doylestown", jerseyNumber: 42,
      hitForAvg: 11, power: 8, speed: 27, arm: 32, fielding: 21, errorResistance: 33, velocity: 31, control: 32, stamina: 32, stuff: 32,
      clutch: 41, vsLHP: 39, grit: 42, stealing: 7, running: 24, throwing: 45, recovery: 28, wRISP: 26, vsLefty: 28, poise: 28, heater: 32, agile: 30,
      abilities: ["Sangfroid"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    { firstName: "Max", lastName: "Mendez", position: "P", eligibility: "SO", homeState: "TN", hometown: "Nashville", jerseyNumber: 44,
      hitForAvg: 13, power: 10, speed: 35, arm: 30, fielding: 20, errorResistance: 41, velocity: 32, control: 29, stamina: 28, stuff: 30,
      clutch: 54, vsLHP: 52, grit: 56, stealing: 10, running: 31, throwing: 61, recovery: 24, wRISP: 26, vsLefty: 26, poise: 26, heater: 30, agile: 38,
      abilities: ["Guts", "Decisive", "Constant Speed"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Nic", lastName: "Morlang", position: "P", eligibility: "FR", homeState: "MD", hometown: "Ellicott City", jerseyNumber: 50,
      hitForAvg: 9, power: 7, speed: 30, arm: 31, fielding: 18, errorResistance: 28, velocity: 32, control: 24, stamina: 23, stuff: 29,
      clutch: 30, vsLHP: 28, grit: 31, stealing: 9, running: 27, throwing: 44, recovery: 20, wRISP: 19, vsLefty: 21, poise: 20, heater: 31, agile: 32,
      abilities: ["Inside Pitch", "Walk"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Rylen", lastName: "Stockton", position: "C", eligibility: "SO", homeState: "NC", hometown: "Asheville", jerseyNumber: 14,
      hitForAvg: 54, power: 46, speed: 32, arm: 58, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 51, grit: 56, stealing: 14, running: 30, throwing: 59, recovery: 45, wRISP: 53, vsLefty: 50, poise: 54, heater: 0, agile: 35,
      abilities: ["Defensive Artisan", "Contact Hitter"], potential: "A-", catcherAbility: 56,
      ...noPitches },
    { firstName: "Devin", lastName: "Russell", position: "C", eligibility: "JR", homeState: "MD", hometown: "Pasadena", jerseyNumber: 18,
      hitForAvg: 32, power: 29, speed: 22, arm: 40, fielding: 37, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 34, vsLHP: 31, grit: 35, stealing: 9, running: 21, throwing: 41, recovery: 30, wRISP: 32, vsLefty: 30, poise: 32, heater: 0, agile: 25,
      abilities: ["God of Pinch Hitting", "Contact Hitter"], potential: "B", catcherAbility: 38,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Ryan", lastName: "Costello", position: "1B", eligibility: "JR", homeState: "LA", hometown: "Baton Rouge", jerseyNumber: 8,
      hitForAvg: 60, power: 63, speed: 40, arm: 58, fielding: 59, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 58, grit: 63, stealing: 15, running: 39, throwing: 59, recovery: 52, wRISP: 60, vsLefty: 55, poise: 60, heater: 0, agile: 43,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jordan", lastName: "Crosland", position: "2B", eligibility: "SO", homeState: "MD", hometown: "Bowie", jerseyNumber: 3,
      hitForAvg: 56, power: 39, speed: 47, arm: 50, fielding: 54, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 50, grit: 54, stealing: 33, running: 45, throwing: 51, recovery: 42, wRISP: 51, vsLefty: 48, poise: 53, heater: 0, agile: 48,
      abilities: ["Contact Hitter", "Chance Maker"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Brayden", lastName: "Martin", position: "3B", eligibility: "JR", homeState: "MD", hometown: "Severna Park", jerseyNumber: 5,
      hitForAvg: 59, power: 51, speed: 47, arm: 56, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 59, stealing: 28, running: 44, throwing: 58, recovery: 47, wRISP: 56, vsLefty: 52, poise: 58, heater: 0, agile: 48,
      abilities: ["Consigliere", "Contact Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Ty", lastName: "Kaunas", position: "SS", eligibility: "FR", homeState: "MD", hometown: "Columbia", jerseyNumber: 2,
      hitForAvg: 54, power: 43, speed: 62, arm: 61, fielding: 57, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 45, grit: 50, stealing: 41, running: 61, throwing: 62, recovery: 41, wRISP: 46, vsLefty: 43, poise: 49, heater: 0, agile: 64,
      abilities: ["Express Baserunning"], potential: "A+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jackson", lastName: "Sirois", position: "SS", eligibility: "SO", homeState: "VA", hometown: "Charlottesville", jerseyNumber: 10,
      hitForAvg: 55, power: 43, speed: 55, arm: 59, fielding: 59, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 50, grit: 55, stealing: 39, running: 53, throwing: 62, recovery: 44, wRISP: 51, vsLefty: 47, poise: 53, heater: 0, agile: 57,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Luke", lastName: "Crawford", position: "1B", eligibility: "JR", homeState: "MD", hometown: "Bethesda", jerseyNumber: 32,
      hitForAvg: 44, power: 43, speed: 30, arm: 44, fielding: 43, errorResistance: 39, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 43, vsLHP: 39, grit: 44, stealing: 11, running: 28, throwing: 46, recovery: 36, wRISP: 40, vsLefty: 38, poise: 40, heater: 0, agile: 31,
      abilities: ["Power Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (5)
    { firstName: "Aden", lastName: "Hill", position: "OF", eligibility: "SR", homeState: "VA", hometown: "Richmond", jerseyNumber: 1,
      hitForAvg: 47, power: 43, speed: 43, arm: 47, fielding: 46, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 45, grit: 48, stealing: 30, running: 42, throwing: 48, recovery: 39, wRISP: 46, vsLefty: 43, poise: 47, heater: 0, agile: 45,
      abilities: ["High-Speed Laser", "Contact Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Bud", lastName: "Coombs", position: "OF", eligibility: "FR", homeState: "MD", hometown: "Bel Air", jerseyNumber: 7,
      hitForAvg: 46, power: 41, speed: 56, arm: 54, fielding: 48, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 43, vsLHP: 39, grit: 45, stealing: 36, running: 54, throwing: 56, recovery: 38, wRISP: 41, vsLefty: 38, poise: 43, heater: 0, agile: 58,
      abilities: ["High Ball Hitter", "vs. Fastballs"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Nate", lastName: "Hawton-Henley", position: "OF", eligibility: "FR", homeState: "MD", hometown: "Rockville", jerseyNumber: 9,
      hitForAvg: 34, power: 30, speed: 49, arm: 47, fielding: 40, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 33, vsLHP: 32, grit: 34, stealing: 30, running: 47, throwing: 49, recovery: 32, wRISP: 32, vsLefty: 30, poise: 33, heater: 0, agile: 50,
      abilities: ["Head-first Slide", "Wide Angle Cannon", "Contact Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Chris", lastName: "Patterson", position: "OF", eligibility: "SR", homeState: "MD", hometown: "Bowie", jerseyNumber: 4,
      hitForAvg: 56, power: 49, speed: 53, arm: 58, fielding: 54, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 35, running: 50, throwing: 59, recovery: 45, wRISP: 53, vsLefty: 49, poise: 54, heater: 0, agile: 54,
      abilities: ["Express Baserunning"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Tyler", lastName: "Hoffman", position: "OF", eligibility: "JR", homeState: "MD", hometown: "Pasadena", jerseyNumber: 20,
      hitForAvg: 40, power: 38, speed: 27, arm: 33, fielding: 28, errorResistance: 27, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 38, grit: 41, stealing: 9, running: 26, throwing: 35, recovery: 32, wRISP: 39, vsLefty: 36, poise: 39, heater: 0, agile: 28,
      abilities: ["Consigliere"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Kevin", lastName: "Brennan", position: "3B", eligibility: "SR", homeState: "MD", hometown: "Bel Air", jerseyNumber: 16,
      hitForAvg: 49, power: 44, speed: 40, arm: 52, fielding: 49, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 45, grit: 50, stealing: 19, running: 38, throwing: 54, recovery: 40, wRISP: 47, vsLefty: 44, poise: 47, heater: 0, agile: 42,
      abilities: ["Laser Beam", "Error Prone"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Matt", lastName: "Whitmore", position: "OF", eligibility: "SO", homeState: "VA", hometown: "Fairfax", jerseyNumber: 28,
      hitForAvg: 30, power: 26, speed: 33, arm: 34, fielding: 31, errorResistance: 28, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 28, vsLHP: 26, grit: 30, stealing: 21, running: 32, throwing: 36, recovery: 26, wRISP: 27, vsLefty: 26, poise: 28, heater: 0, agile: 34,
      abilities: ["Emotional Pillar", "High Speed Charge"], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "Michigan": [
    // PITCHERS (10)
    { firstName: "Tate", lastName: "Carey", position: "P", eligibility: "SO", homeState: "MI", hometown: "Grand Rapids", jerseyNumber: 34,
      hitForAvg: 19, power: 15, speed: 44, arm: 54, fielding: 33, errorResistance: 55, velocity: 60, control: 50, stamina: 50, stuff: 54,
      clutch: 78, vsLHP: 74, grit: 80, stealing: 15, running: 40, throwing: 84, recovery: 46, wRISP: 48, vsLefty: 50, poise: 50, heater: 54, agile: 48,
      abilities: ["Star of Victory", "Intimidator", "Wild Fastball", "Heavy Ball", "Winner's Luck", "Pace"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 7, 5, 1, 0, 0, 0]) },
    { firstName: "Kurt", lastName: "Barr", position: "P", eligibility: "SR", homeState: "MI", hometown: "Ann Arbor", jerseyNumber: 29,
      hitForAvg: 14, power: 12, speed: 31, arm: 31, fielding: 19, errorResistance: 41, velocity: 31, control: 31, stamina: 31, stuff: 31,
      clutch: 59, vsLHP: 55, grit: 60, stealing: 8, running: 28, throwing: 60, recovery: 29, wRISP: 29, vsLefty: 30, poise: 30, heater: 31, agile: 36,
      abilities: ["Strong Starter", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Gavin", lastName: "DeVooght", position: "P", eligibility: "JR", homeState: "MI", hometown: "Brighton", jerseyNumber: 33,
      hitForAvg: 13, power: 10, speed: 33, arm: 29, fielding: 18, errorResistance: 40, velocity: 29, control: 28, stamina: 28, stuff: 29,
      clutch: 53, vsLHP: 52, grit: 54, stealing: 10, running: 30, throwing: 58, recovery: 25, wRISP: 25, vsLefty: 26, poise: 26, heater: 29, agile: 36,
      abilities: ["Sharpness", "Gyroball"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 6, 1, 0, 0, 0]) },
    { firstName: "Max", lastName: "Debiec", position: "P", eligibility: "SR", homeState: "MI", hometown: "Shelby Township", jerseyNumber: 38,
      hitForAvg: 15, power: 12, speed: 30, arm: 31, fielding: 20, errorResistance: 42, velocity: 33, control: 30, stamina: 31, stuff: 31,
      clutch: 56, vsLHP: 53, grit: 58, stealing: 9, running: 26, throwing: 60, recovery: 27, wRISP: 27, vsLefty: 28, poise: 29, heater: 31, agile: 35,
      abilities: ["Strong Starter", "Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Brandon", lastName: "Mann", position: "P", eligibility: "SR", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 22,
      hitForAvg: 15, power: 12, speed: 31, arm: 29, fielding: 20, errorResistance: 41, velocity: 29, control: 29, stamina: 27, stuff: 29,
      clutch: 56, vsLHP: 53, grit: 57, stealing: 8, running: 28, throwing: 57, recovery: 27, wRISP: 27, vsLefty: 27, poise: 27, heater: 29, agile: 35,
      abilities: ["Fireman", "Natural Shuuto", "Constant Speed"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 0, 5, 0, 0]) },
    { firstName: "Wyatt", lastName: "Novara", position: "P", eligibility: "JR", homeState: "MI", hometown: "Traverse City", jerseyNumber: 40,
      hitForAvg: 11, power: 8, speed: 26, arm: 33, fielding: 21, errorResistance: 33, velocity: 32, control: 33, stamina: 31, stuff: 33,
      clutch: 44, vsLHP: 41, grit: 45, stealing: 7, running: 23, throwing: 46, recovery: 28, wRISP: 28, vsLefty: 30, poise: 31, heater: 33, agile: 29,
      abilities: ["Miracle Sharpness"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Cade", lastName: "Montgomery", position: "P", eligibility: "JR", homeState: "MI", hometown: "Portage", jerseyNumber: 42,
      hitForAvg: 9, power: 7, speed: 23, arm: 27, fielding: 18, errorResistance: 27, velocity: 28, control: 26, stamina: 26, stuff: 27,
      clutch: 36, vsLHP: 33, grit: 37, stealing: 7, running: 21, throwing: 39, recovery: 23, wRISP: 23, vsLefty: 24, poise: 25, heater: 27, agile: 26,
      abilities: ["Tunneling"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "David", lastName: "Lally Jr", position: "P", eligibility: "SR", homeState: "MI", hometown: "Novi", jerseyNumber: 44,
      hitForAvg: 11, power: 8, speed: 26, arm: 34, fielding: 23, errorResistance: 35, velocity: 34, control: 35, stamina: 34, stuff: 34,
      clutch: 46, vsLHP: 43, grit: 47, stealing: 7, running: 22, throwing: 47, recovery: 30, wRISP: 30, vsLefty: 32, poise: 32, heater: 34, agile: 30,
      abilities: ["Guts"], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Bischoff", position: "P", eligibility: "FR", homeState: "MI", hometown: "Rochester Hills", jerseyNumber: 48,
      hitForAvg: 9, power: 8, speed: 31, arm: 29, fielding: 17, errorResistance: 30, velocity: 30, control: 23, stamina: 22, stuff: 29,
      clutch: 31, vsLHP: 30, grit: 33, stealing: 11, running: 28, throwing: 46, recovery: 19, wRISP: 19, vsLefty: 21, poise: 19, heater: 29, agile: 34,
      abilities: ["Big Boy Speed", "Winner's Luck"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    { firstName: "Ethan", lastName: "VanBuskirk", position: "P", eligibility: "FR", homeState: "MI", hometown: "Holland", jerseyNumber: 50,
      hitForAvg: 10, power: 8, speed: 33, arm: 32, fielding: 19, errorResistance: 31, velocity: 34, control: 25, stamina: 24, stuff: 30,
      clutch: 33, vsLHP: 31, grit: 34, stealing: 10, running: 29, throwing: 47, recovery: 21, wRISP: 20, vsLefty: 22, poise: 21, heater: 32, agile: 36,
      abilities: ["Fighting Spirit", "Release", "Constant Speed"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Noah", lastName: "Miller", position: "C", eligibility: "SO", homeState: "MI", hometown: "Clarkston", jerseyNumber: 14,
      hitForAvg: 54, power: 46, speed: 33, arm: 59, fielding: 57, errorResistance: 55, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 55, stealing: 15, running: 31, throwing: 60, recovery: 46, wRISP: 52, vsLefty: 49, poise: 54, heater: 0, agile: 36,
      abilities: ["Defensive Artisan", "Contact Hitter"], potential: "A-", catcherAbility: 57,
      ...noPitches },
    { firstName: "Luke", lastName: "Sefcik", position: "C", eligibility: "JR", homeState: "MI", hometown: "Macomb", jerseyNumber: 19,
      hitForAvg: 35, power: 31, speed: 25, arm: 45, fielding: 42, errorResistance: 39, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 37, vsLHP: 34, grit: 39, stealing: 10, running: 24, throwing: 47, recovery: 32, wRISP: 35, vsLefty: 32, poise: 35, heater: 0, agile: 29,
      abilities: ["vs. Breaking Pitches", "Express Baserunning"], potential: "B", catcherAbility: 42,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Joe", lastName: "Longo", position: "1B", eligibility: "SR", homeState: "NJ", hometown: "Westfield", jerseyNumber: 8,
      hitForAvg: 55, power: 54, speed: 35, arm: 49, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 55, vsLHP: 52, grit: 57, stealing: 13, running: 33, throwing: 50, recovery: 46, wRISP: 54, vsLefty: 50, poise: 55, heater: 0, agile: 36,
      abilities: ["Power Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Brayden", lastName: "Jefferis", position: "2B", eligibility: "SO", homeState: "MI", hometown: "Canton", jerseyNumber: 3,
      hitForAvg: 50, power: 38, speed: 48, arm: 51, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 45, grit: 50, stealing: 32, running: 47, throwing: 52, recovery: 42, wRISP: 47, vsLefty: 43, poise: 48, heater: 0, agile: 50,
      abilities: ["Chance Maker"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Colby", lastName: "Turner", position: "3B", eligibility: "JR", homeState: "MI", hometown: "Saline", jerseyNumber: 5,
      hitForAvg: 55, power: 49, speed: 43, arm: 56, fielding: 55, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 55, vsLHP: 51, grit: 56, stealing: 24, running: 41, throwing: 58, recovery: 45, wRISP: 53, vsLefty: 49, poise: 55, heater: 0, agile: 45,
      abilities: ["Contact Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Drew", lastName: "Culbertson", position: "SS", eligibility: "JR", homeState: "OH", hometown: "Dublin", jerseyNumber: 2,
      hitForAvg: 47, power: 38, speed: 49, arm: 54, fielding: 53, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 46, vsLHP: 42, grit: 47, stealing: 35, running: 47, throwing: 56, recovery: 39, wRISP: 43, vsLefty: 41, poise: 46, heater: 0, agile: 50,
      abilities: ["Defensive Artisan", "Express Baserunning"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Carson", lastName: "Luna", position: "SS", eligibility: "FR", homeState: "AZ", hometown: "Scottsdale", jerseyNumber: 24,
      hitForAvg: 41, power: 33, speed: 51, arm: 50, fielding: 46, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 33, running: 50, throwing: 51, recovery: 35, wRISP: 36, vsLefty: 35, poise: 38, heater: 0, agile: 53,
      abilities: ["Tough Out", "Spray Hitter", "Pull Hit"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Dane", lastName: "Morrow", position: "2B", eligibility: "FR", homeState: "MI", hometown: "East Lansing", jerseyNumber: 16,
      hitForAvg: 33, power: 25, speed: 40, arm: 40, fielding: 38, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 31, grit: 33, stealing: 24, running: 39, throwing: 42, recovery: 29, wRISP: 31, vsLefty: 29, poise: 32, heater: 0, agile: 42,
      abilities: ["First Pitch Hitter", "Contact Hitter", "Emergency Strength"], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (5)
    { firstName: "Jonathan", lastName: "Kim", position: "OF", eligibility: "SR", homeState: "CA", hometown: "Irvine", jerseyNumber: 1,
      hitForAvg: 47, power: 41, speed: 43, arm: 47, fielding: 46, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 46, vsLHP: 43, grit: 47, stealing: 31, running: 41, throwing: 48, recovery: 37, wRISP: 44, vsLefty: 41, poise: 46, heater: 0, agile: 44,
      abilities: ["High-Speed Laser", "Contact Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Greg", lastName: "Pace Jr", position: "OF", eligibility: "JR", homeState: "GA", hometown: "Marietta", jerseyNumber: 7,
      hitForAvg: 48, power: 43, speed: 46, arm: 51, fielding: 48, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 46, vsLHP: 43, grit: 48, stealing: 31, running: 45, throwing: 52, recovery: 39, wRISP: 45, vsLefty: 42, poise: 46, heater: 0, agile: 48,
      abilities: ["Express Baserunning"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Brenden", lastName: "Stressler", position: "OF", eligibility: "JR", homeState: "PA", hometown: "State College", jerseyNumber: 9,
      hitForAvg: 51, power: 45, speed: 49, arm: 55, fielding: 52, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 45, grit: 51, stealing: 32, running: 48, throwing: 57, recovery: 42, wRISP: 48, vsLefty: 44, poise: 49, heater: 0, agile: 51,
      abilities: ["Bunt Artisan", "Flying Start", "Contact Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Evan", lastName: "Haeger", position: "OF", eligibility: "SO", homeState: "MI", hometown: "Kalamazoo", jerseyNumber: 11,
      hitForAvg: 50, power: 44, speed: 56, arm: 58, fielding: 53, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 45, grit: 50, stealing: 38, running: 54, throwing: 60, recovery: 41, wRISP: 46, vsLefty: 44, poise: 49, heater: 0, agile: 58,
      abilities: ["Power Hitter", "Shock Commander", "Contact Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jack", lastName: "Summers", position: "OF", eligibility: "FR", homeState: "MI", hometown: "Grosse Pointe", jerseyNumber: 26,
      hitForAvg: 27, power: 23, speed: 38, arm: 37, fielding: 31, errorResistance: 29, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 26, vsLHP: 25, grit: 27, stealing: 23, running: 37, throwing: 38, recovery: 25, wRISP: 25, vsLefty: 23, poise: 26, heater: 0, agile: 40,
      abilities: ["Final Hit", "Unpredictable"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Marcus", lastName: "Chen", position: "DH", eligibility: "JR", homeState: "MI", hometown: "Ann Arbor", jerseyNumber: 20,
      hitForAvg: 44, power: 41, speed: 29, arm: 37, fielding: 31, errorResistance: 29, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 41, grit: 45, stealing: 10, running: 28, throwing: 38, recovery: 35, wRISP: 43, vsLefty: 40, poise: 43, heater: 0, agile: 31,
      abilities: ["Emergency Strength"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "Walsh", position: "OF", eligibility: "SO", homeState: "MI", hometown: "Birmingham", jerseyNumber: 28,
      hitForAvg: 32, power: 27, speed: 43, arm: 42, fielding: 36, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 30, vsLHP: 28, grit: 32, stealing: 27, running: 42, throwing: 43, recovery: 28, wRISP: 28, vsLefty: 27, poise: 30, heater: 0, agile: 45,
      abilities: ["Unrelenting", "Multi-Hit"], potential: "A-", catcherAbility: null,
      ...noPitches },
  ],

  "Michigan State": [
    // PITCHERS (10)
    { firstName: "Nick", lastName: "Powers", position: "P", eligibility: "JR", homeState: "MI", hometown: "Grand Rapids", jerseyNumber: 34,
      hitForAvg: 21, power: 16, speed: 47, arm: 56, fielding: 36, errorResistance: 59, velocity: 58, control: 54, stamina: 56, stuff: 56,
      clutch: 79, vsLHP: 75, grit: 82, stealing: 14, running: 42, throwing: 84, recovery: 49, wRISP: 49, vsLefty: 51, poise: 53, heater: 56, agile: 52,
      abilities: ["Star of Victory", "Strong Starter", "Gyroball", "Intimidator"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Derek", lastName: "Kontul", position: "P", eligibility: "SR", homeState: "MI", hometown: "Midland", jerseyNumber: 29,
      hitForAvg: 14, power: 12, speed: 30, arm: 28, fielding: 18, errorResistance: 40, velocity: 28, control: 28, stamina: 28, stuff: 28,
      clutch: 55, vsLHP: 52, grit: 56, stealing: 8, running: 28, throwing: 56, recovery: 26, wRISP: 26, vsLefty: 26, poise: 26, heater: 28, agile: 36,
      abilities: ["Guts", "Strikeout"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Szczepanski", position: "P", eligibility: "JR", homeState: "MI", hometown: "Dearborn", jerseyNumber: 33,
      hitForAvg: 14, power: 11, speed: 37, arm: 33, fielding: 22, errorResistance: 44, velocity: 33, control: 33, stamina: 33, stuff: 33,
      clutch: 56, vsLHP: 55, grit: 58, stealing: 11, running: 33, throwing: 63, recovery: 29, wRISP: 29, vsLefty: 30, poise: 30, heater: 33, agile: 40,
      abilities: ["Strong Finisher", "Kageura", "Quick Hands", "Intimidator"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Wyatt", lastName: "Rush", position: "P", eligibility: "FR", homeState: "OH", hometown: "Columbus", jerseyNumber: 37,
      hitForAvg: 11, power: 8, speed: 33, arm: 36, fielding: 22, errorResistance: 33, velocity: 37, control: 29, stamina: 28, stuff: 35,
      clutch: 37, vsLHP: 36, grit: 39, stealing: 11, running: 30, throwing: 52, recovery: 24, wRISP: 24, vsLefty: 26, poise: 25, heater: 36, agile: 37,
      abilities: ["Monster Stuff", "Release"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 5, 3, 1, 0, 0, 0]) },
    { firstName: "Jacob", lastName: "Kelley", position: "P", eligibility: "FR", homeState: "MI", hometown: "Lansing", jerseyNumber: 38,
      hitForAvg: 9, power: 7, speed: 29, arm: 31, fielding: 18, errorResistance: 29, velocity: 32, control: 25, stamina: 24, stuff: 30,
      clutch: 32, vsLHP: 31, grit: 34, stealing: 9, running: 27, throwing: 47, recovery: 20, wRISP: 20, vsLefty: 22, poise: 20, heater: 31, agile: 32,
      abilities: ["Constant Speed"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    { firstName: "Marcus", lastName: "Webb", position: "P", eligibility: "JR", homeState: "IN", hometown: "Fort Wayne", jerseyNumber: 22,
      hitForAvg: 15, power: 11, speed: 36, arm: 33, fielding: 22, errorResistance: 44, velocity: 34, control: 32, stamina: 32, stuff: 33,
      clutch: 56, vsLHP: 54, grit: 58, stealing: 10, running: 33, throwing: 62, recovery: 28, wRISP: 28, vsLefty: 29, poise: 30, heater: 33, agile: 40,
      abilities: ["Fireman", "Quick Hands", "Wild Fastball", "Escape Pitch"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Vlasak", position: "P", eligibility: "SO", homeState: "MI", hometown: "Portage", jerseyNumber: 40,
      hitForAvg: 10, power: 7, speed: 28, arm: 30, fielding: 20, errorResistance: 30, velocity: 31, control: 28, stamina: 28, stuff: 30,
      clutch: 38, vsLHP: 36, grit: 41, stealing: 8, running: 25, throwing: 44, recovery: 25, wRISP: 24, vsLefty: 26, poise: 26, heater: 30, agile: 30,
      abilities: ["Wizard Mode", "Intimidator"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Andrew", lastName: "Miller", position: "P", eligibility: "FR", homeState: "MI", hometown: "Troy", jerseyNumber: 42,
      hitForAvg: 11, power: 8, speed: 37, arm: 22, fielding: 14, errorResistance: 34, velocity: 23, control: 19, stamina: 17, stuff: 22,
      clutch: 37, vsLHP: 34, grit: 38, stealing: 12, running: 33, throwing: 52, recovery: 15, wRISP: 14, vsLefty: 16, poise: 15, heater: 22, agile: 40,
      abilities: ["Halting Quickness", "Guts"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Kelmer", position: "P", eligibility: "FR", homeState: "MI", hometown: "Kalamazoo", jerseyNumber: 44,
      hitForAvg: 10, power: 9, speed: 36, arm: 37, fielding: 22, errorResistance: 35, velocity: 39, control: 30, stamina: 29, stuff: 36,
      clutch: 36, vsLHP: 35, grit: 39, stealing: 10, running: 32, throwing: 53, recovery: 25, wRISP: 24, vsLefty: 27, poise: 25, heater: 37, agile: 40,
      abilities: ["Delayed Arm"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 1, 0, 0, 0]) },
    { firstName: "Kyle", lastName: "Tishinski", position: "P", eligibility: "SO", homeState: "MI", hometown: "Macomb", jerseyNumber: 46,
      hitForAvg: 11, power: 8, speed: 29, arm: 34, fielding: 22, errorResistance: 33, velocity: 36, control: 33, stamina: 33, stuff: 34,
      clutch: 43, vsLHP: 41, grit: 44, stealing: 8, running: 26, throwing: 48, recovery: 30, wRISP: 28, vsLefty: 30, poise: 30, heater: 34, agile: 32,
      abilities: ["Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Dylan", lastName: "Campbell", position: "C", eligibility: "JR", homeState: "MI", hometown: "Rochester Hills", jerseyNumber: 14,
      hitForAvg: 58, power: 50, speed: 37, arm: 68, fielding: 65, errorResistance: 61, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 55, grit: 61, stealing: 15, running: 36, throwing: 69, recovery: 51, wRISP: 58, vsLefty: 54, poise: 60, heater: 0, agile: 42,
      abilities: ["Defensive Artisan"], potential: "B", catcherAbility: 65,
      ...noPitches },
    { firstName: "Bryce", lastName: "Kelley", position: "C", eligibility: "SO", homeState: "MI", hometown: "Traverse City", jerseyNumber: 18,
      hitForAvg: 30, power: 26, speed: 22, arm: 39, fielding: 36, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 31, vsLHP: 29, grit: 32, stealing: 9, running: 21, throwing: 40, recovery: 27, wRISP: 30, vsLefty: 27, poise: 30, heater: 0, agile: 24,
      abilities: ["Push", "Artist"], potential: "B", catcherAbility: 36,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Ryan", lastName: "McKay", position: "2B", eligibility: "JR", homeState: "MI", hometown: "Ann Arbor", jerseyNumber: 2,
      hitForAvg: 71, power: 58, speed: 62, arm: 64, fielding: 71, errorResistance: 69, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 69, vsLHP: 66, grit: 71, stealing: 47, running: 59, throwing: 66, recovery: 56, wRISP: 67, vsLefty: 64, poise: 69, heater: 0, agile: 66,
      abilities: ["Contact Hitter", "Defensive Artisan", "Chance Maker"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Brendan", lastName: "Walsh", position: "1B", eligibility: "JR", homeState: "IL", hometown: "Naperville", jerseyNumber: 8,
      hitForAvg: 51, power: 50, speed: 34, arm: 48, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 51, vsLHP: 48, grit: 53, stealing: 12, running: 32, throwing: 50, recovery: 43, wRISP: 50, vsLefty: 46, poise: 51, heater: 0, agile: 36,
      abilities: ["Power Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Josh", lastName: "Terracina", position: "3B", eligibility: "SR", homeState: "MI", hometown: "Sterling Heights", jerseyNumber: 5,
      hitForAvg: 50, power: 45, speed: 40, arm: 53, fielding: 51, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 47, grit: 51, stealing: 21, running: 38, throwing: 54, recovery: 41, wRISP: 48, vsLefty: 45, poise: 50, heater: 0, agile: 41,
      abilities: ["Shock Commander", "Storming Home"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Aiden", lastName: "Marsh", position: "SS", eligibility: "JR", homeState: "OH", hometown: "Dublin", jerseyNumber: 6,
      hitForAvg: 53, power: 42, speed: 57, arm: 61, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 48, grit: 53, stealing: 38, running: 54, throwing: 63, recovery: 44, wRISP: 49, vsLefty: 46, poise: 50, heater: 0, agile: 58,
      abilities: ["Express Baserunning"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Cole", lastName: "Van Ameyde", position: "SS", eligibility: "FR", homeState: "MI", hometown: "Grand Haven", jerseyNumber: 24,
      hitForAvg: 28, power: 21, speed: 36, arm: 35, fielding: 33, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 26, vsLHP: 25, grit: 28, stealing: 22, running: 35, throwing: 36, recovery: 24, wRISP: 25, vsLefty: 24, poise: 26, heater: 0, agile: 37,
      abilities: ["Pull Hit"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Drew", lastName: "Orenchuk", position: "3B", eligibility: "SO", homeState: "MI", hometown: "Canton", jerseyNumber: 16,
      hitForAvg: 50, power: 46, speed: 46, arm: 59, fielding: 56, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 21, running: 44, throwing: 61, recovery: 42, wRISP: 48, vsLefty: 44, poise: 48, heater: 0, agile: 48,
      abilities: ["First Pitch King", "Contact Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (5)
    { firstName: "Jack", lastName: "Crighton", position: "OF", eligibility: "SR", homeState: "MI", hometown: "Brighton", jerseyNumber: 1,
      hitForAvg: 46, power: 42, speed: 45, arm: 48, fielding: 46, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 46, vsLHP: 44, grit: 48, stealing: 31, running: 44, throwing: 49, recovery: 38, wRISP: 45, vsLefty: 42, poise: 46, heater: 0, agile: 46,
      abilities: ["High-Speed Laser"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Brady", lastName: "Collins", position: "OF", eligibility: "JR", homeState: "MI", hometown: "Novi", jerseyNumber: 7,
      hitForAvg: 50, power: 44, speed: 52, arm: 55, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 45, grit: 50, stealing: 35, running: 50, throwing: 57, recovery: 41, wRISP: 46, vsLefty: 44, poise: 49, heater: 0, agile: 53,
      abilities: ["Multi-Hit"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Gavin", lastName: "Redmond", position: "OF", eligibility: "SO", homeState: "MI", hometown: "East Lansing", jerseyNumber: 9,
      hitForAvg: 46, power: 39, speed: 52, arm: 55, fielding: 49, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 45, vsLHP: 42, grit: 46, stealing: 35, running: 49, throwing: 57, recovery: 39, wRISP: 43, vsLefty: 39, poise: 45, heater: 0, agile: 53,
      abilities: ["Low Ball Hitter", "Storming Home"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Luke", lastName: "Ritter", position: "OF", eligibility: "JR", homeState: "IN", hometown: "Carmel", jerseyNumber: 4,
      hitForAvg: 52, power: 47, speed: 48, arm: 55, fielding: 52, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 32, running: 47, throwing: 57, recovery: 44, wRISP: 51, vsLefty: 47, poise: 52, heater: 0, agile: 51,
      abilities: ["Consigliere"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Mason", lastName: "Kraft", position: "OF", eligibility: "SR", homeState: "MI", hometown: "Okemos", jerseyNumber: 20,
      hitForAvg: 42, power: 39, speed: 27, arm: 35, fielding: 30, errorResistance: 29, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 43, vsLHP: 40, grit: 45, stealing: 9, running: 25, throwing: 37, recovery: 33, wRISP: 42, vsLefty: 39, poise: 42, heater: 0, agile: 29,
      abilities: ["Consigliere"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Tyler", lastName: "Bowen", position: "OF", eligibility: "SO", homeState: "MI", hometown: "Shelby Township", jerseyNumber: 28,
      hitForAvg: 37, power: 33, speed: 44, arm: 45, fielding: 41, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 36, vsLHP: 33, grit: 37, stealing: 27, running: 42, throwing: 46, recovery: 32, wRISP: 34, vsLefty: 32, poise: 36, heater: 0, agile: 45,
      abilities: ["Chance Maker"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Nolan", lastName: "Fischer", position: "2B", eligibility: "JR", homeState: "MI", hometown: "Holland", jerseyNumber: 15,
      hitForAvg: 47, power: 43, speed: 32, arm: 41, fielding: 35, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 43, grit: 48, stealing: 12, running: 30, throwing: 43, recovery: 39, wRISP: 44, vsLefty: 41, poise: 44, heater: 0, agile: 34,
      abilities: ["Revenge", "Error Prone"], potential: "B", catcherAbility: null,
      ...noPitches },
  ],
};
