import type { RealPlayer } from "./realRosters";
import { pitchMix, noPitches } from "./pitchMixHelpers";

export const BIG_TEN_BATCH3_ROSTERS: Record<string, RealPlayer[]> = {
  "Purdue": [
    // PITCHERS (10)
    { firstName: "Cole", lastName: "Van Assen", position: "P", eligibility: "JR", homeState: "IN", hometown: "Crown Point", jerseyNumber: 19,
      hitForAvg: 24, power: 20, speed: 42, arm: 87, fielding: 51, errorResistance: 65, velocity: 87, control: 77, stamina: 86, stuff: 86,
      clutch: 92, vsLHP: 87, grit: 99, stealing: 13, running: 48, throwing: 97, recovery: 73, wRISP: 73, vsLefty: 74, poise: 77, heater: 90, agile: 57,
      abilities: ["Star of Victory", "Strong Starter", "Guts", "Intimidator", "Heavy Ball", "Winner's Luck", "Pace"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 7, 6, 1, 0, 0, 0]) },
    { firstName: "Zach", lastName: "Erdman", position: "P", eligibility: "JR", homeState: "TX", hometown: "Lubbock", jerseyNumber: 34,
      hitForAvg: 19, power: 15, speed: 42, arm: 64, fielding: 41, errorResistance: 57, velocity: 73, control: 61, stamina: 64, stuff: 61,
      clutch: 77, vsLHP: 73, grit: 80, stealing: 12, running: 41, throwing: 81, recovery: 58, wRISP: 58, vsLefty: 59, poise: 61, heater: 67, agile: 48,
      abilities: ["Strong Starter", "Explosive Fastball"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Jarvis", lastName: "Evans", position: "P", eligibility: "JR", homeState: "SC", hometown: "Columbia", jerseyNumber: 27,
      hitForAvg: 13, power: 10, speed: 28, arm: 42, fielding: 27, errorResistance: 37, velocity: 46, control: 40, stamina: 42, stuff: 40,
      clutch: 50, vsLHP: 47, grit: 51, stealing: 8, running: 27, throwing: 52, recovery: 37, wRISP: 37, vsLefty: 38, poise: 40, heater: 44, agile: 32,
      abilities: ["Strong Starter", "Guts", "True Slider"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 6, 1, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Kramer", position: "P", eligibility: "SR", homeState: "IN", hometown: "Fishers", jerseyNumber: 41,
      hitForAvg: 12, power: 10, speed: 27, arm: 39, fielding: 25, errorResistance: 37, velocity: 46, control: 39, stamina: 34, stuff: 39,
      clutch: 54, vsLHP: 49, grit: 54, stealing: 7, running: 23, throwing: 52, recovery: 38, wRISP: 39, vsLefty: 38, poise: 41, heater: 44, agile: 28,
      abilities: ["Fireman", "Explosive Fastball", "Guts"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 7, 0, 1, 0, 0, 0]) },
    { firstName: "Barron", lastName: "Sawyer", position: "P", eligibility: "SR", homeState: "IN", hometown: "Westfield", jerseyNumber: 45,
      hitForAvg: 17, power: 16, speed: 40, arm: 64, fielding: 41, errorResistance: 56, velocity: 72, control: 59, stamina: 61, stuff: 61,
      clutch: 73, vsLHP: 69, grit: 76, stealing: 12, running: 36, throwing: 79, recovery: 56, wRISP: 56, vsLefty: 56, poise: 58, heater: 69, agile: 44,
      abilities: ["Explosive Fastball", "Wild Fastball", "vs. Strong Batters", "Inside Pitch"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Westin", lastName: "Boyle", position: "P", eligibility: "JR", homeState: "IN", hometown: "Carmel", jerseyNumber: 38,
      hitForAvg: 7, power: 6, speed: 26, arm: 21, fielding: 15, errorResistance: 24, velocity: 37, control: 20, stamina: 21, stuff: 26,
      clutch: 31, vsLHP: 29, grit: 31, stealing: 6, running: 17, throwing: 35, recovery: 19, wRISP: 18, vsLefty: 19, poise: 19, heater: 23, agile: 21,
      abilities: ["Full Throttle", "Strikeout"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "O'Connell", position: "P", eligibility: "SO", homeState: "IL", hometown: "Naperville", jerseyNumber: 46,
      hitForAvg: 9, power: 7, speed: 27, arm: 30, fielding: 19, errorResistance: 27, velocity: 32, control: 27, stamina: 34, stuff: 27,
      clutch: 33, vsLHP: 32, grit: 35, stealing: 7, running: 22, throwing: 40, recovery: 23, wRISP: 23, vsLefty: 26, poise: 26, heater: 31, agile: 26,
      abilities: ["Hot Head"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Logan", lastName: "Beaman", position: "P", eligibility: "JR", homeState: "IN", hometown: "Lafayette", jerseyNumber: 32,
      hitForAvg: 9, power: 6, speed: 26, arm: 36, fielding: 23, errorResistance: 24, velocity: 40, control: 34, stamina: 34, stuff: 33,
      clutch: 31, vsLHP: 30, grit: 31, stealing: 6, running: 16, throwing: 34, recovery: 31, wRISP: 30, vsLefty: 31, poise: 31, heater: 37, agile: 21,
      abilities: ["Shuuto Spin"], potential: "B-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Josh", lastName: "Willman", position: "P", eligibility: "SO", homeState: "IN", hometown: "Brownsburg", jerseyNumber: 48,
      hitForAvg: 10, power: 7, speed: 28, arm: 31, fielding: 21, errorResistance: 30, velocity: 40, control: 28, stamina: 28, stuff: 28,
      clutch: 35, vsLHP: 34, grit: 37, stealing: 9, running: 25, throwing: 43, recovery: 24, wRISP: 24, vsLefty: 26, poise: 24, heater: 33, agile: 30,
      abilities: ["Flyball Pitcher"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    { firstName: "Kade", lastName: "Hoover", position: "P", eligibility: "FR", homeState: "OH", hometown: "Columbus", jerseyNumber: 50,
      hitForAvg: 9, power: 8, speed: 27, arm: 30, fielding: 18, errorResistance: 29, velocity: 41, control: 28, stamina: 28, stuff: 27,
      clutch: 33, vsLHP: 32, grit: 34, stealing: 8, running: 24, throwing: 42, recovery: 21, wRISP: 20, vsLefty: 24, poise: 21, heater: 32, agile: 29,
      abilities: ["Halting Quickness", "Gyroball"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 3, 4, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Jackson", lastName: "Bessette", position: "C", eligibility: "JR", homeState: "IL", hometown: "Chicago", jerseyNumber: 12,
      hitForAvg: 50, power: 45, speed: 32, arm: 50, fielding: 48, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 46, vsLHP: 42, grit: 46, stealing: 11, running: 24, throwing: 52, recovery: 38, wRISP: 44, vsLefty: 41, poise: 46, heater: 0, agile: 30,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: 46,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Nolan", lastName: "Wilkerson", position: "C", eligibility: "SO", homeState: "IN", hometown: "Muncie", jerseyNumber: 15,
      hitForAvg: 32, power: 29, speed: 27, arm: 33, fielding: 31, errorResistance: 29, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 27, vsLHP: 26, grit: 29, stealing: 8, running: 18, throwing: 35, recovery: 25, wRISP: 26, vsLefty: 25, poise: 26, heater: 0, agile: 20,
      abilities: ["Chance Maker", "Late Night Hero"], potential: "B", catcherAbility: 31,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Dylan", lastName: "Drake", position: "SS", eligibility: "JR", homeState: "IN", hometown: "Indianapolis", jerseyNumber: 2,
      hitForAvg: 57, power: 47, speed: 69, arm: 54, fielding: 55, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 45, grit: 49, stealing: 36, running: 47, throwing: 55, recovery: 40, wRISP: 47, vsLefty: 43, poise: 49, heater: 0, agile: 53,
      abilities: ["Defensive Artisan", "Express Baserunning"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Eli", lastName: "Anderson", position: "2B", eligibility: "JR", homeState: "IN", hometown: "Zionsville", jerseyNumber: 6,
      hitForAvg: 76, power: 62, speed: 87, arm: 72, fielding: 75, errorResistance: 73, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 67, vsLHP: 62, grit: 68, stealing: 43, running: 62, throwing: 73, recovery: 59, wRISP: 66, vsLefty: 61, poise: 67, heater: 0, agile: 68,
      abilities: ["Chance Maker"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Sam", lastName: "Flores", position: "3B", eligibility: "SO", homeState: "CA", hometown: "San Diego", jerseyNumber: 8,
      hitForAvg: 52, power: 46, speed: 50, arm: 52, fielding: 50, errorResistance: 49, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 45, vsLHP: 42, grit: 46, stealing: 17, running: 36, throwing: 54, recovery: 38, wRISP: 43, vsLefty: 39, poise: 45, heater: 0, agile: 39,
      abilities: ["Good Mood", "vs. Fastballs"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Ross", lastName: "Highfill", position: "1B", eligibility: "JR", homeState: "IN", hometown: "Greenwood", jerseyNumber: 24,
      hitForAvg: 62, power: 61, speed: 51, arm: 52, fielding: 55, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 55, vsLHP: 50, grit: 56, stealing: 11, running: 33, throwing: 55, recovery: 44, wRISP: 52, vsLefty: 49, poise: 55, heater: 0, agile: 38,
      abilities: ["Contact Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Tyler", lastName: "Reeves", position: "SS", eligibility: "FR", homeState: "IN", hometown: "Noblesville", jerseyNumber: 3,
      hitForAvg: 31, power: 23, speed: 51, arm: 31, fielding: 27, errorResistance: 25, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 22, vsLHP: 20, grit: 23, stealing: 19, running: 30, throwing: 32, recovery: 20, wRISP: 21, vsLefty: 19, poise: 21, heater: 0, agile: 32,
      abilities: ["Outside Hitter", "Final Hit", "Home Defense"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Maddux", lastName: "Houghton", position: "1B", eligibility: "FR", homeState: "IN", hometown: "Avon", jerseyNumber: 28,
      hitForAvg: 36, power: 36, speed: 50, arm: 36, fielding: 34, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 29, vsLHP: 26, grit: 30, stealing: 10, running: 24, throwing: 38, recovery: 26, wRISP: 27, vsLefty: 24, poise: 27, heater: 0, agile: 27,
      abilities: ["Storming Home", "Ace Killer"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "S",
      ...noPitches },
    { firstName: "Ryan", lastName: "Walstad", position: "2B", eligibility: "FR", homeState: "MN", hometown: "Edina", jerseyNumber: 14,
      hitForAvg: 37, power: 27, speed: 61, arm: 37, fielding: 30, errorResistance: 28, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 24, vsLHP: 23, grit: 25, stealing: 21, running: 33, throwing: 34, recovery: 23, wRISP: 23, vsLefty: 21, poise: 24, heater: 0, agile: 35,
      abilities: ["High Ball Hitter", "Defensive Artisan"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Aaron", lastName: "Manias", position: "OF", eligibility: "SR", homeState: "TX", hometown: "Big Spring", jerseyNumber: 7,
      hitForAvg: 94, power: 90, speed: 84, arm: 73, fielding: 69, errorResistance: 68, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 84, vsLHP: 80, grit: 85, stealing: 35, running: 60, throwing: 77, recovery: 65, wRISP: 84, vsLefty: 77, poise: 81, heater: 0, agile: 65,
      abilities: ["Power Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "CJ", lastName: "Richmond", position: "OF", eligibility: "JR", homeState: "IN", hometown: "Terre Haute", jerseyNumber: 22,
      hitForAvg: 44, power: 39, speed: 51, arm: 41, fielding: 39, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 35, grit: 39, stealing: 27, running: 39, throwing: 42, recovery: 31, wRISP: 36, vsLefty: 34, poise: 38, heater: 0, agile: 41,
      abilities: ["Express Baserunning"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Camden", lastName: "Gasser", position: "OF", eligibility: "SO", homeState: "IN", hometown: "Brownsburg", jerseyNumber: 9,
      hitForAvg: 48, power: 42, speed: 56, arm: 47, fielding: 44, errorResistance: 41, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 41, vsLHP: 38, grit: 42, stealing: 29, running: 44, throwing: 48, recovery: 36, wRISP: 40, vsLefty: 37, poise: 41, heater: 0, agile: 47,
      abilities: ["High-Speed Laser", "Contact Hitter", "Push"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Jake", lastName: "Jarvis", position: "OF", eligibility: "JR", homeState: "IN", hometown: "Evansville", jerseyNumber: 20,
      hitForAvg: 49, power: 45, speed: 55, arm: 47, fielding: 44, errorResistance: 43, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 43, vsLHP: 40, grit: 44, stealing: 31, running: 44, throwing: 48, recovery: 36, wRISP: 41, vsLefty: 38, poise: 43, heater: 0, agile: 47,
      abilities: ["Emergency Strength", "Contact Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Brennan", lastName: "Hein", position: "OF", eligibility: "FR", homeState: "IN", hometown: "Lafayette", jerseyNumber: 26,
      hitForAvg: 37, power: 34, speed: 57, arm: 41, fielding: 34, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 31, vsLHP: 29, grit: 31, stealing: 25, running: 41, throwing: 42, recovery: 29, wRISP: 29, vsLefty: 28, poise: 29, heater: 0, agile: 44,
      abilities: ["Heavy Tank", "vs. Breaking Pitches", "Bad Mood"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Brady", lastName: "Moore", position: "OF", eligibility: "SO", homeState: "IN", hometown: "Bloomington", jerseyNumber: 30,
      hitForAvg: 55, power: 46, speed: 61, arm: 53, fielding: 50, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 45, vsLHP: 44, grit: 48, stealing: 33, running: 50, throwing: 55, recovery: 39, wRISP: 45, vsLefty: 40, poise: 45, heater: 0, agile: 53,
      abilities: ["Laser Beam", "Defensive Artisan"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...noPitches },
  ],

  "Rutgers": [
    // PITCHERS (10)
    { firstName: "Joe", lastName: "Mazza", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Toms River", jerseyNumber: 17,
      hitForAvg: 24, power: 20, speed: 38, arm: 79, fielding: 50, errorResistance: 62, velocity: 80, control: 74, stamina: 78, stuff: 78,
      clutch: 86, vsLHP: 80, grit: 88, stealing: 12, running: 42, throwing: 88, recovery: 69, wRISP: 69, vsLefty: 70, poise: 71, heater: 83, agile: 52,
      abilities: ["Strong Starter", "Sharpness", "vs. Strong Batters", "Kageura", "Strong Finisher"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 6, 6, 1, 0, 0, 0]) },
    { firstName: "Zack", lastName: "Konstantinovsky", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Marlboro", jerseyNumber: 22,
      hitForAvg: 20, power: 15, speed: 42, arm: 64, fielding: 41, errorResistance: 55, velocity: 71, control: 61, stamina: 64, stuff: 61,
      clutch: 78, vsLHP: 74, grit: 79, stealing: 10, running: 38, throwing: 81, recovery: 56, wRISP: 56, vsLefty: 60, poise: 61, heater: 66, agile: 45,
      abilities: ["Strong Starter", "Guts", "Strong Finisher"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Dallin", lastName: "Harrison", position: "P", eligibility: "JR", homeState: "CA", hometown: "San Diego", jerseyNumber: 35,
      hitForAvg: 20, power: 16, speed: 40, arm: 63, fielding: 42, errorResistance: 55, velocity: 71, control: 61, stamina: 63, stuff: 60,
      clutch: 75, vsLHP: 71, grit: 77, stealing: 11, running: 40, throwing: 79, recovery: 57, wRISP: 57, vsLefty: 58, poise: 59, heater: 67, agile: 49,
      abilities: ["Guts", "Big Boy Speed"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Vincent", lastName: "Borghese", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Cherry Hill", jerseyNumber: 40,
      hitForAvg: 14, power: 9, speed: 31, arm: 43, fielding: 27, errorResistance: 41, velocity: 48, control: 42, stamina: 42, stuff: 41,
      clutch: 57, vsLHP: 52, grit: 58, stealing: 7, running: 26, throwing: 58, recovery: 39, wRISP: 40, vsLefty: 40, poise: 41, heater: 45, agile: 32,
      abilities: ["Explosive Fastball", "Guts"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Jordan", lastName: "Savinon", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Newark", jerseyNumber: 29,
      hitForAvg: 13, power: 11, speed: 33, arm: 44, fielding: 27, errorResistance: 38, velocity: 50, control: 41, stamina: 44, stuff: 40,
      clutch: 51, vsLHP: 50, grit: 53, stealing: 9, running: 29, throwing: 57, recovery: 38, wRISP: 38, vsLefty: 39, poise: 39, heater: 46, agile: 36,
      abilities: ["Fireman", "Natural Shuuto"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Marcus", lastName: "Holden", position: "P", eligibility: "SO", homeState: "NJ", hometown: "Woodbridge", jerseyNumber: 46,
      hitForAvg: 10, power: 6, speed: 25, arm: 27, fielding: 17, errorResistance: 28, velocity: 30, control: 25, stamina: 27, stuff: 25,
      clutch: 33, vsLHP: 32, grit: 34, stealing: 6, running: 22, throwing: 40, recovery: 23, wRISP: 23, vsLefty: 24, poise: 24, heater: 29, agile: 25,
      abilities: ["Pace", "Tunneling"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Jake", lastName: "DeLeo", position: "P", eligibility: "SO", homeState: "NJ", hometown: "Princeton", jerseyNumber: 48,
      hitForAvg: 8, power: 7, speed: 28, arm: 23, fielding: 15, errorResistance: 26, velocity: 40, control: 23, stamina: 23, stuff: 27,
      clutch: 31, vsLHP: 29, grit: 31, stealing: 8, running: 21, throwing: 38, recovery: 19, wRISP: 19, vsLefty: 20, poise: 20, heater: 24, agile: 26,
      abilities: ["Strikeout", "Delayed Arm"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    { firstName: "Cole", lastName: "Stetzar", position: "P", eligibility: "SO", homeState: "NJ", hometown: "Haddonfield", jerseyNumber: 33,
      hitForAvg: 8, power: 6, speed: 23, arm: 22, fielding: 14, errorResistance: 23, velocity: 35, control: 22, stamina: 22, stuff: 23,
      clutch: 29, vsLHP: 28, grit: 30, stealing: 4, running: 18, throwing: 34, recovery: 18, wRISP: 18, vsLefty: 20, poise: 19, heater: 23, agile: 22,
      abilities: ["Miracle Sharpness"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    { firstName: "Matt", lastName: "Reardon", position: "P", eligibility: "JR", homeState: "NJ", hometown: "Edison", jerseyNumber: 36,
      hitForAvg: 11, power: 8, speed: 25, arm: 27, fielding: 17, errorResistance: 27, velocity: 27, control: 33, stamina: 26, stuff: 25,
      clutch: 35, vsLHP: 33, grit: 36, stealing: 6, running: 18, throwing: 38, recovery: 24, wRISP: 23, vsLefty: 25, poise: 25, heater: 27, agile: 23,
      abilities: ["Wild Fastball"], potential: "B-", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Hogan", position: "P", eligibility: "FR", homeState: "PA", hometown: "Allentown", jerseyNumber: 50,
      hitForAvg: 9, power: 8, speed: 28, arm: 29, fielding: 18, errorResistance: 29, velocity: 27, control: 28, stamina: 28, stuff: 27,
      clutch: 32, vsLHP: 31, grit: 33, stealing: 8, running: 24, throwing: 41, recovery: 22, wRISP: 21, vsLefty: 23, poise: 22, heater: 29, agile: 29,
      abilities: ["Escape Pitch", "Halting Quickness"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 3, 4, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Matt", lastName: "Chatelle", position: "C", eligibility: "SR", homeState: "NJ", hometown: "Bridgewater", jerseyNumber: 12,
      hitForAvg: 51, power: 44, speed: 33, arm: 48, fielding: 48, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 45, vsLHP: 42, grit: 48, stealing: 10, running: 24, throwing: 49, recovery: 39, wRISP: 44, vsLefty: 41, poise: 46, heater: 0, agile: 28,
      abilities: ["Defensive Artisan", "Tough Out"], potential: "B+", catcherAbility: 45,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Trey", lastName: "Wells", position: "C", eligibility: "SR", homeState: "NJ", hometown: "Middletown", jerseyNumber: 18,
      hitForAvg: 47, power: 43, speed: 38, arm: 46, fielding: 44, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 41, vsLHP: 39, grit: 42, stealing: 10, running: 25, throwing: 47, recovery: 37, wRISP: 40, vsLefty: 38, poise: 41, heater: 0, agile: 27,
      abilities: ["Bad Mood"], potential: "B", catcherAbility: 43,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Yomar", lastName: "Carreras", position: "SS", eligibility: "SO", homeState: "FL", hometown: "Miami", jerseyNumber: 2,
      hitForAvg: 69, power: 55, speed: 78, arm: 65, fielding: 65, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 61, stealing: 46, running: 60, throwing: 67, recovery: 49, wRISP: 58, vsLefty: 55, poise: 60, heater: 0, agile: 64,
      abilities: ["Defensive Artisan", "Express Baserunning"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Charlie", lastName: "Meglio", position: "3B", eligibility: "JR", homeState: "NC", hometown: "Buies Creek", jerseyNumber: 8,
      hitForAvg: 55, power: 58, speed: 48, arm: 48, fielding: 45, errorResistance: 43, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 51, vsLHP: 48, grit: 51, stealing: 12, running: 31, throwing: 50, recovery: 39, wRISP: 51, vsLefty: 47, poise: 50, heater: 0, agile: 34,
      abilities: ["Power Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...noPitches },
    { firstName: "Ryan", lastName: "Jaros", position: "1B", eligibility: "JR", homeState: "NJ", hometown: "Westfield", jerseyNumber: 24,
      hitForAvg: 54, power: 52, speed: 51, arm: 46, fielding: 48, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 46, vsLHP: 42, grit: 48, stealing: 12, running: 29, throwing: 48, recovery: 39, wRISP: 45, vsLefty: 41, poise: 46, heater: 0, agile: 33,
      abilities: ["Contact Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Quinten", lastName: "Perilli", position: "2B", eligibility: "JR", homeState: "NJ", hometown: "Summit", jerseyNumber: 6,
      hitForAvg: 51, power: 40, speed: 64, arm: 47, fielding: 48, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 40, grit: 45, stealing: 26, running: 40, throwing: 47, recovery: 36, wRISP: 41, vsLefty: 37, poise: 42, heater: 0, agile: 45,
      abilities: ["Chance Maker"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Tristan", lastName: "Salinas", position: "SS", eligibility: "JR", homeState: "CA", hometown: "Anaheim", jerseyNumber: 5,
      hitForAvg: 38, power: 30, speed: 50, arm: 38, fielding: 37, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 29, grit: 32, stealing: 23, running: 32, throwing: 39, recovery: 27, wRISP: 31, vsLefty: 29, poise: 32, heater: 0, agile: 37,
      abilities: ["Tough Out", "Resilient", "Chance Maker"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Anthony", lastName: "Stephan", position: "3B", eligibility: "FR", homeState: "NJ", hometown: "Morristown", jerseyNumber: 3,
      hitForAvg: 40, power: 30, speed: 56, arm: 40, fielding: 33, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 26, vsLHP: 25, grit: 28, stealing: 22, running: 34, throwing: 37, recovery: 25, wRISP: 26, vsLefty: 23, poise: 26, heater: 0, agile: 37,
      abilities: ["High Ball Hitter", "Pressure Run"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Max", lastName: "Brown", position: "1B", eligibility: "FR", homeState: "PA", hometown: "Doylestown", jerseyNumber: 28,
      hitForAvg: 34, power: 34, speed: 46, arm: 36, fielding: 33, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 28, vsLHP: 25, grit: 29, stealing: 9, running: 25, throwing: 37, recovery: 25, wRISP: 27, vsLefty: 25, poise: 27, heater: 0, agile: 27,
      abilities: ["Batter Intimidator", "Artist"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Peyton", lastName: "Bonds", position: "OF", eligibility: "JR", homeState: "NJ", hometown: "Piscataway", jerseyNumber: 7,
      hitForAvg: 54, power: 49, speed: 59, arm: 44, fielding: 46, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 44, grit: 48, stealing: 39, running: 46, throwing: 46, recovery: 39, wRISP: 46, vsLefty: 42, poise: 47, heater: 0, agile: 48,
      abilities: ["Express Baserunning", "Power Hitter", "Contact Hitter"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Chase", lastName: "Krewson", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Orlando", jerseyNumber: 10,
      hitForAvg: 57, power: 49, speed: 57, arm: 49, fielding: 47, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 45, grit: 50, stealing: 31, running: 44, throwing: 50, recovery: 39, wRISP: 47, vsLefty: 44, poise: 49, heater: 0, agile: 47,
      abilities: ["Contact Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Nick", lastName: "Cimillo", position: "OF", eligibility: "JR", homeState: "NJ", hometown: "Cranford", jerseyNumber: 9,
      hitForAvg: 52, power: 46, speed: 56, arm: 48, fielding: 45, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 41, grit: 45, stealing: 29, running: 42, throwing: 49, recovery: 37, wRISP: 42, vsLefty: 40, poise: 44, heater: 0, agile: 45,
      abilities: ["God of Pinch Hitting", "Locked and Loaded"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Evan", lastName: "Sleight", position: "OF", eligibility: "SO", homeState: "NY", hometown: "Poughkeepsie", jerseyNumber: 20,
      hitForAvg: 71, power: 61, speed: 72, arm: 70, fielding: 65, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 57, grit: 64, stealing: 42, running: 65, throwing: 71, recovery: 53, wRISP: 59, vsLefty: 54, poise: 60, heater: 0, agile: 70,
      abilities: ["Disturbance", "vs. Breaking Pitches"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Ryan", lastName: "Gale", position: "OF", eligibility: "FR", homeState: "NJ", hometown: "Hoboken", jerseyNumber: 26,
      hitForAvg: 34, power: 27, speed: 49, arm: 34, fielding: 29, errorResistance: 27, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 24, vsLHP: 23, grit: 26, stealing: 21, running: 34, throwing: 35, recovery: 23, wRISP: 23, vsLefty: 22, poise: 23, heater: 0, agile: 37,
      abilities: ["Pressure Run", "Milliner"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Liam", lastName: "Bendo", position: "OF", eligibility: "FR", homeState: "CT", hometown: "Greenwich", jerseyNumber: 30,
      hitForAvg: 33, power: 25, speed: 50, arm: 34, fielding: 29, errorResistance: 27, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 24, vsLHP: 22, grit: 25, stealing: 21, running: 34, throwing: 35, recovery: 22, wRISP: 22, vsLefty: 21, poise: 24, heater: 0, agile: 36,
      abilities: ["Disturbance", "Counterattack", "Contact Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
  ],

  "USC": [
      // 37-12/19-8 BT, D1B #18, Andy Stankiewicz Yr 4. Best start in program history (19-0). Staff #1 nation H/9 (6.86), #1 SHO (8).
      // PITCHERS (10) — 1-8 pitch scale
      // Mason Edwards — LHP JR Thursday ace, 7-0/1.74, #2 nationally per D1B Top 100 SP — TEAM ELITE STUFF
      { firstName: "Mason", lastName: "Edwards", position: "P", eligibility: "JR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 31,
        hitForAvg: 21, power: 16, speed: 42, arm: 85, fielding: 54, errorResistance: 70, velocity: 86, control: 90, stamina: 90, stuff: 93,
        clutch: 99, vsLHP: 99, grit: 99, stealing: 11, running: 41, throwing: 99, recovery: 75, wRISP: 85, vsLefty: 90, poise: 85, heater: 85, agile: 57,
        abilities: ["Star of Victory", "Inside Pitch", "Intimidator", "Heavy Ball", "Winner's Luck"], potential: "A+", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [6, 0, 0, 1, 0, 6, 0]) },
      // Grant Govel — RHP SO Friday/weekend, 9-1/2.55
      { firstName: "Grant", lastName: "Govel", position: "P", eligibility: "FR", homeState: "CA", hometown: "San Diego", jerseyNumber: 27,
        hitForAvg: 13, power: 10, speed: 31, arm: 60, fielding: 34, errorResistance: 44, velocity: 62, control: 60, stamina: 61, stuff: 57,
        clutch: 74, vsLHP: 68, grit: 74, stealing: 8, running: 30, throwing: 72, recovery: 50, wRISP: 54, vsLefty: 54, poise: 60, heater: 61, agile: 39,
        abilities: ["Strong Starter", "Inside Pitch", "Painter", "Guts", "Intimidator"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
      // Diego Velazquez — RHP Saturday starter, 5-1/3.32
      { firstName: "Diego", lastName: "Velazquez", position: "P", eligibility: "JR", homeState: "CA", hometown: "Anaheim", jerseyNumber: 19,
        hitForAvg: 14, power: 11, speed: 34, arm: 57, fielding: 35, errorResistance: 46, velocity: 61, control: 57, stamina: 57, stuff: 56,
        clutch: 67, vsLHP: 63, grit: 70, stealing: 8, running: 32, throwing: 72, recovery: 50, wRISP: 50, vsLefty: 51, poise: 55, heater: 58, agile: 42,
        abilities: ["Strong Starter", "Halting Quickness", "Intimidator"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
      // Andrew Johnson — SO RHP swing, 4-2/3.75 in 60 IP (14 apps)
      { firstName: "Andrew", lastName: "Johnson", position: "P", eligibility: "FR", homeState: "CA", hometown: "Thousand Oaks", jerseyNumber: 35,
        hitForAvg: 10, power: 8, speed: 26, arm: 43, fielding: 25, errorResistance: 35, velocity: 49, control: 40, stamina: 45, stuff: 40,
        clutch: 50, vsLHP: 49, grit: 52, stealing: 8, running: 25, throwing: 55, recovery: 38, wRISP: 36, vsLefty: 38, poise: 39, heater: 45, agile: 34,
        abilities: ["Guts", "Pace", "Winner's Luck", "True Slider"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
      // Adam Troy — closer, 11 SV (3rd nation), 32 K in 25.2 IP
      { firstName: "Adam", lastName: "Troy", position: "P", eligibility: "SR", homeState: "CA", hometown: "Long Beach", jerseyNumber: 23,
        hitForAvg: 14, power: 12, speed: 37, arm: 70, fielding: 38, errorResistance: 52, velocity: 71, control: 68, stamina: 46, stuff: 69,
        clutch: 95, vsLHP: 82, grit: 89, stealing: 10, running: 36, throwing: 87, recovery: 52, wRISP: 70, vsLefty: 68, poise: 74, heater: 71, agile: 47,
        abilities: ["Fireman", "Doctor K", "Decisive", "Strong Finisher", "Straddle"], potential: "A", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 7, 0, 1, 0, 4, 0]) },
      // Henry Chabot — SR RHP rotation depth
      { firstName: "Henry", lastName: "Chabot", position: "P", eligibility: "SR", homeState: "CA", hometown: "Orange", jerseyNumber: 41,
        hitForAvg: 12, power: 9, speed: 28, arm: 45, fielding: 28, errorResistance: 39, velocity: 48, control: 45, stamina: 42, stuff: 42,
        clutch: 54, vsLHP: 49, grit: 55, stealing: 8, running: 25, throwing: 57, recovery: 40, wRISP: 40, vsLefty: 41, poise: 42, heater: 46, agile: 31,
        abilities: ["Guts", "Crossfire"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
      // Landon Sims — JR RP
      { firstName: "Landon", lastName: "Sims", position: "P", eligibility: "JR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 38,
        hitForAvg: 9, power: 7, speed: 23, arm: 36, fielding: 21, errorResistance: 30, velocity: 40, control: 35, stamina: 27, stuff: 36,
        clutch: 44, vsLHP: 40, grit: 45, stealing: 6, running: 21, throwing: 46, recovery: 29, wRISP: 31, vsLefty: 31, poise: 33, heater: 38, agile: 27,
        abilities: ["Fireman", "Sharpness"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 7, 0, 1, 0, 0, 0]) },
      // Gavin Lauridsen — FR RHP — PG 1st Team / Top-100 national
      { firstName: "Gavin", lastName: "Lauridsen", position: "P", eligibility: "FR", homeState: "CA", hometown: "Riverside", jerseyNumber: 36,
        hitForAvg: 8, power: 5, speed: 22, arm: 31, fielding: 13, errorResistance: 22, velocity: 38, control: 27, stamina: 27, stuff: 30,
        clutch: 24, vsLHP: 23, grit: 25, stealing: 5, running: 17, throwing: 33, recovery: 16, wRISP: 16, vsLefty: 17, poise: 17, heater: 25, agile: 21,
        abilities: ["Explosive Fastball"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
      // Jake Snider — SO RHP depth
      { firstName: "Jake", lastName: "Snider", position: "P", eligibility: "FR", homeState: "CA", hometown: "Irvine", jerseyNumber: 48,
        hitForAvg: 9, power: 8, speed: 28, arm: 29, fielding: 19, errorResistance: 29, velocity: 28, control: 36, stamina: 26, stuff: 27,
        clutch: 35, vsLHP: 33, grit: 36, stealing: 8, running: 24, throwing: 42, recovery: 23, wRISP: 22, vsLefty: 24, poise: 24, heater: 29, agile: 29,
        abilities: ["Groundball Pitcher"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
      // Alex Williams — SO RHP depth
      { firstName: "Alex", lastName: "Williams", position: "P", eligibility: "FR", homeState: "CA", hometown: "Fresno", jerseyNumber: 50,
        hitForAvg: 9, power: 7, speed: 25, arm: 27, fielding: 17, errorResistance: 26, velocity: 29, control: 27, stamina: 27, stuff: 26,
        clutch: 30, vsLHP: 29, grit: 33, stealing: 7, running: 23, throwing: 38, recovery: 23, wRISP: 20, vsLefty: 23, poise: 23, heater: 29, agile: 26,
        abilities: ["Halting Quickness"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
      // CATCHERS (2)
      // Isaac Cadena — JR C, transfer (TCU/Ohio St), .304/.442/.519, 6 HR
      { firstName: "Isaac", lastName: "Cadena", position: "C", eligibility: "JR", homeState: "TX", hometown: "Fort Worth", jerseyNumber: 14,
        hitForAvg: 72, power: 58, speed: 32, arm: 53, fielding: 53, errorResistance: 49, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 66, vsLHP: 60, grit: 66, stealing: 10, running: 28, throwing: 53, recovery: 41, wRISP: 66, vsLefty: 60, poise: 66, heater: 0, agile: 34,
        abilities: ["Contact Hitter", "Power Hitter", "Consigliere"], potential: "A+", catcherAbility: 53,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Richard Tejeda — C backup, big game vs Northwestern (3 RBI, 2-run HR)
      { firstName: "Richard", lastName: "Tejeda", position: "C", eligibility: "SO", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 15,
        hitForAvg: 37, power: 37, speed: 26, arm: 36, fielding: 35, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 36, vsLHP: 31, grit: 35, stealing: 7, running: 19, throwing: 36, recovery: 28, wRISP: 36, vsLefty: 31, poise: 35, heater: 0, agile: 22,
        abilities: ["Power Hitter"], potential: "B+", catcherAbility: 35,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // INFIELDERS (7)
      // Kevin Takeuchi — INF JR, offensive leader, .300/54H/44 RBI/48R/13 SB (14 att)/31 BB/11 2B/3 3B
      { firstName: "Kevin", lastName: "Takeuchi", position: "2B", eligibility: "JR", homeState: "CA", hometown: "Torrance", jerseyNumber: 4,
        hitForAvg: 93, power: 66, speed: 78, arm: 60, fielding: 63, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 85, vsLHP: 78, grit: 85, stealing: 60, running: 67, throwing: 60, recovery: 49, wRISP: 85, vsLefty: 78, poise: 85, heater: 0, agile: 63,
        abilities: ["Contact Hitter", "Express Baserunning", "Chance Maker"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Maximo Martinez — INF breakout, .257/.374/.390
      { firstName: "Maximo", lastName: "Martinez", position: "3B", eligibility: "SO", homeState: "CA", hometown: "Whittier", jerseyNumber: 5,
        hitForAvg: 43, power: 39, speed: 38, arm: 38, fielding: 37, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 38, vsLHP: 35, grit: 40, stealing: 13, running: 27, throwing: 38, recovery: 28, wRISP: 38, vsLefty: 35, poise: 38, heater: 0, agile: 32,
        abilities: ["Power Hitter"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Maddox Riske — INF, 5-for-6 game vs Cal Poly
      { firstName: "Maddox", lastName: "Riske", position: "SS", eligibility: "SO", homeState: "CA", hometown: "Newport Beach", jerseyNumber: 6,
        hitForAvg: 50, power: 41, speed: 52, arm: 45, fielding: 45, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 42, vsLHP: 39, grit: 43, stealing: 21, running: 36, throwing: 45, recovery: 34, wRISP: 42, vsLefty: 39, poise: 42, heater: 0, agile: 42,
        abilities: ["Defensive Artisan", "Contact Hitter"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Abbrie Covarrubias — SS JR, 4 RBI vs Rutgers
      { firstName: "Abbrie", lastName: "Covarrubias", position: "SS", eligibility: "JR", homeState: "CA", hometown: "Whittier", jerseyNumber: 2,
        hitForAvg: 51, power: 44, speed: 55, arm: 47, fielding: 47, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 47, vsLHP: 42, grit: 47, stealing: 31, running: 40, throwing: 47, recovery: 34, wRISP: 47, vsLefty: 42, poise: 47, heater: 0, agile: 47,
        abilities: ["Defensive Artisan", "Express Baserunning", "Consigliere"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "S",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Adrian Lopez — 3B JR
      { firstName: "Adrian", lastName: "Lopez", position: "3B", eligibility: "JR", homeState: "CA", hometown: "La Puente", jerseyNumber: 8,
        hitForAvg: 45, power: 41, speed: 39, arm: 38, fielding: 37, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 39, vsLHP: 37, grit: 40, stealing: 12, running: 26, throwing: 39, recovery: 31, wRISP: 39, vsLefty: 35, poise: 39, heater: 0, agile: 29,
        abilities: ["Contact Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Dean Carpentier — 1B JR
      { firstName: "Dean", lastName: "Carpentier", position: "1B", eligibility: "JR", homeState: "CA", hometown: "Santa Monica", jerseyNumber: 24,
        hitForAvg: 40, power: 42, speed: 34, arm: 31, fielding: 32, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 35, vsLHP: 32, grit: 36, stealing: 7, running: 21, throwing: 32, recovery: 28, wRISP: 35, vsLefty: 31, poise: 35, heater: 0, agile: 24,
        abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Caden Dana — 2B JR utility
      { firstName: "Caden", lastName: "Dana", position: "2B", eligibility: "JR", homeState: "CA", hometown: "Mission Viejo", jerseyNumber: 9,
        hitForAvg: 46, power: 37, speed: 51, arm: 43, fielding: 46, errorResistance: 43, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 39, vsLHP: 36, grit: 40, stealing: 25, running: 36, throwing: 43, recovery: 33, wRISP: 38, vsLefty: 35, poise: 39, heater: 0, agile: 40,
        abilities: ["Chance Maker", "Defensive Artisan"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // OUTFIELDERS (6)
      // Jack Basseer — OF SR, .600 SLG, 14 RBI, 19 R
      { firstName: "Jack", lastName: "Basseer", position: "OF", eligibility: "SR", homeState: "CA", hometown: "San Diego", jerseyNumber: 7,
        hitForAvg: 68, power: 72, speed: 55, arm: 49, fielding: 48, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 62, vsLHP: 56, grit: 62, stealing: 26, running: 42, throwing: 49, recovery: 39, wRISP: 62, vsLefty: 56, poise: 62, heater: 0, agile: 43,
        abilities: ["Artist", "Power Hitter", "Consigliere"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Brock Slaton — OF SR
      { firstName: "Brock", lastName: "Slaton", position: "OF", eligibility: "SR", homeState: "LA", hometown: "New Orleans", jerseyNumber: 17,
        hitForAvg: 46, power: 45, speed: 46, arm: 41, fielding: 38, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 41, vsLHP: 38, grit: 42, stealing: 25, running: 36, throwing: 41, recovery: 32, wRISP: 41, vsLefty: 38, poise: 41, heater: 0, agile: 37,
        abilities: ["Power Hitter", "High-Speed Laser"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Rhylan Thomas — OF JR
      { firstName: "Rhylan", lastName: "Thomas", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Long Beach", jerseyNumber: 1,
        hitForAvg: 33, power: 29, speed: 33, arm: 27, fielding: 27, errorResistance: 26, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 27, vsLHP: 26, grit: 28, stealing: 19, running: 27, throwing: 28, recovery: 22, wRISP: 27, vsLefty: 24, poise: 27, heater: 0, agile: 28,
        abilities: ["Express Baserunning", "Contact Hitter"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Dominic Hellman — OF SO speedster
      { firstName: "Dominic", lastName: "Hellman", position: "OF", eligibility: "SO", homeState: "CA", hometown: "Torrance", jerseyNumber: 11,
        hitForAvg: 47, power: 43, speed: 49, arm: 49, fielding: 45, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 41, vsLHP: 39, grit: 42, stealing: 29, running: 43, throwing: 49, recovery: 36, wRISP: 40, vsLefty: 37, poise: 41, heater: 0, agile: 49,
        abilities: ["Express Baserunning", "Contact Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Theo Denlinger — OF JR
      { firstName: "Theo", lastName: "Denlinger", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Santa Monica", jerseyNumber: 20,
        hitForAvg: 38, power: 38, speed: 40, arm: 28, fielding: 26, errorResistance: 23, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 33, vsLHP: 30, grit: 33, stealing: 6, running: 20, throwing: 27, recovery: 24, wRISP: 33, vsLefty: 28, poise: 33, heater: 0, agile: 20,
        abilities: ["Consigliere"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "S",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Braden Davis — OF SO
      { firstName: "Braden", lastName: "Davis", position: "OF", eligibility: "SO", homeState: "TX", hometown: "Austin", jerseyNumber: 26,
        hitForAvg: 38, power: 34, speed: 44, arm: 35, fielding: 34, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 32, vsLHP: 31, grit: 34, stealing: 22, running: 34, throwing: 36, recovery: 28, wRISP: 32, vsLefty: 29, poise: 32, heater: 0, agile: 35,
        abilities: ["Resilient", "Double Play"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
    ],
  
  // UCLA — 45-4 overall, 25-0 Big Ten, D1Baseball #1 (May 3, 2026)
  // Real 2026 mid-season stats from uclabruins.com PDF + Daily Bruin/Baseball America rotation pieces
  "UCLA": [
    // PITCHERS (10) — staff-leading 3.07 ERA, deepest rotation in country
    // Logan Reddemann — Friday SP, JR transfer from USD, projected first-rd, 8 quality starts, elite FB + tantalizing CH
    { firstName: "Logan", lastName: "Reddemann", position: "P", eligibility: "JR", homeState: "CA", hometown: "San Diego", jerseyNumber: 21,
      hitForAvg: 15, power: 12, speed: 28, arm: 61, fielding: 37, errorResistance: 47, velocity: 59, control: 61, stamina: 56, stuff: 61,
      clutch: 66, vsLHP: 64, grit: 67, stealing: 7, running: 28, throwing: 67, recovery: 53, wRISP: 55, vsLefty: 53, poise: 57, heater: 56, agile: 41,
      abilities: ["Star of Victory", "Inside Pitch", "Intimidator", "Natural Shuuto", "Kageura", "Heavy Ball", "True Slider"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    // Wylan Moss — Saturday bulk reliever / piggyback, SO, team-best 0.89 ERA, 93-95 + elite CH (20" horizontal break), top-15 2027 prospect
    { firstName: "Wylan", lastName: "Moss", position: "P", eligibility: "SO", homeState: "CA", hometown: "Calabasas", jerseyNumber: 40,
      hitForAvg: 11, power: 10, speed: 33, arm: 63, fielding: 38, errorResistance: 52, velocity: 63, control: 63, stamina: 52, stuff: 65,
      clutch: 76, vsLHP: 72, grit: 76, stealing: 7, running: 30, throwing: 75, recovery: 52, wRISP: 62, vsLefty: 58, poise: 62, heater: 55, agile: 50,
      abilities: ["Strong Starter", "Inside Pitch", "Sharpness"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "medium",
      ...pitchMix(1, [0, 4, 0, 1, 0, 0, 0]) },
    // Michael Barnett — Saturday opener, SR, 3.74 ERA, 244 career IP, four-pitch mix (sinker/CH/SL/CB)
    { firstName: "Michael", lastName: "Barnett", position: "P", eligibility: "SR", homeState: "CA", hometown: "Manhattan Beach", jerseyNumber: 34,
      hitForAvg: 16, power: 12, speed: 32, arm: 56, fielding: 40, errorResistance: 57, velocity: 54, control: 61, stamina: 56, stuff: 51,
      clutch: 71, vsLHP: 69, grit: 75, stealing: 6, running: 27, throwing: 67, recovery: 53, wRISP: 54, vsLefty: 56, poise: 59, heater: 48, agile: 39,
      abilities: ["Strong Starter", "Guts", "Inside Pitch", "Delayed Arm"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 4, 1, 0, 5, 0]) },
    // Landon Stump — Sunday SP, JR, 4.33 ERA, ~3 IP/start, surviving Sundays
    { firstName: "Landon", lastName: "Stump", position: "P", eligibility: "JR", homeState: "CA", hometown: "Huntington Beach", jerseyNumber: 14,
      hitForAvg: 10, power: 8, speed: 23, arm: 35, fielding: 23, errorResistance: 35, velocity: 39, control: 32, stamina: 29, stuff: 32,
      clutch: 40, vsLHP: 38, grit: 41, stealing: 4, running: 20, throwing: 42, recovery: 29, wRISP: 29, vsLefty: 30, poise: 31, heater: 35, agile: 30,
      abilities: ["Guts", "Release", "Inside Pitch"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    // Easton Hawk — closer, SO, mid-90s + tight horizontal SL, 16 scoreless app, Big Ten Co-Pitcher of Week, Woodland Hills CA
    { firstName: "Easton", lastName: "Hawk", position: "P", eligibility: "SO", homeState: "CA", hometown: "Woodland Hills", jerseyNumber: 27,
      hitForAvg: 9, power: 6, speed: 24, arm: 49, fielding: 27, errorResistance: 38, velocity: 49, control: 44, stamina: 23, stuff: 46,
      clutch: 62, vsLHP: 56, grit: 59, stealing: 5, running: 23, throwing: 58, recovery: 37, wRISP: 47, vsLefty: 44, poise: 49, heater: 41, agile: 38,
      abilities: ["Fireman", "Doctor K", "Intimidator"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "S",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 6, 0, 1, 0, 0, 0]) },
    // Cal Randall — JR setup, 98mph FB touching 100, 21K/11IP (42% K rate, 8th P4), walks 1 of 5
    { firstName: "Cal", lastName: "Randall", position: "P", eligibility: "JR", homeState: "CA", hometown: "Temecula", jerseyNumber: 33,
      hitForAvg: 7, power: 6, speed: 21, arm: 44, fielding: 21, errorResistance: 30, velocity: 46, control: 25, stamina: 15, stuff: 41,
      clutch: 43, vsLHP: 40, grit: 40, stealing: 5, running: 19, throwing: 53, recovery: 26, wRISP: 32, vsLefty: 32, poise: 32, heater: 40, agile: 34,
      abilities: ["Fireman", "Explosive Fastball", "Walk"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 0, 1, 0, 0, 0]) },
    // Angel Cervantes — FR, RHP, 2nd-round talent who chose college, top young prospect
    { firstName: "Angel", lastName: "Cervantes", position: "P", eligibility: "FR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 29,
      hitForAvg: 8, power: 5, speed: 22, arm: 38, fielding: 21, errorResistance: 27, velocity: 42, control: 32, stamina: 30, stuff: 38,
      clutch: 35, vsLHP: 34, grit: 35, stealing: 5, running: 19, throwing: 47, recovery: 25, wRISP: 25, vsLefty: 26, poise: 26, heater: 37, agile: 29,
      abilities: ["Strong Starter", "Sharpness", "Kageura"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    // Zach Strickland — FR RHP, weekend bullpen, elite K/BB
    { firstName: "Zach", lastName: "Strickland", position: "P", eligibility: "FR", homeState: "CA", hometown: "Redondo Beach", jerseyNumber: 45,
      hitForAvg: 7, power: 4, speed: 21, arm: 29, fielding: 16, errorResistance: 25, velocity: 29, control: 36, stamina: 20, stuff: 28,
      clutch: 36, vsLHP: 34, grit: 36, stealing: 4, running: 17, throwing: 39, recovery: 22, wRISP: 25, vsLefty: 25, poise: 27, heater: 29, agile: 25,
      abilities: ["Inside Pitch"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "blonde", hairStyle: "short",
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    // Ian May — RS-Sr LHP, multi-inning long man
    { firstName: "Ian", lastName: "May", position: "P", eligibility: "SR", homeState: "CA", hometown: "Rancho Cucamonga", jerseyNumber: 38,
      hitForAvg: 8, power: 6, speed: 19, arm: 28, fielding: 19, errorResistance: 29, velocity: 26, control: 30, stamina: 26, stuff: 24,
      clutch: 34, vsLHP: 45, grit: 36, stealing: 3, running: 14, throwing: 36, recovery: 24, wRISP: 24, vsLefty: 33, poise: 26, heater: 24, agile: 20,
      abilities: ["Fireman", "Guts", "Houdini"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    // Jake Swenson — JR depth pitcher
    { firstName: "Jake", lastName: "Swenson", position: "P", eligibility: "JR", homeState: "WA", hometown: "Seattle", jerseyNumber: 48,
      hitForAvg: 7, power: 6, speed: 19, arm: 23, fielding: 15, errorResistance: 24, velocity: 25, control: 25, stamina: 21, stuff: 22,
      clutch: 29, vsLHP: 28, grit: 29, stealing: 5, running: 14, throwing: 33, recovery: 19, wRISP: 19, vsLefty: 20, poise: 20, heater: 24, agile: 20,
      abilities: ["True Slider", "Gear Change"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 3, 3, 1, 0, 0, 0]) },
    // CATCHERS (2)
    // Cashel Dugger — JR C, Buster Posey Award watch list, primary backstop
    { firstName: "Cashel", lastName: "Dugger", position: "C", eligibility: "JR", homeState: "CA", hometown: "Torrance", jerseyNumber: 16,
      hitForAvg: 49, power: 46, speed: 26, arm: 55, fielding: 51, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 44, grit: 51, stealing: 8, running: 21, throwing: 55, recovery: 40, wRISP: 47, vsLefty: 43, poise: 50, heater: 0, agile: 28,
      abilities: ["Defensive Artisan", "High-Speed Laser", "Consigliere"], potential: "A-", catcherAbility: 51,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Khansarinia — backup C, allowed 10 SB on 12 attempts (mentioned in PDF SBA)
    { firstName: "Sam", lastName: "Khansarinia", position: "C", eligibility: "SO", homeState: "CA", hometown: "Irvine", jerseyNumber: 18,
      hitForAvg: 35, power: 31, speed: 33, arm: 46, fielding: 41, errorResistance: 39, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 31, vsLHP: 28, grit: 33, stealing: 5, running: 19, throwing: 46, recovery: 28, wRISP: 28, vsLefty: 26, poise: 31, heater: 0, agile: 24,
      abilities: ["Bases Loaded Slugger", "Tough Out", "Resilient"], potential: "B-", catcherAbility: 39,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // INFIELDERS (7)
    // Roch Cholowsky — JR SS, projected #1 overall MLB pick, .335/18HR/62R, leads B10 in runs, generational talent
    { firstName: "Roch", lastName: "Cholowsky", position: "SS", eligibility: "JR", homeState: "CA", hometown: "Oceanside", jerseyNumber: 2,
      hitForAvg: 99, power: 99, speed: 91, arm: 99, fielding: 99, errorResistance: 99, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 99, vsLHP: 99, grit: 99, stealing: 47, running: 87, throwing: 99, recovery: 85, wRISP: 99, vsLefty: 99, poise: 99, heater: 0, agile: 87,
      abilities: ["Iron Man", "Push", "Power Hitter", "Consigliere", "Contact Hitter", "Tough Out"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Mulivai Levu — 1B, .347/14HR/54RBI, All-Conference 2025
    { firstName: "Mulivai", lastName: "Levu", position: "1B", eligibility: "JR", homeState: "HI", hometown: "Honolulu", jerseyNumber: 24,
      hitForAvg: 72, power: 74, speed: 47, arm: 48, fielding: 51, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 68, vsLHP: 60, grit: 64, stealing: 7, running: 23, throwing: 48, recovery: 46, wRISP: 66, vsLefty: 58, poise: 64, heater: 0, agile: 27,
      abilities: ["Artist", "Power Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "L",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Roman Martin — SO, .339/7HR, All-Conference, hybrid C/3B per Daily Bruin
    { firstName: "Roman", lastName: "Martin", position: "3B", eligibility: "SO", homeState: "CA", hometown: "Chino Hills", jerseyNumber: 8,
      hitForAvg: 63, power: 51, speed: 42, arm: 49, fielding: 48, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 52, grit: 52, stealing: 11, running: 26, throwing: 50, recovery: 39, wRISP: 54, vsLefty: 51, poise: 54, heater: 0, agile: 33,
      abilities: ["Contact Hitter", "Defensive Artisan"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Aidan Espinoza — FR INF, .360 (team batting leader), Sherman Oaks/Notre Dame HS
    { firstName: "Aidan", lastName: "Espinoza", position: "2B", eligibility: "FR", homeState: "CA", hometown: "Sherman Oaks", jerseyNumber: 6,
      hitForAvg: 72, power: 48, speed: 59, arm: 47, fielding: 49, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 55, vsLHP: 54, grit: 53, stealing: 19, running: 40, throwing: 47, recovery: 43, wRISP: 58, vsLefty: 56, poise: 54, heater: 0, agile: 46,
      abilities: ["Contact Hitter", "Chance Maker"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Phoenix Call — SO INF, 1 HR, role player
    { firstName: "Phoenix", lastName: "Call", position: "SS", eligibility: "SO", homeState: "CA", hometown: "Anaheim", jerseyNumber: 3,
      hitForAvg: 38, power: 32, speed: 56, arm: 42, fielding: 44, errorResistance: 41, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 33, vsLHP: 32, grit: 36, stealing: 18, running: 33, throwing: 44, recovery: 30, wRISP: 32, vsLefty: 30, poise: 33, heater: 0, agile: 42,
      abilities: ["Iron Man", "Error Prone"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "medium",
      ...noPitches },
    // Cole Lee — depth IF (mentioned in PDF SBA totals)
    { firstName: "Cole", lastName: "Lee", position: "2B", eligibility: "FR", homeState: "CA", hometown: "Glendale", jerseyNumber: 14,
      hitForAvg: 30, power: 25, speed: 51, arm: 33, fielding: 32, errorResistance: 28, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 25, vsLHP: 23, grit: 26, stealing: 14, running: 28, throwing: 33, recovery: 23, wRISP: 23, vsLefty: 22, poise: 25, heater: 0, agile: 33,
      abilities: ["Pinch Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "S",
      skinTone: "light", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Tommy Bott — backup 1B/depth (mentioned in PDF SBA)
    { firstName: "Tommy", lastName: "Bott", position: "1B", eligibility: "FR", homeState: "CA", hometown: "San Clemente", jerseyNumber: 28,
      hitForAvg: 37, power: 41, speed: 57, arm: 46, fielding: 41, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 30, vsLHP: 28, grit: 32, stealing: 8, running: 25, throwing: 46, recovery: 30, wRISP: 30, vsLefty: 27, poise: 30, heater: 0, agile: 28,
      abilities: ["Double Play"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // OUTFIELDERS (6)
    // Will Gasparino — JR OF, Texas transfer, .322/18HR (team co-leader), LA/Harvard-Westlake, two-time All-Big 12, SEC All-Defense
    { firstName: "Will", lastName: "Gasparino", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 11,
      hitForAvg: 79, power: 89, speed: 60, arm: 69, fielding: 67, errorResistance: 63, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 79, vsLHP: 67, grit: 69, stealing: 27, running: 49, throwing: 69, recovery: 56, wRISP: 75, vsLefty: 67, poise: 71, heater: 0, agile: 56,
      abilities: ["Power Hitter", "High-Speed Laser", "Good Infield Hit"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "S",
      skinTone: "light", hairColor: "brown", hairStyle: "medium",
      ...noPitches },
    // Dean West — LF leadoff, .470 OBP, JR, walks/HBP machine
    { firstName: "Dean", lastName: "West", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Temecula", jerseyNumber: 7,
      hitForAvg: 63, power: 49, speed: 56, arm: 47, fielding: 50, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 56, grit: 64, stealing: 36, running: 50, throwing: 49, recovery: 45, wRISP: 56, vsLefty: 56, poise: 57, heater: 0, agile: 52,
      abilities: ["Chance Maker", "Express Baserunning"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Payton Brennan — JR OF, 8 HR, 6 SB
    { firstName: "Payton", lastName: "Brennan", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Anaheim", jerseyNumber: 9,
      hitForAvg: 51, power: 51, speed: 49, arm: 43, fielding: 43, errorResistance: 41, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 45, vsLHP: 43, grit: 48, stealing: 27, running: 40, throwing: 44, recovery: 37, wRISP: 45, vsLefty: 43, poise: 45, heater: 0, agile: 40,
      abilities: ["Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Daylen Reyes — SO OF speed/defense
    { firstName: "Daylen", lastName: "Reyes", position: "OF", eligibility: "SO", homeState: "CA", hometown: "Oxnard", jerseyNumber: 30,
      hitForAvg: 33, power: 29, speed: 40, arm: 38, fielding: 36, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 27, vsLHP: 26, grit: 29, stealing: 26, running: 38, throwing: 38, recovery: 27, wRISP: 27, vsLefty: 26, poise: 28, heater: 0, agile: 38,
      abilities: ["Express Baserunning"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Tristan Iwanaga — depth OF (mentioned PDF SBA 2-2)
    { firstName: "Tristan", lastName: "Iwanaga", position: "OF", eligibility: "SO", homeState: "HI", hometown: "Honolulu", jerseyNumber: 17,
      hitForAvg: 36, power: 31, speed: 49, arm: 38, fielding: 39, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 30, vsLHP: 29, grit: 34, stealing: 22, running: 38, throwing: 39, recovery: 30, wRISP: 30, vsLefty: 29, poise: 32, heater: 0, agile: 39,
      abilities: ["Multi-Hit", "Late Night Hero", "Contact Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Michael Curialle — JR OF depth
    { firstName: "Michael", lastName: "Curialle", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Rancho Cucamonga", jerseyNumber: 26,
      hitForAvg: 33, power: 31, speed: 44, arm: 32, fielding: 32, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 27, vsLHP: 26, grit: 30, stealing: 14, running: 26, throwing: 32, recovery: 24, wRISP: 26, vsLefty: 24, poise: 27, heater: 0, agile: 30,
      abilities: ["Good Mood"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "S",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
  ],

  "Washington": [
    // PITCHERS (10)
    { firstName: "Hayden", lastName: "Lewis", position: "P", eligibility: "SR", homeState: "AZ", hometown: "Tucson", jerseyNumber: 17,
      hitForAvg: 25, power: 19, speed: 40, arm: 82, fielding: 53, errorResistance: 67, velocity: 86, control: 78, stamina: 78, stuff: 78,
      clutch: 95, vsLHP: 90, grit: 99, stealing: 12, running: 42, throwing: 97, recovery: 73, wRISP: 76, vsLefty: 78, poise: 78, heater: 83, agile: 53,
      abilities: ["Star of Victory", "Strong Starter", "Guts", "Escape Pitch", "Gyroball", "Wild Fastball"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 7, 5, 1, 0, 0, 0]) },
    { firstName: "Nate", lastName: "Tichy", position: "P", eligibility: "SO", homeState: "CA", hometown: "Malibu", jerseyNumber: 18,
      hitForAvg: 17, power: 13, speed: 43, arm: 62, fielding: 39, errorResistance: 53, velocity: 70, control: 58, stamina: 61, stuff: 61,
      clutch: 72, vsLHP: 67, grit: 74, stealing: 13, running: 43, throwing: 79, recovery: 50, wRISP: 53, vsLefty: 54, poise: 56, heater: 67, agile: 52,
      abilities: ["Strong Starter", "Explosive Fastball", "Intimidator", "Quick Hands"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "R",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Liam", lastName: "Lierman", position: "P", eligibility: "FR", homeState: "AK", hometown: "Anchorage", jerseyNumber: 15,
      hitForAvg: 8, power: 6, speed: 23, arm: 32, fielding: 14, errorResistance: 23, velocity: 38, control: 29, stamina: 30, stuff: 30,
      clutch: 28, vsLHP: 27, grit: 29, stealing: 6, running: 16, throwing: 33, recovery: 17, wRISP: 17, vsLefty: 18, poise: 18, heater: 25, agile: 22,
      abilities: ["Guts"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Cooper", lastName: "Benson", position: "P", eligibility: "SR", homeState: "OR", hometown: "Portland", jerseyNumber: 41,
      hitForAvg: 13, power: 10, speed: 27, arm: 38, fielding: 25, errorResistance: 37, velocity: 46, control: 38, stamina: 37, stuff: 36,
      clutch: 50, vsLHP: 47, grit: 50, stealing: 7, running: 23, throwing: 50, recovery: 36, wRISP: 36, vsLefty: 37, poise: 37, heater: 40, agile: 28,
      abilities: ["Fireman", "Guts"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 6, 0, 1, 4, 0, 0]) },
    { firstName: "Parker", lastName: "Pistone", position: "P", eligibility: "JR", homeState: "WA", hometown: "Redmond", jerseyNumber: 22,
      hitForAvg: 11, power: 9, speed: 24, arm: 32, fielding: 21, errorResistance: 29, velocity: 38, control: 32, stamina: 33, stuff: 32,
      clutch: 41, vsLHP: 38, grit: 42, stealing: 6, running: 21, throwing: 43, recovery: 29, wRISP: 29, vsLefty: 30, poise: 31, heater: 34, agile: 26,
      abilities: ["Strong Starter", "Flyball Pitcher", "Low Ball"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Sam", lastName: "Strohl", position: "P", eligibility: "JR", homeState: "WA", hometown: "Olympia", jerseyNumber: 38,
      hitForAvg: 16, power: 13, speed: 33, arm: 44, fielding: 29, errorResistance: 41, velocity: 52, control: 44, stamina: 43, stuff: 43,
      clutch: 54, vsLHP: 51, grit: 55, stealing: 9, running: 29, throwing: 58, recovery: 40, wRISP: 37, vsLefty: 41, poise: 41, heater: 48, agile: 36,
      abilities: ["Natural Shuuto", "Star of Victory"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Quinn", lastName: "Mathews", position: "P", eligibility: "SO", homeState: "WA", hometown: "Spokane", jerseyNumber: 48,
      hitForAvg: 9, power: 8, speed: 27, arm: 28, fielding: 18, errorResistance: 28, velocity: 31, control: 34, stamina: 27, stuff: 26,
      clutch: 34, vsLHP: 33, grit: 35, stealing: 9, running: 23, throwing: 40, recovery: 23, wRISP: 23, vsLefty: 24, poise: 23, heater: 30, agile: 28,
      abilities: ["Guts", "Phantasmagoric"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Bremner", position: "P", eligibility: "SO", homeState: "OR", hometown: "Eugene", jerseyNumber: 50,
      hitForAvg: 8, power: 8, speed: 26, arm: 36, fielding: 23, errorResistance: 24, velocity: 43, control: 35, stamina: 35, stuff: 33,
      clutch: 27, vsLHP: 26, grit: 29, stealing: 8, running: 20, throwing: 35, recovery: 26, wRISP: 26, vsLefty: 29, poise: 27, heater: 38, agile: 24,
      abilities: ["Cowardly"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 3, 4, 1, 0, 0, 0]) },
    { firstName: "Nate", lastName: "Weeldreyer", position: "P", eligibility: "JR", homeState: "WA", hometown: "Lynnwood", jerseyNumber: 36,
      hitForAvg: 9, power: 6, speed: 23, arm: 21, fielding: 14, errorResistance: 23, velocity: 34, control: 20, stamina: 20, stuff: 23,
      clutch: 30, vsLHP: 29, grit: 30, stealing: 5, running: 16, throwing: 32, recovery: 19, wRISP: 19, vsLefty: 20, poise: 20, heater: 23, agile: 20,
      abilities: ["Monster Stuff"], potential: "B-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Harmon", position: "P", eligibility: "SO", homeState: "CA", hometown: "San Bernardino", jerseyNumber: 45,
      hitForAvg: 9, power: 7, speed: 25, arm: 27, fielding: 18, errorResistance: 26, velocity: 37, control: 26, stamina: 26, stuff: 25,
      clutch: 30, vsLHP: 28, grit: 31, stealing: 7, running: 20, throwing: 35, recovery: 22, wRISP: 22, vsLefty: 23, poise: 23, heater: 28, agile: 25,
      abilities: ["Poor Finisher"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Colton", lastName: "Bower", position: "C", eligibility: "JR", homeState: "WA", hometown: "Pullman", jerseyNumber: 2,
      hitForAvg: 59, power: 52, speed: 35, arm: 59, fielding: 57, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 50, grit: 56, stealing: 13, running: 30, throwing: 60, recovery: 46, wRISP: 52, vsLefty: 49, poise: 53, heater: 0, agile: 34,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: 53,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Ethan", lastName: "Swidler", position: "C", eligibility: "SR", homeState: "PA", hometown: "Easton", jerseyNumber: 4,
      hitForAvg: 54, power: 48, speed: 34, arm: 53, fielding: 52, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 45, grit: 51, stealing: 11, running: 27, throwing: 55, recovery: 41, wRISP: 48, vsLefty: 44, poise: 49, heater: 0, agile: 29,
      abilities: ["Contact Hitter"], potential: "B", catcherAbility: 49,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // INFIELDERS (7)
    { firstName: "Ty", lastName: "Cowan", position: "SS", eligibility: "SR", homeState: "WA", hometown: "Kirkland", jerseyNumber: 1,
      hitForAvg: 50, power: 43, speed: 62, arm: 47, fielding: 48, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 45, vsLHP: 41, grit: 47, stealing: 34, running: 41, throwing: 48, recovery: 36, wRISP: 43, vsLefty: 41, poise: 45, heater: 0, agile: 47,
      abilities: ["Defensive Artisan", "Express Baserunning"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Chase", lastName: "Cretti", position: "3B", eligibility: "JR", homeState: "WA", hometown: "Sammamish", jerseyNumber: 3,
      hitForAvg: 73, power: 66, speed: 65, arm: 68, fielding: 66, errorResistance: 65, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 65, vsLHP: 60, grit: 66, stealing: 23, running: 47, throwing: 69, recovery: 53, wRISP: 63, vsLefty: 58, poise: 65, heater: 0, agile: 52,
      abilities: ["Contact Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Blake", lastName: "Wilson", position: "1B", eligibility: "JR", homeState: "WA", hometown: "Bellevue", jerseyNumber: 7,
      hitForAvg: 60, power: 57, speed: 53, arm: 51, fielding: 53, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 51, grit: 53, stealing: 13, running: 33, throwing: 53, recovery: 43, wRISP: 51, vsLefty: 49, poise: 53, heater: 0, agile: 36,
      abilities: ["Power Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Casen", lastName: "Taggart", position: "2B", eligibility: "SR", homeState: "WA", hometown: "Pullman", jerseyNumber: 12,
      hitForAvg: 77, power: 62, speed: 87, arm: 68, fielding: 73, errorResistance: 72, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 67, vsLHP: 63, grit: 68, stealing: 42, running: 61, throwing: 72, recovery: 57, wRISP: 66, vsLefty: 61, poise: 67, heater: 0, agile: 67,
      abilities: ["Chance Maker"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Landon", lastName: "Young", position: "SS", eligibility: "FR", homeState: "TX", hometown: "Fort Worth", jerseyNumber: 6,
      hitForAvg: 35, power: 29, speed: 56, arm: 35, fielding: 32, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 28, vsLHP: 26, grit: 29, stealing: 24, running: 35, throwing: 36, recovery: 24, wRISP: 27, vsLefty: 24, poise: 27, heater: 0, agile: 37,
      abilities: ["Late Night Hero"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Alexander", lastName: "Pearson", position: "1B", eligibility: "FR", homeState: "WA", hometown: "Seattle", jerseyNumber: 11,
      hitForAvg: 41, power: 38, speed: 46, arm: 42, fielding: 39, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 29, grit: 34, stealing: 11, running: 28, throwing: 43, recovery: 29, wRISP: 31, vsLefty: 28, poise: 31, heater: 0, agile: 31,
      abilities: ["Storming Home", "Artist"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Jake", lastName: "Dukart", position: "2B", eligibility: "FR", homeState: "WA", hometown: "Pasco", jerseyNumber: 14,
      hitForAvg: 33, power: 26, speed: 53, arm: 34, fielding: 32, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 26, vsLHP: 24, grit: 27, stealing: 21, running: 34, throwing: 34, recovery: 23, wRISP: 24, vsLefty: 23, poise: 26, heater: 0, agile: 36,
      abilities: ["Hit Machine", "Good Mood", "Good Bunt"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Aidan", lastName: "Dougherty", position: "OF", eligibility: "SR", homeState: "CA", hometown: "San Jose", jerseyNumber: 9,
      hitForAvg: 81, power: 75, speed: 82, arm: 72, fielding: 71, errorResistance: 69, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 72, vsLHP: 69, grit: 75, stealing: 47, running: 65, throwing: 75, recovery: 57, wRISP: 72, vsLefty: 65, poise: 72, heater: 0, agile: 71,
      abilities: ["High-Speed Laser", "Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Braeden", lastName: "Terry", position: "OF", eligibility: "SR", homeState: "WA", hometown: "Tacoma", jerseyNumber: 10,
      hitForAvg: 50, power: 45, speed: 54, arm: 45, fielding: 43, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 43, vsLHP: 41, grit: 45, stealing: 27, running: 39, throwing: 46, recovery: 35, wRISP: 42, vsLefty: 39, poise: 43, heater: 0, agile: 42,
      abilities: ["Contact Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Mic", lastName: "Paul", position: "OF", eligibility: "JR", homeState: "LA", hometown: "Baton Rouge", jerseyNumber: 13,
      hitForAvg: 48, power: 45, speed: 54, arm: 43, fielding: 42, errorResistance: 40, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 39, grit: 43, stealing: 32, running: 42, throwing: 44, recovery: 34, wRISP: 40, vsLefty: 38, poise: 42, heater: 0, agile: 43,
      abilities: ["Express Baserunning", "Contact Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Jackson", lastName: "Hotchkiss", position: "OF", eligibility: "SO", homeState: "WA", hometown: "Vancouver", jerseyNumber: 19,
      hitForAvg: 45, power: 79, speed: 53, arm: 43, fielding: 40, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 35, grit: 40, stealing: 27, running: 40, throwing: 44, recovery: 32, wRISP: 37, vsLefty: 33, poise: 38, heater: 0, agile: 43,
      abilities: ["Slap Happy", "Contact Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Kyle", lastName: "Seymour", position: "OF", eligibility: "FR", homeState: "WA", hometown: "Lynnwood", jerseyNumber: 26,
      hitForAvg: 38, power: 31, speed: 55, arm: 39, fielding: 34, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 29, vsLHP: 28, grit: 30, stealing: 25, running: 39, throwing: 41, recovery: 28, wRISP: 28, vsLefty: 25, poise: 28, heater: 0, agile: 42,
      abilities: ["Slap Happy"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...noPitches },
    { firstName: "JR", lastName: "Ritger", position: "OF", eligibility: "SO", homeState: "WI", hometown: "Appleton", jerseyNumber: 30,
      hitForAvg: 33, power: 30, speed: 45, arm: 31, fielding: 28, errorResistance: 27, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 27, vsLHP: 25, grit: 27, stealing: 19, running: 28, throwing: 32, recovery: 24, wRISP: 25, vsLefty: 25, poise: 27, heater: 0, agile: 31,
      abilities: ["Trickster", "Pressure Run"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "R",
      ...noPitches },
  ],
};
