import type { RealPlayer } from "./realRosters";
import { pitchMix, noPitches } from "./pitchMixHelpers";
import { MWC_ROSTERS } from "./mwcRosters";

export const PAC12_ROSTERS: Record<string, RealPlayer[]> = {
  "Oregon State": [
    // 37-11/.771, D1B #6, NCAA Independent Yr 2, Mitch Canham Yr 7. CWS return 2025.
    // Returns 3 lineup regulars (Krieg/Singer/Talt). Lost: Arquette/Turley/Macias/Reeder/Weber to draft. Pitching is the strength.
    // PITCHERS (10) — TEAM ELITE STAFF
    // Dax Whitney — Friday SO RHP ace, 98mph FB, 17"+ sweeper 42% whiff, 3.40/120K/76.2 IP — TEAM ELITE
    { firstName: "Dax", lastName: "Whitney", position: "P", eligibility: "SO", homeState: "ID", hometown: "Boise", jerseyNumber: 22,
      hitForAvg: 16, power: 12, speed: 33, arm: 70, fielding: 41, errorResistance: 54, velocity: 67, control: 66, stamina: 69, stuff: 72,
      clutch: 80, vsLHP: 76, grit: 81, stealing: 10, running: 34, throwing: 81, recovery: 57, wRISP: 62, vsLefty: 63, poise: 67, heater: 70, agile: 44,
      abilities: ["Star of Victory", "Intimidator", "Sharpness", "Decisive", "Winner's Luck"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 8, 7, 1, 0, 0, 0]) },
    // Ethan Kleinschmit — Saturday LHP JR, 3.56/113K/91 IP, JUCO transfer
    { firstName: "Ethan", lastName: "Kleinschmit", position: "P", eligibility: "JR", homeState: "NE", hometown: "Omaha", jerseyNumber: 29,
      hitForAvg: 13, power: 11, speed: 28, arm: 57, fielding: 33, errorResistance: 44, velocity: 50, control: 57, stamina: 57, stuff: 55,
      clutch: 67, vsLHP: 69, grit: 67, stealing: 9, running: 28, throwing: 67, recovery: 49, wRISP: 52, vsLefty: 55, poise: 54, heater: 55, agile: 37,
      abilities: ["Strong Starter", "Fireman", "Inside Pitch", "Star of Victory", "Intimidator", "Full Throttle"], potential: "A", catcherAbility: null,
      throwHand: "L", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 7, 6, 1, 0, 0, 0]) },
    // Eric Segura — Sunday RHP, proven potency
    { firstName: "Eric", lastName: "Segura", position: "P", eligibility: "JR", homeState: "CA", hometown: "Riverside", jerseyNumber: 31,
      hitForAvg: 13, power: 11, speed: 34, arm: 60, fielding: 36, errorResistance: 48, velocity: 55, control: 58, stamina: 60, stuff: 58,
      clutch: 73, vsLHP: 67, grit: 73, stealing: 8, running: 32, throwing: 75, recovery: 51, wRISP: 53, vsLefty: 53, poise: 57, heater: 62, agile: 41,
      abilities: ["Strong Starter", "Painter", "Constant Speed", "Intimidator"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...pitchMix(1, [0, 6, 6, 1, 0, 0, 0]) },
    // Laif Palmer — RHP, top 2026 draft prospect on team
    { firstName: "Laif", lastName: "Palmer", position: "P", eligibility: "JR", homeState: "OR", hometown: "Portland", jerseyNumber: 27,
      hitForAvg: 13, power: 10, speed: 30, arm: 62, fielding: 35, errorResistance: 47, velocity: 56, control: 56, stamina: 45, stuff: 59,
      clutch: 73, vsLHP: 67, grit: 71, stealing: 9, running: 30, throwing: 73, recovery: 45, wRISP: 54, vsLefty: 53, poise: 57, heater: 62, agile: 40,
      abilities: ["Fireman", "Explosive Fastball", "Strikeout", "Intimidator"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 7, 6, 1, 0, 0, 0]) },
    // Trey Morris — RHP, 4 wins, 5 IP CSUN
    { firstName: "Trey", lastName: "Morris", position: "P", eligibility: "JR", homeState: "CA", hometown: "San Diego", jerseyNumber: 33,
      hitForAvg: 11, power: 8, speed: 26, arm: 44, fielding: 28, errorResistance: 38, velocity: 41, control: 48, stamina: 44, stuff: 43,
      clutch: 56, vsLHP: 50, grit: 56, stealing: 7, running: 25, throwing: 56, recovery: 40, wRISP: 40, vsLefty: 40, poise: 43, heater: 44, agile: 34,
      abilities: ["Strong Starter", "Guts", "Indomitable Soul"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    // James DeCremer III — RHP RP
    { firstName: "James", lastName: "DeCremer III", position: "P", eligibility: "SR", homeState: "WA", hometown: "Seattle", jerseyNumber: 38,
      hitForAvg: 11, power: 8, speed: 25, arm: 44, fielding: 25, errorResistance: 34, velocity: 41, control: 42, stamina: 31, stuff: 42,
      clutch: 55, vsLHP: 50, grit: 55, stealing: 6, running: 23, throwing: 53, recovery: 33, wRISP: 39, vsLefty: 39, poise: 42, heater: 45, agile: 32,
      abilities: ["Fireman", "Poker Face", "Good Pickoff", "Strong Finisher"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    // Wyatt Queen — RHP RP
    { firstName: "Wyatt", lastName: "Queen", position: "P", eligibility: "JR", homeState: "OR", hometown: "Eugene", jerseyNumber: 40,
      hitForAvg: 10, power: 8, speed: 24, arm: 41, fielding: 24, errorResistance: 33, velocity: 38, control: 41, stamina: 28, stuff: 39,
      clutch: 51, vsLHP: 46, grit: 51, stealing: 6, running: 23, throwing: 51, recovery: 32, wRISP: 35, vsLefty: 35, poise: 39, heater: 42, agile: 29,
      abilities: ["Fireman", "Strong Starter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    // Jake Pfennigs — JR RHP RP holdover
    { firstName: "Jake", lastName: "Pfennigs", position: "P", eligibility: "JR", homeState: "WA", hometown: "Spokane", jerseyNumber: 25,
      hitForAvg: 8, power: 5, speed: 22, arm: 32, fielding: 20, errorResistance: 28, velocity: 31, control: 32, stamina: 30, stuff: 31,
      clutch: 40, vsLHP: 37, grit: 40, stealing: 5, running: 17, throwing: 41, recovery: 27, wRISP: 28, vsLefty: 28, poise: 30, heater: 33, agile: 24,
      abilities: ["Guts", "Flyball Pitcher", "Cross Cannon"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    // Sam Keller — SO RHP RP
    { firstName: "Sam", lastName: "Keller", position: "P", eligibility: "SO", homeState: "OR", hometown: "Bend", jerseyNumber: 44,
      hitForAvg: 8, power: 6, speed: 21, arm: 30, fielding: 19, errorResistance: 27, velocity: 31, control: 30, stamina: 23, stuff: 29,
      clutch: 38, vsLHP: 35, grit: 38, stealing: 5, running: 19, throwing: 39, recovery: 25, wRISP: 26, vsLefty: 26, poise: 28, heater: 31, agile: 25,
      abilities: ["Top Gear", "Sharpness", "Staredown"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    // Mason Pike — FR two-way SS/P, top-150 draft, up to 95mph (filed as P)
    { firstName: "Mason", lastName: "Pike", position: "P", eligibility: "FR", homeState: "WA", hometown: "Bellevue", jerseyNumber: 50,
      hitForAvg: 19, power: 18, speed: 27, arm: 46, fielding: 26, errorResistance: 34, velocity: 43, control: 34, stamina: 30, stuff: 43,
      clutch: 35, vsLHP: 32, grit: 35, stealing: 18, running: 34, throwing: 59, recovery: 26, wRISP: 24, vsLefty: 26, poise: 26, heater: 46, agile: 37,
      abilities: ["Explosive Fastball", "Sharpness", "Low Ball"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    // CATCHERS (2) — wide-open competition (Weber gone)
    { firstName: "Wilson", lastName: "Hoyt", position: "C", eligibility: "JR", homeState: "OR", hometown: "Salem", jerseyNumber: 14,
      hitForAvg: 38, power: 34, speed: 25, arm: 42, fielding: 42, errorResistance: 39, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 34, vsLHP: 31, grit: 36, stealing: 6, running: 20, throwing: 42, recovery: 31, wRISP: 32, vsLefty: 29, poise: 34, heater: 0, agile: 24,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: 39,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    { firstName: "Maddox", lastName: "Molony", position: "C", eligibility: "FR", homeState: "OR", hometown: "Beaverton", jerseyNumber: 18,
      hitForAvg: 35, power: 32, speed: 31, arm: 40, fielding: 38, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 27, vsLHP: 25, grit: 29, stealing: 7, running: 22, throwing: 40, recovery: 27, wRISP: 25, vsLefty: 24, poise: 27, heater: 0, agile: 25,
      abilities: ["Spray Hitter"], potential: "A-", catcherAbility: 38,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // INFIELDERS (7)
    // Jacob Krieg — 1B SR, exit velo record (118 mph), .312/.409/.393, 16.5% BB rate, top of order — TEAM POWER ELITE
    { firstName: "Jacob", lastName: "Krieg", position: "1B", eligibility: "SR", homeState: "OR", hometown: "Tigard", jerseyNumber: 8,
      hitForAvg: 70, power: 82, speed: 51, arm: 52, fielding: 59, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 75, vsLHP: 69, grit: 75, stealing: 8, running: 27, throwing: 52, recovery: 45, wRISP: 75, vsLefty: 69, poise: 75, heater: 0, agile: 35,
      abilities: ["Artist", "Consigliere", "Defensive Artisan"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // AJ Singer — 2B returner
    { firstName: "AJ", lastName: "Singer", position: "2B", eligibility: "JR", homeState: "OR", hometown: "Portland", jerseyNumber: 10,
      hitForAvg: 45, power: 36, speed: 49, arm: 36, fielding: 41, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 37, grit: 41, stealing: 21, running: 36, throwing: 37, recovery: 30, wRISP: 38, vsLefty: 36, poise: 40, heater: 0, agile: 38,
      abilities: ["Contact Hitter", "Chance Maker"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Vance — SR SS, EMU transfer, .291/13 2B/6 HR/31 RBI, "seasoned"
    { firstName: "Brendan", lastName: "Vance", position: "SS", eligibility: "SR", homeState: "MI", hometown: "Ann Arbor", jerseyNumber: 6,
      hitForAvg: 57, power: 54, speed: 60, arm: 53, fielding: 56, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 47, grit: 53, stealing: 19, running: 40, throwing: 53, recovery: 40, wRISP: 51, vsLefty: 44, poise: 53, heater: 0, agile: 50,
      abilities: ["Defensive Artisan", "Contact Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Tyler Inge — SO 3B/SS, Michigan transfer, "howitzer" arm, versatile
    { firstName: "Tyler", lastName: "Inge", position: "3B", eligibility: "SO", homeState: "MI", hometown: "Detroit", jerseyNumber: 5,
      hitForAvg: 39, power: 34, speed: 34, arm: 48, fielding: 38, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 34, vsLHP: 31, grit: 35, stealing: 14, running: 29, throwing: 48, recovery: 28, wRISP: 33, vsLefty: 31, poise: 34, heater: 0, agile: 34,
      abilities: ["High-Speed Laser", "Defensive Artisan"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // SS depth FR
    { firstName: "Caden", lastName: "Sterling", position: "SS", eligibility: "FR", homeState: "OR", hometown: "Eugene", jerseyNumber: 2,
      hitForAvg: 27, power: 22, speed: 47, arm: 34, fielding: 34, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 21, vsLHP: 20, grit: 23, stealing: 18, running: 31, throwing: 34, recovery: 24, wRISP: 20, vsLefty: 18, poise: 21, heater: 0, agile: 35,
      abilities: ["Artist", "Error Prone"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // 1B depth
    { firstName: "Austin", lastName: "Park", position: "1B", eligibility: "JR", homeState: "OR", hometown: "Beaverton", jerseyNumber: 32,
      hitForAvg: 44, power: 47, speed: 47, arm: 35, fielding: 39, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 39, vsLHP: 35, grit: 39, stealing: 6, running: 21, throwing: 35, recovery: 31, wRISP: 36, vsLefty: 33, poise: 39, heater: 0, agile: 24,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // 2B depth FR
    { firstName: "Carson", lastName: "Tyree", position: "2B", eligibility: "FR", homeState: "OR", hometown: "Hillsboro", jerseyNumber: 12,
      hitForAvg: 31, power: 27, speed: 52, arm: 34, fielding: 33, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 24, vsLHP: 23, grit: 26, stealing: 21, running: 34, throwing: 34, recovery: 24, wRISP: 23, vsLefty: 21, poise: 24, heater: 0, agile: 37,
      abilities: ["First Pitch King", "Contact Hitter", "Pressure Run"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "S",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // OUTFIELDERS (6)
    // Easton Talt — OF returner
    { firstName: "Easton", lastName: "Talt", position: "OF", eligibility: "JR", homeState: "OR", hometown: "Salem", jerseyNumber: 1,
      hitForAvg: 43, power: 40, speed: 52, arm: 38, fielding: 38, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 35, grit: 40, stealing: 18, running: 34, throwing: 38, recovery: 30, wRISP: 39, vsLefty: 34, poise: 40, heater: 0, agile: 35,
      abilities: ["Contact Hitter", "Power Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // CF
    { firstName: "Drew", lastName: "Mitchell", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Sacramento", jerseyNumber: 4,
      hitForAvg: 42, power: 36, speed: 47, arm: 40, fielding: 43, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 37, vsLHP: 35, grit: 38, stealing: 26, running: 43, throwing: 40, recovery: 31, wRISP: 36, vsLefty: 33, poise: 37, heater: 0, agile: 43,
      abilities: ["Express Baserunning"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // RF
    { firstName: "Landon", lastName: "Price", position: "OF", eligibility: "JR", homeState: "OR", hometown: "Hillsboro", jerseyNumber: 9,
      hitForAvg: 38, power: 36, speed: 41, arm: 39, fielding: 36, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 34, vsLHP: 31, grit: 35, stealing: 21, running: 33, throwing: 39, recovery: 29, wRISP: 33, vsLefty: 30, poise: 34, heater: 0, agile: 34,
      abilities: ["High-Speed Laser"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // OF depth
    { firstName: "Brady", lastName: "Kasper", position: "OF", eligibility: "SO", homeState: "WA", hometown: "Bellevue", jerseyNumber: 11,
      hitForAvg: 37, power: 33, speed: 44, arm: 34, fielding: 34, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 29, grit: 33, stealing: 18, running: 32, throwing: 36, recovery: 28, wRISP: 31, vsLefty: 28, poise: 32, heater: 0, agile: 33,
      abilities: ["Head-first Slide"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // OF depth FR
    { firstName: "Jaden", lastName: "Torres", position: "OF", eligibility: "FR", homeState: "CA", hometown: "Riverside", jerseyNumber: 26,
      hitForAvg: 29, power: 26, speed: 45, arm: 31, fielding: 28, errorResistance: 25, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 22, vsLHP: 21, grit: 24, stealing: 19, running: 32, throwing: 31, recovery: 22, wRISP: 21, vsLefty: 19, poise: 22, heater: 0, agile: 34,
      abilities: ["vs. Breaking Pitches", "Consigliere"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // OF depth FR
    { firstName: "Ethan", lastName: "Morris", position: "OF", eligibility: "SO", homeState: "OR", hometown: "Springfield", jerseyNumber: 28,
      hitForAvg: 28, power: 26, speed: 47, arm: 32, fielding: 27, errorResistance: 26, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 23, vsLHP: 22, grit: 23, stealing: 21, running: 32, throwing: 32, recovery: 23, wRISP: 22, vsLefty: 21, poise: 23, heater: 0, agile: 34,
      abilities: ["Bunt Artisan", "Defensive Artisan", "Predicament"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
  ],

  "Washington State": [
    // PITCHERS (10) — 2 FR
    { firstName: "Carter", lastName: "Baumgartner", position: "P", eligibility: "SR", homeState: "WA", hometown: "Pullman", jerseyNumber: 34,
      hitForAvg: 22, power: 18, speed: 38, arm: 71, fielding: 47, errorResistance: 61, velocity: 67, control: 68, stamina: 71, stuff: 69,
      clutch: 80, vsLHP: 75, grit: 83, stealing: 13, running: 43, throwing: 85, recovery: 63, wRISP: 63, vsLefty: 65, poise: 67, heater: 71, agile: 52,
      abilities: ["Strong Starter", "Guts", "Perfect Combustion", "Intimidator", "Inside Pitch", "Heavy Ball"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Zach", lastName: "DeVito", position: "P", eligibility: "JR", homeState: "WA", hometown: "Seattle", jerseyNumber: 29,
      hitForAvg: 9, power: 7, speed: 23, arm: 30, fielding: 21, errorResistance: 29, velocity: 30, control: 30, stamina: 30, stuff: 29,
      clutch: 38, vsLHP: 36, grit: 39, stealing: 6, running: 21, throwing: 40, recovery: 27, wRISP: 27, vsLefty: 27, poise: 29, heater: 30, agile: 27,
      abilities: ["Guts", "True Slider", "Constant Speed"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Josh", lastName: "Petersen", position: "P", eligibility: "JR", homeState: "ID", hometown: "Boise", jerseyNumber: 38,
      hitForAvg: 13, power: 9, speed: 28, arm: 40, fielding: 27, errorResistance: 38, velocity: 39, control: 37, stamina: 40, stuff: 38,
      clutch: 47, vsLHP: 46, grit: 49, stealing: 9, running: 28, throwing: 51, recovery: 35, wRISP: 35, vsLefty: 36, poise: 37, heater: 40, agile: 36,
      abilities: ["Escape Pitch", "Crossfire", "Release"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Mason", lastName: "Lund", position: "P", eligibility: "SR", homeState: "WA", hometown: "Spokane", jerseyNumber: 22,
      hitForAvg: 13, power: 10, speed: 27, arm: 36, fielding: 25, errorResistance: 36, velocity: 35, control: 36, stamina: 35, stuff: 35,
      clutch: 46, vsLHP: 45, grit: 47, stealing: 6, running: 25, throwing: 47, recovery: 33, wRISP: 33, vsLefty: 35, poise: 35, heater: 36, agile: 30,
      abilities: ["Fireman", "Constant Speed"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 5, 4, 0, 5, 0, 0]) },
    { firstName: "Blake", lastName: "Turner", position: "P", eligibility: "SO", homeState: "OR", hometown: "Portland", jerseyNumber: 40,
      hitForAvg: 16, power: 12, speed: 34, arm: 48, fielding: 34, errorResistance: 46, velocity: 47, control: 47, stamina: 48, stuff: 46,
      clutch: 55, vsLHP: 51, grit: 58, stealing: 12, running: 36, throwing: 61, recovery: 40, wRISP: 40, vsLefty: 41, poise: 43, heater: 48, agile: 44,
      abilities: ["Wild Fastball", "Tunneling", "Kageura"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Kyle", lastName: "Foster", position: "P", eligibility: "JR", homeState: "WA", hometown: "Tacoma", jerseyNumber: 42,
      hitForAvg: 6, power: 5, speed: 22, arm: 29, fielding: 20, errorResistance: 21, velocity: 28, control: 28, stamina: 29, stuff: 27,
      clutch: 26, vsLHP: 24, grit: 27, stealing: 5, running: 15, throwing: 28, recovery: 25, wRISP: 25, vsLefty: 26, poise: 27, heater: 29, agile: 19,
      abilities: ["Frozen"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Sorensen", position: "P", eligibility: "SO", homeState: "WA", hometown: "Kennewick", jerseyNumber: 44,
      hitForAvg: 11, power: 8, speed: 29, arm: 29, fielding: 19, errorResistance: 32, velocity: 33, control: 28, stamina: 29, stuff: 29,
      clutch: 38, vsLHP: 34, grit: 39, stealing: 8, running: 25, throwing: 42, recovery: 25, wRISP: 25, vsLefty: 25, poise: 26, heater: 29, agile: 29,
      abilities: ["Release", "Fighting Spirit"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    { firstName: "Braden", lastName: "Church", position: "P", eligibility: "JR", homeState: "MT", hometown: "Missoula", jerseyNumber: 46,
      hitForAvg: 10, power: 6, speed: 30, arm: 27, fielding: 18, errorResistance: 30, velocity: 30, control: 27, stamina: 27, stuff: 30,
      clutch: 37, vsLHP: 35, grit: 39, stealing: 6, running: 23, throwing: 41, recovery: 23, wRISP: 23, vsLefty: 25, poise: 26, heater: 27, agile: 30,
      abilities: ["Strong Starter"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    { firstName: "Andrew", lastName: "Watts", position: "P", eligibility: "FR", homeState: "WA", hometown: "Olympia", jerseyNumber: 48,
      hitForAvg: 8, power: 7, speed: 27, arm: 25, fielding: 14, errorResistance: 26, velocity: 28, control: 20, stamina: 19, stuff: 26,
      clutch: 26, vsLHP: 26, grit: 28, stealing: 9, running: 26, throwing: 37, recovery: 16, wRISP: 16, vsLefty: 17, poise: 16, heater: 25, agile: 31,
      abilities: ["Pace", "Precision Instrument"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 3, 3, 1, 0, 0, 0]) },
    { firstName: "Nolan", lastName: "Harper", position: "P", eligibility: "FR", homeState: "OR", hometown: "Bend", jerseyNumber: 50,
      hitForAvg: 8, power: 7, speed: 24, arm: 23, fielding: 14, errorResistance: 23, velocity: 29, control: 19, stamina: 18, stuff: 23,
      clutch: 24, vsLHP: 23, grit: 25, stealing: 8, running: 23, throwing: 34, recovery: 16, wRISP: 14, vsLefty: 16, poise: 16, heater: 23, agile: 27,
      abilities: ["Straddle"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 3, 3, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Tyler", lastName: "Grant", position: "C", eligibility: "JR", homeState: "WA", hometown: "Pasco", jerseyNumber: 14,
      hitForAvg: 77, power: 70, speed: 47, arm: 79, fielding: 76, errorResistance: 75, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 72, vsLHP: 67, grit: 75, stealing: 19, running: 44, throwing: 80, recovery: 59, wRISP: 69, vsLefty: 65, poise: 72, heater: 0, agile: 50,
      abilities: ["Good Bunt"], potential: "B", catcherAbility: 76,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Sean", lastName: "Callahan", position: "C", eligibility: "SO", homeState: "WA", hometown: "Bellevue", jerseyNumber: 18,
      hitForAvg: 35, power: 31, speed: 30, arm: 34, fielding: 33, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 31, vsLHP: 27, grit: 32, stealing: 9, running: 19, throwing: 36, recovery: 25, wRISP: 29, vsLefty: 26, poise: 31, heater: 0, agile: 23,
      abilities: ["High-Speed Laser"], potential: "B", catcherAbility: 33,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // INFIELDERS (7) — 1 FR
    { firstName: "Jack", lastName: "Mayer", position: "1B", eligibility: "SR", homeState: "WA", hometown: "Yakima", jerseyNumber: 8,
      hitForAvg: 54, power: 52, speed: 50, arm: 48, fielding: 49, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 45, grit: 50, stealing: 11, running: 31, throwing: 49, recovery: 40, wRISP: 48, vsLefty: 43, poise: 49, heater: 0, agile: 36,
      abilities: ["Power Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Derek", lastName: "Lowe", position: "2B", eligibility: "JR", homeState: "WA", hometown: "Spokane", jerseyNumber: 10,
      hitForAvg: 41, power: 32, speed: 53, arm: 35, fielding: 39, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 35, vsLHP: 33, grit: 37, stealing: 23, running: 33, throwing: 37, recovery: 30, wRISP: 35, vsLefty: 32, poise: 35, heater: 0, agile: 35,
      abilities: ["Chance Maker"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Travis", lastName: "Coleman", position: "SS", eligibility: "JR", homeState: "ID", hometown: "Meridian", jerseyNumber: 2,
      hitForAvg: 41, power: 32, speed: 57, arm: 39, fielding: 39, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 35, vsLHP: 32, grit: 37, stealing: 26, running: 35, throwing: 41, recovery: 30, wRISP: 34, vsLefty: 31, poise: 35, heater: 0, agile: 38,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Brock", lastName: "Jensen", position: "3B", eligibility: "SR", homeState: "WA", hometown: "Richland", jerseyNumber: 5,
      hitForAvg: 58, power: 55, speed: 55, arm: 55, fielding: 53, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 50, grit: 53, stealing: 21, running: 39, throwing: 58, recovery: 44, wRISP: 50, vsLefty: 48, poise: 52, heater: 0, agile: 46,
      abilities: ["Late Night Hero", "Head-first Slide", "Contact Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Adam", lastName: "Nguyen", position: "2B", eligibility: "SO", homeState: "WA", hometown: "Kent", jerseyNumber: 3,
      hitForAvg: 72, power: 57, speed: 85, arm: 67, fielding: 71, errorResistance: 67, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 63, vsLHP: 58, grit: 67, stealing: 41, running: 61, throwing: 68, recovery: 55, wRISP: 61, vsLefty: 57, poise: 63, heater: 0, agile: 67,
      abilities: ["Timely Whiff"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Cooper", lastName: "Fields", position: "1B", eligibility: "JR", homeState: "OR", hometown: "Salem", jerseyNumber: 32,
      hitForAvg: 41, power: 40, speed: 47, arm: 35, fielding: 36, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 35, vsLHP: 33, grit: 36, stealing: 6, running: 23, throwing: 36, recovery: 28, wRISP: 35, vsLefty: 32, poise: 35, heater: 0, agile: 26,
      abilities: ["Slap Happy", "Milliner"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Caleb", lastName: "Wong", position: "3B", eligibility: "FR", homeState: "WA", hometown: "Redmond", jerseyNumber: 24,
      hitForAvg: 29, power: 24, speed: 48, arm: 33, fielding: 30, errorResistance: 27, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 24, vsLHP: 23, grit: 24, stealing: 17, running: 32, throwing: 34, recovery: 23, wRISP: 23, vsLefty: 21, poise: 24, heater: 0, agile: 34,
      abilities: ["Bases Loaded Slugger"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    // OUTFIELDERS (6) — 2 FR
    { firstName: "Matt", lastName: "Holliday", position: "OF", eligibility: "SR", homeState: "WA", hometown: "Vancouver", jerseyNumber: 1,
      hitForAvg: 75, power: 72, speed: 76, arm: 68, fielding: 66, errorResistance: 65, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 68, vsLHP: 65, grit: 72, stealing: 41, running: 61, throwing: 72, recovery: 56, wRISP: 66, vsLefty: 63, poise: 68, heater: 0, agile: 65,
      abilities: ["Consigliere"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...noPitches },
    { firstName: "Luke", lastName: "Petersen", position: "OF", eligibility: "JR", homeState: "WA", hometown: "Kirkland", jerseyNumber: 4,
      hitForAvg: 40, power: 36, speed: 45, arm: 37, fielding: 36, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 35, vsLHP: 33, grit: 36, stealing: 23, running: 33, throwing: 39, recovery: 29, wRISP: 34, vsLefty: 31, poise: 35, heater: 0, agile: 35,
      abilities: ["High-Speed Laser"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Dane", lastName: "McMurray", position: "OF", eligibility: "SO", homeState: "WA", hometown: "Everett", jerseyNumber: 7,
      hitForAvg: 38, power: 33, speed: 42, arm: 36, fielding: 34, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 33, vsLHP: 30, grit: 34, stealing: 20, running: 32, throwing: 38, recovery: 28, wRISP: 32, vsLefty: 29, poise: 33, heater: 0, agile: 34,
      abilities: ["Bases Loaded King"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Grant", lastName: "Silva", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Elk Grove", jerseyNumber: 9,
      hitForAvg: 54, power: 50, speed: 56, arm: 50, fielding: 49, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 46, grit: 50, stealing: 28, running: 43, throwing: 51, recovery: 40, wRISP: 46, vsLefty: 43, poise: 49, heater: 0, agile: 46,
      abilities: ["Milliner"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Ben", lastName: "Kowalski", position: "OF", eligibility: "FR", homeState: "WA", hometown: "Tacoma", jerseyNumber: 11,
      hitForAvg: 30, power: 26, speed: 53, arm: 35, fielding: 30, errorResistance: 28, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 25, vsLHP: 23, grit: 26, stealing: 23, running: 35, throwing: 37, recovery: 23, wRISP: 23, vsLefty: 23, poise: 25, heater: 0, agile: 37,
      abilities: ["First Pitch King"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Owen", lastName: "Kline", position: "OF", eligibility: "FR", homeState: "ID", hometown: "Coeur d'Alene", jerseyNumber: 26,
      hitForAvg: 27, power: 24, speed: 49, arm: 32, fielding: 27, errorResistance: 24, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 21, vsLHP: 21, grit: 23, stealing: 20, running: 32, throwing: 33, recovery: 21, wRISP: 21, vsLefty: 20, poise: 21, heater: 0, agile: 34,
      abilities: ["Insurer"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
  ],
  ...MWC_ROSTERS,
};
