import type { RealPlayer } from "./realRosters";
import { pitchMix, noPitches } from "./pitchMixHelpers";
import { MWC_ROSTERS } from "./mwcRosters";

export const PAC12_ROSTERS: Record<string, RealPlayer[]> = {
  "Oregon State": [
    // 37-11/.771, D1B #6, NCAA Independent Yr 2, Mitch Canham Yr 7. CWS return 2025.
    // Returns 3 lineup regulars (Krieg/Singer/Talt). Lost: Arquette/Turley/Macias/Reeder/Weber to draft. Pitching is the strength.
    // PITCHERS (10) — TEAM ELITE STAFF
    // Dax Whitney — Friday SO RHP ace, 98mph FB, 17"+ sweeper 42% whiff, 3.40/120K/76.2 IP — TEAM ELITE
    { firstName: "Dax", lastName: "Whitney", position: "P", eligibility: "SO", homeState: "ID", hometown: "Boise", jerseyNumber: 22,
      hitForAvg: 16, power: 12, speed: 33, arm: 93, fielding: 61, errorResistance: 54, velocity: 97, control: 96, stamina: 96, stuff: 99,
      clutch: 85, vsLHP: 85, grit: 67, stealing: 10, running: 34, throwing: 85, recovery: 67, wRISP: 67, vsLefty: 67, poise: 67, heater: 67, agile: 44,
      abilities: ["Heavy Ball", "vs. Strong Batters", "Sharpness", "Decisive", "Strikeout"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [1, 0, 0, 0, 5, 0, 0, 1, 0, 0]) },
    // Ethan Kleinschmit — Saturday LHP JR, 3.56/113K/91 IP, JUCO transfer
    { firstName: "Ethan", lastName: "Kleinschmit", position: "P", eligibility: "JR", homeState: "NE", hometown: "Omaha", jerseyNumber: 29,
      hitForAvg: 15, power: 12, speed: 32, arm: 65, fielding: 37, errorResistance: 50, velocity: 56, control: 65, stamina: 92, stuff: 63,
      clutch: 76, vsLHP: 78, grit: 67, stealing: 9, running: 32, throwing: 76, recovery: 55, wRISP: 58, vsLefty: 63, poise: 61, heater: 63, agile: 42,
      abilities: ["Strong Starter", "Fireman", "Inside Pitch", "Good Pickoff", "Sharpness", "Full Throttle"], potential: "A", catcherAbility: null,
      throwHand: "L", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [1, 0, 0, 0, 4, 0, 0, 0, 1, 0]) },
    // Eric Segura — Sunday RHP, proven potency
    { firstName: "Eric", lastName: "Segura", position: "P", eligibility: "JR", homeState: "CA", hometown: "Riverside", jerseyNumber: 31,
      hitForAvg: 13, power: 10, speed: 32, arm: 59, fielding: 35, errorResistance: 46, velocity: 53, control: 57, stamina: 82, stuff: 57,
      clutch: 70, vsLHP: 64, grit: 67, stealing: 8, running: 30, throwing: 72, recovery: 49, wRISP: 49, vsLefty: 49, poise: 55, heater: 60, agile: 40,
      abilities: ["Strong Starter", "Fireman", "Constant Speed", "Sharpness"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...pitchMix(1, [1, 3, 0, 1, 4, 0, 0, 0, 0, 0]) },
    // Laif Palmer — RHP, top 2026 draft prospect on team
    { firstName: "Laif", lastName: "Palmer", position: "P", eligibility: "JR", homeState: "OR", hometown: "Portland", jerseyNumber: 27,
      hitForAvg: 14, power: 11, speed: 32, arm: 64, fielding: 37, errorResistance: 50, velocity: 59, control: 59, stamina: 88, stuff: 62,
      clutch: 76, vsLHP: 70, grit: 67, stealing: 9, running: 32, throwing: 76, recovery: 48, wRISP: 57, vsLefty: 56, poise: 60, heater: 65, agile: 42,
      abilities: ["Fireman", "Poker Face", "Strikeout", "Sharpness"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [1, 0, 0, 1, 4, 0, 0, 0, 0, 0]) },
    // Trey Morris — RHP, 4 wins, 5 IP CSUN
    { firstName: "Trey", lastName: "Morris", position: "P", eligibility: "JR", homeState: "CA", hometown: "San Diego", jerseyNumber: 33,
      hitForAvg: 13, power: 10, speed: 32, arm: 55, fielding: 34, errorResistance: 46, velocity: 50, control: 59, stamina: 64, stuff: 53,
      clutch: 68, vsLHP: 62, grit: 67, stealing: 8, running: 30, throwing: 68, recovery: 47, wRISP: 49, vsLefty: 49, poise: 53, heater: 55, agile: 40,
      abilities: ["Strong Starter", "Inside Pitch"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [1, 0, 0, 1, 4, 0, 0, 0, 0, 0]) },
    // James DeCremer III — RHP RP
    { firstName: "James", lastName: "DeCremer III", position: "P", eligibility: "SR", homeState: "WA", hometown: "Seattle", jerseyNumber: 38,
      hitForAvg: 13, power: 10, speed: 32, arm: 56, fielding: 32, errorResistance: 44, velocity: 52, control: 54, stamina: 42, stuff: 54,
      clutch: 70, vsLHP: 64, grit: 67, stealing: 8, running: 30, throwing: 68, recovery: 43, wRISP: 49, vsLefty: 49, poise: 54, heater: 57, agile: 40,
      abilities: ["Fireman", "Poker Face", "Good Pickoff", "Strong Finisher"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [1, 0, 0, 0, 4, 0, 0, 1, 0, 0]) },
    // Wyatt Queen — RHP RP
    { firstName: "Wyatt", lastName: "Queen", position: "P", eligibility: "JR", homeState: "OR", hometown: "Eugene", jerseyNumber: 40,
      hitForAvg: 12, power: 10, speed: 31, arm: 54, fielding: 32, errorResistance: 44, velocity: 49, control: 54, stamina: 36, stuff: 51,
      clutch: 66, vsLHP: 60, grit: 66, stealing: 8, running: 30, throwing: 66, recovery: 41, wRISP: 46, vsLefty: 46, poise: 49, heater: 55, agile: 38,
      abilities: ["Fireman", "Strong Starter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [1, 0, 3, 0, 4, 0, 0, 0, 1, 0]) },
    // Jake Pfennigs — JR RHP RP holdover
    // Sam Keller — SO RHP RP
    // Mason Pike — FR two-way SS/P, top-150 draft, up to 95mph (filed as P)
    // CATCHERS (2) — wide-open competition (Weber gone)
    { firstName: "Wilson", lastName: "Hoyt", position: "C", eligibility: "JR", homeState: "OR", hometown: "Salem", jerseyNumber: 14,
      hitForAvg: 55, power: 51, speed: 46, arm: 51, fielding: 50, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 39, running: 39, throwing: 67, recovery: 46, wRISP: 48, vsLefty: 44, poise: 50, heater: 0, agile: 36,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: 56,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    { firstName: "Maddox", lastName: "Molony", position: "C", eligibility: "FR", homeState: "OR", hometown: "Beaverton", jerseyNumber: 18,
      hitForAvg: 44, power: 39, speed: 23, arm: 22, fielding: 56, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 38, grit: 39, stealing: 38, running: 37, throwing: 56, recovery: 32, wRISP: 30, vsLefty: 28, poise: 32, heater: 0, agile: 30,
      abilities: ["Spray Hitter"], potential: "A-", catcherAbility: 44,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // INFIELDERS (7)
    // Jacob Krieg — 1B SR, exit velo record (118 mph), .312/.409/.393, 16.5% BB rate, top of order — TEAM POWER ELITE
    { firstName: "Jacob", lastName: "Krieg", position: "1B", eligibility: "SR", homeState: "OR", hometown: "Tigard", jerseyNumber: 8,
      hitForAvg: 68, power: 72, speed: 36, arm: 65, fielding: 57, errorResistance: 59, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 59, vsLHP: 60, grit: 59, stealing: 47, running: 47, throwing: 66, recovery: 48, wRISP: 80, vsLefty: 74, poise: 80, heater: 0, agile: 38,
      abilities: ["Line Drive", "Consigliere", "Defensive Artisan"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // AJ Singer — 2B returner
    { firstName: "AJ", lastName: "Singer", position: "2B", eligibility: "JR", homeState: "OR", hometown: "Portland", jerseyNumber: 10,
      hitForAvg: 63, power: 53, speed: 38, arm: 59, fielding: 62, errorResistance: 55, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 47, running: 52, throwing: 64, recovery: 44, wRISP: 56, vsLefty: 52, poise: 58, heater: 0, agile: 56,
      abilities: ["Defensive Artisan", "Chance Maker"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Vance — SR SS, EMU transfer, .291/13 2B/6 HR/31 RBI, "seasoned"
    { firstName: "Brendan", lastName: "Vance", position: "SS", eligibility: "SR", homeState: "MI", hometown: "Ann Arbor", jerseyNumber: 6,
      hitForAvg: 63, power: 61, speed: 46, arm: 64, fielding: 65, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 54, grit: 60, stealing: 47, running: 47, throwing: 67, recovery: 46, wRISP: 58, vsLefty: 52, poise: 60, heater: 0, agile: 56,
      abilities: ["Defensive Artisan", "Contact Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Tyler Inge — SO 3B/SS, Michigan transfer, "howitzer" arm, versatile
    { firstName: "Tyler", lastName: "Inge", position: "3B", eligibility: "SO", homeState: "MI", hometown: "Detroit", jerseyNumber: 5,
      hitForAvg: 61, power: 55, speed: 57, arm: 46, fielding: 41, errorResistance: 61, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 47, running: 47, throwing: 67, recovery: 44, wRISP: 52, vsLefty: 50, poise: 54, heater: 0, agile: 54,
      abilities: ["Pull Hitter", "Defensive Artisan"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // SS depth FR
    { firstName: "Caden", lastName: "Sterling", position: "SS", eligibility: "FR", homeState: "OR", hometown: "Eugene", jerseyNumber: 2,
      hitForAvg: 39, power: 31, speed: 61, arm: 47, fielding: 45, errorResistance: 23, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 39, grit: 41, stealing: 55, running: 55, throwing: 56, recovery: 33, wRISP: 27, vsLefty: 26, poise: 29, heater: 0, agile: 48,
      abilities: ["Power Hitter", "Error Prone"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // 1B depth
    { firstName: "Austin", lastName: "Park", position: "1B", eligibility: "JR", homeState: "OR", hometown: "Beaverton", jerseyNumber: 32,
      hitForAvg: 45, power: 49, speed: 54, arm: 31, fielding: 32, errorResistance: 65, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 41, grit: 37, stealing: 50, running: 44, throwing: 39, recovery: 32, wRISP: 37, vsLefty: 34, poise: 39, heater: 0, agile: 25,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // 2B depth FR
    { firstName: "Carson", lastName: "Tyree", position: "2B", eligibility: "FR", homeState: "OR", hometown: "Hillsboro", jerseyNumber: 12,
      hitForAvg: 38, power: 33, speed: 62, arm: 56, fielding: 51, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 39, vsLHP: 41, grit: 39, stealing: 55, running: 51, throwing: 53, recovery: 30, wRISP: 28, vsLefty: 26, poise: 30, heater: 0, agile: 47,
      abilities: ["Insurer", "Pressure Run"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "S",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // OUTFIELDERS (6)
    // Easton Talt — OF returner
    { firstName: "Easton", lastName: "Talt", position: "OF", eligibility: "JR", homeState: "OR", hometown: "Salem", jerseyNumber: 1,
      hitForAvg: 63, power: 59, speed: 61, arm: 43, fielding: 40, errorResistance: 63, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 54, grit: 60, stealing: 47, running: 52, throwing: 66, recovery: 46, wRISP: 58, vsLefty: 52, poise: 60, heater: 0, agile: 54,
      abilities: ["Spray Hitter", "Power Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // CF
    { firstName: "Drew", lastName: "Mitchell", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Sacramento", jerseyNumber: 4,
      hitForAvg: 59, power: 51, speed: 62, arm: 63, fielding: 65, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 47, running: 60, throwing: 66, recovery: 44, wRISP: 50, vsLefty: 46, poise: 52, heater: 0, agile: 60,
      abilities: ["Home Defense"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // RF
    { firstName: "Landon", lastName: "Price", position: "OF", eligibility: "JR", homeState: "OR", hometown: "Hillsboro", jerseyNumber: 9,
      hitForAvg: 59, power: 55, speed: 62, arm: 64, fielding: 59, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 54, stealing: 47, running: 50, throwing: 67, recovery: 44, wRISP: 50, vsLefty: 46, poise: 52, heater: 0, agile: 52,
      abilities: ["Disturbance"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // OF depth
    { firstName: "Brady", lastName: "Kasper", position: "OF", eligibility: "SO", homeState: "WA", hometown: "Bellevue", jerseyNumber: 11,
      hitForAvg: 53, power: 49, speed: 65, arm: 64, fielding: 60, errorResistance: 40, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 46, vsLHP: 50, grit: 48, stealing: 54, running: 55, throwing: 62, recovery: 40, wRISP: 44, vsLefty: 40, poise: 46, heater: 0, agile: 48,
      abilities: ["Head-first Slide"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // OF depth FR
    { firstName: "Jaden", lastName: "Torres", position: "OF", eligibility: "FR", homeState: "CA", hometown: "Riverside", jerseyNumber: 26,
      hitForAvg: 40, power: 36, speed: 62, arm: 58, fielding: 51, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 39, grit: 39, stealing: 54, running: 55, throwing: 52, recovery: 30, wRISP: 28, vsLefty: 26, poise: 30, heater: 0, agile: 46,
      abilities: ["vs. Breaking Pitches", "Consigliere"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // OF depth SO
    { firstName: "Ethan", lastName: "Morris", position: "OF", eligibility: "SO", homeState: "OR", hometown: "Springfield", jerseyNumber: 28,
      hitForAvg: 39, power: 34, speed: 63, arm: 39, fielding: 31, errorResistance: 18, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 39, vsLHP: 37, grit: 34, stealing: 53, running: 55, throwing: 52, recovery: 30, wRISP: 28, vsLefty: 26, poise: 30, heater: 0, agile: 44,
      abilities: ["Bunt Artisan", "Defensive Artisan", "Predicament"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
      { firstName: "Gunnar", lastName: "Myro", position: "P", eligibility: "JR", homeState: "OR", hometown: "Eugene", jerseyNumber: 51,
      hitForAvg: 0, power: 0, speed: 0, arm: 0, fielding: 0, errorResistance: 0, velocity: 61, control: 57, stamina: 32, stuff: 53,
      clutch: 0, vsLHP: 0, grit: 0, stealing: 0, running: 0, throwing: 0, recovery: 0, wRISP: 0, vsLefty: 0, poise: 0, heater: 0, agile: 0,
      abilities: ["Guts", "Strong Finisher"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      pitchFB: 1, pitch2S: 0, pitchSL: 1, pitchCB: 0, pitchCH: 1, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Jack", lastName: "Salmon", position: "P", eligibility: "JR", homeState: "OR", hometown: "Portland", jerseyNumber: 52,
      hitForAvg: 0, power: 0, speed: 0, arm: 0, fielding: 0, errorResistance: 0, velocity: 63, control: 56, stamina: 22, stuff: 54,
      clutch: 0, vsLHP: 0, grit: 0, stealing: 0, running: 0, throwing: 0, recovery: 0, wRISP: 0, vsLefty: 0, poise: 0, heater: 0, agile: 0,
      abilities: ["Guts", "Strong Finisher"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      pitchFB: 1, pitch2S: 0, pitchSL: 1, pitchCB: 0, pitchCH: 1, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Wade", lastName: "Meckler", position: "OF", eligibility: "SR", homeState: "OR", hometown: "Corvallis", jerseyNumber: 13,
      hitForAvg: 63, power: 42, speed: 52, arm: 33, fielding: 41, errorResistance: 59, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 56, grit: 64, stealing: 56, running: 60, throwing: 67, recovery: 52, wRISP: 60, vsLefty: 56, poise: 66, heater: 0, agile: 62,
      abilities: ["Defensive Artisan", "Batter Intimidator", "Spray Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
  ],

  "Washington State": [
    // PITCHERS (10) — 2 FR
    { firstName: "Carter", lastName: "Baumgartner", position: "P", eligibility: "SR", homeState: "WA", hometown: "Pullman", jerseyNumber: 34,
      hitForAvg: 20, power: 16, speed: 34, arm: 68, fielding: 46, errorResistance: 57, velocity: 72, control: 74, stamina: 90, stuff: 74,
      clutch: 78, vsLHP: 73, grit: 70, stealing: 11, running: 39, throwing: 80, recovery: 62, wRISP: 63, vsLefty: 64, poise: 66, heater: 70, agile: 50,
      abilities: ["Strong Starter", "Strong Finisher", "Sharpness", "Inside Pitch", "Heavy Ball"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [1, 0, 0, 0, 4, 0, 0, 1, 0, 0]) },
    { firstName: "Zach", lastName: "DeVito", position: "P", eligibility: "JR", homeState: "WA", hometown: "Seattle", jerseyNumber: 29,
      hitForAvg: 13, power: 10, speed: 32, arm: 52, fielding: 34, errorResistance: 44, velocity: 55, control: 56, stamina: 92, stuff: 54,
      clutch: 60, vsLHP: 57, grit: 60, stealing: 9, running: 29, throwing: 63, recovery: 45, wRISP: 46, vsLefty: 46, poise: 48, heater: 52, agile: 40,
      abilities: ["Guts", "True Slider", "Constant Speed"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [1, 3, 0, 0, 4, 0, 0, 0, 1, 0]) },
    { firstName: "Josh", lastName: "Petersen", position: "P", eligibility: "JR", homeState: "ID", hometown: "Boise", jerseyNumber: 38,
      hitForAvg: 14, power: 11, speed: 32, arm: 54, fielding: 36, errorResistance: 47, velocity: 57, control: 55, stamina: 95, stuff: 53,
      clutch: 62, vsLHP: 58, grit: 62, stealing: 11, running: 32, throwing: 64, recovery: 47, wRISP: 47, vsLefty: 48, poise: 50, heater: 54, agile: 44,
      abilities: ["Escape Pitch", "Crossfire", "Release"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [1, 0, 0, 1, 4, 0, 0, 0, 0, 0]) },
    { firstName: "Mason", lastName: "Lund", position: "P", eligibility: "SR", homeState: "WA", hometown: "Spokane", jerseyNumber: 22,
      hitForAvg: 15, power: 12, speed: 32, arm: 53, fielding: 35, errorResistance: 47, velocity: 54, control: 56, stamina: 84, stuff: 52,
      clutch: 62, vsLHP: 59, grit: 62, stealing: 8, running: 29, throwing: 62, recovery: 47, wRISP: 47, vsLefty: 49, poise: 49, heater: 50, agile: 40,
      abilities: ["Fireman", "Constant Speed"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [1, 0, 0, 0, 4, 0, 0, 0, 0, 0]) },
    { firstName: "Blake", lastName: "Turner", position: "P", eligibility: "SO", homeState: "OR", hometown: "Portland", jerseyNumber: 40,
      hitForAvg: 16, power: 12, speed: 33, arm: 58, fielding: 38, errorResistance: 49, velocity: 59, control: 59, stamina: 55, stuff: 57,
      clutch: 61, vsLHP: 56, grit: 62, stealing: 12, running: 36, throwing: 68, recovery: 48, wRISP: 48, vsLefty: 49, poise: 51, heater: 55, agile: 48,
      abilities: ["Wild Fastball", "Tunneling", "Kageura"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [1, 0, 0, 1, 4, 0, 0, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Sorensen", position: "P", eligibility: "SO", homeState: "WA", hometown: "Kennewick", jerseyNumber: 44,
      hitForAvg: 11, power: 8, speed: 31, arm: 42, fielding: 25, errorResistance: 38, velocity: 47, control: 43, stamina: 36, stuff: 46,
      clutch: 48, vsLHP: 44, grit: 48, stealing: 8, running: 25, throwing: 52, recovery: 32, wRISP: 33, vsLefty: 34, poise: 36, heater: 40, agile: 35,
      abilities: ["Release", "Flyball Pitcher"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [1, 0, 0, 0, 4, 0, 0, 1, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Tyler", lastName: "Grant", position: "C", eligibility: "JR", homeState: "WA", hometown: "Pasco", jerseyNumber: 14,
      hitForAvg: 72, power: 66, speed: 36, arm: 53, fielding: 63, errorResistance: 63, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 65, vsLHP: 61, grit: 66, stealing: 50, running: 50, throwing: 73, recovery: 54, wRISP: 63, vsLefty: 59, poise: 65, heater: 0, agile: 45,
      abilities: ["Good Bunt"], potential: "B", catcherAbility: 62,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Sean", lastName: "Callahan", position: "C", eligibility: "SO", homeState: "WA", hometown: "Bellevue", jerseyNumber: 18,
      hitForAvg: 56, power: 52, speed: 64, arm: 58, fielding: 52, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 53, grit: 52, stealing: 45, running: 44, throwing: 49, recovery: 38, wRISP: 42, vsLefty: 39, poise: 44, heater: 0, agile: 34,
      abilities: ["Locked and Loaded"], potential: "B", catcherAbility: 39,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // INFIELDERS (7) — 1 FR
    { firstName: "Jack", lastName: "Mayer", position: "1B", eligibility: "SR", homeState: "WA", hometown: "Yakima", jerseyNumber: 8,
      hitForAvg: 71, power: 69, speed: 43, arm: 70, fielding: 62, errorResistance: 68, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 63, stealing: 50, running: 50, throwing: 70, recovery: 52, wRISP: 62, vsLefty: 56, poise: 62, heater: 0, agile: 44,
      abilities: ["Power Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Derek", lastName: "Lowe", position: "2B", eligibility: "JR", homeState: "WA", hometown: "Spokane", jerseyNumber: 10,
      hitForAvg: 58, power: 48, speed: 65, arm: 50, fielding: 46, errorResistance: 40, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 49, grit: 48, stealing: 58, running: 57, throwing: 57, recovery: 41, wRISP: 46, vsLefty: 43, poise: 47, heater: 0, agile: 44,
      abilities: ["Chance Maker"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Travis", lastName: "Coleman", position: "SS", eligibility: "JR", homeState: "ID", hometown: "Meridian", jerseyNumber: 2,
      hitForAvg: 57, power: 47, speed: 63, arm: 53, fielding: 46, errorResistance: 41, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 53, grit: 50, stealing: 58, running: 56, throwing: 61, recovery: 42, wRISP: 46, vsLefty: 44, poise: 47, heater: 0, agile: 46,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Brock", lastName: "Jensen", position: "3B", eligibility: "SR", homeState: "WA", hometown: "Richland", jerseyNumber: 5,
      hitForAvg: 68, power: 66, speed: 40, arm: 66, fielding: 66, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 62, stealing: 50, running: 50, throwing: 73, recovery: 52, wRISP: 60, vsLefty: 56, poise: 62, heater: 0, agile: 51,
      abilities: ["Spray Hitter", "Head-first Slide", "Defensive Artisan"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Adam", lastName: "Nguyen", position: "2B", eligibility: "SO", homeState: "WA", hometown: "Kent", jerseyNumber: 3,
      hitForAvg: 69, power: 58, speed: 50, arm: 65, fielding: 66, errorResistance: 63, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 61, vsLHP: 57, grit: 62, stealing: 51, running: 56, throwing: 72, recovery: 52, wRISP: 60, vsLefty: 56, poise: 61, heater: 0, agile: 60,
      abilities: ["Timely Whiff"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Cooper", lastName: "Fields", position: "1B", eligibility: "JR", homeState: "OR", hometown: "Salem", jerseyNumber: 32,
      hitForAvg: 59, power: 56, speed: 62, arm: 54, fielding: 42, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 51, grit: 48, stealing: 57, running: 54, throwing: 50, recovery: 37, wRISP: 43, vsLefty: 40, poise: 44, heater: 0, agile: 34,
      abilities: ["Storming Home", "Milliner"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Caleb", lastName: "Wong", position: "3B", eligibility: "FR", homeState: "WA", hometown: "Redmond", jerseyNumber: 24,
      hitForAvg: 50, power: 46, speed: 61, arm: 40, fielding: 33, errorResistance: 63, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 51, grit: 51, stealing: 58, running: 57, throwing: 57, recovery: 36, wRISP: 37, vsLefty: 34, poise: 38, heater: 0, agile: 46,
      abilities: ["Bases Loaded Slugger"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    // OUTFIELDERS (6) — 2 FR
    { firstName: "Matt", lastName: "Holliday", position: "OF", eligibility: "SR", homeState: "WA", hometown: "Vancouver", jerseyNumber: 1,
      hitForAvg: 70, power: 67, speed: 68, arm: 62, fielding: 53, errorResistance: 49, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 61, grit: 66, stealing: 52, running: 56, throwing: 74, recovery: 54, wRISP: 62, vsLefty: 59, poise: 64, heater: 0, agile: 60,
      abilities: ["Consigliere"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...noPitches },
    { firstName: "Luke", lastName: "Petersen", position: "OF", eligibility: "JR", homeState: "WA", hometown: "Kirkland", jerseyNumber: 4,
      hitForAvg: 64, power: 61, speed: 61, arm: 45, fielding: 37, errorResistance: 67, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 62, grit: 59, stealing: 59, running: 56, throwing: 71, recovery: 50, wRISP: 56, vsLefty: 52, poise: 58, heater: 0, agile: 56,
      abilities: ["Disturbance"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Dane", lastName: "McMurray", position: "OF", eligibility: "SO", homeState: "WA", hometown: "Everett", jerseyNumber: 7,
      hitForAvg: 63, power: 58, speed: 65, arm: 56, fielding: 49, errorResistance: 43, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 57, vsLHP: 59, grit: 59, stealing: 58, running: 60, throwing: 72, recovery: 50, wRISP: 55, vsLefty: 52, poise: 57, heater: 0, agile: 57,
      abilities: ["Pressure Run"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Grant", lastName: "Silva", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Elk Grove", jerseyNumber: 9,
      hitForAvg: 67, power: 62, speed: 63, arm: 61, fielding: 49, errorResistance: 41, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 61, vsLHP: 57, grit: 61, stealing: 52, running: 54, throwing: 73, recovery: 52, wRISP: 58, vsLefty: 55, poise: 61, heater: 0, agile: 56,
      abilities: ["Milliner"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Ben", lastName: "Kowalski", position: "OF", eligibility: "FR", homeState: "WA", hometown: "Tacoma", jerseyNumber: 11,
      hitForAvg: 49, power: 44, speed: 47, arm: 68, fielding: 56, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 45, grit: 41, stealing: 59, running: 60, throwing: 59, recovery: 35, wRISP: 35, vsLefty: 34, poise: 37, heater: 0, agile: 49,
      abilities: ["vs. Ace"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Owen", lastName: "Kline", position: "OF", eligibility: "FR", homeState: "ID", hometown: "Coeur d'Alene", jerseyNumber: 26,
      hitForAvg: 48, power: 43, speed: 57, arm: 33, fielding: 66, errorResistance: 63, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 48, grit: 48, stealing: 58, running: 60, throwing: 58, recovery: 34, wRISP: 34, vsLefty: 33, poise: 35, heater: 0, agile: 49,
      abilities: ["Insurer"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
      { firstName: "Mikey", lastName: "Cruz Jr.", position: "P", eligibility: "JR", homeState: "WA", hometown: "Pullman", jerseyNumber: 51,
      hitForAvg: 0, power: 0, speed: 0, arm: 0, fielding: 0, errorResistance: 0, velocity: 70, control: 64, stamina: 40, stuff: 62,
      clutch: 0, vsLHP: 0, grit: 0, stealing: 0, running: 0, throwing: 0, recovery: 0, wRISP: 0, vsLefty: 0, poise: 0, heater: 0, agile: 0,
      abilities: ["Guts", "Strong Finisher"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      pitchFB: 1, pitch2S: 0, pitchSL: 1, pitchCB: 0, pitchCH: 1, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Drew", lastName: "Barragan", position: "P", eligibility: "SO", homeState: "WA", hometown: "Spokane", jerseyNumber: 52,
      hitForAvg: 0, power: 0, speed: 0, arm: 0, fielding: 0, errorResistance: 0, velocity: 70, control: 67, stamina: 38, stuff: 62,
      clutch: 0, vsLHP: 0, grit: 0, stealing: 0, running: 0, throwing: 0, recovery: 0, wRISP: 0, vsLefty: 0, poise: 0, heater: 0, agile: 0,
      abilities: ["Guts", "Strong Finisher"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      pitchFB: 1, pitch2S: 0, pitchSL: 1, pitchCB: 0, pitchCH: 1, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Gavin", lastName: "Roy", position: "P", eligibility: "FR", homeState: "WA", hometown: "Seattle", jerseyNumber: 53,
      hitForAvg: 0, power: 0, speed: 0, arm: 0, fielding: 0, errorResistance: 0, velocity: 70, control: 67, stamina: 10, stuff: 62,
      clutch: 0, vsLHP: 0, grit: 0, stealing: 0, running: 0, throwing: 0, recovery: 0, wRISP: 0, vsLefty: 0, poise: 0, heater: 0, agile: 0,
      abilities: ["Guts", "Strong Finisher"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      pitchFB: 1, pitch2S: 0, pitchSL: 1, pitchCB: 0, pitchCH: 1, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
    { firstName: "Owen", lastName: "Donahue", position: "OF", eligibility: "JR", homeState: "WA", hometown: "Spokane", jerseyNumber: 16,
      hitForAvg: 70, power: 57, speed: 66, arm: 63, fielding: 60, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 68, vsLHP: 62, grit: 70, stealing: 52, running: 60, throwing: 72, recovery: 60, wRISP: 67, vsLefty: 62, poise: 68, heater: 0, agile: 63,
      abilities: ["Spray Hitter", "Tough Out"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0, pitchFK: 0, pitchSFF: 0, pitchSHU: 0 },
  ],
  ...MWC_ROSTERS,
};
