import type { RealPlayer } from "./realRosters";
import { pitchMix, noPitches } from "./pitchMixHelpers";

export const SEC_BATCH3_ROSTERS: Record<string, RealPlayer[]> = {
  "South Carolina": [
    // PITCHERS (10)
    { firstName: "Brandon", lastName: "Stone", position: "P", eligibility: "JR", homeState: "SC", hometown: "Columbia", jerseyNumber: 33,
      hitForAvg: 13, power: 11, speed: 34, arm: 45, fielding: 29, errorResistance: 41, velocity: 50, control: 42, stamina: 46, stuff: 42,
      clutch: 57, vsLHP: 53, grit: 59, stealing: 9, running: 30, throwing: 59, recovery: 40, wRISP: 40, vsLefty: 42, poise: 42, heater: 45, agile: 37,
      abilities: ["Strong Starter", "Guts", "Tunneling"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Amp", lastName: "Phillips", position: "P", eligibility: "JR", homeState: "SC", hometown: "Spartanburg", jerseyNumber: 21,
      hitForAvg: 12, power: 9, speed: 29, arm: 40, fielding: 26, errorResistance: 37, velocity: 44, control: 39, stamina: 40, stuff: 37,
      clutch: 50, vsLHP: 47, grit: 53, stealing: 8, running: 26, throwing: 53, recovery: 35, wRISP: 35, vsLefty: 37, poise: 38, heater: 40, agile: 31,
      abilities: ["Guts", "Strong Finisher"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Jake", lastName: "McCoy", position: "P", eligibility: "JR", homeState: "SC", hometown: "Greenville", jerseyNumber: 37,
      hitForAvg: 22, power: 16, speed: 37, arm: 77, fielding: 53, errorResistance: 66, velocity: 77, control: 77, stamina: 77, stuff: 75,
      clutch: 90, vsLHP: 86, grit: 95, stealing: 13, running: 48, throwing: 91, recovery: 72, wRISP: 72, vsLefty: 77, poise: 77, heater: 79, agile: 59,
      abilities: ["Strong Starter", "Sharpness", "Cross Cannon", "Intimidator", "Heavy Ball", "Winner's Luck"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 6, 1, 0, 0, 0]) },
    { firstName: "Josh", lastName: "Gunther", position: "P", eligibility: "JR", homeState: "GA", hometown: "Marietta", jerseyNumber: 45,
      hitForAvg: 9, power: 7, speed: 27, arm: 30, fielding: 20, errorResistance: 29, velocity: 38, control: 28, stamina: 27, stuff: 27,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 7, running: 21, throwing: 42, recovery: 25, wRISP: 25, vsLefty: 27, poise: 27, heater: 30, agile: 27,
      abilities: ["Explosive Fastball"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Riley", lastName: "Goodman", position: "P", eligibility: "SO", homeState: "SC", hometown: "Charleston", jerseyNumber: 28,
      hitForAvg: 8, power: 5, speed: 24, arm: 27, fielding: 17, errorResistance: 27, velocity: 34, control: 25, stamina: 23, stuff: 24,
      clutch: 32, vsLHP: 31, grit: 36, stealing: 5, running: 20, throwing: 38, recovery: 20, wRISP: 21, vsLefty: 23, poise: 23, heater: 27, agile: 25,
      abilities: ["Natural Shuuto"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Marcus", lastName: "Hall", position: "P", eligibility: "JR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 41,
      hitForAvg: 15, power: 10, speed: 38, arm: 55, fielding: 37, errorResistance: 50, velocity: 62, control: 55, stamina: 52, stuff: 52,
      clutch: 65, vsLHP: 62, grit: 70, stealing: 10, running: 39, throwing: 71, recovery: 49, wRISP: 48, vsLefty: 52, poise: 52, heater: 55, agile: 48,
      abilities: ["Cross Cannon", "Decisive", "Crossfire", "Intimidator"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Zach", lastName: "Swanson", position: "P", eligibility: "SO", homeState: "SC", hometown: "Rock Hill", jerseyNumber: 39,
      hitForAvg: 9, power: 5, speed: 23, arm: 23, fielding: 16, errorResistance: 23, velocity: 29, control: 23, stamina: 22, stuff: 23,
      clutch: 31, vsLHP: 29, grit: 34, stealing: 5, running: 18, throwing: 35, recovery: 21, wRISP: 19, vsLefty: 22, poise: 22, heater: 23, agile: 23,
      abilities: ["Indomitable Soul", "Guts"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    { firstName: "Dylan", lastName: "Reeves", position: "P", eligibility: "JR", homeState: "GA", hometown: "Savannah", jerseyNumber: 47,
      hitForAvg: 15, power: 12, speed: 38, arm: 56, fielding: 36, errorResistance: 51, velocity: 65, control: 55, stamina: 53, stuff: 52,
      clutch: 67, vsLHP: 63, grit: 68, stealing: 12, running: 38, throwing: 73, recovery: 47, wRISP: 47, vsLefty: 52, poise: 52, heater: 56, agile: 46,
      abilities: ["Fireman", "Quick Hands", "Strong Starter", "Groundball Pitcher"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 3, 1, 0, 0, 0]) },
    { firstName: "Trevor", lastName: "Mack", position: "P", eligibility: "JR", homeState: "FL", hometown: "Jacksonville", jerseyNumber: 43,
      hitForAvg: 6, power: 6, speed: 26, arm: 22, fielding: 14, errorResistance: 25, velocity: 27, control: 22, stamina: 20, stuff: 26,
      clutch: 31, vsLHP: 29, grit: 31, stealing: 6, running: 18, throwing: 34, recovery: 18, wRISP: 18, vsLefty: 20, poise: 20, heater: 22, agile: 22,
      abilities: ["Guts"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Cole", lastName: "Jenkins", position: "P", eligibility: "JR", homeState: "SC", hometown: "Lexington", jerseyNumber: 49,
      hitForAvg: 8, power: 7, speed: 27, arm: 25, fielding: 16, errorResistance: 26, velocity: 32, control: 25, stamina: 23, stuff: 27,
      clutch: 34, vsLHP: 34, grit: 35, stealing: 7, running: 21, throwing: 39, recovery: 21, wRISP: 21, vsLefty: 22, poise: 22, heater: 25, agile: 25,
      abilities: ["Low Ball", "True Slider"], potential: "B-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Talmadge", lastName: "LeCroy", position: "C", eligibility: "SR", homeState: "SC", hometown: "Easley", jerseyNumber: 18,
      hitForAvg: 44, power: 40, speed: 31, arm: 45, fielding: 44, errorResistance: 43, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 39, grit: 45, stealing: 9, running: 22, throwing: 46, recovery: 35, wRISP: 40, vsLefty: 38, poise: 44, heater: 0, agile: 26,
      abilities: ["Contact Hitter"], potential: "B", catcherAbility: 44,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Jake", lastName: "Randolph", position: "C", eligibility: "FR", homeState: "SC", hometown: "Irmo", jerseyNumber: 24,
      hitForAvg: 37, power: 31, speed: 31, arm: 46, fielding: 39, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 30, vsLHP: 28, grit: 31, stealing: 10, running: 27, throwing: 46, recovery: 28, wRISP: 28, vsLefty: 27, poise: 30, heater: 0, agile: 30,
      abilities: ["Bases Loaded Slugger", "Emotional Pillar", "Contact Hitter"], potential: "B+", catcherAbility: 45,
      throwHand: "R", batHand: "L",
      ...noPitches },
    // INFIELDERS (5)
    { firstName: "KJ", lastName: "Scobey", position: "SS", eligibility: "SO", homeState: "GA", hometown: "Woodstock", jerseyNumber: 2,
      hitForAvg: 51, power: 48, speed: 67, arm: 52, fielding: 50, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 41, grit: 47, stealing: 30, running: 44, throwing: 53, recovery: 38, wRISP: 47, vsLefty: 40, poise: 46, heater: 0, agile: 46,
      abilities: ["Consigliere"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Beau", lastName: "Hollins", position: "1B", eligibility: "SO", homeState: "SC", hometown: "Bluffton", jerseyNumber: 14,
      hitForAvg: 79, power: 70, speed: 63, arm: 65, fielding: 67, errorResistance: 65, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 67, vsLHP: 63, grit: 70, stealing: 17, running: 43, throwing: 67, recovery: 54, wRISP: 67, vsLefty: 62, poise: 65, heater: 0, agile: 46,
      abilities: ["Contact Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Logan", lastName: "Sutter", position: "2B", eligibility: "SR", homeState: "IN", hometown: "Fishers", jerseyNumber: 6,
      hitForAvg: 43, power: 34, speed: 49, arm: 34, fielding: 35, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 34, vsLHP: 34, grit: 35, stealing: 17, running: 28, throwing: 34, recovery: 30, wRISP: 34, vsLefty: 33, poise: 34, heater: 0, agile: 30,
      abilities: ["Contact Hitter", "Chance Maker"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Dawson", lastName: "Harman", position: "3B", eligibility: "JR", homeState: "FL", hometown: "Ocala", jerseyNumber: 10,
      hitForAvg: 60, power: 54, speed: 54, arm: 53, fielding: 51, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 51, vsLHP: 48, grit: 53, stealing: 22, running: 38, throwing: 57, recovery: 42, wRISP: 51, vsLefty: 47, poise: 51, heater: 0, agile: 42,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Will", lastName: "Craddock", position: "2B", eligibility: "FR", homeState: "SC", hometown: "Summerville", jerseyNumber: 16,
      hitForAvg: 34, power: 27, speed: 54, arm: 38, fielding: 34, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 27, vsLHP: 25, grit: 29, stealing: 23, running: 38, throwing: 41, recovery: 25, wRISP: 25, vsLefty: 24, poise: 27, heater: 0, agile: 41,
      abilities: ["Emergency Strength"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Tyler", lastName: "Bak", position: "OF", eligibility: "JR", homeState: "SC", hometown: "Spartanburg", jerseyNumber: 1,
      hitForAvg: 45, power: 35, speed: 51, arm: 39, fielding: 39, errorResistance: 39, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 36, vsLHP: 35, grit: 39, stealing: 30, running: 39, throwing: 41, recovery: 31, wRISP: 35, vsLefty: 33, poise: 36, heater: 0, agile: 43,
      abilities: ["Express Baserunning"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Patrick", lastName: "Evans", position: "OF", eligibility: "JR", homeState: "SC", hometown: "Florence", jerseyNumber: 8,
      hitForAvg: 40, power: 37, speed: 42, arm: 34, fielding: 29, errorResistance: 29, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 35, vsLHP: 32, grit: 36, stealing: 15, running: 25, throwing: 35, recovery: 28, wRISP: 35, vsLefty: 31, poise: 34, heater: 0, agile: 29,
      abilities: ["Power Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Ethan", lastName: "Lizama", position: "OF", eligibility: "SR", homeState: "CA", hometown: "San Diego", jerseyNumber: 3,
      hitForAvg: 79, power: 78, speed: 72, arm: 71, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 70, vsLHP: 66, grit: 71, stealing: 28, running: 53, throwing: 73, recovery: 56, wRISP: 70, vsLefty: 64, poise: 70, heater: 0, agile: 56,
      abilities: ["Power Hitter", "High-Speed Laser"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Reese", lastName: "Moore", position: "OF", eligibility: "JR", homeState: "IA", hometown: "Iowa City", jerseyNumber: 12,
      hitForAvg: 62, power: 59, speed: 61, arm: 51, fielding: 48, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 51, grit: 57, stealing: 18, running: 39, throwing: 53, recovery: 44, wRISP: 54, vsLefty: 49, poise: 53, heater: 0, agile: 42,
      abilities: ["Consigliere"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...noPitches },
    { firstName: "Aaron", lastName: "Jamison", position: "OF", eligibility: "FR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 22,
      hitForAvg: 30, power: 26, speed: 51, arm: 33, fielding: 28, errorResistance: 26, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 23, vsLHP: 22, grit: 24, stealing: 22, running: 33, throwing: 35, recovery: 22, wRISP: 22, vsLefty: 21, poise: 23, heater: 0, agile: 36,
      abilities: ["Spirit Head", "Contact Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Caleb", lastName: "Hoover", position: "OF", eligibility: "FR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 26,
      hitForAvg: 39, power: 35, speed: 66, arm: 44, fielding: 37, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 29, vsLHP: 29, grit: 30, stealing: 29, running: 44, throwing: 47, recovery: 29, wRISP: 29, vsLefty: 26, poise: 29, heater: 0, agile: 49,
      abilities: ["Locked and Loaded", "Error Prone"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Erik", lastName: "Parker", position: "SS", eligibility: "FR", homeState: "SC", hometown: "Greer", jerseyNumber: 30,
      hitForAvg: 35, power: 29, speed: 59, arm: 40, fielding: 35, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 27, vsLHP: 27, grit: 29, stealing: 25, running: 38, throwing: 41, recovery: 27, wRISP: 27, vsLefty: 25, poise: 27, heater: 0, agile: 41,
      abilities: ["Puller Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Bryce", lastName: "Watkins", position: "2B", eligibility: "JR", homeState: "NC", hometown: "Wilmington", jerseyNumber: 32,
      hitForAvg: 38, power: 34, speed: 48, arm: 36, fielding: 35, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 34, vsLHP: 30, grit: 35, stealing: 20, running: 31, throwing: 37, recovery: 28, wRISP: 31, vsLefty: 29, poise: 34, heater: 0, agile: 35,
      abilities: ["Emotional Pillar", "Locked and Loaded", "Home Defense"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
  ],

  "Kentucky": [
    // PITCHERS (10)
    { firstName: "Jaxon", lastName: "Jelkin", position: "P", eligibility: "SR", homeState: "TX", hometown: "Houston", jerseyNumber: 34,
      hitForAvg: 22, power: 17, speed: 41, arm: 85, fielding: 53, errorResistance: 67, velocity: 84, control: 76, stamina: 74, stuff: 84,
      clutch: 92, vsLHP: 87, grit: 93, stealing: 13, running: 47, throwing: 93, recovery: 67, wRISP: 72, vsLefty: 74, poise: 76, heater: 87, agile: 57,
      abilities: ["Strong Starter", "Guts", "Bad Ball Hitter", "Release"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Ben", lastName: "Cleaver", position: "P", eligibility: "JR", homeState: "KY", hometown: "Louisville", jerseyNumber: 22,
      hitForAvg: 13, power: 10, speed: 31, arm: 46, fielding: 29, errorResistance: 41, velocity: 51, control: 46, stamina: 46, stuff: 43,
      clutch: 56, vsLHP: 55, grit: 59, stealing: 8, running: 27, throwing: 60, recovery: 42, wRISP: 42, vsLefty: 44, poise: 44, heater: 46, agile: 33,
      abilities: ["Strong Starter", "Guts", "Fighting Spirit"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 6, 1, 0, 0, 0]) },
    { firstName: "Nate", lastName: "Harris", position: "P", eligibility: "SO", homeState: "KY", hometown: "Lexington", jerseyNumber: 29,
      hitForAvg: 15, power: 11, speed: 37, arm: 57, fielding: 36, errorResistance: 49, velocity: 59, control: 54, stamina: 57, stuff: 53,
      clutch: 66, vsLHP: 65, grit: 69, stealing: 11, running: 36, throwing: 72, recovery: 49, wRISP: 49, vsLefty: 52, poise: 52, heater: 57, agile: 44,
      abilities: ["Strong Starter", "Winner's Luck", "Quick Hands"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Tommy", lastName: "Skelding", position: "P", eligibility: "SO", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 37,
      hitForAvg: 9, power: 6, speed: 28, arm: 31, fielding: 22, errorResistance: 31, velocity: 40, control: 30, stamina: 30, stuff: 29,
      clutch: 38, vsLHP: 38, grit: 42, stealing: 6, running: 22, throwing: 44, recovery: 27, wRISP: 26, vsLefty: 28, poise: 28, heater: 31, agile: 28,
      abilities: ["Fireman"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "R",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Nile", lastName: "Adcock", position: "P", eligibility: "SR", homeState: "KY", hometown: "Bowling Green", jerseyNumber: 38,
      hitForAvg: 12, power: 9, speed: 28, arm: 40, fielding: 26, errorResistance: 37, velocity: 43, control: 40, stamina: 38, stuff: 37,
      clutch: 49, vsLHP: 46, grit: 51, stealing: 7, running: 25, throwing: 52, recovery: 35, wRISP: 35, vsLefty: 36, poise: 37, heater: 40, agile: 31,
      abilities: ["Fireman", "Crossfire"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Chase", lastName: "Alderman", position: "P", eligibility: "JR", homeState: "KY", hometown: "Paducah", jerseyNumber: 42,
      hitForAvg: 8, power: 7, speed: 23, arm: 24, fielding: 15, errorResistance: 23, velocity: 30, control: 23, stamina: 23, stuff: 23,
      clutch: 32, vsLHP: 30, grit: 33, stealing: 7, running: 19, throwing: 35, recovery: 21, wRISP: 21, vsLefty: 21, poise: 22, heater: 24, agile: 22,
      abilities: ["Sharpness"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 6, 1, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Hagenow", position: "P", eligibility: "JR", homeState: "IN", hometown: "Evansville", jerseyNumber: 40,
      hitForAvg: 10, power: 7, speed: 33, arm: 27, fielding: 18, errorResistance: 31, velocity: 33, control: 26, stamina: 26, stuff: 33,
      clutch: 40, vsLHP: 38, grit: 43, stealing: 7, running: 21, throwing: 44, recovery: 23, wRISP: 23, vsLefty: 24, poise: 24, heater: 27, agile: 27,
      abilities: ["Slugger Killer", "Groundball Pitcher"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Mason", lastName: "Wright", position: "P", eligibility: "SO", homeState: "KY", hometown: "Florence", jerseyNumber: 44,
      hitForAvg: 7, power: 5, speed: 21, arm: 22, fielding: 15, errorResistance: 21, velocity: 28, control: 22, stamina: 22, stuff: 21,
      clutch: 27, vsLHP: 27, grit: 30, stealing: 6, running: 18, throwing: 33, recovery: 19, wRISP: 18, vsLefty: 20, poise: 20, heater: 22, agile: 21,
      abilities: ["Precision Instrument"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    // Brady Kirtley — FR RHP — PG HM / Top-500 national
    { firstName: "Brady", lastName: "Kirtley", position: "P", eligibility: "FR", homeState: "KY", hometown: "Owensboro", jerseyNumber: 46,
      hitForAvg: 10, power: 9, speed: 32, arm: 43, fielding: 22, errorResistance: 33, velocity: 52, control: 41, stamina: 38, stuff: 42,
      clutch: 37, vsLHP: 35, grit: 39, stealing: 11, running: 32, throwing: 52, recovery: 26, wRISP: 25, vsLefty: 27, poise: 26, heater: 36, agile: 39,
      abilities: ["Pace"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    { firstName: "Gavin", lastName: "Porter", position: "P", eligibility: "FR", homeState: "TN", hometown: "Nashville", jerseyNumber: 48,
      hitForAvg: 9, power: 8, speed: 28, arm: 33, fielding: 20, errorResistance: 30, velocity: 40, control: 27, stamina: 26, stuff: 31,
      clutch: 33, vsLHP: 31, grit: 35, stealing: 9, running: 29, throwing: 48, recovery: 23, wRISP: 22, vsLefty: 25, poise: 23, heater: 33, agile: 35,
      abilities: ["Kageura", "Strength Distribution", "Phantasmagoric"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 3, 4, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Devin", lastName: "Burkes", position: "C", eligibility: "JR", homeState: "KY", hometown: "Covington", jerseyNumber: 19,
      hitForAvg: 44, power: 41, speed: 31, arm: 45, fielding: 44, errorResistance: 43, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 41, vsLHP: 39, grit: 41, stealing: 11, running: 25, throwing: 46, recovery: 35, wRISP: 40, vsLefty: 38, poise: 41, heater: 0, agile: 28,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: 41,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Colin", lastName: "Slater", position: "C", eligibility: "FR", homeState: "OH", hometown: "Columbus", jerseyNumber: 25,
      hitForAvg: 38, power: 32, speed: 38, arm: 44, fielding: 37, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 28, vsLHP: 27, grit: 30, stealing: 11, running: 25, throwing: 45, recovery: 27, wRISP: 27, vsLefty: 25, poise: 28, heater: 0, agile: 28,
      abilities: ["Milliner"], potential: "B+", catcherAbility: 43,
      throwHand: "R", batHand: "S",
      ...noPitches },
    // INFIELDERS (5)
    { firstName: "Tyler", lastName: "Bell", position: "SS", eligibility: "SO", homeState: "KY", hometown: "Lexington", jerseyNumber: 6,
      hitForAvg: 80, power: 73, speed: 73, arm: 74, fielding: 76, errorResistance: 74, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 75, vsLHP: 75, grit: 75, stealing: 58, running: 62, throwing: 75, recovery: 62, wRISP: 75, vsLefty: 73, poise: 75, heater: 0, agile: 69,
      abilities: ["Artist", "Contact Hitter", "Push"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Luke", lastName: "Lawrence", position: "2B", eligibility: "SR", homeState: "KY", hometown: "Lexington", jerseyNumber: 6,
      hitForAvg: 39, power: 31, speed: 47, arm: 35, fielding: 37, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 34, vsLHP: 31, grit: 36, stealing: 19, running: 29, throwing: 36, recovery: 29, wRISP: 32, vsLefty: 30, poise: 35, heater: 0, agile: 31,
      abilities: ["Chance Maker"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Hudson", lastName: "Brown", position: "1B", eligibility: "JR", homeState: "KY", hometown: "Louisville", jerseyNumber: 8,
      hitForAvg: 41, power: 40, speed: 40, arm: 34, fielding: 35, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 36, vsLHP: 34, grit: 37, stealing: 9, running: 24, throwing: 35, recovery: 29, wRISP: 36, vsLefty: 33, poise: 36, heater: 0, agile: 26,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Ethan", lastName: "Hindle", position: "3B", eligibility: "JR", homeState: "OH", hometown: "Dayton", jerseyNumber: 10,
      hitForAvg: 72, power: 63, speed: 63, arm: 70, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 57, grit: 66, stealing: 27, running: 50, throwing: 72, recovery: 52, wRISP: 58, vsLefty: 56, poise: 62, heater: 0, agile: 56,
      abilities: ["Magician", "Contact Hitter", "Push"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Jake", lastName: "Newell", position: "SS", eligibility: "FR", homeState: "KY", hometown: "Richmond", jerseyNumber: 24,
      hitForAvg: 37, power: 29, speed: 62, arm: 38, fielding: 35, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 28, vsLHP: 27, grit: 30, stealing: 25, running: 37, throwing: 40, recovery: 26, wRISP: 27, vsLefty: 26, poise: 28, heater: 0, agile: 40,
      abilities: ["Two-Strike Hitter", "Push", "First Pitch King"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Ryan", lastName: "Schwartz", position: "OF", eligibility: "SO", homeState: "KY", hometown: "Lexington", jerseyNumber: 1,
      hitForAvg: 44, power: 40, speed: 47, arm: 40, fielding: 39, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 37, vsLHP: 34, grit: 39, stealing: 27, running: 36, throwing: 41, recovery: 31, wRISP: 36, vsLefty: 34, poise: 37, heater: 0, agile: 39,
      abilities: ["Express Baserunning"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Carson", lastName: "Hansen", position: "OF", eligibility: "SR", homeState: "OH", hometown: "Toledo", jerseyNumber: 9,
      hitForAvg: 57, power: 54, speed: 55, arm: 50, fielding: 46, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 50, grit: 55, stealing: 15, running: 37, throwing: 51, recovery: 43, wRISP: 52, vsLefty: 47, poise: 52, heater: 0, agile: 40,
      abilities: ["Consigliere"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "S",
      ...noPitches },
    { firstName: "Will", lastName: "Marcy", position: "OF", eligibility: "JR", homeState: "KY", hometown: "Frankfort", jerseyNumber: 7,
      hitForAvg: 52, power: 46, speed: 60, arm: 48, fielding: 47, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 41, grit: 44, stealing: 29, running: 42, throwing: 50, recovery: 38, wRISP: 42, vsLefty: 39, poise: 44, heater: 0, agile: 44,
      abilities: ["High-Speed Laser"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Bryce", lastName: "Hamilton", position: "OF", eligibility: "FR", homeState: "TN", hometown: "Knoxville", jerseyNumber: 26,
      hitForAvg: 33, power: 29, speed: 54, arm: 36, fielding: 31, errorResistance: 29, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 25, vsLHP: 24, grit: 28, stealing: 23, running: 36, throwing: 38, recovery: 24, wRISP: 24, vsLefty: 23, poise: 25, heater: 0, agile: 39,
      abilities: ["Ace Killer"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "R",
      ...noPitches },
    { firstName: "Drew", lastName: "Foster", position: "OF", eligibility: "JR", homeState: "KY", hometown: "Ashland", jerseyNumber: 11,
      hitForAvg: 38, power: 34, speed: 44, arm: 36, fielding: 33, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 30, grit: 33, stealing: 19, running: 30, throwing: 37, recovery: 27, wRISP: 31, vsLefty: 28, poise: 32, heater: 0, agile: 32,
      abilities: ["Trickster", "Contact Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Cole", lastName: "Daniels", position: "3B", eligibility: "SO", homeState: "KY", hometown: "Elizabethtown", jerseyNumber: 14,
      hitForAvg: 45, power: 39, speed: 50, arm: 41, fielding: 39, errorResistance: 39, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 36, vsLHP: 34, grit: 39, stealing: 15, running: 30, throwing: 43, recovery: 31, wRISP: 35, vsLefty: 33, poise: 36, heater: 0, agile: 33,
      abilities: ["Contact Hitter", "Outside Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Tanner", lastName: "Mills", position: "OF", eligibility: "JR", homeState: "OH", hometown: "Akron", jerseyNumber: 3,
      hitForAvg: 78, power: 71, speed: 79, arm: 76, fielding: 70, errorResistance: 70, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 67, vsLHP: 62, grit: 70, stealing: 42, running: 64, throwing: 78, recovery: 56, wRISP: 64, vsLefty: 60, poise: 67, heater: 0, agile: 70,
      abilities: ["Resilient", "Timely Whiff"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Aidan", lastName: "Cooper", position: "1B", eligibility: "SO", homeState: "KY", hometown: "Hopkinsville", jerseyNumber: 20,
      hitForAvg: 32, power: 31, speed: 40, arm: 27, fielding: 27, errorResistance: 27, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 26, vsLHP: 24, grit: 27, stealing: 6, running: 18, throwing: 29, recovery: 22, wRISP: 26, vsLefty: 24, poise: 26, heater: 0, agile: 20,
      abilities: ["Timely Whiff"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
  ],

  "Missouri": [
    // PITCHERS (10)
    { firstName: "Javyn", lastName: "Pimental", position: "P", eligibility: "SR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 33,
      hitForAvg: 21, power: 14, speed: 39, arm: 82, fielding: 51, errorResistance: 66, velocity: 82, control: 81, stamina: 79, stuff: 79,
      clutch: 84, vsLHP: 83, grit: 89, stealing: 12, running: 45, throwing: 89, recovery: 68, wRISP: 68, vsLefty: 71, poise: 71, heater: 83, agile: 56,
      abilities: ["Guts", "Indomitable Soul", "Good Pickoff", "Intimidator", "Heavy Ball"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 5, 6, 1, 0, 0, 0]) },
    { firstName: "Josh", lastName: "McDevitt", position: "P", eligibility: "JR", homeState: "MO", hometown: "St. Louis", jerseyNumber: 22,
      hitForAvg: 12, power: 8, speed: 31, arm: 43, fielding: 29, errorResistance: 41, velocity: 47, control: 42, stamina: 43, stuff: 41,
      clutch: 49, vsLHP: 48, grit: 54, stealing: 8, running: 31, throwing: 57, recovery: 37, wRISP: 36, vsLefty: 38, poise: 38, heater: 43, agile: 38,
      abilities: ["Strong Starter", "Low Ball"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Brady", lastName: "Kehlenbrink", position: "P", eligibility: "SO", homeState: "MO", hometown: "Kansas City", jerseyNumber: 37,
      hitForAvg: 18, power: 12, speed: 43, arm: 63, fielding: 43, errorResistance: 58, velocity: 73, control: 62, stamina: 62, stuff: 60,
      clutch: 71, vsLHP: 68, grit: 76, stealing: 15, running: 45, throwing: 81, recovery: 54, wRISP: 51, vsLefty: 56, poise: 56, heater: 63, agile: 56,
      abilities: ["Miracle Sharpness", "Kageura", "Intimidator"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Stokes", position: "P", eligibility: "JR", homeState: "MO", hometown: "Springfield", jerseyNumber: 29,
      hitForAvg: 15, power: 11, speed: 36, arm: 53, fielding: 36, errorResistance: 48, velocity: 58, control: 53, stamina: 53, stuff: 50,
      clutch: 62, vsLHP: 59, grit: 64, stealing: 11, running: 36, throwing: 68, recovery: 45, wRISP: 45, vsLefty: 48, poise: 48, heater: 53, agile: 44,
      abilities: ["Fireman", "Wild Fastball", "Explosive Fastball"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Noah", lastName: "Mitchell", position: "P", eligibility: "JR", homeState: "IL", hometown: "Edwardsville", jerseyNumber: 38,
      hitForAvg: 8, power: 7, speed: 27, arm: 32, fielding: 20, errorResistance: 27, velocity: 38, control: 32, stamina: 32, stuff: 27,
      clutch: 36, vsLHP: 35, grit: 38, stealing: 7, running: 22, throwing: 39, recovery: 26, wRISP: 26, vsLefty: 27, poise: 27, heater: 32, agile: 26,
      abilities: ["Walk"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Drew", lastName: "Walters", position: "P", eligibility: "SR", homeState: "MO", hometown: "Columbia", jerseyNumber: 40,
      hitForAvg: 9, power: 6, speed: 22, arm: 28, fielding: 19, errorResistance: 27, velocity: 32, control: 29, stamina: 28, stuff: 26,
      clutch: 35, vsLHP: 34, grit: 36, stealing: 6, running: 19, throwing: 36, recovery: 25, wRISP: 25, vsLefty: 26, poise: 26, heater: 28, agile: 25,
      abilities: ["Constant Speed", "Escape Pitch", "Decisive"], potential: "B-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Kraft", position: "P", eligibility: "JR", homeState: "KS", hometown: "Overland Park", jerseyNumber: 42,
      hitForAvg: 9, power: 6, speed: 27, arm: 29, fielding: 18, errorResistance: 29, velocity: 35, control: 29, stamina: 29, stuff: 26,
      clutch: 36, vsLHP: 34, grit: 38, stealing: 6, running: 23, throwing: 41, recovery: 22, wRISP: 22, vsLefty: 25, poise: 25, heater: 29, agile: 29,
      abilities: ["Slugger Killer"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    { firstName: "Cade", lastName: "Reynolds", position: "P", eligibility: "SO", homeState: "MO", hometown: "Lee's Summit", jerseyNumber: 44,
      hitForAvg: 7, power: 5, speed: 21, arm: 21, fielding: 15, errorResistance: 21, velocity: 27, control: 21, stamina: 21, stuff: 21,
      clutch: 27, vsLHP: 27, grit: 30, stealing: 5, running: 18, throwing: 32, recovery: 17, wRISP: 17, vsLefty: 19, poise: 19, heater: 21, agile: 21,
      abilities: ["Intimidator", "Cross Cannon", "Heavy Ball"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      ...pitchMix(1, [0, 3, 4, 1, 0, 0, 0]) },
    { firstName: "Landon", lastName: "Price", position: "P", eligibility: "FR", homeState: "MO", hometown: "Jefferson City", jerseyNumber: 46,
      hitForAvg: 7, power: 7, speed: 26, arm: 25, fielding: 15, errorResistance: 25, velocity: 29, control: 20, stamina: 19, stuff: 25,
      clutch: 26, vsLHP: 25, grit: 27, stealing: 9, running: 25, throwing: 38, recovery: 17, wRISP: 16, vsLefty: 17, poise: 17, heater: 25, agile: 30,
      abilities: ["Gas Tank"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 3, 4, 1, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Donaldson", position: "P", eligibility: "FR", homeState: "IL", hometown: "O'Fallon", jerseyNumber: 48,
      hitForAvg: 7, power: 6, speed: 25, arm: 37, fielding: 21, errorResistance: 23, velocity: 41, control: 29, stamina: 29, stuff: 33,
      clutch: 25, vsLHP: 23, grit: 25, stealing: 7, running: 23, throwing: 36, recovery: 25, wRISP: 23, vsLefty: 25, poise: 25, heater: 37, agile: 29,
      abilities: ["Glass Heart"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...pitchMix(1, [0, 3, 3, 1, 0, 0, 0]) },
    // CATCHERS (1)
    { firstName: "Mateo", lastName: "Serna", position: "C", eligibility: "JR", homeState: "TX", hometown: "San Antonio", jerseyNumber: 14,
      hitForAvg: 38, power: 39, speed: 25, arm: 41, fielding: 38, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 35, vsLHP: 32, grit: 38, stealing: 8, running: 22, throwing: 41, recovery: 31, wRISP: 35, vsLefty: 32, poise: 35, heater: 0, agile: 25,
      abilities: ["Outside Hitter", "Contact Hitter"], potential: "B+", catcherAbility: 38,
      throwHand: "R", batHand: "L",
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Chris", lastName: "Patterson", position: "3B", eligibility: "JR", homeState: "MO", hometown: "Blue Springs", jerseyNumber: 5,
      hitForAvg: 69, power: 64, speed: 63, arm: 72, fielding: 68, errorResistance: 67, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 61, vsLHP: 56, grit: 63, stealing: 25, running: 52, throwing: 74, recovery: 52, wRISP: 60, vsLefty: 55, poise: 61, heater: 0, agile: 56,
      abilities: ["Defensive Artisan", "Good Bunt"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Kam", lastName: "Durnin", position: "SS", eligibility: "JR", homeState: "NE", hometown: "Omaha", jerseyNumber: 2,
      hitForAvg: 35, power: 28, speed: 48, arm: 36, fielding: 35, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 28, vsLHP: 28, grit: 31, stealing: 20, running: 30, throwing: 37, recovery: 26, wRISP: 28, vsLefty: 26, poise: 30, heater: 0, agile: 32,
      abilities: ["Defensive Artisan"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Jalen", lastName: "Woita", position: "2B", eligibility: "JR", homeState: "SC", hometown: "Columbia", jerseyNumber: 10,
      hitForAvg: 41, power: 36, speed: 50, arm: 35, fielding: 34, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 34, vsLHP: 32, grit: 35, stealing: 16, running: 27, throwing: 37, recovery: 27, wRISP: 34, vsLefty: 31, poise: 34, heater: 0, agile: 31,
      abilities: ["Contact Hitter"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Peyton", lastName: "Basler", position: "1B", eligibility: "SR", homeState: "MO", hometown: "St. Charles", jerseyNumber: 18,
      hitForAvg: 53, power: 49, speed: 53, arm: 48, fielding: 48, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 41, grit: 50, stealing: 12, running: 31, throwing: 50, recovery: 38, wRISP: 44, vsLefty: 40, poise: 48, heater: 0, agile: 34,
      abilities: ["Insurer", "Artist", "Contact Hitter"], potential: "B-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Gehrig", lastName: "Goldbeck", position: "3B", eligibility: "SR", homeState: "MO", hometown: "St. Louis", jerseyNumber: 16,
      hitForAvg: 54, power: 48, speed: 50, arm: 54, fielding: 52, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 43, grit: 51, stealing: 15, running: 37, throwing: 56, recovery: 40, wRISP: 45, vsLefty: 42, poise: 48, heater: 0, agile: 40,
      abilities: ["Walkoff Hitter"], potential: "B-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Keegan", lastName: "Knutson", position: "2B", eligibility: "SR", homeState: "IA", hometown: "Des Moines", jerseyNumber: 20,
      hitForAvg: 37, power: 33, speed: 54, arm: 35, fielding: 35, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 31, vsLHP: 30, grit: 33, stealing: 15, running: 29, throwing: 36, recovery: 28, wRISP: 30, vsLefty: 29, poise: 32, heater: 0, agile: 30,
      abilities: ["Disturbance", "Heat Up"], potential: "B-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    // OUTFIELDERS (5)
    { firstName: "Kaden", lastName: "Peer", position: "OF", eligibility: "JR", homeState: "MO", hometown: "Joplin", jerseyNumber: 1,
      hitForAvg: 45, power: 38, speed: 50, arm: 41, fielding: 38, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 35, grit: 38, stealing: 24, running: 35, throwing: 43, recovery: 32, wRISP: 38, vsLefty: 33, poise: 38, heater: 0, agile: 38,
      abilities: ["Chance Maker"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Pierre", lastName: "Seals", position: "OF", eligibility: "SR", homeState: "MO", hometown: "Kansas City", jerseyNumber: 7,
      hitForAvg: 54, power: 51, speed: 58, arm: 52, fielding: 49, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 44, grit: 49, stealing: 27, running: 42, throwing: 55, recovery: 39, wRISP: 47, vsLefty: 42, poise: 48, heater: 0, agile: 47,
      abilities: ["High-Speed Laser"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Cameron", lastName: "Benson", position: "OF", eligibility: "JR", homeState: "MO", hometown: "Independence", jerseyNumber: 3,
      hitForAvg: 83, power: 74, speed: 80, arm: 75, fielding: 70, errorResistance: 68, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 72, vsLHP: 68, grit: 75, stealing: 37, running: 62, throwing: 75, recovery: 59, wRISP: 72, vsLefty: 64, poise: 72, heater: 0, agile: 68,
      abilities: ["Contact Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Owen", lastName: "Burke", position: "OF", eligibility: "FR", homeState: "MO", hometown: "Chesterfield", jerseyNumber: 26,
      hitForAvg: 34, power: 29, speed: 52, arm: 42, fielding: 34, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 28, vsLHP: 26, grit: 29, stealing: 26, running: 42, throwing: 44, recovery: 26, wRISP: 26, vsLefty: 24, poise: 28, heater: 0, agile: 45,
      abilities: ["Resilient", "Magician", "Contact Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      ...noPitches },
    { firstName: "Carter", lastName: "Fields", position: "OF", eligibility: "FR", homeState: "KS", hometown: "Wichita", jerseyNumber: 24,
      hitForAvg: 30, power: 24, speed: 51, arm: 34, fielding: 28, errorResistance: 25, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 21, vsLHP: 20, grit: 24, stealing: 20, running: 34, throwing: 35, recovery: 20, wRISP: 20, vsLefty: 19, poise: 21, heater: 0, agile: 37,
      abilities: ["Consigliere"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Marcus", lastName: "Webb", position: "1B", eligibility: "FR", homeState: "MO", hometown: "Ballwin", jerseyNumber: 30,
      hitForAvg: 34, power: 32, speed: 50, arm: 37, fielding: 32, errorResistance: 28, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 25, vsLHP: 25, grit: 27, stealing: 8, running: 25, throwing: 39, recovery: 25, wRISP: 25, vsLefty: 23, poise: 25, heater: 0, agile: 27,
      abilities: ["Good Bunt", "Unrelenting", "Contact Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Austin", lastName: "Reed", position: "C", eligibility: "SO", homeState: "MO", hometown: "Rolla", jerseyNumber: 12,
      hitForAvg: 32, power: 29, speed: 24, arm: 33, fielding: 31, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 28, vsLHP: 24, grit: 30, stealing: 6, running: 18, throwing: 35, recovery: 24, wRISP: 25, vsLefty: 24, poise: 28, heater: 0, agile: 20,
      abilities: ["Artist", "Multi-Hit"], potential: "B", catcherAbility: 31,
      throwHand: "R", batHand: "R",
      ...noPitches },
    { firstName: "Jake", lastName: "Thornton", position: "OF", eligibility: "JR", homeState: "MO", hometown: "Wentzville", jerseyNumber: 8,
      hitForAvg: 54, power: 47, speed: 56, arm: 51, fielding: 48, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 45, vsLHP: 42, grit: 47, stealing: 30, running: 45, throwing: 55, recovery: 38, wRISP: 45, vsLefty: 40, poise: 45, heater: 0, agile: 48,
      abilities: ["Tough Out", "Resilient"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "S",
      ...noPitches },
  ],

  "Oklahoma": [
      // 30-16/12-12 SEC, D1B #14, BA #9, Skip Johnson Yr 9. Team WHIP 1.28 (21st nation).
      // PITCHERS (10) — 1-8 pitch scale
      // LJ Mercurius — Friday JR RHP (UNLV transfer), 1.91 ERA / 77 K, Team USA, top-20 K nation early — TEAM ELITE STUFF
      { firstName: "LJ", lastName: "Mercurius", position: "P", eligibility: "JR", homeState: "NV", hometown: "Las Vegas", jerseyNumber: 22,
        hitForAvg: 18, power: 14, speed: 42, arm: 83, fielding: 52, errorResistance: 69, velocity: 83, control: 87, stamina: 87, stuff: 90,
        clutch: 96, vsLHP: 96, grit: 96, stealing: 13, running: 43, throwing: 96, recovery: 73, wRISP: 79, vsLefty: 83, poise: 83, heater: 87, agile: 56,
        abilities: ["Star of Victory", "Intimidator", "Sharpness", "Straddle"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...pitchMix(1, [0, 6, 7, 1, 0, 0, 0]) },
      // Cameron Johnson — Saturday LHP JR
      { firstName: "Cameron", lastName: "Johnson", position: "P", eligibility: "JR", homeState: "LA", hometown: "Baton Rouge", jerseyNumber: 33,
        hitForAvg: 15, power: 11, speed: 33, arm: 62, fielding: 38, errorResistance: 48, velocity: 64, control: 56, stamina: 57, stuff: 60,
        clutch: 71, vsLHP: 81, grit: 71, stealing: 10, running: 33, throwing: 75, recovery: 52, wRISP: 52, vsLefty: 65, poise: 56, heater: 65, agile: 43,
        abilities: ["Strong Starter", "Fireman", "Explosive Fastball", "Intimidator"], potential: "A", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [6, 0, 5, 1, 0, 0, 0]) },
      // Cord Rager — FR LHP — PG 1st Team / Top-100 national (highly regarded prep LHP)
      { firstName: "Cord", lastName: "Rager", position: "P", eligibility: "FR", homeState: "TX", hometown: "Austin", jerseyNumber: 34,
        hitForAvg: 6, power: 5, speed: 18, arm: 28, fielding: 13, errorResistance: 19, velocity: 32, control: 24, stamina: 22, stuff: 27,
        clutch: 20, vsLHP: 22, grit: 22, stealing: 5, running: 17, throwing: 31, recovery: 14, wRISP: 14, vsLefty: 16, poise: 14, heater: 23, agile: 20,
        abilities: ["Explosive Fastball"], potential: "A", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [5, 0, 5, 1, 0, 0, 0]) },
      // Jackson Cleveland — closer SR (Miami transfer), 4 SV (3rd SEC, top 25 nation), 14 K in 14.2 IP
      { firstName: "Jackson", lastName: "Cleveland", position: "P", eligibility: "SR", homeState: "FL", hometown: "Miami", jerseyNumber: 25,
        hitForAvg: 13, power: 10, speed: 32, arm: 63, fielding: 35, errorResistance: 46, velocity: 63, control: 60, stamina: 40, stuff: 60,
        clutch: 82, vsLHP: 71, grit: 77, stealing: 8, running: 32, throwing: 77, recovery: 45, wRISP: 64, vsLefty: 56, poise: 64, heater: 64, agile: 40,
        abilities: ["Fireman", "Doctor K", "Inside Pitch", "Intimidator"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 7, 0, 1, 0, 4, 0]) },
      // Jason Bodin — JR setup, 28 K in 23.1 IP, 3-1
      { firstName: "Jason", lastName: "Bodin", position: "P", eligibility: "JR", homeState: "OK", hometown: "Norman", jerseyNumber: 28,
        hitForAvg: 12, power: 9, speed: 29, arm: 49, fielding: 29, errorResistance: 40, velocity: 53, control: 49, stamina: 35, stuff: 48,
        clutch: 63, vsLHP: 58, grit: 59, stealing: 8, running: 29, throwing: 61, recovery: 39, wRISP: 44, vsLefty: 41, poise: 49, heater: 51, agile: 36,
        abilities: ["Fireman", "Doctor K", "Intimidator"], potential: "A-", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 0, 1, 0, 4, 0]) },
      // Kadyn Leon — SO middle relief (transfer), 13.1 IP / 2 R / 12 K
      { firstName: "Kadyn", lastName: "Leon", position: "P", eligibility: "FR", homeState: "TX", hometown: "El Paso", jerseyNumber: 36,
        hitForAvg: 10, power: 8, speed: 28, arm: 45, fielding: 28, errorResistance: 39, velocity: 50, control: 45, stamina: 34, stuff: 44,
        clutch: 56, vsLHP: 53, grit: 56, stealing: 8, running: 28, throwing: 58, recovery: 36, wRISP: 41, vsLefty: 39, poise: 43, heater: 46, agile: 35,
        abilities: ["Fireman", "High Spin Gyroball", "Sharpness", "Crossfire"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
      // Michael Catalano — spot starter / long relief, 6 IP at Dallas Baptist
      { firstName: "Michael", lastName: "Catalano", position: "P", eligibility: "JR", homeState: "TX", hometown: "Houston", jerseyNumber: 31,
        hitForAvg: 9, power: 7, speed: 22, arm: 34, fielding: 20, errorResistance: 29, velocity: 37, control: 34, stamina: 34, stuff: 32,
        clutch: 40, vsLHP: 37, grit: 40, stealing: 6, running: 20, throwing: 43, recovery: 30, wRISP: 28, vsLefty: 30, poise: 30, heater: 34, agile: 26,
        abilities: ["Guts", "Doctor K", "Constant Speed", "Crossfire"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
      // Reid Hensley — SR RHP veteran, 23 G/2 GS, 2.94 ERA last yr
      { firstName: "Reid", lastName: "Hensley", position: "P", eligibility: "SR", homeState: "OK", hometown: "Tulsa", jerseyNumber: 29,
        hitForAvg: 9, power: 8, speed: 22, arm: 32, fielding: 21, errorResistance: 28, velocity: 36, control: 34, stamina: 30, stuff: 29,
        clutch: 40, vsLHP: 37, grit: 41, stealing: 5, running: 18, throwing: 41, recovery: 28, wRISP: 29, vsLefty: 30, poise: 31, heater: 32, agile: 24,
        abilities: ["Guts", "Quick Hands"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
      // Mason Bixby — JR RHP RP
      { firstName: "Mason", lastName: "Bixby", position: "P", eligibility: "JR", homeState: "TX", hometown: "Fort Worth", jerseyNumber: 38,
        hitForAvg: 15, power: 13, speed: 33, arm: 59, fielding: 35, errorResistance: 48, velocity: 62, control: 59, stamina: 59, stuff: 55,
        clutch: 68, vsLHP: 64, grit: 70, stealing: 11, running: 33, throwing: 72, recovery: 49, wRISP: 49, vsLefty: 53, poise: 55, heater: 60, agile: 42,
        abilities: ["Fireman", "True Slider", "Perfect Combustion", "Guts"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
      // Jaden Barfield — SO RHP
      { firstName: "Jaden", lastName: "Barfield", position: "P", eligibility: "FR", homeState: "OK", hometown: "Norman", jerseyNumber: 37,
        hitForAvg: 8, power: 7, speed: 22, arm: 32, fielding: 20, errorResistance: 29, velocity: 35, control: 31, stamina: 31, stuff: 30,
        clutch: 37, vsLHP: 36, grit: 38, stealing: 7, running: 20, throwing: 40, recovery: 28, wRISP: 27, vsLefty: 29, poise: 29, heater: 32, agile: 26,
        abilities: ["Straddle", "Decisive"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
      // CATCHERS (2)
      // Deiten Lachance — JR C (McLennan JUCO transfer), high-power catching duo
      { firstName: "Deiten", lastName: "Lachance", position: "C", eligibility: "JR", homeState: "FL", hometown: "Orlando", jerseyNumber: 12,
        hitForAvg: 42, power: 42, speed: 24, arm: 38, fielding: 35, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 38, vsLHP: 35, grit: 38, stealing: 9, running: 20, throwing: 38, recovery: 29, wRISP: 38, vsLefty: 35, poise: 38, heater: 0, agile: 23,
        abilities: ["Power Hitter", "Consigliere"], potential: "A-", catcherAbility: 35,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Luke Hoffman — SO C backup
      { firstName: "Luke", lastName: "Hoffman", position: "C", eligibility: "FR", homeState: "OK", hometown: "Lawton", jerseyNumber: 19,
        hitForAvg: 35, power: 30, speed: 25, arm: 36, fielding: 34, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 28, vsLHP: 27, grit: 30, stealing: 7, running: 18, throwing: 36, recovery: 24, wRISP: 27, vsLefty: 25, poise: 30, heater: 0, agile: 19,
        abilities: ["Emergency Strength", "Walkoff Hitter"], potential: "B+", catcherAbility: 32,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // INFIELDERS (7)
      // Jaxon Willits — SS JR, ABCA All-Region, .302/9HR, .366/.534/.488 Cape Cod
      { firstName: "Jaxon", lastName: "Willits", position: "SS", eligibility: "JR", homeState: "OK", hometown: "Broken Arrow", jerseyNumber: 6,
        hitForAvg: 95, power: 73, speed: 80, arm: 68, fielding: 74, errorResistance: 63, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 80, vsLHP: 74, grit: 80, stealing: 41, running: 57, throwing: 68, recovery: 53, wRISP: 80, vsLefty: 74, poise: 80, heater: 0, agile: 68,
        abilities: ["High-Speed Laser", "Contact Hitter", "Defensive Artisan", "Consigliere"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Kyle Branch — 2B SO, SEC All-Frosh, started all 60 G as rookie
      { firstName: "Kyle", lastName: "Branch", position: "2B", eligibility: "SO", homeState: "OK", hometown: "Oklahoma City", jerseyNumber: 2,
        hitForAvg: 60, power: 48, speed: 62, arm: 51, fielding: 54, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 51, vsLHP: 47, grit: 52, stealing: 34, running: 47, throwing: 51, recovery: 41, wRISP: 51, vsLefty: 45, poise: 51, heater: 0, agile: 51,
        abilities: ["Defensive Artisan", "Chance Maker", "Contact Hitter"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Dayton Tockey — 1B JR, 7 HRs in 2025
      { firstName: "Dayton", lastName: "Tockey", position: "1B", eligibility: "JR", homeState: "OK", hometown: "Stillwater", jerseyNumber: 18,
        hitForAvg: 43, power: 45, speed: 38, arm: 37, fielding: 37, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 41, vsLHP: 38, grit: 41, stealing: 8, running: 24, throwing: 37, recovery: 32, wRISP: 41, vsLefty: 37, poise: 41, heater: 0, agile: 27,
        abilities: ["Power Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Camden Johnson — 3B JR (Wichita St transfer, .325 led team)
      { firstName: "Camden", lastName: "Johnson", position: "3B", eligibility: "JR", homeState: "KS", hometown: "Wichita", jerseyNumber: 10,
        hitForAvg: 48, power: 38, speed: 53, arm: 37, fielding: 36, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 40, vsLHP: 36, grit: 40, stealing: 15, running: 27, throwing: 37, recovery: 30, wRISP: 40, vsLefty: 36, poise: 40, heater: 0, agile: 29,
        abilities: ["Contact Hitter", "Power Hitter"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Brendan Brock — 1B/DH JR (SW Illinois transfer), high-power catching duo (40+ HR / 175+ RBI combined)
      { firstName: "Brendan", lastName: "Brock", position: "1B", eligibility: "JR", homeState: "OK", hometown: "Moore", jerseyNumber: 24,
        hitForAvg: 42, power: 50, speed: 36, arm: 32, fielding: 30, errorResistance: 27, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 40, vsLHP: 36, grit: 40, stealing: 8, running: 21, throwing: 34, recovery: 26, wRISP: 40, vsLefty: 35, poise: 40, heater: 0, agile: 25,
        abilities: ["Artist", "Power Hitter"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "S",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Cayden Brumbaugh — SS FR
      { firstName: "Cayden", lastName: "Brumbaugh", position: "SS", eligibility: "FR", homeState: "NE", hometown: "Lincoln", jerseyNumber: 30,
        hitForAvg: 37, power: 30, speed: 47, arm: 37, fielding: 35, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 32, vsLHP: 29, grit: 33, stealing: 22, running: 33, throwing: 39, recovery: 26, wRISP: 29, vsLefty: 26, poise: 32, heater: 0, agile: 36,
        abilities: ["Line Drive", "vs. Ace", "Defensive Artisan"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Marcus Pruitt — 2B JR utility
      { firstName: "Marcus", lastName: "Pruitt", position: "2B", eligibility: "JR", homeState: "OK", hometown: "Tulsa", jerseyNumber: 14,
        hitForAvg: 35, power: 28, speed: 52, arm: 32, fielding: 32, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 29, vsLHP: 26, grit: 29, stealing: 16, running: 26, throwing: 32, recovery: 24, wRISP: 27, vsLefty: 26, poise: 29, heater: 0, agile: 29,
        abilities: ["Hit Machine"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "S",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // OUTFIELDERS (6)
      // Trey Gambill — OF JR, 2nd SEC OBP (.519) in conf, T-7 SEC doubles
      { firstName: "Trey", lastName: "Gambill", position: "OF", eligibility: "JR", homeState: "OK", hometown: "Norman", jerseyNumber: 1,
        hitForAvg: 66, power: 45, speed: 51, arm: 40, fielding: 40, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 56, vsLHP: 51, grit: 56, stealing: 28, running: 40, throwing: 41, recovery: 33, wRISP: 56, vsLefty: 51, poise: 56, heater: 0, agile: 44,
        abilities: ["Chance Maker", "Contact Hitter", "Express Baserunning"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "S",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Jason Walk — OF JR, 15+ XBH, 100+ starts in 2025
      { firstName: "Jason", lastName: "Walk", position: "OF", eligibility: "JR", homeState: "OK", hometown: "Edmond", jerseyNumber: 7,
        hitForAvg: 45, power: 42, speed: 42, arm: 40, fielding: 40, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 40, vsLHP: 36, grit: 40, stealing: 27, running: 38, throwing: 40, recovery: 31, wRISP: 38, vsLefty: 34, poise: 40, heater: 0, agile: 40,
        abilities: ["Express Baserunning", "Power Hitter"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Drew Dickerson — OF SO
      { firstName: "Drew", lastName: "Dickerson", position: "OF", eligibility: "SO", homeState: "OK", hometown: "Tulsa", jerseyNumber: 9,
        hitForAvg: 50, power: 49, speed: 52, arm: 48, fielding: 46, errorResistance: 41, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 48, vsLHP: 41, grit: 49, stealing: 27, running: 41, throwing: 49, recovery: 37, wRISP: 48, vsLefty: 40, poise: 48, heater: 0, agile: 44,
        abilities: ["Consigliere"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Grant Ellis — OF JR
      { firstName: "Grant", lastName: "Ellis", position: "OF", eligibility: "JR", homeState: "TX", hometown: "Plano", jerseyNumber: 11,
        hitForAvg: 37, power: 33, speed: 38, arm: 36, fielding: 32, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 32, vsLHP: 30, grit: 32, stealing: 18, running: 30, throwing: 38, recovery: 27, wRISP: 31, vsLefty: 28, poise: 32, heater: 0, agile: 31,
        abilities: ["High-Speed Laser"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Tyler Owens — OF JR
      { firstName: "Tyler", lastName: "Owens", position: "OF", eligibility: "JR", homeState: "TX", hometown: "Lubbock", jerseyNumber: 3,
        hitForAvg: 38, power: 34, speed: 40, arm: 36, fielding: 34, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 34, vsLHP: 32, grit: 34, stealing: 21, running: 33, throwing: 37, recovery: 28, wRISP: 33, vsLefty: 31, poise: 34, heater: 0, agile: 34,
        abilities: ["Heavy Tank", "Contact Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Ryan Torres — OF SO
      { firstName: "Ryan", lastName: "Torres", position: "OF", eligibility: "SO", homeState: "OK", hometown: "Norman", jerseyNumber: 16,
        hitForAvg: 33, power: 30, speed: 47, arm: 31, fielding: 29, errorResistance: 28, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 26, vsLHP: 24, grit: 28, stealing: 19, running: 28, throwing: 31, recovery: 24, wRISP: 24, vsLefty: 24, poise: 26, heater: 0, agile: 29,
        abilities: ["Pull Hitter", "High-Speed Laser"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
    ],

  // Texas — 35-10 / 15-8 SEC, D1Baseball #4 (May 3, 2026), Schlossnagle Yr 2, RPI #3
  // Team ERA 1.71 (best in SEC early), 0.94 WHIP, .161 OBA. Defending SEC reg-season champ
  "Texas": [
    // PITCHERS (10) — staff: "the stuff on this staff is not fair"
    // Dylan Volantis — SO LHP, ELITE 6'6" sweeping knuckle curve, FR yr: 4-1/1.94/12 SV/74K, BA Frosh of Year, moved closer→Sun starter
    { firstName: "Dylan", lastName: "Volantis", position: "P", eligibility: "FR", homeState: "TX", hometown: "Austin", jerseyNumber: 29,
      hitForAvg: 17, power: 14, speed: 42, arm: 89, fielding: 57, errorResistance: 75, velocity: 86, control: 80, stamina: 64, stuff: 89,
      clutch: 99, vsLHP: 99, grit: 99, stealing: 10, running: 44, throwing: 99, recovery: 64, wRISP: 85, vsLefty: 84, poise: 85, heater: 85, agile: 62,
      abilities: ["Star of Victory", "Intimidator", "Sharpness", "Heavy Ball", "Winner's Luck", "Natural Shuuto"], potential: "A+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "medium",
      ...pitchMix(1, [5, 5, 7, 1, 0, 0, 0]) },
    // Ruger Riojas — Friday RHP SR, 5.61 ERA last yr (illness mid-season), bullpen vet capable of starts
    { firstName: "Ruger", lastName: "Riojas", position: "P", eligibility: "SR", homeState: "TX", hometown: "San Antonio", jerseyNumber: 34,
      hitForAvg: 14, power: 12, speed: 34, arm: 66, fielding: 40, errorResistance: 56, velocity: 67, control: 61, stamina: 61, stuff: 65,
      clutch: 77, vsLHP: 73, grit: 80, stealing: 8, running: 33, throwing: 80, recovery: 56, wRISP: 57, vsLefty: 61, poise: 63, heater: 66, agile: 44,
      abilities: ["Strong Starter", "Guts", "Bad Ball Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "tan", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    // Luke Harrison — Saturday LHP GR, 3.07 / 70.2 IP / 15 GS post-TJ, workhorse
    { firstName: "Luke", lastName: "Harrison", position: "P", eligibility: "SR", homeState: "TX", hometown: "Houston", jerseyNumber: 22,
      hitForAvg: 15, power: 11, speed: 35, arm: 65, fielding: 41, errorResistance: 56, velocity: 67, control: 70, stamina: 70, stuff: 63,
      clutch: 82, vsLHP: 93, grit: 91, stealing: 8, running: 33, throwing: 79, recovery: 65, wRISP: 60, vsLefty: 74, poise: 68, heater: 59, agile: 44,
      abilities: ["Strong Starter", "Guts", "Fireman"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [4, 4, 6, 1, 0, 0, 0]) },
    // Thomas Burns — closer JR RHP, hard-throwing
    { firstName: "Thomas", lastName: "Burns", position: "P", eligibility: "JR", homeState: "TX", hometown: "Fort Worth", jerseyNumber: 38,
      hitForAvg: 10, power: 7, speed: 27, arm: 50, fielding: 28, errorResistance: 38, velocity: 54, control: 45, stamina: 23, stuff: 48,
      clutch: 64, vsLHP: 58, grit: 59, stealing: 6, running: 25, throwing: 64, recovery: 36, wRISP: 48, vsLefty: 46, poise: 49, heater: 51, agile: 35,
      abilities: ["Fireman", "Doctor K", "Intimidator", "Low Ball", "Heavy Ball"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    // Max Grubbs — RHP SR setup, 2.84 ERA / 57 IP last yr
    { firstName: "Max", lastName: "Grubbs", position: "P", eligibility: "SR", homeState: "TX", hometown: "Frisco", jerseyNumber: 48,
      hitForAvg: 6, power: 5, speed: 19, arm: 32, fielding: 19, errorResistance: 28, velocity: 36, control: 32, stamina: 23, stuff: 31,
      clutch: 41, vsLHP: 39, grit: 43, stealing: 4, running: 17, throwing: 40, recovery: 26, wRISP: 31, vsLefty: 31, poise: 32, heater: 32, agile: 22,
      abilities: ["Fireman", "Inside Pitch", "Guts", "Monster Stuff"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    // Sam Cozart — FR RHP midweek SP, 18K in 3 GS / 5 H / 2 ER — elite freshman
    { firstName: "Sam", lastName: "Cozart", position: "P", eligibility: "FR", homeState: "TX", hometown: "Round Rock", jerseyNumber: 46,
      hitForAvg: 11, power: 9, speed: 34, arm: 65, fielding: 38, errorResistance: 53, velocity: 72, control: 62, stamina: 53, stuff: 69,
      clutch: 76, vsLHP: 71, grit: 76, stealing: 8, running: 29, throwing: 82, recovery: 53, wRISP: 62, vsLefty: 58, poise: 64, heater: 70, agile: 47,
      abilities: ["Strong Starter", "Doctor K", "Intimidator", "Sharpness"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    // Haiden Leffew — LHP transfer Wake Forest, situational
    { firstName: "Haiden", lastName: "Leffew", position: "P", eligibility: "JR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 33,
      hitForAvg: 6, power: 6, speed: 19, arm: 30, fielding: 18, errorResistance: 26, velocity: 32, control: 30, stamina: 18, stuff: 28,
      clutch: 35, vsLHP: 42, grit: 37, stealing: 4, running: 17, throwing: 38, recovery: 23, wRISP: 26, vsLefty: 32, poise: 28, heater: 28, agile: 23,
      abilities: ["Fireman", "Crossfire"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    // Ethan Walker — LHP sidearm, late-season key in 2025 (SEC tourney start, NCAA opener)
    { firstName: "Ethan", lastName: "Walker", position: "P", eligibility: "JR", homeState: "TX", hometown: "Austin", jerseyNumber: 37,
      hitForAvg: 8, power: 6, speed: 23, arm: 32, fielding: 20, errorResistance: 31, velocity: 34, control: 33, stamina: 18, stuff: 32,
      clutch: 43, vsLHP: 52, grit: 43, stealing: 5, running: 18, throwing: 43, recovery: 24, wRISP: 29, vsLefty: 37, poise: 32, heater: 29, agile: 27,
      abilities: ["Fireman", "Inside Pitch"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      skinTone: "light", hairColor: "blonde", hairStyle: "short",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    // Kade Bing — LHP RP strike-thrower
    { firstName: "Kade", lastName: "Bing", position: "P", eligibility: "JR", homeState: "TX", hometown: "Lubbock", jerseyNumber: 42,
      hitForAvg: 7, power: 5, speed: 20, arm: 26, fielding: 16, errorResistance: 25, velocity: 30, control: 32, stamina: 16, stuff: 24,
      clutch: 34, vsLHP: 40, grit: 37, stealing: 3, running: 15, throwing: 34, recovery: 20, wRISP: 24, vsLefty: 31, poise: 26, heater: 26, agile: 23,
      abilities: ["Inside Pitch", "Good Pickoff"], potential: "B", catcherAbility: null,
      throwHand: "L", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    // Cal Higgins — RHP transfer
    { firstName: "Cal", lastName: "Higgins", position: "P", eligibility: "SR", homeState: "TX", hometown: "Houston", jerseyNumber: 40,
      hitForAvg: 8, power: 5, speed: 22, arm: 30, fielding: 19, errorResistance: 27, velocity: 34, control: 30, stamina: 18, stuff: 27,
      clutch: 34, vsLHP: 33, grit: 36, stealing: 4, running: 18, throwing: 40, recovery: 22, wRISP: 23, vsLefty: 24, poise: 25, heater: 30, agile: 23,
      abilities: ["Crossfire"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    // CATCHERS (2)
    // Carson Tinney — JR C transfer Notre Dame, 14 HR (#2 team), 2025 Buster Posey finalist, 445-ft HR
    { firstName: "Carson", lastName: "Tinney", position: "C", eligibility: "JR", homeState: "IN", hometown: "South Bend", jerseyNumber: 19,
      hitForAvg: 65, power: 76, speed: 31, arm: 58, fielding: 60, errorResistance: 57, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 61, grit: 64, stealing: 7, running: 25, throwing: 60, recovery: 48, wRISP: 66, vsLefty: 61, poise: 64, heater: 0, agile: 33,
      abilities: ["Power Hitter", "Consigliere", "High-Speed Laser"], potential: "A", catcherAbility: 60,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Chase Porter — SO backup C
    { firstName: "Chase", lastName: "Porter", position: "C", eligibility: "FR", homeState: "TX", hometown: "Cypress", jerseyNumber: 16,
      hitForAvg: 31, power: 28, speed: 25, arm: 36, fielding: 33, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 25, vsLHP: 24, grit: 26, stealing: 6, running: 18, throwing: 36, recovery: 23, wRISP: 24, vsLefty: 23, poise: 25, heater: 0, agile: 22,
      abilities: ["Artist", "Unpredictable", "Good Bunt"], potential: "B+", catcherAbility: 33,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // INFIELDERS (6)
    // Casey Borba — JR 1B, .278/12HR 2025, multi-HR effort early '26, 5 RBI vs TXST
    { firstName: "Casey", lastName: "Borba", position: "1B", eligibility: "JR", homeState: "CA", hometown: "Sacramento", jerseyNumber: 45,
      hitForAvg: 46, power: 57, speed: 36, arm: 32, fielding: 38, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 41, grit: 44, stealing: 6, running: 20, throwing: 32, recovery: 32, wRISP: 46, vsLefty: 40, poise: 43, heater: 0, agile: 24,
      abilities: ["Power Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "S",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Ethan Mendoza — SO 2B, .333 in 2025 team-leader, returning star, +15 lbs offseason
    { firstName: "Ethan", lastName: "Mendoza", position: "2B", eligibility: "SO", homeState: "TX", hometown: "El Paso", jerseyNumber: 2,
      hitForAvg: 58, power: 44, speed: 49, arm: 40, fielding: 49, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 47, grit: 53, stealing: 20, running: 35, throwing: 41, recovery: 40, wRISP: 52, vsLefty: 45, poise: 50, heater: 0, agile: 40,
      abilities: ["Hit Machine", "Contact Hitter", "Chance Maker", "Defensive Artisan"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Adrian Rodriguez — SO SS (moved from util), 2 HR/9 RBI, 2025 Frosh All-American, hand injury
    { firstName: "Adrian", lastName: "Rodriguez", position: "SS", eligibility: "SO", homeState: "TX", hometown: "Flower Mound", jerseyNumber: 6,
      hitForAvg: 59, power: 48, speed: 54, arm: 48, fielding: 55, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 54, stealing: 23, running: 43, throwing: 50, recovery: 38, wRISP: 48, vsLefty: 44, poise: 50, heater: 0, agile: 48,
      abilities: ["Defensive Artisan", "Contact Hitter", "Express Baserunning"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Temo Becerra — JR 3B Stanford transfer, .314 career, 115 starts
    { firstName: "Temo", lastName: "Becerra", position: "3B", eligibility: "JR", homeState: "CA", hometown: "San Jose", jerseyNumber: 10,
      hitForAvg: 62, power: 53, speed: 44, arm: 53, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 50, grit: 55, stealing: 13, running: 35, throwing: 53, recovery: 41, wRISP: 53, vsLefty: 47, poise: 53, heater: 0, agile: 36,
      abilities: ["Contact Hitter", "Defensive Artisan", "Inside Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Josh Livingston — JR Wichita State transfer, 15 HR last year (team-leading), DH/util
    { firstName: "Josh", lastName: "Livingston", position: "3B", eligibility: "JR", homeState: "KS", hometown: "Wichita", jerseyNumber: 20,
      hitForAvg: 39, power: 53, speed: 34, arm: 31, fielding: 31, errorResistance: 28, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 37, vsLHP: 34, grit: 40, stealing: 5, running: 18, throwing: 31, recovery: 28, wRISP: 37, vsLefty: 34, poise: 35, heater: 0, agile: 22,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Callum Early — FR INF Liberty transfer, depth
    { firstName: "Callum", lastName: "Early", position: "2B", eligibility: "FR", homeState: "TX", hometown: "Plano", jerseyNumber: 24,
      hitForAvg: 33, power: 27, speed: 50, arm: 35, fielding: 34, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 26, vsLHP: 25, grit: 27, stealing: 19, running: 34, throwing: 35, recovery: 25, wRISP: 25, vsLefty: 24, poise: 26, heater: 0, agile: 36,
      abilities: ["High Ball Hitter", "Chance Maker"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // OUTFIELDERS (7)
    // Aiden Robbins — JR CF/OF Seton Hall transfer, .358/17HR (TEAM LEADER), 200th career hit, 112mph max EV, top-50 draft
    { firstName: "Aiden", lastName: "Robbins", position: "OF", eligibility: "JR", homeState: "NJ", hometown: "South Orange", jerseyNumber: 1,
      hitForAvg: 79, power: 79, speed: 55, arm: 56, fielding: 56, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 75, vsLHP: 70, grit: 70, stealing: 17, running: 43, throwing: 58, recovery: 49, wRISP: 75, vsLefty: 70, poise: 73, heater: 0, agile: 49,
      abilities: ["Artist", "Power Hitter", "Consigliere"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "S",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Jonah Williams — SO OF, speed/leadoff
    { firstName: "Jonah", lastName: "Williams", position: "OF", eligibility: "SO", homeState: "TX", hometown: "Austin", jerseyNumber: 7,
      hitForAvg: 38, power: 31, speed: 41, arm: 35, fielding: 37, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 33, vsLHP: 29, grit: 35, stealing: 35, running: 43, throwing: 37, recovery: 28, wRISP: 30, vsLefty: 28, poise: 33, heater: 0, agile: 46,
      abilities: ["Express Baserunning", "Chance Maker"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Ashton Larson — JR OF LSU transfer
    { firstName: "Ashton", lastName: "Larson", position: "OF", eligibility: "JR", homeState: "LA", hometown: "Baton Rouge", jerseyNumber: 9,
      hitForAvg: 45, power: 38, speed: 44, arm: 38, fielding: 38, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 34, grit: 40, stealing: 18, running: 34, throwing: 38, recovery: 31, wRISP: 38, vsLefty: 34, poise: 38, heater: 0, agile: 35,
      abilities: ["Contact Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Jack Moroknek — JR OF Butler transfer, replacing Belyeu in RF
    { firstName: "Jack", lastName: "Moroknek", position: "OF", eligibility: "JR", homeState: "IN", hometown: "Indianapolis", jerseyNumber: 23,
      hitForAvg: 42, power: 39, speed: 38, arm: 35, fielding: 35, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 35, grit: 38, stealing: 11, running: 30, throwing: 35, recovery: 30, wRISP: 38, vsLefty: 34, poise: 38, heater: 0, agile: 30,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "L", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Dariyan Pendergrass — JR OF Charleston transfer, speed
    { firstName: "Dariyan", lastName: "Pendergrass", position: "OF", eligibility: "JR", homeState: "SC", hometown: "Charleston", jerseyNumber: 3,
      hitForAvg: 37, power: 30, speed: 47, arm: 35, fielding: 35, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 31, vsLHP: 28, grit: 32, stealing: 35, running: 46, throwing: 35, recovery: 28, wRISP: 29, vsLefty: 28, poise: 31, heater: 0, agile: 49,
      abilities: ["Express Baserunning"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "deep", hairColor: "black", hairStyle: "fade",
      ...noPitches },
    // Anthony Pack Jr — FR OF speed
    { firstName: "Anthony", lastName: "Pack Jr", position: "OF", eligibility: "FR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 26,
      hitForAvg: 38, power: 31, speed: 45, arm: 32, fielding: 31, errorResistance: 29, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 31, grit: 33, stealing: 33, running: 42, throwing: 33, recovery: 26, wRISP: 31, vsLefty: 29, poise: 32, heater: 0, agile: 43,
      abilities: ["Express Baserunning", "Consigliere", "Contact Hitter"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "deep", hairColor: "black", hairStyle: "fade",
      ...noPitches },
    // Miles Bennett — JR OF depth, cannon arm
    { firstName: "Miles", lastName: "Bennett", position: "2B", eligibility: "JR", homeState: "TX", hometown: "The Woodlands", jerseyNumber: 11,
      hitForAvg: 30, power: 26, speed: 38, arm: 34, fielding: 28, errorResistance: 27, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 25, vsLHP: 23, grit: 27, stealing: 13, running: 24, throwing: 34, recovery: 22, wRISP: 24, vsLefty: 22, poise: 25, heater: 0, agile: 27,
      abilities: ["High-Speed Laser"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
  ],
};
