import type { RealPlayer } from "./realRosters";
import { pitchMix, noPitches } from "./pitchMixHelpers";

export const SEC_BATCH1_ROSTERS: Record<string, RealPlayer[]> = {
  "LSU": [
    // PITCHERS (11) — based on real 2026 mid-season ERAs from lsusports.net
    // Casan Evans — Friday SP, 95-99mph, 5.47 ERA but 13.0 K/9, arm discomfort
    { firstName: "Casan", lastName: "Evans", position: "P", eligibility: "JR", homeState: "LA", hometown: "Baton Rouge", jerseyNumber: 20,
      hitForAvg: 14, power: 11, speed: 38, arm: 62, fielding: 40, errorResistance: 55, velocity: 71, control: 46, stamina: 57, stuff: 64,
      clutch: 56, vsLHP: 70, grit: 55, stealing: 8, running: 32, throwing: 76, recovery: 49, wRISP: 48, vsLefty: 56, poise: 51, heater: 60, agile: 52,
      abilities: ["Doctor K", "Walk", "Bad Ball Hitter", "Intimidator", "Winner's Luck"], potential: "A-", catcherAbility: null,
      skinTone: "dark", hairColor: "black", hairStyle: "short",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 4]) },
    // Cooper Moore — Saturday SP, Kansas transfer, 3.38 ERA, plus command (39K/7BB)
    { firstName: "Cooper", lastName: "Moore", position: "P", eligibility: "SR", homeState: "KS", hometown: "Lawrence", jerseyNumber: 22,
      hitForAvg: 16, power: 12, speed: 35, arm: 56, fielding: 42, errorResistance: 56, velocity: 64, control: 67, stamina: 59, stuff: 60,
      clutch: 72, vsLHP: 70, grit: 78, stealing: 8, running: 30, throwing: 70, recovery: 55, wRISP: 60, vsLefty: 56, poise: 63, heater: 56, agile: 50,
      abilities: ["Inside Pitch", "Strong Starter", "Guts", "Grit", "Intimidator"], potential: "A-", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    // William Schmidt — Sunday SP, 4.22 ERA / 64 IP / 85 K — workhorse w/ command issues
    { firstName: "William", lastName: "Schmidt", position: "P", eligibility: "JR", homeState: "LA", hometown: "Mandeville", jerseyNumber: 9,
      hitForAvg: 14, power: 11, speed: 33, arm: 57, fielding: 38, errorResistance: 50, velocity: 61, control: 47, stamina: 61, stuff: 57,
      clutch: 60, vsLHP: 64, grit: 60, stealing: 6, running: 28, throwing: 70, recovery: 51, wRISP: 49, vsLefty: 50, poise: 50, heater: 55, agile: 45,
      abilities: ["Guts", "Strong Starter", "Walk", "Natural Shuuto"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    // Zac Cowan — swing role, 3.63 ERA, 4 GS, 11.4 K/9 — high-leverage long man
    { firstName: "Zac", lastName: "Cowan", position: "P", eligibility: "JR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 26,
      hitForAvg: 13, power: 10, speed: 32, arm: 48, fielding: 35, errorResistance: 48, velocity: 55, control: 54, stamina: 46, stuff: 56,
      clutch: 65, vsLHP: 64, grit: 67, stealing: 6, running: 28, throwing: 60, recovery: 46, wRISP: 53, vsLefty: 50, poise: 50, heater: 46, agile: 42,
      abilities: ["Strong Starter", "Winner's Luck", "Strikeout", "Fighting Spirit"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 5, 3, 1, 0, 0, 0]) },
    // Deven Sheerin — closer-type, 4.01 ERA, 4 SV, 13.6 K/9, upper-90s post-ACL
    { firstName: "Deven", lastName: "Sheerin", position: "P", eligibility: "FR", homeState: "FL", hometown: "Orlando", jerseyNumber: 45,
      hitForAvg: 11, power: 8, speed: 36, arm: 61, fielding: 32, errorResistance: 45, velocity: 67, control: 42, stamina: 29, stuff: 60,
      clutch: 70, vsLHP: 68, grit: 64, stealing: 7, running: 32, throwing: 76, recovery: 38, wRISP: 49, vsLefty: 52, poise: 54, heater: 55, agile: 50,
      abilities: ["Fireman", "Doctor K", "Intimidator", "Crossfire"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 5, 0, 1, 0, 0, 0]) },
    // Grant Fontenot — setup/closer, 5th-yr, 3.71 ERA, 3 SV
    { firstName: "Grant", lastName: "Fontenot", position: "P", eligibility: "SR", homeState: "LA", hometown: "Lafayette", jerseyNumber: 40,
      hitForAvg: 14, power: 10, speed: 30, arm: 48, fielding: 36, errorResistance: 50, velocity: 54, control: 42, stamina: 29, stuff: 53,
      clutch: 70, vsLHP: 65, grit: 67, stealing: 5, running: 26, throwing: 64, recovery: 41, wRISP: 49, vsLefty: 49, poise: 53, heater: 48, agile: 45,
      abilities: ["Fireman", "Guts", "Flyball Pitcher", "Wizard Mode"], potential: "B", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    // Mavrick Rizy — high-leverage RP, 3.86 ERA, dominant Cape Cod
    { firstName: "Mavrick", lastName: "Rizy", position: "P", eligibility: "FR", homeState: "MA", hometown: "Boston", jerseyNumber: 17,
      hitForAvg: 10, power: 8, speed: 35, arm: 51, fielding: 31, errorResistance: 45, velocity: 56, control: 37, stamina: 24, stuff: 54,
      clutch: 62, vsLHP: 62, grit: 60, stealing: 6, running: 30, throwing: 66, recovery: 37, wRISP: 45, vsLefty: 46, poise: 46, heater: 48, agile: 48,
      abilities: ["Fireman", "Walk"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 5, 0, 1, 0, 0, 0]) },
    // Santiago Garcia — LHP high-leverage, 4.98 ERA, 2 SV, 14.1 K/9
    { firstName: "Santiago", lastName: "Garcia", position: "P", eligibility: "JR", homeState: "FL", hometown: "Miami", jerseyNumber: 34,
      hitForAvg: 12, power: 10, speed: 32, arm: 47, fielding: 31, errorResistance: 44, velocity: 50, control: 35, stamina: 24, stuff: 53,
      clutch: 60, vsLHP: 75, grit: 56, stealing: 6, running: 28, throwing: 62, recovery: 37, wRISP: 43, vsLefty: 55, poise: 44, heater: 44, agile: 45,
      abilities: ["Fireman", "Walk", "Gyroball"], potential: "B", catcherAbility: null,
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...pitchMix(1, [0, 5, 3, 1, 0, 0, 0]) },
    // Danny Lachenmayer — LHP RP, 4.72 ERA, 14.9 K/9 in small sample
    { firstName: "Danny", lastName: "Lachenmayer", position: "P", eligibility: "FR", homeState: "TX", hometown: "Houston", jerseyNumber: 28,
      hitForAvg: 10, power: 7, speed: 30, arm: 44, fielding: 29, errorResistance: 42, velocity: 48, control: 38, stamina: 20, stuff: 49,
      clutch: 56, vsLHP: 70, grit: 54, stealing: 5, running: 26, throwing: 58, recovery: 35, wRISP: 40, vsLefty: 51, poise: 41, heater: 42, agile: 44,
      abilities: ["Fireman"], potential: "B", catcherAbility: null,
      skinTone: "light", hairColor: "blonde", hairStyle: "short",
      ...pitchMix(1, [0, 4, 0, 1, 0, 0, 0]) },
    // Ethan Plog — LHP, JUCO transfer (Iowa Western), unique slot
    { firstName: "Ethan", lastName: "Plog", position: "P", eligibility: "FR", homeState: "WI", hometown: "Green Bay", jerseyNumber: 38,
      hitForAvg: 10, power: 7, speed: 28, arm: 40, fielding: 29, errorResistance: 42, velocity: 42, control: 40, stamina: 21, stuff: 43,
      clutch: 52, vsLHP: 64, grit: 54, stealing: 5, running: 24, throwing: 54, recovery: 33, wRISP: 37, vsLefty: 46, poise: 38, heater: 37, agile: 42,
      abilities: ["Fireman"], potential: "B-", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [3, 4, 0, 1, 0, 0, 0]) },
    // Zion Theophilus — Freshman RHP, 4.91 ERA, depth arm
    { firstName: "Zion", lastName: "Theophilus", position: "2B", eligibility: "FR", homeState: "FL", hometown: "Miami", jerseyNumber: 52,
      hitForAvg: 38, power: 30, speed: 30, arm: 60, fielding: 38, errorResistance: 40, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 50, grit: 48, stealing: 5, running: 26, throwing: 58, recovery: 44, wRISP: 48, vsLefty: 50, poise: 48, heater: 0, agile: 44,
      abilities: ["Error Prone"], potential: "B+", catcherAbility: null,
      skinTone: "deep", hairColor: "black", hairStyle: "fade",
      ...noPitches },
    // CATCHERS (2)
    // Cade Arrambide — .331 / 16 HR / 43 RBI / .675 SLG — elite power-hitting C
    { firstName: "Cade", lastName: "Arrambide", position: "C", eligibility: "JR", homeState: "TX", hometown: "Boerne", jerseyNumber: 9,
      hitForAvg: 78, power: 86, speed: 26, arm: 75, fielding: 76, errorResistance: 74, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 78, vsLHP: 75, grit: 75, stealing: 8, running: 24, throwing: 78, recovery: 65, wRISP: 78, vsLefty: 75, poise: 78, heater: 0, agile: 32,
      abilities: ["Power Hitter", "Defensive Artisan", "Consigliere", "High-Speed Laser"], potential: "A", catcherAbility: 76,
      skinTone: "tan", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Omar Serna Jr — .319 / 8 HR / 35 RBI — strong backup C
    { firstName: "Omar", lastName: "Serna", position: "C", eligibility: "SO", homeState: "TX", hometown: "San Antonio", jerseyNumber: 25,
      hitForAvg: 70, power: 65, speed: 25, arm: 65, fielding: 68, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 65, vsLHP: 60, grit: 70, stealing: 7, running: 23, throwing: 68, recovery: 56, wRISP: 65, vsLefty: 60, poise: 64, heater: 0, agile: 30,
      abilities: ["Defensive Artisan", "High-Speed Laser"], potential: "A-", catcherAbility: 70,
      skinTone: "medium", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // INFIELDERS (5)
    // Steven Milam — SS, .290 / 7 HR / 39 RBI, switch hitter, Brooks Wallace semifinalist
    { firstName: "Steven", lastName: "Milam", position: "SS", eligibility: "SR", homeState: "TX", hometown: "Allen", jerseyNumber: 4,
      hitForAvg: 70, power: 56, speed: 50, arm: 64, fielding: 78, errorResistance: 76, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 72, vsLHP: 68, grit: 75, stealing: 35, running: 50, throwing: 72, recovery: 60, wRISP: 70, vsLefty: 68, poise: 72, heater: 0, agile: 70,
      abilities: ["vs. Breaking Pitches", "Defensive Artisan", "Contact Hitter", "Consigliere"], potential: "A", catcherAbility: null,
      skinTone: "medium", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Brayden Simpson — 2B depth/utility, limited PT
    { firstName: "Brayden", lastName: "Simpson", position: "2B", eligibility: "SR", homeState: "LA", hometown: "Baton Rouge", jerseyNumber: 10,
      hitForAvg: 38, power: 32, speed: 42, arm: 42, fielding: 56, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 38, grit: 50, stealing: 22, running: 40, throwing: 44, recovery: 38, wRISP: 40, vsLefty: 40, poise: 44, heater: 0, agile: 50,
      abilities: ["Defensive Artisan"], potential: "B", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Zach Yorke — 1B, .229 / 6 HR / .417 OBP — patient power bat, struggling avg
    { firstName: "Zach", lastName: "Yorke", position: "1B", eligibility: "SR", homeState: "AZ", hometown: "Phoenix", jerseyNumber: 33,
      hitForAvg: 50, power: 60, speed: 28, arm: 44, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 56, grit: 76, stealing: 12, running: 30, throwing: 46, recovery: 50, wRISP: 56, vsLefty: 56, poise: 70, heater: 0, agile: 32,
      abilities: ["Power Hitter", "Tough Out"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "medium",
      ...noPitches },
    // Seth Dardar — 3B, .283 / 5 HR / 28 RBI — converted from P, contributing bat
    { firstName: "Seth", lastName: "Dardar", position: "3B", eligibility: "JR", homeState: "KS", hometown: "Manhattan", jerseyNumber: 24,
      hitForAvg: 65, power: 60, speed: 36, arm: 58, fielding: 58, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 62, grit: 70, stealing: 10, running: 32, throwing: 60, recovery: 50, wRISP: 65, vsLefty: 62, poise: 66, heater: 0, agile: 50,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Jack Ruckert — SS depth, .250 / 0 HR / 8 RBI in part-time role
    { firstName: "Jack", lastName: "Ruckert", position: "SS", eligibility: "SO", homeState: "LA", hometown: "Metairie", jerseyNumber: 32,
      hitForAvg: 50, power: 32, speed: 44, arm: 48, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 44, grit: 56, stealing: 24, running: 42, throwing: 50, recovery: 40, wRISP: 46, vsLefty: 44, poise: 48, heater: 0, agile: 56,
      abilities: ["Good Mood", "Express Baserunning"], potential: "A-", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // OUTFIELDERS (7)
    // Derek Curiel — CF, .343 / 6 HR / 44 RBI — STAR, Golden Spikes contender
    { firstName: "Derek", lastName: "Curiel", position: "OF", eligibility: "JR", homeState: "CA", hometown: "Chino Hills", jerseyNumber: 6,
      hitForAvg: 88, power: 70, speed: 78, arm: 70, fielding: 80, errorResistance: 76, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 86, vsLHP: 78, grit: 82, stealing: 70, running: 78, throwing: 72, recovery: 65, wRISP: 88, vsLefty: 78, poise: 84, heater: 0, agile: 80,
      abilities: ["Contact Hitter", "Power Hitter", "Express Baserunning", "Consigliere", "Tough Out"], potential: "A+", catcherAbility: null,
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Jake Brown — RF, .309 / 16 HR / 49 RBI — power bat
    { firstName: "Jake", lastName: "Brown", position: "OF", eligibility: "SR", homeState: "TX", hometown: "Katy", jerseyNumber: 7,
      hitForAvg: 70, power: 82, speed: 50, arm: 60, fielding: 56, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 72, vsLHP: 68, grit: 70, stealing: 32, running: 48, throwing: 62, recovery: 56, wRISP: 78, vsLefty: 68, poise: 70, heater: 0, agile: 52,
      abilities: ["Power Hitter", "Consigliere", "vs. Breaking Pitches"], potential: "A-", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Mason Braun — OF, .304 / .477 OBP / 31 BB — elite plate discipline
    { firstName: "Mason", lastName: "Braun", position: "OF", eligibility: "SO", homeState: "FL", hometown: "Jacksonville", jerseyNumber: 18,
      hitForAvg: 64, power: 42, speed: 48, arm: 50, fielding: 70, errorResistance: 70, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 58, grit: 88, stealing: 24, running: 46, throwing: 52, recovery: 50, wRISP: 60, vsLefty: 58, poise: 80, heater: 0, agile: 56,
      abilities: ["Tough Out", "Defensive Artisan"], potential: "A-", catcherAbility: null,
      skinTone: "light", hairColor: "blonde", hairStyle: "medium",
      ...noPitches },
    // John Pearson — OF, .253 / 8 HR / 23 RBI — newer power option
    { firstName: "John", lastName: "Pearson", position: "OF", eligibility: "JR", homeState: "TX", hometown: "Dallas", jerseyNumber: 11,
      hitForAvg: 52, power: 62, speed: 38, arm: 48, fielding: 44, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 48, grit: 56, stealing: 20, running: 38, throwing: 50, recovery: 42, wRISP: 50, vsLefty: 48, poise: 52, heater: 0, agile: 44,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Daniel Harden — OF, depth/PR speed
    { firstName: "Daniel", lastName: "Harden", position: "OF", eligibility: "SR", homeState: "LA", hometown: "New Orleans", jerseyNumber: 14,
      hitForAvg: 42, power: 36, speed: 60, arm: 50, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 40, grit: 48, stealing: 50, running: 60, throwing: 52, recovery: 44, wRISP: 42, vsLefty: 40, poise: 46, heater: 0, agile: 60,
      abilities: ["Express Baserunning"], potential: "B", catcherAbility: null,
      skinTone: "dark", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Chris Stanfield — OF, SR, limited PT (.951 fld%, 41 chances)
    { firstName: "Chris", lastName: "Stanfield", position: "OF", eligibility: "SR", homeState: "FL", hometown: "Tampa", jerseyNumber: 1,
      hitForAvg: 38, power: 32, speed: 42, arm: 50, fielding: 50, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 36, grit: 42, stealing: 22, running: 42, throwing: 52, recovery: 38, wRISP: 38, vsLefty: 36, poise: 40, heater: 0, agile: 46,
      abilities: ["High-Speed Laser"], potential: "B", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Trent Caraway — IF/3B, JR (utility)
    { firstName: "Trent", lastName: "Caraway", position: "3B", eligibility: "SR", homeState: "OR", hometown: "Corvallis", jerseyNumber: 44,
      hitForAvg: 46, power: 48, speed: 36, arm: 56, fielding: 48, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 42, grit: 48, stealing: 14, running: 36, throwing: 56, recovery: 38, wRISP: 44, vsLefty: 42, poise: 46, heater: 0, agile: 42,
      abilities: ["Iron Man", "Pull Hitter"], potential: "B", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
  ],

  "Florida": [
      // 32-17/13-11 SEC, RPI #12, BA #13, Kevin O'Sullivan Yr 19. SOS #3, 7 SHO (2nd nation).
      // PITCHERS (10) — 1-8 pitch scale
      // Aidan King — Friday RHP SO, 4-2/1.62 ERA, National Pitcher of the Month — TEAM ELITE STUFF
      { firstName: "Aidan", lastName: "King", position: "P", eligibility: "FR", homeState: "GA", hometown: "Savannah", jerseyNumber: 29,
        hitForAvg: 14, power: 11, speed: 36, arm: 65, fielding: 41, errorResistance: 54, velocity: 65, control: 69, stamina: 65, stuff: 73,
        clutch: 80, vsLHP: 76, grit: 80, stealing: 10, running: 34, throwing: 78, recovery: 57, wRISP: 65, vsLefty: 65, poise: 65, heater: 65, agile: 44,
        abilities: ["Star of Victory", "Intimidator", "Sharpness", "Heavy Ball", "Winner's Luck"], potential: "A+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 7, 6, 1, 0, 0, 0]) },
      // Liam Peterson — Saturday RHP JR, top-ranked P in 2026 MLB Draft, 96 K in 69.1 IP last yr
      { firstName: "Liam", lastName: "Peterson", position: "P", eligibility: "JR", homeState: "FL", hometown: "Jacksonville", jerseyNumber: 23,
        hitForAvg: 16, power: 13, speed: 38, arm: 68, fielding: 41, errorResistance: 54, velocity: 71, control: 57, stamina: 63, stuff: 68,
        clutch: 76, vsLHP: 70, grit: 80, stealing: 10, running: 34, throwing: 80, recovery: 57, wRISP: 57, vsLefty: 62, poise: 65, heater: 71, agile: 44,
        abilities: ["Strong Starter", "Explosive Fastball", "Intimidator", "Tunneling", "Heavy Ball", "Winner's Luck"], potential: "A+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 7, 0, 1, 5, 5, 4]) },
      // Russell Sandefer — Sunday RHP JR (UCF transfer), 2-1/3.00
      { firstName: "Russell", lastName: "Sandefer", position: "P", eligibility: "JR", homeState: "FL", hometown: "Orlando", jerseyNumber: 21,
        hitForAvg: 13, power: 10, speed: 32, arm: 55, fielding: 33, errorResistance: 44, velocity: 56, control: 60, stamina: 57, stuff: 57,
        clutch: 70, vsLHP: 64, grit: 68, stealing: 8, running: 30, throwing: 68, recovery: 47, wRISP: 50, vsLefty: 50, poise: 55, heater: 57, agile: 40,
        abilities: ["Strong Starter", "Inside Pitch", "Strong Finisher", "Winner's Luck", "Doctor K"], potential: "A-", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
      // Jackson Barberi — JR RHP rotation/RP
      { firstName: "Jackson", lastName: "Barberi", position: "P", eligibility: "JR", homeState: "FL", hometown: "Jacksonville", jerseyNumber: 38,
        hitForAvg: 14, power: 12, speed: 34, arm: 52, fielding: 32, errorResistance: 44, velocity: 55, control: 52, stamina: 51, stuff: 52,
        clutch: 60, vsLHP: 56, grit: 62, stealing: 9, running: 32, throwing: 66, recovery: 43, wRISP: 43, vsLefty: 46, poise: 48, heater: 54, agile: 38,
        abilities: ["Guts", "Strong Starter", "Full Throttle"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
      // Billy Barlow — JR RHP RP
      { firstName: "Billy", lastName: "Barlow", position: "P", eligibility: "JR", homeState: "FL", hometown: "Tallahassee", jerseyNumber: 40,
        hitForAvg: 11, power: 9, speed: 30, arm: 48, fielding: 29, errorResistance: 40, velocity: 50, control: 48, stamina: 38, stuff: 48,
        clutch: 70, vsLHP: 58, grit: 62, stealing: 8, running: 28, throwing: 60, recovery: 38, wRISP: 48, vsLefty: 44, poise: 53, heater: 50, agile: 36,
        abilities: ["Fireman", "Guts", "Poker Face"], potential: "A-", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 0, 1, 0, 4, 0]) },
      // McCall Biemiller — LHP
      { firstName: "McCall", lastName: "Biemiller", position: "P", eligibility: "JR", homeState: "PA", hometown: "Pittsburgh", jerseyNumber: 33,
        hitForAvg: 12, power: 10, speed: 32, arm: 52, fielding: 31, errorResistance: 42, velocity: 52, control: 52, stamina: 38, stuff: 52,
        clutch: 64, vsLHP: 76, grit: 64, stealing: 8, running: 30, throwing: 64, recovery: 41, wRISP: 46, vsLefty: 58, poise: 49, heater: 52, agile: 38,
        abilities: ["Fireman"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [5, 0, 5, 1, 0, 0, 0]) },
      // Christian Rodriguez — RHP RP
      { firstName: "Christian", lastName: "Rodriguez", position: "P", eligibility: "JR", homeState: "FL", hometown: "Miami", jerseyNumber: 35,
        hitForAvg: 12, power: 10, speed: 34, arm: 50, fielding: 30, errorResistance: 42, velocity: 54, control: 48, stamina: 38, stuff: 51,
        clutch: 60, vsLHP: 56, grit: 60, stealing: 8, running: 32, throwing: 64, recovery: 39, wRISP: 42, vsLefty: 44, poise: 45, heater: 53, agile: 38,
        abilities: ["Fireman", "Constant Speed", "Explosive Fastball"], potential: "B+", catcherAbility: null,
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
      // Cooper Walls — JR RHP (Hawaii transfer, Big West Frosh P of Year)
      { firstName: "Cooper", lastName: "Walls", position: "P", eligibility: "JR", homeState: "HI", hometown: "Honolulu", jerseyNumber: 22,
        hitForAvg: 14, power: 11, speed: 32, arm: 52, fielding: 31, errorResistance: 42, velocity: 54, control: 51, stamina: 49, stuff: 52,
        clutch: 60, vsLHP: 58, grit: 62, stealing: 9, running: 30, throwing: 66, recovery: 43, wRISP: 45, vsLefty: 46, poise: 48, heater: 54, agile: 38,
        abilities: ["Strong Starter", "Kageura", "Strikeout"], potential: "A-", catcherAbility: null,
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
      // Cam Smith — FR RHP
      { firstName: "Cam", lastName: "Smith", position: "P", eligibility: "FR", homeState: "FL", hometown: "Tampa", jerseyNumber: 48,
        hitForAvg: 11, power: 8, speed: 32, arm: 39, fielding: 22, errorResistance: 34, velocity: 39, control: 32, stamina: 29, stuff: 37,
        clutch: 38, vsLHP: 36, grit: 40, stealing: 11, running: 30, throwing: 52, recovery: 25, wRISP: 25, vsLefty: 28, poise: 26, heater: 40, agile: 36,
        abilities: ["Explosive Fastball"], potential: "A", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
      // Luke McNeillie — FR RHP
      { firstName: "Luke", lastName: "McNeillie", position: "P", eligibility: "FR", homeState: "FL", hometown: "Pensacola", jerseyNumber: 46,
        hitForAvg: 10, power: 8, speed: 34, arm: 37, fielding: 22, errorResistance: 34, velocity: 38, control: 31, stamina: 30, stuff: 37,
        clutch: 36, vsLHP: 36, grit: 38, stealing: 11, running: 32, throwing: 52, recovery: 25, wRISP: 25, vsLefty: 25, poise: 25, heater: 38, agile: 38,
        abilities: ["Low Ball", "Good Pickoff", "Star of Victory"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
      // CATCHERS (2)
      // AJ Malzone — JR C, top hitter
      { firstName: "AJ", lastName: "Malzone", position: "C", eligibility: "JR", homeState: "IL", hometown: "Manteno", jerseyNumber: 28,
        hitForAvg: 70, power: 64, speed: 38, arm: 60, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 70, vsLHP: 60, grit: 70, stealing: 28, running: 38, throwing: 60, recovery: 48, wRISP: 70, vsLefty: 58, poise: 70, heater: 0, agile: 40,
        abilities: ["Contact Hitter", "Defensive Artisan", "Power Hitter"], potential: "A", catcherAbility: 56,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Karson Bowen — SR C
      { firstName: "Karson", lastName: "Bowen", position: "C", eligibility: "SR", homeState: "TX", hometown: "Fort Worth", jerseyNumber: 12,
        hitForAvg: 52, power: 46, speed: 30, arm: 56, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 50, vsLHP: 46, grit: 52, stealing: 12, running: 28, throwing: 56, recovery: 42, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 32,
        abilities: ["Defensive Artisan", "Contact Hitter"], potential: "B+", catcherAbility: 50,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // INFIELDERS (6)
      // Brendan Lawson — SS SO, top 2027 draft prospect, .317/10 HR/61 RBI as FR
      { firstName: "Brendan", lastName: "Lawson", position: "SS", eligibility: "FR", homeState: "FL", hometown: "Miami", jerseyNumber: 2,
        hitForAvg: 80, power: 76, speed: 64, arm: 70, fielding: 70, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 80, vsLHP: 76, grit: 80, stealing: 38, running: 60, throwing: 70, recovery: 56, wRISP: 80, vsLefty: 76, poise: 80, heater: 0, agile: 64,
        abilities: ["Artist", "Defensive Artisan", "Consigliere"], potential: "A+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Caden McDonald — DH/1B two-way star, National Two-Way POW, 12-29 (.414) 4 HR 12 RBI in 7 games — TEAM ELITE POWER
      { firstName: "Caden", lastName: "McDonald", position: "1B", eligibility: "JR", homeState: "FL", hometown: "Tampa", jerseyNumber: 17,
        hitForAvg: 76, power: 90, speed: 38, arm: 60, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 80, vsLHP: 76, grit: 80, stealing: 14, running: 36, throwing: 60, recovery: 46, wRISP: 80, vsLefty: 76, poise: 80, heater: 0, agile: 40,
        abilities: ["Artist", "Power Hitter", "Consigliere"], potential: "A+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Cade Kurland — 2B JR
      { firstName: "Cade", lastName: "Kurland", position: "2B", eligibility: "JR", homeState: "FL", hometown: "Coral Gables", jerseyNumber: 6,
        hitForAvg: 60, power: 56, speed: 50, arm: 56, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 56, vsLHP: 52, grit: 58, stealing: 28, running: 46, throwing: 56, recovery: 46, wRISP: 54, vsLefty: 50, poise: 56, heater: 0, agile: 50,
        abilities: ["Power Hitter", "Contact Hitter"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Sam Miller — 3B SR
      { firstName: "Sam", lastName: "Miller", position: "3B", eligibility: "SR", homeState: "NY", hometown: "New York", jerseyNumber: 10,
        hitForAvg: 56, power: 54, speed: 38, arm: 50, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 54, vsLHP: 50, grit: 56, stealing: 16, running: 36, throwing: 52, recovery: 42, wRISP: 54, vsLefty: 50, poise: 54, heater: 0, agile: 38,
        abilities: ["Consigliere", "Power Hitter"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Cash Strayer — SS FR
      { firstName: "Cash", lastName: "Strayer", position: "SS", eligibility: "FR", homeState: "FL", hometown: "St. Petersburg", jerseyNumber: 24,
        hitForAvg: 32, power: 26, speed: 40, arm: 38, fielding: 36, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 28, vsLHP: 26, grit: 30, stealing: 24, running: 38, throwing: 38, recovery: 26, wRISP: 28, vsLefty: 26, poise: 28, heater: 0, agile: 40,
        abilities: ["Consigliere", "Counterattack"], potential: "A-", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Bryce Buckley — 3B SO
      { firstName: "Bryce", lastName: "Buckley", position: "3B", eligibility: "SO", homeState: "FL", hometown: "Winter Haven", jerseyNumber: 26,
        hitForAvg: 36, power: 30, speed: 32, arm: 40, fielding: 38, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 32, vsLHP: 30, grit: 34, stealing: 14, running: 30, throwing: 38, recovery: 28, wRISP: 30, vsLefty: 28, poise: 32, heater: 0, agile: 32,
        abilities: ["Bunt Artisan", "Double Play"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // OUTFIELDERS (7)
      // Kyle Jones — CF SO, Stetson transfer, .351/23 SB at Stetson, 1st rd talent
      { firstName: "Kyle", lastName: "Jones", position: "OF", eligibility: "SO", homeState: "FL", hometown: "Naples", jerseyNumber: 1,
        hitForAvg: 70, power: 50, speed: 70, arm: 56, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 70, vsLHP: 64, grit: 70, stealing: 56, running: 64, throwing: 56, recovery: 46, wRISP: 64, vsLefty: 60, poise: 70, heater: 0, agile: 64,
        abilities: ["Express Baserunning", "Chance Maker", "Contact Hitter"], potential: "A+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Ethan Surowiec — OF/DH JR, Northwoods League MVP (.387/17 HR)
      { firstName: "Ethan", lastName: "Surowiec", position: "OF", eligibility: "JR", homeState: "MS", hometown: "Oxford", jerseyNumber: 18,
        hitForAvg: 70, power: 70, speed: 36, arm: 50, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 70, vsLHP: 64, grit: 70, stealing: 14, running: 36, throwing: 50, recovery: 42, wRISP: 70, vsLefty: 64, poise: 70, heater: 0, agile: 38,
        abilities: ["Artist", "Power Hitter", "Consigliere"], potential: "A", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Landon Stripling — OF, 2 HR / 4 XBH last 3 games
      { firstName: "Landon", lastName: "Stripling", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Gainesville", jerseyNumber: 13,
        hitForAvg: 60, power: 60, speed: 46, arm: 54, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 60, vsLHP: 56, grit: 60, stealing: 24, running: 44, throwing: 56, recovery: 44, wRISP: 60, vsLefty: 56, poise: 60, heater: 0, agile: 46,
        abilities: ["Power Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Blake Cyr — OF JR
      { firstName: "Blake", lastName: "Cyr", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Bradenton", jerseyNumber: 7,
        hitForAvg: 50, power: 48, speed: 44, arm: 50, fielding: 48, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 48, vsLHP: 44, grit: 50, stealing: 26, running: 42, throwing: 52, recovery: 40, wRISP: 48, vsLefty: 44, poise: 48, heater: 0, agile: 46,
        abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Hayden Yost — OF JR
      { firstName: "Hayden", lastName: "Yost", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Sarasota", jerseyNumber: 3,
        hitForAvg: 48, power: 38, speed: 50, arm: 48, fielding: 46, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 44, vsLHP: 40, grit: 44, stealing: 34, running: 48, throwing: 48, recovery: 38, wRISP: 42, vsLefty: 38, poise: 44, heater: 0, agile: 50,
        abilities: ["Express Baserunning"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Ashton Wilson — OF JR
      { firstName: "Ashton", lastName: "Wilson", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Lakeland", jerseyNumber: 9,
        hitForAvg: 56, power: 48, speed: 50, arm: 56, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 52, vsLHP: 50, grit: 56, stealing: 32, running: 48, throwing: 58, recovery: 44, wRISP: 50, vsLefty: 48, poise: 52, heater: 0, agile: 52,
        abilities: ["High-Speed Laser"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Ty Evans — OF JR
      { firstName: "Ty", lastName: "Evans", position: "2B", eligibility: "JR", homeState: "GA", hometown: "Marietta", jerseyNumber: 11,
        hitForAvg: 54, power: 48, speed: 50, arm: 56, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 52, vsLHP: 48, grit: 54, stealing: 32, running: 48, throwing: 58, recovery: 44, wRISP: 50, vsLefty: 48, poise: 52, heater: 0, agile: 52,
        abilities: ["Tough Out", "Unrelenting", "Contact Hitter"], potential: "B", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
    ],

    "Vanderbilt": [
    // PITCHERS (10)
    { firstName: "Austin", lastName: "Nye", position: "P", eligibility: "SO", homeState: "TN", hometown: "Nashville", jerseyNumber: 34,
      hitForAvg: 24, power: 20, speed: 46, arm: 72, fielding: 43, errorResistance: 54, velocity: 75, control: 68, stamina: 70, stuff: 72,
      clutch: 79, vsLHP: 74, grit: 81, stealing: 13, running: 41, throwing: 85, recovery: 61, wRISP: 63, vsLefty: 65, poise: 67, heater: 72, agile: 50,
      abilities: ["Star of Victory", "Strong Starter", "Sharpness", "Bad Ball Hitter", "Intimidator", "Heavy Ball"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 7, 6, 1, 0, 0, 0]) },
    { firstName: "Connor", lastName: "Fennell", position: "P", eligibility: "JR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 29,
      hitForAvg: 17, power: 13, speed: 37, arm: 55, fielding: 34, errorResistance: 44, velocity: 56, control: 54, stamina: 54, stuff: 55,
      clutch: 63, vsLHP: 60, grit: 65, stealing: 12, running: 36, throwing: 69, recovery: 47, wRISP: 48, vsLefty: 49, poise: 51, heater: 55, agile: 41,
      abilities: ["Strong Starter", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 6, 1, 0, 0, 0]) },
    { firstName: "Nate", lastName: "Taylor", position: "P", eligibility: "SO", homeState: "GA", hometown: "Marietta", jerseyNumber: 22,
      hitForAvg: 15, power: 12, speed: 34, arm: 49, fielding: 28, errorResistance: 39, velocity: 52, control: 43, stamina: 44, stuff: 51,
      clutch: 54, vsLHP: 50, grit: 55, stealing: 12, running: 32, throwing: 64, recovery: 39, wRISP: 39, vsLefty: 41, poise: 41, heater: 51, agile: 37,
      abilities: ["Explosive Fastball", "Strong Starter"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Miller", lastName: "Green", position: "P", eligibility: "JR", homeState: "TN", hometown: "Knoxville", jerseyNumber: 38,
      hitForAvg: 14, power: 11, speed: 31, arm: 44, fielding: 27, errorResistance: 38, velocity: 45, control: 44, stamina: 38, stuff: 44,
      clutch: 56, vsLHP: 52, grit: 57, stealing: 8, running: 28, throwing: 59, recovery: 41, wRISP: 41, vsLefty: 41, poise: 42, heater: 44, agile: 34,
      abilities: ["Fireman", "Guts", "Escape Pitch"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Alex", lastName: "Kranzler", position: "P", eligibility: "JR", homeState: "OH", hometown: "Columbus", jerseyNumber: 40,
      hitForAvg: 15, power: 11, speed: 36, arm: 55, fielding: 33, errorResistance: 45, velocity: 57, control: 55, stamina: 47, stuff: 55,
      clutch: 66, vsLHP: 61, grit: 67, stealing: 10, running: 35, throwing: 70, recovery: 50, wRISP: 50, vsLefty: 51, poise: 52, heater: 55, agile: 40,
      abilities: ["Fireman", "Showtime", "Staredown", "Intimidator"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Patrick", lastName: "Reilly", position: "P", eligibility: "JR", homeState: "NY", hometown: "White Plains", jerseyNumber: 42,
      hitForAvg: 10, power: 8, speed: 24, arm: 29, fielding: 18, errorResistance: 29, velocity: 30, control: 28, stamina: 28, stuff: 29,
      clutch: 40, vsLHP: 37, grit: 41, stealing: 6, running: 22, throwing: 43, recovery: 25, wRISP: 25, vsLefty: 26, poise: 27, heater: 29, agile: 26,
      abilities: ["Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Ginther", position: "P", eligibility: "JR", homeState: "IN", hometown: "Indianapolis", jerseyNumber: 44,
      hitForAvg: 9, power: 7, speed: 22, arm: 27, fielding: 17, errorResistance: 28, velocity: 28, control: 27, stamina: 25, stuff: 27,
      clutch: 35, vsLHP: 35, grit: 37, stealing: 6, running: 21, throwing: 41, recovery: 23, wRISP: 23, vsLefty: 24, poise: 24, heater: 27, agile: 25,
      abilities: ["Pace"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    { firstName: "Aiden", lastName: "Stillman", position: "P", eligibility: "FR", homeState: "CA", hometown: "San Diego", jerseyNumber: 46,
      hitForAvg: 9, power: 7, speed: 29, arm: 27, fielding: 17, errorResistance: 29, velocity: 27, control: 24, stamina: 24, stuff: 27,
      clutch: 33, vsLHP: 31, grit: 34, stealing: 9, running: 27, throwing: 43, recovery: 21, wRISP: 19, vsLefty: 21, poise: 21, heater: 27, agile: 31,
      abilities: ["Delayed Arm"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    { firstName: "Jakob", lastName: "Schulz", position: "P", eligibility: "FR", homeState: "TN", hometown: "Franklin", jerseyNumber: 48,
      hitForAvg: 8, power: 7, speed: 27, arm: 30, fielding: 18, errorResistance: 27, velocity: 31, control: 25, stamina: 23, stuff: 29,
      clutch: 30, vsLHP: 29, grit: 32, stealing: 8, running: 26, throwing: 43, recovery: 21, wRISP: 20, vsLefty: 21, poise: 21, heater: 30, agile: 30,
      abilities: ["Strength Distribution"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    { firstName: "Drew", lastName: "Beam", position: "P", eligibility: "JR", homeState: "TN", hometown: "Murfreesboro", jerseyNumber: 32,
      hitForAvg: 11, power: 9, speed: 27, arm: 36, fielding: 22, errorResistance: 32, velocity: 37, control: 34, stamina: 34, stuff: 36,
      clutch: 44, vsLHP: 41, grit: 46, stealing: 7, running: 26, throwing: 49, recovery: 30, wRISP: 30, vsLefty: 31, poise: 32, heater: 36, agile: 30,
      abilities: ["Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Mack", lastName: "Whitcomb", position: "C", eligibility: "JR", homeState: "TN", hometown: "Cookeville", jerseyNumber: 12,
      hitForAvg: 64, power: 60, speed: 34, arm: 61, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 61, vsLHP: 58, grit: 64, stealing: 14, running: 33, throwing: 64, recovery: 49, wRISP: 61, vsLefty: 57, poise: 61, heater: 0, agile: 36,
      abilities: ["Power Hitter", "Contact Hitter", "Defensive Artisan"], potential: "A-", catcherAbility: 58,
      ...noPitches },
    { firstName: "Colin", lastName: "Barczi", position: "C", eligibility: "JR", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 19,
      hitForAvg: 44, power: 39, speed: 26, arm: 47, fielding: 45, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 43, vsLHP: 39, grit: 44, stealing: 10, running: 25, throwing: 48, recovery: 36, wRISP: 41, vsLefty: 38, poise: 43, heater: 0, agile: 29,
      abilities: ["Consigliere", "Pressure Run"], potential: "B", catcherAbility: 44,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Mike", lastName: "Mancini", position: "2B", eligibility: "JR", homeState: "NJ", hometown: "Westfield", jerseyNumber: 6,
      hitForAvg: 53, power: 42, speed: 46, arm: 53, fielding: 55, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 51, vsLHP: 47, grit: 53, stealing: 29, running: 45, throwing: 54, recovery: 42, wRISP: 49, vsLefty: 46, poise: 51, heater: 0, agile: 47,
      abilities: ["Contact Hitter", "Chance Maker"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Brodie", lastName: "Johnston", position: "SS", eligibility: "JR", homeState: "TN", hometown: "Brentwood", jerseyNumber: 4,
      hitForAvg: 51, power: 45, speed: 50, arm: 58, fielding: 58, errorResistance: 57, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 47, grit: 51, stealing: 32, running: 48, throwing: 60, recovery: 42, wRISP: 48, vsLefty: 45, poise: 50, heater: 0, agile: 51,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Max", lastName: "Jensen", position: "1B", eligibility: "JR", homeState: "NY", hometown: "Ithaca", jerseyNumber: 18,
      hitForAvg: 55, power: 54, speed: 35, arm: 50, fielding: 51, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 55, stealing: 13, running: 34, throwing: 51, recovery: 43, wRISP: 54, vsLefty: 48, poise: 54, heater: 0, agile: 37,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Carter", lastName: "Johnstone", position: "1B", eligibility: "JR", homeState: "CA", hometown: "Fullerton", jerseyNumber: 16,
      hitForAvg: 50, power: 46, speed: 36, arm: 47, fielding: 49, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 46, grit: 50, stealing: 14, running: 35, throwing: 49, recovery: 39, wRISP: 47, vsLefty: 44, poise: 49, heater: 0, agile: 38,
      abilities: ["Consigliere"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Tristan", lastName: "Bristow", position: "SS", eligibility: "FR", homeState: "TN", hometown: "Hendersonville", jerseyNumber: 24,
      hitForAvg: 29, power: 24, speed: 37, arm: 37, fielding: 35, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 27, vsLHP: 26, grit: 29, stealing: 24, running: 36, throwing: 39, recovery: 25, wRISP: 26, vsLefty: 25, poise: 27, heater: 0, agile: 39,
      abilities: ["Two-Strike Hitter", "Puller Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (7)
    { firstName: "Rustan", lastName: "Rigdon", position: "OF", eligibility: "SO", homeState: "GA", hometown: "Kennesaw", jerseyNumber: 1,
      hitForAvg: 59, power: 46, speed: 59, arm: 54, fielding: 55, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 55, vsLHP: 54, grit: 57, stealing: 46, running: 57, throwing: 55, recovery: 46, wRISP: 54, vsLefty: 52, poise: 55, heater: 0, agile: 59,
      abilities: ["vs. Breaking Pitches", "Express Baserunning", "Chance Maker"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Braden", lastName: "Holcomb", position: "OF", eligibility: "JR", homeState: "TN", hometown: "Clarksville", jerseyNumber: 3,
      hitForAvg: 50, power: 47, speed: 44, arm: 52, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 45, grit: 50, stealing: 28, running: 43, throwing: 53, recovery: 41, wRISP: 47, vsLefty: 44, poise: 48, heater: 0, agile: 45,
      abilities: ["Power Hitter", "High-Speed Laser"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Logan", lastName: "Johnstone", position: "OF", eligibility: "SR", homeState: "WA", hometown: "Pullman", jerseyNumber: 7,
      hitForAvg: 48, power: 44, speed: 39, arm: 44, fielding: 43, errorResistance: 41, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 44, grit: 48, stealing: 24, running: 38, throwing: 45, recovery: 38, wRISP: 47, vsLefty: 43, poise: 47, heater: 0, agile: 41,
      abilities: ["Consigliere", "Contact Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Tyler", lastName: "Hicks", position: "OF", eligibility: "FR", homeState: "TN", hometown: "Memphis", jerseyNumber: 20,
      hitForAvg: 35, power: 30, speed: 44, arm: 42, fielding: 38, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 33, vsLHP: 32, grit: 35, stealing: 27, running: 42, throwing: 44, recovery: 30, wRISP: 32, vsLefty: 30, poise: 33, heater: 0, agile: 45,
      abilities: ["Bad Mood"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Grant", lastName: "Massey", position: "OF", eligibility: "FR", homeState: "AL", hometown: "Birmingham", jerseyNumber: 26,
      hitForAvg: 33, power: 28, speed: 44, arm: 42, fielding: 37, errorResistance: 35, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 31, vsLHP: 29, grit: 33, stealing: 27, running: 42, throwing: 44, recovery: 28, wRISP: 29, vsLefty: 28, poise: 31, heater: 0, agile: 45,
      abilities: ["Revenge"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Matthew", lastName: "Polk", position: "OF", eligibility: "JR", homeState: "TN", hometown: "Germantown", jerseyNumber: 9,
      hitForAvg: 55, power: 47, speed: 51, arm: 56, fielding: 55, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 49, grit: 55, stealing: 32, running: 49, throwing: 57, recovery: 44, wRISP: 51, vsLefty: 47, poise: 52, heater: 0, agile: 52,
      abilities: ["Two-Strike Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Javier", lastName: "Vaz", position: "3B", eligibility: "SO", homeState: "FL", hometown: "Miami", jerseyNumber: 10,
      hitForAvg: 56, power: 48, speed: 47, arm: 63, fielding: 60, errorResistance: 59, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 55, vsLHP: 51, grit: 56, stealing: 22, running: 46, throwing: 64, recovery: 46, wRISP: 52, vsLefty: 48, poise: 55, heater: 0, agile: 48,
      abilities: ["Trickster", "Resilient"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Rob", lastName: "Dickey", position: "1B", eligibility: "SO", homeState: "TN", hometown: "Nashville", jerseyNumber: 20,
      hitForAvg: 39, power: 38, speed: 30, arm: 40, fielding: 40, errorResistance: 39, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 35, grit: 39, stealing: 11, running: 29, throwing: 42, recovery: 33, wRISP: 37, vsLefty: 34, poise: 38, heater: 0, agile: 31,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Texas A&M": [
    // PITCHERS (10) — 36-10/15-8 SEC, D1B #9, Earley Yr 2 — series wins over #1 Tenn, #2 Ark, #2 LSU, #2 Texas
    // Ethan Darden — Friday LHP JR Clemson transfer, 4-0/2.88 in relief, NEW Friday SP
    { firstName: "Ethan", lastName: "Darden", position: "P", eligibility: "JR", homeState: "SC", hometown: "Greenville", jerseyNumber: 30,
      hitForAvg: 18, power: 14, speed: 36, arm: 63, fielding: 37, errorResistance: 50, velocity: 63, control: 64, stamina: 61, stuff: 63,
      clutch: 76, vsLHP: 80, grit: 76, stealing: 9, running: 32, throwing: 74, recovery: 51, wRISP: 58, vsLefty: 64, poise: 63, heater: 63, agile: 42,
      abilities: ["Star of Victory", "Fireman", "Inside Pitch", "Good Pickoff", "Intimidator"], potential: "A-", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 6, 0, 1, 0, 0, 0]) },
    // Aiden Sims — Saturday SO RHP, 5-1/4.68, top weekend arm
    { firstName: "Aiden", lastName: "Sims", position: "P", eligibility: "FR", homeState: "TX", hometown: "Austin", jerseyNumber: 22,
      hitForAvg: 16, power: 12, speed: 34, arm: 60, fielding: 35, errorResistance: 46, velocity: 61, control: 57, stamina: 60, stuff: 60,
      clutch: 70, vsLHP: 66, grit: 70, stealing: 11, running: 33, throwing: 72, recovery: 49, wRISP: 51, vsLefty: 54, poise: 56, heater: 60, agile: 38,
      abilities: ["Strong Starter", "Sharpness", "Doctor K", "Flyball Pitcher"], potential: "A", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 7, 5, 1, 0, 0, 0]) },
    // Shane Sdao — was Friday ace, now bullpen LHP after injury return, 3-4/6.55, 1 IP/6 R vs Auburn
    { firstName: "Shane", lastName: "Sdao", position: "P", eligibility: "JR", homeState: "TX", hometown: "Houston", jerseyNumber: 34,
      hitForAvg: 14, power: 11, speed: 34, arm: 53, fielding: 32, errorResistance: 44, velocity: 57, control: 49, stamina: 38, stuff: 53,
      clutch: 58, vsLHP: 70, grit: 60, stealing: 8, running: 30, throwing: 68, recovery: 38, wRISP: 41, vsLefty: 53, poise: 44, heater: 57, agile: 38,
      abilities: ["Fireman", "vs. Strong Batters", "Sharpness"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    // Clayton Freshcorn — Closer RHP JR, 2 scoreless IP wins, dependable late
    { firstName: "Clayton", lastName: "Freshcorn", position: "P", eligibility: "JR", homeState: "TX", hometown: "Katy", jerseyNumber: 38,
      hitForAvg: 15, power: 12, speed: 36, arm: 62, fielding: 35, errorResistance: 46, velocity: 63, control: 60, stamina: 39, stuff: 62,
      clutch: 80, vsLHP: 70, grit: 76, stealing: 8, running: 32, throwing: 74, recovery: 44, wRISP: 60, vsLefty: 55, poise: 63, heater: 63, agile: 40,
      abilities: ["Fireman", "Explosive Fastball", "Intimidator"], potential: "A", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    // Justin Lamkin — SO LHP swing
    { firstName: "Justin", lastName: "Lamkin", position: "P", eligibility: "SO", homeState: "TX", hometown: "Beaumont", jerseyNumber: 46,
      hitForAvg: 13, power: 10, speed: 32, arm: 48, fielding: 29, errorResistance: 40, velocity: 49, control: 48, stamina: 45, stuff: 47,
      clutch: 56, vsLHP: 60, grit: 56, stealing: 8, running: 30, throwing: 60, recovery: 39, wRISP: 39, vsLefty: 45, poise: 42, heater: 48, agile: 36,
      abilities: ["Strong Starter", "Good Pickoff", "vs. Strong Batters"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    // Weston Moss — RP/swing JR
    { firstName: "Weston", lastName: "Moss", position: "P", eligibility: "JR", homeState: "TX", hometown: "San Antonio", jerseyNumber: 29,
      hitForAvg: 13, power: 10, speed: 30, arm: 50, fielding: 30, errorResistance: 42, velocity: 52, control: 50, stamina: 46, stuff: 50,
      clutch: 58, vsLHP: 54, grit: 58, stealing: 8, running: 30, throwing: 64, recovery: 41, wRISP: 41, vsLefty: 43, poise: 44, heater: 52, agile: 36,
      abilities: ["Guts", "Strikeout", "Miracle Sharpness", "Quick Hands"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 5, 6, 1, 0, 0, 0]) },
    // Ryan Prager — JR RHP innings eater
    { firstName: "Ryan", lastName: "Prager", position: "P", eligibility: "JR", homeState: "TX", hometown: "The Woodlands", jerseyNumber: 36,
      hitForAvg: 13, power: 10, speed: 32, arm: 50, fielding: 31, errorResistance: 42, velocity: 51, control: 53, stamina: 49, stuff: 49,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 8, running: 30, throwing: 64, recovery: 41, wRISP: 41, vsLefty: 43, poise: 46, heater: 50, agile: 36,
      abilities: ["Guts", "Inside Pitch"], potential: "B", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    // Cole Messina — JR RP
    { firstName: "Cole", lastName: "Messina", position: "P", eligibility: "JR", homeState: "TX", hometown: "Frisco", jerseyNumber: 42,
      hitForAvg: 11, power: 9, speed: 30, arm: 40, fielding: 26, errorResistance: 38, velocity: 42, control: 40, stamina: 31, stuff: 40,
      clutch: 50, vsLHP: 46, grit: 50, stealing: 7, running: 28, throwing: 54, recovery: 34, wRISP: 33, vsLefty: 34, poise: 36, heater: 41, agile: 34,
      abilities: ["Flyball Pitcher"], potential: "B", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    // Josh Stewart — JR RP depth
    { firstName: "Josh", lastName: "Stewart", position: "P", eligibility: "JR", homeState: "TX", hometown: "Dallas", jerseyNumber: 40,
      hitForAvg: 10, power: 8, speed: 28, arm: 34, fielding: 22, errorResistance: 34, velocity: 37, control: 34, stamina: 30, stuff: 34,
      clutch: 44, vsLHP: 42, grit: 46, stealing: 7, running: 26, throwing: 48, recovery: 29, wRISP: 29, vsLefty: 30, poise: 32, heater: 36, agile: 32,
      abilities: ["Guts"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    // Trey Dombroski — JR RP depth
    { firstName: "Trey", lastName: "Dombroski", position: "P", eligibility: "JR", homeState: "TX", hometown: "College Station", jerseyNumber: 44,
      hitForAvg: 10, power: 7, speed: 28, arm: 32, fielding: 20, errorResistance: 32, velocity: 34, control: 32, stamina: 28, stuff: 32,
      clutch: 42, vsLHP: 40, grit: 44, stealing: 7, running: 26, throwing: 46, recovery: 27, wRISP: 27, vsLefty: 28, poise: 30, heater: 34, agile: 30,
      abilities: ["Delayed Arm"], potential: "B", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    // CATCHERS (2)
    // Bear Harrison — incumbent C, .254/.417/.522, 10 HR, 27 BB — elite OBP/power for catcher
    { firstName: "Bear", lastName: "Harrison", position: "C", eligibility: "JR", homeState: "TX", hometown: "Cypress", jerseyNumber: 2,
      hitForAvg: 60, power: 75, speed: 32, arm: 64, fielding: 64, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 80, vsLHP: 72, grit: 78, stealing: 8, running: 30, throwing: 66, recovery: 50, wRISP: 78, vsLefty: 72, poise: 80, heater: 0, agile: 38,
      abilities: ["Power Hitter", "Consigliere", "Defensive Artisan"], potential: "A-", catcherAbility: 64,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Tyler Keese — backup C SO
    { firstName: "Tyler", lastName: "Keese", position: "C", eligibility: "SO", homeState: "TX", hometown: "Conroe", jerseyNumber: 19,
      hitForAvg: 50, power: 46, speed: 32, arm: 62, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 52, stealing: 10, running: 32, throwing: 64, recovery: 44, wRISP: 48, vsLefty: 44, poise: 50, heater: 0, agile: 38,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: 58,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // INFIELDERS (7)
    // Chris Hacopian — 2B/SS Maryland transfer JR — TEAM ELITE — .375/.502/.656, 14 HR, 61 RBI, top-30 draft
    { firstName: "Chris", lastName: "Hacopian", position: "2B", eligibility: "JR", homeState: "MD", hometown: "Rockville", jerseyNumber: 10,
      hitForAvg: 90, power: 70, speed: 50, arm: 60, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 84, vsLHP: 80, grit: 80, stealing: 26, running: 50, throwing: 60, recovery: 46, wRISP: 84, vsLefty: 80, poise: 80, heater: 0, agile: 54,
      abilities: ["Contact Hitter", "Power Hitter", "Consigliere"], potential: "A+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Gavin Grahovac — 1B JR, top-30 draft, preseason 1st-team All-SEC
    { firstName: "Gavin", lastName: "Grahovac", position: "1B", eligibility: "JR", homeState: "TX", hometown: "Spring", jerseyNumber: 5,
      hitForAvg: 64, power: 75, speed: 36, arm: 56, fielding: 56, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 70, vsLHP: 64, grit: 70, stealing: 12, running: 32, throwing: 56, recovery: 48, wRISP: 72, vsLefty: 64, poise: 70, heater: 0, agile: 42,
      abilities: ["Artist", "Consigliere"], potential: "A", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Boston Kellner — FR SS (former roster had as P; per team report, started final scrimmage at SS)
    { firstName: "Boston", lastName: "Kellner", position: "SS", eligibility: "FR", homeState: "TX", hometown: "Plano", jerseyNumber: 4,
      hitForAvg: 50, power: 36, speed: 56, arm: 56, fielding: 56, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 44, grit: 48, stealing: 26, running: 50, throwing: 56, recovery: 38, wRISP: 44, vsLefty: 42, poise: 48, heater: 0, agile: 56,
      abilities: ["Express Baserunning"], potential: "A", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Nico Partida — FR 3B, 97 mph FB, top-40 PG recruit
    { firstName: "Nico", lastName: "Partida", position: "3B", eligibility: "FR", homeState: "AZ", hometown: "Chandler", jerseyNumber: 24,
      hitForAvg: 50, power: 44, speed: 50, arm: 70, fielding: 54, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 46, vsLHP: 42, grit: 48, stealing: 22, running: 46, throwing: 70, recovery: 40, wRISP: 42, vsLefty: 40, poise: 46, heater: 0, agile: 50,
      abilities: ["High-Speed Laser"], potential: "A+", catcherAbility: null,
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Wesley Jordan — JR UTL/2B, hit .500 opening weekend
    { firstName: "Wesley", lastName: "Jordan", position: "2B", eligibility: "JR", homeState: "TX", hometown: "Midland", jerseyNumber: 8,
      hitForAvg: 60, power: 46, speed: 50, arm: 54, fielding: 56, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 58, stealing: 24, running: 46, throwing: 54, recovery: 42, wRISP: 56, vsLefty: 50, poise: 58, heater: 0, agile: 50,
      abilities: ["Contact Hitter"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Ben Royo — backup IF (was C)
    { firstName: "Ben", lastName: "Royo", position: "OF", eligibility: "JR", homeState: "TX", hometown: "Laredo", jerseyNumber: 14,
      hitForAvg: 46, power: 40, speed: 40, arm: 50, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 46, vsLHP: 42, grit: 48, stealing: 14, running: 36, throwing: 50, recovery: 40, wRISP: 44, vsLefty: 40, poise: 46, heater: 0, agile: 42,
      abilities: ["First Pitch King", "Opposite Field Hitter"], potential: "B+", catcherAbility: null,
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Travis Chestnut — FR 3B/INF depth
    { firstName: "Travis", lastName: "Chestnut", position: "3B", eligibility: "FR", homeState: "TX", hometown: "Round Rock", jerseyNumber: 27,
      hitForAvg: 36, power: 30, speed: 44, arm: 46, fielding: 42, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 30, grit: 34, stealing: 22, running: 42, throwing: 46, recovery: 32, wRISP: 30, vsLefty: 28, poise: 32, heater: 0, agile: 46,
      abilities: ["Counterattack"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // OUTFIELDERS (6)
    // Caden Sorrell — JR CF, top-20 draft prospect, preseason 1st-team All-SEC, multi-HR opening
    { firstName: "Caden", lastName: "Sorrell", position: "OF", eligibility: "JR", homeState: "TX", hometown: "Friendswood", jerseyNumber: 3,
      hitForAvg: 70, power: 70, speed: 56, arm: 60, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 70, vsLHP: 64, grit: 70, stealing: 28, running: 54, throwing: 60, recovery: 48, wRISP: 70, vsLefty: 64, poise: 70, heater: 0, agile: 56,
      abilities: ["Power Hitter", "Consigliere", "High-Speed Laser"], potential: "A+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Jorian Wilson — FR slugger, HR leader vs LSU — NEW
    { firstName: "Jorian", lastName: "Wilson", position: "OF", eligibility: "FR", homeState: "TX", hometown: "Houston", jerseyNumber: 25,
      hitForAvg: 60, power: 70, speed: 46, arm: 56, fielding: 50, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 58, grit: 62, stealing: 16, running: 44, throwing: 56, recovery: 42, wRISP: 64, vsLefty: 58, poise: 64, heater: 0, agile: 48,
      abilities: ["Power Hitter", "Consigliere"], potential: "A+", catcherAbility: null,
      skinTone: "deep", hairColor: "black", hairStyle: "fade",
      ...noPitches },
    // Terrence Kiel II — JR LF/RF leadoff, contact + speed
    { firstName: "Terrence", lastName: "Kiel II", position: "OF", eligibility: "JR", homeState: "TX", hometown: "Pearland", jerseyNumber: 1,
      hitForAvg: 64, power: 46, speed: 64, arm: 56, fielding: 56, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 36, running: 60, throwing: 56, recovery: 44, wRISP: 56, vsLefty: 52, poise: 60, heater: 0, agile: 60,
      abilities: ["Express Baserunning", "Contact Hitter", "Chance Maker"], potential: "A-", catcherAbility: null,
      skinTone: "deep", hairColor: "black", hairStyle: "fade",
      ...noPitches },
    // Blake Binderup — JR OF/1B, last year's starting 1B
    { firstName: "Blake", lastName: "Binderup", position: "OF", eligibility: "JR", homeState: "TX", hometown: "Arlington", jerseyNumber: 7,
      hitForAvg: 56, power: 54, speed: 44, arm: 56, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 18, running: 42, throwing: 56, recovery: 42, wRISP: 54, vsLefty: 50, poise: 54, heater: 0, agile: 46,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Jake Duer — JR OF/1B, projected 7-8 hole
    { firstName: "Jake", lastName: "Duer", position: "1B", eligibility: "JR", homeState: "TX", hometown: "Sugar Land", jerseyNumber: 18,
      hitForAvg: 48, power: 46, speed: 30, arm: 44, fielding: 46, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 46, vsLHP: 42, grit: 48, stealing: 10, running: 30, throwing: 44, recovery: 38, wRISP: 46, vsLefty: 42, poise: 46, heater: 0, agile: 34,
      abilities: ["Contact Hitter"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Sawyer Farr — SO OF/2B bench depth, 31 starts last year
    { firstName: "Sawyer", lastName: "Farr", position: "OF", eligibility: "SO", homeState: "TX", hometown: "McKinney", jerseyNumber: 20,
      hitForAvg: 42, power: 36, speed: 44, arm: 44, fielding: 42, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 22, running: 42, throwing: 44, recovery: 34, wRISP: 36, vsLefty: 34, poise: 38, heater: 0, agile: 44,
      abilities: ["Multi-Hit"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
  ],

  "Tennessee": [
    // PITCHERS (10)
    { firstName: "Tegan", lastName: "Kuhns", position: "P", eligibility: "SO", homeState: "TN", hometown: "Knoxville", jerseyNumber: 34,
      hitForAvg: 16, power: 13, speed: 30, arm: 43, fielding: 26, errorResistance: 36, velocity: 46, control: 40, stamina: 41, stuff: 43,
      clutch: 53, vsLHP: 51, grit: 55, stealing: 8, running: 27, throwing: 57, recovery: 37, wRISP: 37, vsLefty: 39, poise: 40, heater: 43, agile: 33,
      abilities: ["Star of Victory", "Strong Starter", "Intimidator"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 7, 5, 1, 0, 0, 0]) },
    { firstName: "Landon", lastName: "Mack", position: "P", eligibility: "SO", homeState: "NJ", hometown: "Piscataway", jerseyNumber: 29,
      hitForAvg: 16, power: 12, speed: 34, arm: 52, fielding: 32, errorResistance: 42, velocity: 54, control: 49, stamina: 52, stuff: 52,
      clutch: 59, vsLHP: 55, grit: 62, stealing: 11, running: 33, throwing: 67, recovery: 45, wRISP: 45, vsLefty: 45, poise: 48, heater: 52, agile: 38,
      abilities: ["Strong Starter", "Guts", "Tunneling"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
    { firstName: "Evan", lastName: "Blanco", position: "P", eligibility: "JR", homeState: "VA", hometown: "Charlottesville", jerseyNumber: 22,
      hitForAvg: 17, power: 13, speed: 36, arm: 53, fielding: 32, errorResistance: 44, velocity: 55, control: 52, stamina: 52, stuff: 53,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 10, running: 35, throwing: 67, recovery: 45, wRISP: 46, vsLefty: 48, poise: 50, heater: 53, agile: 40,
      abilities: ["Strong Starter", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 6, 1, 0, 0, 0]) },
    { firstName: "Blaine", lastName: "Brown", position: "P", eligibility: "JR", homeState: "TX", hometown: "Houston", jerseyNumber: 38,
      hitForAvg: 19, power: 16, speed: 55, arm: 70, fielding: 47, errorResistance: 55, velocity: 74, control: 70, stamina: 69, stuff: 72,
      clutch: 67, vsLHP: 63, grit: 69, stealing: 30, running: 53, throwing: 73, recovery: 52, wRISP: 53, vsLefty: 55, poise: 56, heater: 74, agile: 55,
      abilities: ["Strong Starter", "Staredown", "Indomitable Soul", "Intimidator"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
    { firstName: "Brandon", lastName: "Arvidson", position: "P", eligibility: "JR", homeState: "CA", hometown: "San Clemente", jerseyNumber: 40,
      hitForAvg: 17, power: 13, speed: 35, arm: 58, fielding: 33, errorResistance: 44, velocity: 59, control: 54, stamina: 54, stuff: 58,
      clutch: 66, vsLHP: 62, grit: 67, stealing: 9, running: 33, throwing: 71, recovery: 49, wRISP: 50, vsLefty: 52, poise: 53, heater: 58, agile: 39,
      abilities: ["Star of Victory", "Sharpness", "Intimidator"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 6, 6, 1, 0, 0, 0]) },
    { firstName: "Zander", lastName: "Sechrist", position: "P", eligibility: "JR", homeState: "TN", hometown: "Maryville", jerseyNumber: 42,
      hitForAvg: 12, power: 9, speed: 27, arm: 36, fielding: 22, errorResistance: 33, velocity: 38, control: 35, stamina: 34, stuff: 36,
      clutch: 46, vsLHP: 43, grit: 47, stealing: 8, running: 26, throwing: 50, recovery: 31, wRISP: 31, vsLefty: 32, poise: 33, heater: 36, agile: 31,
      abilities: ["Fireman"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 1, 0, 0, 0]) },
    { firstName: "Nate", lastName: "Snead", position: "P", eligibility: "SO", homeState: "TN", hometown: "Chattanooga", jerseyNumber: 44,
      hitForAvg: 9, power: 7, speed: 27, arm: 29, fielding: 18, errorResistance: 29, velocity: 31, control: 29, stamina: 28, stuff: 29,
      clutch: 39, vsLHP: 37, grit: 40, stealing: 8, running: 25, throwing: 44, recovery: 26, wRISP: 24, vsLefty: 26, poise: 26, heater: 29, agile: 29,
      abilities: ["Explosive Fastball"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Keele", position: "P", eligibility: "FR", homeState: "TN", hometown: "Clarksville", jerseyNumber: 46,
      hitForAvg: 9, power: 7, speed: 27, arm: 26, fielding: 16, errorResistance: 27, velocity: 26, control: 22, stamina: 21, stuff: 25,
      clutch: 30, vsLHP: 29, grit: 31, stealing: 9, running: 26, throwing: 42, recovery: 18, wRISP: 17, vsLefty: 19, poise: 18, heater: 26, agile: 30,
      abilities: ["High Spin Gyroball", "Intimidator"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 1, 0, 0, 0]) },
    { firstName: "Caden", lastName: "Myers", position: "P", eligibility: "FR", homeState: "GA", hometown: "Alpharetta", jerseyNumber: 48,
      hitForAvg: 8, power: 7, speed: 28, arm: 30, fielding: 18, errorResistance: 28, velocity: 31, control: 25, stamina: 24, stuff: 29,
      clutch: 29, vsLHP: 28, grit: 31, stealing: 8, running: 26, throwing: 43, recovery: 20, wRISP: 19, vsLefty: 21, poise: 20, heater: 30, agile: 31,
      abilities: ["Full Throttle"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 1, 0, 0, 0]) },
    { firstName: "Dalton", lastName: "Rogers", position: "P", eligibility: "JR", homeState: "TN", hometown: "Nashville", jerseyNumber: 36,
      hitForAvg: 10, power: 7, speed: 24, arm: 27, fielding: 18, errorResistance: 28, velocity: 28, control: 27, stamina: 25, stuff: 27,
      clutch: 37, vsLHP: 36, grit: 39, stealing: 6, running: 22, throwing: 42, recovery: 23, wRISP: 23, vsLefty: 25, poise: 25, heater: 27, agile: 26,
      abilities: ["Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
    // CATCHERS (1)
    { firstName: "Stone", lastName: "Lawless", position: "C", eligibility: "JR", homeState: "MS", hometown: "Tupelo", jerseyNumber: 12,
      hitForAvg: 54, power: 51, speed: 34, arm: 62, fielding: 60, errorResistance: 57, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 53, grit: 57, stealing: 15, running: 32, throwing: 63, recovery: 48, wRISP: 54, vsLefty: 51, poise: 56, heater: 0, agile: 36,
      abilities: ["Defensive Artisan", "Consigliere"], potential: "B+", catcherAbility: 56,
      ...noPitches },
    // INFIELDERS (5)
    { firstName: "Ariel", lastName: "Antigua", position: "SS", eligibility: "SO", homeState: "FL", hometown: "Hialeah", jerseyNumber: 2,
      hitForAvg: 47, power: 39, speed: 47, arm: 51, fielding: 51, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 46, vsLHP: 43, grit: 47, stealing: 33, running: 46, throwing: 53, recovery: 39, wRISP: 45, vsLefty: 42, poise: 46, heater: 0, agile: 48,
      abilities: ["Defensive Artisan", "Express Baserunning"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Chris", lastName: "Newstrom", position: "2B", eligibility: "SO", homeState: "TX", hometown: "Humble", jerseyNumber: 6,
      hitForAvg: 59, power: 47, speed: 52, arm: 59, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 52, grit: 59, stealing: 33, running: 51, throwing: 60, recovery: 47, wRISP: 55, vsLefty: 51, poise: 56, heater: 0, agile: 55,
      abilities: ["Chance Maker"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Levi", lastName: "Clark", position: "1B", eligibility: "SO", homeState: "TN", hometown: "Franklin", jerseyNumber: 18,
      hitForAvg: 58, power: 56, speed: 41, arm: 55, fielding: 56, errorResistance: 55, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 53, grit: 58, stealing: 16, running: 39, throwing: 56, recovery: 46, wRISP: 55, vsLefty: 51, poise: 56, heater: 0, agile: 42,
      abilities: ["Power Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Jay", lastName: "Abernathy", position: "3B", eligibility: "SO", homeState: "TN", hometown: "Murfreesboro", jerseyNumber: 10,
      hitForAvg: 51, power: 46, speed: 43, arm: 56, fielding: 54, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 46, grit: 51, stealing: 23, running: 41, throwing: 57, recovery: 41, wRISP: 48, vsLefty: 45, poise: 49, heater: 0, agile: 45,
      abilities: ["Contact Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Cole", lastName: "Pennington", position: "SS", eligibility: "FR", homeState: "TN", hometown: "Sevierville", jerseyNumber: 24,
      hitForAvg: 34, power: 28, speed: 45, arm: 44, fielding: 40, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 33, vsLHP: 30, grit: 34, stealing: 28, running: 44, throwing: 45, recovery: 29, wRISP: 30, vsLefty: 29, poise: 33, heater: 0, agile: 46,
      abilities: ["Line Drive", "Late Night Hero", "Unpredictable"], potential: "A-", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (9)
    { firstName: "Henry", lastName: "Ford", position: "OF", eligibility: "JR", homeState: "VA", hometown: "Richmond", jerseyNumber: 1,
      hitForAvg: 54, power: 55, speed: 46, arm: 51, fielding: 49, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 51, grit: 55, stealing: 29, running: 45, throwing: 52, recovery: 42, wRISP: 54, vsLefty: 49, poise: 54, heater: 0, agile: 48,
      abilities: ["Power Hitter", "Consigliere", "High-Speed Laser"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Reese", lastName: "Chapman", position: "OF", eligibility: "SR", homeState: "TN", hometown: "Memphis", jerseyNumber: 3,
      hitForAvg: 49, power: 43, speed: 46, arm: 49, fielding: 48, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 46, grit: 49, stealing: 29, running: 43, throwing: 51, recovery: 41, wRISP: 47, vsLefty: 43, poise: 48, heater: 0, agile: 47,
      abilities: ["Contact Hitter", "High-Speed Laser"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Manny", lastName: "Marin", position: "OF", eligibility: "SO", homeState: "FL", hometown: "Miami", jerseyNumber: 7,
      hitForAvg: 46, power: 37, speed: 50, arm: 47, fielding: 47, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 43, vsLHP: 40, grit: 45, stealing: 36, running: 49, throwing: 49, recovery: 37, wRISP: 42, vsLefty: 38, poise: 43, heater: 0, agile: 51,
      abilities: ["Express Baserunning", "Chance Maker"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Brady", lastName: "Neal", position: "OF", eligibility: "FR", homeState: "GA", hometown: "Savannah", jerseyNumber: 20,
      hitForAvg: 36, power: 33, speed: 45, arm: 45, fielding: 39, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 35, vsLHP: 33, grit: 36, stealing: 27, running: 42, throwing: 46, recovery: 32, wRISP: 33, vsLefty: 32, poise: 35, heater: 0, agile: 46,
      abilities: ["Trickster", "Contact Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Grant", lastName: "Cherry", position: "OF", eligibility: "JR", homeState: "TN", hometown: "Hendersonville", jerseyNumber: 9,
      hitForAvg: 46, power: 40, speed: 43, arm: 48, fielding: 46, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 41, grit: 46, stealing: 27, running: 41, throwing: 48, recovery: 37, wRISP: 43, vsLefty: 40, poise: 44, heater: 0, agile: 44,
      abilities: ["Contact Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jared", lastName: "Dickey", position: "C", eligibility: "SO", homeState: "TN", hometown: "Franklin", jerseyNumber: 14,
      hitForAvg: 34, power: 32, speed: 22, arm: 39, fielding: 37, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 33, vsLHP: 31, grit: 34, stealing: 9, running: 21, throwing: 40, recovery: 28, wRISP: 32, vsLefty: 29, poise: 33, heater: 0, agile: 24,
      abilities: ["Bases Loaded King", "Contact Hitter"], potential: "B+", catcherAbility: 35,
      ...noPitches },
    { firstName: "Dylan", lastName: "Dreiling", position: "1B", eligibility: "SO", homeState: "TN", hometown: "Knoxville", jerseyNumber: 16,
      hitForAvg: 47, power: 46, speed: 35, arm: 47, fielding: 49, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 46, vsLHP: 43, grit: 47, stealing: 13, running: 33, throwing: 49, recovery: 38, wRISP: 44, vsLefty: 41, poise: 46, heater: 0, agile: 37,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Brock", lastName: "Taylor", position: "OF", eligibility: "FR", homeState: "TN", hometown: "Brentwood", jerseyNumber: 26,
      hitForAvg: 33, power: 29, speed: 43, arm: 41, fielding: 37, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 30, grit: 33, stealing: 26, running: 41, throwing: 43, recovery: 29, wRISP: 30, vsLefty: 29, poise: 32, heater: 0, agile: 44,
      abilities: ["God of Pinch Hitting"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Gavin", lastName: "Turley", position: "3B", eligibility: "SO", homeState: "AL", hometown: "Huntsville", jerseyNumber: 27,
      hitForAvg: 33, power: 29, speed: 33, arm: 39, fielding: 36, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 32, vsLHP: 29, grit: 33, stealing: 18, running: 32, throwing: 40, recovery: 28, wRISP: 31, vsLefty: 28, poise: 32, heater: 0, agile: 34,
      abilities: ["Good Bunt"], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Ole Miss": [
      // 33-17/12-12 SEC, D1B #20, RPI #13, Mike Bianco Yr 26. 7 of last 9 SEC + sweep of LSU.
      // PITCHERS (10) — 1-8 pitch scale
      // Hunter Elliott — Friday SR LHP, preseason All-SEC 1st team, only returning P with 100K + 10W in 2025 — TEAM ELITE STUFF
      { firstName: "Hunter", lastName: "Elliott", position: "P", eligibility: "SR", homeState: "MS", hometown: "Tupelo", jerseyNumber: 34,
        hitForAvg: 16, power: 12, speed: 38, arm: 65, fielding: 41, errorResistance: 54, velocity: 65, control: 69, stamina: 69, stuff: 74,
        clutch: 80, vsLHP: 84, grit: 80, stealing: 10, running: 32, throwing: 78, recovery: 57, wRISP: 65, vsLefty: 69, poise: 65, heater: 65, agile: 44,
        abilities: ["Star of Victory", "Heavy Ball", "Guts", "Intimidator"], potential: "A+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [6, 0, 0, 1, 0, 6, 0]) },
      // Cade Townsend — Saturday JR RHP, 5-1/2.42, .193 BAA, SEC Co-Pitcher of Week
      { firstName: "Cade", lastName: "Townsend", position: "P", eligibility: "JR", homeState: "MS", hometown: "Madison", jerseyNumber: 29,
        hitForAvg: 14, power: 11, speed: 34, arm: 63, fielding: 35, errorResistance: 46, velocity: 61, control: 63, stamina: 63, stuff: 63,
        clutch: 76, vsLHP: 70, grit: 76, stealing: 9, running: 32, throwing: 76, recovery: 51, wRISP: 56, vsLefty: 56, poise: 61, heater: 63, agile: 42,
        abilities: ["Strong Starter", "Inside Pitch", "Doctor K", "Wild Fastball"], potential: "A", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
      // Taylor Rabe — Sunday JR RHP, 3-3/4.17, 6.67 K/BB SEC (2nd)
      { firstName: "Taylor", lastName: "Rabe", position: "P", eligibility: "JR", homeState: "MS", hometown: "Hattiesburg", jerseyNumber: 40,
        hitForAvg: 13, power: 10, speed: 32, arm: 55, fielding: 33, errorResistance: 44, velocity: 57, control: 63, stamina: 55, stuff: 57,
        clutch: 66, vsLHP: 60, grit: 66, stealing: 8, running: 30, throwing: 68, recovery: 47, wRISP: 47, vsLefty: 50, poise: 52, heater: 57, agile: 40,
        abilities: ["Strong Starter", "Inside Pitch", "Straddle", "Showtime"], potential: "A-", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 5, 1, 0, 0, 0]) },
      // Walker Hooks — closer LHP, 3-1/2.45/5 SV (T-2nd SEC)/.176 BAA, 0.82 WHIP
      { firstName: "Walker", lastName: "Hooks", position: "P", eligibility: "JR", homeState: "MS", hometown: "Oxford", jerseyNumber: 31,
        hitForAvg: 12, power: 10, speed: 32, arm: 60, fielding: 33, errorResistance: 44, velocity: 61, control: 62, stamina: 40, stuff: 62,
        clutch: 80, vsLHP: 80, grit: 76, stealing: 8, running: 30, throwing: 74, recovery: 44, wRISP: 62, vsLefty: 63, poise: 63, heater: 62, agile: 40,
        abilities: ["Fireman", "Inside Pitch"], potential: "A", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [5, 0, 6, 1, 0, 0, 0]) },
      // Landon Waters — setup RHP, 0.90 ERA / 1.05 WHIP / .159 BAA
      { firstName: "Landon", lastName: "Waters", position: "P", eligibility: "JR", homeState: "TN", hometown: "Memphis", jerseyNumber: 25,
        hitForAvg: 12, power: 10, speed: 32, arm: 56, fielding: 33, errorResistance: 44, velocity: 58, control: 54, stamina: 39, stuff: 57,
        clutch: 76, vsLHP: 70, grit: 70, stealing: 8, running: 30, throwing: 70, recovery: 44, wRISP: 54, vsLefty: 50, poise: 59, heater: 57, agile: 40,
        abilities: ["Fireman", "Doctor K", "vs. Strong Batters"], potential: "A-", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 0, 1, 0, 4, 0]) },
      // Aiden Sims — RHP, 3 straight quality road starts SEC (Florida/LSU/Missouri)
      { firstName: "Aiden", lastName: "Sims", position: "P", eligibility: "FR", homeState: "AL", hometown: "Mobile", jerseyNumber: 36,
        hitForAvg: 13, power: 10, speed: 33, arm: 54, fielding: 33, errorResistance: 44, velocity: 56, control: 53, stamina: 53, stuff: 54,
        clutch: 64, vsLHP: 58, grit: 66, stealing: 8, running: 30, throwing: 68, recovery: 45, wRISP: 47, vsLefty: 47, poise: 51, heater: 56, agile: 40,
        abilities: ["Strong Starter", "Doctor K", "Flyball Pitcher"], potential: "A-", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
      // Wil Libbert — JR RHP rotation depth
      { firstName: "Wil", lastName: "Libbert", position: "P", eligibility: "JR", homeState: "MO", hometown: "Columbia", jerseyNumber: 22,
        hitForAvg: 14, power: 12, speed: 34, arm: 52, fielding: 32, errorResistance: 44, velocity: 55, control: 51, stamina: 49, stuff: 52,
        clutch: 60, vsLHP: 56, grit: 62, stealing: 9, running: 32, throwing: 66, recovery: 43, wRISP: 43, vsLefty: 46, poise: 48, heater: 54, agile: 38,
        abilities: ["Strong Starter", "Explosive Fastball", "Guts"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 6, 1, 0, 0, 0]) },
      // Hudson Calhoun — JR RHP RP
      { firstName: "Hudson", lastName: "Calhoun", position: "P", eligibility: "JR", homeState: "MS", hometown: "Jackson", jerseyNumber: 38,
        hitForAvg: 13, power: 10, speed: 34, arm: 52, fielding: 32, errorResistance: 44, velocity: 54, control: 50, stamina: 43, stuff: 52,
        clutch: 60, vsLHP: 56, grit: 62, stealing: 8, running: 32, throwing: 66, recovery: 41, wRISP: 43, vsLefty: 46, poise: 47, heater: 54, agile: 38,
        abilities: ["Fireman", "Intimidator"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 5, 1, 0, 0, 0]) },
      // Cole Carbone — JR RHP depth
      { firstName: "Cole", lastName: "Carbone", position: "P", eligibility: "JR", homeState: "AL", hometown: "Huntsville", jerseyNumber: 42,
        hitForAvg: 10, power: 8, speed: 26, arm: 31, fielding: 19, errorResistance: 30, velocity: 31, control: 31, stamina: 29, stuff: 31,
        clutch: 40, vsLHP: 38, grit: 42, stealing: 7, running: 24, throwing: 44, recovery: 25, wRISP: 25, vsLefty: 27, poise: 28, heater: 32, agile: 28,
        abilities: ["Guts"], potential: "B", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 4, 5, 1, 0, 0, 0]) },
      // Grayson Saunier — FR RHP
      { firstName: "Grayson", lastName: "Saunier", position: "P", eligibility: "FR", homeState: "LA", hometown: "Baton Rouge", jerseyNumber: 48,
        hitForAvg: 11, power: 8, speed: 36, arm: 41, fielding: 24, errorResistance: 36, velocity: 42, control: 34, stamina: 32, stuff: 41,
        clutch: 38, vsLHP: 36, grit: 40, stealing: 11, running: 32, throwing: 56, recovery: 27, wRISP: 25, vsLefty: 28, poise: 28, heater: 42, agile: 38,
        abilities: ["Explosive Fastball"], potential: "A", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 4, 4, 1, 0, 0, 0]) },
      // CATCHERS (2)
      // Austin Fawley — JR C, projected starter
      { firstName: "Austin", lastName: "Fawley", position: "C", eligibility: "JR", homeState: "VA", hometown: "Roanoke", jerseyNumber: 12,
        hitForAvg: 60, power: 56, speed: 30, arm: 60, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 60, vsLHP: 54, grit: 60, stealing: 12, running: 28, throwing: 60, recovery: 46, wRISP: 60, vsLefty: 54, poise: 60, heater: 0, agile: 32,
        abilities: ["Power Hitter", "Defensive Artisan", "High-Speed Laser"], potential: "A", catcherAbility: 56,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Gage Oelke — SO C backup
      { firstName: "Gage", lastName: "Oelke", position: "C", eligibility: "FR", homeState: "MS", hometown: "Meridian", jerseyNumber: 14,
        hitForAvg: 40, power: 36, speed: 28, arm: 46, fielding: 44, errorResistance: 40, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 38, vsLHP: 34, grit: 38, stealing: 10, running: 26, throwing: 46, recovery: 34, wRISP: 36, vsLefty: 32, poise: 38, heater: 0, agile: 28,
        abilities: ["Puller Hitter"], potential: "B+", catcherAbility: 42,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // INFIELDERS (7)
      // Judd Utermark — 3B JR, primary power source — TEAM ELITE POWER
      { firstName: "Judd", lastName: "Utermark", position: "3B", eligibility: "JR", homeState: "IA", hometown: "Dubuque", jerseyNumber: 5,
        hitForAvg: 70, power: 90, speed: 36, arm: 56, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 80, vsLHP: 76, grit: 80, stealing: 14, running: 34, throwing: 56, recovery: 44, wRISP: 80, vsLefty: 76, poise: 80, heater: 0, agile: 40,
        abilities: ["Artist", "Consigliere", "Power Hitter"], potential: "A+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Will Furniss — 1B JR
      { firstName: "Will", lastName: "Furniss", position: "1B", eligibility: "JR", homeState: "TX", hometown: "Houston", jerseyNumber: 18,
        hitForAvg: 56, power: 56, speed: 32, arm: 50, fielding: 56, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 56, vsLHP: 52, grit: 56, stealing: 12, running: 32, throwing: 50, recovery: 42, wRISP: 56, vsLefty: 52, poise: 56, heater: 0, agile: 36,
        abilities: ["Power Hitter", "Contact Hitter"], potential: "A-", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Dom Decker — 2B JR (Murray State transfer, eliminated Ole Miss in 2025)
      { firstName: "Dom", lastName: "Decker", position: "2B", eligibility: "JR", homeState: "KY", hometown: "Murray", jerseyNumber: 10,
        hitForAvg: 60, power: 46, speed: 50, arm: 52, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 56, vsLHP: 52, grit: 58, stealing: 32, running: 46, throwing: 54, recovery: 42, wRISP: 54, vsLefty: 50, poise: 56, heater: 0, agile: 50,
        abilities: ["Chance Maker", "Contact Hitter"], potential: "A-", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Brayden Randle — SS JR clutch (winning RBI in 8th vs LSU)
      { firstName: "Brayden", lastName: "Randle", position: "SS", eligibility: "JR", homeState: "MS", hometown: "Brandon", jerseyNumber: 2,
        hitForAvg: 56, power: 42, speed: 50, arm: 60, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 80, vsLHP: 60, grit: 70, stealing: 34, running: 48, throwing: 60, recovery: 42, wRISP: 80, vsLefty: 56, poise: 70, heater: 0, agile: 50,
        abilities: ["Defensive Artisan", "Express Baserunning", "Consigliere"], potential: "A-", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Owen Paino — DH/INF projected starter
      { firstName: "Owen", lastName: "Paino", position: "3B", eligibility: "JR", homeState: "NY", hometown: "Yonkers", jerseyNumber: 6,
        hitForAvg: 60, power: 60, speed: 32, arm: 50, fielding: 48, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 60, vsLHP: 56, grit: 60, stealing: 12, running: 32, throwing: 50, recovery: 42, wRISP: 60, vsLefty: 56, poise: 60, heater: 0, agile: 38,
        abilities: ["Power Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Peyton Stovall — 2B JR
      { firstName: "Peyton", lastName: "Stovall", position: "2B", eligibility: "JR", homeState: "AR", hometown: "Heber Springs", jerseyNumber: 8,
        hitForAvg: 60, power: 50, speed: 50, arm: 56, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 58, vsLHP: 54, grit: 60, stealing: 30, running: 48, throwing: 58, recovery: 48, wRISP: 56, vsLefty: 52, poise: 58, heater: 0, agile: 50,
        abilities: ["Contact Hitter"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Marcus Nance — SS FR
      { firstName: "Marcus", lastName: "Nance", position: "SS", eligibility: "FR", homeState: "TN", hometown: "Nashville", jerseyNumber: 24,
        hitForAvg: 32, power: 28, speed: 46, arm: 42, fielding: 38, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 30, vsLHP: 28, grit: 32, stealing: 28, running: 42, throwing: 44, recovery: 28, wRISP: 28, vsLefty: 26, poise: 30, heater: 0, agile: 46,
        abilities: ["Express Baserunning"], potential: "A-", catcherAbility: null,
        skinTone: "deep", hairColor: "black", hairStyle: "fade",
        ...noPitches },
      // OUTFIELDERS (6)
      // Tristan Bissetta — OF JR, 5 HRs in week 6 (Baseball America Team of Week)
      { firstName: "Tristan", lastName: "Bissetta", position: "OF", eligibility: "JR", homeState: "SC", hometown: "Clemson", jerseyNumber: 7,
        hitForAvg: 64, power: 76, speed: 54, arm: 60, fielding: 58, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 70, vsLHP: 64, grit: 70, stealing: 34, running: 52, throwing: 60, recovery: 46, wRISP: 70, vsLefty: 64, poise: 70, heater: 0, agile: 56,
        abilities: ["Artist", "Contact Hitter", "Power Hitter"], potential: "A", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Hayden Federico — OF JR everyday
      { firstName: "Hayden", lastName: "Federico", position: "OF", eligibility: "JR", homeState: "MS", hometown: "Southaven", jerseyNumber: 1,
        hitForAvg: 50, power: 42, speed: 56, arm: 50, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 50, vsLHP: 46, grit: 50, stealing: 38, running: 50, throwing: 50, recovery: 42, wRISP: 48, vsLefty: 44, poise: 50, heater: 0, agile: 56,
        abilities: ["Express Baserunning", "Chance Maker"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Daniel Pacella — OF JR
      { firstName: "Daniel", lastName: "Pacella", position: "OF", eligibility: "JR", homeState: "IL", hometown: "Normal", jerseyNumber: 3,
        hitForAvg: 56, power: 56, speed: 42, arm: 52, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 56, vsLHP: 52, grit: 56, stealing: 22, running: 40, throwing: 54, recovery: 42, wRISP: 56, vsLefty: 50, poise: 56, heater: 0, agile: 42,
        abilities: ["Power Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Ethan Lyle — OF FR
      { firstName: "Ethan", lastName: "Lyle", position: "OF", eligibility: "FR", homeState: "MS", hometown: "Starkville", jerseyNumber: 20,
        hitForAvg: 38, power: 34, speed: 48, arm: 46, fielding: 42, errorResistance: 40, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 36, vsLHP: 34, grit: 38, stealing: 30, running: 46, throwing: 46, recovery: 32, wRISP: 34, vsLefty: 32, poise: 36, heater: 0, agile: 48,
        abilities: ["Multi-Hit", "Iron Man"], potential: "A-", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Luke Holman — OF JR
      { firstName: "Luke", lastName: "Holman", position: "OF", eligibility: "JR", homeState: "MS", hometown: "Biloxi", jerseyNumber: 9,
        hitForAvg: 42, power: 36, speed: 38, arm: 42, fielding: 40, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 40, vsLHP: 36, grit: 40, stealing: 22, running: 36, throwing: 42, recovery: 32, wRISP: 38, vsLefty: 36, poise: 40, heater: 0, agile: 38,
        abilities: ["High-Speed Laser"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Carter Martin — OF SO
      { firstName: "Carter", lastName: "Martin", position: "OF", eligibility: "SO", homeState: "AL", hometown: "Mobile", jerseyNumber: 26,
        hitForAvg: 34, power: 30, speed: 34, arm: 38, fielding: 34, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 32, vsLHP: 30, grit: 32, stealing: 22, running: 32, throwing: 38, recovery: 28, wRISP: 30, vsLefty: 28, poise: 32, heater: 0, agile: 36,
        abilities: ["vs. Ace"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
    ],
};
