import type { RealPlayer } from "./realRosters";
import { pitchMix, noPitches } from "./pitchMixHelpers";

export const SEC_BATCH2_ROSTERS: Record<string, RealPlayer[]> = {
  "Arkansas": [
      // 32-17/13-11 SEC, D1B #17, Dave Van Horn Yr 24. Lost entire 2025 rotation (Root/Biedelschies/Wood drafted), plus Aloy/Davalan/Foutch.
      // PITCHERS (10) — 1-8 pitch scale
      // Gabe Gaeckle — Friday JR RHP, 2.06 ERA / 35 IP relief 2025, transitioning to starter — TEAM ELITE STUFF
      { firstName: "Gabe", lastName: "Gaeckle", position: "P", eligibility: "JR", homeState: "MO", hometown: "Springfield", jerseyNumber: 22,
        hitForAvg: 16, power: 12, speed: 33, arm: 65, fielding: 40, errorResistance: 54, velocity: 66, control: 56, stamina: 80, stuff: 70,
        clutch: 80, vsLHP: 76, grit: 68, stealing: 10, running: 34, throwing: 78, recovery: 51, wRISP: 61, vsLefty: 61, poise: 65, heater: 68, agile: 44,
        abilities: ["Kageura", "Heavy Ball", "Winner's Luck", "Strikeout"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [1, 0, 0, 0, 4, 4, 4, 0, 0, 0]) },
      // Cole Gibler — LHP Saturday starter
      { firstName: "Cole", lastName: "Gibler", position: "P", eligibility: "JR", homeState: "AR", hometown: "Fayetteville", jerseyNumber: 32,
        hitForAvg: 14, power: 10, speed: 32, arm: 59, fielding: 35, errorResistance: 46, velocity: 56, control: 59, stamina: 86, stuff: 56,
        clutch: 70, vsLHP: 76, grit: 68, stealing: 8, running: 30, throwing: 72, recovery: 51, wRISP: 51, vsLefty: 60, poise: 56, heater: 60, agile: 40,
        abilities: ["Strong Starter", "Fireman", "Kageura", "Natural Shuuto"], potential: "A-", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [6, 0, 0, 0, 0, 4, 0, 1, 0, 0]) },
      // Colin Fisher — LHP JR Sat/Sun
      { firstName: "Colin", lastName: "Fisher", position: "P", eligibility: "JR", homeState: "AR", hometown: "Little Rock", jerseyNumber: 37,
        hitForAvg: 13, power: 10, speed: 32, arm: 55, fielding: 33, errorResistance: 44, velocity: 52, control: 55, stamina: 83, stuff: 51,
        clutch: 64, vsLHP: 74, grit: 66, stealing: 8, running: 30, throwing: 68, recovery: 47, wRISP: 47, vsLefty: 58, poise: 51, heater: 56, agile: 40,
        abilities: ["Fireman", "Sharpness", "Natural Shuuto"], potential: "B+", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [1, 3, 0, 0, 0, 0, 4, 0, 1, 0]) },
      // Ethan McElvain — LHP Vanderbilt transfer
      { firstName: "Ethan", lastName: "McElvain", position: "P", eligibility: "SO", homeState: "TN", hometown: "Nashville", jerseyNumber: 39,
        hitForAvg: 13, power: 10, speed: 32, arm: 57, fielding: 33, errorResistance: 44, velocity: 55, control: 54, stamina: 90, stuff: 55,
        clutch: 66, vsLHP: 74, grit: 66, stealing: 8, running: 30, throwing: 70, recovery: 47, wRISP: 47, vsLefty: 58, poise: 51, heater: 60, agile: 40,
        abilities: ["Fireman", "Constant Speed", "Heavy Ball"], potential: "A", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [1, 0, 0, 1, 0, 0, 4, 0, 0, 0]) },
      // Hunter Dietz — SO RHP, 9K vs Ole Miss in 6 IP
      { firstName: "Hunter", lastName: "Dietz", position: "P", eligibility: "SO", homeState: "TX", hometown: "Katy", jerseyNumber: 45,
        hitForAvg: 12, power: 10, speed: 32, arm: 54, fielding: 33, errorResistance: 44, velocity: 54, control: 50, stamina: 52, stuff: 53,
        clutch: 64, vsLHP: 60, grit: 66, stealing: 8, running: 30, throwing: 68, recovery: 45, wRISP: 47, vsLefty: 48, poise: 51, heater: 58, agile: 40,
        abilities: ["Strong Starter", "vs. Strong Batters", "Pace"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 3, 1, 0, 4, 4, 0, 0, 0]) },
      // Tate McGuire — JR RHP closer/RP
      { firstName: "Tate", lastName: "McGuire", position: "P", eligibility: "JR", homeState: "OK", hometown: "Tulsa", jerseyNumber: 41,
        hitForAvg: 14, power: 10, speed: 32, arm: 57, fielding: 34, errorResistance: 46, velocity: 56, control: 54, stamina: 40, stuff: 54,
        clutch: 70, vsLHP: 64, grit: 68, stealing: 9, running: 32, throwing: 72, recovery: 44, wRISP: 50, vsLefty: 51, poise: 54, heater: 59, agile: 40,
        abilities: ["Fireman", "Guts"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 0, 0, 0, 0]) },
      // Ryan Fry — JR RHP RP
      { firstName: "Ryan", lastName: "Fry", position: "P", eligibility: "JR", homeState: "AR", hometown: "Hot Springs", jerseyNumber: 35,
        hitForAvg: 12, power: 9, speed: 31, arm: 48, fielding: 30, errorResistance: 42, velocity: 44, control: 48, stamina: 32, stuff: 45,
        clutch: 58, vsLHP: 54, grit: 60, stealing: 8, running: 28, throwing: 62, recovery: 39, wRISP: 42, vsLefty: 44, poise: 45, heater: 50, agile: 38,
        abilities: ["Release", "Constant Speed", "Inside Pitch"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 0, 0, 0, 4, 1, 0, 4]) },
      // Peyton Lee — FR RHP — PG 1st Team / Top-100 national
      { firstName: "Peyton", lastName: "Lee", position: "P", eligibility: "FR", homeState: "AR", hometown: "Bentonville", jerseyNumber: 49,
        hitForAvg: 11, power: 8, speed: 32, arm: 49, fielding: 22, errorResistance: 34, velocity: 57, control: 42, stamina: 41, stuff: 48,
        clutch: 36, vsLHP: 34, grit: 38, stealing: 10, running: 30, throwing: 54, recovery: 26, wRISP: 24, vsLefty: 26, poise: 25, heater: 41, agile: 36,
        abilities: ["True Slider", "Tunneling"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 0, 0, 4, 4, 0, 1, 0]) },
      // Kade Smith — JR RHP depth
      { firstName: "Kade", lastName: "Smith", position: "P", eligibility: "JR", homeState: "OK", hometown: "Norman", jerseyNumber: 43,
        hitForAvg: 10, power: 8, speed: 30, arm: 32, fielding: 20, errorResistance: 32, velocity: 31, control: 31, stamina: 13, stuff: 34,
        clutch: 42, vsLHP: 40, grit: 44, stealing: 7, running: 24, throwing: 46, recovery: 27, wRISP: 27, vsLefty: 28, poise: 30, heater: 34, agile: 28,
        abilities: ["Constant Speed", "Sharpness"], potential: "B", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4, 0, 0, 0]) },
      // Tyler Webb — FR depth
      // CATCHERS (2)
      // Ryder Helfrick — JR C, 15 multi-RBI games (#2 team), top draft prospect
      { firstName: "Ryder", lastName: "Helfrick", position: "C", eligibility: "JR", homeState: "FL", hometown: "Tampa", jerseyNumber: 12,
        hitForAvg: 63, power: 75, speed: 55, arm: 63, fielding: 53, errorResistance: 43, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 65, vsLHP: 58, grit: 52, stealing: 51, running: 51, throwing: 59, recovery: 50, wRISP: 76, vsLefty: 70, poise: 76, heater: 0, agile: 38,
        abilities: ["Trash Talker", "vs. Breaking Pitches", "Power Hitter", "Consigliere"], potential: "A+", catcherAbility: 64,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Brendan Kleiman — SR C
      { firstName: "Brendan", lastName: "Kleiman", position: "C", eligibility: "SR", homeState: "MI", hometown: "Ypsilanti", jerseyNumber: 24,
        hitForAvg: 45, power: 41, speed: 59, arm: 53, fielding: 48, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 43, vsLHP: 43, grit: 38, stealing: 32, running: 37, throwing: 56, recovery: 32, wRISP: 38, vsLefty: 34, poise: 38, heater: 0, agile: 28,
        abilities: ["Spray Hitter", "Resilient", "Home Defense"], potential: "B+", catcherAbility: 42,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // INFIELDERS (7)
      // Camden Kozeal — 2B JR, 17 multi-hit games (team lead), top-100 2026 draft — TEAM ELITE HIT
      { firstName: "Camden", lastName: "Kozeal", position: "2B", eligibility: "JR", homeState: "CA", hometown: "Huntington Beach", jerseyNumber: 7,
        hitForAvg: 72, power: 68, speed: 66, arm: 49, fielding: 55, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 80, vsLHP: 76, grit: 68, stealing: 51, running: 51, throwing: 60, recovery: 46, wRISP: 80, vsLefty: 76, poise: 80, heater: 0, agile: 52,
        abilities: ["High Ball Hitter", "High Speed Charge", "Power Hitter", "Consigliere"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // TJ Pompey — SS JR, 8 multi-hit, 6 multi-RBI
      { firstName: "TJ", lastName: "Pompey", position: "SS", eligibility: "JR", homeState: "TX", hometown: "Lubbock", jerseyNumber: 2,
        hitForAvg: 63, power: 69, speed: 64, arm: 48, fielding: 38, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 56, vsLHP: 52, grit: 58, stealing: 51, running: 50, throwing: 68, recovery: 44, wRISP: 56, vsLefty: 52, poise: 56, heater: 0, agile: 56,
        abilities: ["Revenge", "Power Hitter", "Defensive Artisan"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Reese Robinett — 1B JR
      { firstName: "Reese", lastName: "Robinett", position: "1B", eligibility: "JR", homeState: "AR", hometown: "Fayetteville", jerseyNumber: 18,
        hitForAvg: 64, power: 63, speed: 39, arm: 57, fielding: 67, errorResistance: 61, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 64, vsLHP: 54, grit: 52, stealing: 51, running: 51, throwing: 52, recovery: 44, wRISP: 60, vsLefty: 54, poise: 60, heater: 0, agile: 40,
        abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Nolan Souza — 3B JR, 13 multi-hit games
      { firstName: "Nolan", lastName: "Souza", position: "3B", eligibility: "JR", homeState: "HI", hometown: "Honolulu", jerseyNumber: 10,
        hitForAvg: 64, power: 57, speed: 32, arm: 63, fielding: 64, errorResistance: 59, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 58, vsLHP: 54, grit: 60, stealing: 51, running: 51, throwing: 68, recovery: 44, wRISP: 58, vsLefty: 54, poise: 58, heater: 0, agile: 48,
        abilities: ["Contact Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Carson Brumbaugh — SS FR (Zack Stewart's role taken by Brumbaugh, 7 multi-hit)
      { firstName: "Carson", lastName: "Brumbaugh", position: "SS", eligibility: "FR", homeState: "AR", hometown: "Rogers", jerseyNumber: 1,
        hitForAvg: 63, power: 53, speed: 59, arm: 57, fielding: 53, errorResistance: 43, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 50, vsLHP: 51, grit: 54, stealing: 51, running: 58, throwing: 68, recovery: 42, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 60,
        abilities: ["Pull Hit", "Defensive Artisan"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Zack Stewart — 8 multi-hit games, contributing INF
      { firstName: "Zack", lastName: "Stewart", position: "3B", eligibility: "SO", homeState: "TX", hometown: "Houston", jerseyNumber: 11,
        hitForAvg: 57, power: 53, speed: 65, arm: 55, fielding: 47, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 51, vsLHP: 49, grit: 50, stealing: 53, running: 46, throwing: 66, recovery: 40, wRISP: 50, vsLefty: 46, poise: 48, heater: 0, agile: 44,
        abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Alexander Peck — 2B FR depth
      { firstName: "Alexander", lastName: "Peck", position: "2B", eligibility: "FR", homeState: "TX", hometown: "Austin", jerseyNumber: 15,
        hitForAvg: 41, power: 35, speed: 61, arm: 46, fielding: 37, errorResistance: 22, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 43, vsLHP: 38, grit: 35, stealing: 59, running: 56, throwing: 56, recovery: 30, wRISP: 30, vsLefty: 28, poise: 32, heater: 0, agile: 44,
        abilities: ["Chance Maker", "Contact Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // OUTFIELDERS (6)
      // Kuhio Aloy — DH/OF JR, 16 multi-hit, 11 multi-RBI, 13 HR/15 2B as SO, .600 vs Ole Miss — TEAM ELITE POWER
      { firstName: "Kuhio", lastName: "Aloy", position: "OF", eligibility: "JR", homeState: "HI", hometown: "Kailua", jerseyNumber: 4,
        hitForAvg: 69, power: 73, speed: 42, arm: 63, fielding: 66, errorResistance: 59, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 62, vsLHP: 62, grit: 60, stealing: 51, running: 51, throwing: 60, recovery: 46, wRISP: 80, vsLefty: 76, poise: 80, heater: 0, agile: 50,
        abilities: ["Legendary Walkoff Hitter", "Multi-Hit", "Consigliere", "Power Hitter"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Damian Ruiz — OF JR, 12 multi-hit, 5 multi-RBI
      { firstName: "Damian", lastName: "Ruiz", position: "OF", eligibility: "JR", homeState: "TX", hometown: "Beaumont", jerseyNumber: 8,
        hitForAvg: 64, power: 57, speed: 55, arm: 33, fielding: 66, errorResistance: 67, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 58, vsLHP: 54, grit: 58, stealing: 51, running: 51, throwing: 64, recovery: 42, wRISP: 58, vsLefty: 54, poise: 58, heater: 0, agile: 50,
        abilities: ["Contact Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Maika Niu — OF SR, 14 multi-hit
      { firstName: "Maika", lastName: "Niu", position: "OF", eligibility: "SR", homeState: "HI", hometown: "Ewa Beach", jerseyNumber: 6,
        hitForAvg: 64, power: 53, speed: 67, arm: 55, fielding: 50, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 56, vsLHP: 52, grit: 58, stealing: 51, running: 51, throwing: 60, recovery: 40, wRISP: 56, vsLefty: 52, poise: 56, heater: 0, agile: 50,
        abilities: ["Contact Hitter", "Pull Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Carter Rutenbar — OF, 10 multi-hit games
      { firstName: "Carter", lastName: "Rutenbar", position: "OF", eligibility: "SO", homeState: "CA", hometown: "Anaheim", jerseyNumber: 19,
        hitForAvg: 63, power: 57, speed: 45, arm: 67, fielding: 66, errorResistance: 55, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 54, vsLHP: 50, grit: 56, stealing: 51, running: 51, throwing: 62, recovery: 42, wRISP: 54, vsLefty: 50, poise: 54, heater: 0, agile: 50,
        abilities: ["Power Hitter"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Christian Turner — OF FR speedster
      { firstName: "Christian", lastName: "Turner", position: "OF", eligibility: "FR", homeState: "AR", hometown: "Jonesboro", jerseyNumber: 28,
        hitForAvg: 42, power: 36, speed: 66, arm: 37, fielding: 27, errorResistance: 19, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 43, vsLHP: 39, grit: 35, stealing: 59, running: 59, throwing: 50, recovery: 26, wRISP: 28, vsLefty: 26, poise: 28, heater: 0, agile: 50,
        abilities: ["Good Bunt"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "deep", hairColor: "black", hairStyle: "fade",
        ...noPitches },
      // Cole Phillips — OF JR
      { firstName: "Cole", lastName: "Phillips", position: "OF", eligibility: "JR", homeState: "AR", hometown: "Springdale", jerseyNumber: 16,
        hitForAvg: 61, power: 55, speed: 65, arm: 39, fielding: 33, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 52, vsLHP: 53, grit: 54, stealing: 59, running: 56, throwing: 66, recovery: 42, wRISP: 50, vsLefty: 46, poise: 52, heater: 0, agile: 52,
        abilities: ["Defensive Artisan", "Locked and Loaded"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "S",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
    { firstName: "Peyton", lastName: "Holt", position: "3B", eligibility: "JR", homeState: "AR", hometown: "Little Rock", jerseyNumber: 8,
      hitForAvg: 64, power: 46, speed: 50, arm: 60, fielding: 61, errorResistance: 68, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 57, grit: 64, stealing: 51, running: 50, throwing: 68, recovery: 54, wRISP: 60, vsLefty: 57, poise: 64, heater: 0, agile: 56,
      abilities: ["Good Infield Hit", "Chance Maker"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
],
  
  "Alabama": [
      // 33-17/14-11 SEC, D1B #19, Rob Vaughn Yr 3, RPI #9, 15-1 home. Tyler Fay no-hitter vs Florida (1st since 1942).
      // PITCHERS (10) — 1-8 pitch scale
      // Tyler Fay — Friday SR RHP, no-hitter vs Florida 3/20, 8-3, 7 IP/1 ER/10K vs SC — TEAM ELITE STUFF
      { firstName: "Tyler", lastName: "Fay", position: "P", eligibility: "SR", homeState: "AL", hometown: "Tuscaloosa", jerseyNumber: 34,
        hitForAvg: 16, power: 12, speed: 33, arm: 93, fielding: 62, errorResistance: 54, velocity: 98, control: 96, stamina: 80, stuff: 98,
        clutch: 86, vsLHP: 86, grit: 68, stealing: 10, running: 34, throwing: 86, recovery: 68, wRISP: 68, vsLefty: 68, poise: 68, heater: 68, agile: 44,
        abilities: ["vs. Strong Batters", "Strong Starter", "Heavy Ball", "Strikeout"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4, 0, 0, 0]) },
      // Zane Adams — Saturday JR LHP, most SEC starting experience on staff, All-SEC Frosh team 2024
      { firstName: "Zane", lastName: "Adams", position: "P", eligibility: "JR", homeState: "GA", hometown: "Savannah", jerseyNumber: 29,
        hitForAvg: 14, power: 11, speed: 32, arm: 60, fielding: 35, errorResistance: 46, velocity: 58, control: 56, stamina: 86, stuff: 57,
        clutch: 70, vsLHP: 76, grit: 68, stealing: 8, running: 32, throwing: 74, recovery: 51, wRISP: 51, vsLefty: 60, poise: 56, heater: 60, agile: 42,
        abilities: ["Strong Starter", "Fireman", "Low Ball"], potential: "A-", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [1, 3, 0, 0, 0, 0, 4, 1, 0, 0]) },
      // Owen Sarna — RHP Winthrop transfer Sunday contender, "throws nothing but strikes"
      { firstName: "Owen", lastName: "Sarna", position: "P", eligibility: "JR", homeState: "SC", hometown: "Rock Hill", jerseyNumber: 27,
        hitForAvg: 13, power: 10, speed: 32, arm: 55, fielding: 33, errorResistance: 44, velocity: 49, control: 63, stamina: 88, stuff: 52,
        clutch: 66, vsLHP: 60, grit: 66, stealing: 8, running: 30, throwing: 68, recovery: 47, wRISP: 47, vsLefty: 49, poise: 51, heater: 55, agile: 40,
        abilities: ["Inside Pitch", "Strong Starter", "Low Ball"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [1, 0, 0, 0, 0, 0, 4, 0, 1, 0]) },
      // Bobby Alcock — JR RHP weekend/RP, prior SEC Pitcher of Week
      { firstName: "Bobby", lastName: "Alcock", position: "P", eligibility: "JR", homeState: "FL", hometown: "Jacksonville", jerseyNumber: 42,
        hitForAvg: 13, power: 10, speed: 32, arm: 50, fielding: 31, errorResistance: 42, velocity: 47, control: 49, stamina: 96, stuff: 47,
        clutch: 60, vsLHP: 56, grit: 60, stealing: 9, running: 30, throwing: 64, recovery: 43, wRISP: 43, vsLefty: 44, poise: 46, heater: 51, agile: 38,
        abilities: ["Fireman", "Quick Hands", "Sharpness"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4, 0, 0, 0]) },
      // Matthew Heiberger — LHP fireman, 4 high-leverage IP vs Troy (1 H)
      { firstName: "Matthew", lastName: "Heiberger", position: "P", eligibility: "FR", homeState: "AL", hometown: "Birmingham", jerseyNumber: 33,
        hitForAvg: 12, power: 10, speed: 32, arm: 54, fielding: 32, errorResistance: 44, velocity: 50, control: 54, stamina: 60, stuff: 53,
        clutch: 70, vsLHP: 76, grit: 68, stealing: 8, running: 30, throwing: 68, recovery: 43, wRISP: 49, vsLefty: 59, poise: 54, heater: 56, agile: 40,
        abilities: ["Fireman", "Wild Fastball", "Staredown"], potential: "A-", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [1, 0, 0, 1, 0, 0, 4, 0, 0, 0]) },
      // Hagan Banks — JR RHP RP, 3.72 ERA in 17 apps 2025
      { firstName: "Hagan", lastName: "Banks", position: "P", eligibility: "JR", homeState: "AL", hometown: "Mobile", jerseyNumber: 21,
        hitForAvg: 12, power: 10, speed: 32, arm: 52, fielding: 30, errorResistance: 42, velocity: 49, control: 50, stamina: 42, stuff: 49,
        clutch: 64, vsLHP: 58, grit: 64, stealing: 8, running: 30, throwing: 66, recovery: 41, wRISP: 46, vsLefty: 46, poise: 49, heater: 51, agile: 38,
        abilities: ["Straddle", "Staredown"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 0, 4, 0, 0, 4]) },
      // Carson Ozmer — SR closer (school record SV holder)
      { firstName: "Carson", lastName: "Ozmer", position: "P", eligibility: "SR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 39,
        hitForAvg: 11, power: 9, speed: 32, arm: 58, fielding: 33, errorResistance: 44, velocity: 57, control: 55, stamina: 49, stuff: 58,
        clutch: 80, vsLHP: 70, grit: 68, stealing: 8, running: 30, throwing: 72, recovery: 44, wRISP: 60, vsLefty: 55, poise: 63, heater: 61, agile: 40,
        abilities: ["Fireman", "Crossfire", "Decisive"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 0, 0, 4, 0, 1, 0, 0]) },
      // Ashton Crowther — JR (South Carolina transfer)
      { firstName: "Ashton", lastName: "Crowther", position: "P", eligibility: "JR", homeState: "SC", hometown: "Columbia", jerseyNumber: 26,
        hitForAvg: 12, power: 10, speed: 32, arm: 50, fielding: 30, errorResistance: 42, velocity: 47, control: 49, stamina: 36, stuff: 47,
        clutch: 60, vsLHP: 56, grit: 60, stealing: 8, running: 30, throwing: 64, recovery: 41, wRISP: 42, vsLefty: 44, poise: 46, heater: 51, agile: 38,
        abilities: ["Full Throttle", "Wild Fastball"], potential: "B+", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 3, 0, 0, 4, 4, 0, 1, 0]) },
      // Myles Upchurch — FR RHP (19th rd Reds, opted to attend Alabama)
      { firstName: "Myles", lastName: "Upchurch", position: "P", eligibility: "FR", homeState: "GA", hometown: "Alpharetta", jerseyNumber: 48,
        hitForAvg: 11, power: 8, speed: 32, arm: 58, fielding: 33, errorResistance: 46, velocity: 63, control: 52, stamina: 47, stuff: 61,
        clutch: 60, vsLHP: 56, grit: 62, stealing: 10, running: 32, throwing: 70, recovery: 42, wRISP: 46, vsLefty: 48, poise: 50, heater: 62, agile: 40,
        abilities: ["Decisive", "Heavy Ball", "Sharpness"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4, 0, 0, 0]) },
      // Luke Smyers — FR LHP "budding superstar" (Vaughn)
      { firstName: "Luke", lastName: "Smyers", position: "P", eligibility: "FR", homeState: "TN", hometown: "Knoxville", jerseyNumber: 46,
        hitForAvg: 10, power: 8, speed: 32, arm: 52, fielding: 33, errorResistance: 46, velocity: 67, control: 57, stamina: 7, stuff: 64,
        clutch: 66, vsLHP: 76, grit: 68, stealing: 10, running: 30, throwing: 66, recovery: 44, wRISP: 51, vsLefty: 62, poise: 54, heater: 62, agile: 40,
        abilities: ["Wild Fastball", "Intimidator", "Sharpness", "Walk"], potential: "A+", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [1, 0, 0, 1, 0, 0, 4, 0, 0, 0]) },
      // CATCHERS (2)
      // Brady Neal — JR C, 40-game on-base streak — TEAM ELITE HIT
      { firstName: "Brady", lastName: "Neal", position: "C", eligibility: "JR", homeState: "FL", hometown: "Orlando", jerseyNumber: 14,
        hitForAvg: 69, power: 67, speed: 22, arm: 66, fielding: 58, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 64, vsLHP: 58, grit: 52, stealing: 51, running: 51, throwing: 56, recovery: 48, wRISP: 80, vsLefty: 76, poise: 80, heater: 0, agile: 38,
        abilities: ["Iron Wall", "Consigliere", "Defensive Artisan", "Push"], potential: "A+", catcherAbility: 56,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Will Plattner — SR C captain
      { firstName: "Will", lastName: "Plattner", position: "C", eligibility: "SR", homeState: "AL", hometown: "Vestavia Hills", jerseyNumber: 19,
        hitForAvg: 63, power: 57, speed: 29, arm: 48, fielding: 67, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 60, vsLHP: 54, grit: 64, stealing: 51, running: 51, throwing: 68, recovery: 48, wRISP: 56, vsLefty: 52, poise: 60, heater: 0, agile: 40,
        abilities: ["Defensive Artisan", "Tough Out"], potential: "B+", catcherAbility: 60,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // INFIELDERS (7)
      // Justin Lebron — SS JR, 3-run HR vs SC, reached 6 straight games, top draft prospect
      { firstName: "Justin", lastName: "Lebron", position: "SS", eligibility: "JR", homeState: "FL", hometown: "Miami", jerseyNumber: 1,
        hitForAvg: 63, power: 63, speed: 67, arm: 66, fielding: 54, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 58, vsLHP: 54, grit: 76, stealing: 60, running: 70, throwing: 59, recovery: 56, wRISP: 76, vsLefty: 70, poise: 76, heater: 0, agile: 64,
        abilities: ["Express Baserunning", "Power Hitter", "Defensive Artisan", "Consigliere"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Jason Torres — 1B JR, .333 (6-18) / 3 HR / 6 RBI hot stretch, OB 7 straight
      { firstName: "Jason", lastName: "Torres", position: "1B", eligibility: "JR", homeState: "FL", hometown: "Hialeah", jerseyNumber: 8,
        hitForAvg: 64, power: 64, speed: 55, arm: 49, fielding: 35, errorResistance: 61, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 68, vsLHP: 64, grit: 68, stealing: 51, running: 51, throwing: 66, recovery: 48, wRISP: 70, vsLefty: 64, poise: 70, heater: 0, agile: 42,
        abilities: ["Good Infield Hit", "Consigliere"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "S",
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
      // Luke Vaughn — 1B/utility, first-career multi-HR game vs SC (2-4 / 3 RBI)
      { firstName: "Luke", lastName: "Vaughn", position: "1B", eligibility: "SO", homeState: "AL", hometown: "Tuscaloosa", jerseyNumber: 25,
        hitForAvg: 64, power: 64, speed: 66, arm: 65, fielding: 50, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 61, vsLHP: 54, grit: 52, stealing: 51, running: 51, throwing: 52, recovery: 42, wRISP: 60, vsLefty: 54, poise: 60, heater: 0, agile: 36,
        abilities: ["Power Hitter"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Brennan Holt — 2B JR (S. Alabama transfer), everyday
      { firstName: "Brennan", lastName: "Holt", position: "2B", eligibility: "JR", homeState: "AL", hometown: "Mobile", jerseyNumber: 3,
        hitForAvg: 63, power: 51, speed: 50, arm: 63, fielding: 67, errorResistance: 57, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 54, vsLHP: 50, grit: 54, stealing: 51, running: 51, throwing: 66, recovery: 44, wRISP: 50, vsLefty: 46, poise: 54, heater: 0, agile: 50,
        abilities: ["Chance Maker"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Justin Osterhouse — 3B JR
      { firstName: "Justin", lastName: "Osterhouse", position: "3B", eligibility: "JR", homeState: "IN", hometown: "Fort Wayne", jerseyNumber: 5,
        hitForAvg: 63, power: 63, speed: 57, arm: 59, fielding: 39, errorResistance: 25, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 54, vsLHP: 50, grit: 56, stealing: 51, running: 51, throwing: 64, recovery: 44, wRISP: 54, vsLefty: 50, poise: 54, heater: 0, agile: 40,
        abilities: ["Power Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "S",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Will Rhine — SS FR
      { firstName: "Will", lastName: "Rhine", position: "SS", eligibility: "FR", homeState: "GA", hometown: "Marietta", jerseyNumber: 22,
        hitForAvg: 61, power: 52, speed: 60, arm: 68, fielding: 39, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 52, vsLHP: 51, grit: 54, stealing: 51, running: 52, throwing: 68, recovery: 44, wRISP: 50, vsLefty: 46, poise: 52, heater: 0, agile: 58,
        abilities: ["Resilient", "Contact Hitter"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Jake Woodfin — 3B SO depth
      { firstName: "Jake", lastName: "Woodfin", position: "3B", eligibility: "SO", homeState: "AL", hometown: "Decatur", jerseyNumber: 15,
        hitForAvg: 46, power: 42, speed: 58, arm: 34, fielding: 16, errorResistance: 61, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 46, vsLHP: 43, grit: 43, stealing: 50, running: 54, throwing: 50, recovery: 30, wRISP: 32, vsLefty: 30, poise: 34, heater: 0, agile: 30,
        abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // OUTFIELDERS (6)
      // Bryce Fowler — CF JR everyday
      { firstName: "Bryce", lastName: "Fowler", position: "OF", eligibility: "JR", homeState: "AL", hometown: "Huntsville", jerseyNumber: 11,
        hitForAvg: 63, power: 51, speed: 68, arm: 60, fielding: 42, errorResistance: 29, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 54, vsLHP: 50, grit: 54, stealing: 51, running: 50, throwing: 60, recovery: 40, wRISP: 50, vsLefty: 46, poise: 54, heater: 0, agile: 56,
        abilities: ["Chance Maker", "Unpredictable"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Coleman Mizell — OF JR
      { firstName: "Coleman", lastName: "Mizell", position: "OF", eligibility: "JR", homeState: "AL", hometown: "Auburn", jerseyNumber: 4,
        hitForAvg: 64, power: 61, speed: 57, arm: 45, fielding: 60, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 58, vsLHP: 54, grit: 60, stealing: 51, running: 51, throwing: 68, recovery: 46, wRISP: 58, vsLefty: 52, poise: 58, heater: 0, agile: 52,
        abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Peyton Steele — OF JR
      { firstName: "Peyton", lastName: "Steele", position: "OF", eligibility: "JR", homeState: "TN", hometown: "Nashville", jerseyNumber: 7,
        hitForAvg: 57, power: 51, speed: 52, arm: 34, fielding: 67, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 50, vsLHP: 55, grit: 43, stealing: 54, running: 58, throwing: 62, recovery: 38, wRISP: 46, vsLefty: 42, poise: 46, heater: 0, agile: 46,
        abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "S",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Eric Hines — FR OF — PG 2nd Team / Top-200 national (3-3 vs Samford, HR/3 RBI)
      { firstName: "Eric", lastName: "Hines", position: "OF", eligibility: "FR", homeState: "AL", hometown: "Pelham", jerseyNumber: 26,
        hitForAvg: 63, power: 57, speed: 66, arm: 64, fielding: 42, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 59, vsLHP: 57, grit: 43, stealing: 52, running: 55, throwing: 60, recovery: 38, wRISP: 46, vsLefty: 42, poise: 46, heater: 0, agile: 46,
        abilities: ["Power Hitter"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Brooks Miller — OF JR
      { firstName: "Brooks", lastName: "Miller", position: "OF", eligibility: "JR", homeState: "AL", hometown: "Dothan", jerseyNumber: 10,
        hitForAvg: 65, power: 53, speed: 62, arm: 43, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 50, vsLHP: 53, grit: 52, stealing: 53, running: 50, throwing: 68, recovery: 42, wRISP: 48, vsLefty: 44, poise: 50, heater: 0, agile: 50,
        abilities: ["Consigliere"], potential: "B+", catcherAbility: null,
        throwHand: "L", batHand: "S",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Johnny Lemm — OF JR
      { firstName: "Johnny", lastName: "Lemm", position: "OF", eligibility: "JR", homeState: "AL", hometown: "Madison", jerseyNumber: 9,
        hitForAvg: 55, power: 49, speed: 56, arm: 41, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 46, vsLHP: 51, grit: 50, stealing: 52, running: 55, throwing: 66, recovery: 40, wRISP: 46, vsLefty: 42, poise: 48, heater: 0, agile: 48,
        abilities: ["Spray Hitter", "Revenge"], potential: "B+", catcherAbility: null,
        throwHand: "L", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
    ],
  
  // Auburn — 33-15 / 15-11 SEC, D1B #6 (May 3), Butch Thompson Yr 11, RPI #4, SOS #1
  // Pitching staff: ERA 3rd, WHIP #1, K/BB #1, BB/9 #1 nationally
  "Auburn": [
    // PITCHERS (10)
    // Drew Whalen — RHP transfer Western Kentucky, 3.53/90K/31BB last yr, weekend SP
    { firstName: "Drew", lastName: "Whalen", position: "P", eligibility: "JR", homeState: "KY", hometown: "Bowling Green", jerseyNumber: 45,
      hitForAvg: 13, power: 10, speed: 32, arm: 65, fielding: 37, errorResistance: 50, velocity: 61, control: 68, stamina: 83, stuff: 62,
      clutch: 76, vsLHP: 72, grit: 69, stealing: 7, running: 30, throwing: 76, recovery: 51, wRISP: 58, vsLefty: 60, poise: 63, heater: 63, agile: 40,
      abilities: ["True Slider", "Sharpness", "Inside Pitch"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 3, 0, 1, 0, 4, 4, 0, 0, 0]) },
    // Jake Marciano — SO RHP, weekend SP — TEAM ELITE STUFF
    { firstName: "Jake", lastName: "Marciano", position: "P", eligibility: "SO", homeState: "NJ", hometown: "Marlton", jerseyNumber: 33,
      hitForAvg: 13, power: 10, speed: 32, arm: 92, fielding: 60, errorResistance: 50, velocity: 97, control: 95, stamina: 80, stuff: 97,
      clutch: 84, vsLHP: 84, grit: 69, stealing: 7, running: 30, throwing: 84, recovery: 69, wRISP: 69, vsLefty: 69, poise: 69, heater: 69, agile: 42,
      abilities: ["Quick Hands", "Strikeout", "Strong Starter", "Heavy Ball"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 0, 0, 0, 0, 5, 4, 1, 0, 0]) },
    // Jackson Sanders — SO breaking ball specialist
    { firstName: "Jackson", lastName: "Sanders", position: "P", eligibility: "SO", homeState: "GA", hometown: "Marietta", jerseyNumber: 37,
      hitForAvg: 12, power: 10, speed: 32, arm: 56, fielding: 34, errorResistance: 48, velocity: 51, control: 60, stamina: 84, stuff: 57,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 7, running: 28, throwing: 70, recovery: 44, wRISP: 50, vsLefty: 51, poise: 51, heater: 51, agile: 38,
      abilities: ["Strong Starter", "Sharpness", "Groundball Pitcher"], potential: "A", catcherAbility: null,
      throwHand: "L", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 0, 0, 0, 0, 4, 4, 0, 1, 0]) },
    // Garrett Brewer — JR LHP relief, 3.2 scoreless/6K vs Kentucky
    { firstName: "Garrett", lastName: "Brewer", position: "P", eligibility: "JR", homeState: "MI", hometown: "Eau Claire", jerseyNumber: 36,
      hitForAvg: 11, power: 9, speed: 31, arm: 55, fielding: 33, errorResistance: 46, velocity: 52, control: 59, stamina: 87, stuff: 55,
      clutch: 70, vsLHP: 80, grit: 69, stealing: 7, running: 28, throwing: 68, recovery: 42, wRISP: 51, vsLefty: 62, poise: 55, heater: 55, agile: 38,
      abilities: ["Fireman", "vs. Strong Batters"], potential: "A-", catcherAbility: null,
      throwHand: "L", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [1, 0, 0, 1, 0, 0, 4, 0, 0, 4]) },
    // Ryan Hetzler — JR closer, hard fastball
    { firstName: "Ryan", lastName: "Hetzler", position: "P", eligibility: "JR", homeState: "GA", hometown: "Cumming", jerseyNumber: 39,
      hitForAvg: 11, power: 9, speed: 32, arm: 59, fielding: 34, errorResistance: 46, velocity: 59, control: 54, stamina: 55, stuff: 56,
      clutch: 76, vsLHP: 70, grit: 69, stealing: 7, running: 30, throwing: 74, recovery: 44, wRISP: 56, vsLefty: 51, poise: 57, heater: 62, agile: 40,
      abilities: ["Fireman", "Natural Shuuto", "Full Throttle"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4, 0, 0, 0]) },
    // Alex Petrovic — SO RHP swing
    { firstName: "Alex", lastName: "Petrovic", position: "P", eligibility: "SO", homeState: "FL", hometown: "Coral Springs", jerseyNumber: 41,
      hitForAvg: 12, power: 10, speed: 32, arm: 50, fielding: 32, errorResistance: 44, velocity: 48, control: 50, stamina: 43, stuff: 47,
      clutch: 60, vsLHP: 58, grit: 62, stealing: 7, running: 28, throwing: 64, recovery: 43, wRISP: 44, vsLefty: 46, poise: 47, heater: 51, agile: 36,
      abilities: ["Good Pickoff", "Sharpness", "Wild Fastball"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4, 0, 0, 0]) },
    // Mason Barnett — FR RHP
    { firstName: "Mason", lastName: "Barnett", position: "P", eligibility: "FR", homeState: "AL", hometown: "Hoover", jerseyNumber: 49,
      hitForAvg: 10, power: 8, speed: 32, arm: 54, fielding: 31, errorResistance: 44, velocity: 58, control: 50, stamina: 30, stuff: 55,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 7, running: 28, throwing: 66, recovery: 40, wRISP: 44, vsLefty: 46, poise: 46, heater: 58, agile: 38,
      abilities: ["Strong Finisher", "Sharpness"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 0, 0, 0, 0, 4, 4, 1, 0, 0]) },
    // Landon Harper — FR RHP
    { firstName: "Landon", lastName: "Harper", position: "P", eligibility: "FR", homeState: "GA", hometown: "Peachtree City", jerseyNumber: 51,
      hitForAvg: 9, power: 7, speed: 30, arm: 37, fielding: 22, errorResistance: 33, velocity: 40, control: 32, stamina: 43, stuff: 34,
      clutch: 33, vsLHP: 31, grit: 35, stealing: 6, running: 26, throwing: 52, recovery: 23, wRISP: 22, vsLefty: 24, poise: 23, heater: 40, agile: 33,
      abilities: ["True Slider", "Winner's Luck", "Frozen"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 0, 0, 0, 0, 4, 4, 0, 1, 0]) },
    // Jake Tindall — JR RHP RP
    { firstName: "Jake", lastName: "Tindall", position: "P", eligibility: "JR", homeState: "AL", hometown: "Mobile", jerseyNumber: 43,
      hitForAvg: 10, power: 9, speed: 31, arm: 44, fielding: 26, errorResistance: 40, velocity: 42, control: 47, stamina: 41, stuff: 39,
      clutch: 50, vsLHP: 46, grit: 51, stealing: 6, running: 26, throwing: 58, recovery: 33, wRISP: 35, vsLefty: 36, poise: 38, heater: 44, agile: 32,
      abilities: ["Inside Pitch"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4, 0, 0, 0]) },
    // Andreas Alvarez — JR RHP, 2026 SEC strikeout leader, elite velocity — TEAM ELITE STUFF
    { firstName: "Andreas", lastName: "Alvarez", position: "P", eligibility: "JR", homeState: "AL", hometown: "Auburn", jerseyNumber: 46,
      hitForAvg: 13, power: 10, speed: 32, arm: 92, fielding: 60, errorResistance: 52, velocity: 97, control: 95, stamina: 5, stuff: 97,
      clutch: 84, vsLHP: 82, grit: 69, stealing: 7, running: 30, throwing: 84, recovery: 69, wRISP: 69, vsLefty: 69, poise: 69, heater: 69, agile: 42,
      abilities: ["Low Ball", "Heavy Ball", "vs. Strong Batters", "Strong Starter"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...pitchMix(1, [0, 3, 0, 1, 0, 5, 4, 0, 0, 0]) },
    // CATCHERS (2)
    // Chase Fralick — SO C, .335/.426/.472 in 2025, HR in 5 straight games (1st since 1985), .520 last 6 multi-hit
    { firstName: "Chase", lastName: "Fralick", position: "C", eligibility: "SO", homeState: "GA", hometown: "Woodstock", jerseyNumber: 12,
      hitForAvg: 64, power: 76, speed: 19, arm: 69, fielding: 67, errorResistance: 61, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 59, grit: 53, stealing: 51, running: 51, throwing: 56, recovery: 50, wRISP: 80, vsLefty: 72, poise: 78, heater: 0, agile: 38,
      abilities: ["The Almanac", "Defensive Artisan", "Power Hitter", "Consigliere"], potential: "A+", catcherAbility: 64,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Logan Gregorio — JR C transfer, can play 1B too
    { firstName: "Logan", lastName: "Gregorio", position: "C", eligibility: "JR", homeState: "FL", hometown: "Tampa", jerseyNumber: 25,
      hitForAvg: 57, power: 57, speed: 35, arm: 49, fielding: 38, errorResistance: 68, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 55, vsLHP: 51, grit: 45, stealing: 43, running: 43, throwing: 66, recovery: 42, wRISP: 50, vsLefty: 46, poise: 50, heater: 0, agile: 32,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: 56,
      throwHand: "R", batHand: "S",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // INFIELDERS (6)
    // Chris Rembert — SO 2B, ELITE: top pure hitter 2026 draft, .344/14 2B/10 HR 2025, .403 in SEC, 17-G hit streak
    { firstName: "Chris", lastName: "Rembert", position: "2B", eligibility: "SO", homeState: "GA", hometown: "Savannah", jerseyNumber: 1,
      hitForAvg: 70, power: 65, speed: 59, arm: 46, fielding: 69, errorResistance: 68, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 86, vsLHP: 80, grit: 69, stealing: 51, running: 56, throwing: 69, recovery: 56, wRISP: 86, vsLefty: 78, poise: 84, heater: 0, agile: 60,
      abilities: ["Hit Machine", "Consigliere", "Defensive Artisan"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "deep", hairColor: "black", hairStyle: "fade",
      ...noPitches },
    // Eddie Madrigal — JR 1B transfer Saint Mary's, 21 HR last yr, top portal power
    { firstName: "Eddie", lastName: "Madrigal", position: "1B", eligibility: "JR", homeState: "CA", hometown: "Moraga", jerseyNumber: 18,
      hitForAvg: 65, power: 75, speed: 64, arm: 54, fielding: 43, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 69, vsLHP: 66, grit: 68, stealing: 51, running: 51, throwing: 60, recovery: 46, wRISP: 72, vsLefty: 64, poise: 68, heater: 0, agile: 34,
      abilities: ["Unpredictable", "Power Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Eric Guevara — JR SS/3B returning starter
    { firstName: "Eric", lastName: "Guevara", position: "SS", eligibility: "JR", homeState: "FL", hometown: "Tampa", jerseyNumber: 5,
      hitForAvg: 63, power: 57, speed: 65, arm: 57, fielding: 52, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 51, running: 51, throwing: 69, recovery: 46, wRISP: 56, vsLefty: 50, poise: 56, heater: 0, agile: 54,
      abilities: ["Defensive Artisan"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Todd Clay — JR 3B/1B transfer UAB
    { firstName: "Todd", lastName: "Clay", position: "3B", eligibility: "JR", homeState: "AL", hometown: "Birmingham", jerseyNumber: 17,
      hitForAvg: 65, power: 65, speed: 61, arm: 63, fielding: 61, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 60, stealing: 51, running: 51, throwing: 69, recovery: 46, wRISP: 60, vsLefty: 54, poise: 60, heater: 0, agile: 40,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Ethin Bingaman — FR UTL, 3-HR/7-RBI game vs OK, SEC frosh RBI leader (24)
    { firstName: "Ethin", lastName: "Bingaman", position: "3B", eligibility: "FR", homeState: "CA", hometown: "Redlands", jerseyNumber: 21,
      hitForAvg: 65, power: 65, speed: 39, arm: 35, fielding: 63, errorResistance: 59, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 69, vsLHP: 68, grit: 69, stealing: 51, running: 51, throwing: 66, recovery: 46, wRISP: 78, vsLefty: 68, poise: 72, heater: 0, agile: 46,
      abilities: ["Pressure Run", "Consigliere"], potential: "A+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "tan", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Brandon McCraine — R-FR IF, 3-run HR vs A&M
    { firstName: "Brandon", lastName: "McCraine", position: "SS", eligibility: "FR", homeState: "AL", hometown: "Salem", jerseyNumber: 14,
      hitForAvg: 51, power: 51, speed: 67, arm: 61, fielding: 57, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 46, vsLHP: 49, grit: 47, stealing: 57, running: 59, throwing: 62, recovery: 36, wRISP: 44, vsLefty: 40, poise: 44, heater: 0, agile: 46,
      abilities: ["Disturbance"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Brady Cox — JR backup SS
    { firstName: "Brady", lastName: "Cox", position: "SS", eligibility: "JR", homeState: "AL", hometown: "Birmingham", jerseyNumber: 6,
      hitForAvg: 65, power: 49, speed: 66, arm: 67, fielding: 52, errorResistance: 40, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 56, grit: 56, stealing: 58, running: 55, throwing: 69, recovery: 42, wRISP: 46, vsLefty: 42, poise: 48, heater: 0, agile: 56,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // OUTFIELDERS (6)
    // Lucas Steele — JR DH/INF returning, switch hitter
    { firstName: "Lucas", lastName: "Steele", position: "OF", eligibility: "JR", homeState: "FL", hometown: "Bradenton", jerseyNumber: 20,
      hitForAvg: 65, power: 65, speed: 42, arm: 66, fielding: 68, errorResistance: 57, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 64, grit: 66, stealing: 51, running: 51, throwing: 66, recovery: 48, wRISP: 66, vsLefty: 60, poise: 64, heater: 0, agile: 44,
      abilities: ["Consigliere", "Power Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "S",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Cade Belyeu — JR OF returning starter
    { firstName: "Cade", lastName: "Belyeu", position: "OF", eligibility: "JR", homeState: "TX", hometown: "Houston", jerseyNumber: 4,
      hitForAvg: 63, power: 57, speed: 46, arm: 35, fielding: 59, errorResistance: 61, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 56, grit: 56, stealing: 59, running: 58, throwing: 68, recovery: 44, wRISP: 54, vsLefty: 48, poise: 54, heater: 0, agile: 50,
      abilities: ["Consigliere"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Bristol Carter — JR OF speed/defense
    { firstName: "Bristol", lastName: "Carter", position: "OF", eligibility: "JR", homeState: "TN", hometown: "Chattanooga", jerseyNumber: 9,
      hitForAvg: 63, power: 55, speed: 69, arm: 57, fielding: 48, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 51, grit: 58, stealing: 51, running: 69, throwing: 69, recovery: 46, wRISP: 54, vsLefty: 48, poise: 56, heater: 0, agile: 64,
      abilities: ["Storming Home"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Bub Terrell — SO OF
    { firstName: "Bub", lastName: "Terrell", position: "OF", eligibility: "SO", homeState: "AL", hometown: "Opelika", jerseyNumber: 7,
      hitForAvg: 68, power: 70, speed: 66, arm: 54, fielding: 38, errorResistance: 24, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 49, grit: 54, stealing: 57, running: 51, throwing: 62, recovery: 40, wRISP: 54, vsLefty: 46, poise: 52, heater: 0, agile: 44,
      abilities: ["Power Hitter", "Consigliere"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Dylan Roberts — JR OF speed
    { firstName: "Dylan", lastName: "Roberts", position: "OF", eligibility: "JR", homeState: "AL", hometown: "Huntsville", jerseyNumber: 11,
      hitForAvg: 65, power: 53, speed: 63, arm: 63, fielding: 59, errorResistance: 41, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 51, grit: 54, stealing: 51, running: 56, throwing: 69, recovery: 44, wRISP: 50, vsLefty: 46, poise: 52, heater: 0, agile: 60,
      abilities: ["Defensive Artisan"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Jake Mitchell — FR OF
    { firstName: "Jake", lastName: "Mitchell", position: "OF", eligibility: "FR", homeState: "AL", hometown: "Tuscaloosa", jerseyNumber: 28,
      hitForAvg: 42, power: 37, speed: 60, arm: 33, fielding: 19, errorResistance: 59, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 41, vsLHP: 36, grit: 35, stealing: 59, running: 56, throwing: 54, recovery: 28, wRISP: 30, vsLefty: 28, poise: 32, heater: 0, agile: 50,
      abilities: ["Pressure Run"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
  ],

  // Georgia — 38-11 / 18-6 SEC, D1B #5, SEC standings leader (May 3, 2026), Wes Johnson Yr 3
  // NCAA-LEADING 131 HR, .622 SLG, 9.5 R/G (#3 nationally), .325 BA (SEC-best)
  "Georgia": [
    // PITCHERS (10) — staff rebuilt after losing 8 pitchers to 2025 MLB Draft
    // Joey Volchko — Friday RHP JR, 7-2 / 3.75 ERA, team wins leader
    { firstName: "Joey", lastName: "Volchko", position: "P", eligibility: "JR", homeState: "CA", hometown: "San Jose", jerseyNumber: 34,
      hitForAvg: 14, power: 11, speed: 32, arm: 64, fielding: 40, errorResistance: 54, velocity: 65, control: 60, stamina: 95, stuff: 61,
      clutch: 76, vsLHP: 70, grit: 66, stealing: 8, running: 32, throwing: 78, recovery: 56, wRISP: 56, vsLefty: 60, poise: 63, heater: 64, agile: 42,
      abilities: ["Strong Starter", "Sharpness", "Walk"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...pitchMix(1, [0, 0, 3, 1, 4, 0, 4, 0, 0, 4]) },
    // Dylan Vigue — Saturday RHP JR, 4-1 / 2.35 ERA (BEST ON STAFF), elite Tier-1 arm
    { firstName: "Dylan", lastName: "Vigue", position: "P", eligibility: "JR", homeState: "MI", hometown: "Ann Arbor", jerseyNumber: 46,
      hitForAvg: 13, power: 10, speed: 32, arm: 70, fielding: 41, errorResistance: 56, velocity: 69, control: 68, stamina: 90, stuff: 69,
      clutch: 80, vsLHP: 76, grit: 66, stealing: 7, running: 30, throwing: 80, recovery: 52, wRISP: 63, vsLefty: 63, poise: 66, heater: 66, agile: 42,
      abilities: ["Groundball Pitcher", "Heavy Ball", "Bad Ball Hitter"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [1, 0, 0, 0, 0, 4, 4, 1, 0, 0]) },
    // Caden Aoki — Sun SP JR, transfer headliner, leadership accolades
    { firstName: "Caden", lastName: "Aoki", position: "P", eligibility: "JR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 38,
      hitForAvg: 12, power: 10, speed: 32, arm: 55, fielding: 34, errorResistance: 48, velocity: 53, control: 55, stamina: 93, stuff: 53,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 7, running: 30, throwing: 68, recovery: 45, wRISP: 47, vsLefty: 49, poise: 49, heater: 55, agile: 40,
      abilities: ["Strong Starter", "Sharpness"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...pitchMix(1, [0, 0, 0, 0, 0, 4, 4, 0, 1, 0]) },
    // Andrew Behnke — RHP transfer Tennessee, SEC familiarity, midweek/swing
    { firstName: "Andrew", lastName: "Behnke", position: "P", eligibility: "JR", homeState: "TN", hometown: "Knoxville", jerseyNumber: 42,
      hitForAvg: 12, power: 10, speed: 32, arm: 48, fielding: 32, errorResistance: 44, velocity: 45, control: 48, stamina: 81, stuff: 45,
      clutch: 56, vsLHP: 54, grit: 60, stealing: 7, running: 28, throwing: 62, recovery: 41, wRISP: 41, vsLefty: 44, poise: 44, heater: 48, agile: 36,
      abilities: ["Strong Starter", "Escape Pitch", "Strength Distribution"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4, 0, 0, 0]) },
    // Matt Scott — JR RHP RP swing
    { firstName: "Matt", lastName: "Scott", position: "P", eligibility: "JR", homeState: "CA", hometown: "Palo Alto", jerseyNumber: 29,
      hitForAvg: 12, power: 10, speed: 32, arm: 49, fielding: 32, errorResistance: 44, velocity: 46, control: 49, stamina: 78, stuff: 46,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 7, running: 28, throwing: 62, recovery: 41, wRISP: 42, vsLefty: 45, poise: 47, heater: 52, agile: 38,
      abilities: ["Guts", "Groundball Pitcher"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4, 0, 0, 0]) },
    // Chase Palmer — JR RHP RP
    { firstName: "Chase", lastName: "Palmer", position: "P", eligibility: "JR", homeState: "GA", hometown: "Augusta", jerseyNumber: 43,
      hitForAvg: 9, power: 7, speed: 25, arm: 32, fielding: 21, errorResistance: 32, velocity: 33, control: 35, stamina: 46, stuff: 32,
      clutch: 41, vsLHP: 39, grit: 42, stealing: 6, running: 21, throwing: 45, recovery: 27, wRISP: 28, vsLefty: 29, poise: 30, heater: 35, agile: 28,
      abilities: ["Fireman"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4, 0, 0, 0]) },
    // Sam Whitfield — FR RHP RP
    { firstName: "Sam", lastName: "Whitfield", position: "P", eligibility: "FR", homeState: "GA", hometown: "Savannah", jerseyNumber: 36,
      hitForAvg: 8, power: 6, speed: 25, arm: 32, fielding: 20, errorResistance: 30, velocity: 32, control: 32, stamina: 37, stuff: 32,
      clutch: 37, vsLHP: 34, grit: 39, stealing: 6, running: 22, throwing: 43, recovery: 24, wRISP: 25, vsLefty: 26, poise: 26, heater: 34, agile: 27,
      abilities: ["Winner's Luck"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 0, 0, 0, 0, 4, 4, 1, 0, 0]) },
    // Ethan Crawley — FR RHP
    { firstName: "Ethan", lastName: "Crawley", position: "P", eligibility: "FR", homeState: "GA", hometown: "Duluth", jerseyNumber: 49,
      hitForAvg: 7, power: 7, speed: 26, arm: 30, fielding: 18, errorResistance: 28, velocity: 30, control: 28, stamina: 49, stuff: 30,
      clutch: 30, vsLHP: 28, grit: 31, stealing: 5, running: 21, throwing: 43, recovery: 21, wRISP: 21, vsLefty: 21, poise: 21, heater: 33, agile: 26,
      abilities: ["Kageura", "Straddle", "Crossfire"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 0, 0, 0, 0, 0, 4, 0, 1, 4]) },
    // Brandon Wells — FR RHP
    { firstName: "Brandon", lastName: "Wells", position: "P", eligibility: "FR", homeState: "FL", hometown: "Tampa", jerseyNumber: 51,
      hitForAvg: 9, power: 8, speed: 31, arm: 35, fielding: 20, errorResistance: 32, velocity: 35, control: 32, stamina: 34, stuff: 33,
      clutch: 34, vsLHP: 32, grit: 36, stealing: 6, running: 26, throwing: 50, recovery: 24, wRISP: 23, vsLefty: 24, poise: 24, heater: 38, agile: 32,
      abilities: ["True Slider", "Sharpness", "Low Ball"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 3, 0, 1, 0, 4, 3, 0, 0, 0]) },
    // Bryce Calloway — JR 1B/RHP closer transfer New Orleans, .390/18HR/1.206 OPS, light-tower power, primarily 1B but two-way (filed as P)
    { firstName: "Bryce", lastName: "Calloway", position: "P", eligibility: "JR", homeState: "LA", hometown: "New Orleans", jerseyNumber: 18,
      hitForAvg: 22, power: 24, speed: 32, arm: 54, fielding: 44, errorResistance: 54, velocity: 57, control: 54, stamina: 27, stuff: 56,
      clutch: 80, vsLHP: 76, grit: 66, stealing: 8, running: 30, throwing: 70, recovery: 44, wRISP: 62, vsLefty: 59, poise: 59, heater: 61, agile: 36,
      abilities: ["Fireman", "Staredown", "Gyroball", "Intimidator", "Decisive", "Heavy Ball"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4, 0, 0, 0]) },
    // CATCHERS (2)
    // Daniel Jackson — JR C, ELITE: .389/23 HR/21 SB, 1st player in SEC HISTORY with 20HR/20SB season, returning starter
    { firstName: "Daniel", lastName: "Jackson", position: "C", eligibility: "JR", homeState: "GA", hometown: "Lawrenceville", jerseyNumber: 3,
      generational: true,
      hitForAvg: 70, power: 67, speed: 64, arm: 56, fielding: 51, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 90, vsLHP: 82, grit: 48, stealing: 52, running: 55, throwing: 53, recovery: 60, wRISP: 86, vsLefty: 80, poise: 84, heater: 0, agile: 60,
      abilities: ["Spray Hitter", "Consigliere", "Storming Home", "Power Hitter", "The Almanac"], potential: "A+", catcherAbility: 70,
      throwHand: "R", batHand: "R",
      skinTone: "deep", hairColor: "black", hairStyle: "fade",
      ...noPitches },
    // Jack Arcamone — JR transfer Richmond, backup C
    { firstName: "Jack", lastName: "Arcamone", position: "C", eligibility: "JR", homeState: "NJ", hometown: "Toms River", jerseyNumber: 24,
      hitForAvg: 46, power: 43, speed: 42, arm: 53, fielding: 40, errorResistance: 25, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 41, grit: 46, stealing: 36, running: 36, throwing: 59, recovery: 33, wRISP: 37, vsLefty: 35, poise: 39, heater: 0, agile: 30,
      abilities: ["Predicament", "Spray Hitter"], potential: "B+", catcherAbility: 47,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // INFIELDERS (7)
    // Ryland Zaborowski — JR 1B/DH, tied #2 nationally 16 HR last yr, premier power
    { firstName: "Ryland", lastName: "Zaborowski", position: "1B", eligibility: "JR", homeState: "GA", hometown: "Buford", jerseyNumber: 23,
      hitForAvg: 66, power: 71, speed: 56, arm: 59, fielding: 55, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 60, grit: 58, stealing: 49, running: 49, throwing: 60, recovery: 50, wRISP: 78, vsLefty: 70, poise: 74, heater: 0, agile: 34,
      abilities: ["Consigliere", "Power Hitter"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Robbie Burnett — JR 2B, tied #2 nationally 16 HR last yr, star 2B
    { firstName: "Robbie", lastName: "Burnett", position: "2B", eligibility: "JR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 8,
      hitForAvg: 63, power: 63, speed: 59, arm: 56, fielding: 63, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 78, vsLHP: 66, grit: 76, stealing: 49, running: 49, throwing: 66, recovery: 56, wRISP: 76, vsLefty: 70, poise: 76, heater: 0, agile: 56,
      abilities: ["Predicament", "Power Hitter", "Consigliere", "Defensive Artisan"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Slate Alford — JR 3B leadoff, multi-HR vs Kentucky
    { firstName: "Slate", lastName: "Alford", position: "3B", eligibility: "JR", homeState: "MS", hometown: "Hattiesburg", jerseyNumber: 4,
      hitForAvg: 69, power: 62, speed: 44, arm: 45, fielding: 37, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 74, vsLHP: 66, grit: 66, stealing: 49, running: 49, throwing: 74, recovery: 50, wRISP: 70, vsLefty: 66, poise: 72, heater: 0, agile: 50,
      abilities: ["Insurer", "Chance Maker", "Power Hitter", "Consigliere"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Kolby Branch — SR SS returning, .303/13HR/41RBI 2025
    { firstName: "Kolby", lastName: "Branch", position: "SS", eligibility: "SR", homeState: "GA", hometown: "Valdosta", jerseyNumber: 2,
      hitForAvg: 62, power: 62, speed: 46, arm: 39, fielding: 62, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 68, stealing: 49, running: 49, throwing: 74, recovery: 50, wRISP: 64, vsLefty: 56, poise: 64, heater: 0, agile: 50,
      abilities: ["Defensive Artisan", "Power Hitter", "Walkoff Hitter"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Ryan Black — SR INF returning starter
    { firstName: "Ryan", lastName: "Black", position: "2B", eligibility: "SR", homeState: "GA", hometown: "Roswell", jerseyNumber: 6,
      hitForAvg: 67, power: 47, speed: 46, arm: 59, fielding: 59, errorResistance: 61, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 55, grit: 50, stealing: 57, running: 52, throwing: 60, recovery: 40, wRISP: 46, vsLefty: 42, poise: 48, heater: 0, agile: 46,
      abilities: ["Chance Maker"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Rylan Lujo — SO INF/OF, thrives vs SEC
    { firstName: "Rylan", lastName: "Lujo", position: "OF", eligibility: "SO", homeState: "OH", hometown: "Dayton", jerseyNumber: 10,
      hitForAvg: 62, power: 57, speed: 56, arm: 58, fielding: 52, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 58, stealing: 49, running: 49, throwing: 62, recovery: 44, wRISP: 60, vsLefty: 54, poise: 58, heater: 0, agile: 46,
      abilities: ["Spray Hitter", "Consigliere"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Luke Harmon — JR backup SS
    { firstName: "Luke", lastName: "Harmon", position: "SS", eligibility: "JR", homeState: "GA", hometown: "Alpharetta", jerseyNumber: 7,
      hitForAvg: 57, power: 47, speed: 56, arm: 52, fielding: 46, errorResistance: 61, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 49, grit: 52, stealing: 49, running: 50, throwing: 66, recovery: 44, wRISP: 48, vsLefty: 44, poise: 50, heater: 0, agile: 56,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // OUTFIELDERS (6)
    // Tre Phelps — JR OF preseason All-American (returns from injury), .318/10HR/44RBI prior
    { firstName: "Tre", lastName: "Phelps", position: "OF", eligibility: "JR", homeState: "GA", hometown: "Cumming", jerseyNumber: 5,
      hitForAvg: 63, power: 63, speed: 64, arm: 61, fielding: 53, errorResistance: 41, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 78, vsLHP: 66, grit: 76, stealing: 49, running: 50, throwing: 66, recovery: 54, wRISP: 78, vsLefty: 72, poise: 78, heater: 0, agile: 54,
      abilities: ["Power Hitter", "Consigliere", "Spray Hitter"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Kenny Ishikawa — SO OF/LHP transfer Seattle U, .318/8HR, two-way
    { firstName: "Kenny", lastName: "Ishikawa", position: "OF", eligibility: "SO", homeState: "WA", hometown: "Seattle", jerseyNumber: 1,
      hitForAvg: 62, power: 62, speed: 53, arm: 50, fielding: 42, errorResistance: 61, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 64, stealing: 49, running: 56, throwing: 74, recovery: 50, wRISP: 64, vsLefty: 56, poise: 64, heater: 0, agile: 60,
      abilities: ["Unpredictable", "Spray Hitter"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Carter Brown — JR OF
    { firstName: "Carter", lastName: "Brown", position: "OF", eligibility: "JR", homeState: "GA", hometown: "Marietta", jerseyNumber: 9,
      hitForAvg: 57, power: 51, speed: 58, arm: 57, fielding: 63, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 53, grit: 52, stealing: 52, running: 56, throwing: 66, recovery: 42, wRISP: 48, vsLefty: 44, poise: 50, heater: 0, agile: 50,
      abilities: ["Consigliere", "vs. Ace"], potential: "B", catcherAbility: null,
      throwHand: "R", batHand: "S",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Scott Newman — JR OF power
    { firstName: "Scott", lastName: "Newman", position: "OF", eligibility: "JR", homeState: "SC", hometown: "Spartanburg", jerseyNumber: 11,
      hitForAvg: 57, power: 62, speed: 39, arm: 23, fielding: 64, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 49, running: 49, throwing: 60, recovery: 42, wRISP: 56, vsLefty: 50, poise: 54, heater: 0, agile: 38,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Cole Johnson — FR OF — PG 1st Team / Top-100 national
    { firstName: "Cole", lastName: "Johnson", position: "OF", eligibility: "FR", homeState: "GA", hometown: "Suwanee", jerseyNumber: 28,
      hitForAvg: 62, power: 42, speed: 58, arm: 53, fielding: 41, errorResistance: 26, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 51, grit: 41, stealing: 54, running: 47, throwing: 48, recovery: 26, wRISP: 30, vsLefty: 28, poise: 30, heater: 0, agile: 38,
      abilities: ["Error Prone"], potential: "A", catcherAbility: null,
      throwHand: "R", batHand: "L",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Michael O'Shaughnessy — FR 3B depth
    { firstName: "Michael", lastName: "O'Shaughnessy", position: "3B", eligibility: "FR", homeState: "GA", hometown: "Athens", jerseyNumber: 22,
      hitForAvg: 33, power: 62, speed: 29, arm: 19, fielding: 53, errorResistance: 45, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 36, grit: 34, stealing: 37, running: 41, throwing: 33, recovery: 24, wRISP: 25, vsLefty: 24, poise: 27, heater: 0, agile: 31,
      abilities: ["Spray Hitter", "Push"], potential: "B+", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
  ],

  "Mississippi State": [
      // 38-12/15-10 SEC, D1B #11, Brian O'Connor Yr 1 (from Virginia). Heavy transfer class. .310/.538 SLG, 86 HR.
      // PITCHERS (10)
      // Tomas Valincius — LHP JR Friday ace (Virginia transfer), 8-2, 13K vs Auburn, 14K vs Vandy, 7 shutout IP @ Ark — TEAM ELITE STUFF
      { firstName: "Tomas", lastName: "Valincius", position: "P", eligibility: "JR", homeState: "VA", hometown: "Richmond", jerseyNumber: 37,
        hitForAvg: 16, power: 12, speed: 32, arm: 92, fielding: 60, errorResistance: 50, velocity: 97, control: 95, stamina: 81, stuff: 97,
        clutch: 88, vsLHP: 89, grit: 71, stealing: 9, running: 32, throwing: 84, recovery: 71, wRISP: 71, vsLefty: 71, poise: 71, heater: 71, agile: 42,
        abilities: ["Wild Fastball", "vs. Strong Batters", "Heavy Ball", "Natural Shuuto"], potential: "A+", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 5, 4, 0, 0, 0]) },
      // Duke Stone — Saturday RHP FR, 6-1/4.40/78K in 57.1 IP
      { firstName: "Duke", lastName: "Stone", position: "P", eligibility: "FR", homeState: "MS", hometown: "Jackson", jerseyNumber: 45,
        hitForAvg: 14, power: 10, speed: 32, arm: 60, fielding: 33, errorResistance: 46, velocity: 60, control: 56, stamina: 80, stuff: 57,
        clutch: 70, vsLHP: 64, grit: 70, stealing: 8, running: 30, throwing: 72, recovery: 51, wRISP: 51, vsLefty: 52, poise: 56, heater: 62, agile: 38,
        abilities: ["Strong Starter", "Flyball Pitcher", "Staredown"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 0, 0, 4, 4, 1, 0, 0]) },
      // Maddox Webb — Sunday RHP transfer
      { firstName: "Maddox", lastName: "Webb", position: "P", eligibility: "JR", homeState: "VA", hometown: "Charlottesville", jerseyNumber: 33,
        hitForAvg: 13, power: 10, speed: 32, arm: 56, fielding: 33, errorResistance: 44, velocity: 54, control: 55, stamina: 82, stuff: 53,
        clutch: 66, vsLHP: 60, grit: 66, stealing: 8, running: 30, throwing: 70, recovery: 47, wRISP: 47, vsLefty: 49, poise: 52, heater: 58, agile: 40,
        abilities: ["Strong Starter", "Inside Pitch"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 0, 0, 4, 4, 0, 1, 0]) },
      // Tyler Pitzer — RHP transfer rotation/bulk
      { firstName: "Tyler", lastName: "Pitzer", position: "P", eligibility: "SR", homeState: "OH", hometown: "Columbus", jerseyNumber: 35,
        hitForAvg: 13, power: 10, speed: 31, arm: 56, fielding: 33, errorResistance: 44, velocity: 53, control: 56, stamina: 94, stuff: 52,
        clutch: 66, vsLHP: 62, grit: 68, stealing: 8, running: 30, throwing: 70, recovery: 47, wRISP: 47, vsLefty: 49, poise: 52, heater: 56, agile: 38,
        abilities: ["Inside Pitch", "Gyroball"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 3, 1, 0, 4, 4, 0, 0, 0]) },
      // Jackson Logar — LHP transfer rotation
      { firstName: "Jackson", lastName: "Logar", position: "P", eligibility: "JR", homeState: "AL", hometown: "Birmingham", jerseyNumber: 41,
        hitForAvg: 13, power: 10, speed: 31, arm: 55, fielding: 31, errorResistance: 42, velocity: 50, control: 56, stamina: 51, stuff: 52,
        clutch: 64, vsLHP: 70, grit: 66, stealing: 8, running: 30, throwing: 68, recovery: 45, wRISP: 47, vsLefty: 52, poise: 52, heater: 52, agile: 38,
        abilities: ["Fireman", "Strong Starter", "Winner's Luck", "Groundball Pitcher"], potential: "B+", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 0, 4, 0, 0, 4]) },
      // Jack Bauer — LHP FR closer, top-300 HS recruit, retired all 7 vs Auburn
      { firstName: "Jack", lastName: "Bauer", position: "P", eligibility: "FR", homeState: "TX", hometown: "Dallas", jerseyNumber: 47,
        hitForAvg: 13, power: 10, speed: 32, arm: 61, fielding: 33, errorResistance: 44, velocity: 60, control: 57, stamina: 32, stuff: 58,
        clutch: 76, vsLHP: 70, grit: 70, stealing: 8, running: 30, throwing: 74, recovery: 44, wRISP: 52, vsLefty: 57, poise: 60, heater: 63, agile: 40,
        abilities: ["Fireman", "Sharpness"], potential: "A+", catcherAbility: null,
        throwHand: "L", batHand: "L",
        skinTone: "light", hairColor: "blonde", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4, 0, 0, 0]) },
      // Ryan McPherson — RHP SO, retained
      { firstName: "Ryan", lastName: "McPherson", position: "P", eligibility: "SO", homeState: "FL", hometown: "Fort Lauderdale", jerseyNumber: 39,
        hitForAvg: 13, power: 10, speed: 32, arm: 54, fielding: 33, errorResistance: 44, velocity: 51, control: 53, stamina: 35, stuff: 51,
        clutch: 64, vsLHP: 60, grit: 66, stealing: 8, running: 30, throwing: 68, recovery: 45, wRISP: 47, vsLefty: 48, poise: 51, heater: 56, agile: 38,
        abilities: ["Strong Starter", "Good Pickoff", "Gyroball", "Full Throttle"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 0, 0, 4, 4, 1, 0, 0]) },
      // Charlie Foster — RHP JR (Virginia transfer)
      // Brendan Sweeney — JR RHP RP
      { firstName: "Brendan", lastName: "Sweeney", position: "P", eligibility: "JR", homeState: "SC", hometown: "Columbia", jerseyNumber: 49,
        hitForAvg: 12, power: 10, speed: 32, arm: 52, fielding: 32, errorResistance: 44, velocity: 48, control: 50, stamina: 41, stuff: 49,
        clutch: 60, vsLHP: 58, grit: 62, stealing: 8, running: 30, throwing: 66, recovery: 41, wRISP: 44, vsLefty: 44, poise: 47, heater: 52, agile: 38,
        abilities: ["Fireman", "Winner's Luck", "vs. Strong Batters"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4, 0, 0, 0]) },
      // Maddox Miller — FR RHP depth
      { firstName: "Maddox", lastName: "Miller", position: "P", eligibility: "FR", homeState: "MS", hometown: "Starkville", jerseyNumber: 51,
        hitForAvg: 11, power: 8, speed: 32, arm: 54, fielding: 30, errorResistance: 42, velocity: 55, control: 47, stamina: 3, stuff: 52,
        clutch: 54, vsLHP: 50, grit: 56, stealing: 10, running: 30, throwing: 66, recovery: 36, wRISP: 40, vsLefty: 42, poise: 42, heater: 56, agile: 38,
        abilities: ["Strong Starter", "Sharpness"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 0, 0, 1, 0, 4, 4, 0, 0, 0]) },
      // CATCHERS (2)
      { firstName: "Kevin", lastName: "Milewski", position: "C", eligibility: "JR", homeState: "WI", hometown: "Milwaukee", jerseyNumber: 19,
        hitForAvg: 63, power: 57, speed: 53, arm: 65, fielding: 56, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 56, vsLHP: 57, grit: 58, stealing: 44, running: 44, throwing: 71, recovery: 46, wRISP: 54, vsLefty: 50, poise: 56, heater: 0, agile: 38,
        abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: 60,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      { firstName: "Andrew", lastName: "Raymond", position: "C", eligibility: "SO", homeState: "MS", hometown: "Brandon", jerseyNumber: 14,
        hitForAvg: 45, power: 39, speed: 33, arm: 67, fielding: 64, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 41, vsLHP: 44, grit: 43, stealing: 34, running: 31, throwing: 40, recovery: 32, wRISP: 34, vsLefty: 32, poise: 36, heater: 0, agile: 28,
        abilities: ["Consigliere", "Two-Strike Hitter"], potential: "B+", catcherAbility: 40,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // INFIELDERS (7)
      // Ace Reese — 3B JR, .352/.422/.718, 21 HR/66 RBI, SEC Newcomer of Year, 105.4 mph 90th-pct EV — TEAM ELITE
      { firstName: "Ace", lastName: "Reese", position: "3B", eligibility: "JR", homeState: "MS", hometown: "Meridian", jerseyNumber: 2,
        hitForAvg: 67, power: 75, speed: 44, arm: 64, fielding: 66, errorResistance: 57, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 65, vsLHP: 68, grit: 63, stealing: 52, running: 52, throwing: 63, recovery: 48, wRISP: 84, vsLefty: 78, poise: 80, heater: 0, agile: 50,
        abilities: ["Defensive Artisan", "Consigliere", "Power Hitter"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Blake Bevis — 1B SR transfer
      { firstName: "Blake", lastName: "Bevis", position: "1B", eligibility: "SR", homeState: "MS", hometown: "Starkville", jerseyNumber: 18,
        hitForAvg: 61, power: 71, speed: 48, arm: 32, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 60, vsLHP: 54, grit: 52, stealing: 50, running: 47, throwing: 45, recovery: 44, wRISP: 60, vsLefty: 54, poise: 60, heater: 0, agile: 36,
        abilities: ["Power Hitter", "Defensive Artisan"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Gehrig Frei — INF, .316/8 HR/35 RBI
      { firstName: "Gehrig", lastName: "Frei", position: "2B", eligibility: "JR", homeState: "CA", hometown: "San Diego", jerseyNumber: 3,
        hitForAvg: 66, power: 63, speed: 66, arm: 52, fielding: 49, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 60, vsLHP: 56, grit: 62, stealing: 52, running: 52, throwing: 60, recovery: 44, wRISP: 60, vsLefty: 56, poise: 60, heater: 0, agile: 52,
        abilities: ["Power Hitter"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Noah Sullivan — two-way INF, 3rd-team All-American, .323/8 HR/37 RBI
      { firstName: "Noah", lastName: "Sullivan", position: "SS", eligibility: "JR", homeState: "MS", hometown: "Madison", jerseyNumber: 12,
        hitForAvg: 72, power: 60, speed: 52, arm: 66, fielding: 68, errorResistance: 59, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 68, vsLHP: 62, grit: 70, stealing: 52, running: 52, throwing: 71, recovery: 48, wRISP: 68, vsLefty: 60, poise: 70, heater: 0, agile: 56,
        abilities: ["Chance Maker", "Spray Hitter", "Power Hitter"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Ryder Woodson — SS SO depth
      { firstName: "Ryder", lastName: "Woodson", position: "SS", eligibility: "SO", homeState: "MS", hometown: "Oxford", jerseyNumber: 6,
        hitForAvg: 57, power: 49, speed: 64, arm: 61, fielding: 45, errorResistance: 28, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 56, vsLHP: 51, grit: 52, stealing: 60, running: 58, throwing: 70, recovery: 40, wRISP: 46, vsLefty: 44, poise: 48, heater: 0, agile: 56,
        abilities: ["Disturbance"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Chone James — 2B SO depth
      { firstName: "Chone", lastName: "James", position: "2B", eligibility: "SO", homeState: "MS", hometown: "Tupelo", jerseyNumber: 10,
        hitForAvg: 55, power: 47, speed: 60, arm: 39, fielding: 62, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 50, vsLHP: 46, grit: 44, stealing: 60, running: 55, throwing: 64, recovery: 38, wRISP: 44, vsLefty: 42, poise: 46, heater: 0, agile: 50,
        abilities: ["Walkoff Hitter", "Defensive Artisan", "Push"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "deep", hairColor: "black", hairStyle: "fade",
        ...noPitches },
      // Nick Frontino — SS FR depth
      { firstName: "Nick", lastName: "Frontino", position: "SS", eligibility: "FR", homeState: "FL", hometown: "Sarasota", jerseyNumber: 15,
        hitForAvg: 43, power: 37, speed: 69, arm: 43, fielding: 26, errorResistance: 21, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 37, vsLHP: 42, grit: 40, stealing: 60, running: 53, throwing: 38, recovery: 26, wRISP: 26, vsLefty: 25, poise: 28, heater: 0, agile: 40,
        abilities: ["Good Mood", "Timely Whiff"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // OUTFIELDERS (6)
      // Bryce Chance — OF GR, .365/.359 SEC, 17 2B, only 12 K all season — elite contact
      { firstName: "Bryce", lastName: "Chance", position: "OF", eligibility: "SR", homeState: "MS", hometown: "Brandon", jerseyNumber: 8,
        hitForAvg: 71, power: 63, speed: 68, arm: 57, fielding: 40, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 71, vsLHP: 70, grit: 71, stealing: 52, running: 52, throwing: 64, recovery: 50, wRISP: 76, vsLefty: 70, poise: 78, heater: 0, agile: 56,
        abilities: ["Two-Strike Hitter", "Chance Maker", "Consigliere"], potential: "A", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Jacob Parker — OF FR, .342/10 HR/42 RBI, 2 grand slams in last 7 games
      { firstName: "Jacob", lastName: "Parker", position: "OF", eligibility: "FR", homeState: "MS", hometown: "Olive Branch", jerseyNumber: 28,
        hitForAvg: 61, power: 71, speed: 58, arm: 35, fielding: 69, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 71, vsLHP: 60, grit: 64, stealing: 52, running: 52, throwing: 60, recovery: 42, wRISP: 68, vsLefty: 60, poise: 66, heater: 0, agile: 52,
        abilities: ["Power Hitter", "Consigliere"], potential: "A+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Reed Stallman — OF, 10 HR/43 RBI, 2-HR game vs Nicholls
      { firstName: "Reed", lastName: "Stallman", position: "OF", eligibility: "SR", homeState: "VA", hometown: "Richmond", jerseyNumber: 4,
        hitForAvg: 61, power: 71, speed: 60, arm: 56, fielding: 34, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 71, vsLHP: 54, grit: 62, stealing: 52, running: 52, throwing: 66, recovery: 44, wRISP: 60, vsLefty: 54, poise: 60, heater: 0, agile: 46,
        abilities: ["Power Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // James Nunnallee — OF SO, Virginia transfer
      { firstName: "James", lastName: "Nunnallee", position: "OF", eligibility: "SO", homeState: "VA", hometown: "Charlottesville", jerseyNumber: 7,
        hitForAvg: 63, power: 55, speed: 60, arm: 43, fielding: 30, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 54, vsLHP: 57, grit: 56, stealing: 53, running: 56, throwing: 66, recovery: 42, wRISP: 52, vsLefty: 48, poise: 54, heater: 0, agile: 56,
        abilities: ["Resilient"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Aidan Teel — OF JR, Virginia transfer
      { firstName: "Aidan", lastName: "Teel", position: "OF", eligibility: "JR", homeState: "NJ", hometown: "Mahwah", jerseyNumber: 11,
        hitForAvg: 66, power: 61, speed: 50, arm: 64, fielding: 65, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 58, vsLHP: 54, grit: 58, stealing: 52, running: 52, throwing: 70, recovery: 44, wRISP: 56, vsLefty: 52, poise: 58, heater: 0, agile: 54,
        abilities: ["Home Defense", "Contact Hitter"], potential: "A-", catcherAbility: null,
        throwHand: "R", batHand: "L",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Vytas Valincius — OF transfer (non-Virginia)
      { firstName: "Vytas", lastName: "Valincius", position: "OF", eligibility: "JR", homeState: "IL", hometown: "Chicago", jerseyNumber: 5,
        hitForAvg: 63, power: 63, speed: 52, arm: 36, fielding: 68, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 56, vsLHP: 60, grit: 56, stealing: 58, running: 52, throwing: 64, recovery: 42, wRISP: 56, vsLefty: 52, poise: 56, heater: 0, agile: 46,
        abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
        throwHand: "R", batHand: "R",
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
    { firstName: "Kellum", lastName: "Clark", position: "OF", eligibility: "SR", homeState: "MS", hometown: "Starkville", jerseyNumber: 22,
      hitForAvg: 62, power: 57, speed: 60, arm: 50, fielding: 41, errorResistance: 63, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 55, grit: 64, stealing: 52, running: 54, throwing: 66, recovery: 54, wRISP: 60, vsLefty: 55, poise: 60, heater: 0, agile: 56,
      abilities: ["Spray Hitter", "Chance Maker"], potential: "A-", catcherAbility: null,
      throwHand: "R", batHand: "R",
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
],
};
