import type { RealPlayer } from "./realRosters";

function pitchMix(primary: number, secondary: number[]): { pitchFB: number; pitch2S: number; pitchSL: number; pitchCB: number; pitchCH: number; pitchCT: number; pitchSNK: number; pitchSPL: number } {
  return { pitchFB: primary, pitch2S: secondary[0] || 0, pitchSL: secondary[1] || 0, pitchCB: secondary[2] || 0, pitchCH: secondary[3] || 0, pitchCT: secondary[4] || 0, pitchSNK: secondary[5] || 0, pitchSPL: secondary[6] || 0 };
}

const noPitches = { pitchFB: 0, pitch2S: 0, pitchSL: 0, pitchCB: 0, pitchCH: 0, pitchCT: 0, pitchSNK: 0, pitchSPL: 0 };

export const SEC_BATCH3_ROSTERS: Record<string, RealPlayer[]> = {
  "South Carolina": [
    // PITCHERS (10)
    { firstName: "Brandon", lastName: "Stone", position: "P", eligibility: "JR", homeState: "SC", hometown: "Columbia", jerseyNumber: 33,
      hitForAvg: 16, power: 12, speed: 40, arm: 74, fielding: 48, errorResistance: 50, velocity: 76, control: 72, stamina: 76, stuff: 74,
      clutch: 68, vsLHP: 64, grit: 72, stealing: 10, running: 36, throwing: 72, recovery: 66, wRISP: 66, vsLefty: 68, poise: 70, heater: 74, agile: 44,
      abilities: ["Strong Starter", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 4, 0, 0, 0]) },
    { firstName: "Amp", lastName: "Phillips", position: "P", eligibility: "JR", homeState: "SC", hometown: "Spartanburg", jerseyNumber: 21,
      hitForAvg: 16, power: 12, speed: 38, arm: 72, fielding: 46, errorResistance: 48, velocity: 74, control: 70, stamina: 72, stuff: 72,
      clutch: 66, vsLHP: 62, grit: 70, stealing: 10, running: 34, throwing: 70, recovery: 64, wRISP: 64, vsLefty: 66, poise: 68, heater: 72, agile: 42,
      abilities: ["Workhorse"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Jake", lastName: "McCoy", position: "P", eligibility: "JR", homeState: "SC", hometown: "Greenville", jerseyNumber: 37,
      hitForAvg: 16, power: 12, speed: 40, arm: 74, fielding: 48, errorResistance: 50, velocity: 76, control: 74, stamina: 74, stuff: 74,
      clutch: 68, vsLHP: 66, grit: 70, stealing: 10, running: 36, throwing: 72, recovery: 66, wRISP: 66, vsLefty: 70, poise: 70, heater: 74, agile: 44,
      abilities: ["Strong Starter", "Filthy Breaking Ball"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 5, 0, 0, 0]) },
    { firstName: "Josh", lastName: "Gunther", position: "P", eligibility: "JR", homeState: "GA", hometown: "Marietta", jerseyNumber: 45,
      hitForAvg: 14, power: 10, speed: 38, arm: 68, fielding: 44, errorResistance: 46, velocity: 70, control: 64, stamina: 60, stuff: 68,
      clutch: 58, vsLHP: 56, grit: 62, stealing: 10, running: 34, throwing: 66, recovery: 58, wRISP: 56, vsLefty: 60, poise: 60, heater: 68, agile: 42,
      abilities: ["Explosive Fastball"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 3, 0, 0, 0]) },
    { firstName: "Riley", lastName: "Goodman", position: "P", eligibility: "SO", homeState: "SC", hometown: "Charleston", jerseyNumber: 28,
      hitForAvg: 14, power: 10, speed: 38, arm: 66, fielding: 42, errorResistance: 44, velocity: 68, control: 62, stamina: 56, stuff: 66,
      clutch: 54, vsLHP: 52, grit: 60, stealing: 10, running: 34, throwing: 64, recovery: 50, wRISP: 52, vsLefty: 56, poise: 56, heater: 66, agile: 42,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 3, 0, 0, 0]) },
    { firstName: "Marcus", lastName: "Hall", position: "P", eligibility: "JR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 41,
      hitForAvg: 14, power: 10, speed: 40, arm: 68, fielding: 44, errorResistance: 46, velocity: 70, control: 66, stamina: 64, stuff: 68,
      clutch: 60, vsLHP: 58, grit: 64, stealing: 10, running: 36, throwing: 66, recovery: 60, wRISP: 58, vsLefty: 62, poise: 62, heater: 68, agile: 44,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 4, 0, 0, 0]) },
    { firstName: "Zach", lastName: "Swanson", position: "P", eligibility: "SO", homeState: "SC", hometown: "Rock Hill", jerseyNumber: 39,
      hitForAvg: 14, power: 10, speed: 38, arm: 66, fielding: 42, errorResistance: 44, velocity: 68, control: 64, stamina: 62, stuff: 66,
      clutch: 56, vsLHP: 54, grit: 60, stealing: 10, running: 34, throwing: 64, recovery: 56, wRISP: 54, vsLefty: 58, poise: 58, heater: 66, agile: 42,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 5, 0, 0, 0]) },
    { firstName: "Dylan", lastName: "Reeves", position: "P", eligibility: "JR", homeState: "GA", hometown: "Savannah", jerseyNumber: 47,
      hitForAvg: 14, power: 10, speed: 38, arm: 68, fielding: 44, errorResistance: 46, velocity: 70, control: 66, stamina: 64, stuff: 68,
      clutch: 60, vsLHP: 58, grit: 62, stealing: 10, running: 34, throwing: 66, recovery: 58, wRISP: 58, vsLefty: 62, poise: 62, heater: 68, agile: 42,
      abilities: ["Fireman"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 3, 4, 0, 0, 0]) },
    { firstName: "Trevor", lastName: "Mack", position: "P", eligibility: "JR", homeState: "FL", hometown: "Jacksonville", jerseyNumber: 43,
      hitForAvg: 14, power: 10, speed: 40, arm: 66, fielding: 44, errorResistance: 46, velocity: 68, control: 64, stamina: 62, stuff: 66,
      clutch: 58, vsLHP: 56, grit: 60, stealing: 10, running: 36, throwing: 64, recovery: 56, wRISP: 56, vsLefty: 60, poise: 60, heater: 66, agile: 44,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Cole", lastName: "Jenkins", position: "P", eligibility: "JR", homeState: "SC", hometown: "Lexington", jerseyNumber: 49,
      hitForAvg: 14, power: 10, speed: 38, arm: 66, fielding: 42, errorResistance: 44, velocity: 68, control: 64, stamina: 60, stuff: 66,
      clutch: 56, vsLHP: 54, grit: 58, stealing: 10, running: 34, throwing: 64, recovery: 54, wRISP: 54, vsLefty: 58, poise: 58, heater: 66, agile: 42,
      abilities: [], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 3, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Talmadge", lastName: "LeCroy", position: "C", eligibility: "SR", homeState: "SC", hometown: "Easley", jerseyNumber: 18,
      hitForAvg: 58, power: 52, speed: 36, arm: 68, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 68, stealing: 14, running: 34, throwing: 70, recovery: 54, wRISP: 60, vsLefty: 56, poise: 66, heater: 0, agile: 40,
      abilities: ["Guts"], potential: "B", catcherAbility: 65,
      ...noPitches },
    { firstName: "Jake", lastName: "Randolph", position: "C", eligibility: "FR", homeState: "SC", hometown: "Irmo", jerseyNumber: 24,
      hitForAvg: 38, power: 32, speed: 34, arm: 56, fielding: 48, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 36, vsLHP: 34, grit: 38, stealing: 12, running: 32, throwing: 58, recovery: 34, wRISP: 34, vsLefty: 32, poise: 36, heater: 0, agile: 36,
      abilities: [], potential: "B+", catcherAbility: 55,
      ...noPitches },
    // INFIELDERS (5)
    { firstName: "KJ", lastName: "Scobey", position: "SS", eligibility: "SO", homeState: "GA", hometown: "Woodstock", jerseyNumber: 2,
      hitForAvg: 60, power: 58, speed: 62, arm: 70, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 68, vsLHP: 58, grit: 66, stealing: 40, running: 60, throwing: 72, recovery: 52, wRISP: 66, vsLefty: 56, poise: 64, heater: 0, agile: 64,
      abilities: ["Clutch Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Beau", lastName: "Hollins", position: "1B", eligibility: "SO", homeState: "SC", hometown: "Bluffton", jerseyNumber: 14,
      hitForAvg: 66, power: 56, speed: 42, arm: 60, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 16, running: 40, throwing: 62, recovery: 50, wRISP: 62, vsLefty: 56, poise: 60, heater: 0, agile: 44,
      abilities: ["Contact Machine"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Logan", lastName: "Sutter", position: "2B", eligibility: "SR", homeState: "IN", hometown: "Fishers", jerseyNumber: 6,
      hitForAvg: 72, power: 54, speed: 54, arm: 64, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 64, grit: 68, stealing: 34, running: 52, throwing: 66, recovery: 56, wRISP: 66, vsLefty: 62, poise: 66, heater: 0, agile: 56,
      abilities: ["Contact Machine", "Table Setter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Dawson", lastName: "Harman", position: "3B", eligibility: "JR", homeState: "FL", hometown: "Ocala", jerseyNumber: 10,
      hitForAvg: 68, power: 62, speed: 52, arm: 70, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 70, stealing: 28, running: 50, throwing: 72, recovery: 54, wRISP: 66, vsLefty: 60, poise: 66, heater: 0, agile: 54,
      abilities: ["Power Surge"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Will", lastName: "Craddock", position: "2B", eligibility: "FR", homeState: "SC", hometown: "Summerville", jerseyNumber: 16,
      hitForAvg: 40, power: 30, speed: 54, arm: 54, fielding: 48, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 32, running: 52, throwing: 56, recovery: 36, wRISP: 36, vsLefty: 34, poise: 38, heater: 0, agile: 56,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Tyler", lastName: "Bak", position: "OF", eligibility: "JR", homeState: "SC", hometown: "Spartanburg", jerseyNumber: 1,
      hitForAvg: 66, power: 48, speed: 68, arm: 66, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 58, grit: 64, stealing: 48, running: 66, throwing: 68, recovery: 52, wRISP: 58, vsLefty: 56, poise: 60, heater: 0, agile: 70,
      abilities: ["Speed Demon"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Patrick", lastName: "Evans", position: "OF", eligibility: "JR", homeState: "SC", hometown: "Florence", jerseyNumber: 8,
      hitForAvg: 72, power: 66, speed: 56, arm: 68, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 30, running: 54, throwing: 70, recovery: 56, wRISP: 70, vsLefty: 64, poise: 68, heater: 0, agile: 58,
      abilities: ["Power Surge", "Clutch Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Ethan", lastName: "Lizama", position: "OF", eligibility: "SR", homeState: "CA", hometown: "San Diego", jerseyNumber: 3,
      hitForAvg: 70, power: 68, speed: 54, arm: 70, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 28, running: 52, throwing: 72, recovery: 56, wRISP: 68, vsLefty: 62, poise: 68, heater: 0, agile: 56,
      abilities: ["Power Surge", "Cannon Arm"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Reese", lastName: "Moore", position: "OF", eligibility: "JR", homeState: "IA", hometown: "Iowa City", jerseyNumber: 12,
      hitForAvg: 64, power: 60, speed: 48, arm: 60, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 20, running: 46, throwing: 62, recovery: 52, wRISP: 64, vsLefty: 58, poise: 62, heater: 0, agile: 50,
      abilities: ["Clutch Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Aaron", lastName: "Jamison", position: "OF", eligibility: "FR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 22,
      hitForAvg: 40, power: 34, speed: 58, arm: 56, fielding: 46, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 36, running: 56, throwing: 58, recovery: 36, wRISP: 36, vsLefty: 34, poise: 38, heater: 0, agile: 60,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Caleb", lastName: "Hoover", position: "OF", eligibility: "FR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 26,
      hitForAvg: 38, power: 32, speed: 56, arm: 54, fielding: 44, errorResistance: 40, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 36, vsLHP: 34, grit: 38, stealing: 34, running: 54, throwing: 56, recovery: 34, wRISP: 34, vsLefty: 32, poise: 36, heater: 0, agile: 58,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Erik", lastName: "Parker", position: "SS", eligibility: "FR", homeState: "SC", hometown: "Greer", jerseyNumber: 30,
      hitForAvg: 40, power: 32, speed: 56, arm: 56, fielding: 50, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 34, running: 54, throwing: 58, recovery: 36, wRISP: 36, vsLefty: 34, poise: 38, heater: 0, agile: 58,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Bryce", lastName: "Watkins", position: "OF", eligibility: "JR", homeState: "NC", hometown: "Wilmington", jerseyNumber: 32,
      hitForAvg: 58, power: 48, speed: 56, arm: 62, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 34, running: 54, throwing: 64, recovery: 48, wRISP: 54, vsLefty: 50, poise: 56, heater: 0, agile: 58,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "Kentucky": [
    // PITCHERS (10)
    { firstName: "Jaxon", lastName: "Jelkin", position: "P", eligibility: "SR", homeState: "TX", hometown: "Houston", jerseyNumber: 34,
      hitForAvg: 18, power: 14, speed: 40, arm: 78, fielding: 50, errorResistance: 52, velocity: 80, control: 74, stamina: 72, stuff: 78,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 10, running: 36, throwing: 76, recovery: 64, wRISP: 70, vsLefty: 72, poise: 74, heater: 78, agile: 44,
      abilities: ["Strong Starter", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 5, 0, 0, 0]) },
    { firstName: "Ben", lastName: "Cleaver", position: "P", eligibility: "JR", homeState: "KY", hometown: "Louisville", jerseyNumber: 22,
      hitForAvg: 16, power: 12, speed: 38, arm: 76, fielding: 48, errorResistance: 50, velocity: 78, control: 76, stamina: 76, stuff: 76,
      clutch: 70, vsLHP: 68, grit: 72, stealing: 10, running: 34, throwing: 74, recovery: 68, wRISP: 68, vsLefty: 72, poise: 72, heater: 76, agile: 42,
      abilities: ["Strong Starter", "Workhorse"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 6, 5, 0, 0, 0]) },
    { firstName: "Nate", lastName: "Harris", position: "P", eligibility: "SO", homeState: "KY", hometown: "Lexington", jerseyNumber: 29,
      hitForAvg: 16, power: 12, speed: 40, arm: 74, fielding: 48, errorResistance: 50, velocity: 76, control: 72, stamina: 74, stuff: 74,
      clutch: 66, vsLHP: 64, grit: 68, stealing: 12, running: 36, throwing: 72, recovery: 64, wRISP: 64, vsLefty: 68, poise: 68, heater: 74, agile: 44,
      abilities: ["Strong Starter"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 4, 0, 0, 0]) },
    { firstName: "Tommy", lastName: "Skelding", position: "P", eligibility: "SO", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 37,
      hitForAvg: 14, power: 10, speed: 38, arm: 70, fielding: 46, errorResistance: 48, velocity: 72, control: 68, stamina: 68, stuff: 70,
      clutch: 60, vsLHP: 58, grit: 64, stealing: 10, running: 34, throwing: 68, recovery: 60, wRISP: 58, vsLefty: 62, poise: 62, heater: 70, agile: 42,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Nile", lastName: "Adcock", position: "P", eligibility: "SR", homeState: "KY", hometown: "Bowling Green", jerseyNumber: 38,
      hitForAvg: 16, power: 12, speed: 38, arm: 72, fielding: 48, errorResistance: 50, velocity: 74, control: 72, stamina: 70, stuff: 72,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 10, running: 34, throwing: 70, recovery: 64, wRISP: 64, vsLefty: 66, poise: 68, heater: 72, agile: 42,
      abilities: ["Fireman"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Chase", lastName: "Alderman", position: "P", eligibility: "JR", homeState: "KY", hometown: "Paducah", jerseyNumber: 42,
      hitForAvg: 16, power: 12, speed: 40, arm: 72, fielding: 46, errorResistance: 48, velocity: 74, control: 70, stamina: 70, stuff: 72,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 12, running: 36, throwing: 70, recovery: 62, wRISP: 62, vsLefty: 64, poise: 66, heater: 72, agile: 44,
      abilities: ["Filthy Breaking Ball"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 5, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Hagenow", position: "P", eligibility: "JR", homeState: "IN", hometown: "Evansville", jerseyNumber: 40,
      hitForAvg: 14, power: 10, speed: 38, arm: 68, fielding: 44, errorResistance: 46, velocity: 70, control: 66, stamina: 66, stuff: 68,
      clutch: 60, vsLHP: 58, grit: 64, stealing: 10, running: 34, throwing: 66, recovery: 58, wRISP: 58, vsLefty: 62, poise: 62, heater: 68, agile: 42,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Mason", lastName: "Wright", position: "P", eligibility: "SO", homeState: "KY", hometown: "Florence", jerseyNumber: 44,
      hitForAvg: 14, power: 10, speed: 40, arm: 66, fielding: 42, errorResistance: 44, velocity: 68, control: 64, stamina: 64, stuff: 66,
      clutch: 56, vsLHP: 54, grit: 60, stealing: 12, running: 36, throwing: 64, recovery: 56, wRISP: 54, vsLefty: 58, poise: 58, heater: 66, agile: 44,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 5, 0, 0, 0]) },
    { firstName: "Brady", lastName: "Kirtley", position: "P", eligibility: "FR", homeState: "KY", hometown: "Owensboro", jerseyNumber: 46,
      hitForAvg: 12, power: 10, speed: 42, arm: 64, fielding: 38, errorResistance: 40, velocity: 66, control: 52, stamina: 50, stuff: 64,
      clutch: 44, vsLHP: 42, grit: 46, stealing: 14, running: 38, throwing: 62, recovery: 44, wRISP: 42, vsLefty: 46, poise: 44, heater: 64, agile: 46,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 4, 0, 0, 0]) },
    { firstName: "Gavin", lastName: "Porter", position: "P", eligibility: "FR", homeState: "TN", hometown: "Nashville", jerseyNumber: 48,
      hitForAvg: 12, power: 10, speed: 40, arm: 62, fielding: 36, errorResistance: 38, velocity: 64, control: 50, stamina: 48, stuff: 62,
      clutch: 42, vsLHP: 40, grit: 44, stealing: 12, running: 36, throwing: 60, recovery: 42, wRISP: 40, vsLefty: 44, poise: 42, heater: 62, agile: 44,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Devin", lastName: "Burkes", position: "C", eligibility: "JR", homeState: "KY", hometown: "Covington", jerseyNumber: 19,
      hitForAvg: 62, power: 56, speed: 40, arm: 72, fielding: 70, errorResistance: 68, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 18, running: 38, throwing: 74, recovery: 54, wRISP: 62, vsLefty: 58, poise: 64, heater: 0, agile: 44,
      abilities: ["Iron Glove"], potential: "B+", catcherAbility: 66,
      ...noPitches },
    { firstName: "Colin", lastName: "Slater", position: "C", eligibility: "FR", homeState: "OH", hometown: "Columbus", jerseyNumber: 25,
      hitForAvg: 40, power: 34, speed: 36, arm: 58, fielding: 50, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 14, running: 34, throwing: 60, recovery: 36, wRISP: 36, vsLefty: 34, poise: 38, heater: 0, agile: 38,
      abilities: [], potential: "B+", catcherAbility: 56,
      ...noPitches },
    // INFIELDERS (5)
    { firstName: "Tyler", lastName: "Bell", position: "SS", eligibility: "SO", homeState: "FL", hometown: "Tampa", jerseyNumber: 2,
      hitForAvg: 84, power: 68, speed: 74, arm: 78, fielding: 80, errorResistance: 78, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 82, vsLHP: 78, grit: 82, stealing: 60, running: 72, throwing: 80, recovery: 64, wRISP: 82, vsLefty: 76, poise: 80, heater: 0, agile: 76,
      abilities: ["Contact Machine", "Speed Demon", "Iron Glove", "Clutch Hitter"], potential: "A+", catcherAbility: null,
      ...noPitches },
    { firstName: "Luke", lastName: "Lawrence", position: "2B", eligibility: "SR", homeState: "KY", hometown: "Lexington", jerseyNumber: 6,
      hitForAvg: 64, power: 50, speed: 56, arm: 64, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 66, stealing: 36, running: 54, throwing: 66, recovery: 54, wRISP: 60, vsLefty: 56, poise: 64, heater: 0, agile: 58,
      abilities: ["Table Setter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Hudson", lastName: "Brown", position: "1B", eligibility: "JR", homeState: "KY", hometown: "Louisville", jerseyNumber: 8,
      hitForAvg: 66, power: 64, speed: 44, arm: 62, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 16, running: 42, throwing: 64, recovery: 54, wRISP: 66, vsLefty: 60, poise: 66, heater: 0, agile: 46,
      abilities: ["Power Surge"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Ethan", lastName: "Hindle", position: "3B", eligibility: "JR", homeState: "OH", hometown: "Dayton", jerseyNumber: 10,
      hitForAvg: 60, power: 52, speed: 50, arm: 66, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 62, stealing: 26, running: 48, throwing: 68, recovery: 50, wRISP: 56, vsLefty: 52, poise: 58, heater: 0, agile: 52,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Jake", lastName: "Newell", position: "SS", eligibility: "FR", homeState: "KY", hometown: "Richmond", jerseyNumber: 24,
      hitForAvg: 44, power: 34, speed: 58, arm: 58, fielding: 52, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 40, grit: 44, stealing: 36, running: 56, throwing: 60, recovery: 38, wRISP: 40, vsLefty: 38, poise: 42, heater: 0, agile: 60,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Ryan", lastName: "Schwartz", position: "OF", eligibility: "SO", homeState: "KY", hometown: "Lexington", jerseyNumber: 1,
      hitForAvg: 66, power: 58, speed: 64, arm: 68, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 44, running: 62, throwing: 70, recovery: 54, wRISP: 62, vsLefty: 58, poise: 64, heater: 0, agile: 66,
      abilities: ["Speed Demon"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Carson", lastName: "Hansen", position: "OF", eligibility: "SR", homeState: "OH", hometown: "Toledo", jerseyNumber: 9,
      hitForAvg: 64, power: 60, speed: 48, arm: 62, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 20, running: 46, throwing: 64, recovery: 54, wRISP: 66, vsLefty: 60, poise: 66, heater: 0, agile: 50,
      abilities: ["Clutch Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Will", lastName: "Marcy", position: "OF", eligibility: "JR", homeState: "KY", hometown: "Frankfort", jerseyNumber: 7,
      hitForAvg: 62, power: 54, speed: 60, arm: 66, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 40, running: 58, throwing: 68, recovery: 52, wRISP: 58, vsLefty: 54, poise: 60, heater: 0, agile: 62,
      abilities: ["Cannon Arm"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Bryce", lastName: "Hamilton", position: "OF", eligibility: "FR", homeState: "TN", hometown: "Knoxville", jerseyNumber: 26,
      hitForAvg: 42, power: 36, speed: 58, arm: 56, fielding: 48, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 36, running: 56, throwing: 58, recovery: 38, wRISP: 38, vsLefty: 36, poise: 40, heater: 0, agile: 60,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Drew", lastName: "Foster", position: "OF", eligibility: "JR", homeState: "KY", hometown: "Ashland", jerseyNumber: 11,
      hitForAvg: 60, power: 52, speed: 56, arm: 64, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 34, running: 54, throwing: 66, recovery: 50, wRISP: 56, vsLefty: 52, poise: 58, heater: 0, agile: 58,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Cole", lastName: "Daniels", position: "3B", eligibility: "SO", homeState: "KY", hometown: "Elizabethtown", jerseyNumber: 14,
      hitForAvg: 58, power: 50, speed: 48, arm: 64, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 22, running: 46, throwing: 66, recovery: 48, wRISP: 54, vsLefty: 50, poise: 56, heater: 0, agile: 50,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Tanner", lastName: "Mills", position: "OF", eligibility: "JR", homeState: "OH", hometown: "Akron", jerseyNumber: 3,
      hitForAvg: 60, power: 54, speed: 58, arm: 66, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 36, running: 56, throwing: 68, recovery: 50, wRISP: 56, vsLefty: 52, poise: 58, heater: 0, agile: 60,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Aidan", lastName: "Cooper", position: "1B", eligibility: "SO", homeState: "KY", hometown: "Hopkinsville", jerseyNumber: 20,
      hitForAvg: 56, power: 54, speed: 40, arm: 58, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 14, running: 38, throwing: 60, recovery: 46, wRISP: 54, vsLefty: 48, poise: 54, heater: 0, agile: 42,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Missouri": [
    // PITCHERS (10)
    { firstName: "Javyn", lastName: "Pimental", position: "P", eligibility: "SR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 33,
      hitForAvg: 16, power: 12, speed: 38, arm: 72, fielding: 48, errorResistance: 50, velocity: 74, control: 72, stamina: 70, stuff: 72,
      clutch: 64, vsLHP: 62, grit: 68, stealing: 10, running: 34, throwing: 70, recovery: 62, wRISP: 62, vsLefty: 66, poise: 66, heater: 72, agile: 42,
      abilities: ["Workhorse", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 6, 4, 0, 0, 0]) },
    { firstName: "Josh", lastName: "McDevitt", position: "P", eligibility: "JR", homeState: "MO", hometown: "St. Louis", jerseyNumber: 22,
      hitForAvg: 14, power: 10, speed: 40, arm: 68, fielding: 46, errorResistance: 48, velocity: 70, control: 66, stamina: 68, stuff: 68,
      clutch: 58, vsLHP: 56, grit: 62, stealing: 10, running: 36, throwing: 66, recovery: 58, wRISP: 56, vsLefty: 60, poise: 60, heater: 68, agile: 44,
      abilities: ["Strong Starter"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Brady", lastName: "Kehlenbrink", position: "P", eligibility: "SO", homeState: "MO", hometown: "Kansas City", jerseyNumber: 37,
      hitForAvg: 14, power: 10, speed: 40, arm: 66, fielding: 44, errorResistance: 46, velocity: 68, control: 64, stamina: 64, stuff: 66,
      clutch: 56, vsLHP: 54, grit: 60, stealing: 12, running: 36, throwing: 64, recovery: 56, wRISP: 54, vsLefty: 58, poise: 58, heater: 66, agile: 44,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Stokes", position: "P", eligibility: "JR", homeState: "MO", hometown: "Springfield", jerseyNumber: 29,
      hitForAvg: 14, power: 10, speed: 38, arm: 66, fielding: 44, errorResistance: 46, velocity: 68, control: 66, stamina: 66, stuff: 66,
      clutch: 58, vsLHP: 56, grit: 60, stealing: 10, running: 34, throwing: 64, recovery: 56, wRISP: 56, vsLefty: 60, poise: 60, heater: 66, agile: 42,
      abilities: ["Fireman"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 3, 0, 0, 0]) },
    { firstName: "Noah", lastName: "Mitchell", position: "P", eligibility: "JR", homeState: "IL", hometown: "Edwardsville", jerseyNumber: 38,
      hitForAvg: 14, power: 10, speed: 38, arm: 64, fielding: 42, errorResistance: 44, velocity: 66, control: 64, stamina: 64, stuff: 64,
      clutch: 56, vsLHP: 54, grit: 58, stealing: 10, running: 34, throwing: 62, recovery: 54, wRISP: 54, vsLefty: 58, poise: 58, heater: 64, agile: 42,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Drew", lastName: "Walters", position: "P", eligibility: "SR", homeState: "MO", hometown: "Columbia", jerseyNumber: 40,
      hitForAvg: 14, power: 10, speed: 36, arm: 64, fielding: 44, errorResistance: 46, velocity: 66, control: 66, stamina: 64, stuff: 64,
      clutch: 58, vsLHP: 56, grit: 60, stealing: 10, running: 32, throwing: 62, recovery: 56, wRISP: 56, vsLefty: 60, poise: 60, heater: 64, agile: 40,
      abilities: [], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 4, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Kraft", position: "P", eligibility: "JR", homeState: "KS", hometown: "Overland Park", jerseyNumber: 42,
      hitForAvg: 14, power: 10, speed: 40, arm: 64, fielding: 42, errorResistance: 44, velocity: 66, control: 62, stamina: 62, stuff: 64,
      clutch: 54, vsLHP: 52, grit: 58, stealing: 10, running: 36, throwing: 62, recovery: 52, wRISP: 52, vsLefty: 56, poise: 56, heater: 64, agile: 44,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 5, 0, 0, 0]) },
    { firstName: "Cade", lastName: "Reynolds", position: "P", eligibility: "SO", homeState: "MO", hometown: "Lee's Summit", jerseyNumber: 44,
      hitForAvg: 12, power: 10, speed: 38, arm: 62, fielding: 40, errorResistance: 42, velocity: 64, control: 60, stamina: 60, stuff: 62,
      clutch: 52, vsLHP: 50, grit: 56, stealing: 10, running: 34, throwing: 60, recovery: 50, wRISP: 50, vsLefty: 54, poise: 54, heater: 62, agile: 42,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 4, 0, 0, 0]) },
    { firstName: "Landon", lastName: "Price", position: "P", eligibility: "FR", homeState: "MO", hometown: "Jefferson City", jerseyNumber: 46,
      hitForAvg: 12, power: 10, speed: 42, arm: 60, fielding: 36, errorResistance: 38, velocity: 62, control: 48, stamina: 46, stuff: 60,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 14, running: 38, throwing: 58, recovery: 40, wRISP: 38, vsLefty: 42, poise: 40, heater: 60, agile: 46,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Donaldson", position: "P", eligibility: "FR", homeState: "IL", hometown: "O'Fallon", jerseyNumber: 48,
      hitForAvg: 12, power: 10, speed: 40, arm: 58, fielding: 34, errorResistance: 36, velocity: 60, control: 46, stamina: 44, stuff: 56,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 12, running: 36, throwing: 56, recovery: 38, wRISP: 36, vsLefty: 40, poise: 38, heater: 58, agile: 44,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 3, 3, 4, 0, 0, 0]) },
    // CATCHERS (1)
    { firstName: "Mateo", lastName: "Serna", position: "C", eligibility: "JR", homeState: "TX", hometown: "San Antonio", jerseyNumber: 14,
      hitForAvg: 56, power: 58, speed: 38, arm: 68, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 62, stealing: 14, running: 36, throwing: 70, recovery: 50, wRISP: 56, vsLefty: 52, poise: 58, heater: 0, agile: 42,
      abilities: [], potential: "B+", catcherAbility: 62,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Chris", lastName: "Patterson", position: "3B", eligibility: "JR", homeState: "MO", hometown: "Blue Springs", jerseyNumber: 5,
      hitForAvg: 54, power: 50, speed: 48, arm: 64, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 22, running: 46, throwing: 66, recovery: 46, wRISP: 52, vsLefty: 48, poise: 54, heater: 0, agile: 50,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Kam", lastName: "Durnin", position: "SS", eligibility: "JR", homeState: "NE", hometown: "Omaha", jerseyNumber: 2,
      hitForAvg: 56, power: 44, speed: 58, arm: 68, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 58, stealing: 38, running: 56, throwing: 70, recovery: 48, wRISP: 52, vsLefty: 48, poise: 56, heater: 0, agile: 60,
      abilities: ["Iron Glove"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Jalen", lastName: "Woita", position: "2B", eligibility: "JR", homeState: "SC", hometown: "Columbia", jerseyNumber: 10,
      hitForAvg: 62, power: 54, speed: 52, arm: 62, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 28, running: 50, throwing: 64, recovery: 50, wRISP: 60, vsLefty: 54, poise: 60, heater: 0, agile: 54,
      abilities: ["Contact Machine"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Peyton", lastName: "Basler", position: "1B", eligibility: "SR", homeState: "MO", hometown: "St. Charles", jerseyNumber: 18,
      hitForAvg: 56, power: 52, speed: 40, arm: 58, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 52, grit: 60, stealing: 14, running: 38, throwing: 60, recovery: 48, wRISP: 54, vsLefty: 50, poise: 58, heater: 0, agile: 42,
      abilities: [], potential: "B-", catcherAbility: null,
      ...noPitches },
    { firstName: "Gehrig", lastName: "Goldbeck", position: "3B", eligibility: "SR", homeState: "MO", hometown: "St. Louis", jerseyNumber: 16,
      hitForAvg: 54, power: 48, speed: 44, arm: 62, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 58, stealing: 18, running: 42, throwing: 64, recovery: 46, wRISP: 52, vsLefty: 48, poise: 56, heater: 0, agile: 46,
      abilities: [], potential: "B-", catcherAbility: null,
      ...noPitches },
    { firstName: "Keegan", lastName: "Knutson", position: "2B", eligibility: "SR", homeState: "IA", hometown: "Des Moines", jerseyNumber: 20,
      hitForAvg: 52, power: 44, speed: 48, arm: 58, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 48, grit: 56, stealing: 24, running: 46, throwing: 60, recovery: 44, wRISP: 50, vsLefty: 46, poise: 54, heater: 0, agile: 50,
      abilities: [], potential: "B-", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (5)
    { firstName: "Kaden", lastName: "Peer", position: "OF", eligibility: "JR", homeState: "MO", hometown: "Joplin", jerseyNumber: 1,
      hitForAvg: 62, power: 50, speed: 58, arm: 64, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 38, running: 56, throwing: 66, recovery: 50, wRISP: 60, vsLefty: 54, poise: 60, heater: 0, agile: 60,
      abilities: ["Table Setter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Pierre", lastName: "Seals", position: "OF", eligibility: "SR", homeState: "MO", hometown: "Kansas City", jerseyNumber: 7,
      hitForAvg: 60, power: 56, speed: 56, arm: 66, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 34, running: 54, throwing: 68, recovery: 50, wRISP: 58, vsLefty: 54, poise: 60, heater: 0, agile: 58,
      abilities: ["Cannon Arm"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Cameron", lastName: "Benson", position: "OF", eligibility: "JR", homeState: "MO", hometown: "Independence", jerseyNumber: 3,
      hitForAvg: 64, power: 56, speed: 56, arm: 64, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 32, running: 54, throwing: 66, recovery: 50, wRISP: 62, vsLefty: 56, poise: 62, heater: 0, agile: 58,
      abilities: ["Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Owen", lastName: "Burke", position: "OF", eligibility: "FR", homeState: "MO", hometown: "Chesterfield", jerseyNumber: 26,
      hitForAvg: 38, power: 30, speed: 56, arm: 54, fielding: 44, errorResistance: 40, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 36, vsLHP: 34, grit: 38, stealing: 34, running: 54, throwing: 56, recovery: 34, wRISP: 34, vsLefty: 32, poise: 36, heater: 0, agile: 58,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Carter", lastName: "Fields", position: "OF", eligibility: "FR", homeState: "KS", hometown: "Wichita", jerseyNumber: 24,
      hitForAvg: 36, power: 28, speed: 54, arm: 52, fielding: 42, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 34, vsLHP: 32, grit: 36, stealing: 32, running: 52, throwing: 54, recovery: 32, wRISP: 32, vsLefty: 30, poise: 34, heater: 0, agile: 56,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Marcus", lastName: "Webb", position: "1B", eligibility: "FR", homeState: "MO", hometown: "Ballwin", jerseyNumber: 30,
      hitForAvg: 38, power: 36, speed: 36, arm: 52, fielding: 44, errorResistance: 40, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 36, vsLHP: 34, grit: 38, stealing: 12, running: 34, throwing: 54, recovery: 34, wRISP: 34, vsLefty: 32, poise: 36, heater: 0, agile: 38,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Austin", lastName: "Reed", position: "C", eligibility: "SO", homeState: "MO", hometown: "Rolla", jerseyNumber: 12,
      hitForAvg: 50, power: 44, speed: 36, arm: 62, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 46, grit: 54, stealing: 12, running: 34, throwing: 64, recovery: 44, wRISP: 48, vsLefty: 44, poise: 52, heater: 0, agile: 38,
      abilities: [], potential: "B", catcherAbility: 58,
      ...noPitches },
    { firstName: "Jake", lastName: "Thornton", position: "OF", eligibility: "JR", homeState: "MO", hometown: "Wentzville", jerseyNumber: 8,
      hitForAvg: 56, power: 48, speed: 56, arm: 62, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 34, running: 54, throwing: 64, recovery: 46, wRISP: 52, vsLefty: 48, poise: 54, heater: 0, agile: 58,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "Oklahoma": [
    // PITCHERS (10)
    { firstName: "Cameron", lastName: "Johnson", position: "P", eligibility: "JR", homeState: "LA", hometown: "Baton Rouge", jerseyNumber: 33,
      hitForAvg: 18, power: 14, speed: 38, arm: 78, fielding: 50, errorResistance: 52, velocity: 82, control: 74, stamina: 76, stuff: 80,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 10, running: 34, throwing: 76, recovery: 68, wRISP: 70, vsLefty: 72, poise: 74, heater: 80, agile: 42,
      abilities: ["Ace", "Strong Starter", "Explosive Fastball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 5, 0, 0, 0]) },
    { firstName: "LJ", lastName: "Mercurius", position: "P", eligibility: "JR", homeState: "NV", hometown: "Las Vegas", jerseyNumber: 22,
      hitForAvg: 16, power: 12, speed: 40, arm: 76, fielding: 48, errorResistance: 50, velocity: 80, control: 74, stamina: 74, stuff: 78,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 12, running: 36, throwing: 74, recovery: 66, wRISP: 68, vsLefty: 70, poise: 72, heater: 78, agile: 44,
      abilities: ["Strong Starter", "Filthy Breaking Ball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 7, 5, 0, 0, 0]) },
    { firstName: "Reid", lastName: "Hensley", position: "P", eligibility: "SR", homeState: "OK", hometown: "Tulsa", jerseyNumber: 29,
      hitForAvg: 16, power: 12, speed: 38, arm: 74, fielding: 48, errorResistance: 50, velocity: 76, control: 76, stamina: 74, stuff: 74,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 10, running: 34, throwing: 72, recovery: 66, wRISP: 68, vsLefty: 70, poise: 72, heater: 74, agile: 42,
      abilities: ["Workhorse", "Guts"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 4, 0, 0, 0]) },
    { firstName: "Jaden", lastName: "Barfield", position: "P", eligibility: "SO", homeState: "OK", hometown: "Norman", jerseyNumber: 37,
      hitForAvg: 14, power: 10, speed: 40, arm: 72, fielding: 46, errorResistance: 48, velocity: 74, control: 70, stamina: 70, stuff: 72,
      clutch: 62, vsLHP: 60, grit: 66, stealing: 12, running: 36, throwing: 70, recovery: 62, wRISP: 60, vsLefty: 64, poise: 64, heater: 72, agile: 44,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Mason", lastName: "Bixby", position: "P", eligibility: "JR", homeState: "TX", hometown: "Fort Worth", jerseyNumber: 38,
      hitForAvg: 16, power: 12, speed: 38, arm: 72, fielding: 46, errorResistance: 48, velocity: 74, control: 72, stamina: 72, stuff: 72,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 10, running: 34, throwing: 70, recovery: 64, wRISP: 64, vsLefty: 66, poise: 68, heater: 72, agile: 42,
      abilities: ["Fireman"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Cord", lastName: "Rager", position: "P", eligibility: "FR", homeState: "TX", hometown: "Austin", jerseyNumber: 34,
      hitForAvg: 14, power: 10, speed: 42, arm: 70, fielding: 40, errorResistance: 42, velocity: 72, control: 58, stamina: 56, stuff: 70,
      clutch: 50, vsLHP: 48, grit: 54, stealing: 14, running: 38, throwing: 68, recovery: 48, wRISP: 48, vsLefty: 52, poise: 50, heater: 70, agile: 46,
      abilities: ["Explosive Fastball"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Xander", lastName: "Mercurius", position: "P", eligibility: "FR", homeState: "NV", hometown: "Reno", jerseyNumber: 46,
      hitForAvg: 12, power: 10, speed: 42, arm: 66, fielding: 38, errorResistance: 40, velocity: 68, control: 54, stamina: 50, stuff: 66,
      clutch: 46, vsLHP: 44, grit: 48, stealing: 14, running: 38, throwing: 64, recovery: 44, wRISP: 44, vsLefty: 48, poise: 46, heater: 66, agile: 46,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 3, 0, 0, 0]) },
    { firstName: "Nolan", lastName: "Stevens", position: "P", eligibility: "FR", homeState: "MS", hometown: "Starkville", jerseyNumber: 48,
      hitForAvg: 14, power: 12, speed: 40, arm: 64, fielding: 40, errorResistance: 42, velocity: 66, control: 52, stamina: 48, stuff: 64,
      clutch: 44, vsLHP: 42, grit: 46, stealing: 12, running: 36, throwing: 62, recovery: 42, wRISP: 42, vsLefty: 46, poise: 44, heater: 64, agile: 44,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 4, 0, 0, 0]) },
    { firstName: "Colton", lastName: "Briggs", position: "P", eligibility: "JR", homeState: "OK", hometown: "Edmond", jerseyNumber: 40,
      hitForAvg: 14, power: 10, speed: 38, arm: 70, fielding: 44, errorResistance: 46, velocity: 72, control: 68, stamina: 68, stuff: 70,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 10, running: 34, throwing: 68, recovery: 60, wRISP: 60, vsLefty: 62, poise: 64, heater: 70, agile: 42,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 4, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Pearson", position: "P", eligibility: "JR", homeState: "TX", hometown: "Dallas", jerseyNumber: 42,
      hitForAvg: 14, power: 10, speed: 40, arm: 68, fielding: 44, errorResistance: 46, velocity: 70, control: 66, stamina: 66, stuff: 68,
      clutch: 58, vsLHP: 56, grit: 62, stealing: 10, running: 36, throwing: 66, recovery: 58, wRISP: 56, vsLefty: 60, poise: 60, heater: 68, agile: 44,
      abilities: [], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 3, 0, 0, 0]) },
    // CATCHERS (1)
    { firstName: "Deiten", lastName: "Lachance", position: "C", eligibility: "JR", homeState: "FL", hometown: "Orlando", jerseyNumber: 12,
      hitForAvg: 72, power: 72, speed: 42, arm: 74, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 74, vsLHP: 70, grit: 74, stealing: 18, running: 40, throwing: 76, recovery: 58, wRISP: 74, vsLefty: 68, poise: 72, heater: 0, agile: 44,
      abilities: ["Power Surge", "Clutch Hitter"], potential: "A-", catcherAbility: 68,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Kyle", lastName: "Branch", position: "2B", eligibility: "SO", homeState: "OK", hometown: "Oklahoma City", jerseyNumber: 2,
      hitForAvg: 68, power: 52, speed: 64, arm: 68, fielding: 72, errorResistance: 70, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 44, running: 62, throwing: 70, recovery: 54, wRISP: 64, vsLefty: 60, poise: 66, heater: 0, agile: 66,
      abilities: ["Iron Glove", "Table Setter"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Jaxon", lastName: "Willits", position: "SS", eligibility: "JR", homeState: "OK", hometown: "Broken Arrow", jerseyNumber: 6,
      hitForAvg: 68, power: 60, speed: 60, arm: 72, fielding: 72, errorResistance: 70, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 40, running: 58, throwing: 74, recovery: 56, wRISP: 70, vsLefty: 64, poise: 70, heater: 0, agile: 62,
      abilities: ["Contact Machine", "Clutch Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Dayton", lastName: "Tockey", position: "1B", eligibility: "JR", homeState: "OK", hometown: "Stillwater", jerseyNumber: 18,
      hitForAvg: 62, power: 62, speed: 42, arm: 60, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 14, running: 40, throwing: 62, recovery: 52, wRISP: 64, vsLefty: 58, poise: 64, heater: 0, agile: 44,
      abilities: ["Power Surge"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Camden", lastName: "Johnson", position: "3B", eligibility: "JR", homeState: "KS", hometown: "Wichita", jerseyNumber: 10,
      hitForAvg: 68, power: 58, speed: 50, arm: 68, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 62, grit: 68, stealing: 26, running: 48, throwing: 70, recovery: 54, wRISP: 66, vsLefty: 60, poise: 66, heater: 0, agile: 52,
      abilities: ["Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Brendan", lastName: "Brock", position: "1B", eligibility: "FR", homeState: "OK", hometown: "Moore", jerseyNumber: 24,
      hitForAvg: 44, power: 40, speed: 38, arm: 54, fielding: 48, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 40, grit: 44, stealing: 14, running: 36, throwing: 56, recovery: 38, wRISP: 42, vsLefty: 38, poise: 42, heater: 0, agile: 40,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Cayden", lastName: "Brumbaugh", position: "SS", eligibility: "FR", homeState: "NE", hometown: "Lincoln", jerseyNumber: 30,
      hitForAvg: 42, power: 34, speed: 56, arm: 58, fielding: 52, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 38, grit: 42, stealing: 34, running: 54, throwing: 60, recovery: 36, wRISP: 38, vsLefty: 36, poise: 40, heater: 0, agile: 58,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (4)
    { firstName: "Trey", lastName: "Gambill", position: "OF", eligibility: "JR", homeState: "OK", hometown: "Norman", jerseyNumber: 1,
      hitForAvg: 66, power: 50, speed: 62, arm: 64, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 42, running: 60, throwing: 66, recovery: 52, wRISP: 64, vsLefty: 58, poise: 64, heater: 0, agile: 64,
      abilities: ["Table Setter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Jason", lastName: "Walk", position: "OF", eligibility: "JR", homeState: "OK", hometown: "Edmond", jerseyNumber: 7,
      hitForAvg: 62, power: 58, speed: 64, arm: 68, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 58, grit: 66, stealing: 44, running: 62, throwing: 70, recovery: 52, wRISP: 62, vsLefty: 56, poise: 64, heater: 0, agile: 66,
      abilities: ["Speed Demon"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Drew", lastName: "Dickerson", position: "OF", eligibility: "SO", homeState: "OK", hometown: "Tulsa", jerseyNumber: 9,
      hitForAvg: 58, power: 56, speed: 58, arm: 64, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 56, grit: 64, stealing: 36, running: 56, throwing: 66, recovery: 50, wRISP: 62, vsLefty: 54, poise: 62, heater: 0, agile: 60,
      abilities: ["Clutch Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Grant", lastName: "Ellis", position: "OF", eligibility: "JR", homeState: "TX", hometown: "Plano", jerseyNumber: 11,
      hitForAvg: 60, power: 52, speed: 56, arm: 66, fielding: 60, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 58, vsLHP: 54, grit: 60, stealing: 34, running: 54, throwing: 68, recovery: 50, wRISP: 56, vsLefty: 52, poise: 58, heater: 0, agile: 58,
      abilities: ["Cannon Arm"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Luke", lastName: "Hoffman", position: "C", eligibility: "SO", homeState: "OK", hometown: "Lawton", jerseyNumber: 19,
      hitForAvg: 54, power: 48, speed: 36, arm: 66, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 58, stealing: 12, running: 34, throwing: 68, recovery: 46, wRISP: 52, vsLefty: 48, poise: 56, heater: 0, agile: 38,
      abilities: [], potential: "B+", catcherAbility: 60,
      ...noPitches },
    { firstName: "Tyler", lastName: "Owens", position: "OF", eligibility: "JR", homeState: "TX", hometown: "Lubbock", jerseyNumber: 3,
      hitForAvg: 60, power: 54, speed: 60, arm: 66, fielding: 62, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 62, stealing: 38, running: 58, throwing: 68, recovery: 50, wRISP: 58, vsLefty: 54, poise: 60, heater: 0, agile: 62,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Marcus", lastName: "Pruitt", position: "2B", eligibility: "JR", homeState: "OK", hometown: "Tulsa", jerseyNumber: 14,
      hitForAvg: 58, power: 46, speed: 54, arm: 62, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 32, running: 52, throwing: 64, recovery: 48, wRISP: 54, vsLefty: 50, poise: 56, heater: 0, agile: 56,
      abilities: [], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Ryan", lastName: "Torres", position: "OF", eligibility: "SO", homeState: "OK", hometown: "Norman", jerseyNumber: 16,
      hitForAvg: 56, power: 50, speed: 58, arm: 62, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 56, stealing: 36, running: 56, throwing: 64, recovery: 46, wRISP: 52, vsLefty: 48, poise: 54, heater: 0, agile: 60,
      abilities: [], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Texas": [
    // PITCHERS (10)
    { firstName: "Ruger", lastName: "Riojas", position: "P", eligibility: "SR", homeState: "TX", hometown: "San Antonio", jerseyNumber: 34,
      hitForAvg: 18, power: 14, speed: 40, arm: 84, fielding: 52, errorResistance: 54, velocity: 86, control: 80, stamina: 82, stuff: 84,
      clutch: 80, vsLHP: 76, grit: 82, stealing: 10, running: 36, throwing: 82, recovery: 74, wRISP: 78, vsLefty: 80, poise: 82, heater: 84, agile: 44,
      abilities: ["Ace", "Strong Starter", "Workhorse"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 7, 6, 5, 0, 0, 0]) },
    { firstName: "Luke", lastName: "Harrison", position: "P", eligibility: "SR", homeState: "TX", hometown: "Houston", jerseyNumber: 22,
      hitForAvg: 18, power: 14, speed: 38, arm: 82, fielding: 50, errorResistance: 52, velocity: 84, control: 78, stamina: 80, stuff: 82,
      clutch: 78, vsLHP: 76, grit: 80, stealing: 10, running: 34, throwing: 80, recovery: 72, wRISP: 76, vsLefty: 80, poise: 80, heater: 82, agile: 42,
      abilities: ["Ace", "Strong Starter", "Filthy Breaking Ball"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 7, 5, 0, 0, 0]) },
    { firstName: "Dylan", lastName: "Volantis", position: "P", eligibility: "SO", homeState: "TX", hometown: "Austin", jerseyNumber: 29,
      hitForAvg: 16, power: 12, speed: 42, arm: 88, fielding: 50, errorResistance: 52, velocity: 90, control: 78, stamina: 74, stuff: 88,
      clutch: 82, vsLHP: 78, grit: 84, stealing: 12, running: 38, throwing: 86, recovery: 68, wRISP: 80, vsLefty: 82, poise: 80, heater: 88, agile: 46,
      abilities: ["Ace", "Explosive Fastball", "Filthy Breaking Ball"], potential: "A+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 8, 6, 0, 0, 0]) },
    { firstName: "Jason", lastName: "Flores", position: "P", eligibility: "SO", homeState: "TX", hometown: "Dallas", jerseyNumber: 37,
      hitForAvg: 16, power: 12, speed: 40, arm: 78, fielding: 48, errorResistance: 50, velocity: 80, control: 74, stamina: 74, stuff: 78,
      clutch: 70, vsLHP: 68, grit: 72, stealing: 12, running: 36, throwing: 76, recovery: 66, wRISP: 68, vsLefty: 72, poise: 72, heater: 78, agile: 44,
      abilities: ["Strong Starter"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 5, 0, 0, 0]) },
    { firstName: "Thomas", lastName: "Burns", position: "P", eligibility: "JR", homeState: "TX", hometown: "Fort Worth", jerseyNumber: 38,
      hitForAvg: 16, power: 12, speed: 40, arm: 80, fielding: 48, errorResistance: 50, velocity: 82, control: 74, stamina: 66, stuff: 80,
      clutch: 78, vsLHP: 74, grit: 78, stealing: 10, running: 36, throwing: 78, recovery: 62, wRISP: 76, vsLefty: 78, poise: 78, heater: 80, agile: 44,
      abilities: ["Fireman", "Explosive Fastball", "Guts"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 6, 4, 0, 0, 0]) },
    { firstName: "Cole", lastName: "Hennings", position: "P", eligibility: "JR", homeState: "TX", hometown: "Katy", jerseyNumber: 40,
      hitForAvg: 16, power: 12, speed: 38, arm: 74, fielding: 46, errorResistance: 48, velocity: 76, control: 72, stamina: 72, stuff: 74,
      clutch: 66, vsLHP: 64, grit: 68, stealing: 10, running: 34, throwing: 72, recovery: 64, wRISP: 64, vsLefty: 68, poise: 68, heater: 74, agile: 42,
      abilities: ["Workhorse"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Brady", lastName: "Mitchell", position: "P", eligibility: "JR", homeState: "TX", hometown: "Midland", jerseyNumber: 42,
      hitForAvg: 14, power: 10, speed: 38, arm: 72, fielding: 44, errorResistance: 46, velocity: 74, control: 70, stamina: 70, stuff: 72,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 10, running: 34, throwing: 70, recovery: 62, wRISP: 62, vsLefty: 64, poise: 66, heater: 72, agile: 42,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 5, 0, 0, 0]) },
    { firstName: "Sam", lastName: "Cozart", position: "P", eligibility: "FR", homeState: "TX", hometown: "Round Rock", jerseyNumber: 46,
      hitForAvg: 12, power: 10, speed: 42, arm: 68, fielding: 40, errorResistance: 42, velocity: 70, control: 54, stamina: 52, stuff: 68,
      clutch: 48, vsLHP: 46, grit: 50, stealing: 14, running: 38, throwing: 66, recovery: 46, wRISP: 46, vsLefty: 50, poise: 48, heater: 68, agile: 46,
      abilities: [], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 3, 0, 0, 0]) },
    { firstName: "Max", lastName: "Grubbs", position: "P", eligibility: "FR", homeState: "TX", hometown: "Frisco", jerseyNumber: 48,
      hitForAvg: 12, power: 10, speed: 40, arm: 66, fielding: 38, errorResistance: 40, velocity: 68, control: 52, stamina: 50, stuff: 66,
      clutch: 46, vsLHP: 44, grit: 48, stealing: 12, running: 36, throwing: 64, recovery: 44, wRISP: 44, vsLefty: 48, poise: 46, heater: 66, agile: 44,
      abilities: [], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 3, 5, 3, 0, 0, 0]) },
    { firstName: "Trent", lastName: "Massey", position: "P", eligibility: "JR", homeState: "TX", hometown: "Arlington", jerseyNumber: 44,
      hitForAvg: 14, power: 10, speed: 38, arm: 72, fielding: 44, errorResistance: 46, velocity: 74, control: 70, stamina: 68, stuff: 72,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 10, running: 34, throwing: 70, recovery: 60, wRISP: 62, vsLefty: 64, poise: 66, heater: 72, agile: 42,
      abilities: [], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 4, 0, 0, 0]) },
    // CATCHERS (1)
    { firstName: "Carson", lastName: "Tinney", position: "C", eligibility: "JR", homeState: "IN", hometown: "South Bend", jerseyNumber: 19,
      hitForAvg: 74, power: 66, speed: 42, arm: 78, fielding: 76, errorResistance: 74, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 76, vsLHP: 72, grit: 78, stealing: 18, running: 40, throwing: 80, recovery: 60, wRISP: 76, vsLefty: 70, poise: 76, heater: 0, agile: 44,
      abilities: ["Iron Glove", "Clutch Hitter"], potential: "A", catcherAbility: 70,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Ethan", lastName: "Mendoza", position: "2B", eligibility: "SO", homeState: "TX", hometown: "El Paso", jerseyNumber: 2,
      hitForAvg: 76, power: 52, speed: 66, arm: 70, fielding: 74, errorResistance: 72, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 74, vsLHP: 70, grit: 74, stealing: 46, running: 64, throwing: 72, recovery: 58, wRISP: 74, vsLefty: 68, poise: 72, heater: 0, agile: 68,
      abilities: ["Contact Machine", "Table Setter"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Adrian", lastName: "Rodriguez", position: "SS", eligibility: "SO", homeState: "TX", hometown: "Laredo", jerseyNumber: 6,
      hitForAvg: 72, power: 58, speed: 72, arm: 74, fielding: 76, errorResistance: 74, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 72, vsLHP: 68, grit: 74, stealing: 56, running: 70, throwing: 76, recovery: 58, wRISP: 70, vsLefty: 66, poise: 72, heater: 0, agile: 74,
      abilities: ["Iron Glove", "Speed Demon"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Casey", lastName: "Borba", position: "1B", eligibility: "JR", homeState: "CA", hometown: "Sacramento", jerseyNumber: 14,
      hitForAvg: 68, power: 70, speed: 44, arm: 64, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 72, vsLHP: 68, grit: 72, stealing: 16, running: 42, throwing: 66, recovery: 56, wRISP: 72, vsLefty: 66, poise: 70, heater: 0, agile: 46,
      abilities: ["Power Surge", "Clutch Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Temo", lastName: "Becerra", position: "3B", eligibility: "JR", homeState: "CA", hometown: "San Jose", jerseyNumber: 10,
      hitForAvg: 70, power: 58, speed: 54, arm: 70, fielding: 68, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 68, vsLHP: 64, grit: 70, stealing: 30, running: 52, throwing: 72, recovery: 56, wRISP: 68, vsLefty: 62, poise: 68, heater: 0, agile: 56,
      abilities: ["Contact Machine"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Josh", lastName: "Livingston", position: "3B", eligibility: "JR", homeState: "KS", hometown: "Wichita", jerseyNumber: 20,
      hitForAvg: 66, power: 68, speed: 44, arm: 64, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 16, running: 42, throwing: 66, recovery: 54, wRISP: 70, vsLefty: 64, poise: 68, heater: 0, agile: 46,
      abilities: ["Power Surge"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Callum", lastName: "Early", position: "2B", eligibility: "FR", homeState: "TX", hometown: "Plano", jerseyNumber: 24,
      hitForAvg: 46, power: 36, speed: 58, arm: 58, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 42, grit: 46, stealing: 36, running: 56, throwing: 60, recovery: 40, wRISP: 42, vsLefty: 40, poise: 44, heater: 0, agile: 60,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (5)
    { firstName: "Aiden", lastName: "Robbins", position: "OF", eligibility: "JR", homeState: "NJ", hometown: "South Orange", jerseyNumber: 1,
      hitForAvg: 76, power: 72, speed: 66, arm: 74, fielding: 72, errorResistance: 70, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 78, vsLHP: 74, grit: 78, stealing: 46, running: 64, throwing: 76, recovery: 60, wRISP: 78, vsLefty: 72, poise: 76, heater: 0, agile: 68,
      abilities: ["Power Surge", "Clutch Hitter", "Cannon Arm"], potential: "A", catcherAbility: null,
      ...noPitches },
    { firstName: "Jonah", lastName: "Williams", position: "OF", eligibility: "SO", homeState: "TX", hometown: "Austin", jerseyNumber: 7,
      hitForAvg: 64, power: 54, speed: 74, arm: 66, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 66, stealing: 56, running: 72, throwing: 68, recovery: 52, wRISP: 58, vsLefty: 54, poise: 62, heater: 0, agile: 76,
      abilities: ["Speed Demon"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Ashton", lastName: "Larson", position: "OF", eligibility: "JR", homeState: "LA", hometown: "Baton Rouge", jerseyNumber: 9,
      hitForAvg: 66, power: 54, speed: 60, arm: 66, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 64, vsLHP: 60, grit: 66, stealing: 40, running: 58, throwing: 68, recovery: 52, wRISP: 64, vsLefty: 58, poise: 64, heater: 0, agile: 62,
      abilities: ["Contact Machine"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Dariyan", lastName: "Pendergrass", position: "OF", eligibility: "JR", homeState: "SC", hometown: "Charleston", jerseyNumber: 3,
      hitForAvg: 62, power: 44, speed: 82, arm: 64, fielding: 66, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 64, stealing: 72, running: 80, throwing: 66, recovery: 52, wRISP: 58, vsLefty: 54, poise: 62, heater: 0, agile: 82,
      abilities: ["Speed Demon"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Anthony", lastName: "Pack Jr", position: "OF", eligibility: "FR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 26,
      hitForAvg: 52, power: 48, speed: 70, arm: 62, fielding: 56, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 50, running: 68, throwing: 64, recovery: 44, wRISP: 48, vsLefty: 46, poise: 50, heater: 0, agile: 72,
      abilities: ["Speed Demon"], potential: "A+", catcherAbility: null,
      ...noPitches },
    { firstName: "Nate", lastName: "Crawford", position: "OF", eligibility: "FR", homeState: "TX", hometown: "San Antonio", jerseyNumber: 30,
      hitForAvg: 44, power: 38, speed: 60, arm: 58, fielding: 50, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 42, vsLHP: 40, grit: 44, stealing: 38, running: 58, throwing: 60, recovery: 38, wRISP: 40, vsLefty: 38, poise: 42, heater: 0, agile: 62,
      abilities: [], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Chase", lastName: "Porter", position: "C", eligibility: "SO", homeState: "TX", hometown: "Cypress", jerseyNumber: 16,
      hitForAvg: 56, power: 48, speed: 38, arm: 68, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 56, vsLHP: 52, grit: 58, stealing: 14, running: 36, throwing: 70, recovery: 48, wRISP: 54, vsLefty: 50, poise: 56, heater: 0, agile: 40,
      abilities: [], potential: "B+", catcherAbility: 62,
      ...noPitches },
    { firstName: "Miles", lastName: "Bennett", position: "OF", eligibility: "JR", homeState: "TX", hometown: "The Woodlands", jerseyNumber: 11,
      hitForAvg: 64, power: 56, speed: 62, arm: 68, fielding: 64, errorResistance: 62, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 62, vsLHP: 58, grit: 64, stealing: 42, running: 60, throwing: 70, recovery: 52, wRISP: 62, vsLefty: 56, poise: 62, heater: 0, agile: 64,
      abilities: ["Cannon Arm"], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],
};
