import type { RealPlayer } from "./realRosters";
import { pitchMix, noPitches } from "./pitchMixHelpers";

export const SEC_BATCH3_ROSTERS: Record<string, RealPlayer[]> = {
  "South Carolina": [
    // PITCHERS (10)
    { firstName: "Brandon", lastName: "Stone", position: "P", eligibility: "JR", homeState: "SC", hometown: "Columbia", jerseyNumber: 33,
      hitForAvg: 13, power: 10, speed: 32, arm: 59, fielding: 38, errorResistance: 40, velocity: 61, control: 57, stamina: 61, stuff: 59,
      clutch: 55, vsLHP: 51, grit: 57, stealing: 8, running: 29, throwing: 57, recovery: 53, wRISP: 53, vsLefty: 55, poise: 56, heater: 59, agile: 35,
      abilities: ["Strong Starter", "Guts", "Tunneling"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 4, 0, 0, 0]) },
    { firstName: "Amp", lastName: "Phillips", position: "P", eligibility: "JR", homeState: "SC", hometown: "Spartanburg", jerseyNumber: 21,
      hitForAvg: 13, power: 9, speed: 30, arm: 57, fielding: 37, errorResistance: 39, velocity: 59, control: 56, stamina: 57, stuff: 57,
      clutch: 53, vsLHP: 49, grit: 56, stealing: 8, running: 27, throwing: 56, recovery: 51, wRISP: 51, vsLefty: 53, poise: 54, heater: 57, agile: 33,
      abilities: ["Guts", "Strong Finisher"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Jake", lastName: "McCoy", position: "P", eligibility: "JR", homeState: "SC", hometown: "Greenville", jerseyNumber: 37,
      hitForAvg: 20, power: 15, speed: 50, arm: 88, fielding: 60, errorResistance: 62, velocity: 93, control: 88, stamina: 88, stuff: 89,
      clutch: 86, vsLHP: 82, grit: 88, stealing: 12, running: 45, throwing: 87, recovery: 82, wRISP: 82, vsLefty: 88, poise: 88, heater: 90, agile: 55,
      abilities: ["Strong Starter", "Sharpness", "Cross Cannon", "Lefty Killer", "Miracle Sharpness", "Houdini"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 5, 0, 0, 0]) },
    { firstName: "Josh", lastName: "Gunther", position: "P", eligibility: "JR", homeState: "GA", hometown: "Marietta", jerseyNumber: 45,
      hitForAvg: 10, power: 7, speed: 27, arm: 50, fielding: 32, errorResistance: 33, velocity: 51, control: 47, stamina: 44, stuff: 50,
      clutch: 42, vsLHP: 41, grit: 45, stealing: 7, running: 24, throwing: 48, recovery: 42, wRISP: 41, vsLefty: 44, poise: 44, heater: 50, agile: 30,
      abilities: ["Explosive Fastball"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 3, 0, 0, 0]) },
    { firstName: "Riley", lastName: "Goodman", position: "P", eligibility: "SO", homeState: "SC", hometown: "Charleston", jerseyNumber: 28,
      hitForAvg: 10, power: 7, speed: 29, arm: 50, fielding: 32, errorResistance: 34, velocity: 52, control: 47, stamina: 43, stuff: 50,
      clutch: 41, vsLHP: 40, grit: 46, stealing: 7, running: 26, throwing: 49, recovery: 38, wRISP: 40, vsLefty: 43, poise: 43, heater: 50, agile: 32,
      abilities: ["Natural Shuuto"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 3, 0, 0, 0]) },
    { firstName: "Marcus", lastName: "Hall", position: "P", eligibility: "JR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 41,
      hitForAvg: 13, power: 9, speed: 38, arm: 65, fielding: 42, errorResistance: 44, velocity: 66, control: 63, stamina: 61, stuff: 65,
      clutch: 57, vsLHP: 55, grit: 61, stealing: 9, running: 35, throwing: 63, recovery: 57, wRISP: 55, vsLefty: 60, poise: 60, heater: 65, agile: 42,
      abilities: ["Cross Cannon", "Decisive", "Crossfire", "Houdini"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 4, 0, 0, 0]) },
    { firstName: "Zach", lastName: "Swanson", position: "P", eligibility: "SO", homeState: "SC", hometown: "Rock Hill", jerseyNumber: 39,
      hitForAvg: 10, power: 7, speed: 27, arm: 47, fielding: 30, errorResistance: 31, velocity: 48, control: 45, stamina: 44, stuff: 47,
      clutch: 40, vsLHP: 38, grit: 43, stealing: 7, running: 24, throwing: 45, recovery: 40, wRISP: 38, vsLefty: 42, poise: 42, heater: 47, agile: 30,
      abilities: ["Indomitable Soul", "Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 5, 0, 0, 0]) },
    { firstName: "Dylan", lastName: "Reeves", position: "P", eligibility: "JR", homeState: "GA", hometown: "Savannah", jerseyNumber: 47,
      hitForAvg: 13, power: 10, speed: 35, arm: 63, fielding: 40, errorResistance: 43, velocity: 65, control: 61, stamina: 60, stuff: 63,
      clutch: 56, vsLHP: 53, grit: 58, stealing: 10, running: 32, throwing: 61, recovery: 53, wRISP: 53, vsLefty: 58, poise: 58, heater: 63, agile: 39,
      abilities: ["Fireman", "Quick Hands", "Strong Starter", "Groundball Pitcher"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 3, 4, 0, 0, 0]) },
    { firstName: "Trevor", lastName: "Mack", position: "P", eligibility: "JR", homeState: "FL", hometown: "Jacksonville", jerseyNumber: 43,
      hitForAvg: 8, power: 7, speed: 25, arm: 41, fielding: 27, errorResistance: 29, velocity: 42, control: 40, stamina: 38, stuff: 41,
      clutch: 36, vsLHP: 34, grit: 37, stealing: 7, running: 22, throwing: 40, recovery: 34, wRISP: 34, vsLefty: 37, poise: 37, heater: 41, agile: 27,
      abilities: ["Guts"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Cole", lastName: "Jenkins", position: "P", eligibility: "JR", homeState: "SC", hometown: "Lexington", jerseyNumber: 49,
      hitForAvg: 9, power: 7, speed: 25, arm: 44, fielding: 28, errorResistance: 29, velocity: 46, control: 43, stamina: 40, stuff: 44,
      clutch: 37, vsLHP: 36, grit: 38, stealing: 7, running: 22, throwing: 43, recovery: 36, wRISP: 36, vsLefty: 38, poise: 38, heater: 44, agile: 28,
      abilities: ["Low Ball", "True Slider"], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 3, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Talmadge", lastName: "LeCroy", position: "C", eligibility: "SR", homeState: "SC", hometown: "Easley", jerseyNumber: 18,
      hitForAvg: 47, power: 43, speed: 30, arm: 56, fielding: 54, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 47, grit: 56, stealing: 11, running: 27, throwing: 57, recovery: 44, wRISP: 49, vsLefty: 46, poise: 54, heater: 0, agile: 33,
      abilities: ["Contact Hitter"], potential: "B", catcherAbility: 54,
      ...noPitches },
    { firstName: "Jake", lastName: "Randolph", position: "C", eligibility: "FR", homeState: "SC", hometown: "Irmo", jerseyNumber: 24,
      hitForAvg: 38, power: 32, speed: 34, arm: 56, fielding: 48, errorResistance: 43, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 36, vsLHP: 34, grit: 38, stealing: 13, running: 32, throwing: 57, recovery: 34, wRISP: 34, vsLefty: 32, poise: 36, heater: 0, agile: 36,
      abilities: ["Bases Loaded Slugger", "Emotional Pillar", "Trickster"], potential: "B+", catcherAbility: 55,
      ...noPitches },
    // INFIELDERS (5)
    { firstName: "KJ", lastName: "Scobey", position: "SS", eligibility: "SO", homeState: "GA", hometown: "Woodstock", jerseyNumber: 2,
      hitForAvg: 44, power: 42, speed: 45, arm: 52, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 42, grit: 48, stealing: 30, running: 44, throwing: 53, recovery: 38, wRISP: 48, vsLefty: 41, poise: 47, heater: 0, agile: 47,
      abilities: ["Consigliere"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Beau", lastName: "Hollins", position: "1B", eligibility: "SO", homeState: "SC", hometown: "Bluffton", jerseyNumber: 14,
      hitForAvg: 63, power: 54, speed: 40, arm: 57, fielding: 59, errorResistance: 57, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 59, vsLHP: 55, grit: 61, stealing: 15, running: 38, throwing: 59, recovery: 48, wRISP: 59, vsLefty: 54, poise: 57, heater: 0, agile: 41,
      abilities: ["Contact Hitter"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Logan", lastName: "Sutter", position: "2B", eligibility: "SR", homeState: "IN", hometown: "Fishers", jerseyNumber: 6,
      hitForAvg: 50, power: 38, speed: 38, arm: 45, fielding: 47, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 46, vsLHP: 45, grit: 47, stealing: 24, running: 36, throwing: 46, recovery: 39, wRISP: 46, vsLefty: 43, poise: 46, heater: 0, agile: 39,
      abilities: ["Contact Hitter", "Chance Maker"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Dawson", lastName: "Harman", position: "3B", eligibility: "JR", homeState: "FL", hometown: "Ocala", jerseyNumber: 10,
      hitForAvg: 53, power: 48, speed: 41, arm: 54, fielding: 51, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 51, vsLHP: 48, grit: 54, stealing: 22, running: 39, throwing: 57, recovery: 42, wRISP: 51, vsLefty: 47, poise: 51, heater: 0, agile: 42,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Will", lastName: "Craddock", position: "2B", eligibility: "FR", homeState: "SC", hometown: "Summerville", jerseyNumber: 16,
      hitForAvg: 36, power: 27, speed: 48, arm: 48, fielding: 43, errorResistance: 39, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 34, vsLHP: 32, grit: 36, stealing: 29, running: 47, throwing: 51, recovery: 32, wRISP: 32, vsLefty: 31, poise: 34, heater: 0, agile: 51,
      abilities: ["Emergency Strength"], potential: "B+", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Tyler", lastName: "Bak", position: "OF", eligibility: "JR", homeState: "SC", hometown: "Spartanburg", jerseyNumber: 1,
      hitForAvg: 48, power: 36, speed: 50, arm: 48, fielding: 48, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 43, grit: 47, stealing: 36, running: 48, throwing: 50, recovery: 38, wRISP: 43, vsLefty: 41, poise: 44, heater: 0, agile: 52,
      abilities: ["Express Baserunning"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Patrick", lastName: "Evans", position: "OF", eligibility: "JR", homeState: "SC", hometown: "Florence", jerseyNumber: 8,
      hitForAvg: 50, power: 45, speed: 39, arm: 47, fielding: 42, errorResistance: 41, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 45, grit: 50, stealing: 21, running: 37, throwing: 49, recovery: 39, wRISP: 49, vsLefty: 44, poise: 47, heater: 0, agile: 40,
      abilities: ["Power Hitter", "Consigliere"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Ethan", lastName: "Lizama", position: "OF", eligibility: "SR", homeState: "CA", hometown: "San Diego", jerseyNumber: 3,
      hitForAvg: 60, power: 59, speed: 46, arm: 60, fielding: 55, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 59, vsLHP: 55, grit: 60, stealing: 24, running: 45, throwing: 62, recovery: 48, wRISP: 59, vsLefty: 54, poise: 59, heater: 0, agile: 48,
      abilities: ["Power Hitter", "High-Speed Laser"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Reese", lastName: "Moore", position: "OF", eligibility: "JR", homeState: "IA", hometown: "Iowa City", jerseyNumber: 12,
      hitForAvg: 53, power: 50, speed: 40, arm: 50, fielding: 46, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 50, grit: 55, stealing: 17, running: 38, throwing: 52, recovery: 43, wRISP: 53, vsLefty: 48, poise: 52, heater: 0, agile: 41,
      abilities: ["Consigliere"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Aaron", lastName: "Jamison", position: "OF", eligibility: "FR", homeState: "GA", hometown: "Atlanta", jerseyNumber: 22,
      hitForAvg: 28, power: 24, speed: 41, arm: 39, fielding: 33, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 27, vsLHP: 25, grit: 28, stealing: 25, running: 39, throwing: 41, recovery: 25, wRISP: 25, vsLefty: 24, poise: 27, heater: 0, agile: 42,
      abilities: ["Spirit Head", "Lightning Speed"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Caleb", lastName: "Hoover", position: "OF", eligibility: "FR", homeState: "NC", hometown: "Raleigh", jerseyNumber: 26,
      hitForAvg: 28, power: 24, speed: 42, arm: 40, fielding: 33, errorResistance: 31, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 27, vsLHP: 26, grit: 28, stealing: 26, running: 40, throwing: 42, recovery: 26, wRISP: 26, vsLefty: 24, poise: 27, heater: 0, agile: 44,
      abilities: ["Locked and Loaded", "Error Prone"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Erik", lastName: "Parker", position: "SS", eligibility: "FR", homeState: "SC", hometown: "Greer", jerseyNumber: 30,
      hitForAvg: 34, power: 27, speed: 46, arm: 46, fielding: 41, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 31, vsLHP: 30, grit: 34, stealing: 28, running: 45, throwing: 48, recovery: 30, wRISP: 30, vsLefty: 28, poise: 31, heater: 0, agile: 48,
      abilities: ["Puller Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Bryce", lastName: "Watkins", position: "OF", eligibility: "JR", homeState: "NC", hometown: "Wilmington", jerseyNumber: 32,
      hitForAvg: 48, power: 40, speed: 47, arm: 51, fielding: 48, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 43, grit: 48, stealing: 28, running: 45, throwing: 53, recovery: 40, wRISP: 45, vsLefty: 42, poise: 47, heater: 0, agile: 48,
      abilities: ["Emotional Pillar", "Locked and Loaded", "Home Defense"], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "Kentucky": [
    // PITCHERS (10)
    { firstName: "Jaxon", lastName: "Jelkin", position: "P", eligibility: "SR", homeState: "TX", hometown: "Houston", jerseyNumber: 34,
      hitForAvg: 19, power: 15, speed: 43, arm: 86, fielding: 54, errorResistance: 56, velocity: 91, control: 78, stamina: 76, stuff: 88,
      clutch: 76, vsLHP: 72, grit: 78, stealing: 11, running: 39, throwing: 84, recovery: 69, wRISP: 74, vsLefty: 76, poise: 78, heater: 88, agile: 47,
      abilities: ["Strong Starter", "Guts", "Bad Ball Hitter", "Release"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 5, 0, 0, 0]) },
    { firstName: "Ben", lastName: "Cleaver", position: "P", eligibility: "JR", homeState: "KY", hometown: "Louisville", jerseyNumber: 22,
      hitForAvg: 13, power: 10, speed: 31, arm: 61, fielding: 39, errorResistance: 40, velocity: 63, control: 61, stamina: 61, stuff: 61,
      clutch: 56, vsLHP: 55, grit: 58, stealing: 8, running: 27, throwing: 59, recovery: 55, wRISP: 55, vsLefty: 58, poise: 58, heater: 61, agile: 33,
      abilities: ["Strong Starter", "Guts", "Fighting Spirit"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 6, 5, 0, 0, 0]) },
    { firstName: "Nate", lastName: "Harris", position: "P", eligibility: "SO", homeState: "KY", hometown: "Lexington", jerseyNumber: 29,
      hitForAvg: 13, power: 10, speed: 35, arm: 64, fielding: 41, errorResistance: 43, velocity: 66, control: 62, stamina: 64, stuff: 64,
      clutch: 57, vsLHP: 56, grit: 59, stealing: 10, running: 31, throwing: 62, recovery: 56, wRISP: 56, vsLefty: 59, poise: 59, heater: 64, agile: 38,
      abilities: ["Strong Starter", "Winner's Luck", "Quick Hands"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 6, 5, 4, 0, 0, 0]) },
    { firstName: "Tommy", lastName: "Skelding", position: "P", eligibility: "SO", homeState: "OH", hometown: "Cincinnati", jerseyNumber: 37,
      hitForAvg: 10, power: 7, speed: 28, arm: 50, fielding: 34, errorResistance: 35, velocity: 52, control: 49, stamina: 49, stuff: 50,
      clutch: 43, vsLHP: 42, grit: 46, stealing: 7, running: 25, throwing: 49, recovery: 43, wRISP: 42, vsLefty: 45, poise: 45, heater: 50, agile: 31,
      abilities: ["Fireman"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    { firstName: "Nile", lastName: "Adcock", position: "P", eligibility: "SR", homeState: "KY", hometown: "Bowling Green", jerseyNumber: 38,
      hitForAvg: 13, power: 10, speed: 31, arm: 59, fielding: 39, errorResistance: 41, velocity: 61, control: 59, stamina: 57, stuff: 59,
      clutch: 54, vsLHP: 51, grit: 56, stealing: 8, running: 28, throwing: 57, recovery: 53, wRISP: 53, vsLefty: 54, poise: 56, heater: 59, agile: 34,
      abilities: ["Fireman", "Crossfire"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Chase", lastName: "Alderman", position: "P", eligibility: "JR", homeState: "KY", hometown: "Paducah", jerseyNumber: 42,
      hitForAvg: 10, power: 8, speed: 26, arm: 46, fielding: 29, errorResistance: 30, velocity: 48, control: 45, stamina: 45, stuff: 46,
      clutch: 41, vsLHP: 38, grit: 42, stealing: 8, running: 23, throwing: 45, recovery: 40, wRISP: 40, vsLefty: 41, poise: 42, heater: 46, agile: 28,
      abilities: ["Sharpness"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 6, 5, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Hagenow", position: "P", eligibility: "JR", homeState: "IN", hometown: "Evansville", jerseyNumber: 40,
      hitForAvg: 9, power: 6, speed: 23, arm: 41, fielding: 27, errorResistance: 28, velocity: 43, control: 40, stamina: 40, stuff: 41,
      clutch: 36, vsLHP: 35, grit: 39, stealing: 6, running: 20, throwing: 40, recovery: 35, wRISP: 35, vsLefty: 37, poise: 37, heater: 41, agile: 26,
      abilities: ["Slugger Killer", "Groundball Pitcher"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Mason", lastName: "Wright", position: "P", eligibility: "SO", homeState: "KY", hometown: "Florence", jerseyNumber: 44,
      hitForAvg: 10, power: 8, speed: 30, arm: 49, fielding: 31, errorResistance: 32, velocity: 50, control: 48, stamina: 48, stuff: 49,
      clutch: 41, vsLHP: 40, grit: 44, stealing: 9, running: 27, throwing: 48, recovery: 41, wRISP: 40, vsLefty: 43, poise: 43, heater: 49, agile: 32,
      abilities: ["Precision Instrument"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 5, 0, 0, 0]) },
    { firstName: "Brady", lastName: "Kirtley", position: "P", eligibility: "FR", homeState: "KY", hometown: "Owensboro", jerseyNumber: 46,
      hitForAvg: 10, power: 8, speed: 35, arm: 53, fielding: 32, errorResistance: 33, velocity: 55, control: 44, stamina: 42, stuff: 53,
      clutch: 37, vsLHP: 35, grit: 39, stealing: 11, running: 32, throwing: 52, recovery: 37, wRISP: 35, vsLefty: 39, poise: 37, heater: 53, agile: 39,
      abilities: ["Pace"], potential: "A", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 4, 0, 0, 0]) },
    { firstName: "Gavin", lastName: "Porter", position: "P", eligibility: "FR", homeState: "TN", hometown: "Nashville", jerseyNumber: 48,
      hitForAvg: 11, power: 9, speed: 36, arm: 55, fielding: 33, errorResistance: 34, velocity: 58, control: 45, stamina: 43, stuff: 55,
      clutch: 38, vsLHP: 36, grit: 40, stealing: 11, running: 33, throwing: 54, recovery: 38, wRISP: 36, vsLefty: 40, poise: 38, heater: 55, agile: 40,
      abilities: ["Kageura", "Strength Distribution", "Phantasmagoric"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    // CATCHERS (2)
    { firstName: "Devin", lastName: "Burkes", position: "C", eligibility: "JR", homeState: "KY", hometown: "Covington", jerseyNumber: 19,
      hitForAvg: 46, power: 42, speed: 30, arm: 54, fielding: 53, errorResistance: 51, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 45, grit: 49, stealing: 13, running: 29, throwing: 55, recovery: 41, wRISP: 46, vsLefty: 44, poise: 48, heater: 0, agile: 33,
      abilities: ["Defensive Artisan"], potential: "B+", catcherAbility: 49,
      ...noPitches },
    { firstName: "Colin", lastName: "Slater", position: "C", eligibility: "FR", homeState: "OH", hometown: "Columbus", jerseyNumber: 25,
      hitForAvg: 29, power: 24, speed: 26, arm: 41, fielding: 35, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 27, vsLHP: 26, grit: 29, stealing: 10, running: 24, throwing: 43, recovery: 26, wRISP: 26, vsLefty: 24, poise: 27, heater: 0, agile: 27,
      abilities: ["Milliner"], potential: "B+", catcherAbility: 40,
      ...noPitches },
    // INFIELDERS (5)
    { firstName: "Tyler", lastName: "Bell", position: "SS", eligibility: "SO", homeState: "KY", hometown: "Lexington", jerseyNumber: 6,
      hitForAvg: 74, power: 66, speed: 68, arm: 74, fielding: 76, errorResistance: 74, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 75, vsLHP: 75, grit: 75, stealing: 58, running: 62, throwing: 75, recovery: 62, wRISP: 75, vsLefty: 73, poise: 75, heater: 0, agile: 70,
      abilities: ["Artist", "Hit Machine", "Magician"], potential: "A+", catcherAbility: null,
      ...noPitches },
    { firstName: "Luke", lastName: "Lawrence", position: "2B", eligibility: "SR", homeState: "KY", hometown: "Lexington", jerseyNumber: 6,
      hitForAvg: 50, power: 39, speed: 44, arm: 50, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 45, grit: 52, stealing: 28, running: 42, throwing: 52, recovery: 42, wRISP: 47, vsLefty: 44, poise: 50, heater: 0, agile: 45,
      abilities: ["Chance Maker"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Hudson", lastName: "Brown", position: "1B", eligibility: "JR", homeState: "KY", hometown: "Louisville", jerseyNumber: 8,
      hitForAvg: 51, power: 49, speed: 34, arm: 48, fielding: 49, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 51, vsLHP: 48, grit: 52, stealing: 12, running: 33, throwing: 49, recovery: 41, wRISP: 51, vsLefty: 47, poise: 51, heater: 0, agile: 36,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Ethan", lastName: "Hindle", position: "3B", eligibility: "JR", homeState: "OH", hometown: "Dayton", jerseyNumber: 10,
      hitForAvg: 56, power: 48, speed: 46, arm: 61, fielding: 60, errorResistance: 57, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 57, stealing: 24, running: 44, throwing: 63, recovery: 46, wRISP: 51, vsLefty: 48, poise: 54, heater: 0, agile: 48,
      abilities: ["Magician", "Ace Killer", "Shock Commander"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Jake", lastName: "Newell", position: "SS", eligibility: "FR", homeState: "KY", hometown: "Richmond", jerseyNumber: 24,
      hitForAvg: 32, power: 24, speed: 41, arm: 41, fielding: 37, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 29, vsLHP: 28, grit: 32, stealing: 26, running: 40, throwing: 43, recovery: 27, wRISP: 28, vsLefty: 27, poise: 29, heater: 0, agile: 43,
      abilities: ["Two-Strike Hitter", "Push", "First Pitch King"], potential: "A-", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (6)
    { firstName: "Ryan", lastName: "Schwartz", position: "OF", eligibility: "SO", homeState: "KY", hometown: "Lexington", jerseyNumber: 1,
      hitForAvg: 51, power: 45, speed: 49, arm: 52, fielding: 51, errorResistance: 49, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 49, vsLHP: 46, grit: 51, stealing: 34, running: 48, throwing: 54, recovery: 42, wRISP: 48, vsLefty: 45, poise: 49, heater: 0, agile: 51,
      abilities: ["Express Baserunning"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Carson", lastName: "Hansen", position: "OF", eligibility: "SR", homeState: "OH", hometown: "Toledo", jerseyNumber: 9,
      hitForAvg: 56, power: 52, speed: 42, arm: 55, fielding: 51, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 57, vsLHP: 55, grit: 60, stealing: 17, running: 40, throwing: 56, recovery: 47, wRISP: 57, vsLefty: 52, poise: 57, heater: 0, agile: 44,
      abilities: ["Consigliere"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Will", lastName: "Marcy", position: "OF", eligibility: "JR", homeState: "KY", hometown: "Frankfort", jerseyNumber: 7,
      hitForAvg: 46, power: 40, speed: 45, arm: 49, fielding: 48, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 45, vsLHP: 42, grit: 46, stealing: 30, running: 43, throwing: 51, recovery: 38, wRISP: 43, vsLefty: 40, poise: 45, heater: 0, agile: 46,
      abilities: ["High-Speed Laser"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Bryce", lastName: "Hamilton", position: "OF", eligibility: "FR", homeState: "TN", hometown: "Knoxville", jerseyNumber: 26,
      hitForAvg: 31, power: 26, speed: 43, arm: 41, fielding: 35, errorResistance: 33, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 29, vsLHP: 28, grit: 31, stealing: 26, running: 41, throwing: 43, recovery: 28, wRISP: 28, vsLefty: 26, poise: 29, heater: 0, agile: 44,
      abilities: ["Ace Killer"], potential: "A-", catcherAbility: null,
      ...noPitches },
    { firstName: "Drew", lastName: "Foster", position: "OF", eligibility: "JR", homeState: "KY", hometown: "Ashland", jerseyNumber: 11,
      hitForAvg: 44, power: 38, speed: 41, arm: 48, fielding: 44, errorResistance: 43, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 43, vsLHP: 40, grit: 44, stealing: 25, running: 40, throwing: 49, recovery: 37, wRISP: 41, vsLefty: 38, poise: 43, heater: 0, agile: 43,
      abilities: ["Trickster", "Heat Up"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Cole", lastName: "Daniels", position: "3B", eligibility: "SO", homeState: "KY", hometown: "Elizabethtown", jerseyNumber: 14,
      hitForAvg: 42, power: 36, speed: 34, arm: 45, fielding: 43, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 39, vsLHP: 37, grit: 42, stealing: 16, running: 32, throwing: 47, recovery: 34, wRISP: 38, vsLefty: 36, poise: 39, heater: 0, agile: 36,
      abilities: ["Contact Hitter", "Outside Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Tanner", lastName: "Mills", position: "OF", eligibility: "JR", homeState: "OH", hometown: "Akron", jerseyNumber: 3,
      hitForAvg: 54, power: 49, speed: 52, arm: 60, fielding: 55, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 49, grit: 54, stealing: 33, running: 50, throwing: 61, recovery: 44, wRISP: 50, vsLefty: 47, poise: 52, heater: 0, agile: 54,
      abilities: ["Resilient", "Timely Whiff"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Aidan", lastName: "Cooper", position: "1B", eligibility: "SO", homeState: "KY", hometown: "Hopkinsville", jerseyNumber: 20,
      hitForAvg: 37, power: 36, speed: 26, arm: 38, fielding: 38, errorResistance: 37, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 36, vsLHP: 33, grit: 37, stealing: 9, running: 25, throwing: 40, recovery: 30, wRISP: 36, vsLefty: 32, poise: 36, heater: 0, agile: 28,
      abilities: ["Timely Whiff"], potential: "B+", catcherAbility: null,
      ...noPitches },
  ],

  "Missouri": [
    // PITCHERS (10)
    { firstName: "Javyn", lastName: "Pimental", position: "P", eligibility: "SR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 33,
      hitForAvg: 18, power: 13, speed: 44, arm: 86, fielding: 55, errorResistance: 57, velocity: 91, control: 85, stamina: 84, stuff: 88,
      clutch: 73, vsLHP: 72, grit: 78, stealing: 11, running: 39, throwing: 84, recovery: 72, wRISP: 72, vsLefty: 75, poise: 75, heater: 88, agile: 49,
      abilities: ["Guts", "Guts", "Indomitable Soul", "Good Pickoff", "Big Boy Speed", "Grit"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 5, 6, 4, 0, 0, 0]) },
    { firstName: "Josh", lastName: "McDevitt", position: "P", eligibility: "JR", homeState: "MO", hometown: "St. Louis", jerseyNumber: 22,
      hitForAvg: 12, power: 9, speed: 36, arm: 60, fielding: 41, errorResistance: 42, velocity: 62, control: 59, stamina: 60, stuff: 60,
      clutch: 51, vsLHP: 50, grit: 55, stealing: 9, running: 32, throwing: 59, recovery: 51, wRISP: 50, vsLefty: 53, poise: 53, heater: 60, agile: 39,
      abilities: ["Strong Starter", "Low Ball"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
    { firstName: "Brady", lastName: "Kehlenbrink", position: "P", eligibility: "SO", homeState: "MO", hometown: "Kansas City", jerseyNumber: 37,
      hitForAvg: 14, power: 9, speed: 39, arm: 65, fielding: 43, errorResistance: 45, velocity: 67, control: 63, stamina: 63, stuff: 65,
      clutch: 55, vsLHP: 53, grit: 59, stealing: 12, running: 35, throwing: 63, recovery: 55, wRISP: 53, vsLefty: 57, poise: 57, heater: 65, agile: 43,
      abilities: ["Miracle Sharpness", "Kageura", "Monster Stuff"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Tyler", lastName: "Stokes", position: "P", eligibility: "JR", homeState: "MO", hometown: "Springfield", jerseyNumber: 29,
      hitForAvg: 14, power: 10, speed: 37, arm: 64, fielding: 44, errorResistance: 45, velocity: 66, control: 64, stamina: 64, stuff: 64,
      clutch: 57, vsLHP: 55, grit: 59, stealing: 10, running: 34, throwing: 63, recovery: 55, wRISP: 55, vsLefty: 59, poise: 59, heater: 64, agile: 41,
      abilities: ["Fireman", "Wild Fastball", "Explosive Fastball"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 5, 4, 3, 0, 0, 0]) },
    { firstName: "Noah", lastName: "Mitchell", position: "P", eligibility: "JR", homeState: "IL", hometown: "Edwardsville", jerseyNumber: 38,
      hitForAvg: 9, power: 7, speed: 26, arm: 44, fielding: 29, errorResistance: 30, velocity: 45, control: 44, stamina: 44, stuff: 44,
      clutch: 39, vsLHP: 38, grit: 41, stealing: 7, running: 24, throwing: 43, recovery: 38, wRISP: 38, vsLefty: 41, poise: 41, heater: 44, agile: 29,
      abilities: ["Walk"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 5, 4, 0, 0, 0]) },
    { firstName: "Drew", lastName: "Walters", position: "P", eligibility: "SR", homeState: "MO", hometown: "Columbia", jerseyNumber: 40,
      hitForAvg: 13, power: 9, speed: 32, arm: 56, fielding: 39, errorResistance: 40, velocity: 58, control: 58, stamina: 56, stuff: 56,
      clutch: 51, vsLHP: 49, grit: 53, stealing: 9, running: 29, throwing: 54, recovery: 49, wRISP: 49, vsLefty: 53, poise: 53, heater: 56, agile: 36,
      abilities: ["Constant Speed", "Escape Pitch", "Decisive"], potential: "B-", catcherAbility: null,
      ...pitchMix(1, [0, 4, 4, 4, 0, 0, 0]) },
    { firstName: "Ryan", lastName: "Kraft", position: "P", eligibility: "JR", homeState: "KS", hometown: "Overland Park", jerseyNumber: 42,
      hitForAvg: 10, power: 7, speed: 30, arm: 48, fielding: 31, errorResistance: 33, velocity: 50, control: 47, stamina: 47, stuff: 48,
      clutch: 41, vsLHP: 39, grit: 44, stealing: 7, running: 27, throwing: 47, recovery: 39, wRISP: 39, vsLefty: 43, poise: 43, heater: 48, agile: 33,
      abilities: ["Slugger Killer"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 4, 3, 5, 0, 0, 0]) },
    { firstName: "Cade", lastName: "Reynolds", position: "P", eligibility: "SO", homeState: "MO", hometown: "Lee's Summit", jerseyNumber: 44,
      hitForAvg: 10, power: 8, speed: 29, arm: 47, fielding: 31, errorResistance: 31, velocity: 49, control: 46, stamina: 46, stuff: 47,
      clutch: 39, vsLHP: 38, grit: 43, stealing: 8, running: 26, throwing: 46, recovery: 38, wRISP: 38, vsLefty: 41, poise: 41, heater: 47, agile: 31,
      abilities: ["Intimidator", "Cross Cannon", "Top Gear"], potential: "B", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 4, 0, 0, 0]) },
    { firstName: "Landon", lastName: "Price", position: "P", eligibility: "FR", homeState: "MO", hometown: "Jefferson City", jerseyNumber: 46,
      hitForAvg: 9, power: 8, speed: 33, arm: 47, fielding: 28, errorResistance: 30, velocity: 50, control: 38, stamina: 36, stuff: 47,
      clutch: 32, vsLHP: 30, grit: 33, stealing: 11, running: 30, throwing: 46, recovery: 32, wRISP: 30, vsLefty: 33, poise: 32, heater: 47, agile: 36,
      abilities: ["Gas Tank"], potential: "A-", catcherAbility: null,
      ...pitchMix(1, [0, 3, 4, 3, 0, 0, 0]) },
    { firstName: "Jake", lastName: "Donaldson", position: "P", eligibility: "FR", homeState: "IL", hometown: "O'Fallon", jerseyNumber: 48,
      hitForAvg: 9, power: 8, speed: 30, arm: 45, fielding: 26, errorResistance: 28, velocity: 46, control: 35, stamina: 34, stuff: 43,
      clutch: 30, vsLHP: 28, grit: 30, stealing: 9, running: 28, throwing: 43, recovery: 30, wRISP: 28, vsLefty: 30, poise: 30, heater: 45, agile: 34,
      abilities: ["Glass Heart"], potential: "B+", catcherAbility: null,
      ...pitchMix(1, [0, 3, 3, 4, 0, 0, 0]) },
    // CATCHERS (1)
    { firstName: "Mateo", lastName: "Serna", position: "C", eligibility: "JR", homeState: "TX", hometown: "San Antonio", jerseyNumber: 14,
      hitForAvg: 53, power: 54, speed: 36, arm: 64, fielding: 59, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 50, grit: 58, stealing: 13, running: 34, throwing: 65, recovery: 47, wRISP: 53, vsLefty: 48, poise: 54, heater: 0, agile: 39,
      abilities: ["Outside Hitter", "Legendary Walkoff Hitter"], potential: "B+", catcherAbility: 58,
      ...noPitches },
    // INFIELDERS (6)
    { firstName: "Chris", lastName: "Patterson", position: "3B", eligibility: "JR", homeState: "MO", hometown: "Blue Springs", jerseyNumber: 5,
      hitForAvg: 53, power: 49, speed: 48, arm: 63, fielding: 59, errorResistance: 58, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 53, vsLHP: 49, grit: 55, stealing: 22, running: 45, throwing: 65, recovery: 45, wRISP: 52, vsLefty: 48, poise: 53, heater: 0, agile: 49,
      abilities: ["Defensive Artisan", "Good Bunt"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Kam", lastName: "Durnin", position: "SS", eligibility: "JR", homeState: "NE", hometown: "Omaha", jerseyNumber: 2,
      hitForAvg: 42, power: 33, speed: 44, arm: 51, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 40, vsLHP: 38, grit: 44, stealing: 28, running: 42, throwing: 52, recovery: 36, wRISP: 39, vsLefty: 36, poise: 42, heater: 0, agile: 45,
      abilities: ["Defensive Artisan"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Jalen", lastName: "Woita", position: "2B", eligibility: "JR", homeState: "SC", hometown: "Columbia", jerseyNumber: 10,
      hitForAvg: 47, power: 41, speed: 39, arm: 47, fielding: 45, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 45, vsLHP: 43, grit: 47, stealing: 21, running: 37, throwing: 49, recovery: 37, wRISP: 45, vsLefty: 41, poise: 45, heater: 0, agile: 41,
      abilities: ["Contact Hitter"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Peyton", lastName: "Basler", position: "1B", eligibility: "SR", homeState: "MO", hometown: "St. Charles", jerseyNumber: 18,
      hitForAvg: 48, power: 43, speed: 33, arm: 49, fielding: 49, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 48, vsLHP: 43, grit: 51, stealing: 12, running: 32, throwing: 51, recovery: 40, wRISP: 45, vsLefty: 42, poise: 49, heater: 0, agile: 35,
      abilities: ["Insurer", "Artist", "High-Speed Laser"], potential: "B-", catcherAbility: null,
      ...noPitches },
    { firstName: "Gehrig", lastName: "Goldbeck", position: "3B", eligibility: "SR", homeState: "MO", hometown: "St. Louis", jerseyNumber: 16,
      hitForAvg: 52, power: 46, speed: 42, arm: 59, fielding: 57, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 52, vsLHP: 47, grit: 56, stealing: 17, running: 40, throwing: 61, recovery: 43, wRISP: 49, vsLefty: 46, poise: 53, heater: 0, agile: 43,
      abilities: ["Walkoff Hitter"], potential: "B-", catcherAbility: null,
      ...noPitches },
    { firstName: "Keegan", lastName: "Knutson", position: "2B", eligibility: "SR", homeState: "IA", hometown: "Des Moines", jerseyNumber: 20,
      hitForAvg: 38, power: 33, speed: 35, arm: 43, fielding: 43, errorResistance: 40, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 38, vsLHP: 35, grit: 40, stealing: 18, running: 34, throwing: 44, recovery: 33, wRISP: 36, vsLefty: 34, poise: 39, heater: 0, agile: 36,
      abilities: ["Disturbance", "Heat Up"], potential: "B-", catcherAbility: null,
      ...noPitches },
    // OUTFIELDERS (5)
    { firstName: "Kaden", lastName: "Peer", position: "OF", eligibility: "JR", homeState: "MO", hometown: "Joplin", jerseyNumber: 1,
      hitForAvg: 48, power: 40, speed: 45, arm: 51, fielding: 48, errorResistance: 47, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 47, vsLHP: 44, grit: 48, stealing: 30, running: 44, throwing: 52, recovery: 40, wRISP: 47, vsLefty: 42, poise: 47, heater: 0, agile: 47,
      abilities: ["Chance Maker"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Pierre", lastName: "Seals", position: "OF", eligibility: "SR", homeState: "MO", hometown: "Kansas City", jerseyNumber: 7,
      hitForAvg: 50, power: 47, speed: 47, arm: 55, fielding: 52, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 50, vsLHP: 47, grit: 52, stealing: 28, running: 45, throwing: 58, recovery: 42, wRISP: 49, vsLefty: 45, poise: 50, heater: 0, agile: 49,
      abilities: ["High-Speed Laser"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Cameron", lastName: "Benson", position: "OF", eligibility: "JR", homeState: "MO", hometown: "Independence", jerseyNumber: 3,
      hitForAvg: 57, power: 49, speed: 49, arm: 57, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 55, vsLHP: 52, grit: 57, stealing: 28, running: 48, throwing: 58, recovery: 45, wRISP: 55, vsLefty: 49, poise: 55, heater: 0, agile: 52,
      abilities: ["Contact Hitter"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Owen", lastName: "Burke", position: "OF", eligibility: "FR", homeState: "MO", hometown: "Chesterfield", jerseyNumber: 26,
      hitForAvg: 35, power: 28, speed: 52, arm: 50, fielding: 40, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 33, vsLHP: 31, grit: 35, stealing: 31, running: 50, throwing: 52, recovery: 31, wRISP: 31, vsLefty: 29, poise: 33, heater: 0, agile: 53,
      abilities: ["Resilient", "Magician", "Wide Angle Cannon"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Carter", lastName: "Fields", position: "OF", eligibility: "FR", homeState: "KS", hometown: "Wichita", jerseyNumber: 24,
      hitForAvg: 28, power: 21, speed: 41, arm: 39, fielding: 32, errorResistance: 29, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 26, vsLHP: 24, grit: 28, stealing: 24, running: 39, throwing: 41, recovery: 24, wRISP: 24, vsLefty: 23, poise: 26, heater: 0, agile: 43,
      abilities: ["Consigliere"], potential: "B", catcherAbility: null,
      ...noPitches },
    { firstName: "Marcus", lastName: "Webb", position: "1B", eligibility: "FR", homeState: "MO", hometown: "Ballwin", jerseyNumber: 30,
      hitForAvg: 29, power: 27, speed: 27, arm: 40, fielding: 34, errorResistance: 30, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 27, vsLHP: 26, grit: 29, stealing: 9, running: 26, throwing: 42, recovery: 26, wRISP: 26, vsLefty: 24, poise: 27, heater: 0, agile: 29,
      abilities: ["Good Bunt", "Unrelenting", "Magician"], potential: "B+", catcherAbility: null,
      ...noPitches },
    { firstName: "Austin", lastName: "Reed", position: "C", eligibility: "SO", homeState: "MO", hometown: "Rolla", jerseyNumber: 12,
      hitForAvg: 39, power: 34, speed: 28, arm: 48, fielding: 44, errorResistance: 43, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 39, vsLHP: 35, grit: 42, stealing: 9, running: 27, throwing: 49, recovery: 34, wRISP: 37, vsLefty: 34, poise: 40, heater: 0, agile: 29,
      abilities: ["Artist", "Multi-Hit"], potential: "B", catcherAbility: 44,
      ...noPitches },
    { firstName: "Jake", lastName: "Thornton", position: "OF", eligibility: "JR", homeState: "MO", hometown: "Wentzville", jerseyNumber: 8,
      hitForAvg: 53, power: 46, speed: 53, arm: 58, fielding: 55, errorResistance: 53, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 51, vsLHP: 47, grit: 53, stealing: 33, running: 51, throwing: 61, recovery: 44, wRISP: 50, vsLefty: 46, poise: 51, heater: 0, agile: 55,
      abilities: ["Tough Out", "Resilient"], potential: "B", catcherAbility: null,
      ...noPitches },
  ],

  "Oklahoma": [
      // 30-16/12-12 SEC, D1B #14, BA #9, Skip Johnson Yr 9. Team WHIP 1.28 (21st nation).
      // PITCHERS (10) — 1-8 pitch scale
      // LJ Mercurius — Friday JR RHP (UNLV transfer), 1.91 ERA / 77 K, Team USA, top-20 K nation early — TEAM ELITE STUFF
      { firstName: "LJ", lastName: "Mercurius", position: "P", eligibility: "JR", homeState: "NV", hometown: "Las Vegas", jerseyNumber: 22,
        hitForAvg: 14, power: 11, speed: 38, arm: 80, fielding: 50, errorResistance: 54, velocity: 84, control: 84, stamina: 84, stuff: 90,
        clutch: 80, vsLHP: 76, grit: 80, stealing: 10, running: 34, throwing: 80, recovery: 70, wRISP: 76, vsLefty: 80, poise: 80, heater: 84, agile: 44,
        abilities: ["Star of Victory", "Doctor K", "Sharpness", "Straddle"], potential: "A+", catcherAbility: null,
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...pitchMix(1, [0, 6, 7, 5, 0, 0, 0]) },
      // Cameron Johnson — Saturday LHP JR
      { firstName: "Cameron", lastName: "Johnson", position: "P", eligibility: "JR", homeState: "LA", hometown: "Baton Rouge", jerseyNumber: 33,
        hitForAvg: 14, power: 11, speed: 36, arm: 76, fielding: 46, errorResistance: 48, velocity: 80, control: 70, stamina: 72, stuff: 78,
        clutch: 70, vsLHP: 80, grit: 70, stealing: 10, running: 32, throwing: 74, recovery: 64, wRISP: 64, vsLefty: 80, poise: 70, heater: 80, agile: 42,
        abilities: ["Strong Starter", "Fireman", "Explosive Fastball", "Big Boy Speed"], potential: "A", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [6, 0, 5, 5, 0, 0, 0]) },
      // Cord Rager — Sunday FR LHP, highly regarded prep recruit
      { firstName: "Cord", lastName: "Rager", position: "P", eligibility: "FR", homeState: "TX", hometown: "Austin", jerseyNumber: 34,
        hitForAvg: 11, power: 9, speed: 32, arm: 56, fielding: 32, errorResistance: 34, velocity: 60, control: 46, stamina: 42, stuff: 56,
        clutch: 36, vsLHP: 38, grit: 38, stealing: 10, running: 30, throwing: 54, recovery: 36, wRISP: 36, vsLefty: 40, poise: 36, heater: 60, agile: 36,
        abilities: ["Explosive Fastball"], potential: "A", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [5, 0, 5, 4, 0, 0, 0]) },
      // Jackson Cleveland — closer SR (Miami transfer), 4 SV (3rd SEC, top 25 nation), 14 K in 14.2 IP
      { firstName: "Jackson", lastName: "Cleveland", position: "P", eligibility: "SR", homeState: "FL", hometown: "Miami", jerseyNumber: 25,
        hitForAvg: 13, power: 10, speed: 34, arm: 78, fielding: 44, errorResistance: 46, velocity: 80, control: 76, stamina: 50, stuff: 80,
        clutch: 80, vsLHP: 70, grit: 76, stealing: 9, running: 32, throwing: 76, recovery: 56, wRISP: 80, vsLefty: 70, poise: 80, heater: 80, agile: 40,
        abilities: ["Fireman", "Doctor K", "Inside Pitch", "Iron Arm"], potential: "A", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 7, 0, 5, 0, 4, 0]) },
      // Jason Bodin — JR setup, 28 K in 23.1 IP, 3-1
      { firstName: "Jason", lastName: "Bodin", position: "P", eligibility: "JR", homeState: "OK", hometown: "Norman", jerseyNumber: 28,
        hitForAvg: 13, power: 10, speed: 34, arm: 70, fielding: 42, errorResistance: 44, velocity: 74, control: 70, stamina: 50, stuff: 72,
        clutch: 70, vsLHP: 64, grit: 66, stealing: 9, running: 32, throwing: 68, recovery: 56, wRISP: 64, vsLefty: 60, poise: 70, heater: 74, agile: 40,
        abilities: ["Fireman", "Doctor K", "Big Boy Speed"], potential: "A-", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 0, 5, 0, 4, 0]) },
      // Kadyn Leon — SO middle relief (transfer), 13.1 IP / 2 R / 12 K
      { firstName: "Kadyn", lastName: "Leon", position: "P", eligibility: "FR", homeState: "TX", hometown: "El Paso", jerseyNumber: 36,
        hitForAvg: 12, power: 10, speed: 34, arm: 68, fielding: 42, errorResistance: 44, velocity: 70, control: 68, stamina: 50, stuff: 70,
        clutch: 64, vsLHP: 60, grit: 64, stealing: 9, running: 32, throwing: 66, recovery: 54, wRISP: 60, vsLefty: 58, poise: 64, heater: 70, agile: 40,
        abilities: ["Fireman", "High Spin Gyroball", "Sharpness", "Crossfire"], potential: "A-", catcherAbility: null,
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
      // Michael Catalano — spot starter / long relief, 6 IP at Dallas Baptist
      { firstName: "Michael", lastName: "Catalano", position: "P", eligibility: "JR", homeState: "TX", hometown: "Houston", jerseyNumber: 31,
        hitForAvg: 12, power: 10, speed: 32, arm: 64, fielding: 40, errorResistance: 42, velocity: 66, control: 64, stamina: 64, stuff: 64,
        clutch: 56, vsLHP: 54, grit: 58, stealing: 8, running: 30, throwing: 62, recovery: 56, wRISP: 54, vsLefty: 56, poise: 58, heater: 66, agile: 38,
        abilities: ["Guts", "Doctor K", "Constant Speed", "Crossfire"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
      // Reid Hensley — SR RHP veteran, 23 G/2 GS, 2.94 ERA last yr
      { firstName: "Reid", lastName: "Hensley", position: "P", eligibility: "SR", homeState: "OK", hometown: "Tulsa", jerseyNumber: 29,
        hitForAvg: 13, power: 10, speed: 32, arm: 64, fielding: 40, errorResistance: 42, velocity: 64, control: 66, stamina: 60, stuff: 62,
        clutch: 60, vsLHP: 56, grit: 62, stealing: 8, running: 28, throwing: 62, recovery: 56, wRISP: 58, vsLefty: 60, poise: 62, heater: 64, agile: 36,
        abilities: ["Guts", "Guts", "Quick Hands"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 6, 5, 4, 0, 0, 0]) },
      // Mason Bixby — JR RHP RP
      { firstName: "Mason", lastName: "Bixby", position: "P", eligibility: "JR", homeState: "TX", hometown: "Fort Worth", jerseyNumber: 38,
        hitForAvg: 14, power: 12, speed: 36, arm: 70, fielding: 44, errorResistance: 46, velocity: 72, control: 70, stamina: 70, stuff: 70,
        clutch: 64, vsLHP: 60, grit: 66, stealing: 10, running: 32, throwing: 68, recovery: 60, wRISP: 60, vsLefty: 64, poise: 66, heater: 72, agile: 40,
        abilities: ["Fireman", "True Slider", "Perfect Combustion", "Guts"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 4, 5, 0, 0, 0]) },
      // Jaden Barfield — SO RHP
      { firstName: "Jaden", lastName: "Barfield", position: "P", eligibility: "FR", homeState: "OK", hometown: "Norman", jerseyNumber: 37,
        hitForAvg: 12, power: 9, speed: 34, arm: 62, fielding: 40, errorResistance: 42, velocity: 64, control: 60, stamina: 60, stuff: 62,
        clutch: 54, vsLHP: 52, grit: 56, stealing: 10, running: 30, throwing: 60, recovery: 54, wRISP: 52, vsLefty: 56, poise: 56, heater: 64, agile: 38,
        abilities: ["Straddle", "Decisive"], potential: "A-", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
      // CATCHERS (2)
      // Deiten Lachance — JR C (McLennan JUCO transfer), high-power catching duo
      { firstName: "Deiten", lastName: "Lachance", position: "C", eligibility: "JR", homeState: "FL", hometown: "Orlando", jerseyNumber: 12,
        hitForAvg: 60, power: 60, speed: 34, arm: 60, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 60, vsLHP: 56, grit: 60, stealing: 14, running: 32, throwing: 60, recovery: 46, wRISP: 60, vsLefty: 56, poise: 60, heater: 0, agile: 36,
        abilities: ["Power Hitter", "Consigliere"], potential: "A-", catcherAbility: 56,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Luke Hoffman — SO C backup
      { firstName: "Luke", lastName: "Hoffman", position: "C", eligibility: "FR", homeState: "OK", hometown: "Lawton", jerseyNumber: 19,
        hitForAvg: 42, power: 36, speed: 28, arm: 50, fielding: 46, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 40, vsLHP: 38, grit: 42, stealing: 10, running: 26, throwing: 50, recovery: 34, wRISP: 38, vsLefty: 36, poise: 42, heater: 0, agile: 28,
        abilities: ["Emergency Strength", "Walkoff Hitter"], potential: "B+", catcherAbility: 44,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // INFIELDERS (7)
      // Jaxon Willits — SS JR, ABCA All-Region, .302/9HR, .366/.534/.488 Cape Cod
      { firstName: "Jaxon", lastName: "Willits", position: "SS", eligibility: "JR", homeState: "OK", hometown: "Broken Arrow", jerseyNumber: 6,
        hitForAvg: 76, power: 56, speed: 56, arm: 60, fielding: 64, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 70, vsLHP: 64, grit: 70, stealing: 36, running: 50, throwing: 60, recovery: 46, wRISP: 70, vsLefty: 64, poise: 70, heater: 0, agile: 60,
        abilities: ["Contact Hitter", "Defensive Artisan", "Consigliere"], potential: "A+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Kyle Branch — 2B SO, SEC All-Frosh, started all 60 G as rookie
      { firstName: "Kyle", lastName: "Branch", position: "2B", eligibility: "SO", homeState: "OK", hometown: "Oklahoma City", jerseyNumber: 2,
        hitForAvg: 60, power: 46, speed: 56, arm: 56, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 56, vsLHP: 52, grit: 58, stealing: 38, running: 52, throwing: 56, recovery: 46, wRISP: 56, vsLefty: 50, poise: 56, heater: 0, agile: 56,
        abilities: ["Defensive Artisan", "Chance Maker", "Contact Hitter"], potential: "A", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Dayton Tockey — 1B JR, 7 HRs in 2025
      { firstName: "Dayton", lastName: "Tockey", position: "1B", eligibility: "JR", homeState: "OK", hometown: "Stillwater", jerseyNumber: 18,
        hitForAvg: 56, power: 60, speed: 36, arm: 54, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 60, vsLHP: 56, grit: 60, stealing: 12, running: 36, throwing: 54, recovery: 46, wRISP: 60, vsLefty: 54, poise: 60, heater: 0, agile: 40,
        abilities: ["Power Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Camden Johnson — 3B JR (Wichita St transfer, .325 led team)
      { firstName: "Camden", lastName: "Johnson", position: "3B", eligibility: "JR", homeState: "KS", hometown: "Wichita", jerseyNumber: 10,
        hitForAvg: 64, power: 50, speed: 42, arm: 56, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 60, vsLHP: 54, grit: 60, stealing: 22, running: 40, throwing: 56, recovery: 44, wRISP: 60, vsLefty: 54, poise: 60, heater: 0, agile: 42,
        abilities: ["Contact Hitter", "Power Hitter"], potential: "A-", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Brendan Brock — 1B/DH JR (SW Illinois transfer), high-power catching duo (40+ HR / 175+ RBI combined)
      { firstName: "Brendan", lastName: "Brock", position: "1B", eligibility: "JR", homeState: "OK", hometown: "Moore", jerseyNumber: 24,
        hitForAvg: 56, power: 70, speed: 32, arm: 50, fielding: 46, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 60, vsLHP: 56, grit: 60, stealing: 12, running: 32, throwing: 52, recovery: 40, wRISP: 60, vsLefty: 54, poise: 60, heater: 0, agile: 38,
        abilities: ["Artist", "Power Hitter"], potential: "A-", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Cayden Brumbaugh — SS FR
      { firstName: "Cayden", lastName: "Brumbaugh", position: "SS", eligibility: "FR", homeState: "NE", hometown: "Lincoln", jerseyNumber: 30,
        hitForAvg: 32, power: 26, speed: 44, arm: 44, fielding: 40, errorResistance: 36, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 30, vsLHP: 28, grit: 32, stealing: 26, running: 40, throwing: 46, recovery: 28, wRISP: 28, vsLefty: 28, poise: 30, heater: 0, agile: 44,
        abilities: ["Line Drive", "vs. Ace"], potential: "A-", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Marcus Pruitt — 2B JR utility
      { firstName: "Marcus", lastName: "Pruitt", position: "2B", eligibility: "JR", homeState: "OK", hometown: "Tulsa", jerseyNumber: 14,
        hitForAvg: 36, power: 28, speed: 34, arm: 40, fielding: 40, errorResistance: 38, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 36, vsLHP: 32, grit: 36, stealing: 20, running: 32, throwing: 40, recovery: 30, wRISP: 34, vsLefty: 32, poise: 36, heater: 0, agile: 36,
        abilities: ["Hit Machine"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // OUTFIELDERS (6)
      // Trey Gambill — OF JR, 2nd SEC OBP (.519) in conf, T-7 SEC doubles
      { firstName: "Trey", lastName: "Gambill", position: "OF", eligibility: "JR", homeState: "OK", hometown: "Norman", jerseyNumber: 1,
        hitForAvg: 76, power: 50, speed: 56, arm: 50, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 70, vsLHP: 64, grit: 70, stealing: 36, running: 50, throwing: 52, recovery: 42, wRISP: 70, vsLefty: 64, poise: 70, heater: 0, agile: 56,
        abilities: ["Chance Maker", "Contact Hitter", "Express Baserunning"], potential: "A", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Jason Walk — OF JR, 15+ XBH, 100+ starts in 2025
      { firstName: "Jason", lastName: "Walk", position: "OF", eligibility: "JR", homeState: "OK", hometown: "Edmond", jerseyNumber: 7,
        hitForAvg: 60, power: 56, speed: 60, arm: 60, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 60, vsLHP: 54, grit: 60, stealing: 40, running: 56, throwing: 60, recovery: 46, wRISP: 56, vsLefty: 50, poise: 60, heater: 0, agile: 60,
        abilities: ["Express Baserunning", "Power Hitter"], potential: "A-", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Drew Dickerson — OF SO
      { firstName: "Drew", lastName: "Dickerson", position: "OF", eligibility: "SO", homeState: "OK", hometown: "Tulsa", jerseyNumber: 9,
        hitForAvg: 52, power: 50, speed: 52, arm: 56, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 56, vsLHP: 50, grit: 58, stealing: 32, running: 50, throwing: 58, recovery: 44, wRISP: 56, vsLefty: 48, poise: 56, heater: 0, agile: 52,
        abilities: ["Consigliere"], potential: "A-", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Grant Ellis — OF JR
      { firstName: "Grant", lastName: "Ellis", position: "OF", eligibility: "JR", homeState: "TX", hometown: "Plano", jerseyNumber: 11,
        hitForAvg: 50, power: 44, speed: 48, arm: 56, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 50, vsLHP: 46, grit: 50, stealing: 28, running: 46, throwing: 58, recovery: 42, wRISP: 48, vsLefty: 44, poise: 50, heater: 0, agile: 48,
        abilities: ["High-Speed Laser"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Tyler Owens — OF JR
      { firstName: "Tyler", lastName: "Owens", position: "OF", eligibility: "JR", homeState: "TX", hometown: "Lubbock", jerseyNumber: 3,
        hitForAvg: 54, power: 48, speed: 54, arm: 58, fielding: 54, errorResistance: 52, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 54, vsLHP: 50, grit: 54, stealing: 34, running: 52, throwing: 60, recovery: 44, wRISP: 52, vsLefty: 48, poise: 54, heater: 0, agile: 54,
        abilities: ["Heavy Tank", "High Ball Hitter"], potential: "B+", catcherAbility: null,
        skinTone: "light", hairColor: "brown", hairStyle: "short",
        ...noPitches },
      // Ryan Torres — OF SO
      { firstName: "Ryan", lastName: "Torres", position: "OF", eligibility: "SO", homeState: "OK", hometown: "Norman", jerseyNumber: 16,
        hitForAvg: 34, power: 30, speed: 36, arm: 38, fielding: 36, errorResistance: 34, velocity: 0, control: 0, stamina: 0, stuff: 0,
        clutch: 32, vsLHP: 30, grit: 34, stealing: 22, running: 34, throwing: 38, recovery: 28, wRISP: 30, vsLefty: 28, poise: 32, heater: 0, agile: 36,
        abilities: ["Pull Hitter", "High-Speed Laser"], potential: "B+", catcherAbility: null,
        skinTone: "tan", hairColor: "black", hairStyle: "short",
        ...noPitches },
    ],

  // Texas — 35-10 / 15-8 SEC, D1Baseball #4 (May 3, 2026), Schlossnagle Yr 2, RPI #3
  // Team ERA 1.71 (best in SEC early), 0.94 WHIP, .161 OBA. Defending SEC reg-season champ
  "Texas": [
    // PITCHERS (10) — staff: "the stuff on this staff is not fair"
    // Dylan Volantis — SO LHP, ELITE 6'6" sweeping knuckle curve, FR yr: 4-1/1.94/12 SV/74K, BA Frosh of Year, moved closer→Sun starter
    { firstName: "Dylan", lastName: "Volantis", position: "P", eligibility: "FR", homeState: "TX", hometown: "Austin", jerseyNumber: 29,
      hitForAvg: 14, power: 11, speed: 42, arm: 88, fielding: 56, errorResistance: 60, velocity: 88, control: 80, stamina: 64, stuff: 92,
      clutch: 86, vsLHP: 80, grit: 86, stealing: 8, running: 36, throwing: 84, recovery: 64, wRISP: 84, vsLefty: 82, poise: 84, heater: 84, agile: 50,
      abilities: ["Star of Victory", "Doctor K", "Sharpness", "Halting Quickness", "Lefty Killer", "Natural Shuuto"], potential: "A+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "medium",
      ...pitchMix(1, [5, 5, 7, 4, 0, 0, 0]) },
    // Ruger Riojas — Friday RHP SR, 5.61 ERA last yr (illness mid-season), bullpen vet capable of starts
    { firstName: "Ruger", lastName: "Riojas", position: "P", eligibility: "SR", homeState: "TX", hometown: "San Antonio", jerseyNumber: 34,
      hitForAvg: 13, power: 10, speed: 32, arm: 76, fielding: 46, errorResistance: 50, velocity: 80, control: 70, stamina: 70, stuff: 78,
      clutch: 70, vsLHP: 66, grit: 74, stealing: 7, running: 30, throwing: 74, recovery: 64, wRISP: 66, vsLefty: 70, poise: 72, heater: 76, agile: 40,
      abilities: ["Strong Starter", "Guts", "Bad Ball Hitter"], potential: "B+", catcherAbility: null,
      skinTone: "tan", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 5, 5, 5, 0, 0, 0]) },
    // Luke Harrison — Saturday LHP GR, 3.07 / 70.2 IP / 15 GS post-TJ, workhorse
    { firstName: "Luke", lastName: "Harrison", position: "P", eligibility: "SR", homeState: "TX", hometown: "Houston", jerseyNumber: 22,
      hitForAvg: 12, power: 10, speed: 30, arm: 70, fielding: 44, errorResistance: 48, velocity: 70, control: 76, stamina: 76, stuff: 72,
      clutch: 70, vsLHP: 80, grit: 78, stealing: 7, running: 28, throwing: 68, recovery: 70, wRISP: 66, vsLefty: 80, poise: 74, heater: 64, agile: 38,
      abilities: ["Strong Starter", "Guts", "Fireman"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [4, 4, 6, 5, 0, 0, 0]) },
    // Thomas Burns — closer JR RHP, hard-throwing
    { firstName: "Thomas", lastName: "Burns", position: "P", eligibility: "JR", homeState: "TX", hometown: "Fort Worth", jerseyNumber: 38,
      hitForAvg: 11, power: 9, speed: 34, arm: 78, fielding: 42, errorResistance: 46, velocity: 84, control: 68, stamina: 36, stuff: 78,
      clutch: 76, vsLHP: 70, grit: 72, stealing: 7, running: 30, throwing: 76, recovery: 56, wRISP: 74, vsLefty: 70, poise: 76, heater: 80, agile: 42,
      abilities: ["Fireman", "Doctor K", "Explosive Fastball", "Low Ball", "Heavy Ball"], potential: "A-", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 6, 5, 4, 0, 0, 0]) },
    // Max Grubbs — RHP SR setup, 2.84 ERA / 57 IP last yr
    { firstName: "Max", lastName: "Grubbs", position: "P", eligibility: "SR", homeState: "TX", hometown: "Frisco", jerseyNumber: 48,
      hitForAvg: 11, power: 9, speed: 32, arm: 70, fielding: 42, errorResistance: 46, velocity: 74, control: 70, stamina: 50, stuff: 70,
      clutch: 70, vsLHP: 66, grit: 72, stealing: 7, running: 28, throwing: 68, recovery: 56, wRISP: 66, vsLefty: 68, poise: 70, heater: 70, agile: 38,
      abilities: ["Fireman", "Inside Pitch", "Guts", "Monster Stuff"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 5, 4, 4, 0, 0, 0]) },
    // Sam Cozart — FR RHP midweek SP, 18K in 3 GS / 5 H / 2 ER — elite freshman
    { firstName: "Sam", lastName: "Cozart", position: "P", eligibility: "FR", homeState: "TX", hometown: "Round Rock", jerseyNumber: 46,
      hitForAvg: 10, power: 8, speed: 32, arm: 68, fielding: 38, errorResistance: 42, velocity: 70, control: 64, stamina: 50, stuff: 72,
      clutch: 56, vsLHP: 52, grit: 56, stealing: 7, running: 28, throwing: 66, recovery: 50, wRISP: 54, vsLefty: 56, poise: 56, heater: 66, agile: 40,
      abilities: ["Strong Starter", "Doctor K"], potential: "A+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 5, 5, 4, 0, 0, 0]) },
    // Haiden Leffew — LHP transfer Wake Forest, situational
    { firstName: "Haiden", lastName: "Leffew", position: "P", eligibility: "JR", homeState: "NC", hometown: "Charlotte", jerseyNumber: 33,
      hitForAvg: 11, power: 9, speed: 30, arm: 64, fielding: 40, errorResistance: 42, velocity: 64, control: 66, stamina: 40, stuff: 64,
      clutch: 56, vsLHP: 70, grit: 60, stealing: 6, running: 26, throwing: 62, recovery: 50, wRISP: 56, vsLefty: 70, poise: 60, heater: 60, agile: 38,
      abilities: ["Fireman", "Crossfire"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 5, 3, 0, 0, 0]) },
    // Ethan Walker — LHP sidearm, late-season key in 2025 (SEC tourney start, NCAA opener)
    { firstName: "Ethan", lastName: "Walker", position: "P", eligibility: "JR", homeState: "TX", hometown: "Austin", jerseyNumber: 37,
      hitForAvg: 10, power: 8, speed: 30, arm: 60, fielding: 38, errorResistance: 42, velocity: 60, control: 64, stamina: 36, stuff: 64,
      clutch: 60, vsLHP: 72, grit: 60, stealing: 6, running: 26, throwing: 60, recovery: 46, wRISP: 56, vsLefty: 72, poise: 60, heater: 56, agile: 38,
      abilities: ["Fireman", "Inside Pitch"], potential: "B", catcherAbility: null,
      skinTone: "light", hairColor: "blonde", hairStyle: "short",
      ...pitchMix(1, [0, 4, 4, 4, 0, 0, 0]) },
    // Kade Bing — LHP RP strike-thrower
    { firstName: "Kade", lastName: "Bing", position: "P", eligibility: "JR", homeState: "TX", hometown: "Lubbock", jerseyNumber: 42,
      hitForAvg: 10, power: 8, speed: 28, arm: 56, fielding: 36, errorResistance: 40, velocity: 60, control: 70, stamina: 36, stuff: 58,
      clutch: 56, vsLHP: 66, grit: 60, stealing: 6, running: 25, throwing: 56, recovery: 44, wRISP: 54, vsLefty: 66, poise: 58, heater: 56, agile: 36,
      abilities: ["Inside Pitch", "Inside Pitch", "Good Pickoff"], potential: "B", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 4, 3, 0, 0, 0]) },
    // Cal Higgins — RHP transfer
    { firstName: "Cal", lastName: "Higgins", position: "P", eligibility: "SR", homeState: "TX", hometown: "Houston", jerseyNumber: 40,
      hitForAvg: 10, power: 8, speed: 28, arm: 60, fielding: 38, errorResistance: 40, velocity: 64, control: 60, stamina: 36, stuff: 60,
      clutch: 50, vsLHP: 48, grit: 52, stealing: 6, running: 26, throwing: 58, recovery: 44, wRISP: 48, vsLefty: 50, poise: 52, heater: 60, agile: 34,
      abilities: ["Crossfire"], potential: "B", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...pitchMix(1, [0, 4, 3, 3, 0, 0, 0]) },
    // CATCHERS (2)
    // Carson Tinney — JR C transfer Notre Dame, 14 HR (#2 team), 2025 Buster Posey finalist, 445-ft HR
    { firstName: "Carson", lastName: "Tinney", position: "C", eligibility: "JR", homeState: "IN", hometown: "South Bend", jerseyNumber: 19,
      hitForAvg: 70, power: 80, speed: 32, arm: 68, fielding: 70, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 78, vsLHP: 72, grit: 76, stealing: 8, running: 30, throwing: 70, recovery: 56, wRISP: 78, vsLefty: 72, poise: 76, heater: 0, agile: 38,
      abilities: ["Power Hitter", "Consigliere", "High-Speed Laser"], potential: "A", catcherAbility: 70,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Chase Porter — SO backup C
    { firstName: "Chase", lastName: "Porter", position: "C", eligibility: "FR", homeState: "TX", hometown: "Cypress", jerseyNumber: 16,
      hitForAvg: 36, power: 32, speed: 28, arm: 50, fielding: 46, errorResistance: 44, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 36, vsLHP: 34, grit: 38, stealing: 8, running: 26, throwing: 50, recovery: 32, wRISP: 34, vsLefty: 32, poise: 36, heater: 0, agile: 30,
      abilities: ["Artist", "Unpredictable", "Good Bunt"], potential: "B+", catcherAbility: 46,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // INFIELDERS (6)
    // Casey Borba — JR 1B, .278/12HR 2025, multi-HR effort early '26, 5 RBI vs TXST
    { firstName: "Casey", lastName: "Borba", position: "1B", eligibility: "JR", homeState: "CA", hometown: "Sacramento", jerseyNumber: 45,
      hitForAvg: 64, power: 70, speed: 30, arm: 50, fielding: 58, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 68, vsLHP: 64, grit: 68, stealing: 8, running: 30, throwing: 50, recovery: 50, wRISP: 70, vsLefty: 62, poise: 66, heater: 0, agile: 36,
      abilities: ["Power Hitter", "Consigliere"], potential: "A-", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Ethan Mendoza — SO 2B, .333 in 2025 team-leader, returning star, +15 lbs offseason
    { firstName: "Ethan", lastName: "Mendoza", position: "2B", eligibility: "SO", homeState: "TX", hometown: "El Paso", jerseyNumber: 2,
      hitForAvg: 76, power: 56, speed: 56, arm: 56, fielding: 70, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 72, vsLHP: 66, grit: 76, stealing: 28, running: 50, throwing: 58, recovery: 56, wRISP: 74, vsLefty: 64, poise: 72, heater: 0, agile: 56,
      abilities: ["Contact Hitter", "Chance Maker", "Defensive Artisan"], potential: "A", catcherAbility: null,
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Adrian Rodriguez — SO SS (moved from util), 2 HR/9 RBI, 2025 Frosh All-American, hand injury
    { firstName: "Adrian", lastName: "Rodriguez", position: "SS", eligibility: "SO", homeState: "TX", hometown: "Flower Mound", jerseyNumber: 6,
      hitForAvg: 70, power: 56, speed: 60, arm: 64, fielding: 72, errorResistance: 66, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 60, grit: 70, stealing: 30, running: 56, throwing: 66, recovery: 50, wRISP: 64, vsLefty: 58, poise: 66, heater: 0, agile: 64,
      abilities: ["Defensive Artisan", "Contact Hitter", "Express Baserunning"], potential: "A", catcherAbility: null,
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Temo Becerra — JR 3B Stanford transfer, .314 career, 115 starts
    { firstName: "Temo", lastName: "Becerra", position: "3B", eligibility: "JR", homeState: "CA", hometown: "San Jose", jerseyNumber: 10,
      hitForAvg: 72, power: 60, speed: 50, arm: 66, fielding: 68, errorResistance: 64, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 66, vsLHP: 64, grit: 70, stealing: 16, running: 44, throwing: 66, recovery: 52, wRISP: 66, vsLefty: 60, poise: 66, heater: 0, agile: 46,
      abilities: ["Contact Hitter", "Defensive Artisan", "Inside Hitter"], potential: "A-", catcherAbility: null,
      skinTone: "tan", hairColor: "black", hairStyle: "short",
      ...noPitches },
    // Josh Livingston — JR Wichita State transfer, 15 HR last year (team-leading), DH/util
    { firstName: "Josh", lastName: "Livingston", position: "3B", eligibility: "JR", homeState: "KS", hometown: "Wichita", jerseyNumber: 20,
      hitForAvg: 56, power: 70, speed: 30, arm: 50, fielding: 50, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 64, stealing: 8, running: 30, throwing: 50, recovery: 44, wRISP: 60, vsLefty: 54, poise: 58, heater: 0, agile: 36,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Callum Early — FR INF Liberty transfer, depth
    { firstName: "Callum", lastName: "Early", position: "2B", eligibility: "FR", homeState: "TX", hometown: "Plano", jerseyNumber: 24,
      hitForAvg: 38, power: 30, speed: 50, arm: 48, fielding: 46, errorResistance: 42, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 36, vsLHP: 34, grit: 38, stealing: 26, running: 46, throwing: 48, recovery: 34, wRISP: 34, vsLefty: 32, poise: 36, heater: 0, agile: 50,
      abilities: ["High Ball Hitter", "Chance Maker"], potential: "A-", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // OUTFIELDERS (7)
    // Aiden Robbins — JR CF/OF Seton Hall transfer, .358/17HR (TEAM LEADER), 200th career hit, 112mph max EV, top-50 draft
    { firstName: "Aiden", lastName: "Robbins", position: "OF", eligibility: "JR", homeState: "NJ", hometown: "South Orange", jerseyNumber: 1,
      hitForAvg: 84, power: 86, speed: 56, arm: 64, fielding: 64, errorResistance: 60, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 86, vsLHP: 80, grit: 80, stealing: 20, running: 50, throwing: 66, recovery: 56, wRISP: 86, vsLefty: 80, poise: 84, heater: 0, agile: 56,
      abilities: ["Artist", "Power Hitter", "Consigliere"], potential: "A+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Jonah Williams — SO OF, speed/leadoff
    { firstName: "Jonah", lastName: "Williams", position: "OF", eligibility: "SO", homeState: "TX", hometown: "Austin", jerseyNumber: 7,
      hitForAvg: 56, power: 44, speed: 76, arm: 56, fielding: 60, errorResistance: 56, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 48, grit: 58, stealing: 56, running: 70, throwing: 60, recovery: 46, wRISP: 50, vsLefty: 46, poise: 54, heater: 0, agile: 76,
      abilities: ["Express Baserunning", "Chance Maker"], potential: "A-", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Ashton Larson — JR OF LSU transfer
    { firstName: "Ashton", lastName: "Larson", position: "OF", eligibility: "JR", homeState: "LA", hometown: "Baton Rouge", jerseyNumber: 9,
      hitForAvg: 56, power: 46, speed: 50, arm: 54, fielding: 54, errorResistance: 50, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 54, vsLHP: 48, grit: 56, stealing: 26, running: 48, throwing: 54, recovery: 44, wRISP: 54, vsLefty: 48, poise: 54, heater: 0, agile: 50,
      abilities: ["Contact Hitter"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Jack Moroknek — JR OF Butler transfer, replacing Belyeu in RF
    { firstName: "Jack", lastName: "Moroknek", position: "OF", eligibility: "JR", homeState: "IN", hometown: "Indianapolis", jerseyNumber: 23,
      hitForAvg: 60, power: 56, speed: 48, arm: 56, fielding: 56, errorResistance: 54, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 60, vsLHP: 56, grit: 60, stealing: 18, running: 46, throwing: 56, recovery: 46, wRISP: 60, vsLefty: 54, poise: 60, heater: 0, agile: 48,
      abilities: ["Power Hitter"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
    // Dariyan Pendergrass — JR OF Charleston transfer, speed
    { firstName: "Dariyan", lastName: "Pendergrass", position: "OF", eligibility: "JR", homeState: "SC", hometown: "Charleston", jerseyNumber: 3,
      hitForAvg: 46, power: 36, speed: 70, arm: 50, fielding: 50, errorResistance: 48, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 40, grit: 46, stealing: 50, running: 64, throwing: 50, recovery: 38, wRISP: 42, vsLefty: 40, poise: 44, heater: 0, agile: 70,
      abilities: ["Express Baserunning"], potential: "B+", catcherAbility: null,
      skinTone: "deep", hairColor: "black", hairStyle: "fade",
      ...noPitches },
    // Anthony Pack Jr — FR OF speed
    { firstName: "Anthony", lastName: "Pack Jr", position: "OF", eligibility: "FR", homeState: "CA", hometown: "Los Angeles", jerseyNumber: 26,
      hitForAvg: 32, power: 28, speed: 56, arm: 40, fielding: 36, errorResistance: 32, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 30, vsLHP: 28, grit: 32, stealing: 36, running: 50, throwing: 42, recovery: 28, wRISP: 28, vsLefty: 26, poise: 30, heater: 0, agile: 56,
      abilities: ["Express Baserunning"], potential: "A+", catcherAbility: null,
      skinTone: "deep", hairColor: "black", hairStyle: "fade",
      ...noPitches },
    // Miles Bennett — JR OF depth, cannon arm
    { firstName: "Miles", lastName: "Bennett", position: "OF", eligibility: "JR", homeState: "TX", hometown: "The Woodlands", jerseyNumber: 11,
      hitForAvg: 44, power: 38, speed: 44, arm: 60, fielding: 48, errorResistance: 46, velocity: 0, control: 0, stamina: 0, stuff: 0,
      clutch: 44, vsLHP: 40, grit: 46, stealing: 22, running: 42, throwing: 60, recovery: 38, wRISP: 42, vsLefty: 38, poise: 44, heater: 0, agile: 46,
      abilities: ["High-Speed Laser"], potential: "B+", catcherAbility: null,
      skinTone: "light", hairColor: "brown", hairStyle: "short",
      ...noPitches },
  ],
};
