// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/recruiting-ui/HybridRetroModern.tsx": () => import("../components/mockups/recruiting-ui/HybridRetroModern.tsx"),
  "./components/mockups/recruiting-ui/ModernDashboard.tsx": () => import("../components/mockups/recruiting-ui/ModernDashboard.tsx")
};
